### PR TITLE
Update boost to 1.62

### PR DESCRIPTION
**Pull request by drwells**
This large commit updates us to the most recent version of boost (released in late September). Things seem OK with GCC 4.4.7, GCC 4.8.5, Clang 3.8, GCC 6.1, and GCC 6.2 (I ran either large parts of or all of the test suite without any new failures).

It looks like we gained about 600 new files in boost. I tried to not include any new top level headers that we did not use but this could probably be further optimized.

I ported our applicable boost patches for getting rid of warnings. The library builds cleanly except for known spurious warnings for 4.4.7. I don't have any way to test the MSVC patches so I skipped all of them (I think that newer versions of boost do better with MSVC: I think every patch we used is now in boost).

I am not sure how rigorously the boost people test their stuff against older Intel or Microsoft compilers so I would be really happy if someone would try this branch out with one of those :smile: I also did not test this on Debian or macOS so it would be nice for people to check things there too.

Addresses #3086.

Related to this: I would like to bump the minimal required boost version to 1.59 since (as mentioned elsewhere) `small_vector` was added in 1.58 and I want to use it (but 1.58 has bad serialization bugs). Thoughts?

### CODE REVIEW

**Comment by drwells** [comment]
I went back and removed some folders of headers that we do not use either directly or indirectly: we are now down to about 350 new headers. Most of the new stuff is either in the thread, spirit, or fusion libraries so I don't think we can get this much lower.

I noticed that we bundle `boost/numerics` but we don't ever use it. If we get rid of this library then we can also remove `boost/multi_array` and `boost/units`. Thoughts?

**Comment by kronbichler** [comment]
@drwells What is the functionality provided by `boost/numerics` - or do you mean `boost/numeric`? I had a quick look and the contents appear to be:
- some ode integrators: could be interesting, but I never checked what they offer
- interval analysis: remotely interesting in our context
- unit conversion: remotely interesting
- ublas: remotely interesting

All these features do not seem to be vital to deal.II also for the next years, so I'd skip them. Does anybody know of anyone using the numeric headers in a user code?

**Comment by drwells** [comment]
@kronbichler Yes, that was a typo (I meant `boost/numeric`).

It looks like @Rombur is using it in [ORNL-CEES/Cap](https://github.com/ORNL-CEES/Cap). I did not see any other projects that did while quickly flipping through all of the deal.II projects on GitHub that I starred.

**Comment by bangerth** [comment]
I think we used `boost/numeric` in some project, but I don't recall where. It's probably not important any more. It is, however, no longer backward compatible if you remove it when it was there before.

Have you tried to measure the number of megabytes we had in the `contrib/boost` directory before and after your patch? If the difference is not huge, then it may not be worth worrying too much.

**Comment by drwells** [comment]
Good point. I am in favor of keeping it for backwards compatibility.

on `master`:
```
[drwells@archway boost-1.56.0]$ du -h --max-depth=1 ./
436K    ./libs
74M     ./include
75M     ./
```

on `update-boost-1.62`:
```
[drwells@archway boost-1.62.0]$ du -h --max-depth=1 ./
452K    ./libs
82M     ./include
82M     ./
```

and it looks like 5 MB of that comes from updates to `fusion`, which we need.

**Comment by bangerth** [comment]
This seems to me like a totally reasonable increase. Given that you've tested the heck out of it, I'm in favor of merging, but I'll give others time to chime in.

**Comment by drwells** [comment]
Since the boost people don't test against any intel compiler older than 16 I would appreciate it if someone would try things out with whatever older version they have available.

**Comment by kronbichler** [comment]
I'm fine with keeping `numeric` and its dependencies in, given that we had it before and the increase in size is modest. @drwells would you mind squashing/finalizing your commits?

I only have Intel 16 so I cannot easily test the older versions, I'm sorry.

**Comment by drwells** [comment]
I squashed things a bit (from eleven to six commits). I want to leave an explicit commit showing which boost libraries we remove so I think the current history is right.

**Comment by tjhei** [comment]
> I want to leave an explicit commit showing which boost libraries we remove so I think the current history is right.

Hrm, that would mean they are still part of the history blowing up the repo. I am not sure if that matters much, but I thought I would mention it.

**Comment by Rombur** [comment]
There is a bug in cmake 3.6.0 and 3.6.1 which don't recognize boost 1.62 see https://groups.google.com/forum/#!msg/votca/hW3EnwDfez0/MWYYS9VJBQAJ This should be fixed with cmake 3.6.2 https://gitlab.kitware.com/cmake/cmake/commit/a997cac8323dc1764e092b8691857dd9af70956e For me it works fine except that I get a lot of warnings. I think it's fine to bundle boost 1.62 but I just wanted to let you know about this bug.

**Comment by drwells** [comment]
@tjhei What do you mean by 'blowing up the repo'? I don't feel strongly about the history so I can squash things down more if you think that is better.

**Comment by drwells** [comment]
@Rombur That's a good point. I am surprised that things work with 3.5.2 but not those versions. Are any distributions shipping 3.6.0 or 3.6.1?

**Comment by Rombur** [comment]
@drwells I don't know but it works fine for ubuntu. I just wanted everybody to be aware of this in case we get the question on the mailing list.

**Comment by tjhei** [comment]
> @tjhei What do you mean by 'blowing up the repo'?

increasing the total size of the repository and as such slowing down initial clones and taking more disc space.

**Comment by tamiko** [comment]
@drwells 
What about you squash these commits and simply annotate in the commit what you removed?

**Comment by drwells** [comment]
Sure. I now just list the removed libraries in a commit message.

**Comment by drwells** [comment]
It turns out that this change causes one new test failure in C++03 mode: I pushed another commit to fix this.

**Comment by bangerth** [comment]
I suspect that the last commit is independent of boost, right? If so, feel free to cherry-pick it for a separate PR. (No need to remove it from here -- git will get this case right I think.)

**Comment by drwells** [comment]
The boost change causes that test to fail (though the library compiles just fine) so (matter of interpretation) I would say it does depend on boost.

**Comment by bangerth** [comment]
OK, no worries. 

What is missing from this, or can it be merged? I think that the best way to get it tested more broadly is to just merge it and see what everyone finds...

**Comment by kronbichler** [comment]
I agree that this is ready for merging now. I let someone else pull the trigger. ;-)

**Comment by bangerth** [comment]
I gots tha guts to do it!

**Comment by bangerth** [comment]
For the record, everything compiles cleanly with my VERY old gcc 4.4.7.

**Comment by drwells** [comment]
@bangerth Did you not get any of the 'this code breaks strict aliasing' warnings? I got a lot of those when I compiled with 4.4.7 (they don't do anything and the warnings have long since been fixed in GCC).

**Comment by drwells** [comment]
(For what it is worth, GCC 4.4.7, when compiling boost 1.56, prints out the same warning for different reasons)

**Comment by bangerth** [comment]
Yes, dozens or hundreds. I've learned to just ignore them.

**Comment by bangerth** [comment]
And yes, correct -- no difference to 1.56.

**Pull request merged**
