### PR TITLE
Dealii 8.3

### PR DESCRIPTION
**Pull request by ArielPino**
Suggested modification and elimination of the word "obvius"  from a tutorial.

### CODE REVIEW

**Comment by tjhei** [comment]
Please talk to Matthias, Wolfgang, or me. You based your changes on delaii-8.3 and not on the latest development version.

**Comment by ArielPino** [comment]
Ooops! I just updated my copy. Thanks for pointing it out

**Comment by bangerth** [comment]
Can you point to the commit (in the list above) where you fixed the typo? I'd like to rescue the work you did :-)

**Comment by ArielPino** [comment]
Unfortunately, I can´t (not sure about how to do it). However, It was not a typo, but a "style" suggestion that is irrelevant for the understanding of step 15. Therefore, I would leave it there.

**Pull request closed without merging**
