### PR TITLE
Bugfix: Do not test for inclusion of config.h in header tests

### PR DESCRIPTION
**Pull request by tamiko**
It turns out that sometimes [1] the testsuite picks up <code>revision.h</code> (and <code>config.h</code>) as well.

<code>revision.h</code> does not include <code>config.h</code> and the test subsequently fails with the <code>DEAL_II_NAMESPACE_*</code> not being found. I think the - by far - easiest option is to just remove this additional check from the header tests and leave the current pickup logic as it is.

[1] For an in-source build and if an installed deal.II is tested.

### CODE REVIEW

**Comment by tamiko** [comment]
This is an optional candidate for rc2.

**Comment by tjhei** [comment]
Agreed, not high priority for 8.3.

We originally had the ```DEAL_II_NAMESPACE_``` stuff in there to make sure that every header includes config.h?

**Comment by tjhei** [comment]
Would it make sense to do something like this instead:
```
#if !defined(DEAL_II_NAMESPACE_OPEN) && HEADER!="revision.h"
#error "HEADER does not include config.h."
#endif
```

**Comment by tamiko** [comment]
@tjhei I pushed a simplified version to the pr.

**Comment by tjhei** [comment]
Great. Did you check that the header tests are all passing now?

**Comment by bangerth** [comment]
Why not just let `revision.h` include `config.h`? We enforce that every header file includes `config.h` as the first include anyway, I don't see why we shouldn't do the same for this one.

**Comment by tamiko** [comment]
@tjhei : Sure.

@bangerth : I decided against the inclusion <code>config.h</code> in <code>revision.h</code> because it is not needed. The latter only declares 3 preprocessor macros.

**Comment by tjhei** [comment]
I see some value in keeping revision.h as simple as possible.

**Pull request merged**
