### PR TITLE
Replace present_index by index() in DoFAccessor

### PR DESCRIPTION
**Pull request by peterrum**
fixes the problem described in https://groups.google.com/g/dealii/c/Sk5U82Zyd6s

@rezarastak Would you be willing to convert your program to a test?

### CODE REVIEW

**Comment by rezarastak** [comment]
Thanks for starting this PR. Yes I can add a test. I will submit a separate PR with the test in the next couple of days.

**Comment by bangerth** [comment]
OK to merge once we have a patch!

**Comment by rezarastak** [comment]
Is it possible to back-port this bug fix to the 9.3 release?

**Review by kronbichler — APPROVED** [review]

**Comment by bangerth** [comment]
@rezarastak I'm not sure we will have another 9.3 release, but feel free to propose a patch against the 9.3 release branch.

**Pull request merged**
