### PR TITLE
Better document VectorTools::create_point_source_vector().

### PR DESCRIPTION
**Pull request by bangerth**
Motivated by a discussion on the mailing list.

### CODE REVIEW

**Comment by bangerth** [comment]
I didn't want to get into the interpretation of what the interpretation is other than that it's a force term. In practice, point charges also don't exist, of course (although electrons are, even in the QED formulation, pretty darn small :-).

**Comment by davydden** [comment]
I understand that, I just thought it could give a user with less math. background an example of the solution that one could visualize and convince oneself that it can not be well approximated by polynomials. But I don't feel strong about it.

**Comment by bangerth** [comment]
Fair enough. I've updated the text.

**Comment by masterleinad** [comment]
Would you mind to also clarify that the functions only taking a `const Point<spacedim> &p` parameter are only implemented for scalar valued finite elements, while the functions taking an extra `const Point<dim> &orientation` parameter are only implemented if the number of components matches the dimension?
At least this is what we test in the source code.

**Comment by bangerth** [comment]
I added a sentence about the requirement that the element needs to be scalar.

**Comment by masterleinad** [comment]
@bangerth Thanks!

**Pull request merged**
