### PR TITLE
Add Jupyter Notebook

### LINKED ISSUE #5573: Jupyter notebook
I have started working on a Jupyter notebook that shows how to use the python wrappers (see [here](https://github.com/Rombur/dealii/blob/notebook/contrib/python-bindings/notebooks/tutorial.ipynb)). But I am wondering where it should go. For now, I have put it in `/contrib/python-bindings/notebooks/` because it is not a C++ tutorial but I don't know how to make it visible from `dealii.org` or maybe we can just link to the github page directly. Github knows how to render jupyter notebook and I don't think it is trivial to move a notebook to html. I would also like your opinion on whether the notebook should contains the executed code or not. The current notebook contains it which is nice if you want to read it like a tutorial but there is also no point in running the notebook.

### PR DESCRIPTION
**Pull request by Rombur**
Click on the `View` button to see the rendered notebook. 

I don't know where I should add the link to the index notebook. From the the tutorial page?

closes #5573

### CODE REVIEW

**Comment by drwells** [comment]
The link to `tutorial-1` is broken in the GitHub render; is this a problem on their end?

**Comment by Rombur** [comment]
> The link to tutorial-1 is broken in the GitHub render; is this a problem on their end?

No, it will work only after we merge the PR. The link sends you to the address where the tutorial will (?) be once it is merged into master.

**Comment by tjhei** [comment]
very nice!

two suggestions (maybe for the future):
1. rendering the grid lines instead of colored patches is probably more readable.
2. 
You are code like
```
def mat_id_color_sc(cell_id, cell):
    return cell.material_id
```
This would be neater using a lambda ``lambda cell_id, cell: cell.material_id``, which you can put directly into the ``plot_triangulation`` call.

**Comment by Rombur** [comment]
> rendering the grid lines instead of colored patches is probably more readable

I know but for some reasons matplotlib refused to show the grid lines. I have no idea why it doesn't work :disappointed: 

> This would be neater using a lambda

Good idea! I didn't think about that.

**Comment by davydden** [comment]
@tjhei do you have further comments, or can we merge this?

**Pull request merged**
