### PR TITLE
Use ReferenceCell::closest_point() in GridTools::find_active_cell_around_point().

### PR DESCRIPTION
**Pull request by drwells**
Followup to #15218: using the infinity norm won't work correctly with simplices.

### CODE REVIEW

**Review by peterrum — COMMENTED** [review]
Nice! Could you add a test? Next step: generalization of `find_all_active_cells_around_point()` :)

**Comment by drwells** [comment]
I thought we already had a test for this function with simplices - guess not. Now we do!

**Review by peterrum — APPROVED** [review]

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
This fails the following test:
```
119/120 Test #111: simplex/step-68.mpirun=4.debug ................................................***Failed    1.43 sec
gmake[3]: *** [CMakeFiles/simplex.step-68.mpirun4.debug.test.dir/build.make:83: step-68.debug/mpirun=4/output] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:5788: CMakeFiles/simplex.step-68.mpirun4.debug.test.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:5795: CMakeFiles/simplex.step-68.mpirun4.debug.test.dir/rule] Error 2
gmake: *** [Makefile:2825: simplex.step-68.mpirun4.debug.test] Error 2
Test simplex/step-68.mpirun=4.debug: RUN
===============================   OUTPUT BEGIN  ===============================
[ 50%] Built target simplex.step-68.debug
[ 50%] Generating step-68.debug/mpirun=4/output
simplex/step-68.mpirun=4.debug: BUILD successful.
simplex/step-68.mpirun=4.debug: RUN failed. ------ Return code 255
simplex/step-68.mpirun=4.debug: RUN failed. ------ Result: /__w/dealii/dealii/build/tests/simplex/step-68.debug/mpirun=4/failing_output
simplex/step-68.mpirun=4.debug: RUN failed. ------ Partial output:

simplex/step-68.mpirun=4.debug: RUN failed. ------ Additional output on stdout/stderr:


--------------------------------------------------------
An error occurred in line <623> of file </__w/dealii/dealii/source/grid/grid_tools_dof_handlers.cc> in function
    std::vector<std::pair<typename MeshType<dim, spacedim>::active_cell_iterator, dealii::Point<dim> > > dealii::GridTools::find_all_active_cells_around_point(const dealii::Mapping<dim, spacedim>&, const MeshType<dim, spacedim>&, const dealii::Point<spacedim>&, double, const std::pair<typename MeshType<dim, spacedim>::active_cell_iterator, dealii::Point<dim> >&) [with int dim = 2; MeshType = dealii::Triangulation; int spacedim = 2; typename MeshType<dim, spacedim>::active_cell_iterator = dealii::TriaActiveIterator<dealii::CellAccessor<2, 2> >]
The violated condition was: 
    mesh.get_triangulation().all_reference_cells_are_hyper_cube()
Additional information: 
    You are trying to use functionality in deal.II that is currently not
    implemented. In many cases, this indicates that there simply didn't
    appear much of a need for it, or that the author of the original code
    did not have the time to implement a particular case. If you hit this
    exception, it is therefore worth the time to look into the code to
    find out whether you may be able to implement the missing
    functionality. If you do, please consider providing a patch to the
    deal.II development sources (see the deal.II website on how to
    contribute).
--------------------------------------------------------
```

**Comment by drwells** [comment]
The test fails because I added an assertion. We should definitely fix that function (the logic is for hypercubes) but maybe it still works well enough to use particles? I'll convert that one into an issue.

**Pull request merged**
