### PR TITLE
CMake: Compatibility fixes for CMake 3.4.0

### PR DESCRIPTION
**Pull request by tamiko**
CMake 3.4.0 no longer exports MPI_<LANGUAGE>_COMPILER as cached variable.
Therefore, we also have to make sure to unset ordinary variables (in
addition to cached variables) for our "retry" pass.

In reference to #1889

### CODE REVIEW

**Comment by tamiko** [comment]
@drwells *ping*

**Comment by drwells** [comment]
This works. I'll merge when the build finishes (this may take an hour more, my laptop is very slow).

How did you figure out that it was a cached variable problem? I reread `FindMPI.cmake` and I do not see where they changed handling of cached variables.

**Comment by tamiko** [comment]
> How did you figure out that it was a cached variable problem?

It was a guess.

I mean,
  - something changed in the new version,
  - the "hack" to manually set ```MPI_CXX_COMPILER``` (etc.) on first pass, and unset it afterwards (if ```DEAL_II_WITH_MPI``` is true) in a second pass, does not work anymore.
  - Removing this logic fixes the configure process.
  - ```MPI_CXX_COMPILER``` (etc.) is treated as a cached variable

strongly indicates that.
And in fact, ```MPI_CXX_COMPILER``` (etc.) is not present in ```CMakeCache.txt``` any more.


>  I reread FindMPI.cmake and I do not see where they changed handling of cached variables.

The only interesting part in the diff is
```
-      is_file_executable(MPI_${lang}_COMPILER MPI_COMPILER_IS_EXECUTABLE)
-      if (NOT MPI_COMPILER_IS_EXECUTABLE)
+      if (NOT IS_ABSOLUTE "${MPI_${lang}_COMPILER}")
```
So, my guess is that the caching is hidden in ```is_file_executable```. But I want to keep a bit of my sanity, so I haven't investigated any further.

**Comment by drwells** [comment]
@tamiko Thank you for the explanation. I am impressed by the deduction.

This works on `3.4` and `2.8.9` so we are good to go.

**Pull request merged**
