### PR TITLE
Make output of non_nested_transfer tests less verbose

### PR DESCRIPTION
**Pull request by fdrmrc**
Related to #15519 

Instead of printing `src` and `dst` vectors, only the l2 norm of the destination vector is printed.

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]
Excellent, printing the L2 norm should be enough, thank you! It is a pretty good indicator for errors, because it depends on all entries of the vector and for typical cases with similarly sized entries, only permutations are not detected. This should be unproblematic here.

**Review by peterrum — COMMENTED** [review]
I am not particularly happy that we now only print the l2-norm. Could you make the problem size smaller by refining less often? 

I know printing the vectors is still not the best solution and we should compare the results with analytical solution. However, this not working for restriction...

**Comment by kronbichler** [comment]
@peterrum do we have cases where the L2 norm is the same (up to 6 digits of a relative tolerance), but the actual content is different? This is what I meant in the previous post, the L2 norm is surprisingly good at indicating problems. It is better than the L1 norm (where adding the same number multiple times to the same slot) or the infinity norm (where only the largest entry matters), and at least to humans that need to parse a small amount of information it is great. Of course, we should compare to an analytic solution if possible, and we should think if those would work here. But printing vectors is not super helpful, not even short ones: It was really rare when the vector entries told me more than the L2 norm in the past 16 years.

**Comment by peterrum** [comment]
I find it useful in particular when comparing the different implementation (with and without FE_Nothing and matching and nonmatching).

**Comment by fdrmrc** [comment]
> Could you make the problem size smaller by refining less often?

Done!

**Comment by kronbichler** [comment]
Can you check the size of the files? I fear that 3 refinements and polynomial degrees up to 4 still generate too much data. I would prefer not to have file sizes larger than 20-60kB, otherwise it is hard to spot errors anyway. We probably do not need as many degrees.

> I find it useful in particular when comparing the different implementation (with and without FE_Nothing and matching and nonmatching).

I still think that the L2 norm would be good for comparing different implementations as a first indicator for the sanity of the features, and at least for the prolongation we could compute the error easily as we do in https://github.com/dealii/dealii/blob/e13307c507ce0318d956d81503bac95cd79f6b5d/tests/multigrid/transfer_matrix_free_08.cc#L80-L100 How many of these checks do we have for the global-coarsening infrastructure? It took me a while to figure this out for the regular MG, so we should do the same for global coarsening in case we have knowledge.

I do see the argument for local debugging, but as part of a file in the test suite I have doubts. One can always turn on the relevant `if` statements when a test actual starts failing for debugging the cause of the error, but often one needs different measures anyway - I say this from fixing many tests in deal.II over the past 10 years, including many not written by myself, and the case you make did not come up often, at least not as part of the repository. I actually dislike those tests, but my personal opinion should not be in the way of making an objective decision.

Anyway, the ship has already sailed in the sense that we have the history of the huge file in the repo, but I think keeping the repo size reasonable is also part of the code quality, so we should try.

**Comment by fdrmrc** [comment]
All of the golden outputs are now within 60kB. I decreased polynomial degrees and the number of functions to transfer

**Review by kronbichler — APPROVED** [review]

**Review by tamiko — APPROVED** [review]

**Review by peterrum — APPROVED** [review]

**Pull request merged**
