### PR TITLE
Rectangular full matrix

### PR DESCRIPTION
**Pull request by drwells**
`FullMatrix::add_row` currently does not work for rectangular matrices. I switched the `FullMatrix` tests to use rectangular matrices by default, which uncovered about half a dozen more bugs.

This PR fixes all such bugs that I could find (almost always `m()` is used in place of `n()` or vice versa) and switches all `FullMatrix` tests (approximately 160 of them) to use rectangular matrices where ever possible.

### CODE REVIEW

**Comment by bangerth** [comment]
Nice work!

**Comment by bangerth** [comment]
Actually, can you add a changelog entry?

**Comment by drwells** [comment]
One of these days I will remember to add these.

**Pull request merged**
