### PR TITLE
FEPointEvaluation: Implement sum into values option in integrate

### PR DESCRIPTION
**Pull request by bergbauer**
This allows to add several contributions to the same buffer, e.g. coming from inside, surface, and face contributions.

@kronbichler @peterrum

### CODE REVIEW

**Review by peterrum — COMMENTED** [review]
Makes sense. I am wondering what is better: new functions or template arguments (`do_add`  as in the internal function). @kronbichler Do we have precedence cases in `FEEvaluation`? I think I saw somthing like this in the past. But maybe that was only a benchmark code.

**Comment by bergbauer** [comment]
I use this function to directly add contributions from `FEPointEvaluation` objects info `FEEvaluation`/`FEFaceEvaluation` buffers via `StridedArrayView`.

I would like to have the same functionality also for `FEEvaluation`/`FEFaceEvaluation` (where you can provide the buffer) to e.g., let `FEFaceEvaluation` directly add into an `FEEvaluation` buffer or vice versa.

**Comment by kronbichler** [comment]
In `FEEvaluation`, we have an `add` option: https://github.com/dealii/dealii/blob/8d2c8f5e1fbe076f19f5a38f14cdf105cada613a/include/deal.II/matrix_free/fe_evaluation.h#L2265-L2268 but we do not have it for the face integrals. We do not currently have that for `FEFaceEvaluation` as far as I can see, but it would be straight-forward to add these functions.
However, regarding `FEEvaluation` implementing more sophisticated combination techniques beyond a simple addition is likely not the best use of developer time, and I would first spend time on creating a better abstraction around the old ideas https://github.com/kronbichler/multigrid/blob/experimental_merge_vector/common/laplace_operator_dg.h or at least show that we can be similarly fast or faster with the code proposed here.

**Comment by bergbauer** [comment]
The new commit 9ba20c721a414138832d2c322d4371a94eb2aa6c shows how the runtime alternative (with default parameter to `false`) would look like. The overhead introduced through the runtime `if` statements looks acceptable (almost in the noise) in my benchmark.

This interface is similar to `FEEvaluation` now. Let me know what you think @peterrum @kronbichler

**Comment by bergbauer** [comment]
Opinions? I can squash and add a changelog if we decide to go with the runtime argument.

**Review by kronbichler — APPROVED** [review]

**Review by peterrum — APPROVED** [review]

**Pull request merged**
