### PR TITLE
Added doi to step-54.

### PR DESCRIPTION
**Pull request by luca-heltai**

### CODE REVIEW

**Comment by tjhei** [comment]
please wait with merging. @luca-heltai and I are discussing the fact that the readme at doi.org/10.5281/zenodo.546089 contains html tags.

**Comment by bangerth** [comment]
It also has a grammar problem: "using arbitrary CAD files to generated geometry-adapted triangulations" should be "...to generate..."

**Comment by bangerth** [comment]
Are the two parts of this PR (renaming the input file and the DOI) related at all?

**Comment by tjhei** [comment]
> Are the two parts of this PR (renaming the input file and the DOI) related at all?

Changing any of the source files forces the generation of a new and different DOI, so yes.

**Comment by luca-heltai** [comment]
I split the two PR.  I'm waiting for an answer by zenodo. I could not find a way to remove a doi, so for the moment I'll stick to this doi, hoping that they will allow me to change one readme file.

**Comment by luca-heltai** [comment]
> It also has a grammar problem: "using arbitrary CAD files to generated geometry-adapted triangulations" should be "...to generate..."

@bangerth thanks. Fixed.

**Comment by tjhei** [comment]
> I split the two PR. I'm waiting for an answer by zenodo. I could not find a way to remove a doi, so for the moment I'll stick to this doi, hoping that they will allow me to change one readme file.

No, you can not change the content behind a DOI. Why don't you just create a new upload?

**Comment by luca-heltai** [comment]
Done.

**Comment by bangerth** [comment]
Looks good to me now. If it's ready, please merge yourself.

**Pull request merged**
