### PR TITLE
[9.0.1] Redo #7270

### PR DESCRIPTION
**Pull request by tamiko**
This is a minimal version of #7270 to use LDFLAGS/CXXFLAGS in all checks when
necessary and that adds a forgotten RESET_CMAKE_REQUIRED().

### CODE REVIEW

**Comment by tamiko** [comment]
@drwells What about this fix as well?

**Comment by bangerth** [comment]
Why did we need this in 9.0.1? This seems like a non-trivial patch to me...

**Comment by tamiko** [comment]
@bangerth Because it fixes a bug in the build system where we do not use the linker flags when doing the lapack symbol check, see #7266.

**Pull request merged**
