### PR TITLE
FEValues templates

### PR DESCRIPTION
**Pull request by davydden**
part of this PR #472 related to FEValues.

p.s. work in progress, may not compile yet

### CODE REVIEW

**Comment by davydden** [comment]
@bangerth we hit `data_out_*` issues again:

```
/Users/davydden/libs-sources/deal.ii/davydden/source/numerics/data_out_dof_data.cc:561:23: error: no matching member function for call to 'get_function_values'
```

**Comment by bangerth** [comment]
Can you provide the context in which the error happens, i.e., the complete error message? What is the VectorType of the function in which the error happens?

**Comment by davydden** [comment]
since we now require `FEValues::get_function_*` to have consistent local and global types (e.g. `std::vector<float>` and `Vector<float>`) this makes `data-out-related` functions unhappy as they want to evaluate arbitrary input global vector into the local vector of `double`:
```
no known conversion from 'std::vector<double>' to 'std::vector<typename Vector<float>::value_type> &'
```

The complete error is as follows:

```
[ 23%] Building CXX object source/distributed/CMakeFiles/obj_distributed.debug.dir/tria.cc.o
/Users/davydden/libs-sources/deal.ii/davydden/source/numerics/data_out_dof_data.cc:561:23: error: no matching member function for call to 'get_function_values'
      fe_patch_values.get_function_values (*vector, patch_values);
      ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/Users/davydden/libs-sources/deal.ii/davydden/source/numerics/data_out_dof_data.cc:779:11: note: in instantiation of member function 'dealii::internal::DataOut::DataEntry<dealii::DoFHandler<1, 1>, dealii::Vector<float> >::get_function_values' requested here
    = new internal::DataOut::DataEntry<DH,VECTOR>(dofs, &vec, names,
          ^
/Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/fe/fe_values.h:1719:8: note: candidate function [with InputVector = dealii::Vector<float>] not viable: no known conversion from 'std::vector<double>' to 'std::vector<typename Vector<float>::value_type> &' for
      2nd argument
  void get_function_values (const InputVector &fe_function,
       ^
/Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/fe/fe_values.h:1736:8: note: candidate function [with InputVector = dealii::Vector<float>] not viable: no known conversion from 'std::vector<double>' to
      'std::vector<Vector<typename Vector<float>::value_type> > &' for 2nd argument
  void get_function_values (const InputVector       &fe_function,
       ^
/Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/fe/fe_values.h:1758:8: note: candidate function template not viable: requires 3 arguments, but 2 were provided
  void get_function_values (const InputVector &fe_function,
       ^
/Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/fe/fe_values.h:1784:8: note: candidate function template not viable: requires 3 arguments, but 2 were provided
  void get_function_values (const InputVector &fe_function,
       ^
/Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/fe/fe_values.h:1820:8: note: candidate function template not viable: requires 4 arguments, but 2 were provided
  void get_function_values (const InputVector &fe_function,
       ^
```

so far it seems that `data out` things have to be patched as well to make `deal.II` compile.

**Comment by bangerth** [comment]
Ah, yes, I see.

I'm for a workaround for the moment in which you do something like
```
  std::vector<InputVector::value_type> tmp (...);
  fe_values.get_function_values (..., tmp);
  local_values = tmp;   // convert data to double
```
This should work for now and allow to do the fe_values related issues in a first step. In a second step, we can do the DataOut related issues and undo the workaround.

**Comment by bangerth** [comment]
By the way, can I ask you for a favor: The comments in front of the various local `Value`, `Gradient`, etc  structures are now no longer accurate. They currently (in your patch) say something like
```
 /**
* A typedef for the data type of values of the view this class
* represents. Since we deal with a single components, the value type is a
* scalar double.
*/
- typedef double value_type;
+ template<typename number>
+ struct Value
+ {
+ typedef number type;
+ };
```
Would you be willing to change this text in front of each of the new structures to say something like the following (with the obvious adjustments for gradient, curl, etc)?
```
This structure has a local typedef @p type that represents the values of shape functions or
finite element fields at quadrature points. The template argument denotes the type used to store the values of degrees of freedom in vectors of size <code>DoFHandler::n_dofs()</code>.

In places where this type is used to evaluate the values of shape functions at quadrature points, the template argument is simply <code>double</code> since this is the accuracy with which we evaluate shape functions. When evaluating the values of finite element fields, the correct data type for the value of a field at a quadrature point is what you get when you multiply the type used to represent the shape function $\varphi_j(x_q)$ times the type used to store the values $U_j$ of degrees of freedom, in order to form the value of $u_h(x_q)=\sum_j U_j \varphi_j(x_q)$. The local typedef in the current structure corresponds to the type you get when forming this product.
```

**Comment by bangerth** [comment]
And for completeness and reference, if we were allowed to use C++11, we could do this:
```
  typedef double value_type;
  void get_function_values (const VectorType &input,
                        std::vector<decltype(typename VectorType::value_type()) * value_type())> &output);
```
Alas, no C++11 yet in deal.II :-(

**Comment by davydden** [comment]
I changed some comments here 7a2bafd. Is the the way you want them to be?

**Comment by davydden** [comment]
urgh, there are still a lot of errors, like trying to instantiate `FEValuesVeiws` `get_function_*` for `dealii::IndexSet()`.  Index set does not have a value type, thus they don't fit into the current structure...

**Comment by bangerth** [comment]
Feel free to add a local typedef `value_type` to `IndexSet`. It should be `bool`. (Do it in a separate commit, if you don't mind.)

**Comment by davydden** [comment]
I suppose now all instantiation should be done for `std::vector<bool>`, etc?

**Comment by bangerth** [comment]
In essence, yes, this is the kind of text I was hoping for. Thanks for adding it -- just make the relevant changes of adding "gradient of" or "Hessian of" in the appropriate places, and changing the corresponding formulas using $\nabla$ or $\nabla^2$ etc.

**Comment by bangerth** [comment]
Since this is repetitive, another option may also be to refer to a common location where this text is only reproduced once in a generic way. For example in the documentation of namespace FEValuesViews, or in another suitable place. Either way will be fine with me.

**Comment by bangerth** [comment]
On 02/02/2015 05:18 PM, Denis Davydov wrote:
> I suppose now all instantiation should be done for |std::vector<bool>|, etc?

I suppose so.


-- 
------------------------------------------------------------------------
Wolfgang Bangerth               email:            bangerth@math.tamu.edu
                                 www: http://www.math.tamu.edu/~bangerth/

**Comment by davydden** [comment]
I am trying to add equality operator and explicit copy constructor for tensors of different `number`, as this will make life much easier when trying to make `deal.II` compile with current mods. 

So far, I tried adding to `tensor.h`
```
template <int rank_, int dim, typename Number>
template <typename OtherNumber>
inline
Tensor<rank_,dim,Number> &
Tensor<rank_,dim,Number>::operator = (const Tensor<rank_,dim,OtherNumber> &t)
{
  for (unsigned int i=0; i<dim; ++i)
    subtensor[i] = t.subtensor[i];
  return *this;
}

template <int rank_, int dim, typename Number>
template <typename OtherNumber>
Tensor<rank_,dim,Number>::Tensor (const Tensor<rank_,dim,OtherNumber> &t)
{
  *this = t;
}
```

Yet, when I try using it while patching `derivative_approximation`, compiler does not try using it:
```
/Users/davydden/libs-sources/deal.ii/davydden/source/numerics/derivative_approximation.cc:254:18: error: no matching conversion for functional-style cast from 'value_type' (aka 'dealii::Tensor<1, 1, float>') to 'ProjectedDerivative' (aka 'Tensor<1, 1>')
          return ProjectedDerivative(values[0]);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
/Users/davydden/libs-sources/deal.ii/davydden/include/deal.II/base/tensor_base.h:342:3: note: candidate constructor not viable: no known conversion from 'Tensor<[2 * ...], float>' to 'const Tensor<[2 * ...], double>' for 1st argument
  Tensor (const Tensor<1,dim,Number> &);
  ^
```

what am I missing?

p.s. i would add the same thing for ran 0 and 1 tensor.

**Comment by bangerth** [comment]
Good question. Can you separate the patches that extend Tensor into a pull request of their own and construct a test that fails only with these patches?

**Comment by davydden** [comment]
removed couple of commits related to Tensor class, which are being addressed in #492

**Comment by bangerth** [comment]
If you rebase this to master, you should get the changes to `Tensor`.

**Comment by davydden** [comment]
slowly getting somewhere.. there are still issues in `point_value_history` and `error_estimator`... 

but more importantly we need further extensions of operators in tensor class for cases like:
```
symmetric_gradients[q_point] += value *
                                                symmetrize_single_row(comp, *shape_gradient_ptr++);
```
or
```
symmetric_gradients[q_point] += value *
                                                symmetrize_single_row(comp, *shape_gradient_ptr++);
```
where `value` is any of any type (`long`,`double`,`std::compex<double>`) and shape related functions are in `double`. 

I will try fixing it here in separate commits, if it will work we can shift these mods to a separate PR.

**Comment by davydden** [comment]
The last issue in the above is fixed. 

Here's a new one from `IndexSet` and `bool` types: 
```
/Users/davydden/libs-sources/deal.ii/davydden/source/fe/fe_values.cc:483:31: error: no viable overloaded '+='
              values[q_point] += value **shape_value_ptr++;
              ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/davydden/libs-sources/deal.ii/davydden/source/fe/fe_values.cc:1283:15: note: in instantiation of function template specialization 'dealii::FEValuesViews::internal::do_function_values<1, 1, bool>' requested here
    internal::do_function_values<dim,spacedim,typename InputVector::value_type>
              ^
```
So C++ does not what to do with 
`bool += bool * double`. 

Perhaps one can change `value_type` of `IndexSet` to `double`?

**Comment by bangerth** [comment]
I think this points at a larger problem. If anything, one could contemplate changing `IndexSet::value_type` to `int` but even that is questionable: The statement computes the values of a finite element function with binary values for the unknowns, i.e., $u_h(x)=\sum_j U_j \phi_j(x)$ where $U_j$ has data type `bool` and $\phi_j(x)$ has data type `double`.

The result, i.e., the vector you write into, needs to have a data type that corresponds to the product of these two things. So far, you've always encountered cases where the data type of `X * double` is `X`, but here that's not true: the type of `bool * double` should be `double`.

In other words, we would need to introduce something like this, maybe in `base/template_constraints.h`:
```
  template <typename T, typename U> struct ProductType {
    typedef decltype(T() * U()) type;
  };
```
which without C++11 one may approximate with a sequence of specializations:
```
  template <typename T> struct ProductType<T,double> { typedef T type; };
  template <> struct ProductType<bool,double> { typedef double type; };
  ...
```
Then in all of the places where you currently just use `T`, you'd have to use `ProductType<T,double>`.

Does this make sense? I recognize that it's a real pain to go through this, but I think it's the only reasonable approach. Do you want me to introduce such a type in a separate PR so you can use it?

**Comment by bangerth** [comment]
(On a separate note, if `value_type` is bool, you will never be able to do the multiplication. I think using `value_type` equal to `int` makes sense. Feel free to introduce this in a separate patch with a note that explains the rationale for this decision: that we want to look at an `IndexSet` as a numerical object like a vector.

**Comment by davydden** [comment]
I think `ProductType` is good in general, however in either case it will break the whole mods in this PR, namely that the `InputVector` and the container where one stores fe values should have the same type. So for `$u_h(x)=\sum_j U_j \phi_j(x)$` we requre `u_h(x)` and `U_j` to be of the same type. 

I do not know where `IndexSets` are passed to FEValues, but as `bool` casts fine to `double` or `float`, I would prefer to sticking with `value_type=[float|double]`. Of course, the resulting field `u_h(x)` is not bool anymore, but at least it keeps things in the state they were before the PR.

**Comment by davydden** [comment]
a relevant discussion and references to C++ standard on casting bool to `int`: http://stackoverflow.com/questions/4276207/is-c-c-bool-type-always-guaranteed-to-be-0-or-1-when-typecasted-to-int

Same should hold for `double` or `float`.

**Comment by bangerth** [comment]
@davydden Thinking about this some more, I think we've been going down the wrong road. Rather than spend more time with where you are going, let me implement the `ProductType` class, and then start the work on the FEValuesViews and other functions from scratch. Given what you found out about the issue with `IndexSet`, I think that the idea of the local structures like `FEValuesViews::Scalar::Value` isn't workable. Rather, let's throw this away and stick with the original typedefs and then just change functions such as `get_function_values` have signatures such as
```
  template <typename InputVector>
  void get_function_values (const InputVector &fe_function,
                              std::vector<ProductType<InputVector::value_type,value_type>::type> &values) const;
```
This accurately represents what the output should be, and it avoids the necessity to introduce many local structures with the need for awkward explanations, etc.

So my suggestion would be to hold off for a day till the `ProductType` is there and then start from scratch. I'm sorry for having chased you down the wrong direction -- sometimes, software designs just turn out to be wrong :-((

**Comment by davydden** [comment]
@bangerth ok. I'll be away for a couple of weeks, so i'll get back to this PR (and others) at the beginning of march.

**Comment by bangerth** [comment]
OK, I think the infrastructure is now in place and this is ready to move forward.

Take a look here: https://github.com/bangerth/dealii/tree/generic-scalar-types-for-FEValues
If you pull the last two commits, you get a state that I think goes into the right direction. I've converted the FEValuesViews::Scalar class for you (just take a look at the diffs of https://github.com/bangerth/dealii/commit/14082f4fa0bba48c0398a5ee53918d31e36b2891) and I've adjusted some of the generic machinery in fe_values.cc. The whole shebang does not compile right now because the generic machinery was adjusted but the FEValuesViews::Vector/... classes were not. 

If you want, I can leave it for you here. Take a look at the changes made to FEValuesViews::Scalar and make the same changes to FEValuesViews::Vector and FEValuesViews::SymmetricTensor. I think one also needs to make similar changes to the FEValues::get_function_* functions. It should, hopefully, all be rather mechanical. With some luck, it should not spread beyond FEValues, though I suspect that it might also touch DataOut. In any case, feel free to ask for help once you go beyond the mechanical changes.

**Comment by davydden** [comment]
sounds good to me.

I guess i will merge you branch to this one to give it a go here (of course after rebasing on top of the master)

**Comment by bangerth** [comment]
My suggestion would be to actually start a new branch based on my commits. Then repeat the changes I made in FEValuesViews::Scalar to the other classes in fe_values and cherry-pick the commits you've done on your existing branch  onto the new branch -- gitk is your friend in this regard!

**Comment by davydden** [comment]
before rushing to it, i think there are still some open questions. So far you have something like
```
typename ProductType<value_type,typename InputVector::value_type
```
with
```
typedef double        value_type
```

This will become more tricky for other classes, like, FEValuesViews::Vector with
```
typedef dealii::Tensor<1,spacedim>          value_type;
```
One way is to write down all possible multiplications and combinations in `template_constraints.h`, but this is sub-optimal IMHO. 

Perhaps, something like that in `template_constraints.h`
```
template <int dim, int spacedim, typename T, typename U>
struct ProductType< Tensor<dim,spacedim,T>,U>
{
  typedef Tensor<dim,spacedim,ProductType<T,U> type;
};
```
could do the trick?

**Comment by davydden** [comment]
Perhaps, it's better to discuss it in the dedicated PR, here's the commit https://github.com/davydden/dealii/commit/f5569882902e2f6ffb5eb0ae51632339a5b64885

**Comment by bangerth** [comment]
`ProductType` already works for products of `Tensor` objects with everything -- nothing for you to worry about, just use it :-)

**Comment by davydden** [comment]
good to know ;-) was not obvious for me from the code, i will remove the unnecessary commit later...

**Comment by bangerth** [comment]
@davydden :  Since this is superseded by #621 , can we close this PR?

**Comment by davydden** [comment]
agreed

**Comment by davydden** [comment]
in reference to #2033

**Pull request closed without merging**
