### PR TITLE
templating ParallelData in error_estimator

### PR DESCRIPTION
**Pull request by davydden**
currently, part of this PR https://github.com/dealii/dealii/pull/621 ;
Aims to make storage base type consistent with the `InputVector::value_type`.

### CODE REVIEW

**Comment by kronbichler** [comment]
This patch does not currently compile on my machine. It bails out because fe_values.get_function_gradients() cannot take something else than std::vector<Tensor<1,dim,double> > if I can read it correctly. Is there something missing to make this patch complete?

**Comment by bangerth** [comment]
Ugh -- so this should have been a follow-up to #621 then. I'll see about reverting it.

**Comment by bangerth** [comment]
@davydden : Please just add this patch to the ones you have in #621 (e.g., through git cherry-pick).

**Comment by davydden** [comment]
it is currently there, in https://github.com/dealii/dealii/pull/621 i have not removed this commit from that PR yet.

**Comment by davydden** [comment]
i don't think it can be a follow up to https://github.com/dealii/dealii/pull/621 as https://github.com/dealii/dealii/pull/621 will not compile without this patch. So perhaps it shall just be a part of it.

**Comment by davydden** [comment]
in reference to #2033

**Pull request merged**
