### PR TITLE
Updated boost::unordered_map/set to std library

### PR DESCRIPTION
**Pull request by adam4130**
Issue #8162

### CODE REVIEW

**Comment by drwells** [comment]
Thanks for doing this!

I don't have it in front of me right now but I think we might have kept these to preserve compatibility with GCC 4.8. We should double-check with that compiler before merging.

**Comment by masterleinad** [comment]
You need to run the indentation script `contrib/utilities/indent` (or just `make indent` in your build directory) as well.

**Comment by bangerth** [comment]
I love it when I post an idea and someone takes it up! Thanks, @adam4130! Do you know how to run the indentation script? In your build directory, just do `make indent` and then commit (and push) the resulting changes.

@drwells -- do you have evidence that we purposefully didn't use the `std::` classes? I think it's a case where nobody had actually looked at the issue.

/rebuild

**Comment by drwells** [comment]
I think I was remembering #3902, but that isn't relevant here.

Regardless: I just checked with my local copy of GCC 4.8 so its not an issue :heavy_check_mark:

**Pull request merged**
