### PR TITLE
Fix steps broken by PR 1673

### PR DESCRIPTION
**Pull request by jppelteret**
With reference to @tamiko's comment in #1673 highlighting build errors for steps 20, 37 and 45.

### CODE REVIEW

**Comment by jppelteret** [comment]
@tamiko I cannot recreate the problem with step-45. It compiles and runs fine on my machine. Its not obvious to me how the changes made in #1673 could have broken this because most of the classes used here are actually custom classes derived from `Trilinos` types, which this PR did not touch. Any recommendations on how to proceed?

**Comment by jppelteret** [comment]
Given the necessary fixes, should I note this as an incompatibility in the changelog (i.e. that user-defined classes that are used as Preconditioners require some extension)?

**Comment by kronbichler** [comment]
@jppelteret Similarly to step-37, there are two more tests using the same mechanism through PreconditionChebyshev, namely
```
matrix_free/parallel_multigrid.cc
matrix_free/step-37.cc
```
Could you please adjust those as well?

I must admit I am not convinced whether deferring `size_type` to `MATRIX::size_type` really adds anything over just hardcoding it to `types::global_dof_index` (thus saving a line of code in the application); the only case where I could see it makes sense would be the usage of PreconditionChebyshev without the deal.II library behind which is clearly not optimal.

Another point (that I should have seen in #1673 but that PR went below my radar) to check if MATRIX::size_type is indeed enforced is that the size type of the matrix and vector templates are both referring to the same type by some static assert (either in the constructor for preconditioners that have both as a template or in the vmult methods if not), otherwise lots of strange things could happen.

**Comment by tamiko** [comment]
I suggest that we try to refactor in a way that we do not break above example steps...

I'm sorry for not having spotted this earlier.

If this ultimately means that ```IterativeInverse``` is not usable in the ```LinearOperator``` context, so be it. ```IterativeInverse``` is superseded by ```inverse_operator```...

I also suggest that we do not touch ```PointerMatrix``` because it produces quite some fallout:

http://cdash.kyomu.43-1.org/testDetails.php?test=24956979&build=13853
http://cdash.kyomu.43-1.org/testDetails.php?test=24954833&build=13853
http://cdash.kyomu.43-1.org/testDetails.php?test=24956950&build=13853

**Comment by tamiko** [comment]
I suggest we partially revert parts of the pull request that changed ```IterativeInverse``` and the ```ProductMatrix``` types. This does not resolve the issue @kronbichler is referring to.

**Comment by jppelteret** [comment]
@kronbichler To the best of my recollection, within these matrix classes there is a mixture of implementations for defining a `size_type`. I'm happy to hard-code it (like is done elsewhere) and add the `static_assert` as you've recommended. 

@bangerth Are you alright with this? This idea was originally brought up in the context of another `Preconditioner` class.

**Comment by kronbichler** [comment]
@jppelteret Agreed, my suggestion is to hard-code `size_type` in PreconditionChebyshev and add `static_assert` in C++11 mode.

**Comment by jppelteret** [comment]
@kronbichler OK, once #1787 has been merged I'll do this.

**Comment by bangerth** [comment]
The purist in me wants to make sure that `size_type` is always the actually correct type for matrices, but it's true that that requires that user-defined matrix types have to declare it for no actual good reason. So whatever you come up with seems fine with me!

**Comment by tamiko** [comment]
@jppelteret I have merged #1787.

**Comment by jppelteret** [comment]
@tamiko @kronbichler After the partial reversion, I think that f89ba58 should fix this problem and includes the checks that were recommended. The following tests work on my home machine: `lac/linear_operator_*`, `matrix-free/{parallel_multigrid, step-37}`, `step-{20,37,45}`.

**Comment by tamiko** [comment]
Acked. @kronbichler What do you think?

**Comment by kronbichler** [comment]
Great, this is exactly what I had in mind.

**Pull request merged**
