### PR TITLE
add LinearAlgebra::distributed::Vector::add() with pointers

### PR DESCRIPTION
**Pull request by davydden**
@kronbichler :  If you could point me where unit tests for another `add()` are, i would be happy to add one more for the one in this PR.

### CODE REVIEW

**Comment by kronbichler** [comment]
@davydden The tests for the parallel vector are in `mpi/parallel_vector_xx` but I do not think we test the `add` interface summing with selected elements directly (if at all, we only do it implicitly via some assembly test).

**Comment by davydden** [comment]
yes, AFAICT there are no separate tests for `add()`.

**Comment by kronbichler** [comment]
So just add one with all three or now four variants as a new one in `mpi/parallel_vector_18`?

**Comment by davydden** [comment]
> So just add one with all three or now four variants as a new one in mpi/parallel_vector_18?

I am doing it based on `_06`

**Comment by davydden** [comment]
@kronbichler I added a unit test.

**Comment by kronbichler** [comment]
Looks good!

**Pull request merged**
