### PR TITLE
hp Version of KellyErrorEstimator<1,spacedim>

### PR DESCRIPTION
**Pull request by ghost**
The internal error message was a little bit confusing. Looking in the code shows, that this is just not implemented. Would this be straightforward or is that not so easy?

### CODE REVIEW

**Comment by marcfehling** [comment]
Yes, this should be a `ExcNotImplemented`:

Comparing to the other functions, I can only spot a difference to this overload:
https://github.com/dealii/dealii/blob/3d0a9b8767cdd05445a4717774cbdb0c92df24e9/source/numerics/error_estimator_1d.cc#L165-L199

This function is implemented for just one solution, rather than for a collection. But that should already be implemented, as they convert that one solution into a vector of solutions. Funny.

I assume you somehow ran into this exception in one of your applications. Can you try to call
```
   estimate(mapping, 
            dof_handler, 
            quadrature, 
            neumann_bc, 
            solutions, 
            errors, 
            component_mask, 
            coefficients, 
            n_threads, 
            subdomain_id, 
            material_id, 
            strategy); 
```
instead of throwing the exception there  and see it works? This way, we can resolve the mystery behind this function :)

**Comment by gfcas** [comment]
> 
> 
> > > Has someone seen this error in the tester once. I dont understand it right now.
> > 
> > 
> > I think with your change you accidentally caused one of the overloads to call itself, which will end up in a infinite recursion loop.
> 
> OK, thanks, so I will take a second look. But strange, the linux testers are happy...

Should now be fixed...

**Comment by marcfehling** [comment]
Well, I compared both `master` and this feature branch another time and I don't find anything missing.

@gfcas -- I think a changelog entry would be nice. I would merge the PR after you provided one :)

**Comment by gfcas** [comment]
> 
> 
> Looks good to me.
> 
> However, your change of reordering the functions makes this patch horrible to review now :-) I would like to wait for a second approval just in case I missed something.

I totally agree with you, sorry ... I reverted the reordering of the functions and added a minor(?) changelog entry. Thanks for reviewing!

**Pull request merged**
