### PR TITLE
VectorizedArray for ARM NEON intinsics

### PR DESCRIPTION
**Pull request by peterrum**
Moved from my project: https://github.com/peterrum/dealii-neon

### CODE REVIEW

**Comment by tjhei** [comment]
Awesome! Let me know when this is ready to try.

**Comment by peterrum** [comment]
> Awesome! Let me know when this is ready to try.

I guess it is as ready as it will be (I don't have access to the right machines).

The following line has to be updated:

https://github.com/dealii/dealii/blob/f462bc67825ce6a08e25455c4af0e485c2bf919e/include/deal.II/base/vectorization.h#L4534

The rest works hopefully (at least the conversion to SSE2 worked).

**Comment by peterrum** [comment]
@tjhei Wanted to play with this...

**Comment by peterrum** [comment]
Closing since not needed anymore.

**Pull request closed without merging**
