### PR TITLE
Fixed write_pvtu_record #3259

### LINKED ISSUE #3259: Bug in write_pvd_record
Hello,

I think there is a small possibility of bug in the write_pvd_record() in file
dealii/source/base/data_out_base.cc

This is because, if all the time data is of the order of 10^6, but suddenly the time steps become O(1), the time data printed in the file is then just O(6) and information is lost. Due to this, all subsequent files have the same time  and  Paraview is taking that only one file for all the files with same time.

I am copying a part here from the data file that I have for providing some clarification.

After having some very large time-steps in my simulation, the time-steps again drop to around 0.1.

  <DataSet timestep="9.85603e-08" group="" part="0" file="alpha_solution-00050.00000.pvtu"/>
    <DataSet timestep="4e+06" group="" part="0" file="alpha_solution-00051.00000.pvtu"/>
    <DataSet timestep="8e+06" group="" part="0" file="alpha_solution-00052.00000.pvtu"/>

The time step after this is  0.1, but the file does not show this change. 

    <DataSet timestep="8e+06" group="" part="0" file="alpha_solution-00053.00000.pvtu"/>
    <DataSet timestep="8e+06" group="" part="0" file="alpha_solution-00054.00000.pvtu"/>
    <DataSet timestep="8e+06" group="" part="0" file="alpha_solution-00055.00000.pvtu"/>
    <DataSet timestep="8e+06" group="" part="0" file="alpha_solution-00056.00000.pvtu"/>
    <DataSet timestep="8e+06" group="" part="0" file="alpha_solution-00057.00000.pvtu"/>
    <DataSet timestep="8e+06" group="" part="0" file="alpha_solution-00058.00000.pvtu"/>

I think adding flags to out in the file might change this behaviour.

### PR DESCRIPTION
**Pull request by sairajat**
Fixes #3259

### CODE REVIEW

**Comment by bangerth** [comment]
Looks good to me. OK to merge if the tester is happy.

/run-tests

**Comment by sairajat** [comment]
This build successfully passes indentation test, however I do have a question regarding it.

If I want to indent the code that I have written, will running the` contrib/utilities/indent `file will do it ?
Will it just adjust spacing or also add/remove new lines if needed ?

Also, I don't understand how the `contrib/utilities/check_indentation.sh` is to be used ?
When I ran the command, it just showed me the places where I edited the code.

**Comment by bangerth** [comment]
Yes, running `./contrib/utilities/indent` is exactly what you need to do. I think it also correctly adjust spacing.

`contrib/utilities/check_indentation.sh` is not a program you will typically have to run yourself. We probably ought to document at the top of the file what it actually does.

**Comment by bangerth** [comment]
See #3309.

**Pull request merged**
