### PR TITLE
add and use type traits for data exchange in matrix-free

### PR DESCRIPTION
**Pull request by davydden**
fixes https://github.com/dealii/dealii/issues/7187 using type-traits instead of the base class.
better viewed on commit-by-commit basis ~~starting from the 4-th commit~~.

with gcc-8.2 on Ubuntu all matrix-free tests pass:
```
$ ctest -j 4 -R "matrix_free"
...
100% tests passed, 0 tests failed out of 395
```

~~blocked by /~~ builds upon https://github.com/dealii/dealii/pull/7782

### CODE REVIEW

**Comment by davydden** [comment]
rebased.

**Comment by masterleinad** [comment]
There seem to be some kind of problem with the `CI` tester here (https://jenkins.tjhei.info/blue/organizations/jenkins/dealii/detail/PR-7787/3/pipeline):
```
Connecting to https://api.github.com using tjhei/****** (GitHub Access Token)
java.io.FileNotFoundException: https://api.github.com/repos/dealii/dealii/pulls/7787
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:243)
	at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
	at org.kohsuke.github.Requester.parse(Requester.java:625)
	at org.kohsuke.github.Requester.parse(Requester.java:607)
	at org.kohsuke.github.Requester._to(Requester.java:285)
Caused: org.kohsuke.github.GHFileNotFoundException: {
  "message": "Server Error"
}

	at org.kohsuke.github.Requester.handleApiError(Requester.java:699)
	at org.kohsuke.github.Requester._to(Requester.java:306)
	at org.kohsuke.github.Requester.to(Requester.java:247)
	at org.kohsuke.github.GHRepository.getPullRequest(GHRepository.java:715)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.retrieve(GitHubSCMSource.java:1445)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:583)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:95)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:293)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```

**Comment by tjhei** [comment]
Rerunning it, please be patient.

**Comment by kronbichler** [comment]
@davydden can you have a look at the failing test for the header `matrix_free.h`:
```
In file included from /jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/fe_evaluation.h:35:0,
                 from /jenkins/workspace/dealii_PR-7787/include/deal.II/numerics/vector_tools.templates.h:78,
                 from /jenkins/workspace/dealii_PR-7787/tests/all-headers/test_header.cc:17:
/jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/matrix_free.h: In member function ‘void dealii::internal::VectorDataExchange<dim, Number>::update_ghost_values_start(unsigned int, const VectorType&)’:
/jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/matrix_free.h:2821:69: error: expected ‘,’ before ‘)’ token
         std::is_same<Number, typename VectorType::value_type>::value);
                                                                     ^
/jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/matrix_free.h:2821:69: error: expected string-literal before ‘)’ token
/jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/matrix_free.h: In member function ‘void dealii::internal::VectorDataExchange<dim, Number>::update_ghost_values_finish(unsigned int, const VectorType&)’:
/jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/matrix_free.h:2926:69: error: expected ‘,’ before ‘)’ token
         std::is_same<Number, typename VectorType::value_type>::value);
                                                                     ^
/jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/matrix_free.h:2926:69: error: expected string-literal before ‘)’ token
/jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/matrix_free.h: In member function ‘void dealii::internal::VectorDataExchange<dim, Number>::compress_start(unsigned int, VectorType&)’:
/jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/matrix_free.h:3040:69: error: expected ‘,’ before ‘)’ token
         std::is_same<Number, typename VectorType::value_type>::value);
                                                                     ^
/jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/matrix_free.h:3040:69: error: expected string-literal before ‘)’ token
/jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/matrix_free.h: In member function ‘void dealii::internal::VectorDataExchange<dim, Number>::compress_finish(unsigned int, VectorType&)’:
/jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/matrix_free.h:3134:69: error: expected ‘,’ before ‘)’ token
         std::is_same<Number, typename VectorType::value_type>::value);
                                                                     ^
/jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/matrix_free.h:3134:69: error: expected string-literal before ‘)’ token
/jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/matrix_free.h: In member function ‘void dealii::internal::VectorDataExchange<dim, Number>::reset_ghost_values(const VectorType&) const’:
/jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/matrix_free.h:3223:69: error: expected ‘,’ before ‘)’ token
         std::is_same<Number, typename VectorType::value_type>::value);

                                                                     ^
/jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/matrix_free.h:3223:69: error: expected string-literal before ‘)’ token
/jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/matrix_free.h: In member function ‘void dealii::internal::VectorDataExchange<dim, Number>::zero_vector_region(unsigned int, VectorType&) const’:
/jenkins/workspace/dealii_PR-7787/include/deal.II/matrix_free/matrix_free.h:3279:69: error: expected ‘,’ before ‘)’ token
         std::is_same<Number, typename VectorType::value_type>::value);
                                                                     ^
```
(the other failures look a bit spurious, but this one seems real).

**Comment by davydden** [comment]
Will do ASAP.

**Comment by davydden** [comment]
> can you have a look at the failing test for the header matrix_free.h:

oh, it's my wrong usage of `static_assert`, in C++17 you don't need message, in C++11 you do. Will fix.

**Pull request merged**
