### PR TITLE
Move vector tests from tests/bits to tests/vector.

### PR DESCRIPTION
**Pull request by drwells**
More progress towards removing `tests/bits`.

### CODE REVIEW

**Comment by bangerth** [comment]
OK to merge once tester is happy. Thanks!

**Comment by bangerth** [comment]
In reference to #1581 .

**Comment by tjhei** [comment]
> /run-tests

I finally figured out how I managed to break the tester a couple of days ago (it was timing out because it was trying to run all tests).

**Comment by drwells** [comment]
@tjhei I probably should have mentioned that that is what I saw (it ran 1000/4000 tests before timing out).

**Comment by kronbichler** [comment]
This looks fine and I merge now.

**Pull request merged**
