### PR TITLE
remove notes on indentation from documentation

### LINKED ISSUE #13531: Why does "coding conventions" contain information on "indentation"?
see https://www.dealii.org/developer/doxygen/deal.II/CodingConventions.html

Indentation seems to be described already in the wiki:
https://github.com/dealii/dealii/wiki/Contributing
https://github.com/dealii/dealii/wiki/Indentation

Wouldn't it make sense to have this information only once (in the Wiki)?

### PR DESCRIPTION
**Pull request by nfehn**
closes #13531

### CODE REVIEW

**Comment by nfehn** [comment]
Principally, I would have suggested with this PR to remove indentation from "coding conventions" (and, hence, also a link to another page). But if you think it should remain part of coding conventions, we could also add a link.

**Comment by bangerth** [comment]
Yes, let's add a link. Indentation is part of the coding conventions.

**Review by bangerth — CHANGES_REQUESTED** [review]
Let's make sure we add the link before merging.

**Comment by peterrum** [comment]
> But if you think it should remain part of coding conventions, we could also add a link.

@nfehn Could you add the note?

**Review by drwells — APPROVED** [review]

**Comment by drwells** [comment]
The link is in and works so I will go ahead and merge.

**Pull request merged**
