### PR TITLE
Fix DataAccessOnFaces::values for meshes containing non-hypercube cells

### PR DESCRIPTION
**Pull request by peterrum**
@zjiaqi2018 This fixes your problem (step-67 on simplex mesh) for me. Could you verify it also works for you. Thanks!

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]

**Comment by kronbichler** [comment]
Can we add step-67 on simplices as a test (or something related), once you have verified that this works now?

**Comment by zjiaqi2018** [comment]
> Can we add step-67 on simplices as a test (or something related), once you have verified that this works now?

Yes, I am working on it now.

**Comment by peterrum** [comment]
> Can we add step-67 on simplices as a test (or something related), once you have verified that this works now?

Let's add this as follow up. @zjiaqi2018 has verified locally that it works.

**Pull request merged**
