### PR TITLE
CMake: use full compiler/linker flags for trilinos sanity checks

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Review by drwells — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]

**Comment by drwells** [comment]
We definitely add these flags if we are using Kokkos with OpenMP. Is it possible to get in a situation where we do not have kokkos but we do have tpetra with openmp?

**Comment by Rombur** [comment]
>  Is it possible to get in a situation where we do not have kokkos but we do have tpetra with openmp?

No Tpetra is built on top of Kokkos. You cannot have Tpetra without Kokkos

**Review by marcfehling — APPROVED** [review]

**Comment by tamiko** [comment]
@drwells We also set up openmp in `check_01_cpu_features.cmake` - so we should be good. :-)

**Pull request merged**
