### PR TITLE
Re-instantiate deprecated unprefixed ConstantFunction and ZeroFunction

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes https://github.com/dealii/dealii/issues/10677.

### CODE REVIEW

**Review by peterrum — APPROVED** [review]

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
Do you want `DEAL_II_DEPRECATED` or `DEAL_II_DEPRECATED_EARLY`? I don't care much either way...

**Comment by masterleinad** [comment]
This has been deprecated in the previous release already so I don't see a reason to go with `DEAL_II_DEPRECATED_EARLY`.

**Review by bangerth — APPROVED** [review]

**Comment by peterrum** [comment]
Thanks @masterleinad! One less item on the 9.3 list :)

**Pull request merged**
