### PR TITLE
Add a couple of static asserts to SolutionTransfer.

### PR DESCRIPTION
**Pull request by bangerth**
This class (in both of its incarnations) takes both a dimension and a DoFHandler
as template argument. The dimension of the DoFHandler better match the explicitly
given dimension. The added static_assert checks that and prevents instantiation
of the class if that is not the case.

### CODE REVIEW

**Comment by drwells** [comment]
This looks fine, but is this one of those odd cases that MSVC doesn't like with static asserts on integral template parameters? We might have to disable the check on Windows.

**Comment by bangerth** [comment]
I have no idea and no way to test. What to do? Fix it next time someone tries to compile on MSVC? Add the guard even though it may not be necessary?

**Comment by drwells** [comment]
@tjhei I think that you were the one who dealt with these things most recently. I suggest that we surround this with `#ifndef DEAL_II_MSVC` unless someone has a Windows tester available. Does this sound reasonable?

**Comment by bangerth** [comment]
Maybe like this?

**Comment by drwells** [comment]
This looks good to me. We can remove these when MSVC fixes their `static_assert` implementation.

**Pull request merged**
