### PR TITLE
Make GMSH with API appear in doc.

### PR DESCRIPTION
**Pull request by luca-heltai**
Make sure new GMSH read_msh function shows up in doc.

### CODE REVIEW

**Review by drwells — APPROVED** [review]

**Review by peterrum — APPROVED** [review]
Looks good once you have made `indentation` happy!

**Comment by bangerth** [comment]
@luca-heltai Ping?

**Comment by luca-heltai** [comment]
I have no idea where the problem may be. As soon as I have some time to explore this, I'll try to figure out where Doxygen is complaining.

**Comment by bangerth** [comment]
```
/home/runner/work/dealii/dealii/include/deal.II/grid/grid_in.h:892: warning: reached end of file while inside a f$ block!
The command that should end the block seems to be missing!

/home/runner/work/dealii/dealii/include/deal.II/grid/grid_out.h:1953: warning: reached end of file while inside a f$ block!
The command that should end the block seems to be missing!
```
I bet you forgot a dollar sign somewhere...

**Comment by bangerth** [comment]
In the documentation of the gmsh functions in grid_in.h, we have this:
```
   * @code
   * $PhysicalNames // same as MSH version 2
   *   numPhysicalNames(ASCII int)
   *   dimension(ASCII int) physicalTag(ASCII int) "name"(127 characters max)
   *   ...
   * $EndPhysicalNames
   * @endcode
   *
   * For example, the following snippet of mesh file
   * @code
   * MeshFormat
   * 4.1 0 8
   * $EndMeshFormat
   * $PhysicalNames
   * 4
   * 1 1 "ManifoldID:0"
   * 1 2 "BoundaryID: -1, ManifoldID: 1"
   * 2 3 "ManifoldID: 1"
   * 2 4 "MaterialID: 2, ManifoldID: 1"
   * $EndPhysicalNames
   * $Entities
   * ...
   * @endcode
```
I think the various dollar signs here must be escaped with a backslash.

**Comment by luca-heltai** [comment]
Even if they are between `@code` and `@endcode`??

**Comment by luca-heltai** [comment]
That was an easy fix. :)

**Comment by bangerth** [comment]
There you go, glad to hear it worked!

**Pull request merged**
