### PR TITLE
Check that we can read from/write to streams.

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Review by drwells — APPROVED** [review]

**Comment by bangerth** [comment]
The failing check fails in the test `examples/step-33`. This must be unrelated.

**Comment by jpthiele** [comment]
> The failing check fails in the test `examples/step-33`. This must be unrelated.

That one also failed on the regression tester, so I'd agree with it being unrelated.

**Review by masterleinad — APPROVED** [review]

**Comment by masterleinad** [comment]
You'll have to resolve the merge conflict.

**Comment by bangerth** [comment]
Resolved and tests correctly now.

**Review by tjhei — APPROVED** [review]

**Pull request merged**
