### PR TITLE
Avoid usage of the ArborX access traits in polymorphic contexts

### PR DESCRIPTION
**Pull request by masterleinad**
A discussed in https://github.com/dealii/dealii/pull/11963#issuecomment-811072031.

@Rombur Please test that this actually works for you.

### CODE REVIEW

**Comment by Rombur** [comment]
Actually I was thinking about this more, shouldn't we keep the public inheritance and instead have all the functions (including the constructor) of the base predicate protected. That way the base class cannot be used at all.

**Comment by bangerth** [comment]
That's fine with me as well. I think any solution is good with me if maybe we just augment the documentation of the base class. When I read "base class", I think "interface", but that's not how this is done here. It's just a way to provide some "basic functionality" ("basic" as in the adjective for "base"). If you just write the documentation of the base class as stating that, that would be ok as well.

**Comment by masterleinad** [comment]
> Actually I was thinking about this more, shouldn't we keep the public inheritance and instead have all the functions (including the constructor) of the base predicate protected. That way the base class cannot be used at all.

If we want to prevent use in a polymorphic context, i.e.
```
Base* base = new Derived;
```
we need to derive protectedly or privately and we need to import the functions anyway (even if we derive publically and define the whole body of the base class as `protected`) to access the member functions.
Thus, we could additionally have the body of the base classes protected to disallow creating base class instances but not replace the approach here.

**Comment by masterleinad** [comment]
I used https://godbolt.org/z/PrYev6Pn4 for playing with this.

**Review by Rombur — APPROVED** [review]
Thanks for the PR @masterleinad

**Pull request merged**
