### PR TITLE
Fix find_all_active_cells_around_point()

### PR DESCRIPTION
**Pull request by peterrum**
@mschreter Could you take over and add a test. Thx!

### CODE REVIEW

**Comment by mschreter** [comment]
This PR extends `find_all_active_cells_around_point()` to return the right number of cells for a point located on the cell edge/corner between elements of different refinement levels, e.g. as the pink marked point in the figure below.

image

Previously if the pink point was requested withing `RemotePointEvaluation`, the following assert would have been triggered:

```
--------------------------------------------------------
An error occurred in line <352> of file </home/much/work/libs/dealii/include/deal.II/grid/tria_iterator.templates.h> in function
    dealii::TriaActiveIterator<Accessor>::TriaActiveIterator(const dealii::TriaIterator<Accessor>&) [with Accessor = dealii::CellAccessor<1, 1>]
The violated condition was: 
    this->accessor.has_children() == false
Additional information: 
    (none)
```
@nmuch FYI

**Comment by mschreter** [comment]
Ready to review from my side!

**Review by kronbichler — APPROVED** [review]

**Comment by peterrum** [comment]
@mschreter Could you add a change-log entry?

**Review by peterrum — COMMENTED** [review]
@mschreter  Thanks :+1:

**Review by masterleinad — APPROVED** [review]

**Comment by peterrum** [comment]
@mschreter When looking at the picture in https://github.com/dealii/dealii/pull/14728#issuecomment-1420534989, I think you are testing at the wrong place. It should be at (0.5, 0.25). Also would it be possible to switch the order of refinement. You have refined left. I would like to see also on the right. The motivation is that it makes the difference from which side the algorithm is run.

**Comment by mschreter** [comment]
> @mschreter When looking at the picture in [#14728 (comment)](https://github.com/dealii/dealii/pull/14728#issuecomment-1420534989), I think you are testing at the wrong place. It should be at (0.5, 0.25). Also would it be possible to switch the order of refinement. You have refined left. I would like to see also on the right. The motivation is that it makes the difference from which side the algorithm is run.

I've tested (0.25,0.25), which is not a hanging node but is connected to cells at different levels. I thought this should be a critical point as well (not only hanging nodes). Nevertheless, I could extend the test case in a follow-up PR regarding (i) including a hanging node request and (ii) switching refinement direction.

**Pull request merged**
