### PR TITLE
Guard Belos code with macros

### PR DESCRIPTION
**Pull request by Rombur**
We assumed that Belos package was present without checking for it. Add a check and guard Belos code with macros

### CODE REVIEW

**Review by peterrum — APPROVED** [review]
Thanks.

**Review by kronbichler — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]

**Comment by bangerth** [comment]
Follow-up to #14352.

**Comment by bangerth** [comment]
The cuda check fails. I believe that happens not just here.

**Review by bangerth — APPROVED** [review]

**Pull request merged**
