### PR TITLE
Dealii 8.5

### PR DESCRIPTION
**Pull request by ExtremOPS**
Hi deal.ii-team,

I discussed this issue with Martin @kronbichler and he suggested that I propose the little fix myself.

I encountered an aesthetic problem when I used the print_svg(...) function of SparsityPattern. The function creates two rectangles, a grey one (as frame for the svg) and a white one (as background for the visualization), before the entries of the matrices are plotted with little reds rectangles. 

If an input is visualized in the last row or colum the red rectangle "touches" directly the grey frame; this does not happen for the first row or column because there is a little gap of 0.1 pixels.

Therefore my propose for resolving this minor issue is to change line 875 of [SparsityPattern](https://www.dealii.org/8.4.0/doxygen/deal.II/sparsity__pattern_8cc_source.html)
from 
`"   <rect x=\"1\" y=\"1\" width=\"" << n << "\" height=\"" << m`
to
`"   <rect x=\"1\" y=\"1\" width=\"" << n+0.1 << "\" height=\"" << m+0.1`
in order to have a litte white gap around all red rectangles which are at the boundaries of the matrix.

If there are any question, do not hesitate to ask me.

Christoph

### CODE REVIEW

**Comment by davydden** [comment]
please rebase on `master`.

**Comment by davydden** [comment]
p.s. I am sure you did not plant to add `1072` and remove `2738` lines 😄

**Comment by davydden** [comment]
oh, and please create a PR to `master` branch, not `dealii-8.5`.

**Comment by ExtremOPS** [comment]
Sorry for the confusion. I just want to change one line :-)

**Comment by kronbichler** [comment]
I will fix this together with @ExtremOPS on Thursday.

**Comment by bangerth** [comment]
Also, @ExtremOPS: Thanks a lot for the patch and your willingness to fix something in deal.II! We're glad for every patch we can get, and look forward to have you among the contributors of deal.II!

I don't actually see the changes you want to make in the patch (maybe because there are all of the other changes) but if you don't want to wait till @kronbichler can help you with it, try this:
```
  git checkout master          # go to the main development branch
  git pull upstream master   # assuming that 'upstream' is https://github.com/dealii/dealii
  git checkout -b fix-svg       # create a side branch
  git cherry-pick nnnnnnn
```
In the last step, `nnnnnnn` is the commit hash of the commit in which you had made the change you wanted to propose. This moves the change you had to the branch `fix-svg`.

Then push this branch to your github repository:
```
  git push origin fix-svg
```
and when you go to http://github.com/dealii/dealii, it should give you the option to create a new pull request that now only contains the one commit you cared about!

**Comment by bangerth** [comment]
Superseded by #5587

**Pull request closed without merging**
