### PR TITLE
scalapack: query lwork from ppocon

### PR DESCRIPTION
**Pull request by davydden**
i was trying to fix `scalapack_05` on some testers https://cdash.kyomu.43-1.org/testSummary.php?project=1&name=scalapack%2Fscalapack_05.mpirun%3D4.debug&date=2018-02-15 
and was digging into the code. 

Looks like `lwork` is wrong, [IBM](https://www.ibm.com/support/knowledgecenter/SSNR5K_4.2.0/com.ibm.cluster.pessl.v4r2.pssl100.doc/am6gr_lpocon.htm#lpocon) states this as:
```
 lwork ≥ 2np0 + 2nq0 + max(2, max(nb(max(1, iceil(nprow-1, npcol))), nq0 + nb(max(1, iceil(npcol-1, nprow)))))

mb = MB_A
nb = NB_A
iroff = mod(ia-1, mb)
icoff = mod(ja-1, nb)
iarow = mod(RSRC_A + (ia-1)/mb, nprow)
iacol = mod(CSRC_A + (ja-1)/nb, npcol)
np0 = NUMROC(n+iroff, mb, myrow, iarow, nprow)
nq0 = NUMROC(n+icoff, nb, mycol, iacol, npcol)
```
and [netlib-scalapack](http://www.netlib.org/scalapack/explore-html/d6/d68/pspocon_8f_source.html) as
```
       LWORK >= 2*LOCr(N+MOD(IA-1,MB_A)) + 2*LOCc(N+MOD(JA-1,NB_A))+
             MAX( 2, MAX(NB_A*CEIL(NPROW-1,NPCOL),LOCc(N+MOD(JA-1,NB_A)) +
             NB_A*CEIL(NPCOL-1,NPROW)) ).
```

in our case `IA=JA=1` so things are simpler, but still there were no `max` and alike in 
```
int lwork = 2 * n_local_rows + 3 * n_local_columns + column_block_size;
```

To be on the safe side we can query the right number from `ppocon`. 

p.s. this does not fix the `float` test for me, it still hangs on MPI=4 run with a `32x32` matrix with block-size `32` (process grid will consist of one core only here). `double` works just fine, so does `float` with 1 MPI core...

### CODE REVIEW

**Comment by bangerth** [comment]
OK to merge once the tester is happy.

**Comment by davydden** [comment]
For the record, i know what's going on with that `scalapack_05` test. It's another Fortran symbol conflict due to faulty pArpack. Should be `pslamch` (I submitted a patch, will find out if it helps). As soon as I disable pArpack in deal.ii, the test runs fine. @BenBrands , who extended ScaLAPACK functions to run with `float` and modified that test, did not see this issue as he is not building dealii with pArpack.

**Comment by bangerth** [comment]
Oh, are you saying that both SCALAPCK and PArpack have functions called `pslamch` and that the linker chooses one or the other randomly? If so, Ouch!

Can you post a link to your patch, if it's in some public repo, for posterity?

**Comment by bangerth** [comment]
Ah, found it: https://github.com/opencollab/arpack-ng/issues/50

**Comment by davydden** [comment]
> Oh, are you saying that both SCALAPCK and PArpack have functions called pslamch and that the linker chooses one or the other randomly? If so, Ouch!

yeap, Arpack used to have `pdlamch` but i fixed it in https://github.com/opencollab/arpack-ng/pull/21

**Pull request merged**
