### PR TITLE
Fix bug in threaded matrixfree

### LINKED ISSUE #3134: MatrixFree partition_partition gives segmentation fault in the unit test
```
$ git diff
diff --git a/tests/matrix_free/parallel_multigrid_adaptive.cc b/tests/matrix_free/parallel_multigrid_adaptive.cc
index 0de815a..5758aad 100644
--- a/tests/matrix_free/parallel_multigrid_adaptive.cc
+++ b/tests/matrix_free/parallel_multigrid_adaptive.cc
@@ -62,8 +62,8 @@ public:
   {
     const QGauss<1> quad (n_q_points_1d);
     typename MatrixFree<dim,number>::AdditionalData addit_data;
-    addit_data.tasks_parallel_scheme = MatrixFree<dim,number>::AdditionalData::none;
-    addit_data.tasks_block_size = 3;
+    addit_data.tasks_parallel_scheme = MatrixFree<dim,number>::AdditionalData::partition_partition;
+    //addit_data.tasks_block_size = 3;
     addit_data.level_mg_handler = level;
     addit_data.mpi_communicator = MPI_COMM_WORLD;
     ConstraintMatrix constraints;
```
leads to segmentation fault during `data.reinit()` for `mpirun=3` both in `debug` and `release`. I don't think it is expected behaviour.

@kronbichler any ideas?

### PR DESCRIPTION
**Pull request by kronbichler**
Fixes #3134

### CODE REVIEW

**Comment by davydden** [comment]
please check the whole `matrix_free` tests, for me output of `matrix_free/parallel_multigrid_adaptive_mf.mpirun=7` changed a bit.

**Comment by kronbichler** [comment]
All tests through `ctest -R matrix_free` pass.

**Comment by davydden** [comment]
ok, then we difference i see is probably related to `clang` vs `gcc` and not caused by this PR... Still waiting for `$ ctest -R "matrix_free/"` to finish...

**Comment by davydden** [comment]
👍

**Pull request merged**
