### PR TITLE
Require PETSc to be configured with MPI support

### PR DESCRIPTION
**Pull request by masterleinad**
Follow-up to  #15781 addressing https://github.com/dealii/dealii/pull/15781#issuecomment-1646936892.

### CODE REVIEW

**Review by tamiko — APPROVED** [review]

**Comment by stefanozampini** [comment]
I don't understand the argument treat PETSc like Trilinos. PETSc works without MPI and I don't see the reason you should not let users use it. Just my opinion

**Comment by drwells** [comment]
What was the exact error the user ran into? I agree that things should work here and its a little suspicious that they don't - there may be some other bug.

**Comment by bangerth** [comment]
The error had nothing to do with PETSc at all. It was that in one of our PETSc wrappers, we were using `Utilities::MPI::mpi_type_id_for_type`.

**Review by tjhei — APPROVED** [review]
Supporting petsc without MPI would require creating test coverage and regression testing. Considering the limited use case, I prefer disabling this configuration instead.

**Pull request merged**
