### PR TITLE
Relax asserts

### PR DESCRIPTION
**Pull request by peterrum**

### CODE REVIEW

**Review by blaisb — APPROVED** [review]
I don't see a problem with this, but can you explain a bit why you need this change? Just for pedagogy's sake

**Comment by peterrum** [comment]
I want to add additional DoFs to the system, which I manually manage and use for multi-point constraints.

**Review by bangerth — COMMENTED** [review]
I'm opposed to this patch. If you allow the +1 for one extra dof, then why not +2? +3?

Many years ago, we used to have an extension to DoFHandler whereby DoFs could be renumbered in such a way that there were holes. This led to all sorts of issues and we got rid of it. I will also point out that surely it isn't just these two assertions you will trigger (or others will trigger who will now feel encouraged to use the same approach), and you will have to go through the entire library fixing up assertions.

**Comment by peterrum** [comment]
> I'm opposed to this patch. If you allow the +1 for one extra dof, then why not +2? +3?

This is not about 1/2/3 additional DoFs. I am checking a range: at least all DoFs of the DoFHandler should be contained.

**Comment by bangerth** [comment]
I read the assertion the wrong way around, but my point remains: This will lead us to an endless chase throughout the entire library for all of the assertions that have to be relaxed. It also diminishes the ability to give good error message, namely by saying "This object has size X, but the size needs to be Y."

I continue to be opposed to this kind of change. If you want additional degrees of freedom, build a block matrix where one of the blocks has size `n_dofs()` and the other degrees of freedom live in the other blocks.

**Comment by blaisb** [comment]
I am not aware of the history here, but it seems there is some strong opinion agaisn't this PR which are well argued. Are you satisfied with the counter-arguments @peterrum ? In the latter case, I will let you close the PR :).

**Comment by peterrum** [comment]
No, I am not. I don't see the problem that one could embed a matrix into an other one, without the need to create a block matrix. For block matrices, there are less functionalities (like solvers). So one would need to copy one type of matrix to another one.

**Comment by blaisb** [comment]
I understand your point. Maybe we could schedule a zoom/slack discussion on the topic to reach a new consensus? Who would like to be present other than  @bangerth and @peterrum ?
I'll be there to facilitate the discussion. I'd like to make this as fun as possible :).

**Comment by drwells** [comment]
I basically agree with Wolfgang here - that function creates a Laplace matrix and shouldn't do something else. We should be consistent with these semantics in `MatrixCreator`. I can think of a couple of ways to accomplish that and the underlying goal:

- add a new function `make_augmented_laplace_matrix()` with these relaxed assertions which calls some assertion-less internal function
- block matrices (everything should work with block matrices just as well as non-block matrices - that sounds like something we should fix anyway)
- assemble the matrix yourself (not that hard, but annoying)
- null space removal

**Comment by blaisb** [comment]
> I basically agree with Wolfgang here - that function creates a Laplace matrix and shouldn't do something else. We should be consistent with these semantics in `MatrixCreator`. I can think of a couple of ways to accomplish that and the underlying goal:
> 
> * add a new function `make_augmented_laplace_matrix()` with these relaxed assertions which calls some assertion-less internal function
> * block matrices (everything should work with block matrices just as well as non-block matrices - that sounds like something we should fix anyway)
> * assemble the matrix yourself (not that hard, but annoying)
> * null space removal

Although I agree with your point, there are still many places where one could want to generate a matrix using a DOF handler and add additional equations on top of that without using a block matrix. Say I would like, for example, to solve a solid mechanics problem and add additional equations for fixing some rigid body motion or something else, then I could naively want to add  6 equations to my set of equation. If I use a block matrix to achieve this, I cannot use a direct solver straightforwardly and I will need to go through many hoops and loops. I  kinda see where @peterrum is trying to get at...

**Comment by drwells** [comment]
It isn't directly related to the issue here but you should know that `SparseDirectUMFPACK` definitely supports `BlockSparseMatrix`.

**Comment by tamiko** [comment]
We tend to revisit the topic of having a more flexible DoFHandler from times to times. For example for isogeometric analysis we would need to be able to manage an additional number of degrees of freedom (@luca-heltai). And I vagely remembered one or two use cases for some hyperbolics where I wanted to have a more flexible degree of freedom handler.

Thinking about this problem (with too much coffee and not enough sleep) for a minute I think it boils down to the fact that by design we do not allow to concatenate unrelated degree of freedom handlers (or at least their index ranges). What I mean by that is
 - we can concatenate (or take the product) of various finite elements via `FE_System` for a given triangulation and manage a dof range with that via `DoFHandler`.
 - but sometimes it would be really handy to be able to concatenate the global degrees of two sets of `FE_System` and independent triangulations into one `DoFHandler`.
 - This concatenation doesn't really need to be in `DoFHandler`, but rather at the interface between assembly and writing/interacting with matrix structures and vectors.

I think this is in essence what is missing for geometric analysis and what Peter is missing for his multipoint constraints. ... and incidentally what I was missing for "stencil-based methods" (a simple "now take this scalar `DoFHandler` and repeat it 5 times").

So given the fact that I can think of three use cases, I'd say it might be worthwhile discussing how to support such a thing.

**Review by tamiko — CHANGES_REQUESTED** [review]
pending discussion.

**Comment by bangerth** [comment]
I should note that @juleoc02 implemented these kinds of free-floating DoFs using an hp approach with a system of elements where on all but one cell, the last vector component is an `FE_Nothing`, and on one cell it is an element that has as many degrees of freedom as one needs. This is in a pending program for the code gallery: https://github.com/dealii/code-gallery/pull/156 

Specifically, take a look here:
https://github.com/dealii/code-gallery/pull/156/files#diff-88b40e02c4dde50695b08f145dc9e82af38aa23c59077ed32a0aa8cab7173695
Search for `fe_nine` and `fe_ten` and then later on where the active fe index is set on one cell.

This is perhaps not the most elegant way to solve this issue, but it ensures that there remains a 1:1 association of unknowns to DoFs, a 1:1 association of DoFs to cells, a 1:1 association of rows/columns to DoFs. If you do the usual blocking of matrices and vectors based on vector components, you also nicely get a block for these specific DoFs, which oftentimes has different mathematical structures than what comes out of differential operators, and you can use that for Schur complementing and preconditioning.

**Comment by bangerth** [comment]
What do we want to do here? @peterrum ?

**Comment by peterrum** [comment]
Let's agree that we don't agree. Closing.

**Pull request closed without merging**
