### PR TITLE
tests: extra output for memory_consumption_01

### PR DESCRIPTION
**Pull request by davydden**

### CODE REVIEW

**Comment by bangerth** [comment]
Anything interesting in the difference between your output and the saved output?

**Comment by davydden** [comment]
> Anything interesting in the difference between your output and the saved output?

i would not say so. There are **already four** different outputs, a few first diffs w.r.t. the first one are
```
----------------
##6       #:6   <== 3090
##6       #:6   ==> 2842
@ Absolute error = 2.4800000000e+2, Relative error = 8.7262491203e-2
----------------
##7       #:6   <== 1016
##7       #:6   ==> 992
@ Absolute error = 2.4000000000e+1, Relative error = 2.4193548387e-2
----------------
##8       #:6   <== 1480
##8       #:6   ==> 1224
@ Absolute error = 2.5600000000e+2, Relative error = 2.0915032680e-1
```

**Comment by bangerth** [comment]
Your system seems to require substantially less memory. Nice :-)

**Comment by bangerth** [comment]
Are you on a 32-bit system, btw?

**Comment by davydden** [comment]
> Are you on a 32-bit system, btw?

macOS is 64-bit, AFAIK

**Comment by bangerth** [comment]
Hm, how interesting. Apparently clang's C++ library is just more memory efficient then...

**Pull request merged**
