### PR TITLE
Attach a TorusManifold to a Torus.

### PR DESCRIPTION
**Pull request by drwells**
It would be nice to include this in 9.0 but it is getting late.

### CODE REVIEW

**Comment by tamiko** [comment]
@drwells If this is the last geometry to update, it is worth getting this into 9.0 as well. I suggest we merge to master once the CI is happy and if we do not see any fallout there, we cherry pick to the release.

**Comment by drwells** [comment]
Its worth noting that this function is used nowhere in the library and in exactly one test, so chances of trouble are very small.

**Comment by tamiko** [comment]
Does this close #6274?

**Comment by tamiko** [comment]
@drwells The even stronger argument is the fact that with this change our grid generator functions now behave uniformly.

**Comment by tamiko** [comment]
> I am rereading `grid_generator.h` now: we still need to update a few
> sentences (e.g., the description of `quarter_hyper_shell` does not
> mention the manifold attachment).
>
> Another possible problem is the triangulation merging functions. I
> believe that we cannot make general conclusions about the resulting
> geometry, so having a warning in the documentation stating "the
> resulting triangulation does not inherit any manifolds" should
> suffice: that also needs to be added.
>
> Once we do that we should be set.

Sounds good!

Also, pure documentation updates are relatively painless to merge to the
release branch ;-)

**Comment by luca-heltai** [comment]
we have a problem:

~~~
===============================   OUTPUT BEGIN  ===============================
grid/torus_01.debug: BUILD failed. Output:
Generating torus_01.debug/interrupt_guard.cc
Scanning dependencies of target torus_01.debug
Building CXX object CMakeFiles/torus_01.debug.dir/torus_01.cc.o
/home/bob/source/tests/grid/torus_01.cc: In function â€˜void test() [with int dim = 3; int spacedim = 3]â€™:
/home/bob/source/tests/grid/torus_01.cc:54:11: error: â€˜desc_torusâ€™ was not declared in this scope
       x = desc_torus.push_forward(x);
           ^
make[3]: *** [CMakeFiles/torus_01.debug.dir/torus_01.cc.o] Error 1
make[2]: *** [CMakeFiles/torus_01.debug.dir/all] Error 2
make[1]: *** [CMakeFiles/torus_01.debug.diff.dir/rule] Error 2
make: *** [torus_01.debug.diff] Error 2


grid/torus_01.debug: ******    BUILD failed    *******
~~~

**Comment by drwells** [comment]
I am making stupid mistakes; its a good thing we have the tester back up.

I will post a fix in a moment.

**Pull request merged**
