### PR TITLE
Remove deprecated tria_boundary*.h

### LINKED ISSUE #6782: Re-remove tria_boundary*.h
#6770 re-added two header files for compatibility reasons, but we should remove them again after 9.1 is released.

### PR DESCRIPTION
**Pull request by kronbichler**
Closes #6782.

### CODE REVIEW

**Comment by tjhei** [comment]
I still see the file included in tests/ad_common_tests/step-44-helper_scalar_01.h
Can you check?

**Comment by kronbichler** [comment]
Absolutely, I only grepped for the `.cc` files. I fixed it now.

**Comment by tjhei** [comment]
:+1: ready to merge!

**Comment by drwells** [comment]
RIP `Boundary`

**Comment by jppelteret** [comment]
> RIP Boundary

We best take the rest of the day off to mourn our loss 😭

**Pull request merged**
