### PR TITLE
Remove our deprecated netcdf bindings

### PR DESCRIPTION
**Pull request by drwells**
Note that we don't really support netcdf - we support the netcdf C++ legacy bindings. These were deprecated in #7392.

### CODE REVIEW

**Comment by tjhei** [comment]
Wait, what? I was going to use netcdf for a project.

**Comment by drwells** [comment]
I don't understand what you are asking - what parts of our netcdf bindings would you like to use?

**Comment by drwells** [comment]
> So, can we keep netcdf as a dependency

Its important to note that we depend on a package usually named `netcdf-cxx-legacy` and not the current version of netcdf because no one has ported our older C++ wrappers to their newer API.

**Comment by tamiko** [comment]
@tjhei What about you simply adopt the `FindNETCDF.cmake` file into your own project (replacing the `DEAL_II_PACKAGE_HANDLE` call with an export target. I am happy to write that for you.

**Comment by tjhei** [comment]
I would like to introduce functionality to use netcdf I/O, but I can use the C library and reintroduce the cmake functionality if you insist on removing it now. Otherwise, I would suggest we leave the cmake handling in place and just remove the deprecated Grid functionality right now.

**Comment by drwells** [comment]
As far as I can tell we don't currently support linking with the netcdf C library - we only link against `libnetcdf_c++`, so removing this shouldn't impact your use case.

Perhaps your netcdf package is installed in a different way than mine is. Can you compile and link, with the current deal.II netcdf configuration, with/against the netcdf c library you want to use?

**Comment by kronbichler** [comment]
Can you please rebase?

**Comment by tjhei** [comment]
> Can you compile and link, with the current deal.II netcdf configuration, with/against the netcdf c library you want to use?

no, I have netcdf and netcdf-cxx installed.

**Comment by drwells** [comment]
I rebased.

As far as I can tell this is unrelated to @tjhei's use case so lets go ahead with removing.

**Pull request merged**
