### PR TITLE
Correct memory access in grid_tools_guess_pt_owner_02

### PR DESCRIPTION
**Pull request by kronbichler**
@GivAlz for your information, here is what I suggested in #7752.

### CODE REVIEW

**Comment by GivAlz** [comment]
Thank you for correcting it, and sorry for this blunder...

**Comment by kronbichler** [comment]
You're welcome - that's why we are most productive in code development as a community! (I have made plenty of those myself.)

**Comment by kronbichler** [comment]
The affected test passed the pipeline, mergin.

**Pull request merged**
