### PR TITLE
CMake: Link in Boost libraries for ADOLc check

### PR DESCRIPTION
**Pull request by tamiko**
@tjhei Can you give this PR a try, please?

Closes: #6334

### CODE REVIEW

**Comment by jppelteret** [comment]
@tamiko I think that this should only be done if `ADOL-C` is configured to use `BOOST_POOL`. Please see [here](https://gitlab.com/adol-c/adol-c/blob/master/ADOL-C/include/adolc/internal/adolc_settings.h.in#L37) - this is the file from which I made our CMake module detect which other features of `ADOL-C` are enabled.

Side note: I have no idea how to get `ADOL-C` to detect a boost configuration. I couldn't get this to work with my spack setup, and there do not appear to be any configure-time flags that can be passed, so I'm interested to find that it was automatically detected with @tjhei configuration.

**Comment by tjhei** [comment]
> so I'm interested to find that it was automatically detected with @tjhei configuration.

yes, it was on one of my machines. Installed using https://github.com/dealii/candi/pull/66

**Comment by jppelteret** [comment]
@tjhei Do you have boost in path? Since I'm using Spack on my Linux machine I believe that I do not (although I will double check this tomorrow). In the mean time I'll try again to get ADOL-C to detect boost on my Mac to see if I can help debug this. I might not be able to get this done tonight though.

**Comment by jppelteret** [comment]
@davydden You probably have the same setup as me - ADOL-C does not detect boost, and therefore is not configured with it enabled.

**Comment by jppelteret** [comment]
> The machine in questions only has boost_system so deal.II wants to use the bundled boost. Of course that means I am screwed and this PR doesn't help.

Unless we can find a way to explicitly tell ADOL-C not to use boost from within the Candi script.

**Comment by jppelteret** [comment]
@tjhei Check [this out](https://github.com/facebook/folly/blob/master/folly/m4/ax_boost_base.m4#L40-L45). Can you try adding `--with-boost=no` to the Candi script?

**Comment by davydden** [comment]
> Can you try adding --with-boost=no 

one should also see those options from `./configure --help`

**Comment by tjhei** [comment]
> Can you try adding --with-boost=no to the Candi script?

that works. I assume we are not losing much by not using the boost allocator?

**Comment by jppelteret** [comment]
Ok, so I finally got Adol-C to detect boost. We should definitely add a check to our CMake module to check whether `adolc_settings.h` has
```
#define USE_BOOST_POOL 1
```
If so then we should expect the user to not use our bundled boost - the correct link line for ADOL-C is defined in `lib64/pkgconfig/adolc.pc`.

For my own records, this is how I configured Adol-C with boost:
```
git clone git@gitlab.com:adol-c/adol-c.git
cd adol-c

# Nuclear approach to setting things up using autoconf
libtoolize --force
aclocal
autoheader
automake --force-missing --add-missing
autoconf

./configure \
--prefix=${PWD}/../install \
--with-boost=<spack path>/spack/opt/spack/darwin-elcapitan-x86_64/clang-8.0.0-apple/boost-1.63.0-x4d27xpz2aara47cmymt3znv3adxdqj7 \
--enable-atrig-erf
```

**Comment by jppelteret** [comment]
> I assume we are not losing much by not using the boost allocator?

@tjhei I have no idea, as I have not been using it up till now. But I'm now in a position to check it out :-)

**Comment by tamiko** [comment]
All, thanks for the feedback. Will implement the necessary changes :-)

**Comment by jppelteret** [comment]
Thanks @tamiko :-)

**Comment by tamiko** [comment]
@jppelteret Unrelated question - out of curiosity, is there actually a reason why someone want to disable "advanced branching", or "atrig-erf"? Too experimental?

**Comment by tamiko** [comment]
@tjhei @jppelteret Please give this version a try.

**Comment by jppelteret** [comment]
> Unrelated question - out of curiosity, is there actually a reason why someone want to disable "advanced branching", or "atrig-erf"? Too experimental?

Nope, from my point of view these are both essential features (and as best I can tell they were implemented ages ago). But they're both disabled by default, hence the checks.

> Please give this version a try.

Sure, but unfortunately I'll have to do this tomorrow. It looks good though, thanks!

**Comment by davydden** [comment]
@tamiko you need to rebase.

**Comment by tamiko** [comment]
@davydden Rebased and ready to be merged.

**Comment by tamiko** [comment]
@jppelteret 
> Well, since I don't think that any of our testing infrastructure has ADOL-C enabled, ...

`tester` has adolc installed (some live version from March - April this year) on almost all of the configurations :-)

**Comment by jppelteret** [comment]
@tamiko We should probably update the wiki then. Apologies :-/

**Pull request merged**
