### PR TITLE
replace Assert with AssertThrow in tests/base

### PR DESCRIPTION
**Pull request by rezarastak**
The first attempt to address [this comment](https://github.com/dealii/dealii/pull/9492#discussion_r376660548).

I only modified the tests in `tests/base/` except `tests/base/assertion_macros.cc`. I added a paragraph to the documentation for developers specifying that we prefer `AssertThrow` to `Assert` in the test codes. Since the Jenkins CI doesn't check the tests in the release build, I ran the test suite on my machine and the tests passed as expected. I will apply this to the rest of the test suite soon.

### CODE REVIEW

**Comment by rezarastak** [comment]
@peterrum That's correct. We won't be able to change those. But changing `Assert` to `AssertThrow` is an improvement that we can make.

**Comment by tamiko** [comment]
A much more pragmatic way that I recommend to pursue would be to override the Assert preprocessor macro in the testsuite for release mode - that way you get the desired behavior (i.e. `Assert` in tests also trigger in release mode) without changing a single line of code in the tests.

**Comment by tjhei** [comment]
> A much more pragmatic way that I recommend to pursue would be to override the Assert preprocessor macro in the testsuite for release mode

I was thinking the same. 

Option 1:
Modify our assert() macro with a
```
#ifdef ASSERT_ALSO_IN_RELEASE_MODE
 #define Assert bla
```
Do we have already have a macro defined for all source when running the test suite? If not, this could be useful to add.

Option 2:
We could simply override the Assert macro in tests/tests.h. This assumes tests.h is included last.

**Comment by bangerth** [comment]
On 2/10/20 7:14 AM, Timo Heister wrote:
> 
> We could simply override the Assert macro in tests/tests.h. This assumes 
> tests.h is included last.

Or first -- in which case you also convert the occurrences of Assert in the 
deal.II header files. You'd then have to make sure that tests/tests.h includes 
base/exceptions.h so that a later inclusion of base/exceptions.h doesn't 
overwrite your definition of Assert any more.

**Comment by rezarastak** [comment]
> We could simply override the Assert macro in tests/tests.h. This assumes tests.h is included last.

If we go with this approach, I think we should have a check in the indentation script that ensures "../tests.h" is included last in all tests. Also, this requirement might be slightly confusing to the new contributors.

**Comment by masterleinad** [comment]
`clang-format` can take care of that.

**Comment by bangerth** [comment]
I'm ok with this, but because it's generated a bit of discussion here and in other PRs, I think it would be good if a second person approves and merges.

**Comment by masterleinad** [comment]
For me, the discussion reads like we rather want to override the Assert preprocessor macro in the testsuite.

**Comment by masterleinad** [comment]
Superseded by #9539.

**Pull request closed without merging**
