### PR TITLE
Create new string when demangling stacktraces

### LINKED ISSUE #17565: Significant delay with deal.II exceptions on MacOS
On MacOS/Apple Clang, deal.II exceptions experience significant delay.

Our `git bisect`, which resulted in patch #17552, was truncated prematurely.

The actual issue was introduced in  #17208: https://github.com/dealii/dealii/blob/adbb1e237f38ec31fd2d23b5ce102ebdbe4149e6/source/base/exceptions.cc#L288C7-L288C42 with the change of
`stacktrace_entry = stacktrace_entry.substr(0, pos_start);` to `stacktrace_entry.resize(pos_start);` on `line 288`.

Reverting this change eliminates the delay, but will reintroduce CppCheck's complaint about this line.

@ejtovar @tamiko @Rombur @masterleinad

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #17565. @harmonj Can you confirm that this works for you?

### CODE REVIEW

**Review by bangerth — APPROVED** [review]
Wild!

**Review by kronbichler — APPROVED** [review]

**Review by tjhei — APPROVED** [review]

**Comment by ejtovar** [comment]
@masterleinad @harmonj This works for me! @harmonj and I were having the same issue.

**Review by tamiko — COMMENTED** [review]
Merci!

**Comment by bangerth** [comment]
Is this something we'd like to backport to the release branch?

**Pull request merged**
