### PR TITLE
Link in the correct figure.

### PR DESCRIPTION
**Pull request by bangerth**
Follow-up to #11201 where the text no longer matched the figure. I'm fixing this by just linking in the corrected figure. See https://dealii.org/developer/doxygen/deal.II/namespaceGridGenerator.html#ac7515d2b17c025dddc0e37286fb8d216 for the current state.

@eliasstudiert -- FYI.

/rebuild

### CODE REVIEW

**Review by peterrum — COMMENTED** [review]
That was the correct figure  but the text was outdated.

**Comment by eliasstudiert** [comment]
> Follow-up to #11201 where the text no longer matched the figure. I'm fixing this by just linking in the corrected figure. See https://dealii.org/developer/doxygen/deal.II/namespaceGridGenerator.html#ac7515d2b17c025dddc0e37286fb8d216 for the current state.
> 
> @eliasstudiert -- FYI.
> 
> /rebuild

It's true text and figure don't belong together - my bad, I should have adapted the description. I suggest to either use both pictures or only the new one. If we use both, I could provide a nicer version of the image showing the quater_hypershell without the vertical separation line and less space in between.

**Comment by bangerth** [comment]
I think the figure is ok as is (or if you want, we can replace it at a later point). Is there an actual objection to the PR?

**Comment by bangerth** [comment]
Ping?

**Comment by masterleinad** [comment]
@eliasstudiert Is this fine with you?

**Review by eliasstudiert — APPROVED** [review]

**Review by peterrum — APPROVED** [review]
We will update the picture in a follow-up PR.

**Pull request merged**
