### PR TITLE
fixed history in ReductionControl::check() for final iteration

### LINKED ISSUE #5550: ReductionControl::check() does not log last iteration step to history_data
Hi,

the ReductionControl object does not correctly log the last iteration step. If the solution is below the given residual, the ReductionControl::check() method does not append the final iteration to the history data (around line 275 in solver_control.cc). Previous iterations are added via the call to the parent function SolverControl::check(). This causes an assert e.g. when calling average_reduction().

Can be easily fixed by adding the following lines 

```
      if (history_data_enabled)
        history_data.push_back(check_value);
```

### PR DESCRIPTION
**Pull request by jodlbauer**
Fixes #5550 

(hope everything works out ...)

### CODE REVIEW

**Comment by davydden** [comment]
please run indentation script `./contrib/utilities/indent` with `astyle@2.04` in path

**Comment by davydden** [comment]
can you please add a simple regression test to make sure this problem does not appear again if someone decides to refactor the class? See for example `tests/lac/solver_control_02.cc` or `tests/lac/solver_control_06.cc`. You don't really have to solve any system, just make sure the class behaves correctly.

**Comment by bangerth** [comment]
Also, thanks a lot for finding and fixing the bug, @jodlbauer ! Welcome among the contributors to deal.II!

Regarding the indentation and the test: it looks like you already figured this out, but if you need help, let us know!

**Pull request merged**
