### PR TITLE
Remove MPI_COMM_WORLD as default argument in write_vtu_with_pvtu_record

### PR DESCRIPTION
**Pull request by peterrum**
With the consent of @nfehn, I remove the default argument of the MPI communicator. ~Once everyone agrees, I will also update the tutorials, which use this new function.~

### CODE REVIEW

**Comment by masterleinad** [comment]
What's the rational for this change?

**Comment by peterrum** [comment]
@masterleinad 

Essentially if you work with some sub communicator and you forget to hand in the communicator, the function will not have the right behaviour because of this line:

https://github.com/dealii/dealii/blob/0cfddbdb65757c9ba398aeb5c791c862a8b55708/source/base/data_out_base.cc#L7205-L7206

and the code will deadlock because of

https://github.com/dealii/dealii/blob/0cfddbdb65757c9ba398aeb5c791c862a8b55708/source/base/data_out_base.cc#L7190

The change of this PR forces the user to specify explicitly the communicator as is the case for all the other functions in `DataOutInterface`.

**Comment by peterrum** [comment]
BTW: ping @tjhei

**Comment by masterleinad** [comment]
You will also need to fix all the examples this function is used in.

**Comment by peterrum** [comment]
@masterleinad I know: it's in the description of the PR.

**Comment by masterleinad** [comment]
> @masterleinad I know: it's in the description of the PR.

Well, you can't test if you can't compile.

**Comment by bangerth** [comment]
I'm in favor of this change. We shouldn't hard-code `MPI_COMM_WORLD`, and if possible shouldn't default to it either.

Are there other places where we use `MPI_COMM_WORLD` as a default?

**Comment by peterrum** [comment]
> Are there other places where we use MPI_COMM_WORLD as a default?

Yes. But not a lot...

**Comment by peterrum** [comment]
```
> grep -r MPI_COMM_WORLD .
./deal.II/base/mpi.h:#  ifndef MPI_COMM_WORLD
./deal.II/base/mpi.h:#    define MPI_COMM_WORLD 0
./deal.II/base/mpi.h:     * `MPI_COMM_WORLD` communicator. This means that you will have to
./deal.II/base/mpi.h:     * `MPI_COMM_WORLD` (for example, in client-server settings where
./deal.II/base/mpi.h:     * `MPI_COMM_WORLD` during initialization.
./deal.II/base/utilities.h:     * the communicator will correspond to MPI_COMM_WORLD, i.e. a communicator
./deal.II/base/data_out_base.h:   * data_out.write_hdf5_parallel(data_filter, "solution.h5", MPI_COMM_WORLD);
./deal.II/base/data_out_base.h:   *                                                  MPI_COMM_WORLD);
./deal.II/base/data_out_base.h:   * data_out.write_xdmf_file(xdmf_entries, "solution.xdmf", MPI_COMM_WORLD);
./deal.II/base/data_out_base.h:   * data_out.write_hdf5_parallel(data_filter, "solution.h5", MPI_COMM_WORLD);
./deal.II/base/hdf5.h: *                      MPI_COMM_WORLD);
./deal.II/base/hdf5.h:     * defines the processes that participate in this call; `MPI_COMM_WORLD` is
./deal.II/base/timer.h: *   TimerOutput timer (MPI_COMM_WORLD,
./deal.II/base/timer.h: *   timer.print_wall_time_statistics(MPI_COMM_WORLD);
./deal.II/base/index_set.h:#  ifndef MPI_COMM_WORLD
./deal.II/base/index_set.h:#    define MPI_COMM_WORLD 0
./deal.II/base/index_set.h:  make_trilinos_map(const MPI_Comm &communicator = MPI_COMM_WORLD,
./deal.II/base/index_set.h:  make_tpetra_map(const MPI_Comm &communicator = MPI_COMM_WORLD,
./deal.II/lac/block_sparsity_pattern.h:                         const MPI_Comm &communicator = MPI_COMM_WORLD);
./deal.II/lac/block_sparsity_pattern.h:      const MPI_Comm &             communicator = MPI_COMM_WORLD);
./deal.II/lac/block_sparsity_pattern.h:           const MPI_Comm &             communicator = MPI_COMM_WORLD);
./deal.II/lac/block_sparsity_pattern.h:           const MPI_Comm &             communicator = MPI_COMM_WORLD);
./deal.II/lac/block_sparsity_pattern.h:           const MPI_Comm &             communicator = MPI_COMM_WORLD);
./deal.II/lac/petsc_block_vector.h:                           const MPI_Comm &communicator = MPI_COMM_WORLD);
./deal.II/lac/petsc_matrix_free.h:     * MPI_COMM_WORLD</tt>.
./deal.II/lac/petsc_matrix_free.h:     * MPI_COMM_WORLD</tt>.
./deal.II/lac/petsc_matrix_free.h:     * MPI_COMM_WORLD</tt>.
./deal.II/lac/petsc_matrix_free.h:     * MPI_COMM_WORLD</tt>.
./deal.II/lac/trilinos_sparsity_pattern.h:                    const MPI_Comm &communicator      = MPI_COMM_WORLD,
./deal.II/lac/trilinos_sparsity_pattern.h:                    const MPI_Comm &communicator      = MPI_COMM_WORLD,
./deal.II/lac/trilinos_sparsity_pattern.h:                    const MPI_Comm &communicator      = MPI_COMM_WORLD,
./deal.II/lac/trilinos_sparsity_pattern.h:           const MPI_Comm &communicator      = MPI_COMM_WORLD,
./deal.II/lac/trilinos_sparsity_pattern.h:           const MPI_Comm &communicator      = MPI_COMM_WORLD,
./deal.II/lac/trilinos_sparsity_pattern.h:           const MPI_Comm &communicator      = MPI_COMM_WORLD,
./deal.II/lac/trilinos_sparsity_pattern.h:           const MPI_Comm &           communicator  = MPI_COMM_WORLD,
./deal.II/lac/trilinos_sparsity_pattern.h:           const MPI_Comm &           communicator  = MPI_COMM_WORLD,
./deal.II/lac/trilinos_vector.h:                      const MPI_Comm &communicator = MPI_COMM_WORLD);
./deal.II/lac/trilinos_vector.h:             const MPI_Comm &communicator = MPI_COMM_WORLD);
./deal.II/lac/trilinos_vector.h:             const MPI_Comm &communicator = MPI_COMM_WORLD);
./deal.II/lac/trilinos_vector.h:             const MPI_Comm &              communicator = MPI_COMM_WORLD);
./deal.II/lac/trilinos_vector.h:             const MPI_Comm &communicator         = MPI_COMM_WORLD,
./deal.II/lac/trilinos_vector.h:             const MPI_Comm &communicator    = MPI_COMM_WORLD,
./deal.II/lac/trilinos_sparse_matrix.h:                 const MPI_Comm &   communicator          = MPI_COMM_WORLD,
./deal.II/lac/trilinos_sparse_matrix.h:                 const MPI_Comm &communicator          = MPI_COMM_WORLD,
./deal.II/lac/trilinos_sparse_matrix.h:           const MPI_Comm &           communicator  = MPI_COMM_WORLD,
./deal.II/lac/trilinos_sparse_matrix.h:           const MPI_Comm &           communicator  = MPI_COMM_WORLD,
./deal.II/lac/trilinos_sparse_matrix.h:           const MPI_Comm &                      communicator = MPI_COMM_WORLD,
./deal.II/lac/trilinos_sparse_matrix.h:           const MPI_Comm &                      communicator = MPI_COMM_WORLD,
./deal.II/lac/trilinos_parallel_block_vector.h:                           const MPI_Comm &communicator = MPI_COMM_WORLD);
./deal.II/lac/trilinos_parallel_block_vector.h:             const MPI_Comm &             communicator         = MPI_COMM_WORLD,
./deal.II/lac/trilinos_parallel_block_vector.h:             const MPI_Comm &             communicator    = MPI_COMM_WORLD,
./deal.II/lac/trilinos_block_sparse_matrix.h:           const MPI_Comm &                communicator  = MPI_COMM_WORLD,
./deal.II/multigrid/mg_transfer.templates.h:  int ierr = MPI_Barrier(MPI_COMM_WORLD);
./deal.II/multigrid/mg_transfer.templates.h:      ierr = MPI_Barrier(MPI_COMM_WORLD);
./deal.II/multigrid/mg_transfer.templates.h:      ierr = MPI_Barrier(MPI_COMM_WORLD);
./deal.II/multigrid/mg_transfer.templates.h:      int ierr = MPI_Barrier(MPI_COMM_WORLD);
./deal.II/multigrid/mg_transfer.templates.h:      ierr = MPI_Barrier(MPI_COMM_WORLD);
./deal.II/multigrid/mg_transfer.templates.h:        ierr = MPI_Barrier(MPI_COMM_WORLD);
./deal.II/multigrid/mg_transfer.templates.h:  const int ierr = MPI_Barrier(MPI_COMM_WORLD);
./deal.II/sundials/arkode.h:           const MPI_Comm        mpi_comm = MPI_COMM_WORLD);
./deal.II/sundials/ida.h:        const MPI_Comm        mpi_comm = MPI_COMM_WORLD);
./deal.II/sundials/kinsol.h:           const MPI_Comm        mpi_comm = MPI_COMM_WORLD);
````

**Comment by tjhei** [comment]
> I'm in favor of this change. We shouldn't hard-code `MPI_COMM_WORLD`, and if possible shouldn't default to it either.

I agree that we should not do this. It is useful to be explicit about the communicator (and you don't gain much by hiding it).

**Comment by tjhei** [comment]
> > Are there other places where we use MPI_COMM_WORLD as a default?
> 
> Yes. But not a lot...

I would be tempted to remove these, but this is not backwards compatible. Still in favor of this PR...

**Comment by peterrum** [comment]
> Still in favor of this PR...

This function was introduced since the last release. So we do not have any issues on that side and should make the change before the next release.

**Comment by tjhei** [comment]
> This function was introduced since the last release. So we do not have any issues on that side and should make the change before the next release.

Yes, that is why I am in favor. :-)

**Comment by kronbichler** [comment]
It looks like we don't have tests for this function yet, so nothing to change there...

**Pull request merged**
