### PR TITLE
Avoid lambda function to compile with Intel 18/19.

### PR DESCRIPTION
**Pull request by marcfehling**
As reported in https://github.com/xsdk-project/xsdk-issues/issues/148#issuecomment-873256841 and https://github.com/xsdk-project/xsdk-issues/issues/148#issuecomment-873600281.

Intel compilers prior to version `19.1` bail out with an internal compiler error. Removing the (nested) lambda function altogether fixes the issue. Introduced in #12333.

Would have also been a good candidate for the point release #12494.

/rebuild

### CODE REVIEW

**Review by peterrum — APPROVED** [review]
Have you run the `remote_point_evaluation` test?

**Comment by marcfehling** [comment]
I just did. Most of the tests require `p4est` (one also needs `trilinos`) and I've added the corresponding flags in a separate commit.

The tests pass with `gnu`  and `OpenMPI`, but some fail for `Intel` and `Intel MPI` with more than 1 process:
```
	4703 - remote_point_evaluation/remote_point_evaluation_01.mpirun=4.debug (Failed)
	4705 - remote_point_evaluation/remote_point_evaluation_02.mpirun=5.debug (Failed)
```

All the `diff`s look like this:
```
4703: remote_point_evaluation/remote_point_evaluation_01.mpirun=4.debug: DIFF failed. ------ First 20 lines of numdiff output:
4703: ----------------
4703: ##3       #:4   <== 14454
4703: ##3       #:4   ==> 13186
```

Maybe the results depend on the `MPI` implementation? Should we merge anyways?

**Comment by marcfehling** [comment]
> Maybe the results depend on the `MPI` implementation?

No, I get the same errors with `Intel 19.1.1.217` and `OpenMPI 4.0.4`. Results are different with the `Intel` compiler. I will prepare alternative output for these tests.

**Comment by marcfehling** [comment]
> I will prepare alternative output for these tests.

Nevermind, these tests use the `zoltan` as a partitioner for `p::s::Triangulations`. Since the partitioner is not critical for this test, I will change them to use `zorder` which is available in any configuration.

**Review by bangerth — APPROVED** [review]
A triply nested lambda function :-)

**Pull request merged**
