### PR TITLE
Add more C++ resources to step-1.

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Review by marcfehling — APPROVED** [review]

**Comment by tjhei** [comment]
I always recommend https://www.amazon.com/Tour-2nd-Depth-Bjarne-Stroustrup/dp/0134997832 : a compact introduction to c++ assuming you know how to program.

**Comment by jpthiele** [comment]
We spent some time a few years ago for also searching for tutorial videos on C++.
What we found where a good ca. 2 hour long tutorial: https://www.youtube.com/watch?v=6y0bp-mnYU0 
and a playlist of shorter videos on specific topics https://www.youtube.com/playlist?list=PLlrATfBNZ98dudnM48yfGUldqGD0S4FFb

Maybe they could be useful too?

**Comment by tjhei** [comment]
Maybe we should link to a wiki page instead of adding anything to step-1?

**Comment by tamiko** [comment]
Let's keep the list of suggested resources short. We can add more stuff to the wiki/new webpage.

**Review by drwells — APPROVED** [review]

**Comment by drwells** [comment]
I opened an issue in the website repository to track future changes. This is a nice improvement so lets merge it as-is.

**Pull request merged**
