### PR TITLE
Propogate settings set in TrilinosWrappers::Solver<XYZ> to base class.

### LINKED ISSUE #4443: Parameters in TW::AdditionalData not propogated to TW::SolverBase
Refers to [this post](https://groups.google.com/forum/#!topic/dealii/kiLFKj94ubc) on the forum.

It looks like the parameters set in the TrilinosWrappers iterative solver AdditionalData structs are not passed to the SolverBase class. Thus the instance of its own AdditionalData only ever stores its default values, and these defaults are later referenced [here](https://github.com/dealii/dealii/blob/master/source/lac/trilinos_solver.cc#L452) and [here](https://github.com/dealii/dealii/blob/master/source/lac/trilinos_solver.cc#L468). 

Proposed patch: Remove all AdditionalData instances stored in the child iterative solver classes and change their constructors to
```c++
  SolverCG::SolverCG (SolverControl        &cn,
                      const AdditionalData &data)
    :
    SolverBase (cn, 
                SolverBase::AdditionalData(data.output_solver_details))
  {
    solver_name = cg;
  }
```
etc.

### PR DESCRIPTION
**Pull request by jppelteret**
Also allow direct setting of AdditionalData in TrilinosWrappers::SolverBase.

Fixes #4443. 
Supersedes #4512.

### CODE REVIEW

**Comment by jppelteret** [comment]
@juan42 Does the test output in this PR contain the sort of information you expect it to? This is a snippet of the full set of information that Trilinos dumps to std::cout :
```sh
*******************************************************
		***** Problem: Epetra::CrsMatrix
		***** Preconditioned CG solution
		***** ML (L=1, ~/Amesos_KLU_0, )
		***** No scaling
		*******************************************************

                iter:    0           residual = 2.923272e-02
                iter:    1           residual = 2.947044e-13


		Solution time: 0.000577 (sec.)
		total iterations: 1
```

**Comment by juan42** [comment]
That is the expected output, yes.

**Comment by jppelteret** [comment]
Great! One now gets this sort of output from both
```
TrilinosWrappers::SolverBase::AdditionalData solver_data(true);
TrilinosWrappers::SolverBase solver(TrilinosWrappers::SolverBase::cg, solver_control, solver_data);
solver.solve(...);
```
and
```
TrilinosWrappers::SolverCG::AdditionalData solver_data(true);
TrilinosWrappers::SolverCG solver(solver_control, solver_data);
solver.solve(...);
```
so I think that this fixes the issue that you highlighted.

**Comment by Rombur** [comment]
That's a funny bug. It shows that everything needs to be tested...

**Comment by bangerth** [comment]
Out of curiosity, what happens if we ever add more flags to the base class? Do we have to mirror them in all of the `AdditionalData` classes in derived solvers? Would it have been possible to just derive the `AdditionalData` classes in derived solvers from the `AdditionalData` of the base class?

**Comment by jppelteret** [comment]
@bangerth I don't think that this is a problem. Each of the `AdditionalData` in the derived classes currently acts as a filter to the flags set in the base class. As long as the constructor to `SolverBase::AdditionalData` doesn't change then any additions to it won't require changes to the derived class `AdditionalData`.

@juan42 and I first considered using the inheritance approach for the derived `AdditionalData`, but it ultimately didn't sit well with us. The main problem was that somewhere one would have the `gmres_restart_parameter` that you have to think about when creating `AdditionalData` for, e.g., `SolverCG`. With the original design (which we stuck with) this is not the case. Only if one uses `SolverBase` as a `SolverSelector` does one have to take this into consideration. As you indicated, the downside is that one has to mirror the flags that you wish to reference in `Derived::AdditionalData`.

**Comment by bangerth** [comment]
On 06/14/2017 10:57 PM, Jean-Paul Pelteret wrote:
> @bangerth <https://github.com/bangerth> I don't think that this is a 
> problem. Each of the |AdditionalData| in the derived classes currently 
> acts as a filter to the flags set in the base class. As long as the 
> constructor to |SolverBase::AdditionalData| doesn't change then any 
> additions to it won't require changes to the derived class |AdditionalData|.

Right, but that was my point. We can add flags to the 
|SolverBase::AdditionalData| class all day long, but this is only useful 
if we (i) then add the same flags to the (all!) derived classes, and 
(ii) adjust their constructors to pass these flags down to the base 
class. It would be easier if we used inheritance to simplify this 
process, rather than duplication. Of course, the base class would only 
contain the information that is common to *all* derived classes (i.e., 
not contain |gmres_restart_parameter|, for example).

**Comment by jppelteret** [comment]
@bangerth I'll put a PR together for your recommendation at the end of the week, and perhaps we can discuss it more then. Note though that the base class would have to hold the `gmres_restart_parameter` (its used [here](https://github.com/dealii/dealii/blob/master/source/lac/trilinos_solver.cc#L456)), but one can create sensible constructors in the derived classes that hide its initialisation from the user.

**Comment by bangerth** [comment]
Good plan!

**Pull request merged**
