### PR TITLE
instantiate p::d::GridRefinement and p::d::SolutionTransfer for dim==1

### PR DESCRIPTION
**Pull request by davydden**

### CODE REVIEW

**Comment by bangerth** [comment]
I don't actually think you need these asserts -- none of these functions actually make use of any specific functionality of dim>1.

In other words, remove the new asserts and just do the instantiations.

**Comment by davydden** [comment]
> remove the new asserts and just do the instantiations.

done.

**Comment by masterleinad** [comment]
I guess this is uncontroversial.

**Pull request merged**
