### PR TITLE
rephrase changelog entry

### PR DESCRIPTION
**Pull request by tamiko**
In reference to #4704 
In reference to #4752

### CODE REVIEW

**Comment by tamiko** [comment]
@kronbichler

**Comment by bangerth** [comment]
So if these functions were only recently added, after the last release, there isn't really much of a point in adding a changelog entry at all -- no user who jumps from one release to the next had an opportunity to experience this bug.

**Comment by kronbichler** [comment]
I guess I agree with @bangerth - let's remove this for now.

**Comment by tamiko** [comment]
No problem.

**Pull request closed without merging**
