### PR TITLE
improve MPI::Partitioner for the case of empty owned DoFs with with non-empty ghosts

### PR DESCRIPTION
**Pull request by davydden**
TODO:

- [x] currently there is a difference between `debug` and `release` in that ghosts are zeroed in `compress(insert)` for `debug` build and are left un-touched for release. I would expect them to be zeroed in release mode as well: https://github.com/dealii/dealii/blob/master/include/deal.II/base/partitioner.templates.h#L337 

EDIT: discrepancy in zeroing ghosts had to do with the
```
      if (compress_requests.size() == 0)
        return;
```
that I used to have between `import_from_ghosted_array_start` and `import_from_ghosted_array_finish`. In release mode there are no requests for `insert` and so the quoted in the above part of the code was not executed.

But then I guess `LA::parallel::Vector<Number>::compress_finish()` also has the same problem of not zeroing ghosts in release mode? @kronbichler

### CODE REVIEW

**Comment by kronbichler** [comment]
I've only limited time to look into this today, but

```
      if (compress_requests.size() == 0)
        return;
```

This case should only happen if a core neither has ghosts nor is involved in a send operations - thus, there should not be any indices to zero out. Or is it that we do not create the requests for a `insert` operations in `release` mode? In any case

**Comment by davydden** [comment]
@kronbichler 

> is it that we do not create the requests for a insert operations in release mode?

correct, that's the difference between `debug` and `release`, and therefore you don't get to `import_from_ghosted_array_finish` which zeroes ghosts.

> I will look more closely into this tomorrow.

thanks, note that the issue we discuss is somewhat parallel to this PR, namely this PR does not require any fixes on your side, it is ready as far as I am concerned.

**Comment by davydden** [comment]
@dealii/dealii can we have this merged?

**Comment by davydden** [comment]
thanks @kronbichler

**Pull request merged**
