### PR TITLE
MGTransferPrebuilt custom constraints test

### PR DESCRIPTION
**Pull request by tcclevenger**
Adds test for MGTransferPrebuilt with custom constraints to existing MGTransferMatrixFree test (discussed in https://github.com/dealii/dealii/pull/10348).

### CODE REVIEW

**Comment by tjhei** [comment]
great, can you rebase please?

**Comment by tjhei** [comment]
```
multigrid/transfer_07.debug: RUN failed. ------ Result: /home/dealii/build/tests/multigrid/transfer_07.debug/failing_output
multigrid/transfer_07.debug: RUN failed. ------ Partial output:
terminate called after throwing an instance of 'dealii::StandardExceptions::ExcInternalError'
  what():  
--------------------------------------------------------
An error occurred in line <517> of file </jenkins/workspace/dealii_PR-10481/tests/multigrid/../tests.h> in function
    void mpi_initlog(bool, std::ios_base::fmtflags)
The violated condition was: 
    false
```
I think this is a serial test, so you must not use ``mpi_initlog``

**Comment by masterleinad** [comment]
Did you delete `multigrid/transfer_matrix_free_13` on purpose?

**Comment by tjhei** [comment]
> Did you delete `multigrid/transfer_matrix_free_13` on purpose?

he renamed transfer_matrix_free_13.cc to transfer_07.cc

**Comment by masterleinad** [comment]
> he renamed transfer_matrix_free_13.cc to transfer_07.cc

Right, I wanted to ask if that was intentional or if that should have been a new test.

**Comment by tjhei** [comment]
> Right, I wanted to ask if that was intentional or if that should have been a new test.

It adds about 4 lines of real code to the test, so I am with him in not copying it and adding an extra test.

**Comment by tcclevenger** [comment]
@tjhei So, it seems that if I do not include the mpi initialization then the mpi build fails, but if I include it then the serial build fails. Not sure what is happening here..

**Comment by peterrum** [comment]
@tcclevenger Could you test locally which line is making problems. You are using `LA:p:V` in a serial application which looks a bit odd. Maybe during setting up  the `Partitioner` something is happening!?

**Comment by masterleinad** [comment]
```
    ERROR: MGTransferPrebuilt with LinearAlgebra::distributed::Vector currently needs deal.II to be configured with Trilinos.
```

**Comment by tcclevenger** [comment]
Ok, since this is a serial test, I can just use a `Vector<double>` for the prebuilt portion. The other option is having two separate tests. Which do you prefer?

**Comment by tjhei** [comment]
> Which do you prefer?

just make it two separate tests and require trilinos (and use mpiinit)

**Comment by tcclevenger** [comment]
> just make it two separate tests and require trilinos (and use mpiinit)

Instead, for the prebuilt test, I uses `dealii::Vector` which doesn't require Trilinos.

**Comment by tjhei** [comment]
anybody else have comments?

**Comment by masterleinad** [comment]
Would you squash the commits?

**Comment by tcclevenger** [comment]
Thanks everyone! Commits are squashed now.

**Pull request merged**
