### PR TITLE
Disable project_q_hierarchical_03

### PR DESCRIPTION
**Pull request by masterleinad**
Hanging node constraints for `FE_Q_Hierarchical` are just broken for nonstandard face orientations. This is also documented in `fe_q_hierarchical.cc`:
> //TODO: implement the adjust_quad_dof_index_for_face_orientation_table and
//adjust_line_dof_index_for_line_orientation_table fields, and write tests
//similar to bits/face_orientation_and_fe_q_*

### CODE REVIEW

**Comment by tjhei** [comment]
shouldn't you keep the .output file (or add an empty one)?

**Comment by tjhei** [comment]
Otherwise I agree with this change (I am investigating this bug at the moment)

**Comment by tamiko** [comment]
I think it is a good idea to keep the output file as well (to make it easier to resurrect the test at some point.) Did someone already open an issue for the underlying bug?

**Comment by tjhei** [comment]
#4767

**Pull request merged**
