### PR TITLE
Update step 33 (fix UpdateFlags)

### PR DESCRIPTION
**Pull request by mzaguilar8**
Chane update_q_points to update_quadrature_points.

### CODE REVIEW

**Comment by bangerth** [comment]
Ah, you triggered the line length check :-( Can you talk to one of us about running the indentation script?

**Comment by drwells** [comment]
Thanks a lot for the fix!

Could you add a changelog entry describing the fix so that we can add you to the list of deal.II authors? You should add a file in `doc/new/changes/minor/` describing this change: the easiest way to do this is to copy and paste one of the files in this directory, rename it with your name and date, and then change its text to describe this fix.

**Comment by drwells** [comment]
@mzaguilar8 Let us know if you need a hand in wrapping this up.

**Comment by drwells** [comment]
Since all we needed to do was run `make indent` and fix authorship information I went ahead and did it. Closed in favor of #8642.

**Pull request closed without merging**
