### PR TITLE
modified filtered_matrix tests to work with square matrices only

### PR DESCRIPTION
**Pull request by dakshinai**
modified filtered_matrix tests to work with square matrices only

### CODE REVIEW

**Comment by dakshinai** [comment]
Sorry for the multiple requests. Please consider this as final. git pull was adding pending server commits to my local commit. I shall look into it.

**Comment by Rombur** [comment]
Why do you want to force the filtered_matrix to be square? The tests are passing right now.

**Comment by dakshinai** [comment]
Hello Rombur, 

As per my understanding, Filtered matrices are used to solve a system of linear equations that can be represented with square matrices. Also, the apply_constraint test case fails with non-square matrices. Hence the changes were incorporated.

As a next step, Filtered_matrix methods should be modified to raise an exception if non-square matrices are supplied.

Prof. Bangerth could you explain further?

**Comment by bangerth** [comment]
I think `FilteredMatrix` previously accepted non-square matrices in error. The class is clearly intended only for square systems (or so I always thought).

@dakshinai is my employee, so I have a conflict of interest -- I would appreciate someone else reviewing the patch.

**Pull request merged**
