### PR TITLE
Fix test matrix_free/categorize_by_boundary_ids_01

### PR DESCRIPTION
**Pull request by peterrum**
see https://cdash.43-1.org/test/297464

### CODE REVIEW

**Comment by Rombur** [comment]
Why is the assert not passing anymore?

**Comment by peterrum** [comment]
> Why is the assert not passing anymore?

If vectorization is disabled, all cells in the macro cell (1 cell) are categorized correctly by definition.

**Review by drwells — APPROVED** [review]

**Comment by drwells** [comment]
Would it be better to only add that assertion if the vector width is greater than 1?

**Comment by peterrum** [comment]
> Would it be better to only add that assertion if the vector width is greater than 1?

I must admit it is not really relevant if it was sorted or not before. The requirement is that it is sorted after the function call.

**Pull request merged**
