### PR TITLE
CMake: force a single configuration in "multiple generator" mode

### PR DESCRIPTION
**Pull request by tamiko**
In reference to #17766

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

**Review by tjhei — APPROVED** [review]

**Comment by bangerth** [comment]
How will this affect the VS folks?

Following https://github.com/dealii/dealii/issues/17766#issuecomment-2407543375, you say that they use multiple generators, which I assume is the VS project file and a `Makefile` or some such. After your patch, what is it that will be generated?

@kcris FYI

**Comment by tamiko** [comment]
@bangerth 

I was in a hurry and forgot to write out a 


> How will this affect the VS folks?

Hopefully in a positive way.


> you say that they use multiple generators, which I assume is the VS project file and a Makefile or some such. After your patch, what is it that will be generated?

The idea behind the "multiple generator" mode in CMake is to do one confiiguration run that configures the project and then have multiple "build flavors" (debug, release, release with debug info, minimal size) essentially controlled by compiler flags.

We fundamentally do not support this type of setup because we copied the old autotools variant in which we configure two flavors of the library and compile them at the same time. Note that our "debug" and "release" variant do significantly more than just to change compiler flags.

Currently, CMake in multiple generator mode will set up four configurations: "Debug" "Release", "MinSizeRel", and "RelWithDebInfo" and every single one will build the `dealii::dealii_debug` target and the `dealii::dealii_release` target in exactly the same way. With this patch there will only be one configuration matching the chosen `CMAKE_BUILD_TYPE` and everything will only be compiled once and for one configuration alone.

We could in principle support this multiple generator setup but it would amount to rewriting and reorganizing major parts of the configuration process we have right now - for hardly any benefit.


I plan to support the multiple generator mode in downstream projects though - this should only require checking that the `dealii::dealii` target does the right thing and some minor changes to our `deal_ii_setup_target` and `deal_ii_invoke_autopilot` macros. (Famous last words...)

**Comment by bangerth** [comment]
I see -- thank you for the explanation! This also explains why the OP had the `Debug` string in all builds, even the release library: That's simply the generator used, if I understand correctly.

**Pull request merged**
