### PR TITLE
Let petsc_complex/solver_real_[01|02] fail in the same way petsc/solver_[01|02] do

### PR DESCRIPTION
**Pull request by davydden**
… whitespaces

### CODE REVIEW

**Comment by davydden** [comment]
there are also two of those for `petsc/solver_real_[01|02]`.

**Comment by davydden** [comment]
in reference to https://github.com/dealii/dealii/issues/2033

**Comment by davydden** [comment]
@tamiko example the same as in `petsc/solver_real`. It was copied from there and for complex-valued algebra is just a confirmation that it works exactly the same in real plane.

**Comment by tamiko** [comment]
@oneliefleft *ping*

**Comment by davydden** [comment]
@tamiko yes, they do, just differently
```
DEAL::Size 32 Unknowns 961
DEAL::Solver type: N6dealii13PETScWrappers16SolverRichardsonE
DEAL::Starting value 7.750
DEAL::Failure step 100 value 4.004
DEAL::Exception: SolverControl::NoConvergence (solver_control.last_step(), solver_control.last_value())
DEAL::Solver stopped after 100 iterations
```

**Comment by davydden** [comment]
(from solver_01.output)

**Comment by tamiko** [comment]
*wow* This doesn't make any sense. Why do we do that?

**Comment by davydden** [comment]
p.s. i see why the output is different, will fix it to be the same as real-valued...

**Comment by tamiko** [comment]
@davydden What do you mean? All 4 variants should not throw an exception. This one line of output was introduced by me in 2013 - by mistake.

**Comment by davydden** [comment]
@tamiko catch is wrong in complex tests, should be
```
catch (dealii::SolverControl::NoConvergence &e)
    {
      deallog << "Exception: " << e.get_exc_name() << std::endl;
    }
```

**Comment by tamiko** [comment]
@davydden Yes. This doesn't change the fact that the tests are broken.

**Comment by davydden** [comment]
@tamiko  it does not but this is **a different issue**. Here i just want have consistent output.

**Comment by tamiko** [comment]
@davydden Well, now let's fix them.

**Pull request merged**
