### PR TITLE
Remove unnecessary assignment

### PR DESCRIPTION
**Pull request by peterrum**
ping @tjhei

### CODE REVIEW

**Comment by drwells** [comment]
Its possible that we meant to use that and didn't. Lets not merge until an expert chimes in.

/rebuild

**Comment by peterrum** [comment]
@drwells When looking back in history, I see it used to be used; but not any more, since code was strongly rewritten.

**Comment by tjhei** [comment]
Yeah, this can be removed I would think.

**Comment by bangerth** [comment]
4 approvals for a triviality :-)

**Pull request merged**
