### PR TITLE
Fix flags for Trilinos+Kokkos

### PR DESCRIPTION
**Pull request by masterleinad**
Without this pull request, we would not use `Trilinos`' flags that (among others) include flags for `Kokkos` backends such as `OpenMP` or `CUDA`.

### CODE REVIEW

**Review by Rombur — APPROVED** [review]
Thanks with this PR I can use Trilinos. We do get a bunch of warning because by default, Kokkos and deal.II use different `O` optimization flags but we can fix this later.

**Comment by masterleinad** [comment]
> Thanks with this PR I can use Trilinos. We do get a bunch of warning because by default, Kokkos and deal.II use different `O` optimization flags but we can fix this later.

I pushed another commit that should strip the optimization flags.

**Review by tjhei — APPROVED** [review]

**Comment by masterleinad** [comment]
It turns out that `Trilinos` passes all kind of stuff in their exported flags, at least for older versions, in the CI we get, e.g,
```
-g  -fdebug-prefix-map=/build/trilinos-GM3Kol/trilinos-12.14.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++11
```
on top optimization flags. Hence, the last commit just takes the `Kokkos` flags.

**Comment by masterleinad** [comment]
Only the CUDA CI is failing and that should not be affected by the changes here (but rather addressed/worked around in #14436.

**Pull request merged**
