### PR TITLE
Added a subsection about mapping higher-order derivatives in Mapping …

### PR DESCRIPTION
**Pull request by maieneuro**
…documentation

(also added entry to doc/news/changes.h that I forgot to include in previous PR)

### CODE REVIEW

**Comment by bangerth** [comment]
Nice, thanks!

There's a merge conflict right now -- can you please rebase so I can merge? While you're there, would you mind un-abbreviating "w.r.t." in the text to "with regard to"? The consumers of our documentation are by and large not native speakers and may have trouble with abbreviations.

**Comment by bangerth** [comment]
I also wanted to say thanks for finally explaining to me what the "Jacobian push-forward something" is :-)

**Comment by maieneuro** [comment]
Done, done, and it's a pleasure :-). Also added missing markup to a comment in FE_Poly.

**Comment by bangerth** [comment]
By the way, there's a mistake in the last part of the last formula you added:
  http://dealii.org/developer/doxygen/deal.II/classMapping.html
One of the occurrences of the index 'k' in H_mkl H_imk must be a 'j' instead, but I don't know which.

Earlier on, there is a sentence "...real cell coordinates. for instance, the..." where the "for" could use to be capitalized.

No big issues either way, but if you had a minute the small change would be appreciated!

**Pull request merged**
