### PR TITLE
MappingDataOnTheFly: make FE_Nothing unique_ptr

### PR DESCRIPTION
**Pull request by peterrum**
references https://github.com/dealii/dealii/issues/16044

### CODE REVIEW

**Comment by peterrum** [comment]
@bergbauer Could you try out if this helps for you?

**Comment by bergbauer** [comment]
Yes, this helps! Thanks!

**Review by kronbichler — APPROVED** [review]

**Comment by kronbichler** [comment]
We have a failing Cuda CI tester, where I can't see the error due to many warnings. Could you please rebase to master (where the warnings were fixed) so we can see if the error is of concern?

**Comment by masterleinad** [comment]
> We have a failing Cuda CI tester, where I can't see the error due to many warnings. Could you please rebase to master (where the warnings were fixed) so we can see if the error is of concern?

The logs show
```
2023-09-27T11:51:36.4384919Z /tmp/ccUEUs88.s: Fatal error: can't close CMakeFiles/example_step_66_debug.dir/step-66/step-66.cc.o: No space left on device
```

**Pull request merged**
