### PR TITLE
Remove unused "using namespace" directives in the tutorials.

### PR DESCRIPTION
**Pull request by rezarastak**

### CODE REVIEW

**Comment by rezarastak** [comment]
It some tutorials we have it and it is needed. In some tutorials we don't have it at all. I removed the `using namespace dealii` statements that we have but we don't need.

**Comment by rezarastak** [comment]
I am not sure why the appveyor build has failed. I think it was a connection issue unrelated to the changes in this PR.

**Comment by masterleinad** [comment]
Can you just rebase?

**Comment by rezarastak** [comment]
sure!

**Pull request merged**
