### PR TITLE
Get rid of the PolynomialType template argument of FE_Q_Base.

### PR DESCRIPTION
**Pull request by bangerth**
This is similar to what @GrahamBenHarper did in #8597 and #8711. In short, there is no good reason why the `FE_Q_Base` class should have the polynomial space description as a *template argument*, as opposed to just taking an object as a regular argument in the constructor. Indeed, removing this template argument is not overly complicated, and probably also saves us some compile time and disk space.

Related to #1973.

@marcfehling -- FYI, as discussed earlier.

/rebuild

### CODE REVIEW

**Review by marcfehling — APPROVED** [review]
This will make dynamic_casting between different FiniteElement classes a lot easier in the hp-context.

**Comment by bangerth** [comment]
There is a single failure:
```
	4203 - multigrid/transfer_matrix_free_06.mpirun=15.debug (Timeout)
```
I think that that is unrelated.

**Review by masterleinad — APPROVED** [review]

**Comment by bangerth** [comment]
Ping? @marcfehling is waiting on this being merged...

**Comment by masterleinad** [comment]
> Ping? @marcfehling is waiting on this being merged...

I think it's OK to merge your own pull request if it has the `Reviewed and ready to merge label` and all tests passed.

**Comment by bangerth** [comment]
I just don't like doing that. I think we live by peer review, and I'd like others to make that decision to actually pull the trigger.

Thanks, though, for doing it! :-)

**Pull request merged**
