### PR TITLE
Add accessor functions for essential geometric properties of the Manifold classes.

### PR DESCRIPTION
**Pull request by drwells**
Unlike PolarManifold, CylindricalManifold does not make its center accessible. This makes it difficult to, e.g., apply a transformation to a mesh which uses a CylindricalManifold and then update the CylindricalManifold accordingly.

`direction`, `point_on_axis`, and `tolerance` are three constructor arguments so making those public is enough to make it possible to re-create these objects.

*update* I applied the same transformation to the other Manifold classes.

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]
I agree with this change, since we do the same for `SphericalManifold` and `PolarManifold`, however, we do not do it for the other cases here. I think this calls for an additional opinion before merging.

**Review by bangerth — COMMENTED** [review]
Why not provide accessor functions instead? I find exposing internal variables eternally troublesome. You basically tie your hands for implementing things differently in the future.

**Comment by drwells** [comment]
I don't have strong feelings about what interface we use; I did it this way since the other classes have public const members. How about we convert all of them to accessors and early-deprecate the members?

**Comment by bangerth** [comment]
Yes, I'm definitely in favor of this approach!

**Comment by drwells** [comment]
Making everything consistent required a few extra small changes:
1. I gave `TorusManifold`'s variables better names
2. I deprecated `public const Point<spacedim> center;`
3. I added accessors for all other relevant geometric quantities - in each case I only added enough accessors for someone to run the constructor again.

**Review by kronbichler — APPROVED** [review]

**Pull request merged**
