### PR TITLE
VectorTools::compute_no_normal_flux_constraints: use mapping in the case of linear manifold

### PR DESCRIPTION
**Pull request by peterrum**
We are using `MappingQCache` to decouple a linear mesh (with `FlatManifold`) from a high-order description of the computational domain. In this case, it does not make sense to ask the `Manifold` to return the normal vector but one needs to ask the `Mapping`.

FYI @tamiko

### CODE REVIEW

**Comment by kronbichler** [comment]
I think this is a very reasonable option given the interaction of manifolds and mappings. I'm wondering if the distinction via `FlatManifold` could be surprising when thinking some more about it. For example, I'm thinking of the case where we start with something that is not a `FlatManifold`, but still gets deformed via the mapping. Say the elastic deformation of body when posed in spatial coordinates, that starts from a curved manifold in the beginning, but later gets its vertices from the mapping (`MappingQEulerian`, `MappingFEField` etc). Note that one could argue to use the material configuration instead and manually compose with the structural deformation from a mathematical model point of view. That said, I wonder if we should make this explicit in the sense that we say that we want the normal computed by `FEFaceValues` (i.e., the mapping) rather than the normal computed from the manifold.

In any case, we will need to adjust the documentation about what normal is chosen. I looked a bit at the documentation and found https://github.com/dealii/dealii/blob/add8e16ae6718e1e0521653ec1f5c1e48db5ee57/include/deal.II/numerics/vector_tools_constraints.h#L114-L116 but there might be other/more places that also need to be adjusted.

**Comment by peterrum** [comment]
> That said, I wonder if we should make this explicit in the sense that we say that we want the normal computed by FEFaceValues (i.e., the mapping) rather than the normal computed from the manifold.

I like the suggestion. What do you think about the second commit?

**Review by kronbichler — APPROVED** [review]
Nice, I like this.

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
Want to add a changelog entry?

**Comment by peterrum** [comment]
> Want to add a changelog entry?

Done!

**Pull request merged**
