### PR TITLE
Return the box of support points instead of only the vertices.

### PR DESCRIPTION
**Pull request by luca-heltai**

### CODE REVIEW

**Comment by luca-heltai** [comment]
Without this patch, the bounding boxes for our beloved hypersphere look like:

Screenshot 2021-01-16 at 18 11 28

With this patch we get for quadratic:

Screenshot 2021-01-16 at 18 52 46

of course, if we use cubic the situation is worse, since the mid point is not a support point:

Screenshot 2021-01-16 at 18 58 19

**Comment by luca-heltai** [comment]
@blaisb , out of curiousity, how did you get the nice pictures of the bounding boxes with paraview? I don't seem to be able to plot them with lines if I make them transparent, and the ones in the background never show up with their boundaries...

**Review by peterrum — APPROVED** [review]

**Review by drwells — APPROVED** [review]

**Comment by blaisb** [comment]
> @blaisb , out of curiousity, how did you get the nice pictures of the bounding boxes with paraview? I don't seem to be able to plot them with lines if I make them transparent, and the ones in the background never show up with their boundaries...

I realized I missed this question. Sorry Luca. Never made pictures of the bounding box with paraview, I just outputed the simulation subdomain.

**Pull request merged**
