### PR TITLE
Fix FEDomination in FEInterfaceValues and ScratchData.

### PR DESCRIPTION
**Pull request by marcfehling**
In `FEInterfaceValues`, as well as `ScratchData::reinit` that uses `hp::FEFaceValues`, we use the finite element domination logic to find matching quadrature rules and mappings.

Right now, we do this on the cell level (codim = 0), but we should rather do it on a face level (codim = 1) in these two cases.

### CODE REVIEW

**Review by bangerth — APPROVED** [review]
Ah yes, good catch!

**Comment by marcfehling** [comment]
This actually causes a test to fail. For the reason we discussed last time, @bangerth:

After #14225, the return values of `find_dominating_fe` etc changed from `invalid_unsigned_int` to `invalid_fe_index`.

Since #13181 in ScratchData, we reuse the `invalid_unsigned_int` return value to tell `hp::FEValues` to use the local active fe index. This no longer works with the `invalid_fe_index` value, and we get an error like
```
7533: --------------------------------------------------------
7533: An error occurred in line <456> of file <dealii/source/hp/fe_values.cc> in function
7533:     void dealii::hp::FEFaceValues<dim, spacedim>::reinit(const dealii::TriaIterator<dealii::DoFCellAccessor<dim, spacedim, lda> >&, unsigned int, unsigned int, unsigned int, unsigned int) [with bool lda = false; int dim = 2; int spacedim = 2]
7533: The violated condition was: 
7533:     ::dealii::deal_II_exceptions::internals::compare_less_than(real_q_index, this->q_collections.size())
7533: Additional information: 
7533:     Index 65535 is not in the half-open range [0,2).
7533: --------------------------------------------------------
```

`DGQ` elements only dominate each other over cells, but not over faces, which is why the error now shows up. That's why for example `meshworker/scratch_data_03_hp` fails now.

We need to think of adjusting the interfaces fo the `find_dominated_fe` functinos as part of #13595. But for now, let's fix this issue! I will add another commit to this PR.

**Comment by marcfehling** [comment]
With the new commit, this needs another review.

**Review by bangerth — APPROVED** [review]

**Comment by marcfehling** [comment]
The L-infty norm of the solution in the affected test changed. Did we do the right thing with this patch?

**Comment by bangerth** [comment]
I'm afraid this can't be right... But I'll look tomorrow.

**Comment by bangerth** [comment]
There are three logically separate changes in this patch: The codim=1 case in `FEInterfaceValues`, the corresponding change in `ScratchData`, and the translation of indices. Which of these three causes the failing test?

**Pull request closed without merging**
