### PR TITLE
AD Helpers: Add tests

### PR DESCRIPTION
**Pull request by jppelteret**
~~Blocked by #6975, #6976, #6977, #6978, #6979, #6980, #6981~~
~~Blocked by  #7854~~

### CODE REVIEW

**Comment by jppelteret** [comment]
So, locally all of the tests that I *expect* to pass do pass:
```
$ ctest -R "adolc|sacado"
...
99% tests passed, 3 tests failed out of 456

Total Test time (real) = 1091.35 sec

The following tests FAILED:
	 74 - adolc/helper_scalar_failure_04.release (Failed)
	 93 - adolc/helper_tape_index_01.debug (Failed)
	 94 - adolc/helper_tape_index_01.release (Failed)
Errors while running CTest

```
I need to think at some point about these failing tests (i.e. do they actually make sense), but I'd prefer not to do so at this point in time.

**Comment by jppelteret** [comment]
@tamiko Would you mind please setting bob to test this branch, specifically the ADOL-C and Sacado tests?

**Comment by jppelteret** [comment]
@dealii/dealii ping

**Comment by bangerth** [comment]
This just affects tests, right? I was about to just merge in that case, but there is one test that fails:
```
Test adolc/helper_tape_index_01.debug: RUN
===============================   OUTPUT BEGIN  ===============================
[  0%] Generating helper_tape_index_01.debug/interrupt_guard.cc
Scanning dependencies of target helper_tape_index_01.debug
[  0%] Building CXX object CMakeFiles/helper_tape_index_01.debug.dir/helper_tape_index_01.cc.o
[250%] Building CXX object CMakeFiles/helper_tape_index_01.debug.dir/helper_tape_index_01.debug/interrupt_guard.cc.o
Linking CXX executable helper_tape_index_01.debug/helper_tape_index_01.debug
[ 50%] Built target helper_tape_index_01.debug
Scanning dependencies of target helper_tape_index_01.debug.diff
[100%] Generating helper_tape_index_01.debug/output
adolc/helper_tape_index_01.debug: BUILD successful.
adolc/helper_tape_index_01.debug: RUN failed. ------ Return code 134
adolc/helper_tape_index_01.debug: RUN failed. ------ Result: /home/dealii/build/tests/adolc/helper_tape_index_01.debug/failing_output
adolc/helper_tape_index_01.debug: RUN failed. ------ Partial output:

adolc/helper_tape_index_01.debug: RUN failed. ------ Additional output on stdout/stderr:

Tape number: 1
Tape number: 2
Tape number: 3
Tape number: 4
Tape number: 5
Tape number: 6
Tape number: 7
Tape number: 8
Tape number: 9
Tape number: 10
Tape number: 11
Tape number: 12
Tape number: 13
Tape number: 14
Tape number: 15
Tape number: 16
Tape number: 17
Tape number: 18
Tape number: 19
Tape number: 20
Tape number: 21
Tape number: 22
Tape number: 23
Tape number: 24
Tape number: 25
Tape number: 26
Tape number: 27
Tape number: 28
Tape number: 29
Tape number: 30

--------------------------------------------------------
An error occurred in line <206> of file </jenkins/workspace/dealii_PR-6982/tests/adolc/helper_tape_index_01.cc> in function
    void test_scalar_scalar_coupled_one_run(number_t, number_t, tape_index_t) [with int dim = 3; number_t = double; dealii::Differentiation::AD::NumberTypes ad_type_code = (dealii::Differentiation::AD::NumberTypes)0; tape_index_t = short unsigned int]
The violated condition was: 
    std::abs(dpsi_ds1 - func::dpsi_ds1(s1, s2)) < tol
Additional information: 
    No match for first derivative.
--------------------------------------------------------
```

**Comment by bangerth** [comment]
The patch affects 340 files, but that's too much for github to show me. Did you really generate this many distinct tests? (170 tests + 170 output files?)

**Comment by jppelteret** [comment]
> This just affects tests, right? I was about to just merge in that case, but there is one test that fails:

Yes, this PR only consists of tests. 

> The patch affects 340 files, but that's too much for github to show me. Did you really generate this many distinct tests? (170 tests + 170 output files?)

Sounds about right... Actually, in many cases there's a header file that governs a test, then individual `cc` and `output` files for the 2 `ADOL-C` and 4 `Sacado` number types (`AD_type_code` ftw!). You might be asking "jeez, isn't that a bit excessive?". I'd reply "do you have any idea as to how diabolical this whole exercise has been?". Employing the deal.II best programming practices (TM) I've used many of these tests to construct the implementation, not the other way around.

As for the test that is failing:
- I do see the same error on my Linux box with GCC, and
- it is annoying :-/

It suggests that we're trying to perform computations on a tape that ADOL-C doesn't support. But we already ask ADOL-C for the maximum number of tapes allowed (32, by default) and we don't exceed it. This problem does not arise when using Clang as a compiler. I eventually ran out of patience trying to think of a reasonable solution to this. 

Do you think that we need to run this test during the CMake configuration phase, and determine the max number of supported tapes ourselves? That seems like a pain to me. Any suggestions?

**Comment by jppelteret** [comment]
(sorry for the very delayed reply, BTW.)

**Comment by bangerth** [comment]
On 4/26/19 12:41 PM, Jean-Paul Pelteret wrote:
>     The patch affects 340 files, but that's too much for github to show
>     me. Did you really generate this many distinct tests? (170 tests +
>     170 output files?)
> 
> Sounds about right... Actually, in many cases there's a header file that 
> governs a test, then individual |cc| and |output| files for the 2 
> |ADOL-C| and 4 |Sacado| number types (|AD_type_code| ftw!). You might be 
> asking "jeez, isn't that a bit excessive?".

No, absolutely not! You know that I think that more tests is more 
better! I applaud you for comprehensive testing!

**Comment by bangerth** [comment]
About the test: Do I see this right that ADOL-C documents that we can use 32 tapes, but in reality we already get an error at 30? Then why not internally set the maximum number of tapes to 29?

**Comment by jppelteret** [comment]
> Do I see this right that ADOL-C documents that we can use 32 tapes, but in reality we already get an error at 30? 

Yes, that's how I interpret things.

> Then why not internally set the maximum number of tapes to 29?

Because 31 work with clang, but only 29 with GCC. Also, one can actually recompile ADOL-C with another number of maximum tapes (this is a macro setting), so this number is actually not safe to pick ad-hoc. But I'm a bit fed up trying to accommodate all of the strange things that these libraries have thrown at us, so I think that setting the maximum number of tapes to `N_MAX-2` when using GCC might be the best solution for now. I'd document the decision appropriately.

**Comment by bangerth** [comment]
On 5/1/19 10:07 AM, Jean-Paul Pelteret wrote:
> Because 31 work with clang, but only 29 with GCC. Also, one can actually 
> recompile ADOL-C with another number of maximum tapes (this is a macro 
> setting), so this number is actually not safe to pick ad-hoc. But I'm a 
> bit fed up trying to accommodate all of the strange things that these 
> libraries have thrown at us, so I think that setting the maximum number 
> of tapes to |N_MAX-2| when using GCC might be the best solution for now. 
> I'd document the decision appropriately.

That sounds like a good plan. Should we merge this as is, or do you want 
to address this before we merge?

**Comment by jppelteret** [comment]
> Should we merge this as is, or do you want to address this before we merge?

I anticipate going into the office in the next couple of days, so I'll try to put a quick patch together before we merge. Thanks for asking!

**Comment by jppelteret** [comment]
@bangerth I made the fix that we'd discussed. This made the offending test pass on my machine.

**Pull request merged**
