### PR TITLE
Fixed an issue reported by @gassmoeller.

### PR DESCRIPTION
**Pull request by drwells**
I was not able to reproduce #1652 but I believe this should fix it. @gassmoeller would you be willing to help me by trying out these changes and seeing if this fixes things?

@bangerth I am not sure which copy of the exact transformations the library actually calls. Which of these, if either, do you plan on removing?

### CODE REVIEW

**Comment by bangerth** [comment]
I'm still moving around functions but hope to be done with it next week. Could we hold off merging until after I'm done given that I have moved many hundreds of lines in my current tree? I'll respin this patch once I'm done merging, it should be easy to add this one once I'm done.

@gassmoeller: Can you try whether this patch fixes your problem?

**Comment by gassmoeller** [comment]
I can confirm that this fixes #1652 for me. Waiting with the merge is also ok, for now I simply switch off floating point exceptions and ensure that my code interprets the weird unit cell coordinates in the right way ... seems to work for now.
Thanks @drwells for the fast fix :+1:

**Comment by drwells** [comment]
Not a problem (this was quick compared to the amount of time I originally spent writing that function).

**Comment by tjhei** [comment]
I am suspicious when I see floating point comparisons with |==|. Even if you need this only for the case that |b| is zero, an epsilon based comparison might be better instead. Thoughts?

**Comment by drwells** [comment]
I checked strict equality so that the next case would not result in division by zero (and therefore getting `+Inf`, `-Inf`, or `NaN`).

I think the tolerance is a better idea because then if the difference is nearly zero, I end up with a tentative value for `eta` which is nearly zero (which is more valuable than the massive value I would get from `2*c / -b + std::sqrt(discriminant)`. The quadratic formula involves a lot of torturous cases for double precision arithmetic and I am not sure how to do this optimally.

**Comment by tjhei** [comment]
Floating point math is tricky and I am not an expert, just very skeptical :-).

I am not even sure if
```
  if (a == 0.0 && b != 0.0) eta1 = -c/b;
```
is robust. I assume it can still overflow...

**Comment by tjhei** [comment]
I don't really have a good idea how to make this whole code work...

**Comment by drwells** [comment]
@tjhei as far as that line goes, if the linear interpolation formula fails for the given point and cell, then I see no shame in throwing my hands up and letting overflow happen.

I spent a lot of time getting rid of round off errors in this function ( I think I was more successful at this in the `xi` calculation below). I do not know how close we are to a stable quadratic formula (at this point we have more checks than the GSL routine). Does anyone know of sources with better implementations?

**Comment by bangerth** [comment]
This patch conflicts with what was just merged as part of #1703. I'll respin this patch on top of current master next week (I'm traveling till Monday) unless someone beats me to it.

**Comment by drwells** [comment]
This is easy enough to fix; I updated the PR.

**Pull request merged**
