### PR TITLE
GridOut fixes

### LINKED ISSUE #814: Wrong code in GridOut
#804 caught @tjhei 's eye with this piece of code at the end of `GridOut::write_msh`:
```
  if (msh_flags.write_faces)
    write_msh_faces (tria, cell_index, out);
  if (msh_flags.write_lines)
    write_msh_lines (tria, cell_index, out);
```
This is fishy because `cell_index` is passed by value, not by reference. So, if faces and lines are both output, they will get the same object ids. This seems wrong.

There is a similar place in `GridOut::write_ucd` below.

### PR DESCRIPTION
**Pull request by drwells**
This should close #814.

I do not have access to any software that can read UCD files, but I confirmed that for MSH files:
1. The output did have repeated geometric element numbers.
2. GMSH did not like that and deleted information with repeated numbers.

I used the same fix for both `ucd` and `msh` output formats.

While I was there I also made some improvements to these functions (and the documentation) that is unrelated to #814. I can move it to another PR if anyone would prefer that. In particular, I got rid of a few `const_cast`s by making `GridOut` a friend of `Triangulation` so that it can use `active_line_iterator`. An alternative would be to make `begin_active_line()` public.

### CODE REVIEW

**Comment by bangerth** [comment]
The first five of these patches all look good. I'm not excited about the last one:
* Functions such as `begin_active_line` used to be public, but we've moved away from that because (i) the public interface of `Triangulation` was just too big, and (ii) because it turns out that in most circumstances just knowing a face or line iterator without the adjacent cell was just too limiting; this frequently led to inefficient or poorly designed algorithms when one could do better by looping over all cells and the over the faces/lines of these cells.
* Making additional classes `friends` also doesn't seem like a long-term strategy.
* Is it correct that the last patch only changes the output because it traverses lines in a different order than before?

I agree in principle that the `const_cast` is not pretty. At the same time, the "semantics" of passing the triangulation as a `const` object are preserved by the function.


Independent of that point, but more as a general remark, I'm not overly fond of functions that take scalars by reference. The intent of these argument is often hard to discern at call sites when reading through code. Instead, in other places of the library, we've moved to a system where the function takes the initial index as an argument and returns the next free index by value. This leads to code that looks like this:
```
  next_free_index = write_faces (..., next_free_index, ...);
```
This makes it clear to the reader that `next_free_index` really changes as part of this line.

I'm not going to make you change the code in this direction, but just wanted to put this here as a public education announcement ;-)

**Comment by drwells** [comment]
I figured the `const_cast` patch might not be a good idea. I dropped that commit. I might come back to it later (I think I know of another way around the problem).

> Is it correct that the last patch only changes the output because it traverses lines in a different order than before?

Yes. I sorted the line parts of the output before and after this test (after deleting geometry numbers) and got identical results.

> Independent of that point, but more as a general remark, I'm not overly fond of functions that take scalars by reference. The intent of these argument is often hard to discern at call sites when reading through code. Instead, in other places of the library, we've moved to a system where the function takes the initial index as an argument and returns the next free index by value.

This is so much better than what I wrote that I felt compelled to fix it.

**Comment by drwells** [comment]
Hold on a second, something got messed up in a rebase.

**Comment by bangerth** [comment]
For the second time today I forgot to look for an entry in changes.h. Would you mind adding one?

**Comment by drwells** [comment]
Sure

**Pull request merged**
