### PR TITLE
Remove some pthread vestiges that were deprecated a while ago already

### PR DESCRIPTION
**Pull request by bangerth**
/rebuild

### CODE REVIEW

**Comment by masterleinad** [comment]
Didn't we just deprecate that class for `9.1.0`? Is it too early to remove it before the next release? So far, I only removed stuff from `9.0`.

**Comment by bangerth** [comment]
Oh, I didn't pay attention to be honest. I was in that file anyway and fixing stuff so I thought I'd remove it. You're right that this was deprecated in #7244, 19 months ago. Let's postpone till post 9.2 then.

**Comment by masterleinad** [comment]
```
/home/runner/work/dealii/dealii/source/base/thread_management.cc:155:3: error: ‘PosixThreadBarrier’ does not name a type
```

**Comment by masterleinad** [comment]
Can you please rebase?

**Comment by bangerth** [comment]
Rebased.

**Pull request merged**
