### PR TITLE
Clean up some DoFHandler things.

### PR DESCRIPTION
**Pull request by bangerth**
This is a rather large patch, and I apologize in advance to whomever is going to review it :-)
I've broken it up into several independent patches that are all more or less atomic and
achieve a single goal. It is probably easiest to look through everything one commit
at a time.

None of these commits change functionality. Most really just clean things up, and the
only non-trivial change is the one from raw pointers in DoFhandler to std::unique_ptr.

I've run a fair part of the testsuite, with no failures other than the (expected)
changes to serialization due to using std::unique_ptr.

In preparation for eventually doing #3511.

### CODE REVIEW

**Comment by drwells** [comment]
This looks good. Thank you for breaking up the changes atomically; it makes this patch very easy to read.

I have two comments so far:

1. I don't see why we need to use pointers at all in e73b3f7955e4e10ee907fbac76ab7eceefbf1f89 as long as it is possible to efficiently move `DoFLevel`s and `DoFFaces`: since these just wrap `DoFObjects` which only contains (aside from member functions) a `std::vector<types::global_dof_index>` I think relying on moves would be better.
2. Can we just use `std::vector` in 4f5b698eee051c8a748b125502eb05d9d4dc4642 instead of `new[]` and `delete[]`? Unless I am missing something each instance of `MGVertexDoFs` is responsible for both arrays.

**Comment by bangerth** [comment]
These might both make for good follow up patches and clean ups. I suspect that we used pointers in the past because we couldn't move these objects (which are big). I am pretty sure that writing the move operations requires some handwritten code that takes testing, and I won't get to it until I am back home and/or have Internet access from my laptop on a regular basis (I write this comment on my phone via the cell phone network; I expect to have Internet on my laptop only for half an hour or so per day for the next couple of weeks).

As for the MG vertex dofs class: maybe. In looking through it, I've made notes for a couple more cleanups. I'll put your idea there as well, if you allow me to defer.

**Comment by bangerth** [comment]
Oh, about the first point: leaving it as is has the advantage that it mirrors the structure in the triangulation and the hp DoFHandler class.

**Comment by drwells** [comment]
I don't mind deferring these until later; the main reason I brought this up now is that we may be able to avoid redoing the serialization tests a second time.

**Comment by bangerth** [comment]
Fair point, but given the state of my Internet connection, I'd rather leave this for another time :-)

**Comment by drwells** [comment]
I ran the full test suite and noticed no new failures due to these changes aside from the serialization tests. Since we are rewriting a lot of things I think that we should merge this as-is and ignore the failing tests.

I'll merge this later today unless there are objections.

**Pull request merged**
