### PR TITLE
Sort and remove some includes.

### PR DESCRIPTION
**Pull request by bangerth**
The mapping_*.h files did not all #include config.h as first
argument, as they should. They also include all sorts of files
they don't actually need. Remove these. Add them again in other
files that do need them but previously got them via mapping.h.

### CODE REVIEW

**Comment by drwells** [comment]
I have a branch where I fix a bunch of forward inclusions, which partially duplicates this. I should probably stop sitting on it. Related to this is I noticed a lot of tests rely on extra headers being included (I saw the same thing when working on improving forward declarations:

```
[wellsd2@rtg1 build]$ make -j32 setup_tests && ctest -j32 -R map
[...]

The following tests FAILED:
        1212 - fe/mapping_fe_field_real_to_unit_b3_curved.debug (Failed)
        1213 - fe/mapping_fe_field_real_to_unit_b3_curved.release (Failed)
        1220 - fe/mapping_fe_field_real_to_unit_q2_mask.debug (Failed)
        1221 - fe/mapping_fe_field_real_to_unit_q2_mask.release (Failed)
        1270 - fe/mapping_fe_field_real_to_unit_q1.debug (Failed)
        1271 - fe/mapping_fe_field_real_to_unit_q1.release (Failed)
        1323 - fe/mapping_fe_field_real_to_unit_b2_curved.debug (Failed)
        1324 - fe/mapping_fe_field_real_to_unit_b2_curved.release (Failed)
        1392 - fe/mapping_fe_field_real_to_unit_b5_curved.debug (Failed)
        1393 - fe/mapping_fe_field_real_to_unit_b5_curved.release (Failed)
        1494 - fe/mapping_fe_field_real_to_unit_q2_curved.debug (Failed)
        1495 - fe/mapping_fe_field_real_to_unit_q2_curved.release (Failed)
        1595 - fe/mapping_fe_field_real_to_unit_q4_curved.debug (Failed)
        1596 - fe/mapping_fe_field_real_to_unit_q4_curved.release (Failed)
        1632 - fe/mapping_fe_field_real_to_unit_q3_curved.debug (Failed)
        1633 - fe/mapping_fe_field_real_to_unit_q3_curved.release (Failed)
        1772 - fe/mapping_fe_field_real_to_unit_q5_curved.debug (Failed)
        1773 - fe/mapping_fe_field_real_to_unit_q5_curved.release (Failed)
        1808 - fe/mapping_fe_field_real_to_unit_b4_curved.debug (Failed)
        1809 - fe/mapping_fe_field_real_to_unit_b4_curved.release (Failed)
        1827 - fe/mapping_fe_field_real_to_unit_b1.debug (Failed)
        1828 - fe/mapping_fe_field_real_to_unit_b1.release (Failed)
        1887 - codim_one/mapping_q1_eulerian.debug (Failed)
        1888 - codim_one/mapping_q1_eulerian.release (Failed)
        2026 - grid/get_dof_to_support_patch_map_01.debug (Failed)
        2027 - grid/get_dof_to_support_patch_map_01.release (Failed)
        4421 - bits/map_dofs_to_support_points_hp_02.debug (Failed)
        4422 - bits/map_dofs_to_support_points_hp_02.release (Failed)
        4746 - bits/mapping_q_eulerian_04.debug (Failed)
        4747 - bits/mapping_q_eulerian_04.release (Failed)
```

and, upon inspection, these fail with inscrutable compilation errors :(

I see some open cascade warnings but those don't look related.

**Comment by drwells** [comment]
I would bet (but I have not examined this closely) that a lot of tests rely on `mapping_q1.h` to bring in a bunch of headers, so (and I have been pondering this exact situation for several days) I am on the fence as to whether or not we should remove these extra headers. If they break tests, then they will probably also break user codes.

**Comment by bangerth** [comment]
Aw, that's a bummer. But I would advocate to nevertheless fix up the header list -- there is a clear, backward compatible way for people to fix their codes. 

Let me run the testsuite and see what fails there and how hard it would be to fix it.

**Comment by bangerth** [comment]
Turns out that I can't do this until #2330 is merged because it blocks my big machine :-(

**Comment by bangerth** [comment]
My patch really does cause a whole bunch of errors in the testsuite. Should have checked this.

I'd say let's go ahead with @drwells 's #2332 and then I can rebase.

**Comment by bangerth** [comment]
Updated to current master.

**Comment by drwells** [comment]
Nice work; that seems to fix most of the tests. I see the following test failures on my machine:
```
The following tests FAILED:
        1887 - codim_one/mapping_q1_eulerian.debug (Failed)
        1888 - codim_one/mapping_q1_eulerian.release (Failed)
        1980 - grid/grid_tools_local_to_global_vertex_id.mpirun=2.release (Failed)
        3599 - manifold/spherical_manifold_06.debug (Failed)
        3600 - manifold/spherical_manifold_06.release (Failed)
        4746 - bits/mapping_q_eulerian_04.debug (Failed)
        4747 - bits/mapping_q_eulerian_04.release (Failed)
```
Of these only the first and last two are relevant (`1980` segfaults on my tester for reasons that are probably my fault).

`MappingQEulerian` and `MappingQ1Eulerian` both use `Vector<double>` as a default template parameter, but do not include the header. I think that they should include `vector.h`. Regardless of whether or not it is included the tests fail since they try to create `Vector<double>`s without the header.

**Comment by bangerth** [comment]
I've fixed the tests that cailed on my machine. I think this is ready for re-review and/or merge.

**Comment by drwells** [comment]
Unless someone beats me to this, I will look this over when I am back in Troy (Sunday).

**Pull request merged**
