### PR TITLE
Reduce number of threads in tests

### PR DESCRIPTION
**Pull request by kronbichler**
The more we use threading inside the library, the more it hurts to have many threads in tests. I suggest to change the number of threads to 3 rather than 5, because this will clearly reduce the load. On a 24-core machine, I see almost a factor of 1.5 in performance difference between a test suite run with or without threads.

Has anyone objections to this change? If we have a particular test that needs to increase the number of threads to trigger a certain behavior, we could always change the numbers locally. The large majority should do fine with moderate parallelism (more than 2 threads is good to have, but beyond 3 I see no value).

### CODE REVIEW

**Comment by bangerth** [comment]
I have no objections, but it's a controversial enough change that we should let others chime in as well.

**Comment by tamiko** [comment]
I am already exporting
```
export DEAL_II_NUM_THREADS=2
export OMP_NUM_THREADS=2
```
for `tester` - otherwise the testsuite hogs up the system too much (88 cores).

May I suggest to simply drop to 2 and I can remove this manual override? :-)
(If I remember correctly, 3 threads for every test instance was still a bit too much - 2 was the sweet spot.)

**Comment by tjhei** [comment]
> we could always change the numbers locally.

How would you work around the limit set in tests.h? I don't mind having it set to 2 for most tests but think the task related tests might profit from a higher number...

**Comment by drwells** [comment]
I don't have any intuition for what a  good value here would be; using more than two is probably good for finding weird bugs, so three sounds reasonable.

I already override this value in `task_09.cc` (where we spawn threads but immediately put them to sleep); in principle we could ignore the environment variable by calling `unsetenv` inside the tests that really need more than three threads.

**Comment by kronbichler** [comment]
> How would you work around the limit set in tests.h?

I have never really looked into the mechanisms of the tests, but I use `MultithreadInfo::set_thread_limit(xx)` often and it does what is supposed to do. I did a short test with a variant of `tests/matrix_free/step-48` and, unless `mpirun` does pinning (and thus slows down the whole thing), I get it to run on as many threads as I set. Is there any other mechanism inside the testing framework that overrides this?

**Comment by tjhei** [comment]
> Is there any other mechanism inside the testing framework that overrides this?

tests.h has a statically constructed thing that sets the limit, but I guess you can reset it (I wasn't sure about this), as @drwells says.

**Comment by kronbichler** [comment]
> I don't have any intuition for what a good value here would be; using more than two is probably good for finding weird bugs, so three sounds reasonable.

That's also why I chose 3. We can go lower to 2 as well if the majority wants that, but let's have a poll, :tada: for 2 or :smile: for 3.

**Comment by drwells** [comment]
Four people have signed off on this so lets merge.

**Pull request merged**
