### PR TITLE
Grammar mistake in step 2

### PR DESCRIPTION
**Pull request by eanovak**
Grammar mistake. Corrected "among" to "amount".

### CODE REVIEW

**Comment by tjhei** [comment]
Please remove the two files you added by accident (.DS_STORE something). Let one of us know if you need help.

**Comment by tjhei** [comment]
Also, please can you set your full name in your github profile?

**Comment by eanovak** [comment]
Done. I did what you asked. Thanks!

**Comment by bangerth** [comment]
Do you think you could also add an entry to `doc/news/changes/minor` so you can be listed as an author of deal.II?

**Comment by drwells** [comment]
Based on the discussion the developers had elsewhere, lets not worry about adding the changelog here: we can deal with that later on our own in one giant batch commit.

Thanks a lot for the fix @eanovak!

**Comment by bangerth** [comment]
@eanovak -- well done. I'm glad you stayed on for the deal.II workshop!

**Pull request merged**
