### PR TITLE
Simplify a function that returns an array.

### PR DESCRIPTION
**Pull request by bangerth**
Previously, it used a reference to an array as an output argument. Now, we can just
return a std::array<...,dim>.

This is strictly speaking an incompatible change. I suspect that the number of affected
people is going to exceedingly small, though, given that these are classes sort of at
the bottom of the stack and not used in user codes. (They are used in the implementations
of finite element classes.)

### CODE REVIEW

**Comment by masterleinad** [comment]
Some things to fix:
```
/Users/cib-osx/auto-dealii-tjhei-osx/dealii/source/base/polynomial_space.cc:52:11: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
  return {index_map[i]};
          ^~~~~~~~~~~~
          {           }
/Users/cib-osx/auto-dealii-tjhei-osx/dealii/source/base/polynomial_space.cc:73:15: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
      return {n-k, iy};
              ^~~~~~~
              {      }
/Users/cib-osx/auto-dealii-tjhei-osx/dealii/source/base/polynomial_space.cc:78:11: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
  return {numbers::invalid_unsigned_int, numbers::invalid_unsigned_int};
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          {                                                           }
/Users/cib-osx/auto-dealii-tjhei-osx/dealii/source/base/polynomial_space.cc:103:17: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        return {n-k, iy, iz};
                ^~~~~~~~~~~
                {          }
/Users/cib-osx/auto-dealii-tjhei-osx/dealii/source/base/polynomial_space.cc:108:11: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
  return {numbers::invalid_unsigned_int, numbers::invalid_unsigned_int};
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          {                                                           }
```

**Comment by bangerth** [comment]
Krkh. Let's see if it works now.

**Comment by masterleinad** [comment]
Now, it's an indenting issue:
```
diff --git a/source/base/polynomial_space.cc b/source/base/polynomial_space.cc
index 5cb4b3df..dd870dcb 100644
--- a/source/base/polynomial_space.cc
+++ b/source/base/polynomial_space.cc
@@ -71,8 +71,8 @@ compute_index (const unsigned int i) const
   for (unsigned int iy=0; iy<n_1d; ++iy)
     if (n < k+n_1d-iy)
       return {{n-k, iy}};
-    else
-      k+=n_1d-iy;
+  else
+    k+=n_1d-iy;
 
   Assert (false, ExcInternalError());
   return {{numbers::invalid_unsigned_int, numbers::invalid_unsigned_int}};
@@ -101,8 +101,8 @@ compute_index (const unsigned int i) const
     for (unsigned int iy=0; iy<n_1d-iz; ++iy)
       if (n < k+n_1d-iy-iz)
         return {{n-k, iy, iz}};
-      else
-        k += n_1d-iy-iz;
+  else
+    k += n_1d-iy-iz;
 
   Assert (false, ExcInternalError());
   return {{numbers::invalid_unsigned_int, numbers::invalid_unsigned_int}};
```
`astyle` doesn't understand what the `else` belongs to. I guess putting braces around the body of the `for` loop helps.

**Comment by bangerth** [comment]
Good grief. I think we really ought to consider upgrading our astyle version.

Let's see what terrible things happen now!

**Comment by masterleinad** [comment]
> Good grief. I think we really ought to consider upgrading our astyle version.

Or switch to `clang-format`? :wink:

> Let's see what terrible things happen now!

Now, everything looks reasonable. Thanks!

**Pull request merged**
