### PR TITLE
Rename Vector::val to Vector::values.

### PR DESCRIPTION
**Pull request by bangerth**
In the same spirit as #5273.

### CODE REVIEW

**Comment by masterleinad** [comment]
Is there any reason why you don't switch to a `std::unique_ptr` in this PR or do you just want to leave this for another PR?

**Comment by bangerth** [comment]
Yes, next patch. In the works, but logically separate and so I thought I'd submit this already now.

**Comment by bangerth** [comment]
This follow-up is in #5304.

**Pull request merged**
