### PR TITLE
Evaluation kernels: Avoid checking the orientations in inner loop

### PR DESCRIPTION
**Pull request by kronbichler**
This is done by adding an optional template argument that forces the compiler to create a second version of the code in case there are orientations to be taken into account. The alternative could have been to shuffle around the entries in the `temp` vector, similar to what we do for the action at the quadrature points (but typically more efficiently as there is less to reorder this way). Since we chose this path, I selected the first option for now, but we might also consider the latter if we want to reduce the code size.

### CODE REVIEW

**Comment by kronbichler** [comment]
Re-based and ready for review.

**Review by peterrum — APPROVED** [review]

**Comment by masterleinad** [comment]
```
In file included from /home/runner/work/dealii/dealii/include/deal.II/matrix_free/evaluation_template_factory.templates.h:23:0,
                 from /home/runner/work/dealii/dealii/source/matrix_free/evaluation_template_factory.cc:17,
                 from /home/runner/work/dealii/dealii/source/matrix_free/evaluation_template_factory_inst5.cc:17:
/home/runner/work/dealii/dealii/include/deal.II/matrix_free/evaluation_kernels.h: In function ‘void dealii::internal::fe_face_evaluation_process_and_io(Processor&, unsigned int, dealii::EvaluationFlags::EvaluationFlags, typename Processor::Number2_*, const std::vector<dealii::ArrayView<const typename Processor::Number2_> >*, const EvaluationData&, typename Processor::VectorizedArrayType_*) [with int n_face_orientations = 1; Processor = dealii::internal::FEFaceEvaluationImplGatherEvaluateSelector<3, double, dealii::VectorizedArray<double, 2> >::Processor<1>; EvaluationData = dealii::FEEvaluationData<3, dealii::VectorizedArray<double, 2>, true>; bool check_face_orientations = true]’:
/home/runner/work/dealii/dealii/include/deal.II/matrix_free/evaluation_kernels.h:3261:11: error: iteration 1 invokes undefined behavior [-Werror=aggressive-loop-optimizations]
           orientation[v] = &fe_eval.get_shape_info().face_orientations_dofs(
           ^~~~~~~~~~~
/home/runner/work/dealii/dealii/include/deal.II/matrix_free/evaluation_kernels.h:3260:36: note: within this loop
         for (unsigned int v = 0; v < n_lanes; ++v)
                                  ~~^~~~~~~~~
```

**Comment by kronbichler** [comment]
The problem should be fixed now, we should use the appropriate loop bound.

**Comment by masterleinad** [comment]
> The problem should be fixed now, we should use the appropriate loop bound.

I don't see a new commit (and the error persists after restarting the GitHub CI). Did you forget to push?

**Comment by bangerth** [comment]
It seems to work now with all of the CI checks.

**Pull request merged**
