### PR TITLE
Use a virtual destructor with virtual methods.

### PR DESCRIPTION
**Pull request by drwells**
This fixes a new warning.

### CODE REVIEW

**Review by peterrum — APPROVED** [review]

**Comment by drwells** [comment]
Those are some interesting failures. I'm investigating.

**Comment by peterrum** [comment]
A general remark. Maybe we could enable some compiler warnings in the the GitHub tests so that we already catch such issues already during the PR. I did that for braces a month ago...

**Comment by tjhei** [comment]
what is the precise warning?

**Comment by drwells** [comment]
I have `-Wnon-virtual-dtor` enabled.

**Pull request merged**
