### PR TITLE
Update test output.

### PR DESCRIPTION
**Pull request by bangerth**
This fixes two output files following the changes made by @davydden in #2064.

### CODE REVIEW

**Comment by davydden** [comment]
can you please create a third one for `step-36_parallel.with_mpi=true.with_petsc=true.with_slepc=true.mpirun=3.output.2`? The current `2` is the vecrsion which works on desktop Ubuntu 14.04.

**Comment by bangerth** [comment]
Sure :-)

**Comment by bangerth** [comment]
(I took that as an opportunity to teach myself about `git reset --mixed` :-)

**Comment by davydden** [comment]
i don't even know what `reset --mixed` is ;-)

**Pull request merged**
