### PR TITLE
Fix number usage in functions

### PR DESCRIPTION
**Pull request by bangerth**
This removes the second template argument on `Point<dim,Number>` when used as an argument in `Function` objects.

This addresses one part of #526

### CODE REVIEW

**Comment by bangerth** [comment]
I did verify @tjhei 's concern that this
```
struct X 
{
  virtual void f(double);
};

template <typename T>
struct Y : public X
{
  virtual void f(T);
};

Y<double> y;
```
neither triggers an error nor overloads the wrong signature. It does trigger a warning if you instantiate `Y<float>`, though. Under the assumption that nobody actually ever used a different type than `double` for `Function` (because it wasn't useful), I suppose this patch is safe then.

**Comment by kronbichler** [comment]
This looks good.

**Comment by tjhei** [comment]
Agreed. Is this ready to be merged, Wolfgang? Is it worth mentioning in changelog?

**Comment by kronbichler** [comment]
I guess we should mention it when we have removed the template on Point<dim>, which I will start right now.

**Comment by bangerth** [comment]
Yes, it's ready.

I thought about writing an entry to changes.h about just this change, but it seemed like it would be subsumed anyway by whatever we write about removing the second argument to `Point`.

**Comment by luca-heltai** [comment]
I'm a bit late to this discussion, but it occurred to me that one of the reasoning for having a templated argument on Point would be to allow Sacado types in points. Think of this scenario:

Point<3, SacadoDouble> p;
... // initialize p correctly for Sacado 

SomeFunction<3, SacadoDouble> function;

SacadoDouble f = function(p);

f.diff(0);

If we remove the second template from point, the above cannot work. 

L.

--
Luca Heltai <luca.heltai@gmail.com>
http://people.sissa.it/~heltai/
Scuola Internazionale Superiore di Studi Avanzati
Phone:  +39 040 3787 449, Office: 622
--
There are no answers, only cross references

**Pull request merged**
