### PR TITLE
Remove sundials/copy.h

### PR DESCRIPTION
**Pull request by peterrum**
In theory we could do this step now: it is internal and internally we are not using the function. What are the opinions?

### CODE REVIEW

**Comment by luca-heltai** [comment]
I agree.

**Review by luca-heltai — APPROVED** [review]

**Review by tamiko — APPROVED** [review]

**Comment by luca-heltai** [comment]
You forgot to remove the include statement from `ida.cc`:

   /jenkins/workspace/dealii_PR-12230/source/sundials/ida.cc:37:39: fatal error: deal.II/sundials/copy.h: No such file or directory

**Comment by peterrum** [comment]
> You forgot to remove the include statement from ida.cc

That is what you are doing in #12200 ;) I will rebase once that PR is merged!

**Pull request merged**
