### PR TITLE
Remove duplicate memory freeing in GMRES

### LINKED ISSUE #885: GMRES causes segmentation fault in corner case
If the GMRES setting `use_default_residual` is set to `false` and the initial value is already a solution the solver produces a `segmentation fault`. 

The reason for this is that the memory for the temporary variables `r`, `x_` and `gamma_` is freed twice in this scenario: Once directly inside the check if the initial solution is good enough ([here](https://github.com/dealii/dealii/blob/1d8716d2b36ae812566ba0617467ef424cf86482/include/deal.II/lac/solver_gmres.h#L718-L721)) and once at the end of the function (at cleanup, [here](https://github.com/dealii/dealii/blob/1d8716d2b36ae812566ba0617467ef424cf86482/include/deal.II/lac/solver_gmres.h#L885-L888)).

### PR DESCRIPTION
**Pull request by fsonner**
Fixes #885.

### CODE REVIEW

**Comment by bangerth** [comment]
This seems reasonable. Could you create a test that failed before and now succeeds?

**Comment by tjhei** [comment]
Agreed, logic makes sense.

**Comment by fsonner** [comment]
I couldn't figure out whether you use any kind of test naming conventions (i.e. I didn't see one), so I just took the simplest route and hijacked a very similar test about memory leaks in the scenario I described.

**Comment by bangerth** [comment]
Almost perfect: leave the existing test in place and just clone it into a new one. By modifying am existing one,  you essentially remove the test that currently runs. What you want is to just /add/ a new test.

**Comment by fsonner** [comment]
I intentionally modified the old test, because it was just missing a call with different constructor arguments. I didn't remove any of the old functionality though. From skimming the existing tests I thought you have no one-test-per-issue rule, but if that's not the case maybe the issue number should be included directly in the test name (for example `lac/gmres_fix_886.cc`).

**Comment by bangerth** [comment]
I misread your testcase -- I thought that you were modifying an existing code, not just adding something to it. This is fine.

On the more general question of one test per issue: many years ago we had no such rule, and we often mixed different issues into one test. The one you have may be one of those. Another example is `base/utilities_01`. But over time we've come to realize that it is much better to have one (or multiple) small unit tests for each issue, as this makes finding the cause for problems so much easier.

I don't think the issue is worth going back and forth here, so I'm going to merge your patch (thanks very much for tracking this down, by the way!), but it may be worth keeping in mind for the future.

**Pull request merged**
