### PR TITLE
Attempt to work around a compiler warning.

### PR DESCRIPTION
**Pull request by bangerth**
#10786 shows a problem with a compiler warning (unwarranted). But it would be nice to do what #10786 wants to do, so let's try to work around this issue.

/rebuild

### CODE REVIEW

**Comment by masterleinad** [comment]
Do you know if that actually helps with #10786? Otherwise, it would be a good idea to just push this commit to that branch to see.

**Comment by tjhei** [comment]
I cherry-picked it and pushed to the other branch...

**Comment by masterleinad** [comment]
> I cherry-picked it and pushed to the other branch...

Seems to work.

**Comment by tjhei** [comment]
awesome, thanks @bangerth !

**Comment by bangerth** [comment]
OK, thanks for checking!

**Pull request merged**
