### PR TITLE
Provide 64-bit test output variants.

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Comment by masterleinad** [comment]
Hmm... these tests work for me even using 64-bit indices. This implies that the new output for 64-bit indices would probably fail for me.

**Comment by bangerth** [comment]
Hm. We already have two variants for the existing cases. Can you double-check which one of the two you are using in the 32-bit case?

**Comment by masterleinad** [comment]
Using `clang-5` and `metis-5.1.0` the outputfile `sharedtria/communicate_active_fe_indices_01.with_metis\=true.mpirun\=3.output` is the correct output both for 64-bit and 32-bit indices.

**Comment by drwells** [comment]
These tests also pass for me in 64-bit mode. @bangerth What version of metis are you using? I have 5.1.0.

**Comment by drwells** [comment]
This does not conflict with #5131 but does concern the same tests.

**Comment by drwells** [comment]
Metis is tempermental enough that I would be happy just merging this without reproducing the output myself. Unless someone objects I propose that we do that in the next day or so.

**Comment by masterleinad** [comment]
Yes, I object. This modification makes the test fail for me with 64-bit indices.

**Comment by drwells** [comment]
Am I missing something? I thought that this PR just added new alternative outputs.

**Comment by masterleinad** [comment]
> Am I missing something? I thought that this PR just added new alternative outputs.

No, it renames the current output files to be used for 32-bit indices and adds new ones for 64-bit indices. Since the current output files work for me, the tests would start failing for me.

**Comment by drwells** [comment]
Ah, I see. I misunderstood how the files were being moved.

**Comment by bangerth** [comment]
For reference, I'm using the METIS that PETSc 3.7.4 installs when configured with `--with-metis`. That seems to be 5.1.0.

I think this just shows that we should ask ourselves "What have we done in using METIS?" :-( Anyone got alternative suggestions? Should we just use the z-ordering always? What do we do with partitioning coarse meshes? Or should we take and distribute a patched version of METIS that is reproducible?

**Comment by davydden** [comment]
> "What have we done in using METIS?" :-( Anyone got alternative suggestions?

not really. Maybe we shall just re-work unit tests so that they do not output partitioning.

> Or should we take and distribute a patched version of METIS that is reproducible?

If the patch from `non-reproducable` to `reproducable` is small, then one can store them somewhere and recommend users applying it. For example, Spack already patches `parmetis` using PETSc's bugfixes, see https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/parmetis/package.py#L52-L55 . One can do the same with Metis.

But this might also be too big an effort to actually dig into the METIS code and see what's going on.

**Comment by davydden** [comment]
@bangerth one could try [Scotch](https://gforge.inria.fr/projects/scotch/) (6.0.4 released in 2015-03-19), probably [Zoltan](https://trilinos.org/packages/zoltan2/) has what what is needed as well; there is also [KaHIP](http://algo2.iti.kit.edu/kahip/).

**Comment by tjhei** [comment]
> Should we just use the z-ordering always?

I think we should just use the z-ordering flag for most tests (especially new ones).

**Comment by bangerth** [comment]
Could we make z-order the default? We'd have to adjust the existing tests (or explicitly make them use METIS), but at least it lessens the pain going forward.

What does z-order do for partitioning the coarse mesh if that happens to be large?

**Comment by tjhei** [comment]
> What does z-order do for partitioning the coarse mesh if that happens to be large?

Identical to p4est: https://github.com/dealii/dealii/blob/ce2d4770c190c24294afcbd75dabbb173663389d/source/grid/grid_tools.cc#L2494

**Comment by bangerth** [comment]
Do you think this would be good enough for at most around 100 or so processors?

**Comment by tjhei** [comment]
> Do you think this would be good enough for at most around 100 or so processors?

Depends on what "good enough" means. We use it for thousands of processors when using p4est, but we typically refine adaptively then and their is no easy way to use something better. I am pretty sure the METIS partitioning gives better parallel performance as soon as you leave a single node. I think METIS is the better default, but I would use z-order for all but 1-2 tests.

**Comment by bangerth** [comment]
Let's close this. I'll get back to it when necessary.

**Pull request closed without merging**
