### PR TITLE
[WIP] Convert FEValuesViews::*::get_function_values_from_...

### PR DESCRIPTION
**Pull request by bangerth**
This is a try at #4883 where we were talking about converting some of the FEValuesViews::*
member functions to take an ArrayView instead of a std::vector. @drwells -- was this
about what you had in mind?

### CODE REVIEW

**Comment by drwells** [comment]
@bangerth Yes. Unfortunately, while this is an easy patch, I already wrote a broken (relative to the const reference weirdness) version:

https://github.com/drwells/dealii/commit/f9e1c478548a32aaff6eac40df9968d55809483d

**Comment by bangerth** [comment]
Yes, I didn't want to propose this as a serious patch. I was just saying that this seems to work :-) If you have a more complete version, by all means let's go with it!

**Comment by bangerth** [comment]
Yes, this can't work if you don't explicitly specify what `T` is: There is potentially an infinite number of `T`s for which the argument is convertible to `ArrayView<T>`. If you don't want to explicitly specify `T`, then there needs to be a different way for the compiler to deduce what `T` is (as there is in #5100, for example).

**Comment by bangerth** [comment]
Let's close this -- #4883 still links to it if someone wants to look this up, and it was a trial balloon only anyway.

**Pull request closed without merging**
