### PR TITLE
Replace message-less exceptions with ones that say what's happening.

### PR DESCRIPTION
**Pull request by bangerth**
In response to a question on the mailing list. In reference to #610.

### CODE REVIEW

**Comment by drwells** [comment]
This is a nice improvement. Would you mind moving the 'DoF indices' exception into its own named class, i.e., something like `StandardExceptions::ExcUninitializedDoFHandler`?

**Comment by bangerth** [comment]
I've moved away from these kinds of (globally visibile) exceptions in general, but more specifically I've also moved away from using named exception classes unless they take arguments or are used in a number of places. Or was your point about the duplication of the error message?

**Comment by bangerth** [comment]
Because in that latter case, I could just move the exception class declaration into the surrounding class or namespace, instead of a global place.

**Comment by drwells** [comment]
My concern is the duplication. I don't mind too much were it goes, but I think it would be worthwhile to name this exception and put it somewhere so that we don't have to keep duplicating the message.

**Comment by tamiko** [comment]
@bangerth I agree with one exception - I am a huge fan of `ExcNotImplemented`.

**Comment by bangerth** [comment]
Correct. But `ExcNotImplemented` has a lengthy description of what is happening.

**Comment by bangerth** [comment]
@drwells -- I replaced the repeated error messages by an exception class in the `DoFRenumbering` namespace.

**Comment by drwells** [comment]
That is a better place to put it.

**Pull request merged**
