### PR TITLE
Convert PETSc SNES interfaces to use callback error conventions.

### PR DESCRIPTION
**Pull request by bangerth**
The last patch for #15112. Same style as #15269. Including a couple of tests that check that PETSc SNES does not try to backtrack just because a user callback errors out with an exception.

### CODE REVIEW

**Comment by stefanozampini** [comment]
@bangerth Can you apply the patch attached? We can recover from errors in the function
[snes.txt](https://github.com/dealii/dealii/files/11575986/snes.txt)

**Comment by bangerth** [comment]
Can I ask for this patch to be merged without @stefanozampini 's addition? It tests cleanly and is self-contained. I will take care of the changes @stefanozampini suggests in a separate patch.

**Comment by bangerth** [comment]
@stefanozampini As for the change you propose, I don't think I understand. You can't just eat the exception, you have to communicate the fact that the user function did not compute anything useful to the underlying library. In SUNDIALS, this is done by returning a positive error code. SUNDIALS then tries again with a shorter step. How do you intend to do this with PETSc?

(In your suggested patch, you change the logic of eating *any* exception to return -1 into code where only `RecoverableUserCallbackError` is turned into -1. Every other exception leads to incorrect code because you throw an exception that propagates through PETSc code, presumably leading to memory leaks and all sorts of other problems. I don't think this is right, and so would like to postpone this to a separate PR.)

**Review by stefanozampini — APPROVED** [review]

**Comment by bangerth** [comment]
On 5/26/23 13:30, Stefano Zampini wrote:
> The way you signal failure in function evaluation is by setting the residual 
> vector to a quiet_nan value (1.0/0.0)

Oh, seriously? That's certainly an interesting design. Is that documented 
anywhere?

A better design would have re-used the return code, like SUNDIALS does. That's 
because this is independent of the specific function: Your solution only works 
for the residual function, but the same kind of error could happen for the 
Jacobian construction, or the linear solve for example, for which you don't 
have the benefit of a simple object you can inspect.

**Comment by stefanozampini** [comment]
@bangerth I have opened an issue https://gitlab.com/petsc/petsc/-/issues/1388. We can continue the discussion there

**Review by luca-heltai — APPROVED** [review]

**Comment by jedbrown** [comment]
I'll follow up in the new PETSc issue, but as I understand the request, [`SNESSetFunctionDomainError`](https://petsc.org/main/manualpages/SNES/SNESSetFunctionDomainError/) would be the preferred interface.

**Comment by bangerth** [comment]
Thanks, @jedbrown . This is not high on our priority list. I do very much like the design the SUNDIALS folks chose, though, because in many cases one really can just choose a smaller step length and re-try the user call.

**Comment by jedbrown** [comment]
Sorry, which interface? Retrying with a smaller step is natural logic after `SNESSetFunctionDomainError` has been called.

**Comment by stefanozampini** [comment]
> Sorry, which interface? Retrying with a smaller step is natural logic after `SNESSetFunctionDomainError` has been called.

If you mean the interface to snes in deal.ii, it is here https://github.com/dealii/dealii/blob/master/include/deal.II/lac/petsc_snes.templates.h

**Comment by bangerth** [comment]
@jedbrown Are you saying that there is already a way for a callback to indicate that, for example, the residual cannot be computed at the current point? A way that does not rely on the return value of the callback?

**Comment by jedbrown** [comment]
Yeah, that's what the interface is for. I too wish C had better ergonomics for error handling, but the petsc way is to not abuse error codes for non- error conditions. 

https://petsc.org/main/manualpages/SNES/SNESSetFunctionDomainError/#snessetfunctiondomainerror

**Comment by stefanozampini** [comment]
Which translates to VecSetInf, the same I'm doing here https://gitlab.com/petsc/petsc/-/blob/main/src/snes/interface/snes.c#L2457

**Comment by stefanozampini** [comment]
> but the petsc way is to not abuse error codes for non- error conditions.

I would not call abuse handling a special error code that can only be raised by user callbacks

**Comment by bangerth** [comment]
@jedbrown I don't think that differentiating between different non-zero return values is an abuse. The abuse of course is to try and map error codes onto function return values. That's why C++ has exceptions and, more recently, [std::expected](https://en.cppreference.com/w/cpp/utility/expected).

I'm sure we can somehow shoehorn the call to `SNESSetFunctionDomainError` into our interfaces. Before I/Stefano do this, though: This call only applies to SNES residual calls. Not to any of the other callbacks (e.g., setting up or using the Jacobian matrix), right?

**Comment by jedbrown** [comment]
PETSc evaluates residuals before Jacobians (indeed, some users tuck Jacobian evaluation into each residual, though that's not an optimization in the presence of a line search). There is `SNESSetJacobianDomainError`. Some SNES implementations have distinct handling of `snes->domainerror` so I'd encourage using the interfaces rather than raw `VecSetInf`.

There's always a tension between gracefully handling errors (without leaks or deadlocks) and providing enough information to debug. The former is hard when error conditions are reached non-collectively and `PetscError` is intended for the latter. I'm not going to litigate one way or another here. I want graceful recoveries in more circumstances, but those code paths are very hard to test and IMO, language support is necessary to make asynchronous consensus amid non-collective errors tenable. (Linear types might be enough to make it possible with Rust, but it's open research to the best of my knowledge.)

**Pull request merged**
