### PR TITLE
Fixed bug in DiagonalBlockLinearOperator.

### PR DESCRIPTION
**Pull request by luca-heltai**
I was getting always errors of this type:
~~~
/Applications/deal.II.app/Contents/Resources/include/deal.II/lac/block_linear_operator.h:401:25: No member named 'n_block_rows' in 'std::__1::array<std::__1::array<dealii::LinearOperator<dealii::TrilinosWrappers::MPI::Vector, dealii::TrilinosWrappers::MPI::Vector>, 2>, 2>'
~~~
since the constructor for the diagonal block operator was using a call to `block_linear_operator` that the compiler interpreted in the wrong way.

This fixes this, by specifying explicitly the template parameters.

### CODE REVIEW

**Comment by bangerth** [comment]
Do you have something that could be used as a test for this? It's subtle enough that it's not hard to conceive someone removing the explicit specification of template arguments in the next rewrite.

**Comment by luca-heltai** [comment]
The added tes fails on current master, and succeeds on this branch.

**Comment by luca-heltai** [comment]
I think the compilers sees a template function with one template parameter, (`block_blah<BlockMatrixType>(const BlockMatrixType &m`) and one which takes instead an array (block_blah<int m, int n, OpType>(const std::array<std::array<OpType, m>, n > &ops`) If you pass the array as `{a,b}`, then it happily uses the fist version of the template instead of the second one. 

By explicitly calling the second, we force cxx11 to interpret `{a,b}` as initializer lists for an array, and not as some weird `BlockMatrixType`...

**Comment by luca-heltai** [comment]
merge?

**Comment by bangerth** [comment]
The new test fails with a compiler error: http://cdash.kyomu.43-1.org/testDetails.php?test=26369202&build=14398

Would one of you take a look?

**Comment by bangerth** [comment]
Here's the error message:
```

/node/bangerth/trunk/dealii/tests/lac/block_linear_operator_05.cc:47:94: error: call of overloaded ‘block_diagonal_operator(<brace-enclosed initializer list>)’ is ambiguous
/node/bangerth/trunk/dealii/tests/lac/block_linear_operator_05.cc:47:94: note: candidates are:
/node/bangerth/trunk/dealii/include/deal.II/lac/block_linear_operator.h:563:1: note: dealii::BlockLinearOperator<Range, Domain> dealii::block_diagonal_operator(const std::array<dealii::LinearOperator<typename Range::BlockType, typename Domain::BlockType>, m>&) [with long unsigned int m = 2ul, Range = dealii::TrilinosWrappers::MPI::BlockVector, Domain = dealii::TrilinosWrappers::MPI::BlockVector, typename Domain::BlockType = dealii::TrilinosWrappers::MPI::Vector, typename Range::BlockType = dealii::TrilinosWrappers::MPI::Vector]
/node/bangerth/trunk/dealii/include/deal.II/lac/block_linear_operator.h:607:1: note: dealii::BlockLinearOperator<Range, Domain> dealii::block_diagonal_operator(const dealii::LinearOperator<typename Range::BlockType, typename Domain::BlockType>&) [with long unsigned int m = 2ul, Range = dealii::TrilinosWrappers::MPI::BlockVector, Domain = dealii::TrilinosWrappers::MPI::BlockVector, typename Domain::BlockType = dealii::TrilinosWrappers::MPI::Vector, typename Range::BlockType = dealii::TrilinosWrappers::MPI::Vector]
/node/bangerth/trunk/dealii/tests/lac/block_linear_operator_05.cc:47:94: error: unable to deduce ‘auto’ from ‘<expression error>’
/node/bangerth/trunk/dealii/tests/lac/block_linear_operator_05.cc:48:92: error: call of overloaded ‘block_diagonal_operator(<brace-enclosed initializer list>)’ is ambiguous
/node/bangerth/trunk/dealii/tests/lac/block_linear_operator_05.cc:48:92: note: candidates are:
/node/bangerth/trunk/dealii/include/deal.II/lac/block_linear_operator.h:563:1: note: dealii::BlockLinearOperator<Range, Domain> dealii::block_diagonal_operator(const std::array<dealii::LinearOperator<typename Range::BlockType, typename Domain::BlockType>, m>&) [with long unsigned int m = 2ul, Range = dealii::TrilinosWrappers::BlockVector, Domain = dealii::TrilinosWrappers::BlockVector, typename Domain::BlockType = dealii::TrilinosWrappers::Vector, typename Range::BlockType = dealii::TrilinosWrappers::Vector]
/node/bangerth/trunk/dealii/include/deal.II/lac/block_linear_operator.h:607:1: note: dealii::BlockLinearOperator<Range, Domain> dealii::block_diagonal_operator(const dealii::LinearOperator<typename Range::BlockType, typename Domain::BlockType>&) [with long unsigned int m = 2ul, Range = dealii::TrilinosWrappers::BlockVector, Domain = dealii::TrilinosWrappers::BlockVector, typename Domain::BlockType = dealii::TrilinosWrappers::Vector, typename Range::BlockType = dealii::TrilinosWrappers::Vector]
/node/bangerth/trunk/dealii/tests/lac/block_linear_operator_05.cc:48:92: error: unable to deduce ‘auto’ from ‘<expression error>’
```

**Comment by luca-heltai** [comment]
I cannot reproduce this on any of my machines... @tamiko , do you have any idea?

**Comment by tamiko** [comment]
@luca-heltai: gcc-4.6 is buggy.

**Comment by bangerth** [comment]
I moved the discussion to #1869.

**Pull request merged**
