### PR TITLE
Do the work of compute_fill() in parallel over the base elements.

### PR DESCRIPTION
**Pull request by bangerth**
This patch still lacks a changelog entry, and it will collide with #1152 when that is merged. But I thought I'd throw it out here. It simply parallelizes the loop over all base elements.

It passes the testsuite with no new failures.

### CODE REVIEW

**Comment by bangerth** [comment]
By way of explanation, I simply broke the body of the loop out into its own function. There is no change to that code itself.

**Comment by tjhei** [comment]
looks good, please rebase.

**Comment by bangerth** [comment]
Done. This is ready.

This patch would have been a lot more elegant with lambda functions :-(

**Comment by guidokanschat** [comment]
Indeed :-(

**Pull request merged**
