### PR TITLE
Remove unused variable and header files

### PR DESCRIPTION
**Pull request by RichardYCJ**
This is related to #16275 and I also remove two header files that is not used in the source file, which is pointed out by clangd.

### CODE REVIEW

**Review by drwells — APPROVED** [review]

**Comment by bangerth** [comment]
Thank you. 

Out of curiosity, what is the tool you use to see that there are unused include files? This would be useful to run on more files than just this one!

**Comment by RichardYCJ** [comment]
> Thank you.
> 
> Out of curiosity, what is the tool you use to see that there are unused include files? This would be useful to run on more files than just this one!

I use `clangd` as the language server. Since it is based on llvm, clangd can provide powerful and precise of code checking and IntelliSense up to compiler level. It also integrates `clang-format` and `clang-tidy`

I use the VSCode to do the coding and here's how I would see the warnings. There is of course a way that clangd can be used as a command (as it should) I could do some research if you would like to have a script in the contrib directory.
image

Actually, there's a `.clang-tidy` file in our repo and it could do a lot of bug-prone and code efficiency checkings. I had already seen some of these warnings in the code but couldn't find them for the moment.

**Comment by bangerth** [comment]
If that thing checking `#include` files could be hooked into `.clang-tidy`, that would be great. If that's something you'd be interested in exploring, we would love that!

Pretty much every file in deal.II is edited at some point or other every year. In each of these edits, `#include` files are added as necessary, but one generally doesn't notice that an `#include` file is no longer necessary, and I suspect that many `#include`s are in fact not necessary at all -- but they slow down compilation. So having a system that would remove these again would be great.

**Pull request merged**
