### PR TITLE
Workaround: fix compilation with icc and linear_operator

### PR DESCRIPTION
**Pull request by tamiko**
Disables the sfinae lookup in the has_vmult_add helper class for icc.
Intel's compiler up version 15.0.3 run into an sfinae bug otherwise.

With this, has_vmult_add will always report "false" for icc which will
result in a slight performance penalty due to unnecessary temporary
storage.

### CODE REVIEW

**Comment by tamiko** [comment]
Has somebody a smarter solution (that does not involve rewriting everything from scratch with proper type-trait classes)?

**Comment by bangerth** [comment]
It would be nice to have a feature test so that future compilers don't suffer. Also, since you have a workaround, why disable the test when using intel?

What I would really like to see is a small snippet that demonstrates the failure. I'm not yet completely convinced that this is really the solution.

**Comment by bangerth** [comment]
Can you also add a link here to the error messages you currently get (or just copy-paste them)?

**Comment by tamiko** [comment]
@bangerth I'll try to extract a unit test.

**Comment by tamiko** [comment]
@bangerth : Updated. You'll find the explanation of what is going on in <code>cmake/checks/check_03_compiler_bugs.cmake</code>

**Comment by bangerth** [comment]
Thanks, this is very nice and clear.

Out of curiosity, do you happen to know whether that is a known bug in ICC? If not, maybe it would be worthwhile posting a bug report with them...

**Comment by tamiko** [comment]
I haven't investigated so far.

**Pull request merged**
