### PR TITLE
Remove LA::Vector.

### PR DESCRIPTION
**Pull request by drwells**
We agreed to convert VectorSpaceVector a concept which makes this approach no longer relevant.

Part of #3073.

### CODE REVIEW

**Review by bangerth — APPROVED** [review]

**Review by tamiko — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]

**Comment by bangerth** [comment]
Well, it doesn't work:
```
/home/runner/work/dealii/dealii/include/deal.II/trilinos/nox.templates.h:162:17: error: member access into incomplete type 'std::__shared_ptr_access<dealii::LinearAlgebra::EpetraWrappers::Vector, __gnu_cxx::_S_atomic, false, false>::element_type' (aka 'dealii::LinearAlgebra::EpetraWrappers::Vector') [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/trilinos/nox.templates.h:164:19: error: no viable overloaded '=' [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/trilinos/nox.templates.h:203:17: error: member access into incomplete type 'std::__shared_ptr_access<dealii::LinearAlgebra::EpetraWrappers::Vector, __gnu_cxx::_S_atomic, false, false>::element_type' (aka 'dealii::LinearAlgebra::EpetraWrappers::Vector') [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/trilinos/nox.templates.h:220:17: error: member access into incomplete type 'std::__shared_ptr_access<dealii::LinearAlgebra::EpetraWrappers::Vector, __gnu_cxx::_S_atomic, false, false>::element_type' (aka 'dealii::LinearAlgebra::EpetraWrappers::Vector') [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/trilinos/nox.templates.h:244:17: error: member access into incomplete type 'std::__shared_ptr_access<dealii::LinearAlgebra::EpetraWrappers::Vector, __gnu_cxx::_S_atomic, false, false>::element_type' (aka 'dealii::LinearAlgebra::EpetraWrappers::Vector') [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/trilinos/nox.templates.h:246:17: error: member access into incomplete type 'std::__shared_ptr_access<dealii::LinearAlgebra::EpetraWrappers::Vector, __gnu_cxx::_S_atomic, false, false>::element_type' (aka 'dealii::LinearAlgebra::EpetraWrappers::Vector') [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/trilinos/nox.templates.h:263:29: error: member access into incomplete type 'std::__shared_ptr_access<dealii::LinearAlgebra::EpetraWrappers::Vector, __gnu_cxx::_S_atomic, false, false>::element_type' (aka 'dealii::LinearAlgebra::EpetraWrappers::Vector') [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/trilinos/nox.templates.h:266:33: error: no viable overloaded '=' [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/trilinos/nox.templates.h:283:26: error: member access into incomplete type 'std::__shared_ptr_access<dealii::LinearAlgebra::EpetraWrappers::Vector, __gnu_cxx::_S_atomic, false, false>::element_type' (aka 'dealii::LinearAlgebra::EpetraWrappers::Vector') [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/trilinos/nox.templates.h:285:26: error: member access into incomplete type 'std::__shared_ptr_access<dealii::LinearAlgebra::EpetraWrappers::Vector, __gnu_cxx::_S_atomic, false, false>::element_type' (aka 'dealii::LinearAlgebra::EpetraWrappers::Vector') [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/trilinos/nox.templates.h:315:28: error: invalid operands to binary expression ('std::__shared_ptr_access<dealii::LinearAlgebra::EpetraWrappers::Vector, __gnu_cxx::_S_atomic, false, false>::element_type' (aka 'dealii::LinearAlgebra::EpetraWrappers::Vector') and 'std::__shared_ptr_access<dealii::LinearAlgebra::EpetraWrappers::Vector, __gnu_cxx::_S_atomic, false, false>::element_type') [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/trilinos/nox.templates.h:324:24: error: member access into incomplete type 'std::__shared_ptr_access<dealii::LinearAlgebra::EpetraWrappers::Vector, __gnu_cxx::_S_atomic, false, false>::element_type' (aka 'dealii::LinearAlgebra::EpetraWrappers::Vector') [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/trilinos/nox.templates.h:397:35: error: no viable overloaded '=' [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/trilinos/nox.templates.h:409:35: error: no viable overloaded '=' [clang-diagnostic-error]
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/ext/aligned_buffer.h:94:23: error: invalid application of 'sizeof' to an incomplete type 'dealii::LinearAlgebra::EpetraWrappers::Vector' [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/trilinos/nox.templates.h:118:42: error: incomplete type 'dealii::LinearAlgebra::EpetraWrappers::Vector' named in nested name specifier [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/trilinos/nox.templates.h:188:43: error: incomplete type 'dealii::LinearAlgebra::EpetraWrappers::Vector' named in nested name specifier [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/trilinos/nox.templates.h:281:26: error: member access into incomplete type 'std::__shared_ptr_access<dealii::LinearAlgebra::EpetraWrappers::Vector, __gnu_cxx::_S_atomic, false, false>::element_type' (aka 'dealii::LinearAlgebra::EpetraWrappers::Vector') [clang-diagnostic-error]
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/ext/aligned_buffer.h:91:28: error: invalid application of 'sizeof' to an incomplete type 'dealii::LinearAlgebra::EpetraWrappers::Vector' [clang-diagnostic-error]
```
I suspect you need to add an `#include` file somewhere that doesn't get that information transitively any more.

**Comment by drwells** [comment]
You're right - `nox.cc` relied on `read_vector.h` including the epetra and tpetra vector headers. I added both back in.

**Review by tamiko — CHANGES_REQUESTED** [review]
The test `lac/vector_type_traits_is_serial_01` (and maybe others) need updating:
```
/lac/vector_type_traits_is_serial_01.debug/failing_diff
lac/vector_type_traits_is_serial_01.debug: DIFF failed. ------ First 20 lines of numdiff output:
----------------
##16      #:2   <== 1
##16      #:2   ==> 0
@ Absolute error = 1.0000000000e+0, Relative error = Inf
----------------
##17      #:2   <== 1
##17      #:2   ==> 0
@ Absolute error = 1.0000000000e+0, Relative error = Inf
----------------
##18      #:2   <== 1
##18      #:2   ==> 0
@ Absolute error = 1.0000000000e+0, Relative error = Inf
----------------
##19      #:2   <== 1
##19      #:2   ==> 0
@ Absolute error = 1.0000000000e+0, Relative error = Inf
----------------
##27      <== DEAL::
          ==>
```

**Comment by drwells** [comment]
Fixed!

**Pull request merged**
