### PR TITLE
Tensor<rank, dim, Number>: Generalize contract3 for arbitrary tensor ranks

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Comment by bangerth** [comment]
Do we have tests that exercise this new function?

**Comment by bangerth** [comment]
(Or the old variations it replaces?)

**Comment by tamiko** [comment]
Yes, ```base/tensor_accessors_04``` tests the underlying function in ```TensorAccessors```. ```base/tensor_08``` checks one of the former signatures.

I can also put the additional deallog output after "manually verified" in ```tensor_accessors_04``` back in place.

**Comment by bangerth** [comment]
No need. Good enough.

**Comment by tamiko** [comment]
In reference to #1583

**Pull request merged**
