### PR TITLE
Add a comment describing the real to unit logic.

### PR DESCRIPTION
**Pull request by drwells**
This explains the choices made when switching between the closed formula and the newton iteration algorithm, which was brought up again when closing #866. This clarifies the choices I made regarding when to use Newton iteration or the 2D formula.

### CODE REVIEW

**Comment by tamiko** [comment]
Thanks a lot!

**Comment by bangerth** [comment]
As a complete aside (and not a request that you actually implement this): The way you currently implement the exact formula is that the function returns a point (2,2) outside the reference cell when the exact formula doesn't succeed. I think, conceptually, this is a case where throw-catch exceptions would have been appropriate: there is no useful value you can actually return that indicates that the formula failed. So you make up a convention for which return values you consider "within the range of expected values" and which are "exceptional". But that's exactly what exceptions are there for: to exit a function with an "exceptional value" without trying to shoehorn this exceptional value into the range of possible values of the return type.

**Comment by drwells** [comment]
Yes. I am perhaps guiltier than you suspect: I knew this was the better approach, but elected to return bogus values to get slightly more dramatic speed improvements (which appeals to my vanity). I will add some code to make it less confusing as penance.

**Comment by bangerth** [comment]
Is it really true that you'd get worse performance by using exceptions? People made that argument 15 or 20 years ago, but I don't think that has actually been true at any time since then.

**Comment by drwells** [comment]
Yes. Consider this benchmark (this is what I used to test the exact formula back in July when I wrote it):

```cpp
#include <deal.II/base/quadrature_lib.h>
#include <deal.II/base/geometry_info.h>
#include <deal.II/dofs/dof_handler.h>

#include <deal.II/fe/fe_q.h>
#include <deal.II/fe/fe_values.h>
#include <deal.II/fe/mapping_q1.h>

#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/manifold_lib.h>
#include <deal.II/grid/tria.h>
#include <deal.II/grid/tria_accessor.h>

#include <chrono>
#include <iostream>
#include <fstream>
constexpr int dim {2};
constexpr int spacedim {dim};

using namespace dealii;

int main()
{
  const SphericalManifold<dim> boundary;
  Triangulation<dim> triangulation;
  if (dim == 2)
    {
      GridGenerator::simplex(triangulation, {{0, 0}, {1, 0}, {0, 1}});
    }
  else
    {
      GridGenerator::simplex(triangulation, {{0, 0, 0}, {1, 0, 0}, {0, 1, 0}, {1, 1, 1}});
    }
  triangulation.refine_global(1);

  FE_Q<dim> fe(1);

  QGauss<dim> quad(3);
  FEValues<dim> fe_values(fe, quad, update_quadrature_points);
  DoFHandler<dim> dof_handler(triangulation);
  dof_handler.distribute_dofs(fe);

  MappingQ1<dim> map;
  const unsigned int max_refinement_levels = (dim == 3) ? 8 : (dim == 2) ? 11 : 22;

  for (unsigned int refinement_level = 5; refinement_level <= max_refinement_levels;
       ++refinement_level)
    {
      unsigned int unmatched_points {0};
      unsigned int matched_points {0};
      triangulation.refine_global(1);
      auto t0 = std::chrono::high_resolution_clock::now();
      for (const auto &cell : dof_handler.active_cell_iterators())
        {
          fe_values.reinit(cell);
          for (unsigned int q = 0; q < quad.size(); ++q)
            {
              auto unit_point {map.transform_real_to_unit_cell
                  (cell, fe_values.quadrature_point(q))};
              auto error {unit_point.distance(quad.point(q))/unit_point.norm()};

              (error > 5e-15) ? unmatched_points++ : matched_points++;
            }
        }
      auto t1 = std::chrono::high_resolution_clock::now();
      std::cout << "refinement level: " << refinement_level
                << " time elapsed: "
                << std::chrono::duration_cast<std::chrono::milliseconds>(t1 - t0).count()
                << std::endl;
      std::cout << "found "
                << 100*double(unmatched_points)/double(matched_points + unmatched_points)
                << "% points outside of the given tolerance." << std::endl;
    }
}
```

which has the following output on both `master` and a feature branch where I
handle exceptions:

```
[drwells@learch real-to-unit-speed]$ make release # on exceptions branch
(...)
[drwells@learch real-to-unit-speed]$ for i in $(seq 0 10); do make run | grep 'level: 11';done
refinement level: 11 time elapsed: 149
refinement level: 11 time elapsed: 148
refinement level: 11 time elapsed: 148
refinement level: 11 time elapsed: 150
refinement level: 11 time elapsed: 149
refinement level: 11 time elapsed: 148
refinement level: 11 time elapsed: 148
refinement level: 11 time elapsed: 149
refinement level: 11 time elapsed: 148
refinement level: 11 time elapsed: 149
refinement level: 11 time elapsed: 148
[drwells@learch real-to-unit-speed]$ make release # on master
(...)
[drwells@learch real-to-unit-speed]$ for i in $(seq 0 10); do make run | grep 'level: 11';done
refinement level: 11 time elapsed: 129
refinement level: 11 time elapsed: 130
refinement level: 11 time elapsed: 131
refinement level: 11 time elapsed: 130
refinement level: 11 time elapsed: 130
refinement level: 11 time elapsed: 132
refinement level: 11 time elapsed: 129
refinement level: 11 time elapsed: 129
refinement level: 11 time elapsed: 129
refinement level: 11 time elapsed: 130
refinement level: 11 time elapsed: 129
[drwells@learch real-to-unit-speed]$ g++ --version
g++ (GCC) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

This is on my laptop. The slowdown was closer to ten percent on my desktop,
which has the same version of `gcc`.

Observations:
1. The magic failure return values should be cleaned up.
2. The exact formula is still at least about twenty times that of the Newton
   code, so this speed penalty doesn't really matter, but it exists.
3. Perhaps `boost::optional` can solve both issues.

I will play with this a little more this week.

**Comment by tjhei** [comment]
I would prefer an internal function that returns a std::pair<Point,bool> or returns a bool and takes the point by reference and indicate success/fail that way.

**Comment by bangerth** [comment]
So the first set of numbers is with exceptions and the second set of numbers with returning a magical point? Interesting. In how many of the cases was the exception thrown? (It should have been zero, since you're mapping all points inside the cell, right?)

I think `boost::optional` would be another interesting alternative.

**Comment by drwells** [comment]
@bangerth It never throws the exception in this benchmark (I just checked). If I comment out the new occurances of `AssertThrow` then the performance is the same. This disagrees with all the posts I found on how GCC implements exceptions so I don't understand why the performance is so bad.

@tjhei Is this approach used anywhere else in the library? I considered using `boost::optional` or exceptions because they are both used elsewhere in the library.

In case anyone wants to look at this (I don't want to open a PR quite yet) I have the exceptions version on my `refactor-q1-mapping-with-exceptions` branch.

**Pull request merged**
