### PR TITLE
Added move constructor to SparseMatrix

### PR DESCRIPTION
**Pull request by danshapero**
I've added a move constructor for `SparseMatrix` so that these objects can be returned from functions, packed into tuples, etc. The test mirrors that of the `Vector` move constructor and passes with g++-4.8.4 and clang-3.7.

### CODE REVIEW

**Comment by drwells** [comment]
Nice work. We need more move constructors. Two comments:
1. Based on what was agreed upon in #1901 I think `NULL` is preferable to `0` for the coming day where we substitute in `nullptr`.
2. This one is more difficult: your move constructor copies the `Subscriptor` part of the object. Regardless of what `Subscriptor` does I think the right thing would be to move it too since moves should be cheap and copying a subscriptor involves copying `std::map` instances (which might be expensive). The other move constructors in the library don't carry over any Subscriptor information so this might not be necessary; is there a consensus on how to handle subscriptor information when things are moved? My primary concern here is that this class moves subscriptors in one way but the vector classes do something different.

**Comment by bangerth** [comment]
In reference to #898.

**Comment by bangerth** [comment]
I don't think you can move the Subscriptor. The Subscriptor records *which other objects point to the current one*. These other objects will not reference the *new, moved-to* object, however, so the right ting is to default-construct the Subscriptor base of the moved-to object.

An alternative approach that would make sense is in fact to assert that the object that is being moved to is not pointed to from anywhere at all. This assertion is useful because a moved-from object will not likely be in a state that anyone pointing to could still use. It is certainly true that if you use move constructors for temporary objects, that these temporary objects should not be pointed to, and consequently should not have any subscriptions.

**Comment by danshapero** [comment]
Thanks for looking! Copying the subscriptor was an oversight on my part, I'll make the appropriate changes.

**Comment by danshapero** [comment]
Ok, I've changed the constructor to default-initialize the `Subscriptor` . I also changed 0 to `nullptr` as @drwells suggests, since the relevant code is only being built on C++11 anyway.

I experimented with adding an `Assert` that the number of subscriptions is 0. However, this is not enforced in the corresponding move constructor/assignment operator for `Vector`, which uses `swap`, so I opted to leave off the assertion in the interest of consistency.

It might make sense to change the implementation for `Vector` to not use swap, and to throw `ExcInUse` if there are subscriptions to an object that is about to be moved. Some of this functionality could be put in a putative move constructor for `Subscriptor`, which of course doesn't actually do anything but throw an error in the bad case. Either way, that's a topic for a future PR.

**Comment by bangerth** [comment]
On 03/24/2016 03:09 PM, Daniel Shapero wrote:
> Ok, I've changed the constructor to default-initialize the |Subscriptor| . I
> also changed 0 to |nullptr| as @drwells <https://github.com/drwells> suggests,
> since the relevant code is only being built on C++11 anyway.

Good thinking.


> I experimented with adding an |Assert| that the number of subscriptions is 0.
> However, this is not enforced in the corresponding move constructor/assignment
> operator for |Vector|, which uses |swap|, so I opted to leave off the
> assertion in the interest of consistency.
>
> It might make sense to change the implementation for |Vector| to not use swap,
> and to throw |ExcInUse| if there are subscriptions to an object that is about
> to be moved. Some of this functionality could be put in a putative move
> constructor for |Subscriptor|, which of course doesn't actually do anything
> but throw an error in the bad case. Either way, that's a topic for a future PR.
Yes, fair enough. Since you already understand the issue and have looked into 
this, could we interest you in tackling this, maybe, possibly? ;-)

**Comment by danshapero** [comment]
Absolutely! There are a few more classes that I'd like to add move constructors to, especially non-copyable ones like `FEValues`, so having consistent behavior across all of them would be good.

**Comment by bangerth** [comment]
@danshapero -- great, thanks! Can you please add an entry to `doc/news/changes.h` (in the "specific changes" section) as a follow-up pull-request?

**Comment by danshapero** [comment]
Done, see #2427 .

**Pull request merged**
