### PR TITLE
Replace FE::interpolate() by FE::convert_support_point_values_to_nodal_values().

### LINKED ISSUE #3810: Document FiniteElement::interpolate
As a follow-up to #3807: `FETools::compute_node_matrix` calls `FiniteElement::interpolate()`, which is another woefully under-documented function for which I can't really figure out what it is supposed to do...

### PR DESCRIPTION
**Pull request by bangerth**
This fixes #3810. In essence, we concluded there that the old function is
poorly named, has essentially no documentation, and the arguments are
unclear. This PR implements the replacement function in the base class
and documents it to the best of my abilities.

The PR has 5 commits that are logically separate:
* Patch 1 deprecates the old function and all implementations in 
  derived classes.
* Patch 2 provides the new function and documentation.
* Patch 3 implements this function in all derived classes. This patch
  has a lot of code, but nothing of it is new: the implementation is
  copied entirely from the existing implementations of the deprecated
  function, with necessary adjustments of function arguments,
  argument names, etc. This was pretty mechanical -- it is probably
  not worth trying to go through the actual code as none of it
  is new.
* Patch 4 replaces the call to FE::interpolate() by calling
  the new function in FETools::compute_node_matrix(). To the best
  of my knowledge, this is the only place where these functions
  are actually called.
* Patch 5 renames a few variables in FETools::compute_node_matrix()
  so that the variables at the calling site are named like the
  arguments of the function being called.

I've tested the patch with the test suite and see no new failures.
I'm not adding any new tests since these functions are already
quite well tested: They are called via the constructor of their
respective classes every time an element is created. I made a
little mistake in one implementation of the function and got
several dozen test failures.

I did think about shrinking the size of patch 3 above by letting
the old (now deprecated) functions call the new one, or the
other way around. But this is difficult because (i) the argument
lists don't match, and in at least one case the new function
no longer has an argument that the old one has; in any case
it would require awkward conversion of input and output
arguments. (ii) I will remove the deprecated functions after
the next release, as discussed in #3810, and so the code
duplication is only temporary and seemed acceptable.

### CODE REVIEW

**Comment by luca-heltai** [comment]
Let me start a discussion here, since I bumped into some issues related to `FE::interpolate` with one of my students lately.

We assume that generalized support points should be considered as a way to "interpolate" a function, but this could be the right point to let this go. Let me make an example. I'll use a notation that helped me in the past... 

For an FE space V = span{v_i}, the *nodal functions* N^j (as defined in Chiarlet), are a basis for V^*  (the dual of V), and are the *functionals* that associate to any object in V the *degrees of freedom* used to represent them in terms of v_i. 

In other words, for any v in V    

v = sum_i N^i(v) v_i = sum_i v^i v_i

where v^i are the (covariant) indices associated to the basis v_i of V, and are obtained by the nodal functionals N^i applied to v, i.e., v^i = N^i(v). The usual notation applies, that N^j(v_i) = delta^j_i.

For Lagrangian basis functions, N^i(v) is taken to be the dirac delta centered in the ith support point -> one support point is enough to represent N^i(v) for each i.

For non interpolating basis functions, it is still possible to represent N^i(v) by cell integrals/line integrals/whatever functionals. In fact this is always true, because in general **any** N^i(v) in V^* can be represented by an object n^i in V, s.t. N^i(v) = (n^i, v) for any v in V. And we know how to compute (n^i, v) (by quadrature). I think that generalized support points should be allowed to be more numerous than the degrees of freedom, and in general they should not be bound to represent only "interpolation". 

I would rename the function to 

FiniteElement::convert_generalized_support_point_values_to_nodal_values

For example, this is exactly what is done in the FE_RaviartThomas::interpolate function. There the nodal values (for example for RT(0)) are the integrals of the functions on the faces, which can be computed by combining point values of the function v on the faces

N^i(v) := int_{e_i} v.nu ~ sum v(q_ik) nu_ik   (nu_ik is the normal to the face i in the point q_ik)

And this, of course, can be computed by replacing the integral with quadratures. It is by choice that the integrals are computed using **one** quadrature point for basis function, but of course this is not the only possibility.

Moreover, in this case it is clearly *false* that N^i(v) = v(q_i) (v(q_i) is a Tensor<1,dim>, while N^i(v) is a double), so calling this "interpolation" is flawed.

I think that the original idea of "generalized support points" was exactly to allow one to extract from  those points (thought of as "quadrature points" for some quadrature rules) the nodal values, intended as all the nodal functionals N^i computed on v. The assumption that generalized_support_points represent "interpolation" is a great limitation of our current implementation, and I think we should give freedom to FE implementers to decide for themselves if interpolation is what is needed or not... 

The function you suggest as a replacement makes perfect sense (modulo naming), and every FiniteElement can do whatever they like with generalized_support_point_values. For example, lagrangian elements would just plug the identity in here (with the same number of support points as basis functions), but one could implement a finite element with a number of generalized support points > number of basis functions, such that instead of interpolating, one makes an average around the support point, or, for example, computes the nodal values by computing the integral with the Rietz representative n^i in V of N^i in V^*, i.e., 

v^i = (n^i, v)  ~ sum_k n^i(q_k) v(q_k) w_k 

computing the above using a quadrature rule based on some generalized support_points (> number of points).

What the current FE::interpolate functions do is precisely this. However these functions forcibly impose that the number of generalized support points is equal to the number of basis functions. This allows one to solve by "collocation" the problem of computing nodal values, picking up the collocation points in a smart way so that the system is unisolvent, but this is not mandatory.

In general the whole concept of "generalized_support_point" is a bit shady in the library, since there is no true definition anywhere, except saying "that they generalize support point". Your new function is a step forward to making it much cleaner what these points are (they are just special points used to evaluate the nodal functionals) but restricting the definition to "interpolation" is, IMHO, wrong.

**Comment by bangerth** [comment]
Good points, @luca-heltai -- concise as always!

I agree that the concept of *generalized* support points was poorly thought out in the beginning and even worse defined in some understandable way. I wrote a patch a while back for the glossary (#3848) that at least provides some kind of definition, but your idea of having more generalized support points than nodal functionals is (i) new to me, (ii) brilliant. I like it a lot. I suspect a lot of assertions to trigger if we have such an element, though.

So do you agree with the following:
* Rename the function. (I had thought about the suggested name originally, but found it too long and so went with the shorter, if less concise, name. But I'm ok with renaming it.)
* Update the documentation of (i) the function in question here, (ii) the glossary entry to explain your ideas of using generalized support points as quadrature points of functionals.

If so, I would do the first of the two steps above right away. If you allow me to, I'd postpone the second step until after the release.

**Comment by luca-heltai** [comment]
I agree with all points. Just rename the function, and let's leave the discussion in the documentation and the possible implementation for later. 

By the way, right now FERaviartThomas of degree > 1 should already trigger an exception (RT(2) uses != number of gen supp points than dofs_per_cell) but the library seems ok with it... I guess few people try to interpolate those elements... i tried... :( 

Let's postpone a deeper discussion for after the release.

**Comment by bangerth** [comment]
OK, the version of my patch with the renamed function is now here. I will open a new issue about the generalization of generalized support points :-)

**Comment by bangerth** [comment]
@luca-heltai ?

**Pull request merged**
