### PR TITLE
FEValues: simplify CellIteratorBase

### PR DESCRIPTION
**Pull request by peterrum**
alternative to #12930

FYI @simonsticko @bangerth

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]
Looks good to me. Nice cleanup!

**Comment by peterrum** [comment]
I would appreciate if we could proceed on this PR soon, since there a room for more simplifications now, which will probably allow #12024 without too much headache.

**Review by drwells — APPROVED** [review]
I am surprised that we could simply this so much. Nice work!

**Comment by drwells** [comment]
In particular - it looks like we can rely on the instantiation of vector types inside `FEValues` to get the instantiations inside the custom cell iterator type.

**Pull request merged**
