### PR TITLE
Added instantiation for cases when dim < spacedim

### PR DESCRIPTION
**Pull request by malhartidke**
I came across the undefined function error while trying to implement periodic boundary conditions for the case of dim = 2 and spacedim = 3. Although periodic boundary conditions have been implemented for such cases, they were not instantiated. So, I added spacedim loop for the first two _for_ blocks. The conversation regarding this happened on mailing list [here](https://groups.google.com/g/dealii/c/sJ0o4Xf-NU0).

### CODE REVIEW

**Comment by peterrum** [comment]
@malhartidke Thanks for your contribution! Our indentation check is complaining:

```
invalid author 'malhartidke' without firstname and lastname

hint: for possible solutions, consult the webpage:
      https://github.com/dealii/dealii/wiki/Indentation#commit-authorship
Error: Process completed with exit code 2.
```

The link given by the error message might help you to fix the problem.

**Comment by malhartidke** [comment]
I tried to run the amend command, and pushed it to the branch of my forked project and now I am not sure why its showing 3 commits. I think I messed up. Is there a way to resolve this? I am sorry, this was my first ever pull request.

**Comment by peterrum** [comment]
I think the following lines should merge your 3 commits to one:
```
git rebase HEAD~3 -i --autosquash
git rebase --continue
```

But what you also need to do is to format the code. You can run in the source folder the script `./contrib/utilities/indent-all` (it might complain that you have not installed clang-format and will ask you if you want it to be installed).

**Comment by peterrum** [comment]
Close:
> But what you also need to do is to format the code. You can run in the source folder the script ./contrib/utilities/indent-all (it might complain that you have not installed clang-format and will ask you if you want it to be installed).

**Comment by masterleinad** [comment]
It would be good if you could also add a test for this. Just have a look at some of the tests using `DoFTools::make_periodicity_constraints` in tests/ and see if you can copy and modify one accordingly.

**Comment by malhartidke** [comment]
> It would be good if you could also add a test for this. Just have a look at some of the tests using `DoFTools::make_periodicity_constraints` in tests/ and see if you can copy and modify one accordingly.

Sure, I would love to do that, let me see, what I can come up with.

**Comment by bangerth** [comment]
I'll attach the WIP label for the moment, so let's not merge for now until there is a test.

@malhartidke -- many thanks for working on this, we really appreciate your contribution!

**Comment by malhartidke** [comment]
> @malhartidke -- many thanks for working on this, we really appreciate your contribution!

Wouldn't be possible without the help from all of you ! :)

So, I tried writing a test case by modifying  [tests/dofs/dof_tools_21_b.cc](https://github.com/dealii/dealii/blob/154a990d395a081d55ec041a2848920a368dda88/tests/dofs/dof_tools_21_b.cc#L1). I made a third grid for 2D in 3D case by adding spacedim in [2D case](https://github.com/dealii/dealii/blob/154a990d395a081d55ec041a2848920a368dda88/tests/dofs/dof_tools_21_b.cc#L58) and modified the [print_matching()](https://github.com/dealii/dealii/blob/154a990d395a081d55ec041a2848920a368dda88/tests/dofs/dof_tools_21_b.cc#L190) function accordingly. But, the test is failing at _diff_ stage as I am not sure which output to compare. If I am not wrong, theoretically, the output from 2D case and 2D in 3D case should match right?

**Comment by masterleinad** [comment]
If it's only the `diff` stage that is failing everything is likely OK. You just have to update the old `*.output` file with the new output file. Of course, you should also have a look if the new output looks sensible.

**Comment by malhartidke** [comment]
So, the windows-2016 check is failing and I am not sure, how to correct it, can anyone help?

**Comment by peterrum** [comment]
> So, the windows-2016 check is failing and I am not sure, how to correct it, can anyone help?

It has passed. Just the archiving has failed (GitHub sometimes has a hiccup^^).

**Comment by malhartidke** [comment]
> > So, the windows-2016 check is failing and I am not sure, how to correct it, can anyone help?
> 
> It has passed. Just the archiving has failed (GitHub sometimes has a hiccup^^).

Yeah, its showing passed now.

I have added tests for 2D in 3D case. Grid is exactly the same as in 2D, just embedded in 3D. I verified that the output from new case matches the output of 2D case in all tests.

**Review by masterleinad — APPROVED** [review]
Looks reasonable to me. Would you mind adding a changelog entry in `doc/news/changes/minor` and squashing your commits?

**Comment by malhartidke** [comment]
> Looks reasonable to me. Would you mind adding a changelog entry in `doc/news/changes/minor` and squashing your commits?

Yeah, sure, I will do it.

**Review by bangerth — COMMENTED** [review]
Looks good -- thanks a lot for working on this! Let us know when you have added the changelog entry!

**Comment by malhartidke** [comment]
I added a changelog entry and squashed the commits.

**Review by masterleinad — APPROVED** [review]
LGTM.

**Pull request merged**
