### PR TITLE
Revert deprecation of Vector::add(scalar).

### LINKED ISSUE #1848: Undo deprecation of Vector::add(scalar)
#1352 deprecates `Vector::add(scalar)` for all vector classes. I don't think I ever saw a purpose for this function, but https://github.com/geodynamics/aspect/issues/665 now points out that we use the function when subtracting the mean value from the pressure. I don't see a good other way to do this.

We should undo the deprecation. We should probably also add the function to the new vector classes @Rombur is writing.

### PR DESCRIPTION
**Pull request by drwells**
This should resolve #1848.

### CODE REVIEW

**Comment by drwells** [comment]
What would be the best way to update `changes.h`? Should I just change the August 13 entry where this was deprecated?

**Comment by tjhei** [comment]
> Should I just change the August 13 entry where this was deprecated?

Yes, sounds sensible (this was after 8.3.0 so we can change things around).

**Comment by tjhei** [comment]
oh, and :+1:  for the patch, looks good.

**Comment by bangerth** [comment]
Yes. Please merge after changing the changes.h entry.

**Pull request merged**
