### PR TITLE
Workaround: Add additional complex ProductTypeImpl specializations

### PR DESCRIPTION
**Pull request by tamiko**
The workaround introduced in 32ecab6 needs an additional variant to
deduce the product type of Tensor<..., complex<Number>> and
complex<Number> correctly.

Closes: #10246
See also: #10072

### CODE REVIEW

**Comment by tamiko** [comment]
This doesn't have the `#if` in place.

**Comment by drwells** [comment]
I think this is fine as long as we open a TODO or issue to remind us to go back and delete this when we upgrade our minimum compiler requirements.

**Comment by drwells** [comment]
Could we also convert the example code you had in the other issue into a test?

**Comment by tamiko** [comment]
@drwells Yes, I will add a test for unusual tensor products in a minute.

**Comment by tamiko** [comment]
@drwells Done. This is a bit more than just the example. I figured we could just add a `tensors/tensor_31` test, aka don't make Matthias unhappy ^^

**Pull request merged**
