### PR TITLE
Fix warning in step70

### PR DESCRIPTION
**Pull request by peterrum**

### CODE REVIEW

**Comment by kronbichler** [comment]
Does this compile for you? With gcc-7, I get
```
FAILED: examples/CMakeFiles/step-70.release.dir/step-70/step-70.cc.o 
/opt/rh/devtoolset-7/root/usr/bin/c++  -DBOOST_NO_AUTO_PTR -Iinclude -I/home/kronbichler/deal/deal.II/include -I/home/kronbichler/deal/deal.II/bundled/tbb-2018_U2/include -I/home/kronbichler/deal/deal.II/bundled/boost-1.70.0/include -I/home/kronbichler/deal/deal.II/bundled/umfpack/UMFPACK/Include -I/home/kronbichler/deal/deal.II/bundled/umfpack/AMD/Include -I/home/kronbichler/deal/deal.II/bundled/muparser_v2_2_4/include -isystem /usr/include/openmpi-x86_64 -isystem /home/kronbichler/sw/include -isystem /home/kronbichler/sw/trilinos-12-10/include -isystem /home/kronbichler/sw/petsc-3.8.2/include -isystem /home/kronbichler/sw/petsc-3.8.2/arch-linux2-c-opt/include -isystem /home/kronbichler/sw/opencascade/include/oce -isystem /home/kronbichler/sw/FAST/include -isystem /home/kronbichler/sw/sundials/include -pedantic -fPIC -Wall -Wextra -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wsuggest-override -Wswitch -Wsynth -Wwrite-strings -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -fopenmp-simd -std=c++17 -march=native -pthread -Wno-parentheses -Wno-unused-local-typedefs -O2 -funroll-loops -funroll-all-loops -fstrict-aliasing -O3 -MD -MT examples/CMakeFiles/step-70.release.dir/step-70/step-70.cc.o -MF examples/CMakeFiles/step-70.release.dir/step-70/step-70.cc.o.d -o examples/CMakeFiles/step-70.release.dir/step-70/step-70.cc.o -c /home/kronbichler/deal/deal.II/examples/step-70/step-70.cc
/home/kronbichler/deal/deal.II/examples/step-70/step-70.cc: In member function ‘void Step70::StokesImmersedProblem<dim, spacedim>::solve()’:
/home/kronbichler/deal/deal.II/examples/step-70/step-70.cc:1402:70: error: call of overloaded ‘block_diagonal_operator<2, dealii::LinearAlgebraTrilinos::MPI::BlockVector>(<brace-enclosed initializer list>)’ is ambiguous
       block_diagonal_operator<2, LA::MPI::BlockVector>({{amgA, amgS}});
                                                                      ^
In file included from /home/kronbichler/deal/deal.II/examples/step-70/step-70.cc:28:0:
/home/kronbichler/deal/deal.II/include/deal.II/lac/block_linear_operator.h:798:1: note: candidate: dealii::BlockLinearOperator<Range, Domain, BlockPayload> dealii::block_diagonal_operator(const std::array<dealii::LinearOperator<typename Range::BlockType, typename Domain::BlockType, typename BlockPayload::BlockType>, m>&) [with long unsigned int m = 2; Range = dealii::TrilinosWrappers::MPI::BlockVector; Domain = dealii::TrilinosWrappers::MPI::BlockVector; BlockPayload = dealii::internal::BlockLinearOperatorImplementation::EmptyBlockPayload<>; typename BlockPayload::BlockType = dealii::internal::LinearOperatorImplementation::EmptyPayload; typename Domain::BlockType = dealii::TrilinosWrappers::MPI::Vector; typename Range::BlockType = dealii::TrilinosWrappers::MPI::Vector]
 block_diagonal_operator(
 ^~~~~~~~~~~~~~~~~~~~~~~
/home/kronbichler/deal/deal.II/include/deal.II/lac/block_linear_operator.h:847:1: note: candidate: dealii::BlockLinearOperator<Range, Domain, BlockPayload> dealii::block_diagonal_operator(const dealii::LinearOperator<typename Range::BlockType, typename Domain::BlockType, typename BlockPayload::BlockType>&) [with long unsigned int m = 2; Range = dealii::TrilinosWrappers::MPI::BlockVector; Domain = dealii::TrilinosWrappers::MPI::BlockVector; BlockPayload = dealii::internal::BlockLinearOperatorImplementation::EmptyBlockPayload<>; typename BlockPayload::BlockType = dealii::internal::LinearOperatorImplementation::EmptyPayload; typename Domain::BlockType = dealii::TrilinosWrappers::MPI::Vector; typename Range::BlockType = dealii::TrilinosWrappers::MPI::Vector]
 block_diagonal_operator(
 ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by peterrum** [comment]
@kronbichler I was too quick in opening the PR (the code was still compiling). Simply adding `{{}}` as suggested was not enough since the overloaded call was ambiguous. I am afraid, we have to be explicit here or do you see another solution?

**Comment by luca-heltai** [comment]
I'm afraid  this is the only way to make every compiler happy...

**Comment by tjhei** [comment]
Looks good, but I suspect this might break with different configurations...

**Pull request merged**
