### PR TITLE
Error out with too large Trilinos sparsity patterns.

### LINKED ISSUE #13428: Failure when building Trilinos matrices with more than 2B entries
@marcfehling ran into a problem where he has a matrix with 15,110,817 rows and columns, and 2,280,732,000 entries (just barely more than the 2,147,483,647 that form the upper end of what a signed int can represent). This then leads to a segfault as follows:
```
Caught signal 11 (Segmentation fault: address not mapped to object at address 0x1554af260000)
 4  /expanse/lustre/projects/ucd150/mfehling/bin/aocc/trilinos-13.0.1/lib/libepetra.so.13(Epetra_CrsGraph::OptimizeStorage()+0x4e7) [0x155543905307]
 5  /home/mfehling/project/bin/aocc/dealii-10.0.0-pre/lib/libdeal_II.so.10.0.0-pre(dealii::TrilinosWrappers::SparsityPattern::compress()+0x110) [0x155550e8ec30]
 6  /home/mfehling/project/bin/aocc/dealii-10.0.0-pre/lib/libdeal_II.so.10.0.0-pre(dealii::BlockSparsityPatternBase<dealii::TrilinosWrappers::SparsityPattern>::compress()+0x6d) [0x155550cfb05d]
 7  /expanse/lustre/projects/ucd150/mfehling/build-parallel-matrixfree-hp/stokes(Problem::Stokes<3, Trilinos, 3>::setup_system()+0xe98) [0x43a9f8]
 8  /expanse/lustre/projects/ucd150/mfehling/build-parallel-matrixfree-hp/stokes(Problem::Stokes<3, Trilinos, 3>::run()+0x45f) [0x4390cf]
 9  /expanse/lustre/projects/ucd150/mfehling/build-parallel-matrixfree-hp/stokes(main+0x2a1) [0x33cbd1]
10  /lib64/libc.so.6(__libc_start_main+0xf3) [0x15553f7f5873]
11  /expanse/lustre/projects/ucd150/mfehling/build-parallel-matrixfree-hp/stokes(_start+0x2e) [0x33c86e]
```
He reports that this happens both with compiling in 32- and 64-bit mode.

We should take a look at whether we call one of Trilinos's 32-bit functions by accident where there is a 64-bit function we should be calling instead.

### PR DESCRIPTION
**Pull request by bangerth**
Fixes #13428.

/rebuild

### CODE REVIEW

**Comment by marcfehling** [comment]
Let me try whether these errors get triggered in my scenario later.

**Review by masterleinad — APPROVED** [review]
Looks good to me.

**Comment by bangerth** [comment]
@marcfehling  I got the error with the testcase mentioned above at least. It would be interesting to see whether that's also the case for you.

**Comment by marcfehling** [comment]
Do you think it would be useful to turn your `Assert`s to `AssertThrow`s? Usually, you don't run code with more than 2B nonzeros in debug mode. Hmm, I'm not sure whether this would affect performance significantly as it's only in the reinit part.

I still get a segmentation fault on 1 process, and the `Unknown exception!` on 2 processes after compiling your branch. I will try to get a backtrace for these cases in gdb.

And I already triple checked that your patch is part of the code :-/

**Comment by marcfehling** [comment]
Wait a minute... I am using `TrilinosWrappers::BlockSparsityPattern`, whereas your snippet uses `TrilinosWrappers::SparsityPattern`. Could you also add the assertions to `source/lac/block_sparsity_pattern.cc`?

**Comment by bangerth** [comment]
The block matrix variants only wrap around individual blocks that are individually managed by Trilinos. Trilinos in fact doesn't even know that a matrix is a part of a bigger system. As a consequence, there is nothing wrong with having more than 2B entries in a block system; what matters is what's in each block.

**Comment by marcfehling** [comment]
> As a consequence, there is nothing wrong with having more than 2B entries in a block system; what matters is what's in each block.

Yes, I understood the design of the class now. Hmm, could there be a different quantity that we need to check?

In my code and in `step-32`, we call `DoFTools::make_sparsity_pattern` followed by `SparsityPattern::compress`. In this combination, it appears to me that `SparsityPattern::reinit` will never be called. We should place the same kind of assertion somewhere else as well.

https://github.com/dealii/dealii/blob/951db6b4eda1781f9ae1b983df2ffe9162bea546/examples/step-32/step-32.cc#L1697-L1704

---

By the way, these lines trigger the error reported in https://github.com/dealii/dealii/issues/13428#issue-1145289054
https://github.com/dealii/dealii/blob/951db6b4eda1781f9ae1b983df2ffe9162bea546/source/lac/trilinos_sparsity_pattern.cc#L696-L697

**Comment by kronbichler** [comment]
> Do you think it would be useful to turn your Asserts to AssertThrows? Usually, you don't run code with more than 2B nonzeros in debug mode. Hmm, I'm not sure whether this would affect performance significantly as it's only in the reinit part.

I would be in favor of that, too. Not only because one rarely runs in debug mode for bigger sizes, but also because I can imagine writing a solver that terminates more gracefully in case some limit is reached (enabled by catching the exception in user code) than simply failing. I think we have several error messages of these kind (where we check some overflow), so I think we should aim to be consistent in how we do things.

(And to the cost: that is totally negligible in the grand scheme of things, as are most checks for exceeding a number threshold.)

**Comment by bangerth** [comment]
Good point, I changed things to `AssertThrow` instead.

**Comment by bangerth** [comment]
As for where step-32 comes out: It took me a while to get there, but we call this function that is agnostic how many entries per row there will be:
```
  void
  SparsityPattern::reinit(const IndexSet &row_parallel_partitioning,
                          const IndexSet &col_parallel_partitioning,
                          const IndexSet &writable_rows,
                          const MPI_Comm &communicator,
                          const size_type n_entries_per_row)
  {
    Epetra_Map row_map =
      row_parallel_partitioning.make_trilinos_map(communicator, false);
    Epetra_Map col_map =
      col_parallel_partitioning.make_trilinos_map(communicator, false);
    reinit_sp(row_map,
              col_map,
              n_entries_per_row,
              column_space_map,
              graph,
              nonlocal_graph);
  ...
```
The last argument is set to its default, zero. The corresponding `reinit_sp()` function that is called here is the following:
```
    void
    reinit_sp(const Epetra_Map &                  row_map,
              const Epetra_Map &                  col_map,
              const size_type                     n_entries_per_row,
              std::unique_ptr<Epetra_Map> &       column_space_map,
              std::unique_ptr<Epetra_FECrsGraph> &graph,
              std::unique_ptr<Epetra_CrsGraph> &  nonlocal_graph)
    {
      Assert(row_map.IsOneToOne(),
             ExcMessage("Row map must be 1-to-1, i.e., no overlap between "
                        "the maps of different processors."));
      Assert(col_map.IsOneToOne(),
             ExcMessage("Column map must be 1-to-1, i.e., no overlap between "
                        "the maps of different processors."));

      nonlocal_graph.reset();
      graph.reset();
      column_space_map = std::make_unique<Epetra_Map>(col_map);

      AssertThrow((TrilinosWrappers::max_my_gid(row_map) -
                   TrilinosWrappers::min_my_gid(row_map)) *
                      std::uint64_t(n_entries_per_row) <
                    std::numeric_limits<int>::max(),
                  ExcMessage("The TrilinosWrappers use Epetra internally which "
                             "uses 'signed int' to represent local indices. "
                             "Therefore, only 2,147,483,647 nonzero matrix "
                             "entries can be stored on a single process, "
                             "but you are requesting more than that. "
                             "If possible, use more MPI processes."));
  ...
```
The assertion will here not trigger because we have `n_entries_per_row==0`. I think I might have to dig a bit deeper to figure out how we can avoid the issue in this case. 

I would like to do that in a follow-up, if you allow me.

**Review by marcfehling — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]

**Pull request merged**
