### PR TITLE
testing of step-80 to step-89

### PR DESCRIPTION
**Pull request by vyushut**
Proceeding after https://github.com/dealii/dealii/pull/17100, https://github.com/dealii/dealii/pull/17084, https://github.com/dealii/dealii/pull/17130, https://github.com/dealii/dealii/pull/17165, https://github.com/dealii/dealii/pull/17209, https://github.com/dealii/dealii/pull/17232, #17245

### CODE REVIEW

**Review by Rombur — APPROVED** [review]

**Review by tjhei — APPROVED** [review]

**Comment by tjhei** [comment]
@vyushut  do you know what is going on in step-89?

**Comment by peterrum** [comment]
> * Should I request it as in step-89.with_cgal=true.output?
> * Should CGAL be in the CMakeLists.txt? It is not mentioned now:
>   `examples/step-89/CMakeLists.txt:if(NOT DEAL_II_WITH_MPI) # keep in one line`

Yes, it should.

**Comment by tjhei** [comment]
Can you make a separate PR to fix that?

**Comment by tjhei** [comment]
Actually, I think we just need two output files, one with and one without CGAL.

**Review by kronbichler — APPROVED** [review]

**Pull request merged**
