### PR TITLE
Inline functions because of bugs in hipcc

### PR DESCRIPTION
**Pull request by Rombur**
With this PR, #8621, and renaming `lac/exceptions` to `lac/petsc_exceptions`, I can compile deal.II with hipcc. There is still quite a bit of work before we can run on AMD hardware but at least, it compiles.

### CODE REVIEW

**Comment by Rombur** [comment]
It just needs to be inlined

**Comment by masterleinad** [comment]
Would you mind providing a comment then such that we don't forget why this is defined in class?

**Comment by Rombur** [comment]
I've moved the implementation outside the class

**Pull request merged**
