### PR TITLE
Testsuite: retry a test when encountering a segfault

### PR DESCRIPTION
**Pull request by tamiko**
Let's see whether this makes the regression tester less noisy...

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]

**Comment by tamiko** [comment]
I want to rebase this change onto #17275 first.

**Review by masterleinad — APPROVED** [review]

**Comment by tjhei** [comment]
I don't quite understand. Why is it ever ok that we sometimes segfault?

**Comment by tamiko** [comment]
@tjhei This pull request implements exactly what **you** suggested to do a while ago: In order to deal with the very rare and random segfaults on the regression testsuite simply retry such a test. (The frequency of such a failure seems to be less than one in 100000. Furthermore, there isn't really a good action item for us. It's likely a flakey userland or external dependency).

We can also add a configuration option explicitly enabling this retry logic if this is deemed too evil for general use.

I am also open for suggestions how to avoid false positives in the regression testsuite in a different way - short of disabling reporting altogether.

**Comment by bangerth** [comment]
I'm not opposed to the patch, but have a hard time seeing how a test that fails the first time with a segfault should magically work the second time we execute the exact same command. Are you thinking of cases where a test segfaults because there is not enough memory? 

In actual debugging practice, whenever you run your own codes and the program segfaults, you would typically assume that the program is buggy. At least in my own practice, I don't assume that this might be spurious and just try again.

**Comment by tjhei** [comment]
Do you have examples of recent failures?

**Comment by tjhei** [comment]
> This pull request implements exactly what **you** suggested to do a while ago

I apologize, but I have no recollection of that.

**Comment by tamiko** [comment]
Let's table this discussion.

**Pull request closed without merging**
