### PR TITLE
Add process_dofs_vectorized_transpose() variants with constant_offset

### PR DESCRIPTION
**Pull request by peterrum**

### CODE REVIEW

**Comment by peterrum** [comment]
> Do we actually need a new function, or can we merely add the parameter to the other function with a default value of offset = 0? I think the compiler would optimize this away if it inlines the function call, and otherwise it is just a simple integer addition that should be cheap.

@kronbichler Personally, I would prefer to have a new function so that the order of arguments is consistent with that of `process_dof_gather()`. I have modified the code now so that the new functions are called by the old ones. What do you think?

**Comment by kronbichler** [comment]
These are internal interfaces, so we can change the order if we deem it necessary. I am not a big fan of calling the other function because it increases the code size that we need to maintain, but I see your point and would support this in case we have made sure that our typical compilers do not make widely different choices in terms of inlining. One way to ensure this is to check the number of instructions issued in step-59 or step-67, where these functions should be used. We could also consider the new Navier-Stokes benchmark case, but we would need to check how important the function is.

**Review by kronbichler — APPROVED** [review]
I think this looks reasonable from the code perspective. It is good to go from my end.

**Comment by peterrum** [comment]
@kronbichler I have rebased this branch. Is anything missing?

**Review by kronbichler — APPROVED** [review]

**Pull request merged**
