### PR TITLE
Fix mpi/distribute_flux_sparsity_pattern

### LINKED ISSUE #3958: mpi/distribute_flux_sparsity_pattern.mpirun=2.release fails
looks serious:
```
$ ctest -V -R "mpi/distribute_flux_sparsity_pattern.mpirun=2.release"
UpdateCTestConfiguration  from :/home/davydden/libs/dealii-tests/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/davydden/libs/dealii-tests/DartConfiguration.tcl
Test project /home/davydden/libs/dealii-tests
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 6024
    Start 6024: mpi/distribute_flux_sparsity_pattern.mpirun=2.release

6024: Test command: /home/davydden/spack/opt/spack/linux-ubuntu16-x86_64/gcc-6.3.0/cmake-3.7.2-qfd24w4jz4yvsvcy5foddwgiwyykqkuq/bin/cmake "-DTRGT=distribute_flux_sparsity_pattern.mpirun2.release.diff" "-DTEST=mpi/distribute_flux_sparsity_pattern.mpirun=2.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/davydden/libs/dealii-tests/mpi" "-DGUARD_FILE=/home/davydden/libs/dealii-tests/mpi/distribute_flux_sparsity_pattern.release/interrupt_guard.cc" "-P" "/home/davydden/spack/opt/spack/linux-ubuntu16-x86_64/gcc-6.3.0/dealii-develop-wrha3kpxcvgg2wd54rjm5dxl6ksdihf3/share/deal.II/scripts/run_test.cmake"
6024: Test timeout computed to be: 600
6024: make[3]: *** [distribute_flux_sparsity_pattern.release/mpirun=2/output] Error 1
6024: make[2]: *** [CMakeFiles/distribute_flux_sparsity_pattern.mpirun2.release.diff.dir/all] Error 2
6024: make[1]: *** [CMakeFiles/distribute_flux_sparsity_pattern.mpirun2.release.diff.dir/rule] Error 2
6024: make: *** [distribute_flux_sparsity_pattern.mpirun2.release.diff] Error 2
6024: Test mpi/distribute_flux_sparsity_pattern.mpirun=2.release: RUN
6024: ===============================   OUTPUT BEGIN  ===============================
6024: Built target distribute_flux_sparsity_pattern.release
6024: Generating distribute_flux_sparsity_pattern.release/mpirun=2/output
6024: mpi/distribute_flux_sparsity_pattern.mpirun=2.release: BUILD successful.
6024: mpi/distribute_flux_sparsity_pattern.mpirun=2.release: RUN failed. ------ Return code 59
6024: mpi/distribute_flux_sparsity_pattern.mpirun=2.release: RUN failed. ------ Result: /home/davydden/libs/dealii-tests/mpi/distribute_flux_sparsity_pattern.release/mpirun=2/failing_output
6024: mpi/distribute_flux_sparsity_pattern.mpirun=2.release: RUN failed. ------ Partial output:
6024: 
6024: mpi/distribute_flux_sparsity_pattern.mpirun=2.release: RUN failed. ------ Additional output on stdout/stderr:
6024: 
6024: [0]PETSC ERROR: [1]PETSC ERROR: ------------------------------------------------------------------------
6024: [0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
```

debug versions passes. 

This happens with `gcc@6.3.0` and `openmpi@2.0.2`. For the record, **all other 8678 tests but two opencascade related https://github.com/dealii/dealii/issues/3915 pass!**

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #3958.

### CODE REVIEW

**Comment by bangerth** [comment]
Obviously ok to merge. What a bizarre problem!

**Comment by tjhei** [comment]
> What a bizarre problem!

I assume that it is undefined behavior. The newest gcc generates a warning but clang seems to be happy: https://godbolt.org/g/sMV4YK

The funny part for me is that I pointed out the exact line and even then all of you did not see the issue. ;-)

**Comment by masterleinad** [comment]
> I assume that it is undefined behavior. The newest gcc generates a warning but clang seems to be happy: https://godbolt.org/g/sMV4YK

Still I am quite puzzled that it worked in debug mode. At least in your minimal code, optimization flags don't make any difference...

**Comment by drwells** [comment]
Nice catch. I am not sure how I managed to originally write this and not get any GCC complaints. Thank you for fixing my mistake.

**Comment by bangerth** [comment]
On 02/10/2017 02:24 PM, Timo Heister wrote:
> The funny part for me is that I pointed out the exact line and even then
> all of you did not see the issue. ;-)

I did at least realize that I didn't understand what you were saying -- 
so for me, it was a known unknown whereas for everyone else it was 
apparently an unknown unknown ;-)

**Pull request merged**
