### PR TITLE
Move all DataOut tests into numerics.

### PR DESCRIPTION
**Pull request by drwells**
A continuation of my work (#2841, #2771, #2766) to get rid of `tests/bits`.

### CODE REVIEW

**Comment by bangerth** [comment]
In reference to #1581.

**Comment by bangerth** [comment]
I'm going to note that if we wanted to truly address #1581, it's not enough to just move files around into existing directories, but we need to *create more directories* to create more potential for parallelism.

**Comment by drwells** [comment]
@bangerth I agree. I am using a soft limit of about 200 tests per directory (`tests/fe/` has 326 and `tests/lac/` has 266) during this rearrangement process.

My main goal is to get rid of `tests/bits/` (which now has 593 tests; it had 759 when I started) which I think should mostly fix the problem,

**Comment by bangerth** [comment]
Ultimately, I think it really doesn't matter very much which directory a test is in. But we don't want to have directories with too many tests since that limits the parallel scalability of `make setup_tests`. If you want to segregate tests into more (new) directories, you have my blessing :-)

**Pull request merged**
