### PR TITLE
Add missing include

### PR DESCRIPTION
**Pull request by peterrum**

### CODE REVIEW

**Comment by masterleinad** [comment]
Why do you need to include `manifold.h` in `mg_constrained_dofs.h` explicitly?

**Comment by peterrum** [comment]
Because of this line:

https://github.com/dealii/dealii/blob/9335876a279eb16851afa4561e305770f24bc812/include/deal.II/multigrid/mg_constrained_dofs.h#L430-L431

**Comment by kronbichler** [comment]
I think including it via `tria.h` or `tria_accessor.h` that also uses the manifold would make more sense in terms of comprehensive interfaces. Alternatively, I think that moving the code to a (new) `mg_constrained_dofs.cc` file that includes the manifold header would also be an option, whereas the mere addition in a header seems less attractive.

**Comment by peterrum** [comment]
> Alternatively, I think that moving the code to a (new) mg_constrained_dofs.cc file that includes the manifold header would also be an option, whereas the mere addition in a header seems less attractive.

I went with this, since I planed this step anyway.

**Review by masterleinad — APPROVED** [review]

**Review by kronbichler — COMMENTED** [review]
Would you mind keeping the small getter functions that retrieve simple information (like `get_boundary_indices()`, `have_boundary_indices()`, `is_boundary_index()`, `has_boundary_index`, `at_refinement_edge()` etc) in the header file, for uniform style with other files where we keep the small functions in the header and only move the bigger code parts to the library? I think that should still not require the inclusion of `dof_tools.h`.

**Comment by bangerth** [comment]
There's at least one test that fails:
```
/jenkins/workspace/dealii-serial_PR-16216/tests/integrators/assembler_simple_matrix_03.cc: In function ‘void test(dealii::FiniteElement<dim, dim>&)’:
/jenkins/workspace/dealii-serial_PR-16216/tests/integrators/assembler_simple_matrix_03.cc:86:3: error: ‘DoFTools’ has not been declared
   86 |   DoFTools::make_flux_sparsity_pattern(dof, csp);
      |   ^~~~~~~~
make[3]: *** [CMakeFiles/integrators.assembler_simple_matrix_03.debug.dir/build.make:76: CMakeFiles/integrators.assembler_simple_matrix_03.debug.dir/assembler_simple_matrix_03.cc.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:452: CMakeFiles/integrators.assembler_simple_matrix_03.debug.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:407: CMakeFiles/integrators.assembler_simple_matrix_03.debug.test.dir/rule] Error 2
make: *** [Makefile:264: integrators.assembler_simple_matrix_03.debug.test] Error 2
```

**Review by kronbichler — APPROVED** [review]
OK, apart from the CI error.

**Comment by peterrum** [comment]
> OK, apart from the CI error.

@kronbichler I have fixed the failing tests.

**Comment by marcfehling** [comment]
/rebuild

OSX tester hangs so let's try again

**Pull request merged**
