### PR TITLE
Fix a number of tests.

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Comment by tamiko** [comment]
Please reindent and merge :-D

**Comment by bangerth** [comment]
Oh, you merged a PR that fails the indentation check :-(

**Comment by tamiko** [comment]
I brutally reindented before I merged :-]

**Comment by bangerth** [comment]
How did you do this? Did you just take my commits, reindent, and push by hand?

**Comment by tamiko** [comment]
Jup:

```
git fetch origin pull/2755/head:pr_2755
git checkout pr_2755
[...]
git commit [...]
git checkout master
git merge --no-ff pr_2755
git push
```

**Comment by bangerth** [comment]
Uh oh, I thought that we had forbidden direct pushed into the master repo? If we didn't, I would think that a good idea...

**Comment by bangerth** [comment]
OK. No harm done, but I think in general I would prefer we don't do these sorts of things. I very much like the fact that I get to see all changes that are made to the repository, and I suspect that the same may be true for others as well. It really also minimizes the risk of someone accidentally doing something silly to the repository.

**Pull request merged**
