### PR TITLE
Reduce number of failing tests with FMA

### PR DESCRIPTION
**Pull request by kronbichler**
When compiling deal.II with clang (3.5 or 3.7-pre-release) using `-ffp-contract=fast` to use fused-multiply-add (FMA) instructions in newer Intel processors (Haswell, Broadwell), several tests fail because the floating point arithmetics are slightly changed. Often, the accuracy is slightly better because only one rounding instead of two are done. In any case, this affects the results in several tests (see also http://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=10273 ). Therefore, I added more precision to the output of many tests, removed some unnecessary data (convergence rates in step-10 test cases fail around 1e-13 but are not necessary because we are interested in the errors) and let numdiff decide about the accuracy.

Furthermore, I found a small bug in fe_q_base.cc for the interface constraints when tracking down floating point differences. When reviewing the patch, consider the three patches separately. The third on is the one that adds more precision to many lines of code.

### CODE REVIEW

**Comment by tamiko** [comment]
Holy cow, this is a monster of 200k changed lines.

Have you used the <code>check_solver_within_range</code> macro anywhere? Or were this only places were the number of steps to convergence is irrelevant?

If nobody objects in the next hours I merge.

**Comment by kronbichler** [comment]
@tamiko These are only tests where we output floating point numbers. (I didn't touch the other files.) In the tests I touched, I tried to consistently put 8 digits of accuracy, in order for numdiff with relative tolerance 1e-6 to make the checks correctly.

**Comment by bangerth** [comment]
This looks good to me too. Since @tamiko had a question, I'll leave it to the two of you to actually do the merge.

**Comment by bangerth** [comment]
It is interesting, by the way, that this is the second time yesterday that I got to hear about the effects of FMA on the accuracy of output -- I've heard the same from someone working on SPEC CPU benchmarks with a similar problem.

**Comment by tjhei** [comment]
I checked every single line change (just kidding). Looks good to me. :+1:

**Comment by kronbichler** [comment]
That's why compiler writers have been discussing the rules for the FMA behavior and give programmers several options regarding the FMA usage. clang is more conservative than GCC (I think the general rule is to only enable FMA when the result is provably unaffected, which means relatively few occasions), so I manually force it to use it...

But there are some interesting floating point implications. For example, `a*a - a*a` can be different from zero if the second multiplication is done in combination with the subtraction. Something like this happened in the test bits/fe_field_function_04 (the first product is not seen by the compiler, otherwise it wouldn't apply FMA here I guess).

**Pull request merged**
