### PR TITLE
Add vtk output of curved mesh

### LINKED ISSUE #6999: Address comments in #6994
It would be good for us to attend to the few remaining comments listed in #6994.

### PR DESCRIPTION
**Pull request by kronbichler**
Fixes #6999.

This is the promised high order output. @agrayver how did you create the smooth visualization in Paraview in #6994? I used tesselate but then I cannot output the mesh any more...

### CODE REVIEW

**Comment by agrayver** [comment]
@kronbichler you need to look for 'Nonlinear Subdivision level' property and set to a value > 1.

**Comment by bangerth** [comment]
So are you saying that by default, Paraview still only outputs (bi)linear cells even if they had been written as higher order cells into the .vtk file? If so, we should also document this somehow.

**Comment by jppelteret** [comment]
I've been playing around with this since yesterday, and if I understand correctly Paraview does by default display "higher-order" cells, but their geometry appears linear between the nodes of each cell (like they're a set of triangle patches making up one cell). Here's a picture of the starting mesh from one of the tests:

screen shot 2018-08-02 at 15 24 01

But if one tesselates the solution and sets the number of subdivisions at or higher than the cell polynomial order then one resolves the "smooth" manifolds, for example.

screen shot 2018-08-02 at 15 24 16

I hope that there's actually a better way to do this, because I must admit that I was hoping that Paraview would give the smooth element view by default.

**Comment by kronbichler** [comment]
@jppelteret Instead of using the tesselate filter, you can select "Nonlinear Subdivision Level" in the Properties tab of the solution itself, say here (look at where my mouse pointer is located):
screenshot at 2018-08-02 16-44-09

@bangerth Well it plots some sort of bilinear representation of the points itself, so it looks like a subdivided mesh with `n_patches=degree`. But you can turn up that parameter to get a very smooth representation as in my case (and as @agrayver has done in the other PR).

**Comment by jppelteret** [comment]
> you can select "Nonlinear Subdivision Level" in the Properties tab of the solution itself

Thanks @kronbichler. So this seems to be hidden by default in Paraview. I searched up and down the properties tab for the option, but didn't think about using the search bar to look for it. That's a bit unintuitive :-/ but at least I am now enlightened.

**Comment by agrayver** [comment]
While this options might have been more exposed, it actually make sense how it is done: by default, ParaView does not spend any resources on actual non-linear interpolation, because it does not know how accurate you want to have it. It just loads the data and renders bi-/trilinear image and then you can increase accuracy (through "Nonlinear Subdivision Level" property) depending on your needs and available memory.

**Comment by jppelteret** [comment]
> While this option might have been more exposed, it actually make sense how it is done

I agree - they have the interests of people visualising huge datasets in mind. 

To me, what they've done interface wise is not a terribly "friendly" way to expose this functionality to users. (I will openly admit that I have not RTM though, but I've been using Paraview for long enough that I thought I knew my way around it sufficiently well.) I followed the suggestion you made earlier in the thread, namely to

> look for the 'Nonlinear Subdivision level' property

and I didn't see such an option. I then downloaded the latest version of Paraview and still did not see such an option. It totally didn't occur to me that the search bar might yield different results to the options exposed with the `+/-` buttons in the properties bar.

Anyway, its hardly important to discuss the merits of what one must do to get this representation. What is important is that everyone who wants to use this functionality can do so with as little hassle as possible. So I've opened another issue suggesting that we describe the steps needed to do so in more detail somewhere.

**Pull request merged**
