### PR TITLE
Fix compiling with clang-3.7.1

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes the errors in https://cdash.43-1.org/viewBuildError.php?buildid=2832.

### CODE REVIEW

**Comment by bangerth** [comment]
I think we had previously concluded that the requirement of the braces is a misunderstanding of the intent of the C++ standard. (We concluded that when we talked about the requirement of having a default constructor for the same classes for which you now have the default initializers.)

clang 3.7 is pretty old. Do you still get the warnings/error for newer versions? Is there a flag (e.g., `-fpermissive`) that one could use for this old compiler?

**Comment by masterleinad** [comment]
You are likely referring to #8767. No, `fpermissive` doesn't help and I am not aware of another workaround. I don't know the minimum version that doesn't result in these errors.

We were dealing similarly with older `clang` compilers in (https://github.com/dealii/dealii/pull/7669 and https://github.com/dealii/dealii/pull/8018). https://github.com/dealii/dealii/issues/8814 is also related, but there we only had warnings we could suppress.

We still claim to support clang 3.3 (https://www.dealii.org/developer/readme.html) so we should either fix these errors or update the requirements. I would be fine with both. @tamiko brought this to our attention so he might have a case where he needs this old version.

**Comment by tamiko** [comment]
@masterleinad Thanks for looking into this :-D

*mhm* I don't need clang-3.7.1 supports - it just happens to be the oldest version floating around on `simserv04`. So what shall we do? I can try to disable compiling example steps for the clang 3.7.1 configuration in case we do not want to touch the example steps.

But I sense the time has come to update our oldest supported compiler versions again.

Opinions?

**Comment by tjhei** [comment]
> Opinions?

I wouldn't mind bumping to clang 3.8 (this is what ubuntu 16.04 ships with).

**Comment by masterleinad** [comment]
If we also bump the `gcc` requirement to `gcc-5`(which ubuntu 16.04 ships with), we could almost require C++14. :smile:

**Comment by bangerth** [comment]
I'll explain why I'm not happy with this patch: We use the tutorials as teaching tools, and as such, everything that is not blatantly obvious requires an explanation that distracts from the actual message we want to convey with each tutorial. Now, C++ is already a rather complex language our students have trouble with, and so the thought of having to explain why one needs `{}` in certain places (and maybe why using `()` is going to yield something entirely different, even though if one were to provide a nonzero number of constructor arguments the two are exactly the same) is just not an appealing thought. The whole point of #8767 was to simplify the code precisely because we had to explain why some classes needed a default constructor -- something that was just not to the message of the programs in which that happened.

We're going to release what we develop now in 2020. That would be four years after clang 3.8 was bundled with Ubuntu, and probably even more years after gcc stopped requiring the constructor. I think that's a reasonably long lag time.

**Comment by bangerth** [comment]
Have we confirmed that clang 3.8 is actually fine with the code?

**Comment by masterleinad** [comment]
No, we need clang 3.9: https://godbolt.org/z/qCCkJe.

**Comment by tjhei** [comment]
> The whole point of #8767 was to simplify the code precisely because we had to explain why some classes needed a default constructor -- something that was just not to the message of the programs in which that happened.

I agree that having to explain ``{}`` is not elegant. In that case, I would rather undo #8767 and be explicit  about the constructor. I actually like this because I had questions on how to set the number of components to something other than 1 before, which is easy if the explicit call to the base is there.

By the way: Ubuntu 18.04 (the next stable) comes with clang-6. I don't mind bumping the minimum to that. It certainly would make testing easier. :-D

**Comment by bangerth** [comment]
I agree that reverting #8767 would be preferable to me over the current patch. We could just re-apply it for 9.3 then.

@dealii/dealii: But what do others think about requiring clang 3.9? (I don't think it's necessary to *require* 6.0.)

**Comment by drwells** [comment]
I think I prefer reverting #8767. Would clang 3.9 accept `= default;` instead?

**Comment by masterleinad** [comment]
> I think I prefer reverting #8767. Would clang 3.9 accept `= default;` instead?

Yes, but `clang 3.8` does not: https://godbolt.org/z/YGJjjq

**Comment by drwells** [comment]
Bummer.

It looks like clang 3.8 is only three years old so I think we should support it - we usually have a much longer support window than that.

**Comment by Rombur** [comment]
> But what do others think about requiring clang 3.9?

I am always in favor of requiring newer compilers :wink:

**Comment by drwells** [comment]
We don't all agree, so lets do the usual thing and vote:

:+1: drop support for clang 3.8 and clang 3.9 
:-1: keep support for clang 3.8 and clang 3.9

**Comment by Rombur** [comment]
@drwells I modified your poll, we wouldn't drop support for 3.8 and 3.9 and 3.7 and 3.8

**Comment by drwells** [comment]
Thanks. We should follow up with a second poll about 3.9 if we drop those.

**Comment by masterleinad** [comment]
Why do you want to discuss 3.9?

**Comment by drwells** [comment]
I thought support of 3.9 was the original question posed by @bangerth.

**Comment by tamiko** [comment]
I currently have the following configurations on the tester:
```
testsuite-64bit_indices (gcc-9)
testsuite-clang-4.0
testsuite-clang-5.0
testsuite-clang-6.0
testsuite-clang-7.0
testsuite-clang-8.0
testsuite-clang-9.0
testsuite-gcc-4.9
testsuite-gcc-6
testsuite-gcc-7
testsuite-gcc-8
testsuite-gcc-9
testsuite-minimal (gcc-9)
testsuite-petsc_complex (gcc-9)
```
I wouldn't mind dropping some of the older compilers. That would in particular free some resources for adding four more flavors (last Ubuntu LTS, last Ubuntu release, last debian release, debian testing).

**Comment by tamiko** [comment]
For context - I plan to migrate these guys here to the tester in a couple of days:
```
 -        bionic            shut off   ubuntu 18.04 lts
 -        bullseye          shut off   debian 11
 -        buster            shut off   debian 10
 -        disco             shut off   ubuntu 19.04
```

**Comment by bangerth** [comment]
Alternative proposal: We only get the error if we mark the objects as `const`. That's conceptually the right thing to do, but I suspect nobody will notice if we "forget" the `const` for these objects. At the very least, I suspect we won't get questions we then need to explain. Would that be a compromise? It avoids having to declare the default constructors, and also avoids the need for `{}` initialization.

**Comment by masterleinad** [comment]
I pushed a commit following that suggestion. I don't have a strong opinion on whether this is a better solution or not. 
We should nevertheless discuss updating the compiler requirements.

**Comment by bangerth** [comment]
I'm ok with merging this as currently written -- I think it introduces minimal hassle. 

The current situation on the poll is:
* Drop support for clang 3.7/3.8: 4 votes
* Keep support: 1 vote.

So we *could* require clang 3.9 (if one wants to use clang to begin with), but we don't actually have to go that route yet. The current patch suffices to extend life support for these older compilers by a while.

**Comment by masterleinad** [comment]
Someone needs to approve this.

**Comment by bangerth** [comment]
I'm approving, but maybe we could have a second person do the same?

(I think it's worthwhile keeping both commits.)

**Comment by masterleinad** [comment]
Then, let's remove the label for now.

**Comment by drwells** [comment]
I think I am missing something - we voted to not support the compiler for which this patch was written. Doesn't that mean we should not merge?

**Comment by tamiko** [comment]
Let's merge for the time being and drop support when something else shows up.

**Pull request merged**
