### PR TITLE
Convert step-8 to a simplex test

### PR DESCRIPTION
**Pull request by nmuch**
Porting was pretty easy. I had to exchange `execute_coarsening_and_refinement()` for `refine_global()` and reduce refinment cycles to reduce runtime.

I added a comment with all changes to make simplecies work.

### CODE REVIEW

**Review by peterrum — APPROVED** [review]
Thanks a lot, @nmuch! May I ask you to remove the documentation! Thx.

**Comment by nmuch** [comment]
Sure..

**Review by peterrum — APPROVED** [review]

**Comment by bangerth** [comment]
Nice, good work!

**Pull request merged**
