### PR TITLE
Use check_solver_within_range in PETSc(serial) tests

### PR DESCRIPTION
**Pull request by masterleinad**
Part of #4715. Relates #4704.

### CODE REVIEW

**Comment by drwells** [comment]
I would still prefer that we are a bit more conservative and add a new macro that reproduces the current test output.

**Comment by tamiko** [comment]
@drwells I disagree. The idea is to make the output more stable with respect to compiler optimiazations.
Printing initial and final residuals and the iteration number is not a great idea.

**Comment by masterleinad** [comment]
I'll need to fix up this a bit.

**Comment by masterleinad** [comment]
Done.

**Pull request merged**
