### PR TITLE
Use gold instead of the traditional linker if possible.

### LINKED ISSUE #1476: Use gold as the linker when available
http://blogs.s-osg.org/an-introduction-to-accelerating-your-build-with-clang/ shows that one can get nice speedup by using gold instead ld as the linker. On manycore machines (e.g., my 64-core build servers) it usually takes about 5 minutes to compile everything, plus 2 minutes to link everything. The last phase of course is sequential, so I *really* case about link time.

https://bugs.webkit.org/show_bug.cgi?id=137953 seems to have some useful ideas.

### PR DESCRIPTION
**Pull request by bangerth**
This fixes #1476.

### CODE REVIEW

**Comment by tjhei** [comment]
Does gcc fail if gold is not installed/usable so that ENABLE_IF_SUPPORTED fails? We need to test this with old gccs and clang to see if this doesn't break.

**Comment by tamiko** [comment]
@tjhei Correct. I'll give feedback as soon as I've tested in on my setups.

**Comment by bangerth** [comment]
ping?

**Comment by tamiko** [comment]
Well, bad news. We also have to check whether ld.gold is actually evailable. I'll refactor this to ```check_01_compiler_features.cmake``` (because it requires a test) and open a separate pull request.

**Comment by tamiko** [comment]
Btw. Clang-3.7.0 is more intelligent. Here, ```-fuse-ld=gold``` is not available if ```ld.gold``` cannot be used/found.

**Comment by bangerth** [comment]
> Btw. Clang-3.7.0 is more intelligent. Here, |-fuse-ld=gold| is not available
> if |ld.gold| cannot be used/found.

I had hoped that GCC would also implement this :-(

**Pull request closed without merging**
