### PR TITLE
github: update indent worker to Ubuntu 22.04

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Review by marcfehling — APPROVED** [review]

**Comment by bangerth** [comment]
What's the status here?

**Comment by tamiko** [comment]
@bangerth I'll have to iron out some doxygen errors introduced when switching to the new version. I'll do this soon :-)

**Comment by jpthiele** [comment]
This is related to #16024 and the PR's linked therein.
Depending on the doxygen version used in 22.04, the errors should all be fixed by the linked PR's.

**Comment by jpthiele** [comment]
Ping @tamiko: 
Since #16024  the indent runner now installs a fixed doxygen version (1.9.6) that should be above Ubuntu Jammys own version the errors and warnings you got should all be fixed or suppressed (two spurious ones) in the current master branch.

**Comment by bangerth** [comment]
Ping?

**Comment by tamiko** [comment]
@bangerth Updated and ready for review.

**Pull request merged**
