### PR TITLE
Simplify the initialization of a variety of objects.

### PR DESCRIPTION
**Pull request by bangerth**
This is the promised follow-up to #7060.

### CODE REVIEW

**Comment by bangerth** [comment]
Actually, it's not so much about brace initializers but just simpler syntax to begin with.

**Comment by drwells** [comment]
Why not use `{}` for `std::string`?

**Comment by bangerth** [comment]
I could, but I think of `{}` as an empty list, which is not entirely wrong for a string, but `""` just seemed like the more easily readable variant.

**Pull request merged**
