### PR TITLE
Make the order of active_fe_indices stable

### PR DESCRIPTION
**Pull request by bangerth**
This is the follow-up to #7233. The first patch is identical to #7233, and only the second commit is relevant (I will rebase once #7233 is merged). I am pretty sure that this will break lots of tests that now create a different DoF order, but it should not affect correctness. I will have to check which tests need to be adjusted tomorrow.

@marcfehling -- this is my proposal for the bug you see. Can you try this out on your testcase and see whether it helps in all of the combinations in which you found that something breaks? If this helps for the 2d case, then I will have to redo the same kind of patch also for edges in 3d, and vertices.

In reference to #3511. It should provide most of a fix for #7162, but the edge/vertex changes mentioned above are still necessary to fix this completely.

### CODE REVIEW

**Comment by bangerth** [comment]
The two places I thought that need to be fixed in a similar way as here (and maybe documented like in #7233) are in `reserve_space_vertices()` around line 223 -- but this place already uses a stable ordering --; and in `reserve_space()` for 3d for lines around line 730 and following -- which actually also works correctly already, see line 803. 

In other words, this is the whole patch, nothing more to fix! (Other than to update the failing tests.)

**Comment by marcfehling** [comment]
I confirm that your patch fixes the bug for my testcase! Good work!

And if you apply similar changes for vertices and edges, I guess the patch I'm working on in pursuance of #7179 becomes obsolete (see: https://github.com/dealii/dealii/issues/7179#issuecomment-424121429). Which is good since my initial approach to tackle this did not work :)

**Comment by marcfehling** [comment]
Following your last comment, I just checked `hp_unify_dof_indices_02` from #7179 again. Both DoFs we discussed there now belong to subdomain 1, so everything behaves as expected now.

So this pull request also resolves #7179.

**Comment by marcfehling** [comment]
I updated the test reulsts with respect to the new sorting algorithm. Feel free to cherry-pick the following commit, or I'll provide it as a follow-up pull request -- whatever you prefer: https://github.com/marcfehling/dealii/commit/08ae3f93c14463112dc23d7ffe88b395f7aa5adc

There were just two existing tests affected by this change, namely `hp_unify_dof_indices_02` and `hp_step-40_variable_01`. In the latter, the problem with the inconsistent number of DoFs already manifested itself (see `mpirun=10` results).

I do not have configured my `petsc` distribution with complex numbers. Could someone run a quick check on the `hp_step-40_variable_01.with_petsc=true.with_petsc_with_complex=true` tests?

**Comment by marcfehling** [comment]
I neither have configured `petsc` with `hypre`. Would you do the same for `hp_step-40_variable_01.with_petsc_with_hypre=true`?

**Comment by bangerth** [comment]
I've cherry-picked your commit. Let's see what happens here now!

**Comment by marcfehling** [comment]
Interesting. The tests that failed for your commit differ from those whose output I adjusted.

I was sure that I ran the whole testsuite, but apparently something went wrong. I'll have a look tomorrow and provide a separate commit if the current testers will fail again.

**Comment by bangerth** [comment]
Rebased. I think we still have to see what the test suite does.

**Comment by marcfehling** [comment]
Sorry, I was hasty and did not run the indentation script. Please use https://github.com/marcfehling/dealii/commit/6e77cf2c2f67c2fdc4a89cf3b953a8565b5cebac instead.

**Comment by bangerth** [comment]
@marcfehling -- I appreciate the help! I suppose you looked at the changes of at least a couple of the tests and concluded that they were reasonable? Say of `tests/fe/fe_nothing`?

**Comment by marcfehling** [comment]
I looked at `hp_renumber` and `hp_step-40`, but not at `fe_nothing`. I don't have a clue right now how the results come about before and after the patch.

From my understanding, the constrained DoFs should have much higher indices. Can we talk about this tomorrow?

**Comment by marcfehling** [comment]
Ha! The results in `fe_nothing` make sense now and are correct! I'll show you a sketch tomorrow. :)

**Comment by bangerth** [comment]
OK, then I think this is ready for review/merge once the testers are through!

**Comment by bangerth** [comment]
Ping?

**Comment by bangerth** [comment]
Still ping?

**Comment by bangerth** [comment]
(I just don't like merging my own PRs, even if they have been approved.)

**Comment by jppelteret** [comment]
Since this has been approved by 2 people and has been sitting around for a few days, I'm going to go ahead and merge it (as requested).

**Pull request merged**
