### PR TITLE
Rebase Opencascade Boundary classes

### PR DESCRIPTION
**Pull request by masterleinad**
It turns out that we can remove the dependency of the `Opencascade` `Boundary` classes on `Boundary` by simply rebasing to `Manifold`. Technically, this change is incompatible but I doubt that this is really an issue since the functions in `Boundary` are mainly pure virtual and trivial otherwise.

The change of the output for `opencascade/normal_projection_01` is due to the new weights used in the refinement.

Related to #4921.

### CODE REVIEW

**Comment by bangerth** [comment]
You'll have to fix the indentation.

These classes were deprecated before. Do you recall what they were deprecated in favor of? @luca-heltai ?

**Comment by masterleinad** [comment]
> You'll have to fix the indentation.

Actually, `Travis CI` had a different problem:
```
fatal: unable to access 'https://github.com/dealii/dealii.git/': Failed to connect to github.com port 443: Connection timed out
The command "eval git clone --depth=50 https://github.com/dealii/dealii.git dealii/dealii " failed 3 times.
```
I'll try if this goes away after rebasing.

> These classes were deprecated before. Do you recall what they were deprecated in favor of? @luca-heltai ?
All Boundary classes were deprecated in #5222. Since there are no other `Manifold` classes that can deal with `TopoDS_Shape` objects, I would assume that we don't have a replacement.

**Comment by luca-heltai** [comment]
They were deprecated in favour of the implementation presented in this PR. 

:)

AKA, too much rush in deprecating stuff... :)

**Pull request merged**
