### PR TITLE
Introduce DoFAccessor::get_finite_element() 

### LINKED ISSUE #4929: Replace DoFAccessor::get_fe() by DoFAccessor::get_finite_element()
#4908 deprecates the `(hp::)?DoFHandler::get_fe()` function and replaces it by `get_finite_elemen()`. We should probably do the same with the `DoFAccessor::get_fe()` function for consistency.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #4929. 

We will probably want to replace `get_fe` by `get_finite_element()`  everywhere in the code base which I will do successively.

### CODE REVIEW

**Comment by bangerth** [comment]
OK to merge once the tester is happy.

/run-tests

**Comment by bangerth** [comment]
Hm, I'm starting to rethink this. This patch and #4944 produce a lot of churn for not very much benefit. The name `get_fe()` doesn't strike me as particular unintelligible (do others feel differently about this?) and so maybe a better way would be to keep the name everywhere except in the `hp::DoFHandler` class where we deprecate it for this round (as has already happened). After the next release, we remove the `hp::DoFHandler::get_fe()` function and immediately reclaim it whereby it does what `hp::DoFHandler::get_finite_element()` does.

Or maybe we just make an incompatible break as we do elsewhere and just change what that function does?

What do others think? Surely there are fewer users of `hp::DoFHandler::get_fe()` than there are of `cell->get_fe()`, `fe_values.get_fe()`, and `::DoFHandler::get_fe()` (all of which now need to be changed).

**Comment by tjhei** [comment]
I would prefer to keep it as ``get_fe`` to avoid unnecessary churn.

**Comment by kronbichler** [comment]
I would also vote for keeping `get_fe()` and rather adapt the `hp::DoFHandler`.

**Comment by masterleinad** [comment]
In my opinion `get_finite_element` is the better name since this is the class name of the object we return.
In the end, this is the same thing as we did in #1970 with respect to `DoFHandler::get_tria`. But it seems that I am outnumbered here.

The idea of #4770 was to have a common interface for `DoFHandler` and `hp::DoFHandler` with respect to the access to `FiniteElement/hp::FECollection`. We would loose this if we go back to have `DoFHandler::get_fe()` and `hp::DoFHandler::get_finite_element()` for the same functionality.

If we can't agree on renaming `get_fe()`to `get_finite_element()`, I am therefore in favor of doing an incompatible change in what `hp::DoFHandler::get_fe()` does.

**Comment by jppelteret** [comment]
I think that @masterleinad makes a good point, especially given the change in #1970. My preference is for `get_finite_element()` as well.

**Comment by kronbichler** [comment]
> In the end, this is the same thing as we did in #1970 with respect to `DoFHandler::get_tria`

Not exactly, because if I remember correctly we used that opportunity to unify the two pre-existing `get_tria()` and `get_triangulation()` calls in different containers. Whereas we uniformly use `get_fe()` right now. While I agree that `get_finite_element()` would have been the better name if we were to redesign these data structures from scratch, I am opposed to this because it is a pain in the ass to change all those places that use them and it is not used inconsistently within the library. `get_fe()` is likely worse than `get_tria()`. In other words, I'm against going the PETSc way of confusing people that simply use these things in production codes that are built on top of deal.II.

Admittedly, we have a gray zone with `hp::DoFHandler` as mentioned by @masterleinad, but you don't want to know how many working hours were wasted by the `get_tria()` change in our group. For myself it was probably not more than an hour or so because I know these things so well, but honestly I stopped counting the times PhD students or students came to my office and complained that their old codes were broken after I upgraded our production code without the otherwise necessary `ifdef DEAL_II_VERSION_LT(8,3,0)` guards inside a code that uses parts substantially written by me and not themselves, so it was not really clear to them what happened. Well, I should not have taught them the bad habit of disabling the deprecation warnings that came up before that, but we do really change a **lot of interfaces** these days, so again that was self-defense in some sense. Maintaining a production code based on deal.II has become much more work during the last two years than the two years before, even after subtracting the increase in complexity of our production code.

**Comment by masterleinad** [comment]
@kronbichler If most of us agree that we want to keep `get_fe` in `DoFAccessor` and `FEValues` I am of course fine with this and I understand you arguments (although we just deprecate things and don't break the interface immediately).

But what is your suggestion regarding `hp::DoFHandler` and `DoFHandler`? 
For me there are two possibilities:
1.) We leave these classes as they are now and accept that we have `[hp::]?DoFHandler::get_finite_element` and `get_fe` for the other classes.
2.) We get rid off `[hp::]?DoFHandler::get_finite_element` again and put the implementation for `hp::DoFHandler` into `get_fe`; thus doing an incompatible change.

I don't think that changing interfaces back and forth deprecating `get_fe` in the next release just to deprecate `get_finite_element` after that and go back to `get_fe` is better.

**Comment by bangerth** [comment]
`hp::DoFHandler::get_finite_element()` (returning a single element) only makes sense if an index is passed (unlike the `::DoFHandler`). So we could rename it to `hp::DoFHandler::get_fe(unsigned int)` that doesn't have a default value for the argument, and simply overloads the existing function that has no argument and that returns the collection.

That function remains deprecated in favor of `hp::DoFHandler::get_fe_collection()` and can be removed by the next release.

This seems to provide a backward compatible approach for everyone -- if you don't call the function with an argument, you get the old behavior. If you do provide an argument, you get the overload that does what we want it to do.

**Comment by masterleinad** [comment]
I guess this is the best remedy.

**Comment by masterleinad** [comment]
Superseded by #4959.

**Comment by bangerth** [comment]
Thanks for being open-minded about this. It always sucks to throw away a patch on which you've spend a good deal of time. I appreciate you being willing to do so!

**Pull request closed without merging**
