### PR TITLE
Rename settings_ to settings in distributed/tria.cc

### PR DESCRIPTION
**Pull request by peterrum**
FYI @tjhei: to be consistent

### CODE REVIEW

**Comment by bangerth** [comment]
YES! I've never been a fan of these underscores :-)

**Comment by masterleinad** [comment]
Honestly, I don't like using the same name for a function argument and a member variable at all. I would try to avoid shadowing as much as possible but that might just be me.

**Comment by tjhei** [comment]
> Honestly, I don't like using the same name for a function argument and a member variable at all. I would try to avoid shadowing as much as possible but that might just be me.

I think this is the only place where shadowing is okay. The alternative is a) that the member is named awkwardly, b) the argument is named awkwardly (which shows up in the documentation), or c) they have different names and it is not obvious to me that they are the same thing.
Maybe adopting something like bla_ is not a bad idea, but we don't do that consistently...

**Comment by bangerth** [comment]
On 8/23/19 11:49 AM, Timo Heister wrote:
> I think this is the only place where shadowing is okay. The alternative is a) 
> that the member is named awkwardly, b) the argument is named awkwardly (which 
> shows up in the documentation), or c) they have different names and it is not 
> obvious to me that they are the same thing.

To be clear, I only advocate for this style if the two are identical -- i.e., 
if the member variable is initialized with the function argument of same name. 
In this case, there is no question what *value* is being used if the name 
appears in the remainder of the function (even though there is a legitimate 
question as to what *variable* is being used.

**Pull request merged**
