### PR TITLE
Version number update: deal.II -> 9.4.0-pre

### PR DESCRIPTION
**Pull request by tamiko**
This pull request fixes a mistake I introduced a while ago. It updates the
deal.II version number to 9.4.0-pre,

Rationale:

 - During the last release I should have set the version number to 9.4.0-pre
   and not 10.0.0-pre to allow for the possibility to do a 9.4.0 release.

 - This change does not stop us from making a 10.0.0 in a few months.

 - If we want to have a reasonable chance of doing a 9.4.0 release we should
   change to "9.4.0-pre" now so that downstream projects encounter the change
   and can update the version dependency accordingly.

I am not sure whether this change will fly but I think we should give it a try.

### CODE REVIEW

**Review by tjhei — APPROVED** [review]
Awkward indeed. Well, I also think it is okay to do this change now. I don't see us having many major new features between now and May/June...

**Review by masterleinad — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]

**Review by drwells — APPROVED** [review]
I don't have any strong opinions on this one: if we don't break external projects then I think its fine to change this number.

**Comment by bangerth** [comment]
Well, we've got five approvals. Is that enough to merge? :-)

**Comment by marcfehling** [comment]
We should also adjust the release milestones in github correspondingly. I will go ahead and simply rename them for now.

**Pull request merged**
