### PR TITLE
fix installation of FeatureConfig.cmake

### PR DESCRIPTION
**Pull request by BenBrands**
Fixed path for use of DEAL_II_FEATURE_CONFIG

in reference to https://github.com/dealii/dealii/pull/4437

### CODE REVIEW

**Comment by davydden** [comment]
@tamiko 

> The correct path is ${DEAL_II_PROJECT_CONFIG_RELDIR}.


that's NOT the correct path. Namely, the file ends up in `<BUILD_FOLDER>/lib/cmake/deal.II/deal.IIFeatureConfig.cmake`, whereas install is looking for it in `<BUILD_FOLDER>/config/cmake/deal.IIFeatureConfig.cmake`

**Comment by tamiko** [comment]
@davydden It is. See #4445

**Comment by davydden** [comment]
> It is

care to elaborate how your fix is principally better/different?

**Comment by tamiko** [comment]
@davydden The build directory and the final installation layout have to be kept in sync - otherwise it is not possible to use the build directory directly for configuration any more.

The misunderstanding is a very simple one - I have to create to slightly different project configurations for build directory and installation directory. In the build directory the one that should be used resides under `${PROJECT_CONFIG_RELDIR}`, the configuration in `cmake/config` is the one that gets installed.

**Comment by tamiko** [comment]
*argh* See #4446

**Comment by tamiko** [comment]
@davydden I got the pull request number wrong o_O, see above.

**Comment by davydden** [comment]
> The build directory and the final installation layout have to be kept in sync

but they are not, `deal.IIConfig.cmake` lives in `<build/config/cmake` whereas `deal.IIFeatureConfig.cmake` in `lib/cmake/deal.II/`. Both get installed into `prefix/lib/cmake/deal.II/`

**Comment by davydden** [comment]
@tamiko my apologies, apparently `deal.IIConfig.cmake` is both in `cmake` and `lib/cmake/deal.II` of the `build` prefix.

**Comment by tamiko** [comment]
@davydden Guess who wrote this insanity >_>

**Pull request closed without merging**
