### PR TITLE
[9.5] CMake: remove VTK configure option

### PR DESCRIPTION
**Pull request by tamiko**
Our CMake configure for VTK isn't quite prime-time ready. Given the fact
that we currently only support a very minimal infrastructure, let's just
remove the configure option for the release.

In reference to #15383
@luca-heltai *ping*

### CODE REVIEW

**Comment by drwells** [comment]
There are a few other places where we use this feature:
- `include/deal.II/vtk/`
- `doc/doxygen/options.dox.in`
- changelog
- `doc/users/config.smaple`
- `doc/users/cmake_dealii.html`

I'd prefer to remove all of it in addition to the CMake configuration.

**Comment by tamiko** [comment]
@drwells Sure. Let me update the pull request.

**Comment by tamiko** [comment]
@drwells updated!

**Review by kronbichler — APPROVED** [review]

**Comment by luca-heltai** [comment]
I'm not quite sure why osx builds are failing on jenkins. It looks like we don't set cxx standard properly. I'm going to ignore that for the moment.

**Review by luca-heltai — APPROVED** [review]

**Pull request merged**
