### PR TITLE
Use std::to_string() instead of boost lexical_cast.

### PR DESCRIPTION
**Pull request by bangerth**
See also #9409.

### CODE REVIEW

**Comment by drwells** [comment]
I think that this change was my first or second deal.II PR ever :)

**Comment by masterleinad** [comment]
You might want to update the documentation as well:
https://github.com/dealii/dealii/blob/1c31021568346676c9ec72e9d9e5f70297061ca3/include/deal.II/base/utilities.h#L200-L207

**Comment by drwells** [comment]
@masterleinad that is in #9409.

**Comment by bangerth** [comment]
This fails the `base/utilities_11` test because `std::to_string()` writes floating point numbers with a different number of significant digits than `boost::lexical_cast`. Indeed, based on https://www.boost.org/doc/libs/1_65_1/doc/html/boost_lexical_cast/synopsis.html#boost_lexical_cast.synopsis.lexical_cast and https://en.cppreference.com/w/cpp/string/basic_string/to_string, `boost::lexical_cast` uses the standard `iostream` interface for conversion, whereas `std::to_string` uses `sprintf`, and as the example on the latter page shows, does not actually yield what one would typically want for floating point numbers.

I modified this consequently: We really only want to use `std::to_string()` for integral types.

**Pull request merged**
