### PR TITLE
MatrixFreeTools::compute_diagonal: enable for hp

### PR DESCRIPTION
**Pull request by peterrum**
Follow-up PR to #11307. Only the last PR is relevant.

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]
Excellent.

**Comment by kronbichler** [comment]
Could you rebase on master? Not strictly necessary I believe, but I guess that is the reason for the `do not merge` label?

**Comment by peterrum** [comment]
> Could you rebase on master? 

Done.

**Review by kronbichler — APPROVED** [review]

**Pull request merged**
