### PR TITLE
fix PETSc ReinitHelper for LinearOperator and MPI vectors

### LINKED ISSUE #2522: fix PETSc ReinitHelper for LinearOperator and MPI vectors
just so that we don't forget, there are still some left-over issues (pointed out by @luca-heltai ) from PR https://github.com/dealii/dealii/pull/2502 which is authored by  @ESeNonFossiIo .

### PR DESCRIPTION
**Pull request by ESeNonFossiIo**
fixes https://github.com/dealii/dealii/issues/2522

### CODE REVIEW

**Comment by bangerth** [comment]
@davydden -- I'll let you handle this.

@ESeNonFossiIo -- I suppose the "failing test" was the one that failed previously but now works?

**Comment by ESeNonFossiIo** [comment]
@bangerth ... Yup. It is a test I wrote to point out a bug in my previous code. Tomorrow I will squash and fix commits. Now its to late (for me) to check tests and english grammar.. :)

**Comment by davydden** [comment]
@ESeNonFossiIo can you please change the commit message to something more descriptive by `git commit --amend`?

**Comment by davydden** [comment]
looks good to me, but I will certainly let @luca-heltai have a quick look :smile:

**Comment by luca-heltai** [comment]
Looks ok to me. This addresses all comments I had on the previous PR, and fixes a few issues. @ESeNonFossiIo , can you address @davydden comments for the commit message?

**Comment by ESeNonFossiIo** [comment]
@davydden and @luca-heltai Done.
@davydden I used `close #2522` to close automatically the issue and link that bug this PR. Btw, I changed the name of the commit. Is it fine?

**Comment by bangerth** [comment]
@ESeNonFossiIo -- just put the text "closes #xxxx" or "fixes #xxxx" anywhere in the text of the pull request, and it will do the same.

**Comment by ESeNonFossiIo** [comment]
Thanks @bangerth . I did not know that. Good to know :)

**Pull request merged**
