### PR TITLE
DH to DoFHandlerType

### PR DESCRIPTION
**Pull request by drwells**
This is part of an ongoing attempt to make the template argument style more consistent. I reran the full test suite this morning and did not get any new failures so I believe it is ready to merge.

I went ahead and shortened some really long lines and fixed the indentation where appropriate. The indentation in `include/deal.II/numerics/error_estimator.h` is particularly beautiful.

### CODE REVIEW

**Comment by bangerth** [comment]
Nice. So I guess you decided not to make a difference in naming between class names and template names?

**Comment by drwells** [comment]
I do not understand what you mean. I used `DoFHandlerType`, not `DoFHandler`, so my intent was to use different names for template parameters and classes.

**Comment by bangerth** [comment]
I meant making a distinction between these two cases:
```
  template <typename DoFHandlerType> 
  void f(const DoFHandlerType &dh);
```
and
```
  template <template <int,int> class ChooseYourName, int dim, int spacedim> 
  void f(const ChooseYourName<dim,spacedim> &dh);
```
In the second case, the template name `ChooseYourName` is not actually a *type*, but the name of a template. So one could argue that `DoFHandlerType` is not the appropriate choice of name. At the same time, I don't think I feel strongly one way or the other, and I'm totally fine with leaving it as is.

**Comment by drwells** [comment]
Oh, I see. I have a slight preference (maybe 55 to 45) for `DoFHandlerType` in that case to make it clear that it could be `hp::DoFHandler` or just `DoFHandler`.

Does anyone else have a strong preference on template template parameters?

**Comment by kronbichler** [comment]
I prefer DoFHandlerType as the name in both cases listed by @bangerth.

**Comment by bangerth** [comment]
Then that's what we'll go with :-)

**Pull request merged**
