### PR TITLE
Rename a callback in PETScWrappers::TimeStepper.

### PR DESCRIPTION
**Pull request by bangerth**
This is step 1 for #17180. I've got the corresponding patch for the currently pending step-86 queued up locally and will rebase that once this PR here is merged.

@stefanozampini FYI.

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]

**Comment by stefanozampini** [comment]
On a second thought, using the term algebraic_components can be misleading: This callback is supposed to update only the hanging nodes ( thus the name distribute )  while the algebraic components are not only hanging nodes. For example, when you solve a DAE, these are also the algebraic equations that are already taken care in the jacobian solve. Can you find a different name?

**Comment by bangerth** [comment]
No, my understanding is that it's supposed to update *all* algebraic components, which includes both hanging nodes and boundary nodes. In step-86, the corresponding callback is this:
```
petsc_ts.distribute = [&](const double                time,
                              PETScWrappers::MPI::Vector &y) {
      TimerOutput::Scope t(computing_timer, "set algebraic components");
      update_current_constraints(time);
      current_constraints.distribute(y);
   };
```
`current_constraints` includes both kinds of constraints.

For DAEs, that's a good question. Say if you solve a time dependent Stokes equation, all the pressures would be marked as algebraic. @stefanozampini -- what is the callback supposed to do in that case?

**Comment by stefanozampini** [comment]
With DAEs, the algebraic fields are solved during the during the nonlinear solve at the time step level. That's why I don't like the name of the callback , as these are still algebraic components . The reason I introduced the algebraic components index set is precisely the dae case (you don't want to compute the LTE on a dependent variable). Then with @luca-heltai we realized we should have also included hanging nodes and bc dofs in the set

**Comment by bangerth** [comment]
@stefanozampini So do I understand you right that the `algebraic_components` callback should also return the pressure in the time-dependent Stokes equation, for example, but that what is currently called `distribute` should not set those? That was certainly not clear to me -- I had assumed that the latter function should set exactly the indices returned by the former function.

**Comment by stefanozampini** [comment]
Correct.

**Comment by bangerth** [comment]
Oh, that was not clear from the documentation. If the two functions are supposed to do different things, then they should have different names. How about `algebraic_components` and `update_constrained_dofs` then? Does that adequately represent what you think they should do?

**Comment by stefanozampini** [comment]
> Oh, that was not clear from the documentation. If the two functions are supposed to do different things, then they should have different names. How about `algebraic_components` and `update_constrained_dofs` then? Does that adequately represent what you think they should do?

One can still object pressure is a constrained field. I was using `distribute` exactly because I wanted to match the `distribute` concept of the constraints

**Comment by bangerth** [comment]
Right, but one would generally not do it that way. I still think that `distribute()` is not a good name (not here, and not in `AffineConstraints`, but we can not change the latter any more). Would `update_constrained_dofs` be a name you're ok with?

**Comment by stefanozampini** [comment]
Ok with me

**Comment by bangerth** [comment]
OK, so updated.

I will follow up (in a separate patch) by documenting better what the "algebraic" components are and how that relates to the "constrained" components.

**Review by luca-heltai — APPROVED** [review]

**Pull request merged**
