### PR TITLE
cppcheck results 1

### PR DESCRIPTION
**Pull request by drwells**
I recently reran cppcheck on the code base (now that the new version is out) and it found a bunch of new stuff, including #3726 and #3728. Since there are a lot of small things to change I lumped half of the commits in this PR (and I will put up the other half in a moment).

I reran the whole test suite and got no new test failures.

### CODE REVIEW

**Comment by drwells** [comment]
The other half changes adjacent lines to this so I will wait until this is merged before posting the other half.

**Comment by bangerth** [comment]
Very nice -- I particularly like the change to reduce the scope of variables. (I guess you didn't have the HDF5 interfaces enabled ;-) Do not even think about looking at those in this regard.)

OK to merge if the tester is happy.

**Comment by drwells** [comment]
For better or worse all of the HDF5 `hsize_t a[5]` and whatnot are all declared and used in the same scope so cppcheck happily accepts them :)

**Comment by bangerth** [comment]
Ah, that's a little bit funny :-)

**Pull request merged**
