### PR TITLE
Modify FE_QHierarchical to use generalized*_s_p instead

### PR DESCRIPTION
**Pull request by class4kayaker**
Fix to #474.

Changes FE_QHierarchical to set the `generalized*_support_points` vectors instead of `unit*_support_points`. This has been tested using the `*fe/fe_q_hie*` tests.

### CODE REVIEW

**Comment by bangerth** [comment]
Running the full testsuite... hang in there...

**Comment by bangerth** [comment]
I get the following test failures:
```
        1395 - fe/fe_support_points_q_hierarchical.debug (Failed)
        1396 - fe/fe_support_points_q_hierarchical.release (Failed)
        1417 - fe/fe_data_test.debug (Failed)
        1418 - fe/fe_data_test.release (Failed)
```
I suspect that that is all to be expected, but can you check and update the test results as appropriate?

**Comment by class4kayaker** [comment]
After running the tests locally to look at the output both are obviously reasonable changes. I have modified the appropriate files and the tests in question are now passing.

One question that is related but not directly relevant is whether it would be desirable to add tests on the list of generalized support points as a separate issue.

**Comment by bangerth** [comment]
Thanks for taking a look. Yes, I agree that such a test would be useful.

**Pull request merged**
