### PR TITLE
Avoid setting a Boundary when we already have a volume manifold.

### PR DESCRIPTION
**Pull request by kronbichler**
This addresses the issue discussed in #5562.

### CODE REVIEW

**Comment by bangerth** [comment]
The tests that you are modifying all fail:
```
	3406 - matrix_free/matrix_vector_stokes_noflux.debug (Failed)
	3409 - matrix_free/copy_feevaluation.debug (Failed)
	3423 - matrix_free/matrix_vector_stokes_notempl.debug (Failed)
```
They all get floating point exceptions. Is this intended?

**Comment by kronbichler** [comment]
The FPE is fixed by #5564, so this should be fine for merging.

**Comment by kronbichler** [comment]
Thinking about it, I guess it is better that we move the commit to #5564 so that we do not have these spurious failures until that PR is merged.

**Pull request closed without merging**
