### PR TITLE
Fix pointer traversal range of PETSc vectors on each process

### LINKED ISSUE #17405: Potential Issue with Pointer Traversal in `PETScWrappers::VectorBase`'s Functions
While learning the underlying mechanisms of the PETSc wrappers in deal.II, I have noticed some potential issue.

 In the `PETScWrappers::VectorBase::lp_norm()` and `PETScWrappers::VectorBase::mean_value()` functions, pointers retrieved through `VecGetArrayRead()` are iterated over the entire length of the distributed vector, as demonstrated in the following code snippet from `PETScWrappers::VectorBase::mean_value()`:

```c++
// use modern processors better by
// allowing pipelined commands to be
// executed in parallel
const PetscScalar *ptr  = start_ptr;
const PetscScalar *eptr = ptr + (size() / 4) * 4;
while (ptr != eptr)
{
  sum0 += *ptr++;
  sum1 += *ptr++;
  sum2 += *ptr++;
  sum3 += *ptr++;
}
```

Here, the length of the pointer iteration is [`size()`](https://www.dealii.org/current/doxygen/deal.II/classPETScWrappers_1_1VectorBase.html#a3875621a4c149265ca738d48614f053c) rather than [`locally_owned_size()`](https://www.dealii.org/current/doxygen/deal.II/classPETScWrappers_1_1VectorBase.html#acff4e7a74af91a2ab885cf10d0feb961). This confuses me because [PETSc's documentation](https://petsc.org/release/manualpages/Vec/VecGetArrayRead/) states that `VecGetArrayRead()` should only access "this processor's portion of the vector data."

Conversely, in the `PETScWrappers::VectorBase::all_zero()` function, pointer iteration is limited to `locally_owned_size()`, which seems to be the appropriate approach.

However, `tests/petsc/33.cc` in the test suite that tests for the `lp_norm()` function do not reveal any issues, adds to my confusion.

### PR DESCRIPTION
**Pull request by QY-Shi**
To fix #17405.

This is my first (and tiny) PR for deal.II, so please correct me if I've missed anything.

### CODE REVIEW

**Review by tjhei — APPROVED** [review]
Looks good, thank you!

**Comment by tjhei** [comment]
The CI check reports
```
Invalid author 'James' without firstname and lastname

For possible solutions, consult the following page:
      https://github.com/dealii/dealii/wiki/Commit-authorship
```

Let us know if you need help with this.

**Comment by QY-Shi** [comment]
> Invalid author 'James' without firstname and lastname
> 
> For possible solutions, consult the following page:
>       https://github.com/dealii/dealii/wiki/Commit-authorship

Oops, I forgot to update the git configurations in my local repo. I've corrected this with a new commit.

**Review by bangerth — CHANGES_REQUESTED** [review]
Could I ask you to add an entry to `doc/news/changes/minor` that documents the fix? This way you will also be listed as an author of deal.II after the next release (next year)!

**Review by masterleinad — APPROVED** [review]

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
Thank you!

Separately, would you perhaps be interested to also add a test for this? I'm pretty sure that there are several similar tests for parallel vectors already that one could start with and modify to call the functions you changed!

**Pull request merged**
