### PR TITLE
[C++20] Annotate the VectorTools functions with vector concepts.

### PR DESCRIPTION
**Pull request by bangerth**
This is the next step for #14840 to add `requires` clauses to deal.II classes and functions. This particular change is what would have avoided the error reported on the mailing list that I mentioned in #14836. In essence, for all of the functions in `namespace VectorTools` that take either a `typename VectorType` or a `typename In/OutVector` template argument, I make explicit what these types have to satisfy:

- They have to be deal.II vector types
- In some cases, they have to be writable and so cannot be `const`. (This was the cause of the error.)

This turned out to be a bit tedious, but otherwise straightforward. The biggest hurdle was to enumerate all of the vector classes we have -- as others have observed at times, we have *a lot of vector classes*.

I'll share some experience from writing this patch while I'm at it: I was concerned that I would get unintelligible error messages at link time if I was not consistent between the declaration in the `.h` file and the implementation in the `.templates.h` file, but in the end, this turned out not to be the case once I understood the general principle. Basically, it comes down to this example:
```
// .h file: declaration
template <typename VectorType>
requires (condition on VectorType)
void f(VectorType v);

// .templates.h file: implementation
template <typename VectorType>
void f(VectorType v)                    // oops: forgot the 'requires' clause
{ ...}

// .inst file: explicit instantiation
template
void f(Vector<double> v);
```
The compiler will here say that it doesn't know of an implementation of the function it's trying to instantiate, and after some thought that makes sense. What happens is that in the `.h` file, I declare the existence of a function with constraints on the template type. In the `.templates.h` file, because I forgot the `requires` clause, what this is is the declaration and definition of *another* function of the same name without constraints that the compiler will select for types that do not satisfy the constraints of the first function -- in essence a "less specialized" overload of the name `f`. When the compiler comes to the explicit instantiation, it sees that the template argument `Vector<double>` satisfies the `requires` clause and that consequently an instantiation of the first version is requested -- but the compiler has never been told of an implementation of that function, and thus the error message.

The upshot is that once I understood the origin of the error message, it was not hard to find all of the places where I had gotten something wrong. And I didn't need to wait till link time to learn about it.

### CODE REVIEW

**Comment by masterleinad** [comment]
```
/home/runner/work/dealii/dealii/include/deal.II/numerics/vector_tools_integrate_difference.h:190: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
/home/runner/work/dealii/dealii/include/deal.II/numerics/vector_tools_interpolate.h:122: warning: member DEAL_II_CXX20_REQUIRES belongs to two different groups. The second one found here will be ignored.
warning: Inheritance graph for 'SmartPointer' not generated, too many nodes (138), threshold is 50. Consider increasing DOT_GRAPH_MAX_NODES.
warning: Inheritance graph for 'Subscriptor' not generated, too many nodes (198), threshold is 50. Consider increasing DOT_GRAPH_MAX_NODES.
/home/runner/work/dealii/dealii/include/deal.II/numerics/vector_tools_interpolate.h:103: warning: argument 'mapping' of command @param is not found in the argument list of VectorTools::DEAL_II_CXX20_REQUIRES((concepts::is_dealii_vector_type< InVector > &&concepts::is_writable_dealii_vector_type< OutVector >)) const
/home/runner/work/dealii/dealii/include/deal.II/numerics/vector_tools_interpolate.h:103: warning: argument 'dof' of command @param is not found in the argument list of VectorTools::DEAL_II_CXX20_REQUIRES((concepts::is_dealii_vector_type< InVector > &&concepts::is_writable_dealii_vector_type< OutVector >)) const
/home/runner/work/dealii/dealii/include/deal.II/numerics/vector_tools_interpolate.h:103: warning: argument 'fe_function' of command @param is not found in the argument list of VectorTools::DEAL_II_CXX20_REQUIRES((concepts::is_dealii_vector_type< InVector > &&concepts::is_writable_dealii_vector_type< OutVector >)) const
/home/runner/work/dealii/dealii/include/deal.II/numerics/vector_tools_interpolate.h:103: warning: argument 'exact_solution' of command @param is not found in the argument list of VectorTools::DEAL_II_CXX20_REQUIRES((concepts::is_dealii_vector_type< InVector > &&concepts::is_writable_dealii_vector_type< OutVector >)) const
/home/runner/work/dealii/dealii/include/deal.II/numerics/vector_tools_interpolate.h:103: warning: argument 'difference' of command @param is not found in the argument list of VectorTools::DEAL_II_CXX20_REQUIRES((concepts::is_dealii_vector_type< InVector > &&concepts::is_writable_dealii_vector_type< OutVector >)) const
/home/runner/work/dealii/dealii/include/deal.II/numerics/vector_tools_interpolate.h:103: warning: argument 'q' of command @param is not found in the argument list of VectorTools::DEAL_II_CXX20_REQUIRES((concepts::is_dealii_vector_type< InVector > &&concepts::is_writable_dealii_vector_type< OutVector >)) const
/home/runner/work/dealii/dealii/include/deal.II/numerics/vector_tools_interpolate.h:103: warning: argument 'norm' of command @param is not found in the argument list of VectorTools::DEAL_II_CXX20_REQUIRES((concepts::is_dealii_vector_type< InVector > &&concepts::is_writable_dealii_vector_type< OutVector >)) const
/home/runner/work/dealii/dealii/include/deal.II/numerics/vector_tools_interpolate.h:103: warning: argument 'weight' of command @param is not found in the argument list of VectorTools::DEAL_II_CXX20_REQUIRES((concepts::is_dealii_vector_type< InVector > &&concepts::is_writable_dealii_vector_type< OutVector >)) const
/home/runner/work/dealii/dealii/include/deal.II/numerics/vector_tools_interpolate.h:103: warning: argument 'exponent' of command @param is not found in the argument list of VectorTools::DEAL_II_CXX20_REQUIRES((concepts::is_dealii_vector_type< InVector > &&concepts::is_writable_dealii_vector_type< OutVector >)) const
```

**Review by masterleinad — APPROVED** [review]

**Comment by bangerth** [comment]
doxygen sees the macro alright:
```
#ifdef DEAL_II_HAVE_CXX20                                                                                                                                               
#  define DEAL_II_CXX20_REQUIRES(condition) requires(condition)                                                                                                         
#else                                                                                                                                                                   
#  define DEAL_II_CXX20_REQUIRES(condition)                                                                                                                             
#endif 
```
It should simply expand it to nothing. So I have no idea what that error corresponds to?

That said, it *is* a good idea to let doxygen read these constraints and put them into the documentation. I've pushed another patch that enables the macro and associated concepts if (i) we use C++20 *or* (ii) we are in doxygen.

**Review by masterleinad — APPROVED** [review]
Still looks OK to me.

**Comment by bangerth** [comment]
Anyone willing to merge it?

**Pull request merged**
