### PR TITLE
Allow for all FE to be returned by get_fe_by_name

### PR DESCRIPTION
**Pull request by masterleinad**

### CODE REVIEW

**Comment by tjhei** [comment]
Looks good! :+1: 

Can you update the documentation of ``FEFactoryBase::base`` ?

**Comment by masterleinad** [comment]
Along replacing get_fe_from_name everywhere, the documentation is also updated in this regard.

**Comment by drwells** [comment]
It looks like we let this get stale. Could you please fix the merge conflict in `changes.h`?

**Comment by drwells** [comment]
Otherwise this is good to go.

**Comment by masterleinad** [comment]
Here you go @drwells

**Pull request merged**
