### PR TITLE
`QSimplex<dim>::compute_affine_transformation()` in co-dimension one and two

### PR DESCRIPTION
**Pull request by fdrmrc**
This extends `QSimplex<dim>::compute_affine_transformation()` so that it works also in codimension 1 and codimension 2, i.e. you can get a Quadrature on a triangle embedded in 3D, or on a segment in 2D. Or, you can integrate over a segment embedded in the space

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]

**Comment by kronbichler** [comment]
You need to fix the documentation:
```
 /home/runner/work/dealii/dealii/source/base/quadrature_lib.cc:2196: warning: no matching class member found for 
  template Quadrature< 3 > QSimplex< 2 >::compute_affine_transformation(const std::array< Point< 3 >, 2+1 > &vertices) const
```

**Comment by fdrmrc** [comment]
Fixed. I used the first workaround I found on stackoverflow (see the snippet at the end of the answer to this question: https://stackoverflow.com/questions/4840145/doxygen-warning-no-uniquely-matching-class-member-found-for)

**Comment by fdrmrc** [comment]
@kronbichler Do you think this is okay now, or is there something else I should address?

**Review by luca-heltai — APPROVED** [review]

**Comment by luca-heltai** [comment]
If nobody objects, I'll merge this tomorrow.

**Pull request merged**
