### PR TITLE
Specialize ArrayViewHelper::is_contiguous() for pointers.

### PR DESCRIPTION
**Pull request by bangerth**
This is a follow-up to #5769 and #5801.

### CODE REVIEW

**Comment by masterleinad** [comment]
Isn't it sufficient to only have a `bool is_contiguous(T *const, T *const)` overload?
At least [godbolt](https://godbolt.org/g/L2gwwi) shows me that the `bool is_contiguous(T *, T *)` version would never be called.

Out of curiosity: Are these overloads currently called? I would think that for pointers we use the `make_array_view` overload that doesn't check contiguity.

Apart from that (and the merge conflict) this looks good!
Thanks for also adding the comments!

**Comment by bangerth** [comment]
> Isn't it sufficient to only have a |bool is_contiguous(T *const, T 
> *const)| overload?
> At least godbolt <https://godbolt.org/g/L2gwwi> shows me that the |bool 
> is_contiguous(T *, T *)| version would never be called.

I never quite remember the rules for whether
   is_contiguous(T*, T*)
binds to const pointers, and
   is_contiguous(const T*, const T*)
binds to non-const pointers. I suspect both is true. So I guess I could 
remove either version of the function -- will work on that.


> Out of curiosity: Are these overloads currently called? I would think 
> that for pointers we use the |make_array_view| overload that doesn't 
> check contiguity.

Possibly not, but it seems like something we may use at one point or 
other and it seems silly to use an O(N) concept check if we can do it 
with an O(1) check.

I'll come back when I have a different patch.

**Comment by bangerth** [comment]
I removed one of the overloads, and also added a test.

**Comment by masterleinad** [comment]
Looks good!

**Pull request merged**
