### PR TITLE
Make write_gnuplot_dof_support_point_info more robust

### PR DESCRIPTION
**Pull request by kronbichler**
The new implementation applies a lexicographic numbering that is robust against roundoff difference. It still tells two points apart that are only roundoff distance apart, but it does not wildly mix points in different directions if the first coordinate differs only slighly but the latter differ significantly. See the adapted output of the test `dof_tools_write_gnuplot_dof_support_point_info_03.output` to tell how much better the new "implicit" ordering is.

I observed this when looking at `renumber_cuthill_mckee_03.mpirun=2.output` that was failing after #5386 was merged due to roundoff changes in the grid. I could of course also just have adapted the output, but being dependent on roundoff for the sorting of indices sounds like a bad idea anyway that `numdiff` can not fix.

### CODE REVIEW

**Comment by drwells** [comment]
Is it still true that only equal points compare equal? Wouldn't something like

```cpp
Point<2> p0 {1.0, 1.0};
Point<2> p1 {1.0 + 1.0e-5, 0.0};
```

compare equal with this new scheme?

**Comment by tjhei** [comment]
So that I understand:
1. we still use no epsilon here? (good!)
2. the reason to do this is to make the ordering/sorting robust for the test output?

If yes to both, then good to merge.

Clever way of fixing this!

**Comment by kronbichler** [comment]
@drwells You are right, those two points would compare equal, but it is an unlikely case. Anyway, this limitation is easy to catch: If the distance equals to zero, I will sort back to the old comparison.

@tjhei The answer is yes regarding the robustness of test outputs and partly yes regarding the absence of an epsilon: There is actually an implicit epsilon of `1e-5` used to distinguish coordinate directions but the points are still distinguished in terms of absolute equality.

**Comment by kronbichler** [comment]
I fixed the ambiguous case and added a test for it. Note that there is still the possibility of ambiguity if points are `1e-5` apart compared to the next lower dimension that might interact with roundoff, especially in 3D, (as always with floating point values), but this is the most unlikely case I can think of.

**Comment by tjhei** [comment]
Looks good!

**Pull request merged**
