### PR TITLE
Windows action: archive library only if merged into master

### PR DESCRIPTION
**Pull request by peterrum**
... it gets a bit annoying that hardly any PR passes the full tests on GitHub.

### CODE REVIEW

**Comment by peterrum** [comment]
OK. Upload has been skipped. Let's get this merged and see if the upload happens on "master" (maybe there is no "master" anymore and it is called "main"):

Screenshot from 2022-09-19 22-07-25

**Review by drwells — APPROVED** [review]

**Review by tjhei — APPROVED** [review]
That should work (and no, our branch is still called master not main)

**Comment by peterrum** [comment]
> Is there any reason to keep uploading the whole library (even for the master branch)? I would suggest to get rid of this stage entirely.

ping @luca-heltai

**Comment by peterrum** [comment]
See also https://github.com/dealii/dealii/pull/13656#discussion_r862630492:

> The windows artifact is a full working installation of deal.II, that can be used as a binary installation package. Pretty much like our docker images of the master branch, but for windows. These are used by a few guys around the globe to keep their windows apps up to date.

**Review by marcfehling — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]

**Comment by kronbichler** [comment]
We have four approval, I take this as indication that we should get this merged (and hopefully get rid of the intermittent Windows failures).

**Comment by luca-heltai** [comment]
Yes, sorry I'm late to the party. I agree with this change too. No need to upload the library at each PR.

**Pull request merged**
