### PR TITLE
Small optimization.

### PR DESCRIPTION
**Pull request by simonpuchert**
We can get rid of a scalar*vector operation by restructuring.
This also allows tricks like computing theta/sin(theta) directly from
cos(theta) and thus bypassing the atan2 operation.

### CODE REVIEW

**Comment by masterleinad** [comment]
Hmm... It seems you didn't modify `sinphiSq`, `cosphiSq` and `offdiagonal` accordingly.

The most straightforward fix would probably to multiply `cosphi`and `sinphi` by `sincthetaInv/theta` just before the declaration of `sinphiSq`. However, this implies three more multiplications/divisions (so we would have one more than before) and `cosphi`and `sinphi` can't be `const` anymore.

Do you see a better fix?

**Comment by simonpuchert** [comment]
I think I fixed it with only 1 extra division.

**Comment by masterleinad** [comment]
Yes, that looks good. Thanks!

Would you please also update the output for `grid/project_to_object_01`?

**Comment by bangerth** [comment]
@simonpuchert -- ping?

**Comment by masterleinad** [comment]
I created a PR containing a rebased version of this to @gassmoeller's PR. Once it is merged, we can probably just close this.

**Comment by masterleinad** [comment]
Since this is now included in #5562, let's close.

**Pull request closed without merging**
