### PR TITLE
Fix local second-order coupling in SparseVanka

### PR DESCRIPTION
**Pull request by fsonner**
Fixes issue #2118.

### CODE REVIEW

**Comment by bangerth** [comment]
Remarkable that nobody ever found this over the past 17 or 18 years since that class was written. Good job!

I'm not quite familiar with the algorithm any more. Did you verify that this makes the class a better preconditioner? Or how else did you test that this is the correct change?

**Comment by fsonner** [comment]
The current implementation is a Jacobi-type Vanka iteration, i.e. solving the local subproblems without using the already-computed solution, my change makes it a Gauß-Seidel-type Vanka iteration. I don't have any knowledge of the Vanka iteration as preconditioner, just as multigrid smoother, but there the GS variant is considered superior (apart from the usual issue of parallelization).

**Comment by bangerth** [comment]
Fair enough. Vanka turns out to be a poor preconditioner or solver, actually, but much better as a smoother. But there again, did you test that it's a better smoother now?

**Comment by fsonner** [comment]
Quick test: With one pre- and one post-smoothing step I need 12 (GS) instead of 21 (J) multigrid cycles for Navier-Stokes. It's not a benchmark configuration or anything, but still there is a visible effect in certain situations.

**Comment by bangerth** [comment]
Excellent. Then I'm willing to merge this.

Can you please add an entry into the file `doc/news/changes.h` in the "specific changes" section?

**Pull request merged**
