### PR TITLE
CMake: Bugfix: Do not error out if a variable for a feature constraint is undefined

### PR DESCRIPTION
**Pull request by tamiko**
As it is always the case with the build system - every change is rocky. :-/

### CODE REVIEW

**Comment by bangerth** [comment]
What's the case in point here?

**Comment by tamiko** [comment]
Ah, my text is missing:

In reference to #2805 

This fixes a regression introduced by #2805 - namely the old logic required that the variable
```DEAL_II_WITH_TRILINOS``` that is implicitly used in a constraints like ```.with_trilinos=true``` is
defined.

However, with the new type of constraints ```.with_arpack_with_parpack=true``` the variable ```DEAL_II_ARPACK_WITH_PARPACK``` is not necessarily defined any more.

**Comment by davydden** [comment]
I think it's better to actually fix Arpack's cmake so that it always defines `DEAL_II_ARPACK_WITH_PARPACK`. Just to be feature-proof for other features we may have, that may not necessarily be `false` be default.

**Comment by tamiko** [comment]
@davydden There is nothing to fix in Arpack's or PETSC's configuration here.

The problem is that for a disabled feature we might have some bogus information (like version number, or variables of the form ```FEATURE_WITH_SOMETHING```) left in cmake. I would very much prefer to not export this information to ```deal.IIConfig.cmake```.

Further, the only future proof approach is exactly what is done in this pull request. Imagine that a newer testsuite is configured against an older deal.II library version. If the old one happens to not export all configuration variables used by the newer testsuite the test setup fails.

**Comment by davydden** [comment]
@tamiko ok, agree.

**Comment by tamiko** [comment]
@tjhei The CI stuff is really useful :-]

**Comment by davydden** [comment]
@tamiko is this ready to merge?

**Comment by tamiko** [comment]
@davydden Yes.

**Comment by davydden** [comment]
Since there are no further comments, i merge this.

**Pull request merged**
