### PR TITLE
Fix references.bib

### PR DESCRIPTION
**Pull request by jppelteret**
The period is just on the wrong side of the brace.

### CODE REVIEW

**Review by drwells — APPROVED** [review]

**Comment by drwells** [comment]
Nice catch. I'm surprised we don't get a doxygen warning from this.

**Review by marcfehling — APPROVED** [review]

**Comment by jppelteret** [comment]
The only reason that I spotted this is that this half of this file was rendered in colour by my IDE and the other was grey. Took me a few moments to spot the culprit!

**Comment by marcfehling** [comment]
Do we need that period at all? Doesn't seem to be part of the official title: https://dx.doi.org/10.1023/A:1011591328604

**Comment by marcfehling** [comment]
The extra period will probably manifest as an extra period in the current bibliography, so we would have two periods here https://www.dealii.org/developer/doxygen/deal.II/citelist.html#CITEREF_Riviere1999

I would suggest to get rid of it.

**Comment by jppelteret** [comment]
@marcfehling, thanks for thinking about what the output formatting would look like. You're right that we should get rid of it (it's also not in the official publication title, anyway). I've done this now.

**Review by marcfehling — APPROVED** [review]

**Pull request merged**
