### PR TITLE
FEEval: use get_cell_ids() at more places

### PR DESCRIPTION
**Pull request by peterrum**

### CODE REVIEW

**Comment by drwells** [comment]
I think we can build cleanly now that #13254 is in. Let's see:

/rebuild

**Comment by bangerth** [comment]
You'll have to rebase I think.

**Comment by drwells** [comment]
Rats. I hoped the CI used what was on master, but it does not.

**Review by kronbichler — APPROVED** [review]
Excellent.

**Comment by kronbichler** [comment]
Let's merge now as the only complaint are those unrelated three lines.

**Pull request merged**
