### PR TITLE
Change row_length to return size_type instead of unsigned int.

### PR DESCRIPTION
**Pull request by Rombur**
Following path of #2619

### CODE REVIEW

**Comment by kronbichler** [comment]
In case we change row_length, shouldn't all constructors taking the maximum number of entries per row also be adjusted? (I guess that that might require some work on the unit tests of sparsity patterns.)

I don't see a pressing need for this change now, but making it consistent will definitely not hurt.

**Comment by tjhei** [comment]
As ``rowstart`` is ``size_t``, shouldn't ``row_length`` return a ``size_t`` as well?

**Comment by kronbichler** [comment]
> As rowstart is size_t, shouldn't row_length return a size_t as well?

The row length is the difference between two successive entries in `rowstart`, but the length can never be larger than `size_type` because that is the integer for the number of columns. `std::size_t` is only necessary because the accumulated numbers can exceed the range of `size_type`.

**Comment by bangerth** [comment]
I think the current state is actually ok. The function returns how many nonzero entries there are in a row. Nobody in their right mind would create a matrix with more than 4B entries in a row, even if the matrix has more than 4B columns. So I don't see a pressing need to change the return types of these functions, nor of the constructor and `reinit` arguments.

**Comment by Rombur** [comment]
Since I don't really want to change all the interfaces. I am closing this.

**Pull request closed without merging**
