### PR TITLE
Update Ginkgo cmake detection and tests.

### LINKED ISSUE #10008: Compilation failure with current development version of ginkgo
https://cdash.43-1.org/viewBuildError.php?buildid=5961

### PR DESCRIPTION
**Pull request by pratikvn**
This PR updates and simplifies the CMake detection of Ginkgo with a `find_package(Ginkgo)` so that each of the library modules of Ginkgo do not have to be explicitly found and linked. 

It also updates the iteration counts for the tests as the GMRES algorithm in Ginkgo has been updated.

Things to discuss: Since the previous addition, we have added a few features into Ginkgo, which currently do not have an interface to deal.ii. The important additions relevant to deal.ii are:

1. A HIP Executor for execution on AMD GPUs (v 1.2.0)
2. BiCG solver (v1.2.0)
3. ILU-type preconditioners (v1.2.0)
4. Incomplete Sparse approximate inverse preconditioners (v1.2.0)
5. Permutations and Sparse matrix representations (v1.2.0 and v1.1.0 respectively)

If I add the ability to run on AMD GPUs with the `HipExecutor`, then to make sure that we have backward compatibility with older versions of Ginkgo, I would need to `#if` guard these additions with the Ginkgo version numbers. Is this acceptable for you ? 

This PR supersedes #11393 

Closes #10008

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
Looks good to me.

**Comment by masterleinad** [comment]
> If I add the ability to run on AMD GPUs with the `HipExecutor`, then to make sure that we have backward compatibility with older versions of Ginkgo, I would need to `#if` guard these additions with the Ginkgo version numbers. Is this acceptable for you ?

Sure, that sounds reasonable.

**Review by tamiko — APPROVED** [review]
Looks good!

**Comment by pratikvn** [comment]
Thanks, I think you can go ahead and merge this PR when the tests pass and you are ready. I think I will add the additional wrappers in another PR.

**Comment by tamiko** [comment]
I am sorry, I should have paid more attention to this.

There is a major problem with this pull request. 

We need to sanitize some variables imported from the GINKGO project. In particular:
```
#        DEAL_II_WITH_GINKGO set up with external dependencies
#            GINKGO_CXX_COMPILER = /usr/lib/llvm/10/bin/clang++-10
#            GINKGO_CXX_FLAGS = -march=native -O2 -pipe -fpic -stdlib=libc++ -std=c++14
#            GINKGO_CXX_FLAGS_RELEASE = -O3 -DNDEBUG
#            GINKGO_CXX_FLAGS_DEBUG = -g
#            GINKGO_INCLUDE_DIRS = /usr//include
#            GINKGO_USER_INCLUDE_DIRS = /usr//include
#            GINKGO_LIBRARIES = -L/usr/lib64 -lginkgo -lginkgo_omp -lginkgo_cuda -lginkgo_reference
```
the `GINKGO_CXX_*` variables have to be unset, and in the `DEAL_II_PACKAGE_HANDLE` call it should probably be
`LIBRARIES REQUIRED GINKGO_INTERFACE_LINK_LIBRARIES` instead of `GINKGO_INTERFACE_LINK_FLAGS` so that we correctly record the absolute path of all libraries.

**Comment by tamiko** [comment]
Unfortunately, I encounter a second, bigger issue with this change: After the `find_package(GinkGO)` call CMake is left in an invalid state:
```
-- Include /home/tamiko/workspace/dealii/cmake/configure/configure_2_ginkgo.cmake
--   GINKGO_LIBRARIES: -L/usr/lib64 -lginkgo -lginkgo_omp -lginkgo_cuda -lginkgo_reference
--   GINKGO_INCLUDE_DIRS: /usr//include
--   GINKGO_USER_INCLUDE_DIRS: /usr//include
-- Found GINKGO
-- DEAL_II_WITH_GINKGO successfully set up with external dependencies.
-- 
-- Include /home/tamiko/workspace/dealii/cmake/configure/configure_2_metis.cmake
CMake Warning at cmake/macros/macro_find_package.cmake:27 (_FIND_PACKAGE):
  By not providing "FindMETIS.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "METIS", but
  CMake did not find one.

  Could not find a package configuration file provided by "METIS" with any of
  the following names:

    METISConfig.cmake
    metis-config.cmake

  Add the installation prefix of "METIS" to CMAKE_PREFIX_PATH or set
  "METIS_DIR" to a directory containing one of the above files.  If "METIS"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  cmake/configure/configure_2_metis.cmake:23 (FIND_PACKAGE)
  build/CMakeFiles/CMakeTmp/evaluate_expression.tmp:1 (FEATURE_METIS_FIND_EXTERNAL)
  cmake/macros/macro_evaluate_expression.cmake:30 (INCLUDE)
  cmake/macros/macro_configure_feature.cmake:237 (EVALUATE_EXPRESSION)
  cmake/configure/configure_2_metis.cmake:43 (CONFIGURE_FEATURE)
  cmake/macros/macro_verbose_include.cmake:19 (INCLUDE)
  CMakeLists.txt:124 (VERBOSE_INCLUDE)


-- DEAL_II_WITH_METIS has unmet external dependencies.

[... snip ...]
```
This is due to the following statement in the `Ginkgo/GinkgoConfig.cmake` file:
```
set(CMAKE_MODULE_PATH "${GINKGO_INSTALL_MODULE_DIR}")  
```

This directory doesn't even exist...

**Comment by tamiko** [comment]
I will ressurect this PR and add all necessary modifications.

**Pull request merged**
