### PR TITLE
Initialization of Chebyshev smoother

### PR DESCRIPTION
**Pull request by nfehn**
project vector onto space of vectors with zero mean which is necessary in some cases where the matrix is singular
rename variable is_initialized -> eigenvalues_are_initialized in order to improve code readability

### CODE REVIEW

**Comment by tamiko** [comment]
@nfehn Please add a small entry in `doc/news/changes/minor` (just copy one of the other files as template) so that we can track your contribution.

**Comment by kronbichler** [comment]
@nfehn You also need to adapt the output of the tests
```
tests/matrix_free/parallel_multigrid.with_mpi=true.with_p4est=true.with_trilinos=true.mpirun=3.output
tests/matrix_free/parallel_multigrid.with_mpi=true.with_p4est=true.with_trilinos=true.mpirun=7.output
tests/matrix_free/parallel_multigrid_02.with_mpi=true.with_p4est=true.with_trilinos=true.mpirun=3.output
tests/matrix_free/parallel_multigrid_02.with_mpi=true.with_p4est=true.with_trilinos=true.mpirun=7.output
```
You can run the tests as described here: http://dealii.org/developer/developers/testsuite.html#run (check sections 1 to 3).

**Comment by masterleinad** [comment]
@nfehn Would you mind to adjust the output of the failing tests (https://github.com/dealii/dealii/pull/4458#issuecomment-306512058) as well?

**Comment by kronbichler** [comment]
This looks good now. Thanks for adjusting the output.

**Pull request merged**
