### PR TITLE
Remove references to hp::DoFHandler in DoFAccessor.

### PR DESCRIPTION
**Pull request by drwells**
Obviously this won't work until we merge #10328 but I fixed these while looking at another part of that PR.

### CODE REVIEW

**Comment by peterrum** [comment]
Thanks!

**Comment by bangerth** [comment]
The documentation components of it, at least. The rest of course doesn't compile right now.

**Comment by drwells** [comment]
That's probably worthwhile just so that the PR doesn't get stale. I will excise the non-documentation changes.

**Comment by drwells** [comment]
Done!

**Comment by drwells** [comment]
our documentation is so up-to-date that it now refers to future implementations :)

**Pull request merged**
