### PR TITLE
Remove make slice

### LINKED ISSUE #7794: Debug error on MSVC
Hi,
I'm using Win 10 and Visual Studio 2017 (15.9). I replaced the file step.cc of project step.debug with step-2.cc of example 2.

While debugging, an error box poped up that reads:

```
Debug Assertion Failed!
Program:

...alii-master\buildDebug\tests\quick_tests\Debug\step.debug.exe File: D:\Program Files (x86)\Microsoft Visual

Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vector Line: 50

Expression: can't dereference value-initialized vector iterator

For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts.
(Press Retry to debug the application)
```
I retried, and the information below was displayed by call stack window:

```
step.debug.exe!std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > >::operator*() Line 50
	at d:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\vector(50)
step.debug.exe!dealii::make_array_view<std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > >,dealii::MemorySpace::Host>(const std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > > begin, const std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > > end) Line 561
	at l:\dealii-master901\dealii-master\include\deal.ii\base\array_view.h(561)
step.debug.exe!dealii::VectorSlice<std::vector<unsigned int,std::allocator<unsigned int> > const >::VectorSlice<std::vector<unsigned int,std::allocator<unsigned int> > const >(const std::vector<unsigned int,std::allocator<unsigned int> > & v) Line 121
	at l:\dealii-master901\dealii-master\include\deal.ii\base\vector_slice.h(121)
step.debug.exe!dealii::make_slice<std::vector<unsigned int,std::allocator<unsigned int> > const >(const std::vector<unsigned int,std::allocator<unsigned int> > & v) Line 94
	at l:\dealii-master901\dealii-master\include\deal.ii\base\vector_slice.h(94)
step.debug.exe!dealii::SparsityPattern::reinit(const unsigned int m, const unsigned int n, const std::vector<unsigned int,std::allocator<unsigned int> > & row_lengths) Line 608
	at l:\dealii-master901\dealii-master\source\lac\sparsity_pattern.cc(608)
step.debug.exe!dealii::SparsityPattern::reinit(const unsigned int m, const unsigned int n, const unsigned int max_per_row) Line 237
	at l:\dealii-master901\dealii-master\source\lac\sparsity_pattern.cc(237)
step.debug.exe!dealii::SparsityPattern::SparsityPattern() Line 50
	at l:\dealii-master901\dealii-master\source\lac\sparsity_pattern.cc(50)
step.debug.exe!LaplaceProblem<2>::LaplaceProblem<2>(const unsigned int mapping_degree) Line 95
	at l:\dealii-master901\dealii-master\tests\quick_tests\step.cc(95)
step.debug.exe!main() Line 235
	at l:\dealii-master901\dealii-master\tests\quick_tests\step.cc(235)

```
Here is the conetent of config.h.

```
#ifndef dealii_config_h
#define dealii_config_h


/***********************************************************************
 * Information about deal.II:
 */

#define DEAL_II_PACKAGE_NAME "deal.II"

#define DEAL_II_PACKAGE_VERSION "9.1.0-pre"

#define DEAL_II_VERSION_MAJOR 9
#define DEAL_II_VERSION_MINOR 1
#define DEAL_II_VERSION_SUBMINOR 0


/***********************************************************************
 * Configured deal.II features:
 */

/* #undef DEAL_II_WITH_64BIT_INDICES */
/* #undef DEAL_II_WITH_ADOLC */
/* #undef DEAL_II_WITH_ARPACK */
/* #undef DEAL_II_WITH_ASSIMP */
#define DEAL_II_WITH_COMPLEX_VALUES
/* #undef DEAL_II_WITH_CUDA */
/* #undef DEAL_II_WITH_CUDA_AWARE_MPI */
#define DEAL_II_WITH_CXX14
/* #undef DEAL_II_WITH_CXX17 */
/* #undef DEAL_II_WITH_GINKGO */
/* #undef DEAL_II_WITH_GSL */
/* #undef DEAL_II_WITH_GMSH */
/* #undef DEAL_II_WITH_HDF5 */
/* #undef DEAL_II_WITH_LAPACK */
/* #undef LAPACK_WITH_64BIT_BLAS_INDICES */
/* #undef DEAL_II_LAPACK_WITH_MKL */
/* #undef DEAL_II_WITH_METIS */
/* #undef DEAL_II_WITH_MPI */
#define DEAL_II_WITH_MUPARSER
/* #undef DEAL_II_WITH_NANOFLANN */
/* #undef DEAL_II_WITH_NETCDF */
/* #undef DEAL_II_WITH_OPENCASCADE */
/* #undef DEAL_II_WITH_P4EST */
/* #undef DEAL_II_WITH_PETSC */
/* #undef DEAL_II_WITH_SCALAPACK */
/* #undef DEAL_II_WITH_SLEPC */
/* #undef DEAL_II_WITH_SUNDIALS */
/* #undef DEAL_II_WITH_THREADS */
/* #undef DEAL_II_WITH_TRILINOS */
/* #undef DEAL_II_WITH_UMFPACK */
/* #undef DEAL_II_WITH_ZLIB */

// defined for backwards compatibility with pre-C++11
#define DEAL_II_WITH_CXX11
#define DEAL_II_NOEXCEPT noexcept

/***********************************************************************
 * Compiler bugs:
 *
 * For documentation see cmake/checks/check_03_compiler_bugs.cmake
 */

/* #undef DEAL_II_TEMPL_SPEC_FRIEND_BUG */
#define DEAL_II_MEMBER_ARRAY_SPECIALIZATION_BUG
/* #undef DEAL_II_CONST_MEMBER_DEDUCTION_BUG */
/* #undef DEAL_II_BIND_NO_CONST_OP_PARENTHESES */
#define DEAL_II_CONSTEXPR_BUG


/***********************************************************************
 * Compiler features:
 *
 * For documentation see cmake/checks/check_01_compiler_features.cmake
 */

/* #undef DEAL_II_COMPILER_USE_VECTOR_ARITHMETICS */
/* #undef DEAL_II_VECTOR_ITERATOR_IS_POINTER */
/* #undef DEAL_II_HAVE_BUILTIN_EXPECT */
/* #undef DEAL_II_HAVE_GLIBC_STACKTRACE */
/* #undef DEAL_II_HAVE_LIBSTDCXX_DEMANGLER */
#define __PRETTY_FUNCTION__ __func__
#define DEAL_II_DEPRECATED  
#define DEAL_II_ALWAYS_INLINE  
#define DEAL_II_RESTRICT __restrict
/* #undef DEAL_II_COMPILER_HAS_DIAGNOSTIC_PRAGMA */

/*
 * A variable to tell if the compiler used in the current compilation process
 * understands CUDA code.
 */
#if defined(DEAL_II_WITH_CUDA) && defined(__CUDACC__)
#  define DEAL_II_COMPILER_CUDA_AWARE
#endif

/***********************************************************************
 * CPU features:
 *
 * For documentation see cmake/checks/check_01_cpu_features.cmake
 */

/* #undef DEAL_II_WORDS_BIGENDIAN */
// We need to disable SIMD vectorization for CUDA device code.
// Otherwise, nvcc compilers from version 9 on will emit an error message like:
// "[...] contains a vector, which is not supported in device code"
#ifdef __CUDA_ARCH__
#  define DEAL_II_COMPILER_VECTORIZATION_LEVEL 0
#else
#  define DEAL_II_COMPILER_VECTORIZATION_LEVEL 1
#endif
#define DEAL_II_OPENMP_SIMD_PRAGMA  


/***********************************************************************
 * Language features:
 *
 * For documentation see cmake/checks/check_01_cxx_features.cmake
 */

#define DEAL_II_HAVE_CXX11_IS_TRIVIALLY_COPYABLE
#define DEAL_II_HAVE_CXX14_CONSTEXPR_CAN_CALL_NONCONSTEXPR
/* #undef DEAL_II_HAVE_CXX17_SPECIAL_MATH_FUNCTIONS */
/* #undef DEAL_II_HAVE_FP_EXCEPTIONS */
/* #undef DEAL_II_HAVE_COMPLEX_OPERATOR_OVERLOADS */
#define DEAL_II_FALLTHROUGH  


/***********************************************************************
 * System features:
 *
 * For documentation see cmake/checks/check_02_system_features.cmake
 */

/* #undef DEAL_II_HAVE_SYS_RESOURCE_H */
/* #undef DEAL_II_HAVE_UNISTD_H */
/* #undef DEAL_II_HAVE_GETHOSTNAME */
/* #undef DEAL_II_HAVE_GETPID */
/* #undef DEAL_II_HAVE_JN */

#define DEAL_II_MSVC


/***********************************************************************
 * Feature configuration
 *
 * For documentation see cmake/configure/configure_*.cmake and
 * cmake/modules/Find*.cmake
 */

/* cmake/modules/FindADOLC.cmake */
/* #undef DEAL_II_ADOLC_WITH_ATRIG_ERF */
/* #undef DEAL_II_ADOLC_WITH_ADVANCED_BRANCHING */
/* #undef DEAL_II_ADOLC_WITH_TAPELESS_REFCOUNTING */

/* cmake/modules/FindARPACK.cmake */
/* #undef DEAL_II_ARPACK_WITH_PARPACK */

/* cmake/modules/FindPETSC.cmake */
/* #undef DEAL_II_PETSC_WITH_HYPRE */
/* #undef DEAL_II_PETSC_WITH_MUMPS */

/* cmake/modules/FindSUNDIALS.cmake */
/* #undef DEAL_II_SUNDIALS_WITH_IDAS */

/* cmake/configure/configure_1_threads.cmake */
/* #undef DEAL_II_USE_MT_POSIX */
/* #undef DEAL_II_USE_MT_POSIX_NO_BARRIERS */

/* cmake/configure/configure_2_trilinos.cmake */
/* #undef DEAL_II_TRILINOS_CXX_SUPPORTS_SACADO_COMPLEX_RAD */
/* #undef DEAL_II_TRILINOS_WITH_EPETRAEXT */
/* #undef DEAL_II_TRILINOS_WITH_ROL */
/* #undef DEAL_II_TRILINOS_WITH_SACADO */
/* #undef DEAL_II_TRILINOS_WITH_TPETRA */
/* #undef DEAL_II_TRILINOS_WITH_ZOLTAN */


/***********************************************************************
 * Various macros for version number query and comparison:
 *
 * These macros are defined to make testing for specific versions within
 * the deal.II main code as simple as possible.
 */

/*
 * deal.II:
 */

#define DEAL_II_VERSION_GTE(major,minor,subminor) \
 ((DEAL_II_VERSION_MAJOR * 10000 + \
    DEAL_II_VERSION_MINOR * 100 + \
     DEAL_II_VERSION_SUBMINOR) \
    >=  \
    (major)*10000 + (minor)*100 + (subminor))


/*
 * Gmsh:
 */
#ifdef DEAL_II_WITH_GMSH
#  define DEAL_II_GMSH_EXECUTABLE_PATH ""
#endif

/*
 * p4est:
 */

#ifdef DEAL_II_WITH_P4EST
#  define DEAL_II_P4EST_VERSION_MAJOR 
#  define DEAL_II_P4EST_VERSION_MINOR 
#  define DEAL_II_P4EST_VERSION_SUBMINOR 
#  define DEAL_II_P4EST_VERSION_PATCH 

#  define DEAL_II_P4EST_VERSION_GTE(major,minor,subminor,patch) \
 ((DEAL_II_P4EST_VERSION_MAJOR * 1000000 + \
    DEAL_II_P4EST_VERSION_MINOR * 10000 + \
     DEAL_II_P4EST_VERSION_SUBMINOR * 100 + \
      DEAL_II_P4EST_VERSION_PATCH) \
    >=  \
    (major)*1000000 + (minor)*10000 + (subminor)*100 + (patch))
#else
  // p4est up to 0.3.4.1 didn't define P4EST_VERSION_*. since
  // we didn't supports anything before 0.3.4, we assume 0.3.4
  // This means that we can't use the new features in 0.3.4.1
#  define DEAL_II_P4EST_VERSION_GTE(major,minor,subminor,patch) \
  ((0 * 1000000 + \
    3 * 10000 + \
    4 * 100 + \
    0) \
    >=  \
    (major)*1000000 + (minor)*10000 + (subminor)*100 + (patch))
#endif

/*
 * SUNDIALS:
 */

#ifdef DEAL_II_WITH_SUNDIALS
 #  define DEAL_II_SUNDIALS_VERSION_MAJOR 
 #  define DEAL_II_SUNDIALS_VERSION_MINOR 
 #  define DEAL_II_SUNDIALS_VERSION_PATCH 

 #define DEAL_II_SUNDIALS_VERSION_GTE(major,minor,patch) \
   ((DEAL_II_SUNDIALS_VERSION_MAJOR * 10000 + \
     DEAL_II_SUNDIALS_VERSION_MINOR * 100 + \
     DEAL_II_SUNDIALS_VERSION_PATCH) \
     >=  \
     (major)*10000 + (minor)*100 + (patch))

 #define DEAL_II_SUNDIALS_VERSION_LT(major,minor,patch) \
   ((DEAL_II_SUNDIALS_VERSION_MAJOR * 10000 + \
     DEAL_II_SUNDIALS_VERSION_MINOR * 100 + \
     DEAL_II_SUNDIALS_VERSION_PATCH) \
     <  \
     (major)*10000 + (minor)*100 + (patch))
#endif

/*
 * PETSc:
 *
 * Note: The following definitions will be set in petscconf.h and
 *       petscversion.h, so we don't repeat them here.
 *
 *  PETSC_VERSION_MAJOR
 *  PETSC_VERSION_MINOR
 *  PETSC_VERSION_SUBMINOR
 *  PETSC_VERSION_PATCH
 *  PETSC_VERSION_RELEASE
 *  PETSC_USE_COMPLEX
 */

#define DEAL_II_PETSC_VERSION_LT(major,minor,subminor) \
  ((PETSC_VERSION_MAJOR * 10000 + \
    PETSC_VERSION_MINOR * 100 + \
    PETSC_VERSION_SUBMINOR) \
    <  \
    (major)*10000 + (minor)*100 + (subminor))

#define DEAL_II_PETSC_VERSION_GTE(major,minor,subminor) \
  ((PETSC_VERSION_MAJOR * 10000 + \
    PETSC_VERSION_MINOR * 100 + \
    PETSC_VERSION_SUBMINOR) \
    >=  \
    (major)*10000 + (minor)*100 + (subminor))

/*
 * SLEPC
 * see slepcversion.h
 */
#define DEAL_II_SLEPC_VERSION_GTE(major,minor,subminor) \
  ((SLEPC_VERSION_MAJOR * 10000 + \
    SLEPC_VERSION_MINOR * 100 + \
    SLEPC_VERSION_SUBMINOR) \
    >=  \
    (major)*10000 + (minor)*100 + (subminor))

/*
 * Trilinos:
 */

#ifdef DEAL_II_WITH_TRILINOS
#  define DEAL_II_TRILINOS_VERSION_MAJOR 
#  define DEAL_II_TRILINOS_VERSION_MINOR 
#  define DEAL_II_TRILINOS_VERSION_SUBMINOR 

#  define DEAL_II_TRILINOS_VERSION_GTE(major,minor,subminor) \
 ((DEAL_II_TRILINOS_VERSION_MAJOR * 10000 + \
    DEAL_II_TRILINOS_VERSION_MINOR * 100 + \
      DEAL_II_TRILINOS_VERSION_SUBMINOR) \
    >=  \
    (major)*10000 + (minor)*100 + (subminor))
#endif

/*
 * MPI
 */

#ifdef DEAL_II_WITH_MPI
#  define DEAL_II_MPI_VERSION_MAJOR 
#  define DEAL_II_MPI_VERSION_MINOR 

#  define DEAL_II_MPI_VERSION_GTE(major,minor) \
 ((DEAL_II_MPI_VERSION_MAJOR * 100 + \
    DEAL_II_MPI_VERSION_MINOR) \
    >=  \
    (major)*100 + (minor))
#endif

/***********************************************************************
 * Two macro names that we put at the top and bottom of all deal.II files
 * and that will be expanded to "namespace dealii {" and "}".
 */

#define DEAL_II_NAMESPACE_OPEN namespace dealii {
#define DEAL_II_NAMESPACE_CLOSE }

/***********************************************************************
 * Two macros to guard external header includes.
 *
 * Selectively disable diagnostics set by "-Wextra" (and similar flags) for
 * GCC and compiler accepting GCC dialects (such as clang).
 * "diagnostic push" is supported since gcc-4.6 and clang-3.3.
 */

#ifdef DEAL_II_COMPILER_HAS_DIAGNOSTIC_PRAGMA

/* keep pragmas with an exclamation mark in order.. */
#  define DEAL_II_DISABLE_EXTRA_DIAGNOSTICS                             \
_Pragma("GCC diagnostic push")                                    /*!*/ \
_Pragma("GCC diagnostic ignored \"-Wunknown-pragmas\"")           /*!*/ \
_Pragma("GCC diagnostic ignored \"-Wpragmas\"")                   /*!*/ \
_Pragma("GCC diagnostic ignored \"-Wunknown-warning-option\"")    /*!*/ \
_Pragma("GCC diagnostic ignored \"-Wunknown-warning\"")           /*!*/ \
_Pragma("GCC diagnostic ignored \"-Wextra\"")                     /*!*/ \
_Pragma("GCC diagnostic ignored \"-Waddress-of-packed-member\"")        \
_Pragma("GCC diagnostic ignored \"-Wdeprecated-declarations\"")         \
_Pragma("GCC diagnostic ignored \"-Wexpansion-to-defined\"")            \
_Pragma("GCC diagnostic ignored \"-Wexpansion-to-defined\"")            \
_Pragma("GCC diagnostic ignored \"-Wignored-attributes\"")              \
_Pragma("GCC diagnostic ignored \"-Wignored-qualifiers\"")              \
_Pragma("GCC diagnostic ignored \"-Wimplicit-fallthrough\"")            \
_Pragma("GCC diagnostic ignored \"-Winfinite-recursion\"")              \
_Pragma("GCC diagnostic ignored \"-Wint-in-bool-context\"")             \
_Pragma("GCC diagnostic ignored \"-Wmisleading-indentation\"")          \
_Pragma("GCC diagnostic ignored \"-Wmissing-field-initializers\"")      \
_Pragma("GCC diagnostic ignored \"-Wnested-anon-types\"")               \
_Pragma("GCC diagnostic ignored \"-Wnon-virtual-dtor\"")                \
_Pragma("GCC diagnostic ignored \"-Woverflow\"")                        \
_Pragma("GCC diagnostic ignored \"-Woverloaded-virtual\"")              \
_Pragma("GCC diagnostic ignored \"-Wpedantic\"")                        \
_Pragma("GCC diagnostic ignored \"-Wtautological-constant-out-of-range-compare\"") \
_Pragma("GCC diagnostic ignored \"-Wtype-limits\"")                     \
_Pragma("GCC diagnostic ignored \"-Wundef\"")                           \
_Pragma("GCC diagnostic ignored \"-Wunused-but-set-parameter\"")        \
_Pragma("GCC diagnostic ignored \"-Wunused-but-set-variable\"")         \
_Pragma("GCC diagnostic ignored \"-Wunused-function\"")                 \
_Pragma("GCC diagnostic ignored \"-Wunused-parameter\"")                \
_Pragma("GCC diagnostic ignored \"-Wunused-private-field\"")            \
_Pragma("GCC diagnostic ignored \"-Wunused-variable\"")                 \
_Pragma("GCC diagnostic warning \"-Wpragmas\"")                   /*!*/

#  define DEAL_II_ENABLE_EXTRA_DIAGNOSTICS                              \
_Pragma("GCC diagnostic pop")

#else

#  define DEAL_II_DISABLE_EXTRA_DIAGNOSTICS
#  define DEAL_II_ENABLE_EXTRA_DIAGNOSTICS

#endif

/***********************************************************************
 * Define a portable preprocessor macro that generates custom warnings
 * reporting the line and the file where the warning appears. Taken from:
 * http://goodliffe.blogspot.com/2009/07/c-how-to-say-warning-to-visual-studio-c.html
 */

#ifdef _MSC_VER
  #define DEAL_II_STRINGIZE_HELPER(x) #x
  #define DEAL_II_STRINGIZE(x) DEAL_II_STRINGIZE_HELPER(x)
  #define DEAL_II_DO_PRAGMA(x) __pragma(x)
  #define DEAL_II_WARNING(desc) DEAL_II_DO_PRAGMA(message(__FILE__ "(" DEAL_II_STRINGIZE(__LINE__) ") : warning: " #desc))
#else
  #define DEAL_II_DO_PRAGMA(x) _Pragma(#x)
  #define DEAL_II_WARNING(desc) DEAL_II_DO_PRAGMA(message(#desc))
#endif

/***********************************************************************
 * Final inclusions:
 */

/*
 * Some systems require including mpi.h before stdio.h which happens in
 * types.h
 */
#if defined(DEAL_II_WITH_MPI) || defined(DEAL_II_WITH_PETSC)
#  include <mpi.h>
#endif

#include <deal.II/base/numbers.h>
#include <deal.II/base/types.h>

#endif
```

And so I created this issue.

### PR DESCRIPTION
**Pull request by drwells**
Possibly fixes #7794: MSVC apparently encounters an error when converting a `VectorSlice` temporary into an `ArrayView` temporary. I suspect, though I do not have a Windows machine handy, that we can fix this by completely removing all intermediate `VectorSlice` constructors.

### CODE REVIEW

**Comment by drwells** [comment]
The tester doesn't seem to have found my comment. Lets try this again:

/rebuild

**Comment by masterleinad** [comment]
Some tests are missing header files: https://jenkins.tjhei.info/blue/organizations/jenkins/dealii/detail/PR-7798/3/tests

**Comment by qwebean** [comment]
I have rebuilt the whole solution.
The patch doesn't not work.
Still the same problem appears.

> step.debug.exe!dealii::make_array_view<std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > >,dealii::MemorySpace::Host>(const std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > > begin, const std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > > end) Line 555
> 	at l:\dealii-master901\dealii-master\include\deal.ii\base\array_view.h(555)
> step.debug.exe!dealii::VectorSlice<std::vector<unsigned int,std::allocator<unsigned int> > const >::VectorSlice<std::vector<unsigned int,std::allocator<unsigned int> > const >(const std::vector<unsigned int,std::allocator<unsigned int> > & v) Line 121
> 	at l:\dealii-master901\dealii-master\include\deal.ii\base\vector_slice.h(121)
> step.debug.exe!dealii::make_slice<std::vector<unsigned int,std::allocator<unsigned int> > const >(const std::vector<unsigned int,std::allocator<unsigned int> > & v) Line 94
> 	at l:\dealii-master901\dealii-master\include\deal.ii\base\vector_slice.h(94)
> step.debug.exe!dealii::SparsityPattern::reinit(const unsigned int m, const unsigned int n, const std::vector<unsigned int,std::allocator<unsigned int> > & row_lengths) Line 608
> 	at l:\dealii-master901\dealii-master\source\lac\sparsity_pattern.cc(608)

Here are the values while the program pauses execution here.

> array_view.h(555)

 It seems that the pointers of begin and end
are not initialized. I guess this is the point. 


  | Name | Value | Type
-- | -- | -- | --
◢ | begin | {???} | const std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > >
  | ◢ [ptr] | 0x0000000000000000 {???} | unsigned int *
  |   | <Unable to read memory> | unsigned int
  | ◢ [Raw View] | {_Ptr=0x0000000000000000 {???} } | const std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > >
  | ◢ std::_Iterator_base12 | {_Myproxy=0x000002283057c770 {_Mycont=0x000000b7a9afe2d0 {_Myproxy=0x000002283057c770 {_Mycont=0x000000b7a9afe2d0 {...} ...} } ...} ...} | std::_Iterator_base12
  | ▶ _Myproxy | 0x000002283057c770 {_Mycont=0x000000b7a9afe2d0 {_Myproxy=0x000002283057c770 {_Mycont=0x000000b7a9afe2d0 {...} ...} } ...} | std::_Container_proxy *
  | ◢ _Mynextiter | 0x000000b7a9afe1d0 {_Myproxy=0x000002283057c770 {_Mycont=0x000000b7a9afe2d0 {_Myproxy=0x000002283057c770 {...} } ...} ...} | std::_Iterator_base12 *
  | ▶ _Myproxy | 0x000002283057c770 {_Mycont=0x000000b7a9afe2d0 {_Myproxy=0x000002283057c770 {_Mycont=0x000000b7a9afe2d0 {...} ...} } ...} | std::_Container_proxy *
  | ▶ _Mynextiter | 0x0000000000000000 <NULL> | std::_Iterator_base12 *
  | ◢ _Ptr | 0x0000000000000000 {???} | unsigned int *
  |   | <Unable to read memory> | unsigned int
◢ | end | {???} | const std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > >
  | ◢ [ptr] | 0x0000000000000000 {???} | unsigned int *
  |   | <Unable to read memory> | unsigned int
  | ▶ [Raw View] | {_Ptr=0x0000000000000000 {???} } | const std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned int> > >

**Comment by drwells** [comment]
Fixed.

**Pull request merged**
