### PR TITLE
add distribute_local_to_global of diagonal entries to a vector

### PR DESCRIPTION
**Pull request by davydden**
in reference to https://github.com/dealii/dealii/pull/3184#issuecomment-252429781

The idea is to make `distribute_local_to_global()` distribute local matrix with applied constraints to a vector of diagonal elements.

Current solution is not the most beutifull as I had to distinguish between
```
template <typename MatrixType>
  void
  distribute_local_to_global (const FullMatrix<typename MatrixType::value_type> &local_matrix,
                              const std::vector<size_type> &local_dof_indices,
                              MatrixType                   &global_matrix) const;
```
and
```
template <typename VectorType>
  void
  distribute_local_to_global (VectorType                   &global_diagonal_vector,
                              const FullMatrix<typename VectorType::value_type> &local_matrix,
                              const std::vector<size_type> &local_dof_indices) const;
```
by changing arguments order. There is also quite  a lot of code duplication.

I think the better approach is just enhance vector class to have a function similar to matrix classes (i.e. https://www.dealii.org/developer/doxygen/deal.II/classSparseMatrix.html#ac97efa0f970b0bcf40da82584f71d39c) 
```
VectorClass:add	(	const size_type 	row,
const size_type 	n_cols,
const size_type * 	col_indices,
const number2 * 	values,
const bool 	elide_zero_values = true,
const bool 	col_indices_are_sorted = false 
)	
```
and then take diagonals only. This way everything should work out-of-the-box. Thoughts?

TODO
- [ ] check test

### CODE REVIEW

**Comment by kronbichler** [comment]
@davydden I would definitely prefer to go through the existing code path for the diagonal matrix and not introduce a version with switched arguments. That can only lead to confusion. However, I do not like to equip the general vector classes with an `add()` function that is tailored for matrices as that would lead to some confusion in various contexts as well. The best alternative as I see it would be to create a new `DiagonalMatrix` class that only provides a selection of methods and skips all entries that are not going to the diagonal. One could put a template on the vector type for that matrix and then instantiate the `ConstraintMatrix` methods with the respective matrix classes as well. It should be rather compact to do that.

On the other hand, I am not entirely sure about the overall picture: What are our needs regarding creating matrix diagonals by the vector assembly routines? The matrix-free code path is along this trajectory but I am not sure how much of a difference it would make to get the diagonal slightly wrong as we do it right now. The geometric multigrid paths would not be affected because you never smooth on a mesh with hanging nodes. Our multigrid toolchain does local smoothing that smooths within a level only, possibly ignoring parts of the domain where no cell of a certain level appears due to adaptivity, as opposed to global coarsening where you take an adaptively refined mesh and coarsen *all* cells by one level, giving hanging nodes also on coarser levels and requiring to smooth over hanging nodes. Unless we implement the global coarsening, I see no need for better "diagonals". I can't imagine it changes any iteration counts on simple Jacobi-preconditioned systems. Jacobi on Laplace will be bad anyway, and on a mass matrix the approximation given by the vector version of `distribute_local_to_global` is a convergent mass matrix approximation and thus likely to be within 1-2 iterations in all cases.

**Comment by davydden** [comment]
> DiagonalMatrix class that only provides a selection of methods and skips all entries that are not going to the diagonal. One could put a template on the vector type for that matrix and then instantiate the ConstraintMatrix methods with the respective matrix classes as well. It should be rather compact to do that.

That's certainly an option which is much cleaner than the current version.

> The matrix-free code path is along this trajectory but I am not sure how much of a difference it would make to get the diagonal slightly wrong as we do it right now... The geometric multigrid paths would not be affected because you never smooth on a mesh with hanging nodes.

Fair comment, i did not take this into account.

It looks like we will see a difference only if one combines MatrixFree and preconditioners based on diagonals without multigrid. Frankly i don't have any application in mind where one would need that.

Let's see what others have to say, but I am perfectly fine to closet his PR.

**Comment by tjhei** [comment]
> What are our needs regarding creating matrix diagonals by the vector assembly routines?

It might be useful if you want the normal matrix and the diagonal separately, I guess?

**Comment by davydden** [comment]
@kronbichler : do you mind copy-pasting your comment on GMG+Matrix-free from the above to `assemble_multigrid` section in `Step-37` tutorial? :smile: I know that this one is global refinement only, but i think it would be nice to have a small note for users.

**Comment by kronbichler** [comment]
@davydden I opened the new issue #3222 to keep track of it. I want to do it with the general re-design of step-37.

**Comment by kronbichler** [comment]
@tjhei That's a fair point. Should we then try to add a minimal matrix interface to a matrix constructed from a vector with a template on the vector class? We could even think of re-designing the Chebyshev smoother to take a general `Preconditioner` operator as an argument. Besides offering the possibility to move the code more closely to a common smoother interface as discussed in #3184, this will also allow to use Chebyshev with something else than Jacobi, say block-Jacobi in DG methods. (I've already tested such methods and they are quite nice in some contexts.)

**Comment by tjhei** [comment]
> @tjhei That's a fair point. Should we then try to add a minimal matrix interface to a matrix constructed from a vector with a template on the vector class

I agree that a DiagonalMatrix would be the way to go. But if nobody needs it right now, I think we shouldn't bother implementing it. I was also thinking that you might do different variants of this: lumping entries, only taking the diagonal, or something similar.

**Comment by bangerth** [comment]
FWIW, I also agree that representing a diagonal matrix with a vector is a poor idea. If we need a diagonal matrix, let's have a class whose name and interface reflects that.

**Comment by davydden** [comment]
i am closing this PR in favour of the issue https://github.com/dealii/dealii/issues/3223 to continue the discussion.

**Pull request closed without merging**
