### PR TITLE
cppcheck: avoid an unused variable

### PR DESCRIPTION
**Pull request by tamiko**
In reference to #8080

### CODE REVIEW

**Comment by drwells** [comment]
I am a bit disturbed that my copy of cppcheck didn't find this. What version are you using?

**Comment by tamiko** [comment]
```
[I] dev-util/cppcheck
     Available versions:  1.86 (**)9999{tbz2} {htmlreport pcre qt5 PYTHON_TARGETS="python2_7 python3_5 python3_6"}
     Installed versions:  9999{tbz2}(12:01:24 PM 03/24/2019)(pcre qt5 -htmlreport PYTHON_TARGETS="python2_7 python3_5 python3_6")
     Homepage:            https://github.com/danmar/cppcheck
     Description:         Static analyzer of C/C++ code
```

Git checkout from March.

**Comment by drwells** [comment]
Hm. And how did you invoke it?

**Comment by tamiko** [comment]
@drwells 
```
cppcheck --force -j4 --enable=all -I./include/ ./source/*/*.cc >cppcheck-results.txt 2>&1
```

**Pull request merged**
