### PR TITLE
Use exceptions to mark Q1 transform failures.

### PR DESCRIPTION
**Pull request by drwells**
This is a response to the discussion in #1465: There are multiple ways to do signal transform failure, but the other parts throw an exception, so this makes things consistent.

### CODE REVIEW

**Comment by tjhei** [comment]
I didn't quite get the conclusion of the discussion: why are you going with exceptions now after you have shown that it is slower? In my opinion there is no point in arguing about a pretty function interface of an internal function. You could return a boost:optional, a pair, NaN in the coordinates, etc..

**Comment by drwells** [comment]
I can redo it with special return values (some sort of tuple) if that is your preference (that is also an improvement over what I originally wrote), but I think this approach is better because it makes the handling of failed real to unit transformations uniform (i.e., different parts handle failure the same way: exceptions).

Here is my back of the envelope calculation: the new code path is about `3000%` faster and exceptions create a `10%` speed penalty. Therefore with exceptions the new code path is `2700%` faster. I do not think this function was ever a bottle neck anyway, so in my opinion the 'prettier' version should be chosen.

**Comment by drwells** [comment]
Actually, on second thought: it looks like @bangerth and @luca-heltai are about to remove `MappingQ1` anyway, so this question probably won't be relevant after that is done. We should probably address this after that happens.

**Comment by bangerth** [comment]
Au contraire. The class may go away, but the code will remain: I plan to continue treating p=1 as a special case in whatever class will survive. So please continue with this (or let us know if you'd like to stick with the patch -- in which case I'd gladly let @tjhei handle the matter).

**Comment by drwells** [comment]
Oh, I have to see these exact formulae through to the bitter end at this point (I think I started this whole thing nearly two months ago). I do not mind rehashing this PR at some point in the future.

My concern is that the exception handling logic resides in the innards of `MappingQ1`, which might not exist in the near future.

**Comment by bangerth** [comment]
I think the code currently is still in mapping_q1.cc. I would say go ahead with the assumption that that's where it will remain for now and I will just deal with the consequences when I get around to moving it.

**Comment by tjhei** [comment]
Well, then let us go ahead with this as it. It looks good to me.

**Pull request merged**
