### PR TITLE
SparsityTools::reorder_Cuthill_McKee: Fix criterion for inner loop

### PR DESCRIPTION
**Pull request by kronbichler**
This might be a possibly controversial patch because it will likely break many tests (I did not check all, but I saw more than a dozen already locally on a selection of tests), that I did not yet touch at this stage.

To summarize this change, let me quote what Wikipedia says about the Cuthill-McKee ordering, see also https://en.wikipedia.org/wiki/Cuthill%E2%80%93McKee_algorithm:
Screenshot From 2024-11-01 20-53-15

Note the second part, which says that we should sort `A_i` by the minimum predecessor, and as a tiebreak ascending by vertex degree. Yet, when I looked at the original implementation we actually sort `A_i` by minimum vertex degree, and only then use the predecessor as a tie-break. I noticed that I got relatively high distances within a set `A_i`, and I believe this is the reason.

Of course, one has to wonder what this means to the quality of the ordering in general. I did not extensively test this yet, as I wanted to put this up for discussion first: We might have reasons not to follow the conventional form, or I might interpret the text in the wrong way. So any comments are welcome. If we believe we want this form, I will look at all the tests, and update the PR.

### CODE REVIEW

**Comment by bangerth** [comment]
I was hoping to see how many tests you managed to break, but you got saved by a compiler warning that ended compilation :-)
```
/__w/dealii/dealii/source/lac/sparsity_tools.cc:660:29: error: loop variable ‘dof’ creates a copy from type ‘const std::pair<unsigned int, unsigned int>’ [-Werror=range-loop-construct]
  660 |             for (const auto dof : dofs_by_coordination)
      |                             ^~~
/__w/dealii/dealii/source/lac/sparsity_tools.cc:660:29: note: use reference type to prevent copying
  660 |             for (const auto dof : dofs_by_coordination)
      |                             ^~~
      |                             &
```

**Comment by bangerth** [comment]
Separately, though: I think I implemented that function in around 1998, from a book about the finite element method that I only have in the office. I might either have gotten it wrong, or the book actually had the algorithm as implemented. Either way, I have no objections to changing things though I wonder whether it's worth it -- we don't use the function very much, and so I'm not sure if the pain is worth it. What made you look into it? In other words, what's the application where you care about it enough?

**Comment by kronbichler** [comment]
I had looked into the algorithm while reading a paper which made certain claims on Cuthill-McKee, and then I couldn't verify it with our implementation. Which is why I then started reading more, and found this. However, it was mostly verifying others' research, so no original request from my end at this point.

That said, I don't care about the application very much. I made a short test now, though, and found that step-22 in 3d runs significantly slower with my suggestion. Previously, the ILU preconditioner on level 3 for the A matrix would take 51-63 CG iterations with a mean near 55 to converge, whereas with this change the numbers are 59-75, with a mean around 65. So it seems the ILU does suffer more than I could ever hope to gain. Let us close this. This was a simple change to make for me, and we can always go back to it if we think there is separate value in it.

**Comment by bangerth** [comment]
Ha, what do you know! Can't predict how these experiments work out :-)

**Pull request closed without merging**
