### PR TITLE
extra output for OCE 0.18

### PR DESCRIPTION
**Pull request by davydden**
looks like the output format changed slightly. Diffs are in `FILE_SCHEMA`, `APPLICATION_PROTOCOL_DEFINITION` and a few other places.

### CODE REVIEW

**Comment by bangerth** [comment]
Do you have a diff between your output file and the saved one? Do they differ in any interesting way?

**Comment by davydden** [comment]
> Do they differ in any interesting way?

I know nothing about opencascade, so I can' judge. But he diffs are:

---
create:
```
----------------
##4       #:1   <== FILE_SCHEMA(('AUTOMOTIVE_DESIGN_CC2
##4       #:1   ==> FILE_SCHEMA(('AUTOMOTIVE_DESIGN
@                                                     @@
##4       #:4   <== 2
##4       #:4   ==> 0
@ Absolute error = 2.0000000000e+0, Relative error = Inf
##4       #:7   <== -1
##4       #:7   ==> 1
@ Absolute error = 2.0000000000e+0, Relative error = 2.0000000000e+0
##4       #:9   <== 5
##4       #:9   ==> 1
@ Absolute error = 4.0000000000e+0, Relative error = 4.0000000000e+0
##4       #:10  <== 4
##4       #:10  ==> 1
@ Absolute error = 3.0000000000e+0, Relative error = 3.0000000000e+0
----------------
##7       #:2   <== APPLICATION_PROTOCOL_DEFINITION('committee
##7       #:2   ==> APPLICATION_PROTOCOL_DEFINITION('international
@                                                     @@
##7       #:3   <== draft'
##7       #:3   ==> standard'
@                                                     @@
----------------
##8       #:2   <== 1997
##8       #:2   ==> 2000
@ Absolute error = 3.0000000000e+0, Relative error = 1.5022533801e-3
----------------
##15      #:2   <== MECHANICAL_CONTEXT(''
##15      #:2   ==> PRODUCT_CONTEXT(''
@                                                     @@
----------------
##45      #:2   <== PRODUCT_TYPE('part'
##45      #:2   ==> PRODUCT_RELATED_PRODUCT_CATEGORY('part'
@                                                     @@

+++  File "/Users/davydden/spack/var/spack/stage/dealii-develop-yfqypqhbak6tfj2t5zlz7t55otkc32pm/dealii/tests/opencascade/step_create.output" differs from file "output"
```

---

write:

```
----------------
##4       #:1   <== FILE_SCHEMA(('AUTOMOTIVE_DESIGN_CC2
##4       #:1   ==> FILE_SCHEMA(('AUTOMOTIVE_DESIGN
@                                                     @@
##4       #:4   <== 2
##4       #:4   ==> 0
@ Absolute error = 2.0000000000e+0, Relative error = Inf
##4       #:7   <== -1
##4       #:7   ==> 1
@ Absolute error = 2.0000000000e+0, Relative error = 2.0000000000e+0
##4       #:9   <== 5
##4       #:9   ==> 1
@ Absolute error = 4.0000000000e+0, Relative error = 4.0000000000e+0
##4       #:10  <== 4
##4       #:10  ==> 1
@ Absolute error = 3.0000000000e+0, Relative error = 3.0000000000e+0
----------------
##7       #:2   <== APPLICATION_PROTOCOL_DEFINITION('committee
##7       #:2   ==> APPLICATION_PROTOCOL_DEFINITION('international
@                                                     @@
##7       #:3   <== draft'
##7       #:3   ==> standard'
@                                                     @@
----------------
##8       #:2   <== 1997
##8       #:2   ==> 2000
@ Absolute error = 3.0000000000e+0, Relative error = 1.5022533801e-3
----------------
##15      #:2   <== MECHANICAL_CONTEXT(''
##15      #:2   ==> PRODUCT_CONTEXT(''
@                                                     @@
----------------
##183     #:2   <== PRODUCT_TYPE('part'
##183     #:2   ==> PRODUCT_RELATED_PRODUCT_CATEGORY('part'
@                                                     @@

+++  File "/Users/davydden/spack/var/spack/stage/dealii-develop-yfqypqhbak6tfj2t5zlz7t55otkc32pm/dealii/tests/opencascade/step_write.output" differs from file "output"
```

**Comment by bangerth** [comment]
Good enough, I think.

**Comment by luca-heltai** [comment]
Yes, they updated STEP standard between oce 17 and oce 18. Thanks for spotting this one out.

**Pull request merged**
