### PR TITLE
Tests: Remove build_tests/ category

### PR DESCRIPTION
**Pull request by tamiko**
The build_tests/ category had been an ugly hack for compiling all
configurable example steps.

But nowadays we already compile all (configurable) example steps as part of
the main build process - so this is redundant. Further, selectively running
a subset of example steps (as was done) is ugly and useless
(output is never compared).

Thus, let's simply remove the category and custom cmake script files.

In reference to #4427

### CODE REVIEW

**Comment by drwells** [comment]
We still need to update the documentation in a few places:
1. We should remove the `TEST_PICKUP_REGEX` in `tests/run_buildtest.cmake` and `tests/run_testsuite.cmake`
2. `doc/developers/testsuite.html` needs to be updated too

Additionally, in the (fortunately no longer so ambiguously named) build test mode of the test suite, we should compile all examples now instead of running these build tests. Could you add that too?

**Comment by tamiko** [comment]
> We should remove the TEST_PICKUP_REGEX in tests/run_buildtest.cmake and tests/run_testsuite.cmake

It servers the purpose of selecting no test so we should keep it, otherwise we run every test.
(I know that this is a bit hacky - but the alternative would be more logic.)

**Comment by drwells** [comment]
Would you be willing to change the regex to something more direct, like `do_not_run_any_tests`?

**Comment by tamiko** [comment]
@drwells Can do that. Also adjusting documentation.

**Comment by tamiko** [comment]
@drwells Updated.

**Comment by tamiko** [comment]
@davydden In fact, whether dynamically loading the link interface actually works was never tested by the `build_tests/*` (only a hand-picked number of stages without external dependency were allowed to run).

**Comment by drwells** [comment]
Lines 783-784 of `testsuite.html` still mention the build tests.

**Comment by drwells** [comment]
That should do it.

**Pull request merged**
