### PR TITLE
Add missing #ifdef DEAL_II_WITH_THREADS around tbb calls

### LINKED ISSUE #7824: Undeclared identifier 'tbb'
Hi @Rombur the last version of deal.ii and it does not compile. I think that it is related to  #7808 

The compilation report with the errors can be found here:
http://cdash.kyomu.43-1.org/buildSummary.php?buildid=8495

A few of errors:
```make
In file included from /opt/src/dealii/include/deal.II/base/aligned_vector.h:24:                                                                                                                                      
/opt/src/dealii/include/deal.II/base/parallel.h:160:7: error: use of undeclared identifier 'tbb'           
      tbb::parallel_for(tbb::blocked_range<Iterator>(x_begin, x_end, grainsize),                                                                                                   
      ^                                                                                                                                                                                 
/opt/src/dealii/include/deal.II/base/parallel.h:160:25: error: use of undeclared identifier 'tbb'                                            
      tbb::parallel_for(tbb::blocked_range<Iterator>(x_begin, x_end, grainsize),                              
                        ^                                                                                         
/opt/src/dealii/include/deal.II/base/parallel.h:160:44: error: 'Iterator' does not refer to a value         
      tbb::parallel_for(tbb::blocked_range<Iterator>(x_begin, x_end, grainsize),                                                             
                                           ^                                                        
/opt/src/dealii/include/deal.II/base/parallel.h:153:24: note: declared here                                                           
    template <typename Iterator, typename Functor>                                                                 
                       ^                                                                                                                                                     
/opt/src/dealii/include/deal.II/base/parallel.h:162:25: error: use of undeclared identifier 'tbb'                                                                     
                        tbb::auto_partitioner());                                                                                                                                                
                        ^ 
```

### PR DESCRIPTION
**Pull request by Rombur**
Fix #7824

@dangars with this I can compile with `DEAL_II_WITH_THREADS=OFF`

### CODE REVIEW

**Comment by drwells** [comment]
I think we should provide a non-threaded version of this function to use when threads are not enabled; thats what we do with a lot of the other thread stuff.

**Comment by drwells** [comment]
(for the first one, that is)

**Comment by tjhei** [comment]
Yes. I think we should merge as is to fix compilation first, though.

**Comment by dangars** [comment]
@Rombur Now deal.ii can be built with -DDEAL_II_WITH_THREADS=OFF :)

**Pull request merged**
