### PR TITLE
Fix several tests.

### PR DESCRIPTION
**Pull request by bangerth**
I finally managed a star merge of independent commits into one single merge commit :-)

### CODE REVIEW

**Comment by drwells** [comment]
A somewhat pedantic complaint, but unless I missed something the FEValues instance you modified does not ever use values (so you can also remove the `update_values` flag).

**Comment by drwells** [comment]
Otherwise this is good :+1:

**Comment by drwells** [comment]
I was able to do this myself by rebasing this entire branch against `master` (which gets rid of the extra merge commit) and then doing a `fixup` of the new commit removing `update_values`  onto the commit with message "Remove unused variables".

**Comment by drwells** [comment]
To answer your question precisely: I suggest just rebasing against master and then adding this as a `fixup`.

**Comment by tjhei** [comment]
Can you squash all your commits while you are at it?

**Comment by tamiko** [comment]
@tjhei 
> Can you squash all your commits while you are at it?

You monster.

**Comment by bangerth** [comment]
I've removed the extraneous update flags and committed this as an additional commit. Allow me to indulge in the fact that I finally managed a star merge, and not squash or linearize the history of this PR :-)

**Comment by drwells** [comment]
I think that this is fine. @tjhei do you insist on the squashing?

**Comment by tjhei** [comment]
> Allow me to indulge in the fact that I finally managed a star merge

You know a simple set of cherry-picks would have done it too, right? :-)

> do you insist on the squashing?

I prefer a simpler history especially for a 10 line change like this. Whatever, not an important fight to pick.

**Pull request merged**
