### PR TITLE
Avoid signed overflow in Testing::rand

### PR DESCRIPTION
**Pull request by masterleinad**
Detected using `-fsanitize=undefined`.

### CODE REVIEW

**Comment by drwells** [comment]
I have to admit that (while I don't doubt that this is right) I don't understand this at all. Is this only for unsigned integer types? Would you please add some documentation to the new function to explain how it calculates the wrap-around (which I think is what it does)?

**Comment by drwells** [comment]
Thanks for the text. I now understand it.

**Comment by drwells** [comment]
@tjhei It looks like you added `rand` here in ad89a1cfd0e6cbd38a770fc8d48fd3cc1bc00bcf. Do you remember where it came from or if it makes any assumptions on overflow?

**Comment by tjhei** [comment]
> Do you remember where it came from or if it makes any assumptions on overflow?

I don't, but probably from https://www.mscs.dal.ca/~selinger/random/ or a glibc implementation. I assume the author's did not think about this problem.

**Comment by jppelteret** [comment]
> Yes, I just ran both of them 1e10 times.

Only 1e10 times? Sounds like a fluke to me ;-P

**Comment by bangerth** [comment]
Yea, 1e10 does sound like a coincidence! What's the period of the random number generator? I think we should test at least that long! Would you mind adding a test that checks that (it's ok if you wanted to output only, say, every 1000th number.)

**Comment by masterleinad** [comment]
From https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=stdlib/random.c;hb=HEAD:
> The total period of the generator is approximately deg*(2**deg - 1); thus
   doubling the amount of state information has a vast influence on the
   period of the generator. 

That means for `degree=31` that the period is approximately 66,571,993,057.

**Comment by bangerth** [comment]
Ha, so you were *almost* there!

**Comment by masterleinad** [comment]
> That means for degree=31 that the period is approximately 66,571,993,057.

Running the test in `Debug mode` takes around 25 minutes for me. I would probably just cut the number of iterations by 5 or so then (even if this doesn't look at the whole period).

**Comment by bangerth** [comment]
Err, you all realized that I was joking, right!?

**Pull request merged**
