### PR TITLE
FESystem: Compare for domination by component instead of base element

### LINKED ISSUE #17521: compare_for_domination() assertion error when using FESystems with different number of base elements
If multiple FESystems are used where each FESystem has a different number of base elements, the assertion in the compare_for_domination() fails throwing an error. For example, if using

**FESystem[FE_Q(1)^3]
FESystem[FE_Q(1)^2-FE_Nothing^1]**

the following assertion error is thrown
**An error occurred in line <2478> of file <../deal.II/src/source/fe/fe_system.cc> in function
    dealii::FiniteElementDomination::Domination dealii::FESystem<dim, spacedim>::compare_for_domination(const dealii::FiniteElement<dim, spacedim>&, unsigned int) const [with int dim = 2; int spacedim = 2]
The violated condition was:
    this->n_base_elements() == fe_sys_other->n_base_elements()
Additional information:
    You are trying to use functionality in deal.II that is currently not
    implemented. In many cases, this indicates that there simply didn't
    appear much of a need for it, or that the author of the original code
    did not have the time to implement a particular case. If you hit this
    exception, it is therefore worth the time to look into the code to
    find out whether you may be able to implement the missing
    functionality. If you do, please consider providing a patch to the
    deal.II development sources (see the deal.II website on how to
    contribute).**

### PR DESCRIPTION
**Pull request by mkghadban**
fixes #17521 (hopefully)

### CODE REVIEW

**Review by masterleinad — COMMENTED** [review]
Can you add a test case that uses the example from the corresponding issue?

**Comment by masterleinad** [comment]
Also, please run `make indent` to fix the indentation.

**Comment by marcfehling** [comment]
We have tests in [tests/hp/fe_collection_05.cc](https://github.com/dealii/dealii/blob/master/tests/hp/fe_collection_05.cc) and  [tests/hp/fe_collection_06.cc](https://github.com/dealii/dealii/blob/master/tests/hp/fe_collection_06.cc). It would be great if you could expand those with your use case!

**Comment by mkghadban** [comment]
> Also, please run `make indent` to fix the indentation.

Done!

**Comment by marcfehling** [comment]
So basically what your patch allows is that you do a `FiniteElementDomination` comparison with `FESystem` objects with a varying number of base elements, as long as the total number of components is the same. That is a nice feature.

I do not remember why we went over the base elements instead of the components in the first place. Were there performance concerns? I will tag @bangerth -- maybe he remembers.

The additional test you provided was a just a minor variation of the others, i.e. we already cover the scenario in the other tests. I went ahead and changed the other tests so that they make use of your new feature instead of introducing another variation.

**Review by marcfehling — APPROVED** [review]

**Review by bangerth — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]

**Comment by bangerth** [comment]
@mkghadban I forgot: Would you mind adding an entry to `doc/news/changes/minor` that explains the change? This way you will (appropriately!) be listed in the changelog file for the next release.

**Comment by mkghadban** [comment]
Not at all! I added it in PR #17588.

**Pull request merged**
