### PR TITLE
Replace C-style arrays in MatrixFree

### PR DESCRIPTION
**Pull request by peterrum**

### CODE REVIEW

**Review by drwells — APPROVED** [review]
Thanks a lot for doing this. Seeing arrray references instead of pointers in function calls makes the code much easier to understand.

**Review by tjhei — COMMENTED** [review]
Is any of this user-facing?

**Comment by peterrum** [comment]
> Is any of this user-facing and as such not backwards compatible? Looks good otherwise.

Should be all internal. But let's wait for @kronbichler's opionion!

**Review by kronbichler — APPROVED** [review]

**Comment by kronbichler** [comment]
None of those should be directly user-facing and even the use of internal (implementation-dependent) data structures is unlikely to directly access or pass around C-style arrays.

**Pull request merged**
