### PR TITLE
[WIP] Sparsity tools DG coupling 1D

### LINKED ISSUE #2290: 1d instantiation of DoFTools::make_flux_sparsity_pattern missing
As reported by Weixiong Zhang on the mailing list:
...................................

I extended my code from 2D to 1D. It is a vector hyperbolic system. The spatial discretization is DG1. When in 2D, I specified which component coupled to which and then:
DoFTools::make_flux_sparsity_pattern (dof_handler, dsp, cell_coupling, face_coupling);

It was perfectly fine and saved tons of memories for me in 2D. But when I tried in 1D case, I got the following problem:

```
Undefined symbols for architecture x86_64:
  "void dealii::DoFTools::make_flux_sparsity_pattern<dealii::DoFHandler<1, 1>, dealii::DynamicSparsityPattern>(dealii::DoFHandler<1, 1> const&, dealii::DynamicSparsityPattern&, dealii::Table<2, dealii::DoFTools::Coupling> const&, dealii::Table<2, dealii::DoFTools::Coupling> const&)", referenced from:
      NFPN_1D<1>::setup_system() in nfpn1d.cc.o
ld: symbol(s) not found for architecture x86_64
```

If I just use
DoFTools::make_flux_sparsity_pattern (dof_handler, dsp);

It will be fine.

So I am curious what's going on there.

Thanks in advance!
Weixiong

### PR DESCRIPTION
**Pull request by drwells**
This should close #2290 and partly addresses #2293.

All of the tests currently pass but I do not think there are any tests for this function in 1D right now. I would like to add some before this gets merged.

The important commit is 1628c42, where I got rid of the user flag based logic.

### CODE REVIEW

**Comment by drwells** [comment]
There are about twelve tests that currently use this function in 2D and 3D (things like `bits/of_tools_18d_x.cc`). These tests currently skip the 1D case. Does anyone have a recommendation for how to verify that these tests are correct in 1D without checking every line of output (something like 25,000 new lines)?

**Comment by bangerth** [comment]
On 03/03/2016 05:21 PM, David Wells wrote:
> There are about twelve tests that currently use this function in 2D and 3D
> (things like |bits/of_tools_18d_x.cc|). These tests currently skip the 1D
> case. Does anyone have a recommendation for how to verify that these tests are
> correct in 1D without checking every line of output (something like 25,000 new
> lines)?

Clone the tests and on the cloned test only run the 1d version. Spot check the 
output of the cloned tests on artificially created meshes -- the original 
tests should continue to work as they did before anyway.

**Comment by kronbichler** [comment]
The new code looks fine, therefore I wouldn't go to too great lengths regarding the test output. Your current strategy aims to reproduce the old behavior of adding the indices over a face only once. I don't think that's necessary - otherwise you would add entries that already exist which does not hurt either. So for verification, I would compare the output when adding from both sides with the more efficient strategy that you devised above and call it a day.

**Comment by drwells** [comment]
That's a good point and will probably save me a lot of time.

Before I address this, though, I would like to get rid of about half the tests for this function: we currently have two variants (one uses `CompressedSetSparsityPattern` and the other uses `CompressedSparsityPattern`) for each test case, so we should be able to switch one to `DynamicSparsityPattern` and get rid of the other one.

**Comment by drwells** [comment]
I examined a few (not all) of the sparsity patterns generated by the tests and followed @kronbichler's suggestion, so this should be good to go.

**Comment by kronbichler** [comment]
I think this is good for merge. Any other comments? @drwells is there anything left to do since there still is the WIP tag?

**Comment by drwells** [comment]
@kronbichler oh, I should have removed that. I do not think that there is anything left to do for this PR.

**Pull request merged**
