### PR TITLE
Make test output more robust.

### PR DESCRIPTION
**Pull request by kronbichler**
Output the vertex locations for each component separately and put a space between the parenthesis and the numerical output (for numdiff).

### CODE REVIEW

**Comment by kronbichler** [comment]
The changes in the output files are rather boring...

**Comment by tjhei** [comment]
Spacing makes sense for numdiff. Is the output more robust by outputting each component separately or why do you do that?

**Comment by tjhei** [comment]
(looks good, please merge yourself after reading my comment)

**Comment by kronbichler** [comment]
It's because `Logstream::operator<<` of `Point<dim>` (or Tensor) does not obey to threshold_double. (numdiff would mark the test as passed anyway but I prefer having '0' instead of '0.00' or '-6.94e-18', to mention a few numbers from the diff.)

**Pull request merged**
