### PR TITLE
Deprecate FunctionMap

### LINKED ISSUE #2247: Deprecate FunctionMap
The discussion in #2241 shows that `FunctionMap<...>::type` is quite generally a bad idea. First, it doesn't provide much clarity what type this actually refers to when reading the code -- one needs to look it up. This is relevant because, unlike things like `std::vector::iterator` or `Triangulation::active_cell_iterator`, one actually needs to know what `FunctionMap::type` is if one wants to use it in any meaningful ways.

Second, now that Function objects are also frequently templated on their scalar type, this scalar type cannot be deduced from the `FunctionMap<dim,number>::type` argument, requiring the explicit specification of a template argument.

Consequently, the easiest way to deal with the problem is to deprecate the whole thing and just spell out the typedef'ed type everywhere it is currently used. #2241 already does that in parts.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #2247. I agree that the clarity outweighs the lengthy type description.

### CODE REVIEW

**Comment by bangerth** [comment]
Thanks. This patch has run into merge conflicts. Can you please update it?

**Comment by masterleinad** [comment]
I rebased.

**Comment by bangerth** [comment]
Hm, it still says that I can't merge...

**Comment by masterleinad** [comment]
> Hm, it still says that I can't merge...

It seems our protected branch now requires each PR to be up-to-date even if there are no merge-conflicts...

**Comment by bangerth** [comment]
Hm, that makes no sense -- it doesn't scale if you just have enough development. We also don't have the tester power to test newly rebased branches quick enough. Can we switch this off?

**Comment by tamiko** [comment]
@bangerth Ups. That was me. I accidentally checked one box too many when I reenabled the Travis CI as "Required" check. Turned it off again.

**Pull request merged**
