### PR TITLE
Remove unused functions

### PR DESCRIPTION
**Pull request by peterrum**
I guess we can remove these function. They are nowhere used.

### CODE REVIEW

**Comment by masterleinad** [comment]
Can you please rebase? It seems like `Travis` doesn't report back and we can't merge without it.

**Comment by peterrum** [comment]
@masterleinad I have rebased this branch and the one in PR #9795 in the morning. Travis seems still to be stuck...

**Comment by kronbichler** [comment]
I think Travis CI works better now, so we could give this another spin.

**Pull request merged**
