### PR TITLE
Deprecate another function in DoFTools.

### PR DESCRIPTION
**Pull request by bangerth**
It's again a function that returns by-argument instead of by-value. Replace it by a function that returns by-value.

Also replace the usage of this function in the examples.

### CODE REVIEW

**Comment by tjhei** [comment]
I like the change to return the value, but I have one related question:
```
    locally_owned_dofs = dof_handler.locally_owned_dofs();
    locally_relevant_dofs = DoFTools::extract_locally_relevant_dofs(dof_handler);
```
It is kind of odd to me, that one is a member of the DoFHandler, while the other one is not. If it was part of DoFHandler, we would be able to cache the result as well?

**Comment by tamiko** [comment]
@tjhei That's a good point. Maybe while we're at it (and already deprecate a function signature). What about relocation the function in the DoFHandler as well? After all, the locally relevant set as we define it is a canonical choice (only depending on the DoFHandler).

**Comment by bangerth** [comment]
Well, that's a bigger change -- we currently have three functions in `DoFTools` for locally owned/active/relevant, but only one in `DoFHandler` (for the first). There are also corresponding "level" functions that currently also all reside in `DoFTools`.

I am agnostic as to what to do. If we decided to merge this change, it will not be difficult later on to make a further change by script if the functions moved into `DoFHandler`.

(I will note that they are currently implemented only once in a generic way, whereas we would have to duplicate them for `DoFHandler` and `hp::DoFHandler` -- though the code duplication would be minimal.)

**Comment by tjhei** [comment]
> If we decided to merge this change, it will not be difficult later on to make a further change by script if the functions moved into `DoFHandler`.

I am not insisting on my suggestion, but if we make the additional change later, I would propose not to merge this PR. This just causes additional PRs in downstream projects.

**Comment by bangerth** [comment]
Well, so what should we do. Anyone else got any opinions?

**Comment by kronbichler** [comment]
I'd also like to have them in the `DoFHandler` - the question is whether we really need to have the locally active ones in the DoFHandler, because I have almost never used them, but at this point I think the symmetry in interfaces make the case.

I do however not feel that the addition to `DoFHandler` must be done within this PR (and support this one as is). As long as we manage to put it there before the next release, I think the headache for external projects will be manageable (especially since we would likely still keep the functions that compute the data in `DoFTools`).

**Comment by bangerth** [comment]
We didn't come to a consensus here, and #10563 also points the way for the future.

**Pull request closed without merging**
