### PR TITLE
Update GridGenerator::truncated_cone.

### PR DESCRIPTION
**Pull request by drwells**
First half of the fix for #6250.

The 3D grid currently uses 4 coarse level cells on circular slices: this is poorly conditioned since, when refined, some cells will converge to triangles. This commit uses the five-square (implemented by `GridGenerator::hyper_ball<2>`) to get a much better coarse grid.

### CODE REVIEW

**Comment by masterleinad** [comment]
Do you have pictures?

**Comment by drwells** [comment]
Yes. Here is the present version:

truncated-cone-master-2

and newer:
truncated-cone-3b

**Comment by drwells** [comment]
I'll add pictures to the PR.

**Comment by luca-heltai** [comment]
Nice!

**Pull request merged**
