### PR TITLE
Fix some clang-tidy 9 findings

### PR DESCRIPTION
**Pull request by masterleinad**

### CODE REVIEW

**Comment by bangerth** [comment]
OK if you apply this indentation issue:
```
-    AdvectionProblem(const Settings& settings);
+    AdvectionProblem(const Settings &settings);
```

**Comment by tjhei** [comment]
the tester doesn't run correctly, because @masterleinad created it the branch in the upstream repository instead of in his fork.

**Comment by masterleinad** [comment]
Oops... see #8874.

**Pull request closed without merging**
