### PR TITLE
Make the class MappingQ equivalent to MappingQGeneric

### PR DESCRIPTION
**Pull request by kronbichler**
Since we introduced manifolds, the use of `MappingQ` (creating deformed cells only near the boundary in the default case, and only optionally making all cells curved) has become very error-prone. For non-flat volume manifolds, we would even have gaps in the mesh.

I think we have reached a consensus in the past that we should simply get rid of this class as it makes no sense any more. It is just a maintenance burden and makes the mapping classes more difficult to use. I adapted the classes that were previously using it to the new scheme: this patch may look like a lot of code, but it really only moves around some things from some internal base classes like `MappingQEulerianGeneric` into the actual class.

If we agree, I will add a changelog entry. One future change we might think about is whether we want to move the code from `MappingQGeneric` back into `MappingQ` - but that is an independent change.

### CODE REVIEW

**Comment by kronbichler** [comment]
I think we actually had a bug in step-32 due to the old `MappingQ` class: We used to compute on a spherical shell (which attaches a volume manifold), but we only applied the mapping near the boundary.

**Comment by drwells** [comment]
I thought the main advantage of this class was that one could have a curved boundary and still use `MappingQ1` on all the internal cells. Are we going to make people use `MappingQCollection` if they want to achieve that instead in the future?

**Comment by kronbichler** [comment]
I also changed the tests to not use the deprecated constructor. In a few manifold tests, we explicitly asked for both the `MappingQ` just at the boundary and everywhere; of course, it now only makes sense to keep one.

**Comment by kronbichler** [comment]
> I thought the main advantage of this class was that one could have a curved boundary and still use MappingQ1 on all the internal cells. Are we going to make people use MappingCollection if they want to achieve that instead in the future?

Do you think it will bother many people? I admit that we might lose a little bit of performance, but I can't see it substantial. If the underlying manifold is not a flat one, the grid was inconsistent before. But if it is, the generation of additional points should be pretty cheap. And we use tensor products for higher order functions to quickly evaluate stuff inside `FEValues`, so I can only see this matter for non-tensor product quadrature formulas or for `FEFaceValues`.

**Comment by drwells** [comment]
I was curious so I put together a little timing program comparing the two:
```cpp
#include <deal.II/base/timer.h>
#include <deal.II/dofs/dof_handler.h>

#include <deal.II/fe/fe_nothing.h>
#include <deal.II/fe/fe_values.h>
#include <deal.II/fe/mapping_q_generic.h>
#include <deal.II/fe/mapping_q.h>

#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/tria.h>

int main()
{
    using namespace dealii;

    TimerOutput timer_out(std::cout, TimerOutput::summary,
                          TimerOutput::wall_times);

    Triangulation<3> tria;
    GridGenerator::hyper_ball(tria);
    tria.refine_global(4);

    // const unsigned int fe_degree = 4;
    const unsigned int quad_degree = 7;
    FE_Nothing<3> fe;
    QGauss<3> quad(quad_degree);

    {
        TimerOutput::Scope scope(timer_out, "MappingQ");

        MappingQGeneric<3> mapping(3);
        FEValues<3> fe_values(mapping,
                              fe,
                              quad,
                              update_quadrature_points | update_JxW_values);
        for (const auto &cell : tria.active_cell_iterators())
            fe_values.reinit(cell);
    }

    {
        TimerOutput::Scope scope(timer_out, "MappingQGeneric");
        MappingQ<3> mapping(3);
        FEValues<3> fe_values(mapping,
                              fe,
                              quad,
                              update_quadrature_points | update_JxW_values);
        for (const auto &cell : tria.active_cell_iterators())
            fe_values.reinit(cell);
    }
}
```
and I got
```
[ 66%] Built target mapping
[100%] Run mapping with Release configuration


+---------------------------------------------+------------+------------+
| Total wallclock time elapsed since start    |       1.9s |            |
|                                             |            |            |
| Section                         | no. calls |  wall time | % of total |
+---------------------------------+-----------+------------+------------+
| MappingQ                        |         1 |      1.24s |        65% |
| MappingQGeneric                 |         1 |     0.591s |        31% |
+---------------------------------+-----------+------------+------------+

[100%] Built target run
```
I didn't compile with `march=native` - I'll try that next.

**Comment by kronbichler** [comment]
Thanks for the numbers - I think it's not too bad, given that all you do is compute the Jacobians and quadrature points and no "real" work. But let's wait for other opinions.

**Comment by drwells** [comment]
It's a little worse with `-O3 -march=native` (this is also with clang):
```
[ 66%] Built target mapping
[100%] Run mapping with Release configuration


+---------------------------------------------+------------+------------+
| Total wallclock time elapsed since start    |       1.3s |            |
|                                             |            |            |
| Section                         | no. calls |  wall time | % of total |
+---------------------------------+-----------+------------+------------+
| MappingQ                        |         1 |     0.921s |        71% |
| MappingQGeneric                 |         1 |     0.343s |        26% |
+---------------------------------+-----------+------------+------------+

[100%] Built target run
```

**Comment by kronbichler** [comment]
Wait, but now the `MappingQGeneric` function is faster?

**Comment by drwells** [comment]
I wrote the wrong labels in the timers. Let me fix that - I'll update those previous messages.

**Comment by kronbichler** [comment]
OK, so a factor of 3. Thanks!

**Comment by drwells** [comment]
OK, one more table, with `FE_Q<3>(3)` and update gradients:
```
[ 66%] Built target mapping
[100%] Run mapping with Release configuration


+---------------------------------------------+------------+------------+
| Total wallclock time elapsed since start    |         5s |            |
|                                             |            |            |
| Section                         | no. calls |  wall time | % of total |
+---------------------------------+-----------+------------+------------+
| MappingQ                        |         1 |      2.26s |        45% |
| MappingQGeneric                 |         1 |      2.71s |        54% |
+---------------------------------+-----------+------------+------------+

[100%] Built target run
```
so the performance change isn't much.

In conclusion now that we merged `DoFHandler` and `hp::DoFHandler` I suppose its not too much to ask that people use a `MappingCollection` if they want to use different mappings on different cells, so lets do it.

**Comment by kronbichler** [comment]
How do we want to proceed? I think #2206 is another good example why we should simply make the deformation on all cells the default.

**Review by bangerth — COMMENTED** [review]
I'm ok with this change. I wished there was a way to get rid of the `MappingQGeneric` class instead of the `MappingQ` class, but maybe that needs to come in a second step.

**Comment by kronbichler** [comment]
Yes, it would be good to get rid of that class; it is not overly difficult because we just need to switch some names. I'd do that in a second step, which can come soon after this one. (I just want one round of the regression testers on this.)

**Comment by kronbichler** [comment]
Can we move on with this PR?

**Review by drwells — APPROVED** [review]

**Comment by drwells** [comment]
That puts us at two approvals and no objections. Lets merge this today unless someone speaks up.

**Pull request merged**
