### PR TITLE
Replace logstream.push/pop by Logstream::Prefix.

### PR DESCRIPTION
**Pull request by bangerth**
This does the conversion in the linear solvers. It simplifies the logic in a number
of places where we specifically had to have a try-catch block where we pop the
deallog prefix in the catch block but now this can happen automatically via
the destructor of the Prefix class. Consequently, the patch is probably
easiest to read with ?w=1.

In some sense this is a follow-up to #4935 and the patches that resolved
that because they already largely emptied out the catch blocks of the
memory deallocation.

### CODE REVIEW

**Comment by bangerth** [comment]
Ping?

**Comment by bangerth** [comment]
@masterleinad  -- in which time zone do you happen to be today? It was 2:30am in Germany when you merged this!

**Comment by masterleinad** [comment]
@bangerth I am just having a slightly unusual working rhythm at the moment. :wink:

**Pull request merged**
