### PR TITLE
Avoid ambiguity of namespace internal::ConstraintMatrix and class ConstraintMatrix

### PR DESCRIPTION
**Pull request by masterleinad**
When including `dofs/dof_accessor.templates.h` after `constraint_matrix.templates.h` we find int the former file the namespace `internal::ConstraintMatrix` instead of the class `ConstraintMatrix`.

We should probably just avoid having a namespace with the same name as a class even if it is nested in another `internal` namespace.

### CODE REVIEW

**Comment by tjhei** [comment]
> We should probably just avoid having a namespace with the same name as a class even if it is nested in another internal namespace.

Agreed. Having a namespace with the same name as a class is a terrible idea.

Maybe ``internal::constraint_matrix`` would be more appropriate?

**Comment by drwells** [comment]
I liked the `internal::ConstraintMatrix::` notation (I have used it all over the place in the library), but I suppose it should go since it leads to strange namespace lookup problems.

We should probably pick a convention for these things since there are a lot of them. I'd prefer something like `ConstraintMatrixImplementation` since we already use `*Implementation` in other places.

**Comment by bangerth** [comment]
I'm not a fan of this patch I'm afraid. We use this idiom all over the place -- converting just one place seems like the wrong approach. Why not qualify the symbols with the appropriate namespace `deali::` or `internal::ConstraintMatrix` in the places where the compiler complains?

**Comment by tjhei** [comment]
> Why not qualify the symbols with the appropriate namespace in the places where the compiler complains?

I don't think this is a good approach. You would have to try all combinations of .template.h with all other header files, otherwise things break randomly in user code (this is how we discovered this issue). The error message is also completely unhelpful (something like ``ConstraintMatrix`` does not name a type).

I would vote to change these namespaces to something that can not collide with class names (for example ``internal::ClassNameImplementation`` or ``internal::class_name`` or ``internal::header_file_name``). Maybe using the name of the header is more appropriate anyways because that is what it is used for: to do a file scope.

**Comment by bangerth** [comment]
On 03/01/2018 03:00 PM, Timo Heister wrote:
> I don't think this is a good approach. You would have to try all 
> combinations of .template.h with all other header files, otherwise 
> things break randomly in user code (this is how we discovered this 
> issue).

But we've been doing things this way for a good long time. I agree that 
it sometimes happens, but it's not like we have an epidemic of these 
error messages -- in other words, we must have code that's by and large 
already safe for this kind of thing.

So before we embark on changing this system everywhere, I'd be 
interested in seeing some kind of empirical evidence that it's actually 
necessary and that it's not enough to fix the occasional issue whenever 
it comes up.


> The error message is also completely unhelpful (something like 
> |ConstraintMatrix| does not name a type).

You get used to it ;-)


> I would vote to change these namespaces to something that can not 
> collide with class names (for example 
> |internal::ClassNameImplementation| or |internal::class_name| or 
> |internal::header_file_name|). Maybe using the name of the header is
>  more appropriate anyways because that is what it is used for: to do
> a file scope.

That works, but to make this uniform, it's a pretty big change. (If you 
want to do that, use the class name -- otherwise it's difficult to move 
stuff from one file to another.)

**Comment by tjhei** [comment]
> You get used to it ;-)

well, my student, @masterleinad , and I were stumped...

**Comment by masterleinad** [comment]
> That works, but to make this uniform, it's a pretty big change. (If you
> want to do that, use the class name -- otherwise it's difficult to move
> stuff from one file to another.)

I am willing to make this change and use `Internal::ClassNameImplementation` if this finds acceptance.

**Comment by bangerth** [comment]
I'd be ok with that.

**Comment by masterleinad** [comment]
Superseded by #5994.

**Pull request closed without merging**
