### PR TITLE
Removed wrapping for reference cell.

### LINKED ISSUE #11626: Broken python wrappers.
The elimination of the enum `ReferenceCell::Type::CellKinds` broke our python wrappers:

```
 /usr/bin/c++  -DBOOST_NO_AUTO_PTR -DPyDealII_release_EXPORTS -Iinclude -I../include -I../bundled/taskflow-2.5.0/include -I../contrib/python-bindings/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -isystem /usr/include/trilinos -isystem /usr/include/hdf5/openmpi -isystem /usr/include/scotch -isystem /usr/include/suitesparse -isystem /usr/include/petsc -isystem /usr/lib/x86_64-linux-gnu/hdf5/openmpi/include -isystem /usr/include/opencascade -isystem /usr/include/slepc -isystem /usr/include/python3.8 -fPIC   -pedantic -fPIC -Wall -Wextra -Wmissing-braces -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wsuggest-override -Wswitch -Wsynth -Wwrite-strings -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -Wno-class-memaccess -fopenmp-simd -pthread -Wno-unused-local-typedefs -O2 -funroll-loops -funroll-all-loops -fstrict-aliasing -Wno-unused-local-typedefs -MD -MT contrib/python-bindings/source/CMakeFiles/PyDealII_release.dir/export_reference_cell.cc.o -MF contrib/python-bindings/source/CMakeFiles/PyDealII_release.dir/export_reference_cell.cc.o.d -o contrib/python-bindings/source/CMakeFiles/PyDealII_release.dir/export_reference_cell.cc.o -c ../contrib/python-bindings/source/export_reference_cell.cc
#5 6892. ../contrib/python-bindings/source/export_reference_cell.cc: In function ‘void dealii::python::export_reference_cell()’:
#5 6892. ../contrib/python-bindings/source/export_reference_cell.cc:31:47: error: ‘CellKinds’ is not a member of ‘dealii::ReferenceCell::Type’
#5 6892.    31 |     boost::python::enum_<ReferenceCell::Type::CellKinds>("CellKinds")
#5 6892.       |                                               ^~~~~~~~~
#5 6892. ../contrib/python-bindings/source/export_reference_cell.cc:31:47: error: ‘CellKinds’ is not a member of ‘dealii::ReferenceCell::Type’
#5 6892. ../contrib/python-bindings/source/export_reference_cell.cc:31:56: error: template argument 1 is invalid
#5 6892.    31 |     boost::python::enum_<ReferenceCell::Type::CellKinds>("CellKinds")
#5 6892.       |                                                        ^
#5 6892. ../contrib/python-bindings/source/export_reference_cell.cc:44:48: error: ‘CellKinds’ is not a member of ‘dealii::ReferenceCell::Type’
#5 6892.    44 |       boost::python::init<ReferenceCell::Type::CellKinds>(
#5 6892.       |                                                ^~~~~~~~~
#5 6892. ../contrib/python-bindings/source/export_reference_cell.cc:44:48: error: ‘CellKinds’ is not a member of ‘dealii::ReferenceCell::Type’
#5 6892. ../contrib/python-bindings/source/export_reference_cell.cc:44:57: error: template argument 1 is invalid
#5 6892.    44 |       boost::python::init<ReferenceCell::Type::CellKinds>(
#5 6892.       |                                                         ^
#5 6899. [937/966] Building CXX object contrib/python- :bindings/source/CMakeFiles/PyDealII_release.dir/cell_accessor_wrapper.cc.o
#5 6990. [938/966] Linking CXX shared library lib/libdeal_II.g.so.9.3.0-pre
#5 6990. ninja: build stopped: subcommand failed.
```
and with it our master docker images.

### PR DESCRIPTION
**Pull request by luca-heltai**
Closes #11626.

Since the enum has been removed, I just removed the corresponding wrapper. This won't be compiled by any of the testers, except on merge to master, so none of the tests is relevant, except indent. 

@peterrum, @agrayver

### CODE REVIEW

**Review by peterrum — APPROVED** [review]
Since it compiled locally, I will merge this PR. The is another PR that enables the build of the python wrapper by CI.

**Comment by bangerth** [comment]
Thanks for fixing my breakage!

**Comment by bangerth** [comment]
@luca-heltai I think I'm only now realizing what this patch does. If you remove the wrapping file, we have the wrapper class but it can't be used in python. What was the intention of the patch here? We probably want these wrappers back at some point, right?

**Comment by luca-heltai** [comment]
> @luca-heltai I think I'm only now realizing what this patch does. If you remove the wrapping file, we have the wrapper class but it can't be used in python. What was the intention of the patch here? We probably want these wrappers back at some point, right?

Yes. I thought we should have waited for the interface to stabilize a bit. :) 

Now we are building also the python wrappers with github actions. We should not get into trouble anymore. :)

**Comment by agrayver** [comment]
I plan to continue working on pzthon wrappers for mixed/tria meshes, but as @luca-heltai said, it waits for the C++ interface to be less volatile.

**Comment by luca-heltai** [comment]
> I plan to continue working on pzthon wrappers for mixed/tria meshes, but as @luca-heltai said, it waits for the C++ interface to be less volatile.

@agrayver , did you, by any  chance, experiment with AutoWIG and deal.II? (https://hal.inria.fr/hal-01756458/document)

**Comment by agrayver** [comment]
> did you, by any chance, experiment with AutoWIG and deal.II?

I saw this one recently, but I did not experiment with it. At some point I did try another generator and it failed. 

Certainly, if one wants to convert a big part of the library, one will have to find an automated way... But given the complexity of deal.II I am not sure it is possible. 

An alternative is cython (say petsc4py uses it), but there, again, one has to write an intermediate layer and with templates this becomes as (or more...) tedious...

**Comment by luca-heltai** [comment]
AutoWIG claims they can do templates easily, leveraging LLVM. Maybe we could explore this a bit.

**Pull request merged**
