### PR TITLE
Slightly decrease solver tolerance in lac/gmres_eigenvalues

### PR DESCRIPTION
**Pull request by masterleinad**
This (in combination with #6535) makes sure that all tests with `ICC 19` are passing for a standard configuration.

### CODE REVIEW

**Comment by masterleinad** [comment]
> @masterleinad I thought the last release were icc-18.0.2 where and how did you get 19?

I have a beta version. You can get it at https://software.intel.com/en-us/articles/intel-parallel-studio-xe-2019-beta

**Comment by tamiko** [comment]
Unfortunately, this test now for other configurations: https://cdash.kyomu.43-1.org/viewTest.php?onlydelta&buildid=1624

**Comment by bangerth** [comment]
Let's ignore this issue for the release at least. It is not a problem if a couple of tests fail on the release branch.

**Comment by tamiko** [comment]
@bangerth I am not very happy with that. I will open an issue.

**Pull request merged**
