### PR TITLE
Redo output for physics/step-44* tests

### PR DESCRIPTION
**Pull request by jppelteret**
Instead of checking the convergence rates for each Newton iteration
against some benchmark result that is machine specific, we now monitor
the solution at a fixed point. This should remain unchanged if the
problem converges correctly for each timestep. The nonlinear solver
output is now send to the file "stdout".

Fixes #3747

### CODE REVIEW

**Comment by jppelteret** [comment]
@masterleinad @bangerth I think that this is a better, more flexible solution to monitoring the output of these tests. Lesson learned!

**Comment by tamiko** [comment]
@jppelteret We also have a `check_solver_within_range` macro that can be used to check that an iterative solver converges within a certain range of iterations.

**Comment by jppelteret** [comment]
Thanks for the info @tamiko. I still think that in this case it makes sense just to simplify the output.

**Comment by masterleinad** [comment]
The modified tests pass for me as well. I close #3747 in favor of this PR.

**Comment by jppelteret** [comment]
@masterleinad Thanks for the confirmation!

**Pull request merged**
