### PR TITLE
Check for range of function calls in bfgs tests.

### PR DESCRIPTION
**Pull request by marcfehling**
The `bfgs_05` tests report 134 function calls on our machine instead of 133 in the output file. Other machines on `cdash` report that they need 135 function calls, see https://cdash.dealii.43-1.org/test/9355358.

To me this appears to be a very strict condition for a test. I disable writing the number of function calls into `deallog`.

I'm open for different suggestions. For example, we could still accept a range of function calls (+/- 2 or so, like #13755).

Part of #13703.

### CODE REVIEW

**Comment by kronbichler** [comment]
I agree with @drwells, let us print out a range. Since there is as single size here, let us print the range 130-140 e.g. via https://github.com/dealii/dealii/blob/e92b7c6c6ceb4ab0b4b70fe3df39bb32d312899a/tests/tests.h#L374-L377

**Comment by marcfehling** [comment]
Thank you for your feedback! I gave `check_solver_within_range` a shot.

It's really just the counter of the function calls that the testers complain about. The number of convergence steps remains the same, which I find interesting. Let's leave the rest for now, and come back to it when testers keep failing.

**Review by kronbichler — APPROVED** [review]
I agree on this. Even though we do not output the number of iterations besides the number of function calls, I think this is good enough as BFGS strongly correlates in the two numbers.

**Comment by marcfehling** [comment]
`check_solver_within_range` suppresses the output from the solver class, so we would loose additional information in the output file. https://github.com/dealii/dealii/blob/31b3dae3fcb1062cee521ed99f17fb29213ea84d/tests/tests.h#L379

With additional function calls, the results change as @drwells pointed out. However, as the numbers we are comparing against are close to zero, `numdiff` treats them as the same result.

I kept both commits in this branch. Let me know which one you prefer

**Comment by kronbichler** [comment]
Let us go with this solution, this is fine, as we do print the number of function calls after all.

**Pull request merged**
