### PR TITLE
Rename MappingQGeneric to MappingQ in python interface

### PR DESCRIPTION
**Pull request by agrayver**
Follow up of #12561

### CODE REVIEW

**Review by peterrum — APPROVED** [review]
Looks good to me. Do you want to add a change-log entry?

**Review by kronbichler — APPROVED** [review]

**Review by masterleinad — COMMENTED** [review]
Should `MappingQGenericWrapper` still be a deprecated alias for `MappingQWrapper` for backward compatibility?

**Comment by agrayver** [comment]
> Do you want to add a change-log entry?

I see it as a part of #12561 which is documented already. Do you think it needs a separate one?

>  Should MappingQGenericWrapper still be a deprecated alias for MappingQWrapper for backward compatibility?

The python interface has been around for about one year and I personally doubt there are many production codes that would be affected by this change. That said, creating another alias should be easy. Let me know what you prefer.

**Comment by masterleinad** [comment]
> The python interface has been around for about one year and I personally doubt there are many production codes that would be affected by this change. That said, creating another alias should be easy. Let me know what you prefer.

I think it's just a good idea to do that just as we do in the rest of the codebase.

**Comment by agrayver** [comment]
I've added an alias for the old name. The only problem with solution is that it does not warn a user about deprecation, but I see no way of doing this using builtin functional.

**Review by masterleinad — COMMENTED** [review]
Hmmm... I was more thinking about something like
```
using MappingQGenericWrapper DEAL_II_DEPRECATED = MappingQWrapper;
```
I am not quite sure about the effect, though.

**Comment by agrayver** [comment]
> Hmmm... I was more thinking about something like

We are talking about deprecating python class, aren't we? The solution you showed deals with the internal MappingQGenericWrapper class that a user should never construct from within the C++ program.

**Comment by masterleinad** [comment]
> We are talking about deprecating python class, aren't we? The solution you showed deals with the internal MappingQGenericWrapper class that a user should never construct from within the C++ program.

That's why I said, "I am not quite sure about the effect, though.". I hoped users of the python interface would see that somehow. If there is no way to show deprecation warnings within the python interface, I am not opposed to breaking backward compatibility there.

**Comment by Rombur** [comment]
I am fine changing the name without deprecating but if we really want to deprecate `MappingQGeneric`, I think the way to go is to have `MappingQGenericWrapper` derive from ``MappingQGeneric` and have the constructor print a message that the class is deprecated. You will also need to duplicate `export_mapping` since now you have two classes.

**Comment by agrayver** [comment]
Should I remove the last commit?

**Comment by Rombur** [comment]
> Should I remove the last commit?

Yes, I think so.

**Comment by agrayver** [comment]
Here we go.

**Review by masterleinad — APPROVED** [review]

**Pull request merged**
