### PR TITLE
Force to rerun tests in check_01_compiler_features.cmake

### PR DESCRIPTION
**Pull request by masterleinad**
This improves #6490. We already had a test for a `constexpr` support in `std::max`. Hence, there is no need to duplicate that.
Also ICC18 has `constexpr` support in `std::max` if `CXX17` support is requested, but not for `CXX14`.
To avoid similar problems this PR forces to rerun all tests (that depend on a version flag) in `check_01_compiler_features.cmake` instead of using the cached result.

### CODE REVIEW

**Comment by masterleinad** [comment]
Also rerun the attribute `deprecated` checks since they also depend on the version requested.

**Comment by tamiko** [comment]
Alternatively, we could also go the extra mile and introduce a "CLEAR" mechanism (as we do for our feature configuration) to clear compiler/processor/platform checks altogether if the compiler flags change. I actually like this idea. Shall we go that route?

**Comment by masterleinad** [comment]
> Alternatively, we could also go the extra mile and introduce a "CLEAR" mechanism (as we do for our feature configuration) to clear compiler/processor/platform checks altogether if the compiler flags change. I actually like this idea. Shall we go that route?

Yes, that sounds good to me. In my opinion, running `CMake` is so cheap that is doesn't really hurt to rerun these tests and be on the safe side.

**Comment by tamiko** [comment]
@masterleinad Let me try to propose an alternative solution.

**Comment by masterleinad** [comment]
> @masterleinad Let me try to propose an alternative solution.

Thanks!

**Comment by tamiko** [comment]
*sigh* How I love the interoparability of icc with gcc-7:
```
/opt/intel/compilers_and_libraries_2018.2.199/linux/bin/intel64/icpc    -DDEAL_II_HAVE_CXX11_FUNCTIONAL_LLVMBUG20084_OK -std=c++17 -MD -MT CMakeFiles/cmTC_98bb1.dir/src.cxx.o -MF CMakeFiles/cmTC_98bb1.dir/src.cxx.o.d -o CMakeFiles/cmTC_98bb1.dir/src.cxx.o -c src.cxx
In file included from src.cxx(2):
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/functional(139): error: class template "std::_Mem_fn_traits" has already been defined
  _GLIBCXX_MEM_FN_TRAITS(noexcept, true_type, true_type)
  ^
```

**Comment by masterleinad** [comment]
> sigh How I love the interoparability of icc with gcc-7:

Yes, this is why I use older gcc versions....

**Comment by drwells** [comment]
How annoying. Thanks for cleaning up my mess.

**Pull request closed without merging**
