### PR TITLE
Fix FiniteElement::has_support_points() for FE_Nothing.

### PR DESCRIPTION
**Pull request by bangerth**
@OresteMarquis This is what we were talking about at the workshop last week. Would you like to write a patch that similarly adjusts the other `has_*()` functions in that file?

### CODE REVIEW

**Comment by OresteMarquis** [comment]
Yes absolutely, it will be done tomorrow hopefully!

**Review by kronbichler — APPROVED** [review]

**Comment by bangerth** [comment]
Ping?

**Comment by kronbichler** [comment]
You could have merged this yourself, as I already approved it, but I'm happy to merge now.

**Comment by bangerth** [comment]
@kronbichler I just don't like merging my own patches, even if approved. Longstanding issue with my brain...

**Pull request merged**
