### PR TITLE
Allows the CMake option DEAL_II_WITH_CXX11 to be enabled on Windows.

### PR DESCRIPTION
**Pull request by tulioligneul**
When the CMake option DEAL_II_WITH_CXX11 is enabled on Windows, don't execute
the test "_check_version("11" "0x")" that checks the compiler flag "-std=c++11".
Since the Visual Studio's compiler doesn`t have a flag to enable/disable c++11,
this test was deactivated. Also, it is made sure that the tests with "CHECK_CXX_SOURCE_COMPILES"
for c++11 are properly executed.

### CODE REVIEW

**Comment by drwells** [comment]
I am surprised that we did not run into this issue when we were testing 8.5 on Windows. @tjhei ?

**Comment by tjhei** [comment]
I am not sure if this is the best case to fix things, @tamiko ? I know starting from VS2015 there are flags like ``/std:c++14``.

> I am surprised that we did not run into this issue when we were testing 8.5 on Windows. @tjhei ?

My test coverage on windows since the 8.5 release has been lacking. *blush*. I can probably test things this weekend.

**Comment by tjhei** [comment]
Note: this PR is also to the wrong branch. Note that master compiles correctly, so I am not sure this patch is needed.

**Comment by drwells** [comment]
@tjhei I think I had to add `/std:c++14` to get things to work but I'll check.

**Comment by tjhei** [comment]
> tjhei I think I had to add /std:c++14 to get things to work but I'll check.

I do not need to mess with flags for MSVC 2015 and 2017.

**Comment by drwells** [comment]
I think that we should close this PR. We can currently compile the library in C++11 mode on Windows. Regardless, 8.5 is long done now and we should not add more commits to that branch.

Thoughts?

**Comment by tjhei** [comment]
I do not have problems without this patch, so I agree.

**Pull request closed without merging**
