### PR TITLE
Post release branch: switch DEAL_II_DEPRECATED_EARLY over to DEAL_II_DEPRECATED

### PR DESCRIPTION
**Pull request by tamiko**
In reference to #15383

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

**Review by marcfehling — APPROVED** [review]

**Review by tjhei — APPROVED** [review]

**Comment by bangerth** [comment]
I forgot -- is this supposed to happen pre-release?

**Comment by drwells** [comment]
Nope - `DEPRECATED_EARLY` gets promoted to `DEPRECATED` right after we branch.

**Comment by bangerth** [comment]
Right -- I actually meant post-branch (but on the master branch). I assume you already did the branch?

**Comment by drwells** [comment]
Ah - yes, we now have a separate 9.5 branch, so merging this would be OK (but Matthias asked that we pause merges to master to let the CI finish)

**Comment by tamiko** [comment]
@bangerth @drwells Correct, this must happen after we branched. But indeed we did :-)

**Review by kronbichler — APPROVED** [review]

**Pull request merged**
