### PR TITLE
Let FE::clone() return a std::unique_ptr.

### LINKED ISSUE #4209: Change `clone`s to return `std::unique_ptr`s
For example, in #4207, instead of

```cpp
clone_base_elements += Threads::new_task ([ &,i,ind] ()
{
  base_elements[ind]
    = std::make_pair (std::shared_ptr<FiniteElement<dim,spacedim>>(fes[i]->clone()),
                      multiplicities[i]);
});
```

we could just write

```cpp
clone_base_elements += Threads::new_task ([ &,i,ind] ()
{
  base_elements[ind] = {fes[i]->clone(), multiplicities[i]};
});
```

and still have the memory managed correctly in all circumstances (if any destructor is thrown the `FiniteElement<dim> *`'s destuctor will be ~~thrown~~ run).

While this change would not be backwards compatible, I am not aware of any user projects (from my list of stars on GitHub) that use this function. We would break (in a small way) every user defined `FiniteElement` (and `Mapping`) that is not already in the repository. Thoughts?

I am usually not in favor of breaking changes, but this one is extremely useful, unlikely to break user codes, and is relatively easy to fix in the case that it does, so I think we should consider it.

edit: delete redundant sentence
edit: fix word choice

### PR DESCRIPTION
**Pull request by bangerth**
This fixes #4209. The only interesting part is the fact that I can't use
std_cxx14::make_unique() for FE_Enriched because it wants to call a
constructor that is not public. So I have to make the cast from a
pointer to the std::unique_ptr by hand. The rest is boring and
mechanical.

The patch by itself fails a lot of tests because the current master
branch is broken. But when tested together with #4464, I have only
3 failing tests that are all unrelated to the best of my knowledge.

### CODE REVIEW

**Comment by drwells** [comment]
My only very minor complaint is that it the indentation looks funny: would you mind moving `clone` up a line where it got split?

**Comment by bangerth** [comment]
Hm, an interesting oddity of astyle that can't deal with the `>>` closing template arguments without a space. I've solved the problem by adding the space instead.

**Comment by davydden** [comment]
> Hm, an interesting oddity of astyle that can't deal with the >> closing template arguments without a space

noticed that as well. `astyle` `@3.0.1` is released in `2017-05-30`, maybe it's time to adopt it ? :smile:

**Comment by drwells** [comment]
I tried running this version of `astyle` and it crashed with exceptions thrown about accessing string entries past the end of an array.

**Comment by davydden** [comment]
> it crashed

too bad...

**Comment by bangerth** [comment]
Let's leave updating astyle to a different PR (see also #4470).

By itself, I consider this current PR ready.

**Pull request merged**
