### PR TITLE
Make indent script work for python bindings

### PR DESCRIPTION
**Pull request by agrayver**
From discussion in #9023 

@bangerth FYI

### CODE REVIEW

**Comment by bangerth** [comment]
Alternatively (and maybe easier), you can run your fixed indentation script and submit the changes in that directory as a separate patch that is merged before this one.

**Comment by agrayver** [comment]
I suggest we postpone this until after #9023 is merged -- I will then update the indent of the entire bindings.

**Comment by agrayver** [comment]
Coming back to this: what should I do? 

Remove contrib/.clang-format permanently and add indent changes to this branch?

**Comment by masterleinad** [comment]
I am not opposed to just removing the file. We might have been a bit too restrictive when disallowing indenting in all these folders. On the other hand, it is a bit strange to have `python-bindings` in the `contrib` folder anyway, but this should not be a concern here.

**Comment by agrayver** [comment]
Hm, I removed the file and ran indent script from the root directory, but it did not change a single file in the contrib folder. Any clue?

**Comment by masterleinad** [comment]
> Hm, I removed the file and ran indent script from the root directory, but it did not change a single file in the contrib folder. Any clue?

Yes, you need to run `./contrib/utilities/indent-all` and also modify that file accordingly beforehand.

**Comment by agrayver** [comment]
Ok, now this has worked!

**Pull request merged**
