### PR TITLE
CMake: Enforce strict build type matching in DEAL_II_(ADD_TEST|SETUP_TARGET)

### LINKED ISSUE #3075: CMake: Enforce matching build types in DEAL_II_ADD_TEST / DEAL_II_SETUP_TARGET
I came across a very interesting problem with (active) cell iterator being used as a member of a class in a user library
```
  template <int dim>
  class Atom
  {
  public:
    Atom();
    typename dealii::DoFHandler<dim>::active_cell_iterator parent_cell;
  };
```

This leads to double free or corruption on GCC in **Release mode** only with the current master branch. The code runs fine when linked against `8.4.1` with GCC or current master with Clang both in Debug and Release modes.

The prerequisites are as follows (if any of those is not the case, problem disappears!)
1. use `Utilities::MPI::MPI_InitFinalize`  in .cc file
2. In the user library, have a default constructor for a class, which contains DoFHandler<dim>::active_cell_iterator
3. link .cc against the library, do not declare and define the class directly inside .cc

A one-dummy-class library with a dummy test which demonstrates the issue can be download from 
https://groups.google.com/group/dealii-developers/attach/3b8b33a54794d/init_finalize.tar.gz?part=0.1&authuser=0 . Currently there is no way to attach this unit test to the library, unless @tamiko knows some tricks how to abuse unit tests to build a single class library.

By doing bisection between now and `8.4.0` I figure out that ec7d6ee1cf00b4dd074bd92e3efcca53e93331f3 by @bangerth is the first commit which demonstrates the issue. This commit is a part of https://github.com/dealii/dealii/pull/2179. 
Previous commit 6461bb7092b2dc18745afadb29f248de434475f6 runs fine both in Debug and Release mode with GCC.

I don't understand how adding an Assert may result in different behaviour during Release build. @bangerth : any ideas (especially given strange prerequisite list)? I think it should still be possible to have an object of `active_cell_iterator` initialized without DoFHandler and alike. We have things like `find_active_cell_around_point` which return iterators. They may fail to find the cell in case of `p::d::Tria`, but this may be a correct behaviour to be processes by a user.

In reference to this post https://groups.google.com/forum/#!topic/dealii-developers/huPy80Fpra4

p.s. appears with deal.II build with Candi and Spack on Ubuntu 16 and 14 with GCC 4.8, 5.4, 6.2.

### PR DESCRIPTION
**Pull request by tamiko**
This pr helps resolving several misconfiguration issues in CMake user projects.
More precisely,

 * the DEAL_II_SETUP_TARGET(target) call now only works if
   CMAKE_BUILD_TYPE is set to Debug, or Release. For all other cases it has to
   be invoked with an explicit argument for the library to use,
   DEAL_II_SETUP_TARGET(target DEBUG|RELEASE).

 * DEAL_II_ADD_TEST(...) strictly requires (also in user projects) that the
   build type to be Debug, Release, or DebugRelease, i.e., the three cases
   supported within the deal.II build system.

Changes:

84501c7 (Matthias Maier, 9 seconds ago)
   add news/changes.h entry

c187884 (Matthias Maier, 3 minutes ago)
   Documentation: Update to latest changes and changes in #1758

e943efb (Matthias Maier, 20 minutes ago)
   CMake: Verbosely error out in DEAL_II_SETUP_TARGET if build type is
   unsupported

dab6b3c (Matthias Maier, 39 minutes ago)
   CMake: Verbosely error out in DEAL_II_ADD_TEST if build types do not match

e3879e2 (Matthias Maier, 83 minutes ago)
   CMake: Bugfix: Throw a verbose error message instead of silently ignoring
   an argument

Closes #3075

### CODE REVIEW

**Comment by tamiko** [comment]
@davydden The issue you encountered is the following:
 - `DEAL_II_INITIALIZE_CACHED_VARIABLES` sets `CMAKE_BUILD_TYPE` to `DebugRelease` (if the library was built with `DebugRelease`. (pr #1758).
 - The subsequent call to `DEAL_II_SETUP_TARGET` chooses the debug library to link against if the build type is set to DebugRelease
 - The call to `DEAL_ADD_TEST` sets up two tests, one for debug and one for release, if the build type is DebugRelease

The behavior of the last two macros is exactly the intended design. The behavior of the first one was changed in #1758 by @asartori86. The rational was to have a nicer default for libraries (build on top of deal.II). This resulted in the following behavior:
```
DEAL_II_INITIALIZE_CACHED_VARIABLES()
# ...
DEAL_II_INVOKE_AUTOPILOT()
```
worked a intended, only build types `Debug` and `Release` are available. Whereas
```
DEAL_II_INITIALIZE_CACHED_VARIABLES()
# ...
# don't use autopilot style macro
```
set the build type to `DebugRelease`.

This pull request "resolves" the situation by throwing an error in the following case:
```
DEAL_II_INITIALIZE_CACHED_VARIABLES()
# ...
# don't use autopilot style macro
DEAL_II_SETUP_TARGET(target) # without DEBUG|RELEASE
```
This makes the error at least obvious.

I'm currently tending to revert the change in @1758 and set the default back to `Debug` instead of `DebugRelease` - assuming that a library user that wants the latter will be able to setup up the build type manually.
Opinions? (Especially @luca-heltai @asartori86 )

**Comment by tjhei** [comment]
The tester doesn't like your changes:
```
FAILED: cd /home/bob/build-clang/tests/metis && /usr/bin/cmake -DDEAL_II_DIR=/home/bob/build-clang -UDIFF_DIR -UNUMDIFF_DIR -UTEST_PICKUP_REGEX -UTEST_TIME_LIMIT /home/bob/source/tests/metis > /dev/null
CMake Error at /home/bob/build-clang/share/deal.II/macros/macro_deal_ii_add_test.cmake:148 (MESSAGE):
  

  DEAL_II_ADD_TEST cannot set up a test with CMAKE_BUILD_TYPE "DebugRelease".
  deal.II was build with CMAKE_BUILD_TYPE "Debug"

  

Call Stack (most recent call first):
  /home/bob/build-clang/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake:237 (DEAL_II_ADD_TEST)
  CMakeLists.txt:5 (DEAL_II_PICKUP_TESTS)
```

**Comment by tamiko** [comment]
@tjhei I forgot to push one last change.

**Comment by davydden** [comment]
@tamiko 

> This pull request "resolves" the situation by throwing an error in the following case:

will it throw and error if `CMAKE_BUILD_TYPE=...` is set when configuring a user library? 

Can you also update the docs with the recommended approach when not using autopilot?
I assume one needs to have one target for debug and one for release, i.e.

```
DEAL_II_SETUP_TARGET(${TARGETLIB_DEBUG})
DEAL_II_SETUP_TARGET(${TARGET_DEBUG})

TARGET_LINK_LIBRARIES(${TARGET_DEBUG}
    ${TARGETLIB_DEBUG}
  )

DEAL_II_SETUP_TARGET(${TARGETLIB_RELEASE})
DEAL_II_SETUP_TARGET(${TARGET_RELEASE})

TARGET_LINK_LIBRARIES(${TARGET_RELEASE}
    ${TARGETLIB_RELEASE}
  )
```
and then the default would work with `Debug` and `Release` tests running properly?

**Comment by tamiko** [comment]
@davydden 

I suggest we first decide on the policy we want to follow before we change corresponding documentation.

> I'm currently tending to revert the change in @1758 and set the default back to Debug instead of DebugRelease - assuming that a library user that wants the latter will be able to set up the build type manually.
Opinions? (Especially @luca-heltai @asartori86 )

**Comment by asartori86** [comment]
> I'm currently tending to revert the change in @1758 and set the default back to Debug instead of DebugRelease - assuming that a library user that wants the latter will be able to set up the build type manually.
> Opinions? (Especially @luca-heltai @asartori86 )

fine for both of us :)

**Comment by tamiko** [comment]
@davydden The macro logic is now in sync with the documentation again.

**Comment by davydden** [comment]
i suppose the recommended workflow in case no build type is specified is
```
DEAL_II_SETUP_TARGET(${TARGETLIB_DEBUG} DEBUG)
DEAL_II_SETUP_TARGET(${TARGET_DEBUG} DEBUG)

TARGET_LINK_LIBRARIES(${TARGET_DEBUG}
    ${TARGETLIB_DEBUG}
  )

DEAL_II_SETUP_TARGET(${TARGETLIB_RELEASE} RELEASE)
DEAL_II_SETUP_TARGET(${TARGET_RELEASE} RELEASE)

TARGET_LINK_LIBRARIES(${TARGET_RELEASE}
    ${TARGETLIB_RELEASE}
  )
```

**Comment by tamiko** [comment]
@davydden It depends on what you try to achieve. For the fully automatic stuff, no. The build type is always set to `Debug`, or `Release`.

**Comment by davydden** [comment]
> It depends on what you try to achieve.

a user library with a single executable and several unit tests to work with `DebugRelease` similar to `deal.II` unit tests (i.e. two librareis, two executables, unit tests compiled in Debug and Release mode).

> For the fully automatic stuff, no

you mean `DEAL_II_INVOKE_AUTOPILOT`? I don't use it.

**Pull request merged**
