### PR TITLE
Only permit use of ld.lld linker when the Clang compiler is used.

### LINKED ISSUE #7811: ld.lld cannot link with openmpi (with enabled fortran support in openmpi)
I've just discovered via `git bisect` that `950cfca3abb5ba36505ed286f4ab2424bb2cb8f9` (#7795) may cause failure in the configuration phase. This is on my linux machine, which previously used `-fuse-ld=gold`. I have a `spack`-built LLVM in path (loaded via modules) which, I guess, gets detected and causes the flag `-fuse-ld=lld` to appear in the linker line. I see that there's already a check to see that a basic program can compile though... what can we do to make this more robust?

```
-- Performing Test DEAL_II_HAVE_USABLE_FLAGS_DEBUG
-- Performing Test DEAL_II_HAVE_USABLE_FLAGS_DEBUG - Failed
CMake Error at cmake/setup_finalize.cmake:95 (MESSAGE):
  

    Configuration error: Cannot compile a test program with the final set of
    compiler and linker flags:
      CXX flags (DEBUG): -pedantic -fPIC -Wall -Wextra -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wsuggest-override -Wswitch -Wsynth -Wwrite-strings -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -Wno-class-memaccess -fopenmp-simd -std=c++17 -Wno-unused-local-typedefs -O0 -ggdb -Wa,--compress-debug-sections
      LD flags  (DEBUG): -Wl,--as-needed -rdynamic -fuse-ld=lld -L/usr/lib/gcc/x86_64-linux-gnu/8/ -lgfortran -ggdb
      LIBRARIES (DEBUG): <path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/boost-1.69.0-gzvs7exfbtdm4abn5ih2tz4x7uhewjv4/lib/libboost_iostreams-mt.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/boost-1.69.0-gzvs7exfbtdm4abn5ih2tz4x7uhewjv4/lib/libboost_serialization-mt.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/boost-1.69.0-gzvs7exfbtdm4abn5ih2tz4x7uhewjv4/lib/libboost_system-mt.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/boost-1.69.0-gzvs7exfbtdm4abn5ih2tz4x7uhewjv4/lib/libboost_thread-mt.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/boost-1.69.0-gzvs7exfbtdm4abn5ih2tz4x7uhewjv4/lib/libboost_regex-mt.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/boost-1.69.0-gzvs7exfbtdm4abn5ih2tz4x7uhewjv4/lib/libboost_chrono-mt.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/boost-1.69.0-gzvs7exfbtdm4abn5ih2tz4x7uhewjv4/lib/libboost_date_time-mt.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/boost-1.69.0-gzvs7exfbtdm4abn5ih2tz4x7uhewjv4/lib/libboost_atomic-mt.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libmuelu-adapters.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libmuelu-interface.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libmuelu.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libifpack2.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libanasazitpetra.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libModeLaplace.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libanasaziepetra.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libanasazi.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libmapvarlib.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libsuplib_cpp.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libsuplib_c.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libsuplib.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libsupes.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libaprepro_lib.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libchaco.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libio_info_lib.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libIonit.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libIotr.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libIohb.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libIogn.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libIovs.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libIoexo_fac.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libIofx.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libIoex.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libIoss.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libnemesis.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libexoIIv2for32.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libexodus_for.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libexodus.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libamesos2.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libbelostpetra.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libbelosepetra.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libbelos.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libml.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libifpack.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libzoltan2.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libamesos.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libgaleri-xpetra.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libgaleri-epetra.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libaztecoo.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libxpetra-sup.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libxpetra.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libepetraext.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libtrilinosss.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libtpetraext.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libtpetrainout.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libtpetra.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libkokkostsqr.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libtpetraclassiclinalg.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libtpetraclassicnodeapi.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libtpetraclassic.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libtriutils.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libzoltan.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libepetra.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libsacado.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libkokkoskernels.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libteuchoskokkoscomm.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libteuchoskokkoscompat.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libteuchosremainder.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libteuchosnumerics.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libteuchoscomm.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libteuchosparameterlist.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libteuchoscore.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libkokkosalgorithms.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libkokkoscontainers.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libkokkoscore.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/trilinos-12.12.1-intry6vbyyffsvsqo76xfzmbf4ymtweg/lib/libgtest.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/matio-1.5.13-5hyqbnpbfjurzwdqfehjuzf37n4i2xac/lib/libmatio.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/netcdf-4.6.2-6k5yvpktnlm7jsa2zib5uytmsah4wotr/lib/libnetcdf.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/mumps-5.1.1-3mmkzqn2ggqh2dw5fdizzdqwhn4fp72c/lib/libdmumps.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/mumps-5.1.1-3mmkzqn2ggqh2dw5fdizzdqwhn4fp72c/lib/libmumps_common.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/mumps-5.1.1-3mmkzqn2ggqh2dw5fdizzdqwhn4fp72c/lib/libpord.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/netlib-scalapack-2.0.2-c4oh6ijycn3ghtybd3xafasg57ahmb3c/lib/libscalapack.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/hypre-2.15.1-5a3ks3pt2zsvssxdvft54vj2iv5zzldp/lib/libHYPRE.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/hdf5-1.10.4-ozy5y574qva5tm4fgseqsm577btcn4t5/lib/libhdf5.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/zlib-1.2.11-dndjvh6fpzdr3thkyvbemikb52dos4ss/lib/libz.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/hdf5-1.10.4-ozy5y574qva5tm4fgseqsm577btcn4t5/lib/libhdf5_hl.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/parmetis-4.0.3-zweeewwr6oxq7fy5b5v5hbsyc3gr5ysr/lib/libparmetis.so;dl;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/suite-sparse-5.3.0-qwizyk56yyfgs64jncyt7wmuca5w7alw/lib/libumfpack.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/suite-sparse-5.3.0-qwizyk56yyfgs64jncyt7wmuca5w7alw/lib/libcholmod.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/suite-sparse-5.3.0-qwizyk56yyfgs64jncyt7wmuca5w7alw/lib/libccolamd.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/suite-sparse-5.3.0-qwizyk56yyfgs64jncyt7wmuca5w7alw/lib/libcolamd.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/suite-sparse-5.3.0-qwizyk56yyfgs64jncyt7wmuca5w7alw/lib/libcamd.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/suite-sparse-5.3.0-qwizyk56yyfgs64jncyt7wmuca5w7alw/lib/libsuitesparseconfig.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/suite-sparse-5.3.0-qwizyk56yyfgs64jncyt7wmuca5w7alw/lib/libamd.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/metis-5.1.0-2og2oed3ucpn7ky77viwsj2pzmzdqjjy/lib/libmetis.so;rt;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/adol-c-develop-2rs6raysyorckdztjkb3tdot4p42xgra/lib64/libadolc.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/p4est-2.0-wry6yho5f766k6crqacoq5kkeyad4v6x/lib/libp4est.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/p4est-2.0-wry6yho5f766k6crqacoq5kkeyad4v6x/lib/libsc.so;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/openblas-0.3.5-vb72x3uulzxakm4iv5sw7oelq5dz7cfc/lib/libopenblas.so;gfortran;m;quadmath;c;<path/to/spack>/opt/spack/linux-ubuntu18.10-x86_64/gcc-8.2.0/intel-tbb-2019.2-rd4a7jt5pbxyremzsayu7qtzv7vwb2jh/lib/libtbb_debug.so

Call Stack (most recent call first):
  cmake/macros/macro_verbose_include.cmake:19 (INCLUDE)
  CMakeLists.txt:132 (VERBOSE_INCLUDE)

-- Configuring incomplete, errors occurred!
```

### PR DESCRIPTION
**Pull request by jppelteret**
Fixes #7811

### CODE REVIEW

**Comment by jppelteret** [comment]
I would ask that this be merged asap, and perhaps the more elegant solution proposed in https://github.com/dealii/dealii/issues/7811#issuecomment-473207037 be introduced in a later PR.

**Comment by tamiko** [comment]
Actually, no this doesn't fix #7811 at all.
 - Even with the old version ld.lld was only selected if clang/clang++ was the toolchain.
 - I still cannot compile with ld.lld + clang/clang++ + mpi.

The best course of action would be to simply revert the original logic and let the use set ld.lld by hand.

@tjhei *ping*

**Comment by jppelteret** [comment]
> Actually, no this doesn't fix #7811 at all.

Well, it fixes my permutation of #7811... 

> I still cannot compile with ld.lld + clang/clang++ + mpi.

Out of curiosity, is your entire software stack built using clang?

**Comment by jppelteret** [comment]
> Even with the old version ld.lld was only selected if clang/clang++ was the toolchain.

Not true. As  I was using GCC as my compiler but LLVM was in the path. I see that I didn't explain this clearly though.

**Comment by tamiko** [comment]
> Out of curiosity, is your entire software stack built using clang?

That's a good point!

Not on my development machine (here, I use a mixture of clang/gcc for packages). I will give this a try on the tester (recompiling the entire environment with clang + ld.lld).

> Not true. As I was using GCC as my compiler but LLVM was in the path. I see that I didn't explain this clearly though.

I am a bit surprised by this, because gcc as of version 8.3.0 does not recognize the -fuse-ld=ld.lld option:
```
c++: error: unrecognized command line option ‘-fuse-ld=lld’; did you mean ‘-fuse-ld=bfd’?
```

**Comment by tamiko** [comment]
Ah!
```
 5122 2018-11-08  Roman Geissler  <roman.geissler@amadeus.com>                         
 5123                                                                                  
 5124     * collect2.c (linker_select):  Add USE_LLD_LD.                               
 5125     (ld_suffixes): Add ld.lld.                                                   
 5126     (main): Handle -fuse-ld=lld.                                                 
 5127     * common.opt (-fuse-ld=lld): New option.                                     
 5128     * doc/invoke.texi (-fuse-ld=lld): Document.                                  
 5129     * opts.c (common_handle_option): Handle OPT_fuse_ld_lld.
```
Way too modern for my taste!

**Comment by tjhei** [comment]
@jppelteret thanks for providing the quick work-around.

@tamiko it is interesting that google doesn't have anything about your error message. What would be needed to discover your error during configure time? We already have a special logic for gold in configure_1_mpi.cmake...

**Comment by tamiko** [comment]
@tjhei Good point. Working on it.

**Comment by tamiko** [comment]
@tjhei I have added a corresponding check in #7816. I have a hard time finding the corresponding missing feature bug again for lld..

**Pull request merged**
