### PR TITLE
Let the user specify the zlib compression level.

### PR DESCRIPTION
**Pull request by drwells**
For a simple linear example with about 10,000 degrees of freedom, I saw that saving the output took about 75% of the time with the current (maximum compression) setting. It only takes about 10% of the time with the speedy version.

### CODE REVIEW

**Comment by bangerth** [comment]
Yes, this makes sense. Can you please fix the indentation (https://travis-ci.org/dealii/dealii/builds/73976383) and add an entry to doc/news/changes.h?

**Comment by drwells** [comment]
Done. Do you have any recommendations for writing some accompanying tests?

**Comment by guidokanschat** [comment]
To be honest, I am not sure if there is any reasonable way of testing. If some minor issue changes (roundoff errors), the binary output will be different in an unrecognizable way.

**Comment by drwells** [comment]
I am not sure either, but at a minimum I can check that the flags do not cause errors in zlib.

**Comment by guidokanschat** [comment]
That could be a good idea.

**Comment by bangerth** [comment]
I don't recall what we do to test VTU format in the current tests (though it should be easy to look up). One way you can reliably test this is if you just output a vector with known values, e.g. a nodal vector with values `[0, 1, 2, ..., ndofs-1]`. For reasonably small meshes, all of these will be representable exactly with floating point numbers, and so no round-off comes into play. Such a vector should be reliably compressible independent of platform and compiler.

**Comment by drwells** [comment]
It looks like several tests just embed base64 data, so I did something similar.

**Comment by bangerth** [comment]
We haven't had trouble with the other tests. If it works there, it should work here. Thanks!

**Pull request merged**
