### PR TITLE
Unit test for  GridTools::compute_point_locations in simplex meshes

### PR DESCRIPTION
**Pull request by lwy5515**
Based on #11514 . This is a unit test for `GridTools::compute_point_locations` in simplex meshes.

### CODE REVIEW

**Review by peterrum — APPROVED** [review]

**Comment by drwells** [comment]
We need to rebase.

**Comment by lwy5515** [comment]
Do I need to wait for possible changes from #11514 ?

**Comment by bangerth** [comment]
Yes, let's get #11514 merged first, then rebase this.

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
The `multigrid/transfer_matrix_free_06.mpirun=15.debug` test timed out. I'll take that as unrelated. We should probably revisit that test and see whether we can make it quicker -- 10 minutes with 15 cores is quite a lot of CPU time.

**Comment by tjhei** [comment]
> The `multigrid/transfer_matrix_free_06.mpirun=15.debug` test timed out. I'll take that as unrelated.

But this PR ended up breaking master, by the way:
```
/jenkins/workspace/dealii_master/tests/simplex/compute_point_locations_01.cc:37:3: error: ‘GridGenerator’ has not been declared
   GridGenerator::subdivided_hyper_cube_with_simplices(tria, 1);
```

**Comment by bangerth** [comment]
Hm, apologies for not looking closely enough :-( Only one of the 12 checks failed, and I believe that the only test that failed was the `multigrid/transfer_matrix_free_06.mpirun=15.debug` one that had been mentioned in other PRs before. Unfortunately, the Jenkins output is no longer available, so I can't see where I went wrong :-(

**Pull request merged**
