### PR TITLE
Enable set up of active_cell_index_partitioner for p:s:T

### PR DESCRIPTION
**Pull request by peterrum**
~For now only locally-owned cells and a single halo are considered.~

Needed by #11857.

### CODE REVIEW

**Review by drwells — APPROVED** [review]

**Comment by tjhei** [comment]
Not sure what is going on with CU here: we quicktests with mpi are timing out, even after restart.

**Comment by peterrum** [comment]
OK. The test actually dead-locked because of https://github.com/dealii/dealii/pull/10529 (`p:s:T` without artificial cells). I now have also included a specialization for this case.

**Review by kronbichler — APPROVED** [review]

**Comment by tjhei** [comment]
for the record, which of the tests was that?

**Comment by peterrum** [comment]
> for the record, which of the tests was that?

`tests/quick_tests/step-metis.cc` and others that did use p:s:T without artificial cells.

**Comment by kronbichler** [comment]
I guess we are ready here, let us merge now.

**Pull request merged**
