### PR TITLE
CMake: Bugfix: Use correct cmake variable in external projects

### PR DESCRIPTION
**Pull request by tamiko**
In macros for external projects we have to use
  DEAL_II_USER_DEFINITIONS
instead of
  DEAL_II_DEFINITIONS

In reference to #4880

### CODE REVIEW

**Comment by tamiko** [comment]
I have added a basic functionality check to `a-framework`.

**Comment by drwells** [comment]
I like your branch name :)

This just makes the 3.9 logic the same as 3.8, i.e., doing the equivalent to

```cmake
    SET_PROPERTY(TARGET ${_target} APPEND PROPERTY
      COMPILE_DEFINITIONS "${DEAL_II_USER_DEFINITIONS};${DEAL_II_USER_DEFINITIONS_${_build}}"
      )
```
right?

**Comment by drwells** [comment]
I don't have a copy of cmake 3.9 yet so I cannot fully test this, but it looks right and everything works on my machine (with 3.8).

**Comment by tamiko** [comment]
@drwells It does. And yes, this fixes the error on the testing site (tested there).

**Pull request merged**
