### PR TITLE
Fix #6756

### LINKED ISSUE #6756: Example/Tutorial Step-51 Hits An Assertion Failure
The version of Deal.II is 9.0.0 release, and it's built under Debug mode.
Step 51 throws an exception regarding dimension mismatch. The following is the output message from running step 51:

```
Solving with Q1 elements, adaptive refinement
=============================================

Cycle 0:
   Number of degrees of freedom: 80
   Number of BiCGStab iterations: 37

--------------------------------------------------------
An error occurred in line <7271> of file <<hidden path>/Downloads/dealii/dealii-9.0.0/include/deal.II/numerics/vector_tools.templates.h> in function
    void dealii::VectorTools::internal::do_integrate_difference(const dealii::hp::MappingCollection<dim, spacedim> &, const DoFHandlerType &, const InVector &, const Function<spacedim> &, OutVector &, const dealii::hp::QCollection<dim> &, const dealii::VectorTools::NormType &, const Function<spacedim> *, const double) [dim = 2, InVector = dealii::Vector<double>, OutVector = dealii::Vector<float>, DoFHandlerType = dealii::DoFHandler<2, 2>, spacedim = 2]
The violated condition was: 
    exact_solution.n_components==n_components
Additional information: 
    Dimension 2 not equal to 3.

Stacktrace:
-----------
#0  <hidden path>/.local/dealii/debug-9.0.0/lib/libdeal_II.g.so.9.1.0-pre: 
#1  <hidden path>/.local/dealii/debug-9.0.0/lib/libdeal_II.g.so.9.1.0-pre: void dealii::VectorTools::integrate_difference<2, dealii::Vector<double>, dealii::Vector<float>, 2>(dealii::DoFHandler<2, 2> const&, dealii::Vector<double> const&, dealii::Function<2, double> const&, dealii::Vector<float>&, dealii::Quadrature<2> const&, dealii::VectorTools::NormType const&, dealii::Function<2, double> const*, double)
#2  ./step-51.debug: Step51::HDG<2>::postprocess()
#3  ./step-51.debug: Step51::HDG<2>::run()
#4  ./step-51.debug: main
--------------------------------------------------------

[1]    30001 abort (core dumped)  ./step-51.debug
```

Seems the underlying FE and `Function` object fed to `VectorTools::integrate_difference` have different numbers of components. This doesn't look like intentional (i.e., unlike in some other steps, we do something wrong intentionally to see exception handling).

Fix the number of components that initializes parent `Function` object [in line 197](https://github.com/dealii/dealii/blob/master/examples/step-51/step-51.cc#L197) seems to resolve the issue.

Thanks for this amazing library!

### PR DESCRIPTION
**Pull request by piyueh**
Fix issue #6756.

### CODE REVIEW

**Comment by tamiko** [comment]
@piyueh Hi! One minor thing before we can merge: You have to reformat your one-line change slightly. Have a look at [1], or even better run the script `./contrib/utilitites/indent` (from within the deal.II source directory).

[1] https://travis-ci.org/dealii/dealii/builds/392027226?utm_source=github_status&utm_medium=notification

**Comment by piyueh** [comment]
Thank you @tamiko! I've updated the change.

**Comment by bangerth** [comment]
Yes, great!

I think you should get credit for the patch in a public way -- it's fixing a very visible bug, after all. Would you mind writing an entry in `doc/news/changes/minor` that describes the fix?

**Comment by piyueh** [comment]
Thank you @bangerth! I've updated the changelog as suggested. However, it seems there's a conflict to the current state of the master branch. I'll try to resolve the conflict.

**Comment by piyueh** [comment]
I've rebased the PR to the current state of the master branch and resolved the conflict. Thanks!

**Comment by masterleinad** [comment]
Thanks for fixing!

**Comment by masterleinad** [comment]
> @bangerth ... and the moment I reenabled Travis CI as mandatory status check (after it performed well for about two weeks), it failed again. sigh

Simple enough to restart `Travis`.

**Pull request merged**
