### PR TITLE
Move implementation of ConsenusAlgorithm into mpi.templates.h

### PR DESCRIPTION
**Pull request by peterrum**
This PR does nothing than moving the implementation from `mpi.cc` to `mpi.templates.h` so that users can write their own `ConsensusAlgorithmProcess`. The next PR will actually contain something useful (which needs this changes)!

### CODE REVIEW

**Comment by tjhei** [comment]
somewhat related: have you considered moving Consensus* into a separate header/.cc? It has becoming quite a lot of code that most users don't need.

**Comment by peterrum** [comment]
> somewhat related: have you considered moving Consensus* into a separate header/.cc? It has becoming quite a lot of code that most users don't need.

If you think it would be better, I can do that. But will lead again to cyclic dependency of the files...

**Comment by tjhei** [comment]
> If you think it would be better, I can do that. But will lead again to cyclic dependency of the files...

That's annoying. Is this because some implementation inside mpi.cc depends on the consensus algorithms?

**Comment by peterrum** [comment]
@tjhei Yes. The function `compute_point_to_point_communication_pattern` is using it here:

https://github.com/dealii/dealii/blob/27eb58067b3dc87d5532377cbbf90e490e0a5ce9/source/base/mpi.cc#L304-L309

and probably soon `compute_n_point_to_point_communications` (see issue #9452).

**Comment by tjhei** [comment]
> Yes. The function `compute_point_to_point_communication_pattern` is using it here:

But that is in the mpi.cc only, so we should be able to move it.

**Pull request merged**
