### PR TITLE
Do not allow assigning to rvalue references of VectorizedArray.

### PR DESCRIPTION
**Pull request by bangerth**
This implements the suggestion I made in https://github.com/dealii/dealii/pull/14839#issuecomment-1454734440.

### CODE REVIEW

**Comment by bangerth** [comment]
Ah well, look at this. It actually works!

**Comment by sebproell** [comment]
@bangerth Although this change would have fixed the very specific problem we had in #14839, let me note that it is not consistent with other numeric types such as `std::complex` or Sacado's `DFad`. 

Also, isn't this an incompatible change? Yes, it is likely a bug or unintended if a user code assigns to a temporary, just wondering if deprecation is more appropriate.

**Comment by bangerth** [comment]
I'm thinking of it as a bug that we can just fix. It is almost certainly unintended if anyone used the old semantics.

As for other classes: This is true. I don't know whether I value avoiding mistakes or consistency with other classes more.

**Review by masterleinad — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]
I guess the situation where this would happen before was almost always unintended, and the error would have helped to trace down the problem, so let us go with this code directly.

**Pull request merged**
