### PR TITLE
Document the minimal supported MPI version

### PR DESCRIPTION
**Pull request by masterleinad**
Related to #7677. Looking at `FindMPI.cmake` it doesn't seem feasible to check for the `MPI` version being at least 2.0 since there seem to be cases where we fail to detect the correct version.

### CODE REVIEW

**Comment by drwells** [comment]
Are we actually compatible with MPI 2.0? I have no idea if we are using any newer features or not.

**Comment by masterleinad** [comment]
All I can say is that we test for `2.2` in `mpi.cc`. Hence, I guess that someone tried build with something less than this at least at some point.

**Comment by masterleinad** [comment]
For compiling with `OpenMPI-1.2.9` (`MPI-2.0`) I needed some changes:
- I could only find `MPI_Comm_create_group` used in `ScaLAPACKMatrix::copy_from` and `ScaLAPACKMatrix::copy_to` in the `MPI-3.0` documentation. Hence, these function are declared as not implemented if the detected `MPI` version is less than `3.0`.
- `MPI_Isend` uses a non-`const` buffer before `MPI-3.0`. Hence, we need the `DEAL_II_MPI_CONST_CAST` macro in a couple more places.

**Comment by drwells** [comment]
Thanks for checking (and digging up this ancient version of openmpi!)

**Pull request merged**
