### PR TITLE
add step-34 DOI

### PR DESCRIPTION
**Pull request by luca-heltai**

### CODE REVIEW

**Comment by tjhei** [comment]
I think we should define guidelines on what to include in the zenodo upload: a CMakeLists.txt would certainly be helpful. (I know that it is too late now here)

**Comment by luca-heltai** [comment]
I followed the same strategies of the majority of the other ones. Only step-57 included a CMakeLists.txt...

**Comment by jppelteret** [comment]
I agree that I should have added a `CMakeLists.txt` to `step-44`'s entry. A set of guidelines could help ensure that this doesn't happen again.

**Comment by tjhei** [comment]
> Only step-57 included a CMakeLists.txt...

Yeah, I realized my mistake too late.

**Comment by tjhei** [comment]
See https://github.com/dealii/dealii/wiki/Code-DOI-best-practices

**Pull request merged**
