### PR TITLE
Fix python bindings configuration for new boost

### PR DESCRIPTION
**Pull request by agrayver**
In relation to #8961 

@masterleinad is this what you meant?

### CODE REVIEW

**Comment by masterleinad** [comment]
Nearly. I was suggesting to bump the required version to 1.59 since this is what we require elsewhere, keep the current logic for <1.67 and only add `${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR}` for version >=1.67

**Comment by agrayver** [comment]
Done. I don't understand the purpose of "LIST(REMOVE_ITEM ...) ... LIST(APPEND ...)" so I kept it for the old branch only. The _FIND_PACKAGE line alone suffices for the CMake 3.10 and 3.14 and, I believe, provides the same behaviour if we add keyword REQUIRED.

**Comment by agrayver** [comment]
ping

**Comment by masterleinad** [comment]
Can you confirm that this works for boost version <1.67.0 when removing
```
  LIST(REMOVE_ITEM CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/modules/)
  SET(Boost_FOUND)
  # Use the low level _FIND_PACKAGE function instead of our wrapper
  LIST(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/modules/)
```
? This is what I wanted to check before merging.

**Comment by agrayver** [comment]
> Can you confirm that this works for boost version <1.67.0 when removing

Yes, it does work:

```
-- Setting up python bindings
-- Found PythonInterp: /home/ag/anaconda3/envs/gofem/bin/python (found version "3.7.3") 
-- Found PythonLibs: /home/ag/anaconda3/envs/gofem/lib/libpython3.7m.so (found version "3.7.3") 
-- Boost 1.59 found.
-- Found Boost components:
   python
-- Setting up python bindings - Done
```


Shall I remove these lines?

**Comment by masterleinad** [comment]
Yes, that appears to be OK.

**Comment by agrayver** [comment]
Done.

**Pull request merged**
