### PR TITLE
tests/symengine/batch_optimizer: add output variants

### PR DESCRIPTION
**Pull request by tamiko**
Add output variants for the symengine/batch_optimizer that fails due to
changes in the libstdc++ library between version 9 and 10.

Let's simply add an output variant for the time being. The proper fix
will be to change these tests to not produce output depending on the
standard library or compiler that is being used.

### CODE REVIEW

**Comment by jppelteret** [comment]
I'd like to get some clarification on the potential overlap between this and https://github.com/dealii/dealii/pull/10162 before proceeding.

**Comment by tamiko** [comment]
@jppelteret Wow, I didn't see #10162 at all. I remember looking at the description but I thought it were an issue not a pull request. Testing the proper fix as we speak.

**Comment by jppelteret** [comment]
No worries. Thanks for testing it. I hope it sorts this all out.

**Comment by tamiko** [comment]
Obsolete :smile_cat:

**Pull request closed without merging**
