### PR TITLE
Change TensorProductPolynomialsConst from "is-a" to "has-a" TensorProductPolynomials

### PR DESCRIPTION
**Pull request by GrahamBenHarper**
This is almost exactly the same as #8742 except for `TensorProductPolynomialsConst` instead.

Future work would involve modifying the classes to remove the need for friendship with `TensorProductPolynomials`. I'd like to push this through before #8723 so I may base that PR off this work and derive all 4 classes from `ScalarPolynomialsBase` in one PR.

All tests for `fe` and `base` are successful on my end.

### CODE REVIEW

**Comment by GrahamBenHarper** [comment]
On second thought, since it looks like #8723 has passed all tests, I can rebase this after #8723 merges. That may be easier.

**Comment by bangerth** [comment]
Please rebase since there are currently some merge conflicts.

**Comment by GrahamBenHarper** [comment]
All `base` and `fe` tests pass on my end!

**Comment by GrahamBenHarper** [comment]
I'll add that as a comment in #8768. I'm not certain that the renumbering functionalities for TPPBubbles and TPPConst are used in the testsuite.

**Pull request merged**
