### PR TITLE
C++ cleanup, p9: Remove SchurMatrix

### PR DESCRIPTION
**Pull request by tamiko**
In reference to #4212

### CODE REVIEW

**Comment by drwells** [comment]
Did we ever formally deprecate this class? I don't see a `DEAL_II_DEPRECATED` attribute.

**Comment by tamiko** [comment]
@drwells I forgot to add the deprecation attribute in 60c6f427. But I am not willing to compromise ;-)

**Comment by bangerth** [comment]
Since there was no deprecation, I think it would be nice to have a changelog entry that says that this class was removed and what people should use instead.

OK to merge if you add such an entry (or will do so as part of another PR).

**Comment by tamiko** [comment]
@bangerth There will be a detailed changelog entry explaining what to do for every of the dozen classes. (It's the one with the TODO in the first pull request).

**Pull request merged**
