### PR TITLE
Fix many of the output files for the tests of sacado and adolc

### PR DESCRIPTION
**Pull request by rezarastak**
While working on #8011, I ran the CI tests for Sacado and Adol-C and observed strange failures such as:
```
dealii/build$ ctest -R sacado/physics_functions_01_2.debug -V
UpdateCTestConfiguration  from :/mnt/scratch/repos/dealii/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/mnt/scratch/repos/dealii/build/DartConfiguration.tcl
Test project /mnt/scratch/repos/dealii/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 7505
    Start 7505: sacado/physics_functions_01_2.debug

7505: Test command: /usr/bin/cmake "-DTRGT=physics_functions_01_2.debug.diff" "-DTEST=sacado/physics_functions_01_2.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/reza/scratch/repos/dealii/build/tests/sacado" "-DGUARD_FILE=/home/reza/scratch/repos/dealii/build/tests/sacado/physics_functions_01_2.debug/interrupt_guard.cc" "-P" "/home/reza/scratch/repos/dealii/build/share/deal.II/scripts/run_test.cmake"
7505: Test timeout computed to be: 600
7505: make[3]: *** [physics_functions_01_2.debug/diff] Error 1
7505: make[2]: *** [CMakeFiles/physics_functions_01_2.debug.diff.dir/all] Error 2
7505: make[1]: *** [CMakeFiles/physics_functions_01_2.debug.diff.dir/rule] Error 2
7505: make: *** [physics_functions_01_2.debug.diff] Error 2
7505: Test sacado/physics_functions_01_2.debug: DIFF
7505: ===============================   OUTPUT BEGIN  ===============================
7505: Built target physics_functions_01_2.debug
7505: Generating physics_functions_01_2.debug/diff
7505: sacado/physics_functions_01_2.debug: BUILD successful.
7505: sacado/physics_functions_01_2.debug: RUN successful.
7505: sacado/physics_functions_01_2.debug: DIFF failed. ------ Source: /home/reza/scratch/repos/dealii/tests/sacado/physics_functions_01_2.output
7505: sacado/physics_functions_01_2.debug: DIFF failed. ------ Result: /home/reza/scratch/repos/dealii/build/tests/sacado/physics_functions_01_2.debug/output
7505: Check /home/reza/scratch/repos/dealii/build/tests/sacado/physics_functions_01_2.debug/output /home/reza/scratch/repos/dealii/tests/sacado/physics_functions_01_2.output
7505: sacado/physics_functions_01_2.debug: DIFF failed. ------ Diff:   /home/reza/scratch/repos/dealii/build/tests/sacado/physics_functions_01_2.debug/failing_diff
7505: sacado/physics_functions_01_2.debug: DIFF failed. ------ First 8 lines of numdiff/diff output:
7505: 2,3c2,3
7505: < DEAL::Double:OK
7505: < DEAL::Float:OK
7505: ---
7505: > DEAL:Double::OK
7505: > DEAL:Float::OK
7505: sacado/physics_functions_01_2.debug: DIFF failed. ------ First 50 lines diff output:
7505: *** /home/reza/scratch/repos/dealii/tests/sacado/physics_functions_01_2.output	Tue Apr 23 19:29:27 2019
7505: --- output	Sun May  5 20:33:15 2019
7505: ***************
7505: *** 1,4 ****
7505:   
7505: ! DEAL::Double:OK
7505: ! DEAL::Float:OK
7505:   DEAL::OK
7505: --- 1,4 ----
7505:   
7505: ! DEAL:Double::OK
7505: ! DEAL:Float::OK
7505:   DEAL::OK
7505: CMakeFiles/physics_functions_01_2.debug.diff.dir/build.make:64: recipe for target 'physics_functions_01_2.debug/diff' failed
7505: CMakeFiles/Makefile2:4483: recipe for target 'CMakeFiles/physics_functions_01_2.debug.diff.dir/all' failed
7505: CMakeFiles/Makefile2:4490: recipe for target 'CMakeFiles/physics_functions_01_2.debug.diff.dir/rule' failed
7505: Makefile:1923: recipe for target 'physics_functions_01_2.debug.diff' failed
7505: 
7505: 
7505: sacado/physics_functions_01_2.debug: ******    DIFF failed    *******
7505: 
7505: ===============================    OUTPUT END   ===============================
7505: Expected stage PASSED - aborting
7505: CMake Error at /home/reza/scratch/repos/dealii/build/share/deal.II/scripts/run_test.cmake:140 (MESSAGE):
7505:   *** abort
7505: 
7505: 
1/1 Test #7505: sacado/physics_functions_01_2.debug ...***Failed    0.24 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.63 sec

The following tests FAILED:
	7505 - sacado/physics_functions_01_2.debug (Failed)
Errors while running CTest
```
Digging deeper into it, I noticed that there are mistakes in the reference output files of many tests. For example the code 
```
deallog.push("Float");
deallog << "OK" << std::endl;
```
will create the output `DEAL:Float::OK` rather than `DEAL::Float:OK`. So, using `sed`, I fixed many of these typos.

### CODE REVIEW

**Comment by jppelteret** [comment]
Thanks for fixing these annoying mistakes. I can confirm that the real output is indeed different from the blessed output for `sacado/physics_functions_01_2.debug` (and, therefore, presumably for the others that you've listed here). I can only assume that errors crept in when, at some point, I must have edited these output files by hand. Strange that they pass on both of my machines as well as the tester.

**Comment by rezarastak** [comment]
Thank you for confirming that there were errors in the test files of the repository. For a couple of hours I was trying to figure out if there is something wrong with my build environment :) 

My fixes reduced the number of failings tests considerably, but there are still tests failing within Sacado and Adol-C that require attention.

**Comment by jppelteret** [comment]
> Thank you for confirming that there were errors in the test files of the repository. For a couple of hours I was trying to figure out if there is something wrong with my build environment :)

Out of curiosity, do you have `numdiff` installed? It could be that `numdiff` is a bit more compliant than standard `diff` when comparing the text-based outputs.

> My fixes reduced the number of failings tests considerably, but there are still tests failing within Sacado and Adol-C that require attention.

Are they the same tests that are failing here
https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=9496
?

**Comment by rezarastak** [comment]
> Out of curiosity, do you have `numdiff` installed? It could be that `numdiff` is a bit more compliant than standard `diff` when comparing the text-based outputs.

Thanks for pointing it out. I didn't have numdiff. Now I installed it and the number of test errors went way down.

> Are they the same tests that are failing here
> https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=9496

Currently on my machine these tests fail (I only tested Sacado + Adolc):
* 7421 - sacado/helper_scalar_coupled_3_components_01_4.mpirun=2.debug (Failed)
* 7422 - sacado/helper_scalar_coupled_3_components_01_4.mpirun=2.release (Failed)
* 7433 - sacado/helper_scalar_coupled_4_components_01_2.debug (Failed)
* 7437 - sacado/helper_scalar_coupled_4_components_01_4.debug (Failed)
* 94 - adolc/helper_scalar_failure_04.release (Failed)
* 114 - adolc/helper_tape_index_01.release (Failed)

**Comment by jppelteret** [comment]
If you can put the `failing_output` + `stdout` in a gist, I can start to look at them and try to figure out what might be going wrong.  I can't give you a time frame for this though.  Looking at the results of the tester, there's still some work to do to get a robust solution with these two frameworks.

**Comment by rezarastak** [comment]
I ran the tests on the latest master branch and attached the output here.

`ctest -j 5 -R 'sacado|adolc' -V > sacado-adolc-tests-dad0cf2ae9.txt`
[sacado-adolc-tests-dad0cf2ae9.txt](https://github.com/dealii/dealii/files/3149273/sacado-adolc-tests-dad0cf2ae9.txt)

>  I can start to look at them and try to figure out what might be going wrong. I can't give you a time frame for this though.

Thank you for responding to my questions and trying to fix the failing tests.

When I submitted the PR I didn't have numdiff and didn't know why I was getting this many fails. So I tried to report it to you and fix some of the output files myself. Now I learned something new (`numdiff`) and it appears this patch is good but not necessary :)

**Comment by jppelteret** [comment]
Thanks a lot for the output -- that's certainly helpful. There's already a patch for some of these in the works (#8017) and I'll be looking at some of the other tests soon.

**Comment by jppelteret** [comment]
> it appears this patch is good but not necessary

Well, numdiff was a band-aid for what was clearly some incorrect output. So we appreciate your fixing the offending "blessed" outputs!

**Pull request merged**
