### PR TITLE
Relax lac/gmres_reorthogonalize_01

### PR DESCRIPTION
**Pull request by masterleinad**
This failed when running with `DEAL_II_WITH_THREADS=OFF` with one iteration off.

### CODE REVIEW

**Comment by tamiko** [comment]
Nice cleanup.

**Comment by kronbichler** [comment]
I am late to this commit, but as the original author of that test I must say that this change defeats the purpose of the test, namely to show when re-orthogonalization kicks in. Now you lose all output on that matter. Sure, we still have the control on the number of iterations, but since this was the only test that monitored the feature of re-orthogonalization I am quite uncomfortable with the new state.

The problem with re-orthogonalization is that it inherently is a round-off issue, so of course the tests are fragile. Anyway, I would have preferred to add a second output on this particular test.

**Comment by tamiko** [comment]
@kronbichler 
We are about to remove all internal `deallog` output in linear solvers, see #4730.

So it would be nice to take the opportunity to add an additional signal for the re-orthogonalization process and update this test to output something when a re-orthogonalization occurs.

**Comment by kronbichler** [comment]
I know that, but it would have been nice if one of the two people involved in effectively deleting a test would have taken that step, rather than kicking the ball back the person who points to that fact.

**Comment by tamiko** [comment]
@kronbichler I haven't implied that you should do that. I have reverted the merge.

**Comment by kronbichler** [comment]
@tamiko thanks. I hope to help on that transition once we approach it (and when I've finished some of the other work that is blocking most of my time right now).

**Pull request merged**
