### PR TITLE
AlignedVector: Move element destructors into the 'deleter' object.

### PR DESCRIPTION
**Pull request by bangerth**
A conceptually not so nice detail of the `AlignedVector` class (predating the work for #12008) is that we called element destructors separately from the function that releases the memory. The work for #12008 further separated this, by moving the call to `std::free()` into the deleter object of a `std::unique_ptr`, but doing the element destruction by hand at a different place.

This patch unifies these places by moving the destruction of elements into the deleter object. For this the deleter needs to know how many elements are currently stored, and so needs to reference `this`. This is conceptually not so difficult, the only place where one needs to pay attention (or, like me, spend two hours debugging) is that one has to remember that when moving an object, the deleter also needs to be reset to refer to the *current* object, not the one being *moved from*. 

This fixes a bug in `replicate_across_communicators()` for which I will provide a test separately with explanation. So would appreciate if we could get this into 9.3 still. 

/rebuild

### CODE REVIEW

**Comment by bangerth** [comment]
Maybe to explain why I need to do this: If the destruction of elements does not happen inside the deleter, then it needs to happen somewhere else -- currently in `clear()`, which among other places is called by the destructor. The problem with this is that after the implementation of `replicate_across_communicator()`, there are cases where we no longer own the memory (namely, on the non-owning processors that share a shared memory space), and we currently still call the element destructors on these processes because in `clear()` we don't know whether we own or do not own the memory. Only the deleter actually does, and so the destruction of individual elements is something that has to be done there. Indeed, it is already done there:
```
  elements =
    decltype(elements)(aligned_shmem_pointer,
                       [is_shmem_root,
                        array_size,
                        aligned_shmem_pointer,
                        shmem_group_communicator,
                        shmem_window](T *) mutable {
                         if (is_shmem_root)
                           for (unsigned int i = 0; i < array_size; ++i)
                             aligned_shmem_pointer[i].~T();

                         int ierr;
                         ierr = MPI_Win_free(&shmem_window);
                         AssertThrowMPI(ierr);

                         ierr = MPI_Comm_free(&shmem_group_communicator);
                         AssertThrowMPI(ierr);
                       });
```
But this means that when calling the destructor of `AlignedVector` (or `clear()`), these elements are destroyed twice on the owning process, and once on the non-owning ones -- not what we want.

**Comment by bangerth** [comment]
Related to #12008.

**Comment by bangerth** [comment]
I added the test (explanation is above) and verified that the output is correct.

**Review by kronbichler — APPROVED** [review]

**Comment by kronbichler** [comment]
We have a few failing tests, e.g. from the quick-tests:
```
[4/4] cd /home/dealii/build/tests/quick_tests && /home/dealii/build/tests/quick_tests/step.debug > step.debug-OK 2>&1 || ( echo step.debug:\ RUN\ failed.\ Output: && cat step.debug-OK && rm step.debug-OK && exit 1 ) && echo step.debug:\ PASSED.
FAILED: cd /home/dealii/build/tests/quick_tests && /home/dealii/build/tests/quick_tests/step.debug > step.debug-OK 2>&1 || ( echo step.debug:\ RUN\ failed.\ Output: && cat step.debug-OK && rm step.debug-OK && exit 1 ) && echo step.debug:\ PASSED.
step.debug: RUN failed. Output:
--------------------------------------------------------
An error occurred in line <1072> of file </jenkins/workspace/dealii_PR-12185/include/deal.II/base/aligned_vector.h> in function
    dealii::AlignedVector<T>::reserve(dealii::AlignedVector<T>::size_type)::<lambda(T*)> [with T = double]
The violated condition was: 
    this->used_elements_end != nullptr

Additional information: 
    This exception -- which is used in many places in the library --
    usually indicates that some condition which the author of the code
    thought must be satisfied at a certain point in an algorithm, is not
    fulfilled. An example would be that the first part of an algorithm
    sorts elements of an array in ascending order, and a second part of
    the algorithm later encounters an element that is not larger than the
    previous one.

    There is usually not very much you can do if you encounter such an
    exception since it indicates an error in deal.II, not in your own
    program. Try to come up with the smallest possible program that still
    demonstrates the error and contact the deal.II mailing lists with it
    to obtain help.
```

**Comment by peterrum** [comment]
@bangerth Do you have time to work on this PR? Or should anyone of use give you a hand?

**Comment by bangerth** [comment]
I had already written a longish comment about how, after 3 hours of trying to wrap my mind around this thing, I was completely stuck and needed help. But I did in the end find it: Just like mentioned in the very first comment above, it was yet another place where we exchange pointers and forget to reset the deleter -- in this case, in the `swap` function.

I think the lesson of this patch is this: Try by all means to stay away from from custom deleters that refer to the object that *owns* the pointer. I don't see a way to avoid this here, but getting this right is just too damn complicated. Just don't do it. This patch took me ~6 hours, so about ~20 lines of (now hopefully correct) actual code per hour, comments included. Not a great ratio.

**Review by masterleinad — APPROVED** [review]
Looks OK to me.

**Comment by bangerth** [comment]
OK, seems to work! Phew!!

**Review by drwells — APPROVED** [review]
Nice work - as always, I appreciate that you are willing to work through these sometimes terrible details.

**Pull request merged**
