### PR TITLE
Fix initlog

### PR DESCRIPTION
**Pull request by class4kayaker**
Work on fixing #4250. Note that in some cases the script may have changed the line endings, implying a larger diff than actually exists. Trying to identify the mpi_initlog cases may not have been as successful, though the script did catch quite a few (removed due to closer check identifying that the search criterion were not correct and the check was not as easily matched).

This should probably be carefully tested given that only a small number of tests were tried. Also, due to the current configuration, the changes to the mpi tests have not yet been tested.

This will probably not catch all of the cases, but given that it catches over 1000 it is probably still worth doing.

----

Python script used (note that it does not by default like the latin1 encoding in at one of the files, I had to rewrite that as utf8 and then revert the change after running the script)

````python
import os
import re
import sys
import os.path
import itertools

re_initlog = re.compile(
    r'std::ofstream\s+logfile\(\"output\"\);\s+'
    r'deallog\.attach\(logfile\);'
)

re_mpi_initlog = re.compile(
    r'unsigned int myid\s*=\s*'
    r'Utilities::MPI::this_mpi_process\s*\(MPI_COMM_WORLD\);\s+'
    r'deallog\.push\s*\(\s*Utilities::int_to_string\s*\(myid\)\s*\);'
)


def cmp_lines(fn_1, fn_2):
    with open(fn_1, 'r') as f_1, open(fn_2, 'r') as f_2:
        for l1, l2 in itertools.zip_longest(f_1, f_2):
            if l1 != l2:
                return False
    return True


def replace_if_different(fn_1, fn_2):
    if cmp_lines(fn_1, fn_2):
        os.remove(fn_2)
        return False
    else:
        os.rename(fn_2, fn_1)
        return True


def f_re_sub(fn, r_cmp, sub):
    fn_o = fn+'.new'
    with open(fn, 'r') as inf, open(fn_o, 'w') as of:
        of.write(r_cmp.sub(
            sub,
            inf.read()))
    return replace_if_different(fn, fn_o)


def add_include(fn):
    re_include = re.compile(
        r'#include "\.\./tests\.h"\s'
    )
    fn_o = fn+'.new'

    includeline = '#include "../tests.h"\n'
    added = False
    with open(fn, 'r') as f_i:
        for line in f_i:
            if re_include.match(line):
                return False

        with open(fn_o, 'w') as of:
            f_i.seek(0, 0)
            for line in f_i:
                if not added and line.startswith('#include'):
                    added = True
                    of.write(includeline)
                of.write(line)
    return replace_if_different(fn, fn_o)


for root, subdirs, files in os.walk(sys.argv[1]):
    for fn_base in files:
        fn = os.path.join(root, fn_base)
        if fn.endswith('.cc'):
            print('{: <60s} '.format(fn), end='')
            dirty = False
            if f_re_sub(fn, re_initlog, 'initlog();'):
                print('l', end='')
                dirty = True
            if f_re_sub(fn, re_mpi_initlog, 'mpi_initlog();'):
                print('m', end='')
                dirty = True
            if dirty:
                if add_include(fn):
                    print('i')
                else:
                    print()
            else:
                print('', end='\r')
````

### CODE REVIEW

**Comment by masterleinad** [comment]
Running the testsuite on this PR the following tests fail:

- 	877 - aniso/fe_tools.debug (Failed)
- 	878 - aniso/fe_tools.release (Failed)
- 	951 - base/conditional_ostream.debug (Failed)
- 	952 - base/conditional_ostream.release (Failed)
- 	961 - base/data_out_base.debug (Failed)
- 	962 - base/data_out_base.release (Failed)
- 	1209 - base/logstream_end.debug (Failed)
- 	1210 - base/logstream_end.release (Failed)
- 	1455 - base/table_handler_12.debug (Failed)
- 	1456 - base/table_handler_12.release (Failed)
- 	1471 - base/task_03.debug (Failed)
- 	1472 - base/task_03.release (Failed)
- 	1473 - base/task_04.debug (Failed)
- 	1474 - base/task_04.release (Failed)
- 	1477 - base/task_06.debug (Failed)
- 	1478 - base/task_06.release (Failed)
- 	1479 - base/task_07.debug (Failed)
- 	1480 - base/task_07.release (Failed)
- 	1481 - base/task_08.debug (Failed)
- 	1482 - base/task_08.release (Failed)
- 	1483 - base/task_09.debug (Timeout)
- 	1484 - base/task_09.release (Timeout)
- 	1489 - base/task_12.debug (Failed)
- 	1490 - base/task_12.release (Failed)
- 	1491 - base/task_12_capture.debug (Failed)
- 	1492 - base/task_12_capture.release (Failed)
- 	1493 - base/task_13.debug (Failed)
- 	1494 - base/task_13.release (Failed)
- 	1543 - base/thread_12.debug (Failed)
- 	1544 - base/thread_12.release (Failed)
- 	1567 - base/thread_validity_06.debug (Failed)
- 	1568 - base/thread_validity_06.release (Failed)
- 	1569 - base/thread_validity_07.debug (Failed)
- 	1570 - base/thread_validity_07.release (Failed)
- 	1581 - base/threads_02.debug (Failed)
- 	1582 - base/threads_02.release (Failed)
- 	1687 - bits/christian_1.debug (Failed)
- 	1688 - bits/christian_1.release (Failed)
- 	1689 - bits/christian_2.debug (Failed)
- 	1690 - bits/christian_2.release (Failed)
- 	1894 - bits/fe_tools_11.debug (Failed)
- 	2083 - bits/solution_transfer.debug (Failed)
- 	2084 - bits/solution_transfer.release (Failed)
- 	2486 - distributed_grids/2d_coarse_grid_01.debug (Failed)
- 	2487 - distributed_grids/2d_coarse_grid_02.debug (Failed)
- 	2488 - distributed_grids/2d_coarse_grid_03.debug (Failed)
- 	2489 - distributed_grids/2d_coarse_grid_04.debug (Failed)
- 	2490 - distributed_grids/2d_coarse_grid_x_01.debug (Failed)
- 	2491 - distributed_grids/2d_coarse_grid_x_01.release (Failed)
- 	2492 - distributed_grids/2d_coarsening_01.debug (Failed)
- 	2493 - distributed_grids/2d_coarsening_02.debug (Failed)
- 	2494 - distributed_grids/2d_coarsening_03.debug (Failed)
- 	2495 - distributed_grids/2d_coarsening_03.release (Failed)
- 	2496 - distributed_grids/2d_coarsening_05.debug (Failed)
- 	2497 - distributed_grids/2d_coarsening_05.release (Failed)
- 	2498 - distributed_grids/2d_dofhandler_01.debug (Failed)
- 	2499 - distributed_grids/2d_dofhandler_01.release (Failed)
- 	2500 - distributed_grids/2d_refinement_01.debug (Failed)
- 	2501 - distributed_grids/2d_refinement_02.debug (Failed)
- 	2502 - distributed_grids/2d_refinement_03.debug (Failed)
- 	2503 - distributed_grids/2d_refinement_03.release (Failed)
- 	2504 - distributed_grids/2d_refinement_04.debug (Failed)
- 	2505 - distributed_grids/2d_refinement_04.release (Failed)
- 	2506 - distributed_grids/2d_refinement_05.debug (Failed)
- 	2507 - distributed_grids/2d_refinement_05.release (Failed)
- 	2508 - distributed_grids/2d_refinement_06.debug (Failed)
- 	2509 - distributed_grids/2d_refinement_06.release (Failed)
- 	2510 - distributed_grids/2d_refinement_07.debug (Failed)
- 	2513 - distributed_grids/3d_coarse_grid_01.debug (Failed)
- 	2515 - distributed_grids/3d_coarse_grid_03.debug (Failed)
- 	2516 - distributed_grids/3d_coarse_grid_04.debug (Failed)
- 	2517 - distributed_grids/3d_coarse_grid_05.debug (Failed)
- 	2518 - distributed_grids/3d_coarse_grid_06.debug (Failed)
- 	2519 - distributed_grids/3d_coarse_grid_06.release (Failed)
- 	2520 - distributed_grids/3d_coarse_grid_x_01.debug (Failed)
- 	2521 - distributed_grids/3d_coarse_grid_x_01.release (Failed)
- 	2522 - distributed_grids/3d_coarsening_01.debug (Failed)
- 	2523 - distributed_grids/3d_coarsening_02.debug (Failed)
- 	2524 - distributed_grids/3d_coarsening_03.debug (Failed)
- 	2525 - distributed_grids/3d_coarsening_03.release (Failed)
- 	2526 - distributed_grids/3d_coarsening_04.debug (Failed)
- 	2527 - distributed_grids/3d_coarsening_04.release (Failed)
- 	2528 - distributed_grids/3d_coarsening_05.debug (Failed)
- 	2529 - distributed_grids/3d_coarsening_05.release (Failed)
- 	2530 - distributed_grids/3d_refinement_01.debug (Failed)
- 	2531 - distributed_grids/3d_refinement_02.debug (Failed)
- 	2532 - distributed_grids/3d_refinement_03.debug (Failed)
- 	2533 - distributed_grids/3d_refinement_04.debug (Failed)
- 	2534 - distributed_grids/3d_refinement_04.release (Failed)
- 	2535 - distributed_grids/3d_refinement_05.debug (Failed)
- 	2536 - distributed_grids/3d_refinement_05.release (Failed)
- 	2537 - distributed_grids/3d_refinement_06.debug (Failed)
- 	2538 - distributed_grids/3d_refinement_06.release (Failed)
- 	2539 - distributed_grids/3d_refinement_07.debug (Failed)
- 	2540 - distributed_grids/3d_refinement_07.release (Failed)
- 	2541 - distributed_grids/3d_refinement_08.debug (Failed)
- 	2542 - distributed_grids/3d_refinement_08.release (Failed)
- 	2543 - distributed_grids/3d_refinement_09.debug (Failed)
- 	2546 - distributed_grids/anisotropic.debug (Failed)
- 	2558 - distributed_grids/solution_transfer_01.debug (Failed)
- 	2559 - distributed_grids/solution_transfer_01.release (Failed)
- 	2560 - distributed_grids/solution_transfer_02.debug (Failed)
- 	2561 - distributed_grids/solution_transfer_02.release (Failed)
- 	2562 - distributed_grids/solution_transfer_03.debug (Failed)
- 	2563 - distributed_grids/solution_transfer_03.release (Failed)
- 	2564 - distributed_grids/solution_transfer_04.debug (Failed)
- 	2565 - distributed_grids/solution_transfer_04.release (Failed)
- 	2567 - distributed_grids/tria_settings_01.debug (Failed)
- 	2568 - distributed_grids/tria_settings_01.release (Failed)
- 	3011 - fe/dgp_01.debug (Failed)
- 	3255 - fe/fe_tools.debug (Failed)
- 	3256 - fe/fe_tools.release (Failed)
- 	3257 - fe/fe_tools_01.debug (Failed)
- 	3258 - fe/fe_tools_01.release (Failed)
- 	3991 - grid/extrude_orientation_01.debug (Failed)
- 	3992 - grid/extrude_orientation_01.release (Failed)
- 	3993 - grid/extrude_orientation_02.debug (Failed)
- 	3994 - grid/extrude_orientation_02.release (Failed)
- 	4025 - grid/grid_generator_01.debug (Failed)
- 	4026 - grid/grid_generator_01.release (Failed)
- 	4027 - grid/grid_generator_01a.debug (Failed)
- 	4028 - grid/grid_generator_01a.release (Failed)
- 	4029 - grid/grid_generator_01b.debug (Failed)
- 	4030 - grid/grid_generator_01b.release (Failed)
- 	4031 - grid/grid_generator_02.debug (Failed)
- 	4032 - grid/grid_generator_02.release (Failed)
- 	4033 - grid/grid_generator_03.debug (Failed)
- 	4034 - grid/grid_generator_03.release (Failed)
- 	4035 - grid/grid_generator_04.debug (Failed)
- 	4036 - grid/grid_generator_04.release (Failed)
- 	4037 - grid/grid_generator_05.debug (Failed)
- 	4038 - grid/grid_generator_05.release (Failed)
- 	4039 - grid/grid_generator_06.debug (Failed)
- 	4040 - grid/grid_generator_06.release (Failed)
- 	4041 - grid/grid_generator_07.debug (Failed)
- 	4042 - grid/grid_generator_07.release (Failed)
- 	4043 - grid/grid_generator_08.debug (Failed)
- 	4044 - grid/grid_generator_08.release (Failed)
- 	4057 - grid/grid_generator_hyper_sphere.debug (Failed)
- 	4058 - grid/grid_generator_hyper_sphere.release (Failed)
- 	4143 - grid/grid_output_input.debug (Failed)
- 	4144 - grid/grid_output_input.release (Failed)
- 	4549 - hp/fe_nothing_17.debug (Failed)
- 	4550 - hp/fe_nothing_17.release (Failed)
- 	4769 - hp/solution_transfer.debug (Failed)
- 	4770 - hp/solution_transfer.release (Failed)
- 	4771 - hp/solution_transfer_02.debug (Failed)
- 	4772 - hp/solution_transfer_02.release (Failed)
- 	4789 - hp/solution_transfer_11.debug (Failed)
- 	4790 - hp/solution_transfer_11.release (Failed)
- 	4791 - hp/solution_transfer_12.debug (Failed)
- 	4792 - hp/solution_transfer_12.release (Failed)
- 	5510 - mappings/mapping_fe_field_real_to_unit_b4_curved.debug (Failed)
- 	5546 - mappings/mapping_q1_eulerian_01.debug (Failed)
- 	5547 - mappings/mapping_q1_eulerian_01.release (Failed)
- 	5554 - mappings/mapping_q_eulerian_01.debug (Failed)
- 	5555 - mappings/mapping_q_eulerian_01.release (Failed)
- 	5556 - mappings/mapping_q_eulerian_02.debug (Failed)
- 	5557 - mappings/mapping_q_eulerian_02.release (Failed)
- 	5558 - mappings/mapping_q_eulerian_03.debug (Failed)
- 	5559 - mappings/mapping_q_eulerian_03.release (Failed)
- 	6397 - mpi/p4est_save_01.mpirun=10.debug (Failed)
- 	6398 - mpi/p4est_save_01.mpirun=10.release (Failed)
- 	6401 - mpi/p4est_save_02.mpirun=10.debug (Failed)
- 	6402 - mpi/p4est_save_02.mpirun=10.release (Failed)
- 	6403 - mpi/p4est_save_02.mpirun=4.debug (Failed)
- 	6408 - mpi/p4est_save_03.mpirun=4.release (Failed)
- 	6409 - mpi/p4est_save_04.mpirun=5.debug (Failed)
- 	6733 - mpi/torus.mpirun=2.debug (Failed)
- 	6734 - mpi/torus.mpirun=2.release (Failed)
- 	7164 - numerics/data_out_curved_cells.debug (Failed)
- 	7165 - numerics/data_out_curved_cells.release (Failed)
- 	7425 - opencascade/arclength_boundary_02.debug (Failed)
- 	7426 - opencascade/arclength_boundary_02.release (Failed)
- 	7433 - opencascade/circle_normal_projection.debug (Failed)
- 	7434 - opencascade/circle_normal_projection.release (Failed)
- 	7451 - opencascade/interpolation_curve_boundary.debug (Failed)
- 	7452 - opencascade/interpolation_curve_boundary.release (Failed)
- 	7461 - opencascade/plane_intersection_01.debug (Failed)
- 	7462 - opencascade/plane_intersection_01.release (Failed)
- 	7522 - parameter_handler/parameter_handler_3.debug (Failed)
- 	7523 - parameter_handler/parameter_handler_3.release (Failed)
- 	7524 - parameter_handler/parameter_handler_3_with_alias_01.debug (Failed)
- 	7525 - parameter_handler/parameter_handler_3_with_alias_01.release (Failed)
- 	7526 - parameter_handler/parameter_handler_3_with_alias_02.debug (Failed)
- 	7527 - parameter_handler/parameter_handler_3_with_alias_02.release (Failed)
- 	7528 - parameter_handler/parameter_handler_3_with_alias_03.debug (Failed)
- 	7529 - parameter_handler/parameter_handler_3_with_alias_03.release (Failed)
- 	7530 - parameter_handler/parameter_handler_3_with_alias_04.debug (Failed)
- 	7531 - parameter_handler/parameter_handler_3_with_alias_04.release (Failed)
- 	7532 - parameter_handler/parameter_handler_3_with_space.debug (Failed)
- 	7533 - parameter_handler/parameter_handler_3_with_space.release (Failed)
- 	7534 - parameter_handler/parameter_handler_4.debug (Failed)
- 	7535 - parameter_handler/parameter_handler_4.release (Failed)
- 	7536 - parameter_handler/parameter_handler_4a.debug (Failed)
- 	7537 - parameter_handler/parameter_handler_4a.release (Failed)
- 	7538 - parameter_handler/parameter_handler_4a_with_alias.debug (Failed)
- 	7539 - parameter_handler/parameter_handler_4a_with_alias.release (Failed)
- 	7540 - parameter_handler/parameter_handler_4a_with_alias_deprecated.debug (Failed)
- 	7541 - parameter_handler/parameter_handler_4a_with_alias_deprecated.release (Failed)
- 	7542 - parameter_handler/parameter_handler_4b.debug (Failed)
- 	7543 - parameter_handler/parameter_handler_4b.release (Failed)
- 	7544 - parameter_handler/parameter_handler_5.debug (Failed)
- 	7545 - parameter_handler/parameter_handler_5.release (Failed)
- 	7546 - parameter_handler/parameter_handler_6.debug (Failed)
- 	7547 - parameter_handler/parameter_handler_6.release (Failed)
- 	7548 - parameter_handler/parameter_handler_6_bool.debug (Failed)
- 	7549 - parameter_handler/parameter_handler_6_bool.release (Failed)
- 	7550 - parameter_handler/parameter_handler_7.debug (Failed)
- 	7551 - parameter_handler/parameter_handler_7.release (Failed)
- 	7552 - parameter_handler/parameter_handler_8.debug (Failed)
- 	7553 - parameter_handler/parameter_handler_8.release (Failed)
- 	7586 - parameter_handler/parameter_handler_read_xml.debug (Failed)
- 	7587 - parameter_handler/parameter_handler_read_xml.release (Failed)
- 	7596 - parameter_handler/parameter_handler_write_json.debug (Failed)
- 	7597 - parameter_handler/parameter_handler_write_json.release (Failed)
- 	7598 - parameter_handler/parameter_handler_write_section_1.debug (Failed)
- 	7599 - parameter_handler/parameter_handler_write_section_1.release (Failed)
- 	7600 - parameter_handler/parameter_handler_write_section_2.debug (Failed)
- 	7601 - parameter_handler/parameter_handler_write_section_2.release (Failed)
- 	7602 - parameter_handler/parameter_handler_write_section_xml.debug (Failed)
- 	7603 - parameter_handler/parameter_handler_write_section_xml.release (Failed)
- 	7604 - parameter_handler/parameter_handler_write_xml.debug (Failed)
- 	7605 - parameter_handler/parameter_handler_write_xml.release (Failed)
- 	7888 - petsc/vector_print.debug (Failed)
- 	7889 - petsc/vector_print.release (Failed)
- 	8011 - slepc/solve_04.release (Failed)

**Comment by masterleinad** [comment]
That definitely goes in the right direction!
I guess we should take somewhat smaller steps for which we know that the testsuite still passes.

**Comment by class4kayaker** [comment]
I modified the script slightly to look for the obvious error source and added a check for if logfile was still referenced after the substitution. I also reverted the attempt to script the mpi_initlog due to the criterion used not being the correct one.

Current script is now

````python
import os
import re
import sys
import os.path
import itertools

re_initlog = re.compile(
    r'std::ofstream\s+logfile\(\"output\"\);\s+'
    r'deallog\.attach\(logfile\);'
)

re_initlog_vars = [
    re.compile(r'\blogfile\b')
]

# re_mpi_initlog = re.compile(
#     r'unsigned int myid\s*=\s*'
#     r'Utilities::MPI::this_mpi_process\s*\(MPI_COMM_WORLD\);\s+'
#     r'deallog\.push\s*\(\s*Utilities::int_to_string\s*\(myid\)\s*\);'
# )


def cmp_lines(fn_1, fn_2):
    with open(fn_1, 'r') as f_1, open(fn_2, 'r') as f_2:
        for l1, l2 in itertools.zip_longest(f_1, f_2):
            if l1 != l2:
                return False
    return True


def replace_if_different(fn_1, fn_2):
    if cmp_lines(fn_1, fn_2):
        os.remove(fn_2)
        return False
    else:
        os.rename(fn_2, fn_1)
        return True


def f_re_sub(fn, r_cmp, sub, scans=[]):
    fn_o = fn+'.new'
    with open(fn, 'r') as inf, open(fn_o, 'w') as of:
        of.write(r_cmp.sub(
            sub,
            inf.read()))
    valid = True
    with open(fn_o, 'r') as of:
        for line in of:
            for v in scans:
                if not v.search(line) is None:
                    valid = False
    if valid:
        return replace_if_different(fn, fn_o)
    else:
        os.remove(fn_o)


def add_include(fn):
    re_include = re.compile(
        r'#include "\.\./tests\.h"\s'
    )
    fn_o = fn+'.new'

    includeline = '#include "../tests.h"\n'
    added = False
    with open(fn, 'r') as f_i:
        for line in f_i:
            if re_include.match(line):
                return False

        with open(fn_o, 'w') as of:
            f_i.seek(0, 0)
            for line in f_i:
                if not added and line.startswith('#include'):
                    added = True
                    of.write(includeline)
                of.write(line)
    return replace_if_different(fn, fn_o)


for root, subdirs, files in os.walk(sys.argv[1]):
    for fn_base in files:
        fn = os.path.join(root, fn_base)
        if fn.endswith('.cc'):
            print('{: <60s} '.format(fn), end='')
            dirty = False
            if f_re_sub(fn, re_initlog, 'initlog();', scans=re_initlog_vars):
                print('l', end='')
                dirty = True
#             if f_re_sub(fn, re_mpi_initlog, 'mpi_initlog();'):
#                 print('m', end='')
#                 dirty = True
            if dirty:
                if add_include(fn):
                    print('i')
                else:
                    print()
            else:
                print('', end='\r')
````

**Comment by masterleinad** [comment]
There are some places (e.g. "tests/base/table_handler_12.cc") where
> std::ofstream logfile("output");
  deallog.attach(logfile);

is not replaced by
> initlog();

Anyway, this is progression and for me only `mpi/torus.cc` is failing (just remove `static` in front of `initlog()`. Apart from that, I am fine with this, but let's have a second opinion.

**Comment by class4kayaker** [comment]
I added a check that looked at the file after the substitution and identified whether there were any uses of the logfile variable. The particular test you mention makes use of the actual logfile output, and does not use deallog directly. There may be more scriptable substitutions, but I was aiming for getting the bulk of the unambiguous cases out of the way.

**Comment by masterleinad** [comment]
For me, `mpi/torus` is the only test that is still failing. Probably, you can just remove the whole
>   if (Utilities::MPI::this_mpi_process (MPI_COMM_WORLD) == 0)
    {
      static std::ofstream logfile("output");
      deallog.attach(logfile);
      deallog.threshold_double(1.e-10);
    }


block. Can you check?

**Comment by class4kayaker** [comment]
I reverted the mpi/torus test to match the current master.

**Comment by masterleinad** [comment]
Thanks!

**Pull request merged**
