### PR TITLE
fe/memory_consumption_01: remove test

### PR DESCRIPTION
**Pull request by tamiko**
When compiled against libc++ we have a slightly different memory
consumption profile than compared to libstdc++. Simply add a variant

### CODE REVIEW

**Comment by drwells** [comment]
That's odd - I thought we removed all of the memory consumption tests in #4727. Shouldn't we also just remove this test?

**Comment by tamiko** [comment]
On Wed, May  6, 2020, at 21:10 CDT, David Wells <notifications@github.com> wrote:

> That's odd - I thought we removed all of the memory consumption tests
> in #4727. Shouldn't we also just remove this test?

Ah, that explains why I have so few memory consumption test failures...


deleting.

**Comment by tamiko** [comment]
@drwells Updated.

**Pull request merged**
