### PR TITLE
Make MappingQ1::InternalData more generic

### PR DESCRIPTION
**Pull request by bangerth**
As mentioned in #1429, MappingQ1 and MappingQ are a pretty terrible mess right now because the latter is derived from the former even though there is no is-a relationship. Consequently, the code is a disaster.

This patch moves us a step closer to disentangling this mess. Previously, MappingQ1::InternalData stored a flag that said "represents a Q1 or a Qp mapping", and then all sorts of internal contortions had to happen in the mapping classes dependening on this. This flag is now gone, and the MappingQ1::InternalData class is now generic for all polynomial degrees. It now also stores this polynomial degree, and can initialize itself properly, rather than having the MappingQ1 and MappingQ class battle it out who is responsible to do so (via some crazy emulated virtual function mechanism). 

This is a continuation of #1425 and addresses #1429. In reference to #1198. I'm not done with this series of patches, but this moves me much closer to the desired goal: breaking out the common parts of these two classes (including `MappingQ1::InternalData`) into a shared `MappingQGeneric` or similarly named class, and really only having the things that are different between the classes left in `MappingQ1` and `MappingQ`. This step is now rather close: The InternalData class could in fact already be moved out. But one step at a time.

### CODE REVIEW

**Comment by bangerth** [comment]
I've pushed another two commits here that separate the common stuff of the two classes into a generic base class. What remains in `mapping_q1.cc` and `mapping_q.cc` is actually relatively little. Some of that I plan on migrating into the base class at a later time.

**Comment by luca-heltai** [comment]
I like the cleanup very much. However I have a comment on this: in the long term I think having classes MappingQ, MappingQ1, MappingQGeneric, etc. which are *not* based on our FEQ classes should be avoided. I'm afraid this puts us one step further (instead of closer) from separating geometry from topology.

**Comment by bangerth** [comment]
You've really drunk the isogeometric analysis coolaid, haven't you? ;-)

But yes: I agree. I'm not doing anything that changes functionality or would make this goal any more difficult to achieve. In fact, I'm just cleaning up some terrible historical cruft that isolates things from each other and will make it a lot simpler to change things because they're not nearly as entangled as before. Currently, you end up with these call chains where you call a function in Mapping, you come out in MappingQ, which calls MappingQ1, which calls a couple of other functions in MappingQ1 which then call back to a MappingQ and so on and so forth. It's really difficult to understand how one gets into any given function, and my hope is that I can make this a bit clearer and thereby easier to change.

**Comment by kronbichler** [comment]
I have looked at the patch and technically, the code looks ready for merge (except for the merge conflict).

However, I have a more fundamental question: Now that you spend a significant amount of work at separating MappingQ/MappingQ, why not get rid of the historical 'mistake' of having separate classes and simply make MappingQ1 part of MappingQ (with StaticMappingQ1 that is used in many places defined as Mapping(1))? Does this move us closer to removing MappingQ1? I realize that MappingQ adds new points whereas MappingQ1 simply takes the vertices of the triangulation, but I see that my students struggle with having two separate classes for something that is conceptually the same. And I don't see how performance could be affected if we implement MappingQ well.

I agree with @luca-heltai that the mapping interfaces are way too complicated and we should not need more than
- MappingCartesian
- MappingQ
- MappingFEField
If the topology is separated from the geometry, MappingQ could really be a wrapper to MappingFEField based on FESystem(FE_Q,dim), such that all code is in one single place for MappingFEField.

**Comment by luca-heltai** [comment]
@bangerth , let's say that I drunk the whole iso-**parametric** first, and think of iso-**geometric** just as a fancy name for something that has been around for three decades now... 

;)

I fully agree with @kronbichler . With one difference: the default base class `Mapping`, should be tied much closer to `Manifold`, as it truly is a **local chart** of an **atlas** (the `Triangulation` as we intend it now) which describes the `Manifold`...

For now, please fix the conflict, squash everything in one commit, and merge yourself.

**Comment by luca-heltai** [comment]
Oh, and BTW, the most important part of iso-wathere is the **iso** part, not the fancy name afterwards... This means "the same": something we do **not** have, except in the `MappingFEField` class...

;)

**Comment by bangerth** [comment]
@luca-heltai -- I certainly didn't intend to step on your feet with my comment :-) You did see the smiley, I hope!

As for the other issues, let's move this discussion to a new issue: #1537

**Comment by luca-heltai** [comment]
No offense taken here! ;) I'm not a huge fan of the iso-geometric way of pushing new names for old stuff just to be able to say "I'm doing something new", so I think we agree more than you can think of... 

:D

**Comment by bangerth** [comment]
Rebased and merged.

**Pull request merged**
