### PR TITLE
Deprecate Utilities::MPI::create_group

### LINKED ISSUE #13475: Remove Utilities::MPI::create_group()
Following #13465 (see also #13447) , we can remove the `Utilities::MPI::create_group()` function, which then simply wraps the call
```
return MPI_Comm_create_group(comm, group, tag, new_comm);
```
It currently does something non-trivial only in the case that we have MPI <3. 

Alternatively, maybe better, we can keep the function and make sure we check the return type rather than passing on the error code as we currently do. An even better idea would be to make the function similar to `duplicate_communicator()`, which would imply checking the MPI error code and then returning the actual communicator.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #13475.

### CODE REVIEW

**Comment by tjhei** [comment]
This will conflict with #13465. Can we merge that first, please?

**Comment by tjhei** [comment]
can you rebase please?

**Comment by masterleinad** [comment]
> can you rebase please?

Done.

**Review by bangerth — APPROVED** [review]

**Review by tjhei — APPROVED** [review]
thanks!

**Pull request merged**
