### PR TITLE
CMake: Remove a faulty list manipulation

### PR DESCRIPTION
**Pull request by tamiko**
Closes: https://github.com/dealii/dealii/issues/7423

### CODE REVIEW

**Comment by bangerth** [comment]
Can you elaborate why this is correct?

**Comment by tamiko** [comment]
@bangerth I posted the explanation on the issue, not the pull request. Mea culpa:
"""
Wow this is some pretty terrible piece of CMake logic: If the variable is not an empty string, remove the first and second element.

It turns out that this is also entirely irrelevant. The final list of includes gets deduplicated nowadays within `DEAL_II_PACKAGE_HANDLE```.
"""

**Comment by bangerth** [comment]
I see. Thanks for the explanation!

**Comment by drwells** [comment]
@tamiko this won't fix that issue; the issue referred to the 9.0.1 branch (though of course we should fix it on master).

**Pull request merged**
