### PR TITLE
Convert a lot of tests to use initlog().

### PR DESCRIPTION
**Pull request by drwells**
This takes care of about a ~quarter~ third of the remaining usages of `initlog`.

This commit brought to you by Florence.

### CODE REVIEW

**Comment by drwells** [comment]
Part of #4250.

**Comment by drwells** [comment]
Hah. The only interesting change is when we need to close the log file and sort it before the end of the program (i.e., the `task` tests)

```cpp
int
main()
{
  initlog();

  {
    Threads::Thread<> t1 = Threads::new_thread(test, 1);
    Threads::Thread<> t2 = Threads::new_thread(test, 2);

    t1.join();
    t2.join();

    deallog << "OK" << std::endl;
  }

  std::ofstream *out_stream = dynamic_cast<std::ofstream *>(&deallog.get_file_stream());
  Assert(out_stream != nullptr, ExcInternalError());
  deallog.detach();
  out_stream->close();
  sort_file_contents("output");
}
```

the rest is dull.

I did run all of the tests locally.

**Comment by drwells** [comment]
Slight correction: I did not run the complex PETSc tests locally, but I did run the rest.

**Comment by tjhei** [comment]
let's see what happens. :)

**Pull request merged**
