### PR TITLE
GitHub CI: Test building with Trilinos+Tpetra

### PR DESCRIPTION
**Pull request by masterleinad**

### CODE REVIEW

**Review by bangerth — APPROVED** [review]
This seems useful in view of the fact that we're creating substantial new functionality in this area at the moment.

**Comment by bangerth** [comment]
Well, one of the CI checks now fails though because it can't find Trilinos...

**Comment by marcfehling** [comment]
I suggest to use either the `linux-debug-parallel` or `linux-release-serial` worker (or both) to test with TPetra, as they both use the docker image that comes with Trilinos installations.

**Comment by marcfehling** [comment]
Actually, the `linux-debug-parallel` worker already builds with `TRILINOS=ON`.
https://github.com/dealii/dealii/blob/af50e53354d73646eac3db2337121c4e8e63edaa/.github/workflows/linux.yml#L116

What do you need to do to make it use TPetra?

**Comment by masterleinad** [comment]
> What do you need to do to make it use TPetra?

Enable 64-it indices and disable PETSc.

**Review by marcfehling — APPROVED** [review]

**Comment by masterleinad** [comment]
ping

**Pull request merged**
