### PR TITLE
[9.6] Use aliases for TpetraTypes::[Dual]View[Unmanaged]

### PR DESCRIPTION
**Pull request by masterleinad**
Cherry-picking #17437.

### CODE REVIEW

**Review by marcfehling — APPROVED** [review]

**Review by marcfehling — APPROVED** [review]

**Comment by jpthiele** [comment]
What was your reasoning for removing the unmanaged part?
Would that not lead to errors when we use the pointer outside of this function again?

**Comment by masterleinad** [comment]
> What was your reasoning for removing the unmanaged part?

The `View` will still be unmanaged if constructed from a pointer.

**Comment by jpthiele** [comment]
Good to know, but that was not clear from the documentation of Kokkos.

**Comment by masterleinad** [comment]
> Good to know, but that was not clear from the documentation of Kokkos.

https://kokkos.org/kokkos-core-wiki/API/core/view/view.html?highlight=view#_CPPv44View12pointer_typeDpRK7IntType mentions that but we could be clearer about it. The only way to check for a View to be unmanaged is by checking `use_count() == 0`.

**Review by tamiko — APPROVED** [review]

**Pull request merged**
