### PR TITLE
Gmres n tmp vectors bound

### PR DESCRIPTION
**Pull request by drwells**
Another coverity catch.

### CODE REVIEW

**Comment by masterleinad** [comment]
> home/bob/source/include/deal.II/lac/solver_gmres.h:784:38: error: no matching function for call to 'max'
  const unsigned int n_tmp_vectors = std::max(additional_data.max_n_tmp_vectors, 3);
 
`clang` doesn't like that.
```
const unsigned int n_tmp_vectors = std::max(additional_data.max_n_tmp_vectors, 3U);
```
should probably work.

**Comment by bangerth** [comment]
OK to merge if you manage to get a modified version past the testers.

**Comment by drwells** [comment]
whoops; that should be `3u`. I'll fix it.

**Pull request merged**
