### PR TITLE
Fix SymEngine tests for SymEngine version 0.7 and greater

### LINKED ISSUE #10016: Compatibility with current symengine dev version
I have uniform fallout with the current development version of symengine, trying again locally with version 0.6.0:
  https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=5978

### PR DESCRIPTION
**Pull request by jppelteret**
- Change now invalid conversion operation between symbolic double and real double
- Simply some output to make it deterministic (remove all symbolic output when evaluated numeric output is available)
- Provide some alternative output when no numeric output is available (and the test specifically serves to check the symbolic output)

Fixes #10016

### CODE REVIEW

**Comment by drwells** [comment]
I had to add
```cpp

#include <deal.II/lac/full_matrix.h>
#include <deal.II/lac/vector.h>

```

to `batch_optimizer_01.h` to get this to compile. The test

    10821 - symengine/batch_optimizer_01_1b.release (Failed)

also still fails for me. Otherwise this is good since it fixes 99% of the test failures for symengine.

**Comment by drwells** [comment]
In particular:
```
10821: symengine/batch_optimizer_01_1b.release: DIFF failed. ------ Diff:   /home/drwells/Documents/Code/CPP/dealii-dev/build/tests/symengine/batch_optimizer_01_1b.release/failing_diff
10821: symengine/batch_optimizer_01_1b.release: DIFF failed. ------ First 20 lines of numdiff output:
10821: ----------------
10821: ##883     #:9   <== 21.72508240
10821: ##883     #:9   ==> 21.72508049
10821: @ Absolute error = 1.9100000000e-6, Relative error = 8.7916820418e-8
```

**Comment by jppelteret** [comment]
@drwells I've added those missing includes (how did this test ever compile?) and have reduced the precision in the output for `symengine/batch_optimizer_01_1b`.

**Review by drwells — APPROVED** [review]

**Comment by drwells** [comment]
I checked and all the tests pass with symengine 0.7, so lets merge!

**Pull request merged**
