### PR TITLE
Add some more tests for iterator filters

### LINKED ISSUE #13169: Compilation Error when Combining IteratorFilter with FEInterfaceValues
The code below uses an iterator filter together with `FEInterfaceValues` but gives a rather unexpected compilation error with gcc 10.3.0. I don't understand if the problem is with the filter, the `reinit` function or the compiler.

```c++
#include <deal.II/base/quadrature_lib.h>

#include <deal.II/dofs/dof_handler.h>

#include <deal.II/fe/fe_interface_values.h>
#include <deal.II/fe/fe_q.h>

#include <deal.II/grid/filtered_iterator.h>

using namespace dealii;

int
main()
{
  const int dim = 2;

  const FE_Q<dim>       fe(1);
  const QGauss<dim - 1> quadrature(1);

  FEInterfaceValues<dim> fe_interface_values(fe, quadrature, update_default);


  DoFHandler<dim> dof_handler;
  for (const auto &cell : dof_handler.active_cell_iterators() |
                            IteratorFilters::ActiveFEIndexEqualTo(0))
    {
      const unsigned int invalid_subface = numbers::invalid_unsigned_int;
      const unsigned int face_index      = 0;

      fe_interface_values.reinit(cell,
                                 face_index,
                                 invalid_subface,
                                 cell->neighbor(face_index),
                                 cell->neighbor_of_neighbor(face_index),
                                 invalid_subface);
    }
}
```
Compilation error:
```
[ 50%] Building CXX object CMakeFiles/example.dir/example.cc.o
In file included from /home/simon/workspace/sandbox/example.cc:8:
/home/simon/bin/dealii/include/deal.II/grid/filtered_iterator.h: In instantiation of ‘bool dealii::FilteredIterator<BaseIterator>::PredicateTemplate<Predicate>::operator()(const BaseIterator&) const [with Predicate = dealii::TriaIterator<dealii::DoFCellAccessor<2, 2, false> >; BaseIterator = dealii::TriaActiveIterator<dealii::DoFCellAccessor<2, 2, false> >]’:
/home/simon/bin/dealii/include/deal.II/grid/filtered_iterator.h:1343:1:   required from here
/home/simon/bin/dealii/include/deal.II/grid/filtered_iterator.h:1346:19: error: no match for call to ‘(const dealii::TriaIterator<dealii::DoFCellAccessor<2, 2, false> >) (const dealii::TriaActiveIterator<dealii::DoFCellAccessor<2, 2, false> >&)’
 1346 |   return predicate(bi);
      |          ~~~~~~~~~^~~~
make[2]: *** [CMakeFiles/example.dir/build.make:82: CMakeFiles/example.dir/example.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/example.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```

### PR DESCRIPTION
**Pull request by jppelteret**
Fixes #13169

### CODE REVIEW

**Comment by jppelteret** [comment]
@simonsticko Can you check if this works for you?

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
You currently have this error in a number of places:
```
/jenkins/workspace/dealii_PR-13170/tests/grid/filtered_iterator_07_operator.cc:55:26: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   Assert(n_cells_visited == Utilities::fixed_power<dim>(2),
                          ^
```
(Also line 99, and in the corresponding test without `_operator` in the name.)

**Comment by simonsticko** [comment]
> @simonsticko Can you check if this works for you?

Yes, works for me. :+1:

**Comment by jppelteret** [comment]
> Yes, works for me.

Great, thanks for the confirmation.

> You currently have this error in a number of places:

Thanks for the heads up. I've changed the counter type from `unsigned int` to `int`.

**Pull request merged**
