### PR TITLE
Use std::next instead of ++object.begin().

### PR DESCRIPTION
**Pull request by bangerth**
I didn't know about `std::next` until @drwells pointed it out in #12692. In the description at https://en.cppreference.com/w/cpp/iterator/next, there is a sentence that caught my eye:

> Although the expression ++c.begin() often compiles, it is not guaranteed to do so: c.begin() is an rvalue expression, and there is no LegacyInputIterator requirement that specifies that increment of an rvalue is guaranteed to work. In particular, when iterators are implemented as pointers or its operator++ is lvalue-ref-qualified, ++c.begin() does not compile, while std::next(c.begin()) does.

I also often find it sort of awkward to read `++triangulation.begin()` because the operation `++` is at the opposite end of the expression from where I get to see what the object is that is being operated on (namely, `.begin()`). `std::next` doesn't fit this, but I still find it easier to read.

/rebuild

### CODE REVIEW

**Comment by drwells** [comment]
A bunch of tests fail because `std::next()` assumes that the iterator type defines `difference_type` when it isn't just a pointer.

**Comment by marcfehling** [comment]
There are still a few tests failing on the `jenkins CI`
```
1070 - bits/sparse_matrix_iterator_12.debug (Failed)
1080 - bits/sparse_matrix_iterator_11.debug (Failed)
1243 - bits/chunk_sparse_matrix_iterator_12.debug (Failed)
1347 - bits/chunk_sparse_matrix_iterator_11.debug (Failed)
```

It basically boils down to issues for these two iterator types
```
error: no matching function for call to ‘next(dealii::SparseMatrix<double>::iterator)’
error: no matching function for call to ‘next(dealii::ChunkSparseMatrix<double>::iterator)’
```

and the error messages are of the type `template argument deduction/substitution failed`
```
1065/4425 Test #1070: bits/sparse_matrix_iterator_12.debug .........................................***Failed    4.02 sec
/jenkins/workspace/dealii_PR-12717/tests/bits/sparse_matrix_iterator_12.cc: In function ‘void test()’:
/jenkins/workspace/dealii_PR-12717/tests/bits/sparse_matrix_iterator_12.cc:42:78: error: no matching function for call to ‘next(dealii::SparseMatrix<double>::iterator)’
   SparseMatrix<double>::const_iterator k = A.begin(), j = std::next(A.begin());
                                                                              ^
In file included from /usr/include/c++/5/bits/stl_algobase.h:66:0,
                 from /usr/include/c++/5/bits/char_traits.h:39,
                 from /usr/include/c++/5/ios:40,
                 from /usr/include/c++/5/istream:38,
                 from /usr/include/c++/5/sstream:38,
                 from /usr/include/c++/5/complex:45,
                 from /jenkins/workspace/dealii_PR-12717/include/deal.II/base/numbers.h:29,
                 from /home/dealii/build/include/deal.II/base/config.h:501,
                 from /jenkins/workspace/dealii_PR-12717/include/deal.II/lac/sparse_matrix.h:20,
                 from /jenkins/workspace/dealii_PR-12717/tests/bits/sparse_matrix_iterator_12.cc:20:
/usr/include/c++/5/bits/stl_iterator_base_funcs.h:184:5: note: candidate: template<class _ForwardIterator> _ForwardIterator std::next(_ForwardIterator, typename std::iterator_traits<_Iter>::difference_type)
     next(_ForwardIterator __x, typename
     ^
/usr/include/c++/5/bits/stl_iterator_base_funcs.h:184:5: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/stl_iterator_base_funcs.h: In substitution of ‘template<class _ForwardIterator> _ForwardIterator std::next(_ForwardIterator, typename std::iterator_traits<_Iter>::difference_type) [with _ForwardIterator = dealii::SparseMatrixIterators::Iterator<double, false>]’:
/jenkins/workspace/dealii_PR-12717/tests/bits/sparse_matrix_iterator_12.cc:42:78:   required from here
/usr/include/c++/5/bits/stl_iterator_base_funcs.h:184:5: error: no type named ‘difference_type’ in ‘struct std::iterator_traits<dealii::SparseMatrixIterators::Iterator<double, false> >’
make[3]: *** [CMakeFiles/bits.sparse_matrix_iterator_12.debug.dir/sparse_matrix_iterator_12.cc.o] Error 1
```

**Comment by bangerth** [comment]
I had to add a bit more infrastructure to teach `std::iterator_traits` about our iterators, but it works now.

**Comment by marcfehling** [comment]
> I had to add a bit more infrastructure to teach `std::iterator_traits` about our iterators, but it works now.

I see that the few more using-declarations did the trick!

**Comment by bangerth** [comment]
It was the addition of the specializations of `std::iterator_traits`. I have to admit that I don't like this business of specializing things located in `namespace std`...

**Pull request merged**
