### PR TITLE
Pass by const reference instead of const value.

### PR DESCRIPTION
**Pull request by drwells**
Caught by coverity.

### CODE REVIEW

**Comment by drwells** [comment]
whoops. Fixed.

**Comment by drwells** [comment]
```

FAILED: cd /home/bob/build-clang/source/fe && 
/home/bob/build-clang/bin/expand_instantiations
/home/bob/build-clang/share/deal.II/template-arguments <
/home/bob/source/source/fe/fe_q.inst.in >
/home/bob/build-clang/source/fe/fe_q.inst.tmp &&
/usr/bin/cmake -E rename /home/bob/build-clang/source/fe/fe_q.inst.tmp
/home/bob/build-clang/source/fe/fe_q.inst
Invalid instantiation list: missing 'for'
ninja: build stopped: subcommand failed.
```

I think Bob is unhappy.

**Comment by masterleinad** [comment]
Let's just merge. The error is clearly spurious or unrelated to this PR.

**Pull request merged**
