### PR TITLE
If a test fails, also reports the error code.

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Comment by tjhei** [comment]
Out of curiosity, when is that useful? Do we have any test with interesting return values?

**Comment by bangerth** [comment]
That is useful for #965 where a test aborts with a floating point exception, which yields a return value of 136. I think the same would be the case for a segmentation fault (return value 9) instead of the standard failure code of 1.

**Comment by tjhei** [comment]
I am not sure how this will help you though because the error output of the test will be captured anyways, right? Do you want to grep for the return value or something?

**Comment by bangerth** [comment]
If a program is aborted with a segmentation fault, the message that says "Program aborted, segmentation fault" isn't printed to either stdout nor stderr. I tried to capture it and just write it into the output file, but that doesn't seem to work. I think the message is really just printed by the shell that executed the program, and where that output ends up in ctest I have no idea.

**Comment by tjhei** [comment]
Oh, okay. Thanks for explaining.

**Pull request merged**
