### PR TITLE
Convert a lot of places to range-based loops over all active cells.

### PR DESCRIPTION
**Pull request by bangerth**
Done in the same way as #9603. Follow-up to #9240. This is exceedingly mechanical -- I haven't touched a single place by hand (the only one I did I put into a separate PR: #9605.)

/rebuild

### CODE REVIEW

**Comment by masterleinad** [comment]
Looks like you need to address some merge conflicts.

**Comment by bangerth** [comment]
Let's see about now.

**Comment by bangerth** [comment]
Just for the statistics -- I'm deleting 180 lines of code :-)

**Comment by tjhei** [comment]
we need to check with a recent version of clang to detect unused variable warnings like #9609 before we merge.

**Comment by bangerth** [comment]
I compiled it in release mode and didn't see any warnings.

**Comment by tjhei** [comment]
can you rebase to master? There are some conflicts.

**Comment by bangerth** [comment]
I fixed the merge conflicts.

**Pull request merged**
