### PR TITLE
Update bundled boost

### LINKED ISSUE #7830: Update bundled boost
#3279 was the last update of the bundled `boost` package. In the meantime we needed to apply quite some changes to fix issues with recent compilers.

We should update the package after the next release to not diverge.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #7830 by updating to `boost-1.70.0`. I want to run the test suite first before cleaning this up.
I first updated all the files we are already using, then added missing required packages, and added `override`.

### CODE REVIEW

**Comment by drwells** [comment]
This looks like a lot but its of comparable size to last time: see #3279.

Did you delete the boost libraries that we deleted last time too?

**Comment by masterleinad** [comment]
> Did you delete the boost libraries that we deleted last time too?

I didn't delete anything. I just added libraries that were needed for compiling. In total, these are 209 new files.

**Comment by kronbichler** [comment]
This looks reasonable to me. Can you please have a look at the failing CI tests related to boost?

**Comment by masterleinad** [comment]
Yes, I am on it.

**Comment by masterleinad** [comment]
Great! I will clean up the commits soonish.

**Comment by masterleinad** [comment]
I cleaned the history. This should be ready.

**Comment by masterleinad** [comment]
Admittedly, I am still seeing
```
bundled/boost-1.62.0/include/boost/mpl/set/aux_/item.hpp:47:84: error: friend declaration 'char (& boost::mpl::operator||(const boost::mpl::s_item<T, Base>&, boost::mpl::aux::type_wrapper<T>*))[boost::mpl::s_item<T, Base>::order:: value]' declares a non-template function [-Werror=non-template-friend]
     BOOST_MPL_AUX_SET_OVERLOAD( order_tag_, ORDER_BY_KEY, s_item, aux::type_wrapper<T>* );
                                                                                    ^
bundled/boost-1.62.0/include/boost/mpl/set/aux_/item.hpp:47:84: note: (if this is not what you intended, make sure the function template has already been declared and add <> after the function name here) 
bundled/boost-1.62.0/include/boost/mpl/set/aux_/item.hpp:48:98: error: friend declaration 'char (& boost::mpl::operator%(const boost::mpl::s_item<T, Base>&, boost::mpl::aux::type_wrapper<T>*))[1]' declares a non-template function [-Werror=non-template-friend]
bundled/boost-1.62.0/include/boost/mpl/set/aux_/item.hpp:63:99: error: friend declaration 'char (& boost::mpl::operator%(const boost::mpl::s_mask<T, Base>&, boost::mpl::aux::type_wrapper<T>*))[2]' declares a non-template function [-Werror=non-template-friend]
bundled/boost-1.62.0/include/boost/mpl/set/aux_/item.hpp:77:100: error: friend declaration 'char (& boost::mpl::operator%(const boost::mpl::s_unmask<T, Base>&, boost::mpl::aux::type_wrapper<T>*))[1]' declares a non-template function [-Werror=non-template-friend]
```
with `gcc-5.4.0`(and `CUDA`) but that is preexisting.

**Comment by bangerth** [comment]
I see no meaningful way to review this patch. Since @kronbichler was already ok with it, and so am I, let's pull the trigger. The earlier we commit this patch, the longer we have to figure out what works and what doesn't.

**Pull request merged**
