### PR TITLE
Fix unused-but-set-variable warnings

### PR DESCRIPTION
**Pull request by Rombur**

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
LGTM

**Review by marcfehling — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]

**Comment by bangerth** [comment]
How did you find this? It's an interesting compiler analysis: Apparently, the compiler figured out that we are only ever writing into a variable, but never reading from it. That's a much more complicated analysis than to determine that we never *use* it...

**Comment by masterleinad** [comment]
Recent clang versions produce these kinds of warnings.

**Comment by Rombur** [comment]
Yes, I found that using the clang 13

**Pull request merged**
