### PR TITLE
Provide a template variable that can be used to query whether T is a natively supported MPI type.

### PR DESCRIPTION
**Pull request by bangerth**
Building a bit of infrastructure that I then want to next use in `std::enable_if` clauses. This is in essence a C++20-style concept that we can at a later time use if we want to convert `enable_if` clauses into `requires` clauses.

/rebuild

### CODE REVIEW

**Comment by bangerth** [comment]
Ping?

**Review by tjhei — APPROVED** [review]
Looks good to me.

**Comment by masterleinad** [comment]
This reminded me of https://github.com/dealii/dealii/pull/12954 which does something very similar. I was surprised that that one was never finished, though.

**Comment by bangerth** [comment]
If anyone would like to merge this, then I'll rebase #12954 on top and finish it off.

**Comment by bangerth** [comment]
Optimizing `MPI::broadcast` was indeed what I wrote this for.

**Review by masterleinad — APPROVED** [review]

**Pull request merged**
