### PR TITLE
Move some class declarations into the .h file.

### LINKED ISSUE #10284: Bug in AffineConstraintsData
Here's a bug that takes a good long time to explain -- story time: 

`AffineConstraints::distribute_local_to_global()` in its various incarnations uses an object of type `internals::AffineConstraintsData<number>` as a scratch object to work on. That class is, in essence, a singleton:
```
  template <typename number>
  class AffineConstraintsData
  {
  public:
    struct ScratchData
    { ... };

   ...

  private:
    /**
     * The actual data object that contains a scratch data for each thread.
     */
    static Threads::ThreadLocalStorage<ScratchData> scratch_data;
  };
```
All accesses are then through the `static` member variable, which is thread-local and consequently doesn't get in the way as long as each thread on which `AffineConstraints::distribute_local_to_global()` doesn't get interrupted by another call to the same function while it works. (But there is a check that would abort the program with an error if that were to happen.)

The bug now happens in the following context: If one configures deal.II with `DEAL_II_WITH_THREADS=OFF`, then the thread-local variable expands to just one global variable (it's `static` after all). That's fine if we're really just running single-threaded, but maybe we want to use `std::async` anyway -- in other words, we don't want to use the TBB facilities but just the C++11 ones. Why would one want to do that? Because we don't support the TBB on Windows -- so `DEAL_II_WITH_THREADS=OFF`, but maybe we want to run a few things in parallel anyway. For example, if one wanted to solve the PDE with different parameter values: an embarrassingly parallel  problem.

Well, back to the issue at hand: `scratch_data` in that case exists only once, but multiple threads all want to call `AffineConstraints::distribute_local_to_global()` on their respective data structures, and that is going to create trouble.

So how do we address this kind of thing?

### PR DESCRIPTION
**Pull request by bangerth**
Next step in my quest to fix #10284. I need to create one of these cache objects in the `AffineConstraints` class, so the cache class (and everything that is referenced in it) needs to be in the `.h` file.

No functional changes, just moving stuff from one file to another.

/rebuild

### CODE REVIEW

**Comment by bangerth** [comment]
The one test that has not completed appears spurious. All the other tests succeed.

**Comment by masterleinad** [comment]
Just for clarification:
You are saying that you need to create `Cache` objects directly in `affine_constraints.h` and not just in `affine_constraints.templates.h` or `affine_constraints.cc`?

**Comment by bangerth** [comment]
@drwells Correct. We currently have one global such object, declared and defined in the `.templates.h` file. I want to make this object a member variable of `AffineConstraints`, which -- being declared in the `.h` file -- requires me to move these classes to the `.h` file.

**Comment by drwells** [comment]
I think you meant to @masterleinad there.

**Pull request merged**
