### PR TITLE
Remove deprecated functions

### PR DESCRIPTION
**Pull request by bangerth**
This is the first part of getting rid of the many deprecated functions we have. More patches coming over time.

I have tried to remove the remaining functions in MGConstrainedDoFs but they do not have obvious replacements and are used extensively in the testsuite to a degree that I feel not qualified to address. Someone else will have to take care of these.

### CODE REVIEW

**Comment by tjhei** [comment]
@guidokanschat do you agree ``MGConstrainedDoFs::at_refinement_edge_boundary`` and ``MGConstrainedDoFs::non_refinement_edge_index`` are good to be removed?

**Comment by tjhei** [comment]
@bangerth can you rebase to master please? Looks good otherwise.

**Comment by bangerth** [comment]
I've rebased. 

@Guido: The functions in question were deprecated last July but previously already marked for removal. In any case, they are available but deprecated in 8.2, so I'd like to remove them for 8.3.

**Comment by tamiko** [comment]
Looks good.

While we're at it: What about (in a separate pull-request)
 - removing the direct mumps interface as well
 - removing the compatibility definitions in <code>configure.h.in</code> and reducing it in size?

(One could even think about removing the Make.global_options.in comatibility cruft as well.)

**Comment by bangerth** [comment]
Both valid targets. Feel free to open issues for them and I or someone else will eventually get to them. Right now I'm still fighting with the 150+ other functions that had previously been deprecated...

**Comment by bangerth** [comment]
@guidokanschat : Your input was requested here -- it's a big patch touching many files, so I'd like to not keep it open for too long.

**Comment by guidokanschat** [comment]
The functions in MGConstrainedDoFs can go. They should not be called by user code anyway

**Pull request merged**
