### PR TITLE
Introduce SolverGMRES::connect_re_orthogonalization_slot

### LINKED ISSUE #5011: Use signal to monitor re-orthogonalization in SolverGMRES
Once #4730 is merged, the automatic re-orthogonalization of SolverGMRES will not be directly visible to the user any more, which might cause confusion when looking at the solver behavior in certain cases. In order not to forget about that, we should add a signal that a user can connect to in case such an event happens.

In reference to #5008.

### PR DESCRIPTION
**Pull request by masterleinad**
Introduce a signal for reorthogonalization in `SolverGMRES` and redo #5008.
Fixes #5011.

@kronbichler A peace offer to you :wink:

### CODE REVIEW

**Comment by masterleinad** [comment]
Passes a local testsuite run.

**Comment by masterleinad** [comment]
I am quite sure that the failing test is unrelated.

**Comment by kronbichler** [comment]
Yes, that failure is unrelated.

**Pull request merged**
