### PR TITLE
Fix a bug from #432: Only do MPI::sum when MPI is initialized.

### PR DESCRIPTION
**Pull request by kronbichler**

### CODE REVIEW

**Comment by bangerth** [comment]
So you have MPI compiled in, but you're working in a program that doesn't use MPI and so doesn't initialize the MPI system?

The patch is ok, please merge unless you think that these kinds of checks might actually be better handled inside the various functions in namespace Utilities::MPI.

**Comment by kronbichler** [comment]
Yes indeed. There is a similar check further up in source/base/partitioner.cc.

Regarding the checks: Intuitively I would say that this single function, job_supports_mpi(), better fits into the Utilities::MPI namespace. It's MPI-related and we have moved everything else there. If you agree, I will create a separate pull request and deprecate this old interface.

**Comment by bangerth** [comment]
I didn't move it because it wasn't there already with the old location deprecated. But you can move it and leave the old function in place with a deprecation marker.

What I meant with the remark was more whether the call to `job_supports_mpi` should in fact be inside `Utilities::MPI::max`, rather than in every place where we call the function?

**Comment by kronbichler** [comment]
Oh, I see. Having the check there might be a good idea if the cost of MPI_Initialized() is low enough since we would call it on every MPI_Allreduce call. I have never looked into that but I would expect it to be reasonably cheap and thread-safe. Anyone who knows more about it?

**Comment by bangerth** [comment]
I can't imagine it being more than returning a pre-evaluated boolean. Surely it doesn't involve communication, so it must be cheap compared to the actual communication.

**Comment by kronbichler** [comment]
This is what I expect as well. I will move it there in a separate pull request.

**Pull request merged**
