### PR TITLE
Replace some DEAL_II_WITH_P4EST with DEAL_II_WITH_MPI

### PR DESCRIPTION
**Pull request by peterrum**
some lines I have forgotten in PR #9215... Sorry about this!

ping @tjhei

### CODE REVIEW

**Comment by kronbichler** [comment]
@peterrum would you mind fixing the error that clang-tidy complains about - not introduced by you but now visible:
```
/jenkins/workspace/dealii-tidy_PR-9224/so/jenkins/workspace/dealii-tidy_PR-9224/source/dofs/dof_handler_policy.cc:4466:68: error: use nullptr [modernize-use-nullptr,-warnings-as-errors]
/jenkins/workspace/dealii-tidy_PR-9224/source/dofs/dof_handler_policy.cc:4527:57: error: use nullptr [modernize-use-nullptr,-warnings-as-errors]
```

**Comment by peterrum** [comment]
@kronbichler Done! Now deal.II should be `NULL`-free ;)

**Pull request merged**
