### PR TITLE
step-67 simplex test

### PR DESCRIPTION
**Pull request by zjiaqi2018**
Added step-67 simplex test. 
Floating point exceptions are disabled to avoid a division by zero, see the discussions [#11889](https://github.com/dealii/dealii/issues/11889).

### CODE REVIEW

**Review by peterrum — COMMENTED** [review]
Excellent! May I ask you to shortly describe the performed modifications in the header of the file. You can take a look at the other (simplex step) test how it is done there.

**Comment by zjiaqi2018** [comment]
> Excellent! May I ask you to shortly describe the performed modifications in the header of the file. You can take a look at the other (simplex step) test how it is done there.

Yes, I described the major modifications there.

**Review by peterrum — APPROVED** [review]
Thank you! Great to see step-67 on simplices!

**Pull request merged**
