### PR TITLE
Add a particle test.

### PR DESCRIPTION
**Pull request by bangerth**
I felt like I wanted another test to check for the various particle improvements (see everything linked to from #11206). This patch adds a slightly modified version of step-19 as a test -- specifically modified to run within just a few seconds.

/rebuild

### CODE REVIEW

**Comment by bangerth** [comment]
I believe that the CI (serial build) check failure is spurious.

**Comment by masterleinad** [comment]
```
/tmp/cccynDNr.s: Fatal error: can't close CMakeFiles/chart_manifold_04_embedded.debug.dir/chart_manifold_04_embedded.cc.o: No space left on device
```

**Comment by masterleinad** [comment]
Let's retry.

/rebuild

**Review by kronbichler — APPROVED** [review]
This looks good to me in principle, so I already approve. However, I would suggest to remove comments unless you see a good reason for keeping them: Sooner or later they will diverge from the tutorial program so I would see them as merely disturbing here.

**Comment by bangerth** [comment]
I think that if there is divergence between the tutorial program and the test, that it would be that much more useful to have the comments left in. These comments comment the state of the test, not whatever is in the tutorial at any given time.

I recognize that the comments are written at a different level than we usually do for tests, but I think that they still provide a small benefit when left in.

**Pull request merged**
