### PR TITLE
Remove DEAL_II_HAVE_ISFINITE.

### PR DESCRIPTION
**Pull request by drwells**
This function is now part of the C++11 standard.

### CODE REVIEW

**Comment by tjhei** [comment]
We don't we deprecate our ``is_finite`` and use ``std::isfinite`` everywhere in the library?

**Comment by bangerth** [comment]
/run-tests
OK to merge once the tester is happy.

**Comment by bangerth** [comment]
@tjhei 's suggestion is useful, but separate. Can someone open a PR?

**Comment by drwells** [comment]
The issue with this is that `std::isfinite` does not have complex-valued overloads, but our own `is_finite` does.

**Comment by tamiko** [comment]
Tests seem to be unrelated (famous last words).

**Pull request merged**
