### PR TITLE
CMake: remove find_package override

### LINKED ISSUE #14065: Configuration: Checking for parallel HDF5 fails
The check for parallel HDF5 (version 1.10.7, built through spack) is failing for my configuration. Specifically, [this line](https://github.com/dealii/dealii/blob/master/cmake/configure/configure_50_hdf5.cmake#L28) seems to be the culprit. Maybe this flag is not present in all versions of HDF5?

Here is the relevant part of the configuration output:
```
     596    --   HDF5_INCLUDE_DIRS: <PATH>/hdf5-1.10.7-dtklg2jrvt6qmxacwfp5bkpohggkt3bf/include;<PATH>/openmpi-4.1.4-eis7yrm5hdpkyjqewqdrdowk2664ujj4/include
     597    --   HDF5_USER_INCLUDE_DIRS: <PATH>/hdf5-1.10.7-dtklg2jrvt6qmxacwfp5bkpohggkt3bf/include;<PATH>/openmpi-4.1.4-eis7yrm5hdpkyjqewqdrdowk2664ujj4/include
     598    --   HDF5_LIBRARIES: <PATH>/hdf5-1.10.7-dtklg2jrvt6qmxacwfp5bkpohggkt3bf/lib/libhdf5.so;<PATH>/openmpi-4.1.4-eis7yrm5hdpkyjqewqdrdowk2664ujj4/lib/libmpi.so
     599    -- Found HDF5
     600    -- Insufficient hdf5 installation found: hdf5 has to be configured with MPI support.
     601    -- DEAL_II_WITH_HDF5 has unmet external dependencies.
```

I also attach two of the HDF5 configuration files that indicate that it is build with parallel capabilities. 
[libhdf5.settings.txt](https://github.com/dealii/dealii/files/8995585/libhdf5.settings.txt)
[hdf5-config.cmake.txt](https://github.com/dealii/dealii/files/8995589/hdf5-config.cmake.txt)

### PR DESCRIPTION
**Pull request by tamiko**
Closes #14065

### CODE REVIEW

**Comment by tamiko** [comment]
@mathsen Would you mind verifying quickly that this change (i.e., removing the `FIND_PACKAGE` macro wrapper) fixes the problem?

**Comment by mathsen** [comment]
@tamiko Thanks for the quick fix - I can confirm that this commit fixes the spack build issue for me.

**Review by drwells — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]

**Comment by tamiko** [comment]
@tjhei I don't think so. It will make manual overrides a bit more difficult. But in retrospect - I think introducing this override had been a bad idea.

On a related note, I think it is time to modernize our dependency setup anyway (to use proper import targets for everything) and  this macro would have probably been removed in that process anyway.

**Review by tjhei — APPROVED** [review]

**Comment by jppelteret** [comment]
A bit late, but many thanks for fixing this @tamiko! And thank you for the detective work in #14065 @mathsen and @RichardYCJ.

**Pull request merged**
