### PR TITLE
Fix two mistakes with MPI initialization.

### PR DESCRIPTION
**Pull request by bangerth**
In one case, we unnecessarily initialize MPI. The second case undoes a recent
invalid patch that removed the initialization, but it turns out that we
actually need it because we use Trilinos (see the main function of step-31
for an explanation).

### CODE REVIEW

**Comment by tjhei** [comment]
One thing I just realized is that we also do the TBB thread limit stuff in MPI_InitFinalize (including parsing DEAL_II_NUM_THREADS). Does that mean we should call MPI_InitFinalize in many more examples? (every program that uses TBB)

**Comment by bangerth** [comment]
There's no problem with other tutorials. The default is to use as many threads as the TBB chooses, and I think this is reasonable, so there is no need to initialize the TBB explicitly. The reason why we call `MPI_InitFinalize` in programs that don't use MPI is that they rely on Trilinos and Trilinos wants the MPI system initialized whether the computation is parallel or not.

**Comment by tjhei** [comment]
> There's no problem with other tutorials. The default is to use as many threads as the TBB chooses

Yes, I know. But this means DEAL_II_NUM_THREADS is ignored, which is confusing. (see for example the thread on the mailing list from today, where Bruno suggests changing this variable even though it won't have any effect). 

This is unrelated to this patch, though. :-)

**Comment by tjhei** [comment]
See #415 for a discussion.

**Pull request merged**
