### PR TITLE
Add the tutorial to the doxygen pages.

### LINKED ISSUE #1594: Get tutorial a spot in the doxygen manual top menu
This from Joshua Hansel, from the mailing list:
.....................
Hi,

Maybe I'm blind, but sometimes I have a hard time finding the tutorials page when in the doxygen pages. I eventually manage to find it by clicking on the "Main Page" tab and then finding the link in the first sentence there, but I think a "Tutorials" tab on the doxygen pages would be helpful - it's the page that I (and I imagine plenty others) use most frequently. If it can be done, I think it would save some less experienced users some frustration.

Also, might I suggest a "suggestion" tag for suggested tags in the mailing list (for suggestions that aren't necessarily "feature_request"s)?

Thanks,
Joshua

### PR DESCRIPTION
**Pull request by bangerth**
Also reorder items a bit so that the 'related pages' come after modules,
namespaces, and classes.

This fixes #1594.

### CODE REVIEW

**Comment by bangerth** [comment]
I pushed a second commit that also adds a link to http://www.dealii.org to the top-level menu of all doxygen pages.

**Comment by tamiko** [comment]
Let's have a look.

**Comment by bangerth** [comment]
It looks good, I'd say: https://www.dealii.org/developer/doxygen/deal.II/index.html

**Comment by tjhei** [comment]
Yes. :+1:

**Pull request merged**
