### PR TITLE
Encapsulate functions in VectorOperations namespace

### LINKED ISSUE #3596: More descriptive namespace for `vector_operations_internal.h`
As discussed in #3594, we should not put the operations of `include/deal.II/lac/vector_operations_internal.h` into a general namespace `dealii::internal` but rather use the more descriptive namespace `dealii::internal::VectorOperations`. The namespace `internal` is overloaded already, so better classification is definitely helpful. (We have not released this code yet, it comes from #2577, so no need to be compatible whatsoever.)

### PR DESCRIPTION
**Pull request by Rombur**
fixes #3596

### CODE REVIEW

**Comment by bangerth** [comment]
It looks like the patch only includes parts where you now add one more namespace level to the names of functions you call. But I don't see the part where you actually move these functions into the extra namespace. Did I miss this?

**Comment by Rombur** [comment]
It should be there: https://github.com/dealii/dealii/pull/3748/files#diff-7e4f54390162a02eb055e1fe3f62faadL30 You need to load the diff, I think that there are too many difference because more than 2000 lines are changed (new indentation).

**Comment by Rombur** [comment]
Not sure why the build failed, I am not using boost...

**Comment by bangerth** [comment]
Oh, I missed this indeed. Thanks for pointing out the obvious!

I'm ok with merging this. @kronbichler -- any thoughts?

**Comment by kronbichler** [comment]
Great! Thanks for the change.

(The reason the tester failed was due to #3745.)

**Pull request merged**
