### PR TITLE
Tests: Provide output variants for clang-6 and libc++

### PR DESCRIPTION
**Pull request by tamiko**
These three tests fail due to using a different C++ standard library
(namely clang's libc++). This changes the renumbering in
dofs/dof_renumbering_02 slightly and of course the memory consumption
that gets printed in the fe/fe_move_0* tests.

Let's add some output variants.

### CODE REVIEW

**Comment by drwells** [comment]
Didn't we decide to get rid of all of the memory consumption tests for this reason?

**Comment by tamiko** [comment]
@drwells Good point. I removed the two `fe/fe_move` tests from this PR. Separate one incoming.

**Comment by drwells** [comment]
I do not understand why we get different results for this renumbering scheme with clang. Do you have any intuition for why this occurs?

Otherwise: all this PR does now is add an additional output file, so it can most likely be merged as-is.

**Comment by tamiko** [comment]
@drwells A lot of the `dofs/dof_renumbering_*` tests already have a couple of alternative outputs (depending on standard library and boost library).

I do not have any insight in what exactly of the standard algorithms cause the slightly different numbering. We probably simply use an `std::sort` variant (which is not stable).

**Comment by tamiko** [comment]
Anyone in the mood of merging this one? :-)

**Pull request merged**
