### PR TITLE
Fix include statements in testsuite

### PR DESCRIPTION
**Pull request by tamiko**
Changes:

95eee0e (Matthias Maier, 19 seconds ago)
   add a forgotten changelog entry

b32994e (Matthias Maier, 5 minutes ago)
   Testsuite: Fix includes

   One of the previous changes removed [...]/deal.II from the list of include
   directories. Consequently, it is now mandatory to prefix all deal.II
   includes with deal.II/

### CODE REVIEW

**Comment by bangerth** [comment]
Looks good. Which cmake patch removed the non-prefixed include paths? How did we not notice?

**Comment by tamiko** [comment]
Am 20. Jan 2015, 02:41 schrieb Wolfgang Bangerth <notifications@github.com>:

> Looks good. Which cmake patch removed the non-prefixed include paths?

  884a611474b6668c3f22cc0b7d448f6ccaec619e

> How did we not notice?

  *umh*

**Comment by bangerth** [comment]
My question was more "how did the testers still produce reasonable results". But it probably doesn't matter. Thanks for the patch!

**Comment by tamiko** [comment]
> My question was more "how did the testers still produce reasonable
> results". But it probably doesn't matter. Thanks for the patch!

Because with the exception of those 100 tests the rest are high
quality(tm) ones with full include paths :-P

**Pull request merged**
