### PR TITLE
Be explicit regarding zero tolerance in merge_triangulations

### PR DESCRIPTION
**Pull request by peterrum**
I was a bit surprised by this behavior. 

FYI @jh66637

### CODE REVIEW

**Review by tjhei — COMMENTED** [review]
I think we should treat 0 as an error instead and add an assert.

**Comment by peterrum** [comment]
> I think we should treat 0 as an error instead and add an assert.

I found the behavior also a bit confusing. But I have the fear that people are using/misusing the behavior. For examples, jh66637 does this in the test of https://github.com/dealii/dealii/pull/14059 to merge two triangulation into a single one without eliminating the vertices.

**Comment by jh66637** [comment]
That's correct. I use this behavior to generate non-matching grids, but I understand that this is not how the function was intended to be used. 
What do you think about adding a new function (e.g. merge_non_matching_triangulations()) to be able to get the behavior but in an explicit way? This way, tolerance==0.0 can be deprecated and later asserted in delete_duplicate_vertices().

Either way, let me know if I can help you on this topic.

**Comment by tjhei** [comment]
Interesting. I think a separate function would be a better design and less surprising. But I am okay with either option.

**Comment by peterrum** [comment]
> Interesting. I think a separate function would be a better design and less surprising. But I am okay with either option.

@tjhei  Personally, I would prefer to keep a single function for now.In the case of the new function `merge_non_matching_triangulations`, we would still have the same dilemma: with or without tolerance.

**Review by tjhei — APPROVED** [review]

**Comment by tjhei** [comment]
Fine. :-)

**Pull request merged**
