### PR TITLE
FlexibleIndexStorage: fix memory allocation

### PR DESCRIPTION
**Pull request by peterrum**

### CODE REVIEW

**Review by drwells — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]
Very good, thank you for the quick fix!

**Comment by kronbichler** [comment]
The failing test is intermittent. Let me merge this.

**Comment by marcfehling** [comment]
This resolves my memory related problems, and as a consequence also speeds up the setup of the `MGTwoLevelTransfer` objects. Thank you!

Data on my reference scenario.
Before:
```
level:0 DofHandlerFineView_AfterConstruction. vmpeak (GB): max=12.3383
level:1 DofHandlerFineView_AfterConstruction. vmpeak (GB): max=12.3383
[...]
level:11 DofHandlerFineView_AfterConstruction. vmpeak (GB): max=12.3383
level:12 DofHandlerFineView_AfterConstruction. vmpeak (GB): max=14.1199
level:13 DofHandlerFineView_AfterConstruction. vmpeak (GB): max=23.1199
level:14 DofHandlerFineView_AfterConstruction. vmpeak (GB): max=59.1199
level:15 DofHandlerFineView_AfterConstruction. vmpeak (GB): max=203.156
```

After:
```
level:0 DofHandlerFineView_AfterConstruction. vmpeak (GB): max=12.3383 sum=12.3383
level:1 DofHandlerFineView_AfterConstruction. vmpeak (GB): max=12.3383 sum=12.3383
[...]
level:11 DofHandlerFineView_AfterConstruction. vmpeak (GB): max=12.3383 sum=12.3383
level:12 DofHandlerFineView_AfterConstruction. vmpeak (GB): max=12.3383 sum=12.3383
level:13 DofHandlerFineView_AfterConstruction. vmpeak (GB): max=12.3383 sum=12.3383
level:14 DofHandlerFineView_AfterConstruction. vmpeak (GB): max=12.3383 sum=12.3383
level:15 DofHandlerFineView_AfterConstruction. vmpeak (GB): max=12.3383 sum=12.3383
```

**Comment by bangerth** [comment]
That's kind of a nice improvement :-)

**Comment by bangerth** [comment]
I think this would have deserved a changelog entry :-)

**Pull request merged**
