### PR TITLE
Remove using 'deallog' in the linear solvers.

### PR DESCRIPTION
**Pull request by bangerth**
In many cases, all that actually happened was pushing and popping a prefix,
but no actual output. In any case, the level of output was in most cases
not particularly useful to average users (e.g., saying that some restart
happened), and we generally like to have classes and functions that have
no side effects.

Relates to #4704.

### CODE REVIEW

**Comment by tjhei** [comment]
Isn't this used inside the testsuite? I would assume that you have to change output there, right?

**Comment by bangerth** [comment]
Hm...

/run-tests

**Comment by tamiko** [comment]
This is probably a perfect opportunity to replace all of the output in the testsuite by using `check_solver_within_range` :-P

**Comment by tamiko** [comment]
@bangerth Only 140 failing tests due to this change [1]. I suggest to port to `check_solver_within_range` :-)

[1] https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=9804

**Comment by tamiko** [comment]
Example output diff:
```
bits/deal_solver_04.debug: DIFF failed. ------ First 50 lines diff output:
*** /srv/testsuite/dealii/tests/bits/deal_solver_04.output	Wed May 24 02:22:07 2017
--- output	Tue Aug  8 23:15:38 2017
***************
*** 1,6 ****
  
  DEAL::Size 32 Unknowns 961
  DEAL::Solver type: N6dealii12SolverMinResINS_6VectorIdEEEE
! DEAL:minres::Starting value 31.00
! DEAL:minres::Convergence step 43 value 0.0006916
  DEAL::Solver stopped after 43 iterations
--- 1,6 ----
  
  DEAL::Size 32 Unknowns 961
  DEAL::Solver type: N6dealii12SolverMinResINS_6VectorIdEEEE
! DEAL::Starting value 31.00
! DEAL::Convergence step 43 value 0.0006916
  DEAL::Solver stopped after 43 iterations
```

**Comment by bangerth** [comment]
Should work now.

**Comment by tamiko** [comment]
I will let bob test again.

**Comment by bangerth** [comment]
Oh, that means changing all of the output files again :-(

That might have to wait until after the hackathon...

**Comment by bangerth** [comment]
Coming back to this: I don't like @tjhei's request. The goal of this patch is to remove `deallog` from at least a part of the code base. If we keep the `log_history` part of `SolverControl`, then I feel like nothing is actually achieved here -- we would be removing some references, but it doesn't really take us any closer to the goal of not outputting to some random global output stream that is hard to control and even harder to use in parallel contexts. 

My preference would be to implement/document equivalent ways of getting this sort of output from `SolverControl` without having to keep around the `log_history()` mechanism that utilizes `deallog`. That should, in fact, not be very difficult to do by adding a signal that is called every time in `check()` where we currently generate the output.

**Comment by bangerth** [comment]
@tjhei -- what's your opinion on my suggestion above?

**Comment by tjhei** [comment]
> Coming back to this: I don't like @tjhei's request.

I think when discussing over lunch at the workshop we agreed that it is quite useful to be able to log the history of a failing solver by adding only a small amount of code (right now: enable deallog, turn on log_history). I also don't think I am the only one who relies on this right now. I am not insisting that it has to stay exactly that way if you prefer to get rid of deallog inside ``SolverControl``, but it should still be "easy" to do (and documented somehow).
I think right now one would have to
1. ``enable_history_data``
2. wrap the ``solve()`` call with a try/catch
3. get and print the history data manually in the catch.

It would be great if we document and preferably simplify this.

**Comment by tjhei** [comment]
> It would be great if we document and preferably simplify this.

And as you said, something like ``solver_control.check_signal.attach([] (int iteration, double tolerance) {std::cout << "step " << iteration << ": " << residual << std::endl;});`` would be doable, right?

**Comment by bangerth** [comment]
That's precisely what I have in mind. Would you be amenable to such a solution?

If you agree, then I'll update this patch for all of the merge conflicts that have accumulated, and implement the solution above in a separate PR.

**Comment by tjhei** [comment]
> That's precisely what I have in mind. Would you be amenable to such a solution?

I am okay with that. @tamiko ?

**Comment by davydden** [comment]
@tamiko ping.

ps. It would also be good to have a signal for convergence (`solver_control.converge_signal.attach()`). Say if I use the linear solver inside the Krylov-type eigensolver, i would be interested to get the average number if iterations it took linear solver while applying `A^{-1}` and log this data.

**Comment by bangerth** [comment]
This patch is hopelessly outdated by now. Let's scrap this attempt.

**Pull request closed without merging**
