### PR TITLE
add yet another pair of outputs for Metis on macOS with Clang 9.0.0

### PR DESCRIPTION
**Pull request by davydden**
some of those tests have already 6 output files... 😞

### CODE REVIEW

**Comment by drwells** [comment]
This does not conflict with #5119.

**Comment by drwells** [comment]
Metis is tempermental enough that I would be happy just merging this without reproducing the output myself. Unless someone objects I propose that we do that in the next day or so.

**Comment by bangerth** [comment]
Well, it does conflict with #5119 in the sense that that patch marks up all output files based on whether they are 32-bit or 64-bit. If we merged this PR, we'd have to also rename the newly added output file.

**Comment by davydden** [comment]
> . If we merged this PR, we'd have to also rename the newly added output file.

Why? We don’t have any naming convention for blessed output files

**Comment by bangerth** [comment]
Yes, that's what I meant.

**Comment by tamiko** [comment]
Let's put this temporarily on "WIP" so that it doesn't get accidentally merged :-)

**Comment by davydden** [comment]
@bangerth i renamed the tests so that 64bit ints are disabled.

**Comment by masterleinad** [comment]
What about 64-bit indices enabled? Are the current output files appropriate already?

**Comment by davydden** [comment]
> What about 64-bit indices enabled? Are the current output files appropriate already?

no idea, i don't use 64-bit dealii on macOS.

**Pull request merged**
