### PR TITLE
Initialize member variables.

### LINKED ISSUE #3549: Static analysis: source/base/timer.cc

### PR DESCRIPTION
**Pull request by bangerth**
Fixes #3549.

### CODE REVIEW

**Comment by drwells** [comment]
Why don't we add a default constructor to `MinMaxAvg` that does this instead?

**Comment by bangerth** [comment]
Excellent point. I'll get to that tomorrow or Monday.

**Comment by bangerth** [comment]
It doesn't work. In fact, `MinMaxAvg` looks like this:
```
    struct MinMaxAvg
    {
      // Note: We assume a POD property of this struct in the MPI calls in
      // min_max_avg
      double sum;
      double min;
      double max;
      unsigned int min_index;
      unsigned int max_index;
      double avg;
    };
```
MPI doesn't work with non-POD data structures :-(

**Comment by bangerth** [comment]
In other words, I think we should still go with my current patch.

**Comment by drwells** [comment]
You are correct. I thought adding a default constructor would not change its POD-ness but the standard disagrees.

**Pull request merged**
