### PR TITLE
FEInterfaceValues::get_jump/average_*_function_values

### PR DESCRIPTION
**Pull request by zjiaqi2018**
Address https://github.com/dealii/dealii/issues/11464

Add FEInterfaceValues::functions get_*_function_values() to evaluate solution 
values across cell faces, such as the jump in (or average of) values, gradients, and Hessians.
@tjhei

### CODE REVIEW

**Comment by tjhei** [comment]
Great. I think this makes sense! Thank you. 👍 /rebuild

**Comment by luca-heltai** [comment]
Isn't this a duplicate of the FEInterfaceViews::Scalar functionality?

https://www.dealii.org/developer/doxygen/deal.II/classFEInterfaceViews_1_1Scalar.html

I agree to have it here as well, consistently to what we have also in FEValues. However, it would make sense to provide (maybe in another PR?)  also the versions for vector valued FES, filling a vector of vector of jumps/avg, etc.

**Comment by zjiaqi2018** [comment]
> Isn't this a duplicate of the FEInterfaceViews::Scalar functionality?
> 
> https://www.dealii.org/developer/doxygen/deal.II/classFEInterfaceViews_1_1Scalar.html

Yes.

> I agree to have it here as well, consistently to what we have also in FEValues. However, it would make sense to provide (maybe in another PR?) also the versions for vector valued FES, filling a vector of vector of jumps/avg, etc.

Will do it in another PR.
 
> To avoid code duplication, wouldn't it make sense to call within these functions, simply the corresponding Views function?

Yes, it makes sense. Thank you.

**Comment by tjhei** [comment]
> However, it would make sense to provide (maybe in another PR?) also the versions for vector valued FES, filling a vector of vector of jumps/avg, etc.

Those already exist in FEInterfaceViews::Vector though, right? I don't think it makes sense to have them in the FEInterfaceValues as well. You would almost always create a view.

**Comment by luca-heltai** [comment]
> Those already exist in FEInterfaceViews::Vector though, right? I don't think it makes sense to have them in the FEInterfaceValues as well. You would almost always create a view.

Not exactly. The interface of the multicomponent (not just vector valued) would look like:

`get_jumps_in_function_values(const &InVectorType, std::vector<std::vector<ValueType>> &jumps)`

i.e., it would return all components at once (say vx,vy,p for a stokes problem), coherently with the FEValues case.

**Review by luca-heltai — APPROVED** [review]

**Comment by tjhei** [comment]
> it would return all components at once (say [vx],[vy],[p] for a stokes problem), coherently with the FEValues case.

Okay, I didn't think those would be very useful to have.

**Comment by tjhei** [comment]
@zjiaqi2018 can you fix the following error please?
```
/Users/runner/work/dealii/dealii/include/deal.II/fe/fe_interface_values.h:3367:17: error: unused variable 'interface_dof_indices' [-Werror,-Wunused-variable]
```

**Review by peterrum — APPROVED** [review]
Excellent :)

**Pull request merged**
