### PR TITLE
Move the exodus conversion functions to RefereneCell.

### PR DESCRIPTION
**Pull request by bangerth**
/rebuild

### CODE REVIEW

**Comment by bangerth** [comment]
Follow-up to #11544.

**Review by drwells — APPROVED** [review]

**Comment by bangerth** [comment]
Ping?

**Comment by drwells** [comment]
Sorry for the delay - do you have exodus installed locally? If not I should compile this so we don't break the CI yet again.

**Comment by bangerth** [comment]
I don't, but the functions in question seem to have been used in only two places, which I fixed.

**Comment by bangerth** [comment]
But a cross check would certainly be appreciated!

**Comment by drwells** [comment]
I'll recompile and run the exodus tests locally and if everything passes I will merge. I'm pretty sure this PR is fine as-is but we have messed this up enough times recently that I want to check.

**Comment by bangerth** [comment]
Yes, we have :-)

**Comment by drwells** [comment]
It works!

**Comment by bangerth** [comment]
I appreciate the cross check!

**Pull request merged**
