### PR TITLE
Correct LinearAlgebra::distributed::BlockVector::memory_consumption()

### LINKED ISSUE #3359: Static analysis: dealii-git/include/deal.II/lac/la_parallel_block_vector.templates.h
```
dealii-git/include/deal.II/lac/la_parallel_block_vector.templates.h	762	err	V568 It's odd that the argument of sizeof() operator is the 'this->n_blocks()' expression.
```

We should address these warnings and errors from the static analysis tool PVS. In response to #3342.

### PR DESCRIPTION
**Pull request by kronbichler**
Fixes #3359.

PVS complained about a strange `sizeof() operator in terms of this->n_blocks()`. This was indeed wrong because that size is already contained in `MemoryConsumption::memory_consumption (this->block_indices);`

### CODE REVIEW

**Comment by bangerth** [comment]
I think it would be nice if you made the same changes as in #3390, just for symmetry. There was also the follow-up in #3432.

**Comment by kronbichler** [comment]
That's right. I missed #3432, too many commits lately ;-)

It's a pity that we have to re-implement the memory consumption method but due to inheritance from both `VectorSpaceVector` and `BlockVectorBase` this cannot be avoided. I also took the chance to add a memory consumption test for the block vector. It turned out that the memory consumption of a block vector is a bit tricky to measure (I got different results in debug and release mode with 64 bit integers), so I added two tests.

**Comment by bangerth** [comment]
I'm curious about the difference in debug/release modes. Our objects are supposed to be binary compatible, so this surprises me. Do you happen to know what causes the difference?

**Comment by kronbichler** [comment]
I could not see it directly, but I will have a look. I assume that an std::vector holding the vector entries gets capacity 3 in one case and length 4 in the other, but I have to confirm. The difference is 24 bytes.

**Comment by bangerth** [comment]
OK, that would be a harmless case. I was afraid that we have a member variable that is only conditionally part of the object, depending on whether we are in debug or release mode.

**Comment by kronbichler** [comment]
I've re-run the test and now get the same results for debug and release mode in 64 bits. I've re-run a few times now and this makes me wonder if I had a wrongly compiled file somewhere around (e.g. with the old code). I will prepare a PR that deletes the second alternative. We can always add it in case it is needed on the testers.

**Comment by bangerth** [comment]
OK, that's a relief. Thanks for checking!

**Pull request merged**
