### PR TITLE
Enable C++11 for CUDA

### LINKED ISSUE #2598: C++11 flags not passed to nvcc
I can compile deal.II with nvcc but when I add cuda code, I get an error for the c++11 functions. I have to add ```-DCUDA_NVCC_FLAGS="-std=c++11"``` during configuration. It seems the flags are not passed correctly to nvcc.

### PR DESCRIPTION
**Pull request by kalj**
Fixes #2598 .

### CODE REVIEW

**Comment by Rombur** [comment]
Should we throw an error if the compiler doesn't support C++11? I don't think it is worth the trouble to support cuda without C++11.

**Comment by kalj** [comment]
That's okay with me. New patch which throws an error if C++11 is not enabled.

**Comment by Rombur** [comment]
@kalj this PR broke CMake when deal.II is not compiled with C++11 http://cdash.kyomu.43-1.org/buildSummary.php?buildid=816 You should check for C++11 only if CUDA is found and ```DEAL_II_WITH_CUDA=ON```

**Comment by kalj** [comment]
Oh yeah. Major bummer. Fix pushed here #2616.

**Pull request merged**
