### PR TITLE
Compatibility with CGAL 6.0

### PR DESCRIPTION
**Pull request by sloriot**

### CODE REVIEW

**Review by tamiko — APPROVED** [review]
Thanks! I will run this against CGAL 5.6.1 and 6.0.0 quickly prior to merging.

**Comment by tamiko** [comment]
@sloriot Thanks a lot for the fix. I took the liberty to rebase and squash your commits and added a changelog entry in your name.

**Review by kronbichler — APPROVED** [review]

**Comment by tamiko** [comment]
Looking good:
```
100% tests passed, 0 tests failed out of 62
Total Test time (real) = 192.98 sec
```

**Pull request merged**
