### PR TITLE
extend example of user projects testsuite to contain header files

### PR DESCRIPTION
**Pull request by davydden**
the user in  https://groups.google.com/forum/?fromgroups#!topic/dealii/6YgunmMhva0 tried to follow the documentation but could not figure out how to setup includes. So adjust code snippets and directory structure to contain `support.h` to hopefully make the example complete.

### CODE REVIEW

**Comment by davydden** [comment]
@dealii/dealii can we merge this? 😄

**Comment by tjhei** [comment]
This looks okay to me.

Can you think of a good way of letting the reader know that they need to write ``#include <support.h>`` inside the test? (or is that written somewhere already that I didn't see)

**Comment by davydden** [comment]
@tjhei how about the updated version?

**Comment by tjhei** [comment]
:+1:

**Pull request merged**
