### PR TITLE
fix petsc installation readme

### PR DESCRIPTION
**Pull request by stefanozampini**
closes https://github.com/dealii/dealii/issues/17281

### CODE REVIEW

**Comment by stefanozampini** [comment]
@bangerth I have removed the mention of Trilinos ML since I believe it is outdated.

**Review by bangerth — APPROVED** [review]
Thank you!

**Comment by jpthiele** [comment]
> @bangerth I have removed the mention of Trilinos ML since I believe it is outdated.

Yes, Trilinos ML is bound to be removed next year together with the rest of the Epetra stack.
My question would be if the same effect can be observed with PETSc and MueLu which is the new Multigrid package of the Tpetra stack.

**Comment by stefanozampini** [comment]
PETSc maintains its own  stripped down version of ML. There's no conflict
with MueLU

**Comment by bangerth** [comment]
Also, I build with PETSc and Trilinos all the time and have not seen this problem in many years.

**Pull request merged**
