### PR TITLE
CMake: Fix path to deal.IIFeatureConfig.cmake

### PR DESCRIPTION
**Pull request by tamiko**
In reference to #4445

### CODE REVIEW

**Comment by tamiko** [comment]
> @tamiko common, what's' the difference?! In the original PR all the
> CMake files where in one place. So you change where from to install
> instead of where to save it.

The difference is that in the original pull request a

  FIND_PACKAGE(deal.II)
  INCLUDE(${DEAL_II_FEATURE_CONFIG})

when using the build directory *directly* will lead to a configure
error.

**Comment by davydden** [comment]
ok, let's roll with that and see if it works.

**Comment by tamiko** [comment]
@davydden Do me a favor and check it quickly as well :-D Boarding my final flight now.

**Comment by davydden** [comment]
this installs fine.

**Pull request merged**
