### PR TITLE
Add authors to the lines that list the code gallery programs.

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Comment by drwells** [comment]
Looks good aside from one small nitpick: there is an extra space generated before the closing parenthesis after the authors are listed.

**Comment by bangerth** [comment]
I avoided the space, and also made sure that authors are separated by commas.

**Comment by tamiko** [comment]
@bangerth candidate for 8.4?

**Comment by bangerth** [comment]
@tamiko -- not a bad idea. See #2193

**Pull request merged**
