### PR TITLE
Fix PETScWrappers::PreconditionBase warnings

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes https://cdash.dealii.43-1.org/viewBuildError.php?type=1&buildid=1961 by reverting commit cf6c923.

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]

**Comment by bangerth** [comment]
I would prefer if we deprecate the `PreconditionBoomerAMG` default constructor instead, and change our code base to use the non-default constructors.

**Comment by bangerth** [comment]
I can do this if you'd like me to (after Thanksgiving).

**Comment by masterleinad** [comment]
> I would prefer if we deprecate the `PreconditionBoomerAMG` default constructor instead, and change our code base to use the non-default constructors.

Hmm... I think the point of #14438 (or #14428) was to unify the interface for `PETSc` and `Trilinos` and the `Trilinos` preconditioners only have default constructors.

**Comment by bangerth** [comment]
I see. Fair point. Then why not remove the `=default` from the constructor and instead implement it by calling the base class constructor with `MPI_COMM_NULL`?

**Comment by masterleinad** [comment]
> I see. Fair point. Then why not remove the `=default` from the constructor and instead implement it by calling the base class constructor with `MPI_COMM_NULL`?

I don't care much either way. I did the changes in aa8e6183585d9ecf2f5165a049b1b13e5bb83f24.

**Review by bangerth — APPROVED** [review]
Oh, I had not realized that it is *all* of the preconditioners that had that problem. Thanks for tackling this!

**Pull request merged**
