### PR TITLE
Docker: Fix driver field.

### PR DESCRIPTION
**Pull request by marcfehling**
Follow-up to https://github.com/dealii/dealii/pull/16045.

### CODE REVIEW

**Comment by marcfehling** [comment]
My runner gets to the `login` stage
https://github.com/marcfehling/dealii/actions/runs/6316579919

**Review by masterleinad — APPROVED** [review]

**Comment by marcfehling** [comment]
Fingers crossed: https://github.com/dealii/dealii/actions/runs/6317283748

**Comment by marcfehling** [comment]
> Fingers crossed: https://github.com/dealii/dealii/actions/runs/6317283748

This didn't do the trick :-(

I think we either need to build the dockerimage manually and watch the process to make sure it succeed, or we need at more diagnostics to our workflow files, or we abandon the `focal` image.

**Comment by masterleinad** [comment]
> This didn't do the trick :-(

It was worth a try. 🙁

**Comment by masterleinad** [comment]
> I think we either need to build the dockerimage manually and watch the process to make sure it succeeds, or we need to add more diagnostics to our workflow files, or we abandon the `focal` image altogether.

I can build it locally without any problems.

**Pull request merged**
