### PR TITLE
Fix Tpetra vector compression state after add() into locally owned entry

### LINKED ISSUE #17615: Inconsistency in Tpetra Distributed Vector's `add()` function
**Description:**

While migrating from Epetra stack to Tpetra stack in my project, I encountered an issue related to distributed vectors.

**Problem:**

After assembling a non-ghost distributed vector (which allows writing to non-local entries), the program hangs when I call `my_vector.compress(VectorOperation::add)`.

**Potential Cause:**

I discovered that the inconsistency stems from `my_vector.compressed` across different processes. Specifically:

- On processes with only locally owned entries, the `Vector<Number, MemorySpace>::add()` function does not modify the internal `compressed` state.
- However, on processes with non-locally owned entries, `compressed` **is** modified, as in the [code snippet](https://github.com/dealii/dealii/blob/898bd72bf3a97852cf77f3eb1810d995127c5c09/include/deal.II/lac/trilinos_tpetra_vector.h#L1162C1-L1223C10) below from function `Vector<Number, MemorySpace>::add()`.
- 

```c++
          // Check if the index is in the locally owned index set.
          // If so, we can write right into the locally owned
          // part of the vector.
          if (TrilinosWrappers::types::int_type local_row =
                vector->getMap()->getLocalElement(row);
              local_row != Teuchos::OrdinalTraits<int>::invalid())
            {
              vector_1d_local(local_row) += values[i];
              // maybe missed a `compressed = false;` here?
            }
          else
            {
              // If the element was not in the locally owned part,
              // we need to figure out whether it is in the nonlocal
              // part. It better be:
              Assert(nonlocal_vector.get() != nullptr, ExcInternalError());
              TrilinosWrappers::types::int_type nonlocal_row =
                nonlocal_vector->getMap()->getLocalElement(row);


#  if DEAL_II_TRILINOS_VERSION_GTE(14, 0, 0)
              Assert(nonlocal_row != Teuchos::OrdinalTraits<int>::invalid(),
                     ExcAccessToNonLocalElement(
                       row,
                       vector->getMap()->getLocalNumElements(),
                       vector->getMap()->getMinLocalIndex(),
                       vector->getMap()->getMaxLocalIndex()));
#  else
              Assert(nonlocal_row != Teuchos::OrdinalTraits<int>::invalid(),
                     ExcAccessToNonLocalElement(
                       row,
                       vector->getMap()->getNodeNumElements(),
                       vector->getMap()->getMinLocalIndex(),
                       vector->getMap()->getMaxLocalIndex()));


#  endif


              // Having asserted that it is, write into the nonlocal part.
              // To do so, we first need to make sure that we have a view
              // of the nonlocal part of the vectors, since we have
              // deferred creating this view previously:
              if (!vector_1d_nonlocal)
                {
#  if DEAL_II_TRILINOS_VERSION_GTE(13, 2, 0)
                  auto vector_2d_nonlocal =
                    nonlocal_vector->template getLocalView<Kokkos::HostSpace>(
                      Tpetra::Access::ReadWrite);
#  else
                  auto vector_2d_nonlocal =
                    nonlocal_vector->template getLocalView<Kokkos::HostSpace>();
#  endif


                  vector_1d_nonlocal =
                    Kokkos::subview(vector_2d_nonlocal, Kokkos::ALL(), 0);


#  if !DEAL_II_TRILINOS_VERSION_GTE(13, 2, 0)
                  // Mark the nonlocal vector as to-be-modified as well.
                  nonlocal_vector->template modify<Kokkos::HostSpace>();
#  endif
                }
              (*vector_1d_nonlocal)(nonlocal_row) += values[i];
              compressed = false;
            }
```

This discrepancy leads to a hang during the vector compression, where an `if(!compressed)` condition seperate two different code paths on different processes.

### PR DESCRIPTION
**Pull request by QY-Shi**
To fix #17615.

### CODE REVIEW

**Comment by QY-Shi** [comment]
After adding this line, my project runs fine on my machine; however, 4 tests (13, 53, 54, 57) failed : (
I only use `distribute_local_to_global()` to add values to global entries, but the 4 failing tests seem to rely on the `+=` and `-=` with `operator(index)` for writable access, so there might still be an issue with those operators.

I admit that I’m somewhat confused by the inheritance relationships within many classes in dealii. I’m not entirely sure which exact code is responsible for obtaining a writable entry through the `operator(index)`.

**Comment by masterleinad** [comment]
```diff
diff --git a/include/deal.II/lac/trilinos_tpetra_vector.h b/include/deal.II/lac/trilinos_tpetra_vector.h
index efd37cc8a2..f093a661b6 100644
--- a/include/deal.II/lac/trilinos_tpetra_vector.h
+++ b/include/deal.II/lac/trilinos_tpetra_vector.h
@@ -1167,7 +1167,8 @@ namespace LinearAlgebra
               local_row != Teuchos::OrdinalTraits<int>::invalid())
             {
               vector_1d_local(local_row) += values[i];
-              compressed = false;
+              if (nonlocal_vector.get() != nullptr)
+                compressed = false;
             }
           else
             {
@@ -1286,6 +1287,8 @@ namespace LinearAlgebra
               local_row != Teuchos::OrdinalTraits<int>::invalid())
             {
               vector_1d_local(local_row) = values[i];
+              if (nonlocal_vector.get() != nullptr)
+                compressed = false;
             }
           else
             {
```
should fix it. Basically, we only need to mark the vector as non-compressed if we created the nonlocal vector indicating that some processes might have non-local entries.

Can you add a test for the issue you found?

**Comment by QY-Shi** [comment]
> should fix it. Basically, we only need to mark the vector as non-compressed if we created the nonlocal vector indicating that some processes might have non-local entries.

Ah, I see! I forgot that a locally owned vector is always in a compressed state. I’ll correct this mistake right away.

> Can you add a test for the issue you found?

As for the test, I haven’t submitted any tests for dealii before, so please excuse my amateurish questions. How can I ensure that my test is run with multiple MPI processes? Do I just need to add a file under `tests/trilinos_tpetra`, and it will automatically be compiled and run by CMake?

**Comment by masterleinad** [comment]
> As for the test, I haven’t submitted any tests for dealii before, so please excuse my amateurish questions. How can I ensure that my test is run with multiple MPI processes? Do I just need to add a file under `tests/trilinos_tpetra`, and it will automatically be compiled and run by CMake?

Yes, just have a look at the existing tests there. In particular, you have to provide an output file that contains the expected outout to `deallog` and the filename has to include `.mpirun=2.` for the number of MPI processes to use.

**Comment by bangerth** [comment]
@jpthiele @kinnewig FYI.

**Comment by bangerth** [comment]
@QY-Shi Would you mind combining the two commits into one? Only the combination leads to a correct result, it would be nice to only have one commit in the history.

**Review by masterleinad — APPROVED** [review]

**Comment by QY-Shi** [comment]
Now that all tests passed, I squashed into 1 commit.

**Comment by bangerth** [comment]
Outstanding, thank you for the patch!

**Pull request merged**
