### PR TITLE
Provide C++20-style operator| to filter iterator ranges.

### PR DESCRIPTION
**Pull request by bangerth**
In the same spirit as provided by the C++20 [range adaptors](https://en.cppreference.com/w/cpp/ranges) feature, this little function makes it possible to "filter" ranges over the active cells of Triangulation and DoFHandler objects.

This allows to replace:
```
  DoFHandler<dim> dof_handler;
  ...
  for (const auto &cell : dof_handler.active_cell_iterators())
    {
      if (cell->is_locally_owned())
        {
          fe_values.reinit (cell);
          ...do the local integration on 'cell'...;
        }
    }
```
by:
```
  DoFHandler<dim> dof_handler;
  ...
  const auto filtered_iterators_range =
    filter_iterators();
  for (const auto &cell :
          dof_handler.active_cell_iterators() | IteratorFilters::LocallyOwnedCell())
    {
      fe_values.reinit (cell);
      ...do the local integration on 'cell'...;
    }
```
Here, the `operator|` is to be interpreted in the same way as is done in the [range adaptors](https://en.cppreference.com/w/cpp/ranges) feature that is part of [C++20](https://en.wikipedia.org/wiki/C%2B%2B20). It has
the same meaning as the `|` symbol on the command line: It takes what is on its left as its inputs, and filters and transforms to produce some output. In the example above, it "filters" all of the active cell iterators and removes those that do not satisfy the predicate -- that is, it produces a range of iterators that only contains those cells that are both active and locally owned.

I've wanted to do this for a long time because the syntax of range adaptors (of which filters are a special case) is so elegant. It turns out that if one looks at what we already have, it was all there: We just had it in a free function `filter_iterators()`, rather than an `operator|()`.

The last commit here converts a few random places to see whether this all actually works :-)

/rebuild

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
Looks good to me!

**Comment by masterleinad** [comment]
You need to resolve some merge conflicts.

/rebuild

**Comment by bangerth** [comment]
Rebased. Let's see whether this works.

**Review by drwells — APPROVED** [review]

**Comment by bangerth** [comment]
Yay. I really like this syntax :-)

**Pull request merged**
