### PR TITLE
Inline a message text instead of going through contortions.

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Comment by drwells** [comment]
I don't think its a serious issue that we got rid of the `\n`s, but we can add them back in if someone minds.

**Comment by drwells** [comment]
I don't understand the control flow in this block: if the parameter file does not exist then we create one and then throw an exception that is not caught. Why?

Would it make more sense to just print this message to the console and then set up the parameter handler with default values?

**Comment by bangerth** [comment]
The exception is caught in `main()`. The `throw` is then essentially an `abort()`, except that we provide the location of where that happened in the error message.

I'm against running the code with defaults -- the error usually happens because you mistyped the name of the input file. If the program runs, it should run what you wanted to do or not at all. It shouldn't run a different set of parameters than you expected, in particular not if it runs for several hours :-)

**Comment by drwells** [comment]
Good point.

**Pull request merged**
