### PR TITLE
Fix a funny comment.

### PR DESCRIPTION
**Pull request by bangerth**
@tamiko pointed this out. The text was introduced in 6a7840fd733. I am glad that I did not author that commit :-)

### CODE REVIEW

**Comment by bangerth** [comment]
Or was it @drwells who pointed it out? I don't remember -- @drwells mentioned in on slack...

**Comment by drwells** [comment]
I thought the consensus here was to write
```cpp
          for (unsigned int i = 0; i < GeometryInfo<3>::vertices_per_cell; ++i)
            vertices_lex[GeometryInfo<3>::ucd_to_deal[i]] = cell.vertices[i];
          AssertThrow(GridTools::cell_measure<3>(all_vertices, vertices_lex) >
                        0,
                        0,
                      ExcMessage("the grid is seriously broken and should be sticked into the bin"));
```
:)

**Comment by bangerth** [comment]
@drwells: While funny, in practice no user will actually get the joke because they don't know the backstory. It is sad in some sense, but I think we ought to just fix all of these grammar problems -- though I suspect that the smiley at the end of your last comment implies that you agree :-)

For a similar case that's just plain aggravating to everyone else who is not inordinately proud of their own, 20 year old joke, see here: https://lwn.net/Articles/753646/

**Comment by drwells** [comment]
Yes; to be clear, I do not advocate actually changing the error message to say that!

**Pull request merged**
