### PR TITLE
Add tests for gmsh-4.3

### PR DESCRIPTION
**Pull request by masterleinad**
This test is the same as for `gmsh-4`. We read a `gmsh-2` file and save it in the `gmsh-4.1` format. Then we check that `deal.II` produces the same triangulation for both files.

### CODE REVIEW

**Comment by tamiko** [comment]
See #8276

**Comment by tamiko** [comment]
Depends on #8279

**Comment by drwells** [comment]
I think the test failure is spurious, but the failure message is hard to understand:
```
<1s

[WS-CLEANUP] Deleting project workspace...

[WS-CLEANUP] Deferred wipeout is used...

[WS-CLEANUP] done

[CTest-Version 3.x (default)] - No test report file(s) were found with the pattern '*.xml' relative to '/jenkins/workspace/dealii_PR-8269' for the testing framework 'CTest-Version 3.x (default)'.

Did you enter a pattern relative to (and within) the workspace directory?

Did you generate the result report(s) for 'CTest-Version 3.x (default)'?"
```

**Comment by masterleinad** [comment]
I rebased. Let's hope we have more luck this time.

**Comment by masterleinad** [comment]
Now it's
```
/jenkins/workspace/dealii_PR-8269/tests/mappings/mapping_fe_field_02.cc:76:1: fatal error: error writing to /tmp/cc5GUcvQ.s: No space left on device
```

**Pull request merged**
