### PR TITLE
Filter out --help from argv when initializing Kokkos

### LINKED ISSUE #15456: Passing `--help` to a deal.II application prints the kokkos help
As pointed out by @nfehn , a simple program like:

```cpp
#include <deal.II/base/mpi.h>

using namespace dealii;

int main(int argc, char *argv[])
{
  Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv, 1);
}
```

give the following output if run with `./main --help`:

```

--------------------------------------------------------------------------------
-------------Kokkos command line arguments--------------------------------------
--------------------------------------------------------------------------------
This program is using Kokkos.  You can use the following command line flags to
control its behavior:

Kokkos Core Options:
  --kokkos-help                  : print this message
  --kokkos-disable-warnings      : disable kokkos warning messages
  --kokkos-print-configuration   : print configuration
  --kokkos-tune-internals        : allow Kokkos to autotune policies and declare
                                   tuning features through the tuning system. If
                                   left off, Kokkos uses heuristics
  --kokkos-num-threads=INT       : specify total number of threads to use for
                                   parallel regions on the host.
  --kokkos-device-id=INT         : specify device id to be used by Kokkos.
  --kokkos-map-device-id-by=(random|mpi_rank)
                                 : strategy to select device-id automatically from
                                   available devices.
                                   - random:   choose a random device from available.
                                   - mpi_rank: choose device-id based on a round robin
                                               assignment of local MPI ranks.
                                               Works with OpenMPI, MVAPICH, SLURM, and
                                               derived implementations.

Kokkos Tools Options:
  --kokkos-tools-libs=STR        : Specify which of the tools to use. Must either
                                   be full path to library or name of library if the
                                   path is present in the runtime library search path
                                   (e.g. LD_LIBRARY_PATH)
  --kokkos-tools-help            : Query the (loaded) kokkos-tool for its command-line
                                   option support (which should then be passed via
                                   --kokkos-tools-args="...")
  --kokkos-tools-args=STR        : A single (quoted) string of options which will be
                                   whitespace delimited and passed to the loaded
                                   kokkos-tool as command-line arguments. E.g.
                                   `<EXE> --kokkos-tools-args="-c input.txt"` will
                                   pass `<EXE> -c input.txt` as argc/argv to tool

Except for --kokkos[-tools]-help, you can alternatively set the corresponding
environment variable of a flag (all letters in upper-case and underscores
instead of hyphens). For example, to disable warning messages, you can either
specify --kokkos-disable-warnings or set the KOKKOS_DISABLE_WARNINGS
environment variable to yes.

Join us on Slack, visit https://kokkosteam.slack.com
Report bugs to https://github.com/kokkos/kokkos/issues
--------------------------------------------------------------------------------
```

This is an unwanted behavior in user code if the output should be the help of the application (as in the case of `ExaDG`).

### PR DESCRIPTION
**Pull request by bangerth**
Fixes #15456. Alternative to #15464.

### CODE REVIEW

**Review by tamiko — APPROVED** [review]

**Comment by tamiko** [comment]
I prefer this version. I think there is little harm in passing `argc`, `argv` down to kokkos given the fact that kokkos has a separate `--kokkos-*` namespace for arguments. For example, the kokkos help message is still available via `--kokkos-help`.

**Review by drwells — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]

**Comment by tamiko** [comment]
I think we have sufficient consensus.

**Comment by kronbichler** [comment]
As expressed in #15456, I agree with this setting. I am not sure if it is the solution we will have long-term, but for now I think this addresses the most pressing issue.

**Comment by peterrum** [comment]
I also don't think this is the perfect solution. Working with additional datas as in the rest of the library would probably make more sense. At least `--help` works again :+1:  However, since `MPI_InitFinalize` is (still) not well documented, we can still changes this while keeping backwards compatibility.

**Pull request merged**
