### PR TITLE
Simplify some con/destructors by using =default.

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Comment by drwells** [comment]
LGTM 👍

**Comment by masterleinad** [comment]
I thought I (or `clang-tidy`) found all...

**Comment by drwells** [comment]
Yes, well, don't underestimate our own John Henry of C++ :)

**Comment by bangerth** [comment]
Ha, that's a funny reference. I didn't know about John Henry. I hope I don't die hammer in hand fixing things in our software. I do hope to die in some exciting  foreign land sipping a cup of good coffee and reading a book :-)

**Pull request merged**
