### PR TITLE
Identity constraints in h-adapted grids?

### PR DESCRIPTION
**Pull request by marcfehling**
I noticed the presence of identity constraints in h-adapted meshes using continuous Lagrange elements of even polynomial degree.

To my knowledge, these identities should have all been resolved in h-adapted meshes during `distribute_dofs` when only one finite element is present. Is this a bug?

@bangerth -- We talked about this today. I created a simple test case.

### CODE REVIEW

**Comment by marcfehling** [comment]
The line dof of the coarse cell is identity constrained to the vertex dof of the fine cells. This causes the identity constraints to appear only for the even polynomial degrees.

For the `FE_Q<2>(2)` scenario, it looks like this:



If this is intended behavior, then everything is fine and we have a new test :-)

**Comment by bangerth** [comment]
Yes, no bug. We know how to unify vertex-to-vertex dofs, and line-to-line dofs, but not vertex-to-line dofs. There is no infrastructure in the finite element interface to ask that question, and so we end up with constraints -- no different from a regular hanging node if you had Q1 elements on all cells.

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
Adding another test of this is perhaps not necessary, but it also doesn't hurt.

**Pull request merged**
