### PR TITLE
Detect CUDA compute capability

### PR DESCRIPTION
**Pull request by masterleinad**
It's easy to forget to set the compute capability when compiling with `CUDA`. In case platform introspection is allowed, this pull request adds autodetection for the compute capability by asking device 0.

### CODE REVIEW

**Comment by bangerth** [comment]
Your patch tries to elucidate HOST properties when what you want to know about is TARGET properties. Is this going to work when, for example, you're compiling on the front end of a cluster (which has no GPUs attached) for the nodes of the cluster (which DO have them attached)?

**Comment by masterleinad** [comment]
No, that will not work. That is the reason why we only try this if `DEAL_II_ALLOW_PLATFORM_INTROSPECTION=ON`. Also, manually setting the compute capability has precedence and we don't try to autodetect either.

**Comment by masterleinad** [comment]
Let me add that to the error message.

**Comment by Rombur** [comment]
Looks good but before we merge let me try it.

**Pull request merged**
