### PR TITLE
Let step-1 output SVG instead of EPS.

### PR DESCRIPTION
**Pull request by bangerth**
EPS is just an outdated format.

I've already put these pictures online, but they look like this:
step-1 grid-1-r9 2
step-1 grid-2r2

### CODE REVIEW

**Comment by bangerth** [comment]
Fail. The second picture should have been this one:
step-1 grid-2-r9 2

**Comment by tjhei** [comment]
While I agree that eps is a terrible format to output into by default, I am also not sure if the default settings for svg are very useful. Especially the cell index might be confusing?

**Comment by bangerth** [comment]
Would it be more useful if I defaulted the SVG writer to not output cell numbers?

**Comment by tjhei** [comment]
> Would it be more useful if I defaulted the SVG writer to not output cell numbers?

What is your opinion? We can also leave it like you proposed with the paragraph you wrote about the SVG settings.

**Comment by bangerth** [comment]
I would remove the cell numbers from the plot but leave the colors. In fact, I find the cell numbers not useful as a default.

There are currently two pending patches for the SVG writer. If you're willing to merge this, then I'll remove the cell number output in a follow-up patch that changes the default.

**Comment by bangerth** [comment]
Part of #5982.

**Comment by tjhei** [comment]
The documentation you wrote as part of this PR reference the "cell number" though. Do you still want this PR to be merged as is?

**Comment by bangerth** [comment]
Yes. Let's keep things in sync.

**Comment by peterrum** [comment]
@bangerth: I have the feeling that the figures here and in PR#8448 are too big. When I open the tutorials of developer version, I cannot see 10% on the right in my browser (100% zoom; 1920 x 1080 monitor) and have to scroll right. I think the sizes as shown here on github would be better...

**Comment by bangerth** [comment]
@peterrum -- good point. Is this better?

**Comment by krishnakumarg1984** [comment]
@bangerth 
This does not seem to be completely agreeable to me. For instance, it looks like the `write_svg` function (SVG writer) does not know how to print curved cells and can only display quadrilaterals.
See #9296.

For a newcomer to the library, this is off-putting when the visualization does not produce what you expect. In the case of a `hyper_ball` or `hyper_shell`, the user needs to see a curved outer boundary for sure.

**Pull request merged**
