### PR TITLE
Add FieldTransfer for the transfer of field with FE_Nothing

### PR DESCRIPTION
**Pull request by Rombur**
This PR is intended to start the discussion on how to transfer a solution when cells have been activated during mesh refinement, i.e., the finite element is changed from `FE_Nothing` to something else. Do not waste your time reviewing this PR, it is not complete. This is just to illustrate one possible solution. 

Why do we want to do this? Changing the finite element on a cell from `FE_Nothing` to `FE_Q` allows to simulate the addition of material during additive manufacturing. In this case, the object is built one layer at the time and new material is added on the top of the old one. This new material has a prescribed temperature. In practice, this means that we have a temperature vector that needs to be transfer after some kind of p-refinement (from `FE_Nothing` to `FE_Q(1)` for example). This is different than a regular p-refinement because the new dofs cannot get the value from a coarser element. There is also a unique problem with hanging nodes. Normally, the coarse cell is used to constrain the refined cells. However, if the activated cell is coarser than the current cell we don't want it to constrain the  refined cells. Multiple attempts have been made to try to fix this problem see https://github.com/dealii/dealii/pull/11132, https://github.com/dealii/dealii/pull/12380, https://github.com/dealii/dealii/issues/11533. This exact problem also came up on the mailing list a few times.

The problem of doing the transfer when there are no hanging nodes both in serial and in parallel have been explained [here](https://github.com/dealii/dealii/pull/11132). I have used the solution discussed in that PR. The way I treat hanging nodes is by inverting the usual constraint matrix in order for the refined cells to constrain the coarse cell. Because the matrix is rectangular, I used SVD to invert it but maybe a QR decomposition would be more appropriate.

There are three test cases in this PR:
 1. One cell is activated
 2. Multiple cells are activated and we use MPI
 3. Multiple cells with hanging nodes are activated

IIRC @marcfehling thought that changes in the way `SolutionTransfer` pack and unpack data would be a more elegant solution. I would like for us to agree on what's the best forward. Is the current PR the way to go or should we do something else?

### CODE REVIEW

**Comment by marcfehling** [comment]
Thank you for formulating your ideas in this PR!

I remember our discussion and need to find the notes I took back then. If I remember correctly, I was not fond of the idea to introduce another class that is essentially similar to `SolutionTransfer`, but does just one thing different.

In general, the `FENothing` object represents the space of `zero` functions. In case the FE is dominating or not, the transition of your solution on the interface with an `FENothing` will be continuous or not. I think the idea I had in general was to set the dof values on 'activated' cells to zero, respecting continuity constraints as described above depending on how you configured your `FENothing` object.

One of the features of the `SolutionTransfer` class is to do all the preparation and packing of data before refining the mesh, and only do the unpacking after the mesh refinement. My other additional idea I had (that you referred to) was to have a mechanism to prepare data on to-be-activated cells before refining the mesh. Something like: 1) check if current fe is fe_nothing; 2) call some callback function (or something else, something more elegant) to prepare data for the future FE on this cell; 3) pack this data and prepare transfer.

We would need to intervene here.
https://github.com/dealii/dealii/blob/edd3519258f121fa1b340b7bf49a5c14cdc5e02e/source/distributed/solution_transfer.cc#L329-L338
We could either add another callback function for the fe_nothing case at `dofs_per_cell == 0`, or (what I would prefer), move this whole set of instructions into a general free function that we pass as a function pointer to SolutionTransfer (similar to [`AdaptationStrategies`](https://www.dealii.org/developer/doxygen/deal.II/namespaceAdaptationStrategies.html) in [`CellDataTransfer`](https://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1distributed_1_1CellDataTransfer.html)). This way, users can do whatever they want in transferring their solutions if they have a corner case in mind.

In my opinion, the introduction of a new class is not necessary and would just yield more code to maintain. @Rombur Would the above idea cover all the cases you have in mind?

**Comment by marcfehling** [comment]
...and we also need to make sure that this works in the `serial` and `parallel::shared` cases as well...

**Comment by Rombur** [comment]
I think it covers all the cases but it will be a real pain to use when the cells don't have the same refinement level. I don't want the users to have to deal with https://github.com/dealii/dealii/issues/11533 themselves and I don't see how you can treat that case without knowledge of the `AffineConstraints`. https://github.com/dealii/dealii/issues/11533 is a special case where the dofs of the coarse and the refine cells match but in the general case they won't. So everybody will have to invert the `AffineConstraints` themselves which requires to understand how `AffineConstraints` works. We could provide that function ourselves but it doesn't really match how your callback works. Your callback function works at the cell level but I need to use constrained dofs that links dofs of different cells together.

**Comment by marcfehling** [comment]
> I think it covers all the cases but it will be a real pain to use when the cells don't have the same refinement level. I don't want the users to have to deal with #11533 themselves and I don't see how you can treat that case without knowledge of the `AffineConstraints`. #11533 is a special case where the dofs of the coarse and the refine cells match but in the general case they won't. So everybody will have to invert the `AffineConstraints` themselves which requires to understand how `AffineConstraints` works. We could provide that function ourselves but it doesn't really match how your callback works. Your callback function works at the cell level but I need to use constrained dofs that links dofs of different cells together.

With the `future_fe_index`, you know what kind of FE will be assigned to that particular cell. So you can prepare a buffer for this cell and its new FE accordingly, with the number of dofs of that particular new FE. You will not call `get_interpolated_dof_values` in the case of `FE_Nothing`, but need set the corresponding dofs on your own or by some external function.

You can check the values of neighboring cells and use them if you need a continuous solution. Things would get problematic if you decide to "activate" a chunk of `FE_Nothing` elements, though.

I think you could circumvent the issues with `AffineConstraints` and overwritten dof values as described in #11533, if you set the correctly interpolated values on the "activated" cell during the mechanism described above. To be honest, though, I don't know how to make that happen right now (maybe via [FiniteElement::get_face_interpolation_matrix](https://www.dealii.org/developer/doxygen/deal.II/classFiniteElement.html#a704fd4e8da3219ba0f71a17b5effdf55)). Or maybe I didn't get your point yet @Rombur :)

**Comment by Rombur** [comment]
> I think you could circumvent the issues with AffineConstraints and overwritten dof values as described in #11533, if you set the correctly interpolated values on the "activated" cell during the mechanism described above. 

What's been done in https://github.com/dealii/dealii/issues/11533 only works because they use `FE_Q(2)`. It won't work in the general case because the dofs of the coarse cell and the fine cells don't "match". So yes, we need to do something similar but it's a lot more difficult in the general case.

> To be honest, though, I don't know how to make that happen right now (maybe via FiniteElement::get_face_interpolation_matrix).

Right, that's the hard part. The information is stored in the `AffineConstraints` but in the wrong format. Normally we want to impose the value on the fine cells but if we activate the coarse cell, we need to impose the values on the coarse cell. This means inverting the relationships you have in `AffineConstraints`. There might a better way to get this information, maybe we should use `FiniteElement::get_face_interpolation_matrix()` instead of inverting a constraint matrix but this is complex enough that we cannot let users figure this out.

The cases were there are no hanging nodes or you activate a finer cell are pretty trivial. The only one that's difficult is when you activate a coarse cell due to the fact that `AffineConstraints::distribute()` will change the solution in an unexpected way.

**Comment by Rombur** [comment]
@marcfehling any progress on your side?

**Comment by Rombur** [comment]
@marcfehling What do you want to do here? I would like to have this capability in the next release, either using something similar to what's done in this PR or by another way. I think we just need to take a decision on how we are going to tackle this problem.

**Comment by Rombur** [comment]
@marcfehling @peterrum I have updated the PR and it is now in a decent state. Like we discussed before the release, I have put the class in the `experimental` namespace so that once @marcfehling has a better solution, we can remove this class. I am not sure if we want to advertise this class with a new log entry.

BTW, I am open to a better name for the class.

**Comment by Rombur** [comment]
@marcfehling @peterrum _ping_

**Review by marcfehling — APPROVED** [review]
I'm okay with merging as is in a dedicated namespace.

Not sure if the solution I had in mind will be better, and we can compare it to `FieldTransfer` once I find time working on it.

You might want to add the `p4est` flag to the names of all output files.

**Comment by Rombur** [comment]
> You might want to add the p4est flag to the names of all output files.

Done

**Comment by marcfehling** [comment]
```
3041/4557 Test #3048: hp/field_transfer_03.debug ............................................................***Failed    5.62 sec
/jenkins/workspace/dealii_PR-12759/tests/hp/field_transfer_03.cc: In function ‘int main(int, char**)’:
/jenkins/workspace/dealii_PR-12759/tests/hp/field_transfer_03.cc:44:71: error: use of deleted function ‘dealii::parallel::distributed::Triangulation<dim, spacedim>::Triangulation(const MPI_Comm&, typename dealii::Triangulation<dim, spacedim>::MeshSmoothing, dealii::parallel::distributed::Triangulation<dim, spacedim>::Settings) [with int dim = 2; int spacedim = 2; MPI_Comm = int; typename dealii::Triangulation<dim, spacedim>::MeshSmoothing = dealii::Triangulation<2, 2>::MeshSmoothing]’
   parallel::distributed::Triangulation<2> triangulation(MPI_COMM_WORLD);
                                                                       ^
In file included from /jenkins/workspace/dealii_PR-12759/include/deal.II/distributed/cell_data_transfer.h:23:0,
                 from /jenkins/workspace/dealii_PR-12759/include/deal.II/distributed/cell_data_transfer.templates.h:22,
                 from /jenkins/workspace/dealii_PR-12759/include/deal.II/distributed/field_transfer.h:21,
                 from /jenkins/workspace/dealii_PR-12759/tests/hp/field_transfer_03.cc:20:
/jenkins/workspace/dealii_PR-12759/include/deal.II/distributed/tria.h:1018:16: note: declared here
       explicit Triangulation(
                ^
make[3]: *** [CMakeFiles/hp.field_transfer_03.debug.dir/field_transfer_03.cc.o] Error 1
```

**Comment by Rombur** [comment]
Thanks should be fixed

**Comment by Rombur** [comment]
_ping_

**Review by marcfehling — APPROVED** [review]

**Pull request merged**
