### PR TITLE
Make dimension counters unsigned.

### PR DESCRIPTION
**Pull request by bangerth**
Prompted by #12947. The vast majority of these places already use `unsigned`.

/rebuild

### CODE REVIEW

**Comment by peterrum** [comment]
This is not that easy. In most places, `dim` is int.

**Comment by drwells** [comment]
I think we should keep these as `int` to avoid compiler warnings about tautological loops. I don't remember the precise warning but we have run into it when instantiating for `dim == 0` in the last year or so.

**Comment by tamiko** [comment]
The warning occurs with gcc-10 (ish) when you have a construct of the
form:

```
template<unsigned int dim>
void foo {
  for (unsigned int i = 0; ...) {
    if (i < dim) {
      // ...
    }    
  }
}
```

In this case gcc (used to) issue a warning when instantiating with
`dim == 0` that "i < 0" always equates to false. This seems to be fixed
gcc-11 onwards.

**Comment by tamiko** [comment]
The CI fails with:
```
source/grid/grid_tools_dof_handlers.cc:2300:15: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]

         if (i == direction)

               ^
```

**Comment by bangerth** [comment]
It seems to work with this version :-)

**Review by kronbichler — APPROVED** [review]
This is OK for me if this does not lead to the warnings on any of our supported platforms.

**Comment by bangerth** [comment]
The testers at least don't report anything. Want to give it a try by merging and seeing what happens on everyone's platforms?

**Comment by tamiko** [comment]
@bangerth I'll run the testsuite against it.

**Comment by tamiko** [comment]
@bangerth gcc 10 with `-std=cxx20` doesn't like the patchset: https://cdash.43-1.org/viewBuildError.php?type=1&buildid=7826

**Comment by tamiko** [comment]
@bangerth 
gcc 11 doesn't like the unsigned change either: https://cdash.43-1.org/viewBuildError.php?type=1&buildid=7837
clang is fine, older gcc versions are also fine.
My hope is that gcc 12 has gotten rid of this spurious warning.

**Comment by tjhei** [comment]
What is the advantage of making these counter ``unsigned``? I feel like it might not be worth the trouble.

**Comment by bangerth** [comment]
My goal is simply consistency:
```
>> egrep -r 'for \(unsigned int.*< (space)?dim' include/ source/ | wc -l
1867
>> egrep -r 'for \(int.*< (space)?dim' include/ source/ | wc -l
52
```

I'll take a look at the errors in the next couple of days.

**Comment by bangerth** [comment]
I've omitted those cases where we get comparisons of `unsigned < 0` and corresponding warnings.

**Review by tamiko — APPROVED** [review]
No more warnings on gcc-10 and gcc-11

**Comment by tamiko** [comment]
@tjhei *ping*

**Pull request merged**
