### PR TITLE
Turn off checking LAPACK API on Windows as it fails to fulfill its purpo...

### PR DESCRIPTION
**Pull request by l-korous**
...se.

### CODE REVIEW

**Comment by tamiko** [comment]
What is the userland you use (Compiler, and lapack libraries)?

**Comment by l-korous** [comment]
I use Visual Studio compiler and I use prebuilt lapack libs from http://icl.cs.utk.edu/lapack-for-windows/lapack/

**Comment by tamiko** [comment]
For the case that this patch is not applied, i.e. when the lapack check fails. Can you send <code>detailed.log</code> as well as <code>CMakeFiles/CMakeError.log</code> to the developer mailing list, please?

**Comment by bangerth** [comment]
Or attach it to the PR :-)

**Comment by bangerth** [comment]
Any news?

**Comment by l-korous** [comment]
I have the output (sorry for the delay). I see that it is linking of quadmath.lib which makes the compilation fail (and therefore mark the library as wrong).

lapackerror

- quadmath.lib is linked even though...  in my case here:
https://github.com/l-korous/dealii/blob/db825ed3431952481b3c738356c819bf3640075d/cmake/modules/FindLAPACK.cmake#L81
... it is not found, so it should not be used.

**Comment by tamiko** [comment]
Most likely the problem lies in <code>cmake/modules/FindLAPACK.cmake</code>:

```
SET(_fortran_libs ${CMAKE_Fortran_IMPLICIT_LINK_LIBRARIES})                      
SET_IF_EMPTY(_fortran_libs gfortran m quadmath c)                                
FOREACH(_lib ${_fortran_libs})                                                   
  FIND_SYSTEM_LIBRARY(${_lib}_LIBRARY NAMES ${_lib})                             
  LIST(APPEND _additional_libraries ${_lib}_LIBRARY)                             
ENDFOREACH()   
```

Try to temporarily remove quadmath from the list. I'll have a look into how to fix it properly.

**Comment by tamiko** [comment]
<code>DEAL_II_PACKAGE_HANDLE</code> filters out any variables with <code>...-NOTFOUND</code>. Consequently, the only possibility that <code>quadmath</code> shows up is that <code>FIND_SYSTEM_LIBRARY</code> returns an erroneous success. Which can be likely the case, because it depends on the compiler to bail out when invoked with <code>-l...</code>.

Does this happen with a standalone configuration for deal.II?

**Comment by l-korous** [comment]
Hi, yes, standalone.

**Comment by tamiko** [comment]
I suggest, we fix the quadmath check instead.

**Pull request closed without merging**
