### PR TITLE
Fix step-81 complex number warnings

### PR DESCRIPTION
**Pull request by zjiaqi2018**
Fix complex number warnings
Closes https://github.com/dealii/dealii/issues/13890

### CODE REVIEW

**Comment by peterrum** [comment]
@tamiko Do you agree?

**Review by kronbichler — APPROVED** [review]

**Comment by tjhei** [comment]
What is the warning message?

**Comment by bangerth** [comment]
@tjhei See https://github.com/dealii/dealii/issues/13890.

**Review by bangerth — APPROVED** [review]

**Comment by marcfehling** [comment]
clang-tidy asks you to use a braced initializer list:
```
/jenkins/workspace/dealii-tidy_PR-13892/examples/step-81/step-81.cc:321:16: error: avoid repeating the return type from the declaration; use a braced initializer list instead [modernize-return-braced-init-list,-warnings-as-errors]
```
Try something like `return {1.0, s};` instead of `return std::complex<double>(1.0, s);`

**Review by masterleinad — APPROVED** [review]

**Review by tjhei — APPROVED** [review]

**Pull request merged**
