### PR TITLE
Add reinit_faces() for Quadrature<dim>

### PR DESCRIPTION
**Pull request by jh66637**
@bergbauer @peterrum I have use cases in which I want to use `NonMatching::MappingInfo` and I already know the quadratures on faces in dimension `dim`, i.e. `Quadradure<dim>`. Internally, `reinit_faces(Quadradure<dim-1>)` converts the quadratures to `Quadradure<dim>`. 

With this PR it is possible to avoid the conversion of `Quadradure<dim>` to `Quadradure<dim-1>`, just to be able to use `reinit_faces()` which internally performs the reverse operation. 

I will add a test and undraft the PR once I recompiled `deal.II`.

@bergbauer FYI: I would like to apply similar changes for the new overload in `FEFacePointEval` once it is merged.

### CODE REVIEW

**Comment by peterrum** [comment]
How is this in conflict with https://github.com/dealii/dealii/pull/16359?

**Comment by bergbauer** [comment]
I intend to remove the projection to a `Quadradure<dim>` once #16359 is merged, and only use the <dim-1> data. https://github.com/bergbauer/dealii/blob/d002a6010323246962fe6b2ec15c10f790facc80/include/deal.II/matrix_free/fe_point_evaluation.h#L1390-L1392

Loading `Point<dim-1>` is more memory efficient than `Point<dim>`.

**Comment by jh66637** [comment]
There might be merge conflicts but there should be no other conflicts. https://github.com/dealii/dealii/pull/16359 adds a new `reinit_faces()` method and leaves the old `reinit_faces()` method untouched. The new method has `std::vector<Quadrature<dim-1>>` instead of `std::vector<std::vector<Quadrature<dim-1>>`. It also converts from `Quadrature<dim-1>` to `Quadrature<dim>` and I would like to add a similar overload once it is merged. 

https://github.com/dealii/dealii/pull/16359 is more important and should be merged first.

**Comment by jh66637** [comment]
> I intend to remove the projection to a `Quadradure<dim>` once #16359 is merged, and only use the `Quadrature<dim-1> `data. https://github.com/bergbauer/dealii/blob/d002a6010323246962fe6b2ec15c10f790facc80/include/deal.II/matrix_free/fe_point_evaluation.h#L1390-L1392
> 
> Loading `Point<dim-1>` is more memory efficient than `Point<dim>`.

@bergbauer OK, so you would keep the methods as they are and convert to `Quadrature<dim-1>` before `reinit_faces()` which will be OK because there will be no transformation to `Quadrature<dim>` anymore inside the function?

What do you think about doing it the other way, i.e have `reinit_faces(Quadrature<dim>)` and convert to `Quadrature<dim-1>' before calling `reinit_faces(Quadrature<dim-1>)' ?

**Comment by bergbauer** [comment]
> OK, so you would keep the methods as they are and convert to Quadrature<dim-1> before reinit_faces() which will be OK because there will be no transformation to Quadrature<dim> anymore inside the function?

Correct.

`reinit_faces(Quadrature<dim>)` feels unnatural to me, because who ensures that the quadrature points all lie inside a face? How do you convert it to a `Quadrature<dim-1>` and where do you get a `Quadrature<dim>` from for a face? CGAL?

**Comment by jh66637** [comment]
Yes, CGAL gives intersections in a list of `Point<dim>`, since the intersection is not directly related to a cell this can not be changed. `QGaussSimplex::mapped_quadrature()` takes the list of points and converts them to a `Quadrature<dim>`. 

https://github.com/dealii/dealii/pull/16299/files#diff-6aa609a8649d3a50906faf50bbfe0dbbfe68b6ea07585ceb9554851648f41b2dR1711-R1727

**Comment by bergbauer** [comment]
And you want to use [transform_real_to_unit_cell](https://dealii.org/developer/doxygen/deal.II/classMapping.html#a38ba6aaa1745359910e1b465a0f5fb27) instead of [project_real_point_to_unit_point_on_face](https://dealii.org/developer/doxygen/deal.II/classMapping.html#aca0e49bd04f5f52ad9a481367706c985)? You need the points in reference space anyway. In my opinion, it is safer to pass a `Quadrature<dim-1>` to `NonMatching::MappingInfo` for a face.

**Comment by jh66637** [comment]
From the code snippet you are right. I am planning to fetch the points differently. The main reason for the PR is to avoid the 'QProjector' operation but since you are planning to optimize this anyway I can live with the interface as it is and convert the quadratures manually :)

**Pull request closed without merging**
