### PR TITLE
Disabled a few extra diagnostic warnings for external packages

### PR DESCRIPTION
**Pull request by jppelteret**
- `-Wignored-qualifiers`
- `-Woverflow`
- `-Wpedantic`

### CODE REVIEW

**Comment by masterleinad** [comment]
Why do you do that? Who are the offenders?

**Comment by jppelteret** [comment]
Currently there are none, but `Adol-C` will kick up a few errors when we include some of their headers. I've added an extra label to indicate this :-)

**Comment by jppelteret** [comment]
Relates #4958

**Comment by drwells** [comment]
@jppelteret it looks like #4967 is incompatible with this.

**Comment by jppelteret** [comment]
@drwells Fixed, thanks!

**Pull request merged**
