### PR TITLE
Use clang-tidy's modernize-deprecated-headers

### PR DESCRIPTION
**Pull request by masterleinad**
Clean up the `run_clang_tidy.sh`a bit and at the 'modernize-deprecated-headers` check. Related to #5938.

### CODE REVIEW

**Comment by tamiko** [comment]
@masterleinad At some point I have to ask you whether all of these clang-tidy changes don't get a bit obsessive? :stuck_out_tongue_winking_eye:

**Comment by masterleinad** [comment]
We can always discuss if this is to restrictive or not. In general, I am in favor of at least evaluating the checks.

**Comment by masterleinad** [comment]
In the end, this file is not for requiring these checks to pass but to automatically get improvement suggestions.

**Pull request merged**
