### PR TITLE
Update output of bits/cone_03

### PR DESCRIPTION
**Pull request by masterleinad**
As [CDash](https://cdash.kyomu.43-1.org/testSummary.php?project=1&name=bits%2Fcone_03.debug&date=2018-01-07) shows, #5684 also changed output for this test which uses a `FlatManifold` object in the 2D case starting from #5697.

### CODE REVIEW

**Comment by bangerth** [comment]
Is the new output expected? It's qualitatively different than the previous output.

**Comment by masterleinad** [comment]
> Is the new output expected? It's qualitatively different than the previous output.

Yes, it is. We don't require the output of `get_normals_at_vertices` to be normalized and the scaling is the only difference.

**Comment by bangerth** [comment]
Thanks for the confirmation!

**Pull request merged**
