### PR TITLE
MGTwoLevelTransfer: Clean old vector content in prolongate_add

### PR DESCRIPTION
**Pull request by kronbichler**
This fixes a bug observed by @nfehn in https://github.com/exadg/exadg/issues/453, where old content of a temporary vector would spoil the result. The reason is that we had a separate logic for DG elements that could set vector elements (rather than add-into) at some point, and forgot to clean that up. Our standard tests would not pick this up because we only check the transfer once, whereas it should run twice to expose this bug.

I could observe the bug in the test, returning vectors with entry `2` rather than `1` in some of the outputs, so this is a sensitive test for the bug I'm fixing.

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

**Comment by kronbichler** [comment]
You mean to use `VectorSetter` for the case `!inplace`, right? Because we do `prolongate_add`, so we need to do the other function.

Regarding clearing the vectors, I would prefer to minimize the work, which means clearing the vectors before use, rather than after. Another reason is that clearing before use is more stable if we start using the vectors in different functions and forget resetting them. The main goal should be to avoid using the temporary vectors and directly work with the `dst` vector of `prolongate_add`. We can't do that for all cases, though, so we need the other path.

**Comment by peterrum** [comment]
> !inplace, right?

Right. Let me know if I should implement that. After the recent refactoring, the information is not directly available anymore.

**Review by peterrum — APPROVED** [review]

**Comment by peterrum** [comment]
@kronbichler I have fixed the failing test. Now CI should pass and we can merge.

**Comment by kronbichler** [comment]
Thank you!

**Comment by kronbichler** [comment]
I am confused why the PR is still shown as open, while https://github.com/dealii/dealii/commits/master shows that it has been merged. Any ideas? I guess we can simply close this one?

**Pull request merged**
