### PR TITLE
Fix expansion for Adol-C numbers

### LINKED ISSUE #5420: AD number types broke compilation
looks like https://github.com/dealii/dealii/pull/5382 broke testers https://cdash.kyomu.43-1.org/viewBuildError.php?buildid=12975

Probably some number types are being expanded regardless of Sacado being around. 

@jppelteret can you please have a look?

### PR DESCRIPTION
**Pull request by jppelteret**
Fixes #5420

### CODE REVIEW

**Comment by jppelteret** [comment]
@davydden Since you can reproduce the issue, would you mind please testing this patch?

**Comment by jppelteret** [comment]
Thanks a lot for the quick feedback.

**Comment by tamiko** [comment]
Thanks!

**Comment by tamiko** [comment]
Unfortunately, this did not fix it. http://cdash.kyomu.43-1.org/viewBuildError.php?buildid=12981

**Comment by jppelteret** [comment]
Oh, I see that this is [missing the header to the product types](https://github.com/dealii/dealii/blob/master/source/fe/fe_values.cc#L43). Sorry I missed this. I'll fix this now.

**Pull request merged**
