### PR TITLE
Boost: Disallow version 1.77 due to multiple unresolved upstream bugs

### PR DESCRIPTION
**Pull request by tamiko**
Closes: https://github.com/dealii/dealii/issues/12817

### CODE REVIEW

**Comment by tamiko** [comment]
Quoting @drwells : <i>FWIW - there are so many problems with this boost release that Arch Linux is skipping it. We might want to add it to the list of unsupported boost versions and hope things are fixed in 1.78.</i>

I have now tried for the better part of the morning to make our bounding box implementation compile with boost 1.77. It is quite frustrating...

**Review by drwells — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]

**Review by tjhei — APPROVED** [review]
Good idea! 👍

**Comment by marcfehling** [comment]
> Indeed, I don't have access to the developer discussion, but you can see here
> 
> https://archlinux.org/packages/extra/x86_64/boost/
> 
> that it was flagged out-of-date in August and has not yet been updated.

`boost` has just been updated to 1.78.0 for `archlinux`

**Comment by drwells** [comment]
Oh my. I will try that out this week!

**Comment by drwells** [comment]
Unsurprisingly things don't work for nontrivial reasons. Lets continue the work in #13037,

**Pull request merged**
