### PR TITLE
Add GridGenerator::cylinder/subdivided_cylinder/truncated_cone to the python wrappers

### PR DESCRIPTION
**Pull request by Rombur**
Add three more `GridGenerator` functions to the python wrappers.

### CODE REVIEW

**Review by bangerth — APPROVED** [review]
Do we have Python tests that could check all of this? If not, we should probably come up with a plan that makes sure that this actually works. I also don't quite know how we document which functions one can call from Python...

**Review by kronbichler — APPROVED** [review]

**Comment by Rombur** [comment]
> Do we have Python tests that could check all of this? 

We do have tests. I run them regularly by hand. I still need to add them to my nightly.

> I also don't quite know how we document which functions one can call from Python...

Right now, the only way is to call something like `help(dealii.Triangulation)` in a notebook. It might be useful to create a `python` module in doxygen. I'll look into it.

**Comment by bangerth** [comment]
@Rombur Yes, I think both making sure we run the Python tests as part of the regular test suite and having documentation would be great!

**Comment by bangerth** [comment]
See also #19509.

**Pull request merged**
