### PR TITLE
Fix ExtrapolateImplementation for arbitrary VectorTypes

### LINKED ISSUE #3199: Compilation error with PETSCSCALAR=std::complex
Something between merge b18df5d and d356c5d broke the petsc-scalar complex build [1]. But I am at a loss to find it.

[1] http://cdash.kyomu.43-1.org/viewBuildError.php?buildid=1702

### PR DESCRIPTION
**Pull request by masterleinad**
This fixes #3199

### CODE REVIEW

**Comment by tamiko** [comment]
@masterleinad You have renamed a related test to `petsc_with_complex=false`.
Does it make sense to also provide a `petsc_with_complex=true` variant (probably a separate test)?
Just to document currently expected output.

**Comment by masterleinad** [comment]
@tamiko I decided to skip the case `petsc_with_complex=true` as the test uses `VectorTools::integrate_difference` that does not seem to be implemented for `std::complex`.

**Comment by drwells** [comment]
This does not compile under clang on my laptop (or the tester) so I removed the 'ready to merge' label.

**Comment by drwells** [comment]
For what it is worth, here is what I get when I try to compile:

```
-*- mode: compilation; default-directory: "~/Documents/Code/CPP/dealii-dev-clang/build/" -*-
Compilation started at Wed Oct  5 13:23:06

make -j1 obj_fe.debug
[ 10%] Built target expand_instantiations_exe
[ 50%] Built target obj_fe.inst
[ 60%] Building CXX object source/fe/CMakeFiles/obj_fe.debug.dir/fe_tools_extrapolate.cc.o
In file included from /home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:17:
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:890:7: error: too few template parameters in template redeclaration
      template <int,int> friend class dealii::FETools::internal::ExtrapolateImplementation;
      ^~~~~~~~~~~~~~~~~~
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1599:9: note: in instantiation of template class 'dealii::parallel::distributed::Triangulation<2, 2>' requested here
    if (dynamic_cast<const parallel::distributed::Triangulation<dim,spacedim>*>(&dof2.get_tria()) != 0)
        ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/build/source/fe/fe_tools_extrapolate.inst:1315:7: note: in instantiation of function template specialization 'dealii::FETools::extrapolate<2,
      dealii::Vector<double>, dealii::Vector<double>, 2>' requested here
 void extrapolate< 2 >
      ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:65:5: note: previous template declaration is here
    template <int dim,int spacedim,class OutVector>
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:17:
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:890:7: error: too few template parameters in template redeclaration
      template <int,int> friend class dealii::FETools::internal::ExtrapolateImplementation;
      ^~~~~~~~~~~~~~~~~~
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1599:9: note: in instantiation of template class 'dealii::parallel::distributed::Triangulation<3, 3>' requested here
    if (dynamic_cast<const parallel::distributed::Triangulation<dim,spacedim>*>(&dof2.get_tria()) != 0)
        ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/build/source/fe/fe_tools_extrapolate.inst:2611:7: note: in instantiation of function template specialization 'dealii::FETools::extrapolate<3,
      dealii::Vector<double>, dealii::Vector<double>, 3>' requested here
 void extrapolate< 3 >
      ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:65:5: note: previous template declaration is here
    template <int dim,int spacedim,class OutVector>
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1359:72: error: 'parallel_forest' is a private member of 'dealii::parallel::distributed::Triangulation<2, 2>'
            if (dealii::internal::p4est::tree_exists_locally<dim> (tr->parallel_forest,
                                                                       ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1608:24: note: in instantiation of function template specialization 'dealii::FETools::internal::ExtrapolateImplementation<2, 2,
      dealii::Vector<double> >::extrapolate_parallel<dealii::Vector<double> >' requested here
        implementation.extrapolate_parallel (u3_relevant, dof2, u2);
                       ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:735:61: note: declared private here
      typename dealii::internal::p4est::types<dim>::forest *parallel_forest;
                                                            ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1360:72: error: 'coarse_cell_to_p4est_tree_permutation' is a private member of
      'dealii::parallel::distributed::Triangulation<2, 2>'
                                                                   tr->coarse_cell_to_p4est_tree_permutation[cell->index()])
                                                                       ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:801:44: note: declared private here
      std::vector<types::global_dof_index> coarse_cell_to_p4est_tree_permutation;
                                           ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1365:49: error: 'coarse_cell_to_p4est_tree_permutation' is a private member of
      'dealii::parallel::distributed::Triangulation<2, 2>'
            const unsigned int tree_index = tr->coarse_cell_to_p4est_tree_permutation[cell->index()];
                                                ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:801:44: note: declared private here
      std::vector<types::global_dof_index> coarse_cell_to_p4est_tree_permutation;
                                           ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1366:76: error: 'init_tree' is a private member of 'dealii::parallel::distributed::Triangulation<2, 2>'
            typename dealii::internal::p4est::types<dim>::tree *tree = tr->init_tree(cell->index());
                                                                           ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:809:7: note: declared private here
      init_tree(const int dealii_coarse_cell_index) const;
      ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1370:42: error: 'parallel_forest' is a private member of 'dealii::parallel::distributed::Triangulation<2, 2>'
            const WorkPackage data (*tr->parallel_forest, *tree,tree_index,cell,p4est_coarse_cell);
                                         ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:735:61: note: declared private here
      typename dealii::internal::p4est::types<dim>::forest *parallel_forest;
                                                            ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:752:70: error: 'parallel_forest' is a private member of 'dealii::parallel::distributed::Triangulation<2, 2>'
          if (dealii::internal::p4est::tree_exists_locally<dim> (tr->parallel_forest,
                                                                     ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1216:7: note: in instantiation of member function 'dealii::FETools::internal::ExtrapolateImplementation<2, 2,
      dealii::Vector<double> >::compute_needs' requested here
      compute_needs (dof2, cells_we_need);
      ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1311:7: note: in instantiation of function template specialization 'dealii::FETools::internal::ExtrapolateImplementation<2, 2,
      dealii::Vector<double> >::compute_all_non_local_data<dealii::Vector<double> >' requested here
      compute_all_non_local_data (dof2, u2_relevant);
      ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1608:24: note: in instantiation of function template specialization 'dealii::FETools::internal::ExtrapolateImplementation<2, 2,
      dealii::Vector<double> >::extrapolate_parallel<dealii::Vector<double> >' requested here
        implementation.extrapolate_parallel (u3_relevant, dof2, u2);
                       ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:735:61: note: declared private here
      typename dealii::internal::p4est::types<dim>::forest *parallel_forest;
                                                            ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:753:70: error: 'coarse_cell_to_p4est_tree_permutation' is a private member of
      'dealii::parallel::distributed::Triangulation<2, 2>'
                                                                 tr->coarse_cell_to_p4est_tree_permutation[cell->index()])
                                                                     ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:801:44: note: declared private here
      std::vector<types::global_dof_index> coarse_cell_to_p4est_tree_permutation;
                                           ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:758:47: error: 'coarse_cell_to_p4est_tree_permutation' is a private member of
      'dealii::parallel::distributed::Triangulation<2, 2>'
          const unsigned int tree_index = tr->coarse_cell_to_p4est_tree_permutation[cell->index()];
                                              ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:801:44: note: declared private here
      std::vector<types::global_dof_index> coarse_cell_to_p4est_tree_permutation;
                                           ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:759:74: error: 'init_tree' is a private member of 'dealii::parallel::distributed::Triangulation<2, 2>'
          typename dealii::internal::p4est::types<dim>::tree *tree = tr->init_tree(cell->index());
                                                                         ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:809:7: note: declared private here
      init_tree(const int dealii_coarse_cell_index) const;
      ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:776:43: error: 'parallel_forest' is a private member of 'dealii::parallel::distributed::Triangulation<2, 2>'
          traverse_tree_recursively (*tr->parallel_forest,
                                          ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:735:61: note: declared private here
      typename dealii::internal::p4est::types<dim>::forest *parallel_forest;
                                                            ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:951:47: error: 'coarse_cell_to_p4est_tree_permutation' is a private member of
      'dealii::parallel::distributed::Triangulation<2, 2>'
          const unsigned int tree_index = tr->coarse_cell_to_p4est_tree_permutation[cell->index()];
                                              ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1239:11: note: in instantiation of function template specialization 'dealii::FETools::internal::ExtrapolateImplementation<2, 2,
      dealii::Vector<double> >::compute_cells<dealii::Vector<double> >' requested here
          compute_cells (dof2, u, cells_to_compute, computed_cells, new_needs);
          ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1311:7: note: in instantiation of function template specialization 'dealii::FETools::internal::ExtrapolateImplementation<2, 2,
      dealii::Vector<double> >::compute_all_non_local_data<dealii::Vector<double> >' requested here
      compute_all_non_local_data (dof2, u2_relevant);
      ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1608:24: note: in instantiation of function template specialization 'dealii::FETools::internal::ExtrapolateImplementation<2, 2,
      dealii::Vector<double> >::extrapolate_parallel<dealii::Vector<double> >' requested here
        implementation.extrapolate_parallel (u3_relevant, dof2, u2);
                       ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:801:44: note: declared private here
      std::vector<types::global_dof_index> coarse_cell_to_p4est_tree_permutation;
                                           ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:955:71: error: 'parallel_forest' is a private member of 'dealii::parallel::distributed::Triangulation<2, 2>'
              (dealii::internal::p4est::tree_exists_locally<dim> (tr->parallel_forest,
                                                                      ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:735:61: note: declared private here
      typename dealii::internal::p4est::types<dim>::forest *parallel_forest;
                                                            ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:961:74: error: 'init_tree' is a private member of 'dealii::parallel::distributed::Triangulation<2, 2>'
          typename dealii::internal::p4est::types<dim>::tree *tree = tr->init_tree(cell->index());
                                                                         ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:809:7: note: declared private here
      init_tree(const int dealii_coarse_cell_index) const;
      ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:965:51: error: 'parallel_forest' is a private member of 'dealii::parallel::distributed::Triangulation<2, 2>'
          compute_cells_in_tree_recursively (*tr->parallel_forest,
                                                  ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:735:61: note: declared private here
      typename dealii::internal::p4est::types<dim>::forest *parallel_forest;
                                                            ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1359:72: error: 'parallel_forest' is a private member of 'dealii::parallel::distributed::Triangulation<2, 2>'
            if (dealii::internal::p4est::tree_exists_locally<dim> (tr->parallel_forest,
                                                                       ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1608:24: note: in instantiation of function template specialization 'dealii::FETools::internal::ExtrapolateImplementation<2, 2,
      dealii::Vector<float> >::extrapolate_parallel<dealii::Vector<float> >' requested here
        implementation.extrapolate_parallel (u3_relevant, dof2, u2);
                       ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:735:61: note: declared private here
      typename dealii::internal::p4est::types<dim>::forest *parallel_forest;
                                                            ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1360:72: error: 'coarse_cell_to_p4est_tree_permutation' is a private member of
      'dealii::parallel::distributed::Triangulation<2, 2>'
                                                                   tr->coarse_cell_to_p4est_tree_permutation[cell->index()])
                                                                       ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:801:44: note: declared private here
      std::vector<types::global_dof_index> coarse_cell_to_p4est_tree_permutation;
                                           ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/source/fe/fe_tools_extrapolate.cc:1365:49: error: 'coarse_cell_to_p4est_tree_permutation' is a private member of
      'dealii::parallel::distributed::Triangulation<2, 2>'
            const unsigned int tree_index = tr->coarse_cell_to_p4est_tree_permutation[cell->index()];
                                                ^
/home/drwells/Documents/Code/CPP/dealii-dev-clang/include/deal.II/distributed/tria.h:801:44: note: declared private here
      std::vector<types::global_dof_index> coarse_cell_to_p4est_tree_permutation;
                                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[3]: *** [source/fe/CMakeFiles/obj_fe.debug.dir/build.make:831: source/fe/CMakeFiles/obj_fe.debug.dir/fe_tools_extrapolate.cc.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:3183: source/fe/CMakeFiles/obj_fe.debug.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3195: source/fe/CMakeFiles/obj_fe.debug.dir/rule] Error 2
make: *** [Makefile:1228: obj_fe.debug] Error 2

Compilation exited abnormally with code 2 at Wed Oct  5 13:23:14
```

**Comment by masterleinad** [comment]
@drwells This should now be fine. Strange that my compiler just accepted this before.

**Comment by bangerth** [comment]
Let's merge this and see whether it makes progress. If it breaks with one compiler or another, we can always fix this up, but it looks correct to me.

**Pull request merged**
