### PR TITLE
Implemented Praveen fix.

### PR DESCRIPTION
**Pull request by luca-heltai**
This closes partly #3144, by using a simpler implementation for the spherical Manifold that directly overloads `get_new_point` instead of using pair-wise simplification. 

This seems to effect convergence of simple tests on SphericalManifold, and even if the Jacobian is not exact, results are much better than in the previous implementation.

There seems to be still a bug in the overall design of the Manifold concept that prevents three dimensional problems to converge to machine precision when inner cells are curved, but I could not find a solution so far.

### CODE REVIEW

**Comment by tjhei** [comment]
> /run_tests?

it is "/run-tests" and not necessary here, because all your PRs will be tested automatically.

**Comment by bangerth** [comment]
I think this is progress, but are you saying that the patch really *should* not have any effect, but does? In other words, that the implementation in the base class plus the `project_to_manifold` function should have done the exact same thing as the new implementation is now doing?

**Comment by bangerth** [comment]
(I'm asking this because if this were true, this opens a door towards really finding what is going on -- because you now have two implementations of the same functionality that one can compare.)

**Comment by luca-heltai** [comment]
Unfortunately, the functionality is not the same. Technically speaking, here we use an ortographic projection (take the average on the bilinear plane, then project the point on the sphere). The original implementation took pairwise geodesics starting from points with smaller weights. 

This implementation is invariant w.r.t. to collections of points with the same weights,  while the other was not (one of the tests I corrected shows this behaviour: take three points with 1/3 weight and the result now does not change if you change the order of the points). I do not expect the same result, but I see no reasons why the other implementation should have a plateau in the convergence... 

Somehow I think this is deeper than I foresaw, and I'm struggling in understanding what is going on...

**Comment by luca-heltai** [comment]
I think the normals have some problems now. Please wait before merging.

**Comment by luca-heltai** [comment]
The normal bug was a "false positive". We do not use the Manifold when computing normals with MappingQ and MappingQGeneric, and therefore two normals from two adjacent cells should not be the same...

**Pull request merged**
