### PR TITLE
Link in step-70 pictures and videos.

### PR DESCRIPTION
**Pull request by bangerth**
Addresses the broken links mentioned in #10243 at least for the 2d case. I think that the video is actually a better visualization than the still images in https://gist.github.com/blaisb/a211c601067bb853a23c5beae3af0d9c The youtube video also has more features than embedding an animated gif, so I didn't take that one.

What's still missing are the 3d results, though.

### CODE REVIEW

**Comment by luca-heltai** [comment]
https://youtu.be/Srwq7zyR9mg

**Comment by luca-heltai** [comment]
Ps: if you want to play with the 3d results, here you'll find (as soon as they finish uploading), the vtu files I used to generate the movie above. 

https://gist.github.com/luca-heltai/b459c57000a70c4b8e7c0e72bba5ca07

**Comment by blaisb** [comment]
> Addresses the broken links mentioned in #10243 at least for the 2d case. I think that the video is actually a better visualization than the still images in https://gist.github.com/blaisb/a211c601067bb853a23c5beae3af0d9c The youtube video also has more features than embedding an animated gif, so I didn't take that one.
> 
> What's still missing are the 3d results, though.

Great, love the youtube animation :)!

**Comment by bangerth** [comment]
I also linked in the 3d video. Thanks!

**Comment by bangerth** [comment]
@luca-heltai -- I've played a bit with the 3d files and there is something funny going on with them. The velocity of the fluid drastically changes from one time step to the next and seems to oscillate somehow between about 200 and 1100 as max. Is this expected? I would have assumed that from one time step to the next, the velocity remains roughly the same....

**Comment by luca-heltai** [comment]
> @luca-heltai -- I've played a bit with the 3d files and there is something funny going on with them. The velocity of the fluid drastically changes from one time step to the next and seems to oscillate somehow between about 200 and 1100 as max. Is this expected? I would have assumed that from one time step to the next, the velocity remains roughly the same....

It is usually expected that with high penalty parameters, the L infty norm of the velocity may vary a lot according to where the solid points end up being in the fluid. The L2 norm is still under control, but you get spikes in the velocity here and there.

This happens especially when there are too many quadrature points for the solid part w.r.t. to the fluid part (i.e., when the fluid is not resolved enough). The simulation was admittedly a small one, just to get some quick results out also in the 3d case. Refining the fluid a couple of times more sould fix the issue.

**Comment by bangerth** [comment]
@luca-heltai But it isn't just the L-infinity norm. Have you looked at the velocity field? It *globally* oscillates in magnitude. The *pattern* stays the same from time step to time step, but the magnitude changes drastically.

**Pull request merged**
