### PR TITLE
Make mapping in GridTools::distributed_compute_point_locations() unique

### LINKED ISSUE #12496: Problem in insert_global_particles
There is a problem in insert_global_particles used in Lethe-DEM.
An extra particle is inserted at the center or corner of the triangulation (box). This is new and it did not happen using previous versions of deal.II.
So, I tried to find the commit after which this problem appears:
https://github.com/dealii/dealii/commit/870f097bc9ce582dd0a9e738990567256fc228d7
As insert_global_particles has three input arguments (insertion_position, global_bounding_boxes, and particle_properties), I checked these arguments and I believe the problem originates from a change in the mentioned commit in global_bounding_boxes.
@blaisb @gassmoeller @peterrum @kronbichler I would appreciate it if you could help with this issue

### PR DESCRIPTION
**Pull request by peterrum**
... and simplify the whole code according to https://github.com/dealii/dealii/pull/12199#issuecomment-841395884.

closes #12496

FYI @blaisb @shahabgol May I ask you to test this in your test case. Thx!

### CODE REVIEW

**Comment by blaisb** [comment]
@peterrum Perfect, I confirm that this fixes #12496

**Review by drwells — APPROVED** [review]
Looks reasonable - if @blaisb is happy then lets merge.

**Comment by shahabgol** [comment]
> ... and simplify the whole code according to [#12199 (comment)](https://github.com/dealii/dealii/pull/12199#issuecomment-841395884).
> 
> closes #12496
> 
> FYI @blaisb @shahabgol May I ask you to test this in your test case. Thx!

Thanks, @peterrum. The problem is fixed now.

**Pull request merged**
