### PR TITLE
WorkStream cleanups

### PR DESCRIPTION
**Pull request by bangerth**
This is the promised follow-up to #13031. The changes are probably easiest to review by looking at each commit separately, along with the commit message.

/rebuild

### CODE REVIEW

**Comment by tamiko** [comment]
@bangerth Man, you're too fast. See #13039 13039

**Comment by tamiko** [comment]
Rerunning the testsuite on this one.

**Review by tamiko — APPROVED** [review]

**Comment by marcfehling** [comment]
Looks like the docker image builds now! (at least its past its dropout from https://github.com/dealii/dealii/pull/13031#issuecomment-986359653)
https://github.com/dealii/dealii/runs/4436632802

**Comment by bangerth** [comment]
Good news. 

I like the new TBB interface substantially better than the old one. This one actually looks intuitive to me, and the code is substantially cleaner now!

**Pull request merged**
