### PR TITLE
Restrict mpi/petsc_step-27

### PR DESCRIPTION
**Pull request by masterleinad**
This test requires Hypre.

### CODE REVIEW

**Comment by drwells** [comment]
It looks like `trilinos_step-27.cc` and `interpolate_to_different_mesh_02.cc` (which also uses trilinos) in the same directory might suffer from the same problem. Could you fix those too while we are there?

**Comment by masterleinad** [comment]
@drwells The test you are mentioning are using `TrilinosWrappers::PreconditionAMG` which is based on `ML` and that is a required module.

**Comment by drwells** [comment]
Ah: nevermind!

**Pull request merged**
