### PR TITLE
Bugfix: Also compile the expand_instantiations macro with our build flags

### LINKED ISSUE #1792: Control compiler flags with which we build our build tools
The Windows build results posted by Krzysztof in recent days consistently show errors that something was not compiled with `/EHsc`. This confused me at first because we do add this flag. But what I think it really is is that we don't build the `expand_instantiations` script with this flag. I believe that the error message actually happens as a run-time error in this program, rather than as a compiler error while building something else. Indeed, our regular object files are compiled with flags such as this:
```
/usr/bin/c++   -DDEBUG -DTBB_DO_ASSERT=1 -DTBB_USE_DEBUG -Isource/base -Iinclude -I/home/bangerth/p/deal.II/1/dealii/include -I/home/bangerth/p/deal.II/1/dealii/bundled/tbb41_20130401oss/include -I/home/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Include -I/home/bangerth/p/deal.II/1/dealii/bundled/umfpack/AMD/Include -I/home/bangerth/p/deal.II/1/dealii/bundled/boost-1.56.0/include -I/home/bangerth/p/deal.II/1/dealii/bundled/muparser_v2_2_4/include -I/usr/include/mpich -I/home/bangerth/bin/trilinos-11.12.1-mpi/include -I/home/bangerth/bin/petsc-3.5.3/include -I/home/bangerth/bin/p4est-1.1/FAST/include    -pedantic -fpic -Wall -Wextra -Wpointer-arith -Wwrite-strings -Wsynth -Wsign-compare -Wswitch -Woverloaded-virtual -Wno-long-long -Wno-deprecated-declarations -std=c++11 -fstack-protector -Wno-parentheses -Wno-unused-local-typedefs -Og -ggdb -Wa,--compress-debug-sections -MMD -MT source/base/CMakeFiles/obj_base.debug.dir/job_identifier.cc.o -MF "source/base/CMakeFiles/obj_base.debug.dir/job_identifier.cc.o.d" -o source/base/CMakeFiles/obj_base.debug.dir/job_identifier.cc.o -c /home/bangerth/p/deal.II/1/dealii/source/base/job_identifier.cc
```

On the other hand, `expand_instantiations` is built like this:
```
/usr/bin/c++     -MMD -MT cmake/scripts/CMakeFiles/expand_instantiations_exe.dir/expand_instantiations.cc.o -MF "cmake/scripts/CMakeFiles/expand_instantiations_exe.dir/expand_instantiations.cc.o.d" -o cmake/scripts/CMakeFiles/expand_instantiations_exe.dir/expand_instantiations.cc.o -c /home/bangerth/p/deal.II/1/dealii/cmake/scripts/expand_instantiations.cc
```

I think we may want to think of ways to pass flags when building our build tools as well. Specifically, for Windows, we will need `/EHsc`.

### PR DESCRIPTION
**Pull request by tamiko**
It turns out that the Windows platform needs this.

Closes #1792

### CODE REVIEW

**Comment by bangerth** [comment]
@tamiko -- many thanks for the quick response!

I forgot to state this in the original issue: Part of the problem is that in a cross-compilation setup, `expand_instantiations` is a host tool, whereas we compile the library for the target system. I don't recall whether we currently support cross compilation at all (which one needs for systems such as BlueGenes). What is the effect of your patch on this?

**Comment by bangerth** [comment]
(I'm merging because it is strictly a step forward despite the bigger question.)

**Comment by tamiko** [comment]
>  I don't recall whether we currently support cross compilation at all

We support cross compilation. (If no unguarded ```CHECK_CXX_SOURCE_RUNS``` sneaked in behind my back).

> What is the effect of your patch on this?

The target ```expand_instantiations_exe``` will always be built and results in an executable found under ```${CMAKE_BINARY_DIR}/bin```. This patch compiles and links the executable now with the compiler and linker flags we set during configure.

In case of a cross compilation setup, the macro ```macro_expand_instantiations.cmake``` does not use the target ```expand_instantiations_exe``` but relies on an executable ```expand_instantiations``` set via ```$PATH```.

**Comment by tamiko** [comment]
https://www.dealii.org/developer/developers/porting.html has short documentation. Example toolchain files can be found in our repository: ```doc/developers/Toolchain*.sample```

**Comment by bangerth** [comment]
I see, thanks for confirming. This makes sense now.

**Pull request merged**
