### PR TITLE
No need to futz with the VTK flags in step-15.

### PR DESCRIPTION
**Pull request by bangerth**
/rebuild

### CODE REVIEW

**Comment by drwells** [comment]
Why not? I don't see any reason to remove the demonstration of this feature.

**Comment by bangerth** [comment]
There are a million things we *could* do in these tutorials. But just like with every class lecture we teach, you pick a topic and stick with a certain direction you think is most educational. I see no reason why this particular program should be discussing this issue, so I axed it: Focus on one thing, and stick with it.

There isn't even a particular point in doing this here: We *already* use compression in the VTU writer, we just optimize for space where here we select optimizing for time, or the other way around. What's the point in doing that here?

**Comment by bangerth** [comment]
Maybe put differently: Let's assume the program had not done that so far, and I proposed a patch that adds it. Would you think that a good idea? I think my view of these tutorials is that of a minimalist: Everything that isn't really needed should not be there. (I recognize that that's *my* view of the tutorials and am not offended if others feel differently.)

**Comment by drwells** [comment]
Those are good points. My main concern is that setting that flag makes IO a lot faster in some cases (I remember it was like 2x as fast when I added it vs. the space optimization choice) so I think its important that this code show up in the tutorials.

Fortunately it looks like we set up `VtkFlags` in a couple other tutorials so this patch doesn't completely remove documentation of the feature so I am happy with the change (as opposed to deleting the equivalent code in step-9).

**Review by drwells — APPROVED** [review]

**Review by drwells — APPROVED** [review]

**Pull request merged**
