### PR TITLE
Replace static const by static constexpr in FEEValuation

### LINKED ISSUE #5354: failing tests matrix-free
`matrix_free/fe_evaluation_dofs_per_cell`

see https://cdash.kyomu.43-1.org/viewTest.php?onlydelta&buildid=12687

related to https://github.com/dealii/dealii/pull/5348

@kronbichler can you please have a look?

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #5354.

### CODE REVIEW

**Comment by kronbichler** [comment]
Thanks for fixing my mess @masterleinad. There are times when I do hate the C++ standard that allows so many different things. Some compilers like mine permit to do the obvious for a constant value whereas others adhere more strictly to the standard and take the value by reference, for which section 9.4.2/4 says "The member shall still be defined in a namespace scope if it is used in the program".

**Comment by kronbichler** [comment]
The tester still indicates trouble with these expressions, see e.g. here:
https://cdash.kyomu.43-1.org/testDetails.php?test=54264545&build=12717
(this is on de1fe8d, i.e., after this PR was merged).

The funny thing is that I tried to install clang-5 to reproduce on my machine (without external libraries) but I cannot, the test is fine. Does anybody else still see problems? If yes, we could most likely work around the problems by copying the values in the output function to temporary `unsigned int` variables. If someone can confirm, I will make this modification.

**Comment by masterleinad** [comment]
@kronbichler I was testing with `clang-5` for fixing this, so the test passes for me as well with that compiler. Let me try with `clang-4`

**Comment by masterleinad** [comment]
The test passes with `clang-4` for me as well.

**Comment by masterleinad** [comment]
... and `ICC-18` which was also failing before for me.

**Pull request merged**
