### PR TITLE
add asserts and comments in MPI::Partitioner

### PR DESCRIPTION
**Pull request by davydden**

### CODE REVIEW

**Comment by davydden** [comment]
> simplify lines 218-228 with what I wrote in #7095?

done

**Comment by kronbichler** [comment]
Have you checked that the MPI tests run on your machine locally? I'm asking because the tester won't cover these. If so, please merge yourself.

**Comment by davydden** [comment]
> Have you checked that the MPI tests run on your machine locally? I'm asking because the tester won't cover these. If so, please merge yourself.

hm, I thought we do have at least one tester which covers MPI tests... I will run tests locally tomorrow from another machine. Switching branches and re-compiling deal.II is very time consuming these days for me ;-((

**Comment by Rombur** [comment]
> Switching branches and re-compiling deal.II is very time consuming these days for me

You can use [git  worktree](https://git-scm.com/docs/git-worktree) so that switching branch is not as bad

**Comment by masterleinad** [comment]
> Have you checked that the MPI tests run on your machine locally? I'm asking because the tester won't cover these.

Passes the testsuite for me.

**Pull request merged**
