### PR TITLE
correcting some notations

### PR DESCRIPTION
**Pull request by pengfej**

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]
Thank you.

**Comment by kronbichler** [comment]
We can't currently see your full name:
```
invalid author '=' without firstname and lastname

hint: for possible solutions, consult the webpage:
```
https://github.com/dealii/dealii/wiki/Indentation#commit-authorship

**Comment by tjhei** [comment]
Pengfei, we can discuss the next time we meet.

**Comment by tjhei** [comment]
Looks good, thanks! /rebuild

**Pull request merged**
