### PR TITLE
Expose mesh loop bug for anisotropic grids.

### PR DESCRIPTION
**Pull request by luca-heltai**
`mesh_loop` does not know how to deal with anisotropic grids.

The first commit exposes the bug. We are working on a fix.

### CODE REVIEW

**Comment by nicola-giuliani** [comment]
bug_2d

**Comment by luca-heltai** [comment]
(mesh loop assumes that cells on different levels must be refined differently, and does not ask the proper function)

**Comment by nicola-giuliani** [comment]
bug_3d

**Review by kronbichler — APPROVED** [review]

**Pull request merged**
