### PR TITLE
Tutorial step 3+4 inconsistency in problem statement

### PR DESCRIPTION
**Pull request by christophkammer1989**
Documentation for step 3+4 tutorials states that Poisson problem is solved on domain [0,1]^dim. The code for the solver is implemented to solve Poisson problem on domain [-1,1]^dim.
Making pull request to resolve issue with inconsistent documentation,

### CODE REVIEW

**Comment by peterrum** [comment]
@christophkammer1989 Thanks for the quick PR! Something seems to went wrong. Have you added the changes to the current version of master?

**Comment by tamiko** [comment]
This is a pull request of the release branch dealii-9.2 to be merged into master :-)

**Comment by peterrum** [comment]
> This is a pull request of the release branch dealii-9.2 to be merged into master :-)

How is that possible?

**Comment by peterrum** [comment]
@christophkammer1989 I'll answer your question from the forum here. 

> Wouldn't it be easier to change the documentation on the tutorials website or is that done through Git, too?

The documentation is also on github. The documentation which users see on https://www.dealii.org/developer/doxygen/deal.II/index.html (or https://www.dealii.org/current/doxygen/deal.II/index.html) is automatically created.

The file which has to be updated is i.a.:

https://github.com/dealii/dealii/blob/e159ac89de419181c5f24566ba9eeb16303e75e8/examples/step-3/doc/intro.dox#L17

My suggestion is that in the first step you create a fork of `deal.II`, fetch the current version of deal.II, switch to master, create a new branch and add there the few changes you are proposing. After that you can push these changes to your fork (probably then you need to create a new PR - if you cannot change the branch of this PR - @tamiko is it possible?).

You can find a more detailed description of these steps [here](https://github.com/dealii/dealii/wiki/Contributing).

**Comment by christophkammer1989** [comment]
Thanks, let me read through this. I've never used Git to that extent.

**Pull request closed without merging**
