### PR TITLE
consistently use local_size()

### PR DESCRIPTION
**Pull request by masterleinad**
Revives #10335 based on #11472.

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]

**Comment by bangerth** [comment]
You'll have to rebase because of a merge conflict.

**Comment by bangerth** [comment]
I'm all for this, but I had comments on #10335 that were not addressed there and consequently are not either here. Can we still put those fixes in before merging?

**Comment by masterleinad** [comment]
> I'm all for this, but I had comments on #10335 that were not addressed there and consequently are not either here. Can we still put those fixes in before merging?

@bangerth I addressed the comments you had in the other pull request here now.

**Pull request merged**
