### PR TITLE
contrib/makeofflinedoc.sh: Use https instead of http

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Comment by drwells** [comment]
This shell command hangs for me when I try to run it.

**Comment by drwells** [comment]
wait, nevermind; the problem was on my end.

**Comment by tamiko** [comment]
> This shell command hangs for me when I try to run it.

Are you sure? (I.e. do you see output when you remove the "-q" parameter
for wget?) Further, do you see files popping up in 
"<build>/doc/doxygen/deal.II/images"?

**Comment by drwells** [comment]
You are correct on all accounts; I did not realize `-q` was in the argument list :(

**Pull request merged**
