### PR TITLE
Add some modified Sacado::Fad::DFad examples to the testsuite

### PR DESCRIPTION
**Pull request by jppelteret**
These tests just demonstrate the mechanism of configuring and using (nested) Sacado FAD numbers.

### CODE REVIEW

**Comment by bangerth** [comment]
Since you have the Sacado license headers in the testcases, can you prefix them with a sentence that explains what they are doing there?

**Comment by tjhei** [comment]
@tamiko is this an acceptable way to handle the license situation?

**Comment by jppelteret** [comment]
As I mentioned offline to @tjhei, if this way of referencing the original example is no good then I'll simply rewrite the test. It wouldn't be too much work, but I thought it would be a nice idea to have a direct comparison to a reference example in their suite.

**Comment by jppelteret** [comment]
I decided that I didn't want to wait and I changed the tests. This is now ready for review.

**Pull request merged**
