### PR TITLE
MSVS: fix linkage

### PR DESCRIPTION
**Pull request by resetius**

### CODE REVIEW

**Comment by resetius** [comment]
amd.h defines amd_malloc/calloc/realloc/free as extern "C"
amd_global.cc does not have extern "C" and some compilers (example: MSVS2015) can compile it as C++ and put mangled symbols to output binary as a result we've got linkage error

trivial example shows the problem:
`
$ cat amd_symbols.cc
#include <stdio.h>
#include <stdlib.h>

void *(*amd_malloc) (size_t) = malloc ;
void (*amd_free) (void *) = free ;
void *(*amd_realloc) (void *, size_t) = realloc ;
void *(*amd_calloc) (size_t, size_t) = calloc ;

$ g++ -c amd_symbols.cc

$ nm amd_symbols.o
0000000000000000 b .bss
0000000000000000 d .data
0000000000000000 r .rdata$zzz
0000000000000000 t .text
0000000000000018 D amd_calloc
0000000000000008 D amd_free
0000000000000000 D amd_malloc
0000000000000010 D amd_realloc
                 U calloc
                 U free
                 U malloc
                 U realloc

C:\Projects>cl -c amd_symbols.cc
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

amd_symbols.cc

$ nm amd_symbols.obj
0000000000000000 d .data
0000000000000000 N .debug$S
0000000000000000 i .drectve
0000000000000018 D ?amd_calloc@@3P6APEAX_K0@ZEA
0000000000000008 D ?amd_free@@3P6AXPEAX@ZEA
0000000000000000 D ?amd_malloc@@3P6APEAX_K@ZEA
0000000000000010 D ?amd_realloc@@3P6APEAXPEAX_K@ZEA
0000000001055e97 a @comp.id
0000000080000190 a @feat.00
                 U calloc
                 U free
                 U malloc
                 U realloc
`

**Comment by drwells** [comment]
This looks reasonable to me and we have patched our bundled copy of UMFPACK from time to time (though it has been a few years): this is similar to ed15bcb275ef90dbd7ae923b7ce19afe0fd54707.

Since we compile all of these files as C++ anyway, I think that we should just get rid of the preprocessor checks. Would you mind getting rid of those before we merge this?

**Comment by resetius** [comment]
sure
PR updated

**Comment by bangerth** [comment]
The `#include` inside the `extern "C"` makes me nervous, but we're early enough in the development cycle -- let's just see what happens here.

**Comment by drwells** [comment]
We could just move the `#include <stdio.h>` up to the top of the file.

**Pull request merged**
