### PR TITLE
base/mpi.h: also instantiate for signed long long int

### PR DESCRIPTION
**Pull request by tamiko**
Vaguely in reference to #16493

### CODE REVIEW

**Review by masterleinad — COMMENTED** [review]
What about `MPI_DEVICE_SCALARS` for consistency?

**Comment by tamiko** [comment]
@masterleinad Good point.

**Review by masterleinad — APPROVED** [review]

**Review by bangerth — COMMENTED** [review]
Out of curiosity, it is true that on all systems we work on, two out of `int`, `long int`, and `long long int` are the same. Does the compiler not complain in those cases?

Should we instead instantiate for `int` and `int64_t`?

**Comment by tamiko** [comment]
@bangerth I think according to the standard `int`, `long int` and `long long int` are distinct types, meaning:
```
template <typename C> void foo(){};
template void foo<int>();
template void foo<long int>();  // ok
template void foo<long long int>(); // ok
template void foo<std::int64_t>(); // error: duplicate instantiation

```

**Comment by drwells** [comment]
It would be deeply weird if
```cpp
static_assert(std::is_same_v<long int, long long int>);
```
succeeded on some platforms but failed on others.

**Comment by bangerth** [comment]
Not weird at all. `std::is_same<int,std::int16_t>` is also true on some platforms and false on others. The length of integers has always been platform dependent. On some platforms, `long int` is 32 bit and on others it is 64 bit. `long long int` is pretty generally 64 bit, but I don't think the standard guarantees that it is.

**Comment by tamiko** [comment]
The difference is that `std::intN_t` is allowed to be a typedef whereas `int`, `long`, and `long long` must be different types. Even if they are functionally the same.

**Comment by drwells** [comment]
It's an interesting question and I had to look it up to be sure. In 17.4.2 all the `cstdint` types (`int16_t` et al) are declared with `using`, whereas in 6.8.2 `signed char`, `short int`, etc are "the five standard signed integer types".

**Review by bangerth — APPROVED** [review]

**Pull request merged**
