### PR TITLE
step-69: Remove boundary c_ij fix

### PR DESCRIPTION
**Pull request by tamiko**
We compute the boundary normal by averaging the normal over the
quadrature points weighted with the shape function. It turns out that
this is sufficient to preserve mass and total energy. No change of the
c_ij's are needed.

### CODE REVIEW

**Comment by tamiko** [comment]
@itomasSNL @kronbichler *ping*

**Comment by tamiko** [comment]
All, I would like to get a review by @itomasSNL on this one :sweat_smile:

**Review by kronbichler — APPROVED** [review]

**Comment by tamiko** [comment]
Let's merge this as is - @itomasSNL promised to follow up with some documentation updates in a separate pull request :-)

**Comment by itomasSNL** [comment]
@kronbichler @tamiko Now the documentation and the source code are consistent.

**Review by kronbichler — APPROVED** [review]

**Pull request merged**
