### PR TITLE
Fix quick_tests

### LINKED ISSUE #6911: Quick test with complex petsc fails
When deal.ii is compiled with the complex version of petsc, the quick test for petsc fails.

Probably it is a test for designed the real version of petsc. Maybe when deal.ii is built with complex petsc it should run a complex test for petsc.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #6911.

### CODE REVIEW

**Comment by tamiko** [comment]
```
FAILED: /usr/bin/c++   -DDEBUG -DTBB_DO_ASSERT=1 -DTBB_USE_DEBUG -I/home/bob/source/source/numerics -Isource/numerics -Iinclude -I/home/bob/source/include -I/home/bob/source/bundled/tbb-2018_U2/include -I/home/bob/source/bundled/boost-1.62.0/include -I/home/bob/source/bundled/umfpack/UMFPACK/Include -I/home/bob/source/bundled/umfpack/AMD/Include -I/home/bob/source/bundled/muparser_v2_2_4/include -isystem /home/bob/libs/parmetis-4.0.3/include -isystem /home/bob/libs/oce-OCE-0.17/include/oce    -pedantic -fPIC -Wall -Wextra -Wpointer-arith -Wwrite-strings -Wsynth -Wsign-compare -Wswitch -Woverloaded-virtual -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -std=c++11 -Wno-parentheses -Wno-unused-local-typedefs -Og -ggdb -Wa,--compress-debug-sections -MMD -MT source/numerics/CMakeFiles/obj_numerics_debug.dir/derivative_approximation.cc.o -MF "source/numerics/CMakeFiles/obj_numerics_debug.dir/derivative_approximation.cc.o.d" -o source/numerics/CMakeFiles/obj_numerics_debug.dir/derivative_approximation.cc.o -c /home/bob/source/source/numerics/derivative_approximation.cc
In file included from include/deal.II/base/config.h:398:0,
                 from /home/bob/source/include/deal.II/base/quadrature_lib.h:20,
                 from /home/bob/source/source/numerics/derivative_approximation.cc:16:
/home/bob/source/include/deal.II/base/numbers.h:57:24: fatal error: Sacado.hpp: No such file or directory
 #  include <Sacado.hpp>
                        ^
```

**Comment by masterleinad** [comment]
Might `DEAL_II_TRILINOS_WITH_SACADO` be cached and wrongly set?

**Comment by masterleinad** [comment]
Actually, we have
```
-- Found TRILINOS
-- Check whether the found trilinos package contains all required modules:
-- Found Amesos
-- Found Epetra
-- Found Ifpack
-- Found AztecOO
-- Found Teuchos
-- Found ML
-- Found MueLu
-- Module ROL not found!
-- Found Sacado
-- Found Zoltan
-- Could not find a sufficient Trilinos installation: Trilinos has to be configured with the same MPI configuration as deal.II.
-- Found SACADO_CONFIG_H
-- Found SACADO_TRAD_HPP
-- Performing Test TRILINOS_CXX_SUPPORTS_SACADO_COMPLEX_RAD
-- Performing Test TRILINOS_CXX_SUPPORTS_SACADO_COMPLEX_RAD - Success
-- DEAL_II_WITH_TRILINOS has unmet external dependencies.
[...]
  ( DEAL_II_WITH_TRILINOS = OFF )
```

**Comment by jppelteret** [comment]
That's interesting. So we should actually force all `DEAL_II_WITH_TRILINOS_WITH_...=OFF` if  `DEAL_II_WITH_TRILINOS = OFF`.

**Comment by Rombur** [comment]
Thanks for finding the problem @masterleinad I wonder why we don't have the problem with Zoltan

**Comment by Rombur** [comment]
OK I know how to fix the problem. I just need to move some code around. PR incoming

**Pull request merged**
