### PR TITLE
Allow to enforce unique mapping in RemotePointEvaluation

### LINKED ISSUE #12192: Unique map in RemotePointEvaluation
As pointed out in https://groups.google.com/g/dealii/c/hm-SEp6ghdw, it would be nice a unique map within `RemotePointEvaluation`.

FYI @DavidSCN

### PR DESCRIPTION
**Pull request by peterrum**
closes #12192

FYI @mschreter @DavidSCN

### CODE REVIEW

**Comment by DavidSCN** [comment]
First of all thank you very much for quick reaction and your efforts.

I just tested it and I'm not completely sure I understand (according to our discussion): the unique mapping flag decides now for a unique evaluation cell, even in case of distributed triangulations where points may be located at the partitioning boundary. What I finally need in order to completely solve my issue would be the owner information of the cell-to-point mapping, meaning I need to know which process 'owns' and evaluates each vertex. 

In any case, I need to receive/decide for all values exclusively on one particular process, even when I define them more than once as an input argument across processes. I guess the information is already inside the evaluation cache and I just don't know how to query it.

**Comment by peterrum** [comment]
> In any case, I need to receive/decide for all values exclusively on one particular process, even when I define them more than once as an input argument across processes. I guess the information is already inside the evaluation cache and I just don't know how to query it.

To me this sounds like that you want that the mapping is bidirectional unique. This is not really the task `RemotePoinEvaluation` since it returns the values for a vector of points:
```cpp
std::vector<Point<dim>> evaluation_points;

// fill points

const vector<double> result = 
  VectorTools::evaluate_at_points<1>( /*...*/ evaluation_points /*...*/);
```

What you would need is a pre-processing step:
```cpp
std::vector<Point<dim>> relevant_evaluation_points;

// fill points (as before)

// kick out duplicates
std::vector<Point<dim>> evaluation_points = make_unique(relevant_evaluation_points);

const vector<double> result = 
  VectorTools::evaluate_at_points<1>( /*...*/ evaluation_points /*...*/);
```

To kick out duplicates is not implemented yet, but shouldn't be to difficult based on CosensusAlgorithm and a Cartesian decomposition of the whole domain. You might want to checkout the implementation in https://github.com/dealii/dealii/blob/master/include/deal.II/base/mpi_compute_index_owner_internal.h.

Out of curiosity, could you provide some more details how you intend to use the function, in particular where the points are coming from and why they need to be unique. In my use cases, it is actually good to have these multiple times, since we might want to test them multiple times (on different  cells on different processes).

**Comment by DavidSCN** [comment]
> Out of curiosity, could you provide some more details how you intend to use the function, in particular where the points are coming from and why they need to be unique. In my use cases, it is actually good to have these multiple times, since we might want to test them multiple times (on different cells on different processes).

Yes, sure. As you know, we deal with non-matching meshes of different solvers. For coupling purpose, we want to evaluate the computed solution in our deal.II solver at the coupling meshes of _other_ solvers (which have an arbitrary location at the respective interface, where this class comes in). However, I obviously need to re-partition the interface mesh of the non-deal.II solver according to the partitioning of my deal.II solver. I cannot enforce the point uniqueness during the re-partitioning since I eventually want to construct (non-related) interpolants based on the partitioning, where overlapping partitions/vertices are explicitly required. We also use axis-aligned bounding boxes for the interface partitioning which might not be accurate enough for curved geometries. The evaluated data, i.e. boundary condition for the other solver, is finally applied peer-to-peer, so that duplication leads to duplicated boundary condition leading to errors. 

The important point is that I cannot avoid the overlap in the end and I cannot accept a duplicated evaluation. There are other remedies and options than enforcing uniqueness during evaluation, but I think it is the easiest option in order to get a working version for now.

Therefore, your second code example is exactly my intended use-case. The `RemotePoinEvaluation` is actually even doing a bit too much since I don't really need results from other processes and (I guess) also do not need the underlying communication patter (at least for CG, update ghost values on the global vector should be enough). However, I tried to use the `FEPointEvaluation` raw and it failed in the first place since I do not have any reference cell positions. Thus, I started with the maybe too powerful `RemotePointEvaluation`. 

> To kick out duplicates is not implemented yet, but shouldn't be to difficult based on CosensusAlgorithm and a Cartesian decomposition of the whole domain. You might want to checkout the implementation in https://github.com/dealii/dealii/blob/master/include/deal.II/base/mpi_compute_index_owner_internal.h.

Thanks again, I will definitely check that out.

**Comment by peterrum** [comment]
Indeed for your case `RemotePointEvaluation` is an overkill, since the points are already at the right processes. What you want is to filter the vector of locally relevant points the following way: check if point is owned by any local cell. If this is the case, you need to check if the point is also owned by cells of other processes (i.e., ghost cells) and if that is the case you need to find a consensus: the most simplest consensus - since it does not involve any communication - is to pick the rank of the lowest rank (which is a good heuristic used in many parts of the library).

A code that acplishes this could look like this:
```cpp
template <int dim, int spacedim>
std::vector<
  std::pair<typename Triangulation<dim, spacedim>::active_cell_iterator,
            Point<dim>>>
make_unique(const Mapping<dim, spacedim> &      mapping,
            const Triangulation<dim, spacedim> &tria,
            const std::vector<Point<spacedim>>  points_in,
            double                              tolerance = 1e-10)
{
  std::vector<
    std::pair<typename Triangulation<dim, spacedim>::active_cell_iterator,
              Point<dim>>>
    unique_points;

  GridTools::Cache<dim, spacedim> cache(tria, mapping);
  typename Triangulation<dim, spacedim>::active_cell_iterator cell_hint;
  const std::vector<bool>                                     marked_vertices;

  const unsigned int my_rank =
    Utilities::MPI::this_mpi_process(tria.get_communicator());

  for (const auto &point : points_in)
    {
      const auto first_cell = GridTools::find_active_cell_around_point(
        cache, point, cell_hint, marked_vertices, tolerance);

      cell_hint = first_cell.first;
      if (cell_hint.state() == IteratorState::valid)
        {
          const auto active_cells_around_point =
            GridTools::find_all_active_cells_around_point(
              cache.get_mapping(),
              cache.get_triangulation(),
              point,
              tolerance,
              first_cell);

          unsigned int lowes_rank = numbers::invalid_unsigned_int;

          for (const auto &cell : active_cells_around_point)
            lowes_rank = std::min(lowes_rank, cell.first->subdomain_id());

          if (lowes_rank != my_rank)
            continue;

          for (const auto &cell : active_cells_around_point)
            if (cell.first->is_locally_owned())
              {
                unique_points.push_back(cell);
                break;
              }
        }
    }

  return unique_points;
}
```

Hope this helps.

**Comment by DavidSCN** [comment]
Alright, then let me say thank you very much for the third time, this will definitely help! :)

**Review by kronbichler — APPROVED** [review]

**Comment by kronbichler** [comment]
Looks good to me. If you want this for the 9.3 release, please rebase to master, squash commits into reasonable-sized portions, and add the `ready-to-test` flag.

**Comment by peterrum** [comment]
I will rebase in a couple of minutes. But, I do not insist on having this in 9.3, since I wouldn't have accepted such "new features" myself in the last minute.

**Review by kronbichler — APPROVED** [review]

**Pull request merged**
