### PR TITLE
Use debug flags when checking for compress-debug-sections

### PR DESCRIPTION
**Pull request by masterleinad**
Currently, building with debug flags using `clang-7` fails for me and `compress-debug-sections` seems to be guilty. The `ENABLE_IF_SUPPORTED` test passes but fails when debug flags such as `-g` or `-ggdb` are added. Hence, we should just add these flags when performing the test.

For completeness, `clang-7` fails the `DEAL_II_HAVE_USABLE_FLAGS_DEBUG` check with the following output:
```
 /opt/compiler/llvm-7.0.0/bin/clang++    -DDEAL_II_HAVE_USABLE_FLAGS_DEBUG -pedantic -fPIC -Wall -Wextra -Wpointer-arith -Wwrite-strings -Wsynth -Wsign-compare -Wswitch -Woverloaded-virtual -Wno-deprecated-declarations -Qunused-arguments -Wno-unsupported-friend -Wno-     undefined-var-template -openmp-simd -std=c++17 -stdlib=libc++ -Wno-unused-local-typedefs -Og -ggdb -Wa,--compress-debug-sections -o CMakeFiles/cmTC_b4b1d.dir/src.cxx.o -c src.cxx
 Stack dump:
 0.  Program arguments: /opt/compiler/llvm-7.0.0/bin/clang-7 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj --compress-debug-sections -disable-free -disable-llvm-verifier -discard-value-names -main-file-name src.cxx -mrelocation-model pic -pic-level 2 -mthread-model     posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -coverage-notes-file /mnt/data/darndt/Sources/dealii-   clang-7.0.0rc3/build/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_b4b1d.dir/src.cxx.gcno -resource-dir /opt/compiler/llvm-7.0.0/lib/clang/7.0.0 -D DEAL_II_HAVE_USABLE_FLAGS_DEBUG -I/export/home/darndt/include -I/export/home/darndt/include -I. -internal-isystem /opt/compiler/     llvm-7.0.0/bin/../include/c++/v1 -internal-isystem /usr/local/include -internal-isystem /opt/compiler/llvm-7.0.0/lib/clang/7.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -   Og -Wall -Wextra -Wpointer-arith -Wwrite-strings -Wsynth -Wsign-compare -Wswitch -Woverloaded-virtual -Wno-deprecated-declarations -Wno-unsupported-friend -Wno-undefined-var-template -Wno-unused-local-typedefs -pedantic -std=c++17 -fdeprecated-macro -fdebug-compilation- dir /mnt/data/darndt/Sources/dealii-clang-7.0.0rc3/build/CMakeFiles/CMakeTmp -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -o CMakeFiles/cmTC_b4b1d.dir/src.cxx.o -x c++ src.cxx -faddrsig
 1.  <eof> parser at end of file
 2.  Code generation
 #0 0x0000000001cece54 PrintStackTraceSignalHandler(void*) (/opt/compiler/llvm-7.0.0/bin/clang-7+0x1cece54)
 #1 0x0000000001ceae7e llvm::sys::RunSignalHandlers() (/opt/compiler/llvm-7.0.0/bin/clang-7+0x1ceae7e)
 #2 0x0000000001ced012 SignalHandler(int) (/opt/compiler/llvm-7.0.0/bin/clang-7+0x1ced012)
 #3 0x00007f92af564390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
 #4 0x0000000001aa7ad3 llvm::Error llvm::handleErrors<llvm::consumeError(llvm::Error)::'lambda'(llvm::ErrorInfoBase const&)>(llvm::Error, llvm::consumeError(llvm::Error)::'lambda'(llvm::ErrorInfoBase const&)&&) (/opt/compiler/llvm-7.0.0/bin/clang-7+0x1aa7ad3)
 #5 0x0000000001aa3aa6 (anonymous namespace)::ELFWriter::writeObject(llvm::MCAssembler&, llvm::MCAsmLayout const&) (/opt/compiler/llvm-7.0.0/bin/clang-7+0x1aa3aa6)
 #6 0x0000000001aa2045 (anonymous namespace)::ELFSingleObjectWriter::writeObject(llvm::MCAssembler&, llvm::MCAsmLayout const&) (/opt/compiler/llvm-7.0.0/bin/clang-7+0x1aa2045)
 #7 0x0000000001a57068 llvm::MCAssembler::Finish() (/opt/compiler/llvm-7.0.0/bin/clang-7+0x1a57068)
 #8 0x000000000243a370 llvm::AsmPrinter::doFinalization(llvm::Module&) (/opt/compiler/llvm-7.0.0/bin/clang-7+0x243a370)
 #9 0x0000000001895833 llvm::FPPassManager::doFinalization(llvm::Module&) (/opt/compiler/llvm-7.0.0/bin/clang-7+0x1895833)
 #10 0x0000000001895d93 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/compiler/llvm-7.0.0/bin/clang-7+0x1895d93)
 #11 0x0000000001e70697 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::        unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/opt/compiler/llvm-7.0.0/bin/clang-7+0x1e70697)
 #12 0x000000000266624d clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/opt/compiler/llvm-7.0.0/bin/clang-7+0x266624d)
 #13 0x0000000002b5ca25 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler/llvm-7.0.0/bin/clang-7+0x2b5ca25)
 #14 0x00000000022a6717 clang::FrontendAction::Execute() (/opt/compiler/llvm-7.0.0/bin/clang-7+0x22a6717)
 #15 0x0000000002251518 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler/llvm-7.0.0/bin/clang-7+0x2251518)
 #16 0x000000000233a7a5 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler/llvm-7.0.0/bin/clang-7+0x233a7a5)
 #17 0x0000000000933d7f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler/llvm-7.0.0/bin/clang-7+0x933d7f)
 #18 0x0000000000932343 main (/opt/compiler/llvm-7.0.0/bin/clang-7+0x932343)
 #19 0x00007f92ae4fb830 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20830)
 #20 0x000000000092f779 _start (/opt/compiler/llvm-7.0.0/bin/clang-7+0x92f779)
 clang-7: error: unable to execute command: Segmentation fault
 clang-7: error: clang frontend command failed due to signal (use -v to see invocation)
 clang version 7.0.0 (tags/RELEASE_700/final)
 Target: x86_64-unknown-linux-gnu
 Thread model: posix
 InstalledDir: /opt/compiler/llvm-7.0.0/bin
 clang-7: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
 clang-7: note: diagnostic msg:
 ********************
 
 PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
 Preprocessed source(s) and associated run script(s) are located at:
 clang-7: note: diagnostic msg: /tmp/src-c8590f.cpp
 clang-7: note: diagnostic msg: /tmp/src-c8590f.sh
 clang-7: note: diagnostic msg:
 
 ********************
 ninja: build stopped: subcommand failed.
 
 Source file was:
 int main(){ return 0; }
```

### CODE REVIEW

**Comment by drwells** [comment]
```
clang-7: error: unable to execute command: Segmentation fault
```

Is this a bug in clang?

**Comment by masterleinad** [comment]
I am not sure. Probably it's rather a problem with my installation. I used the pre-built version instead of building the compiler from source.

**Comment by drwells** [comment]
I'll try with my copy of clang-7.

**Comment by drwells** [comment]
When I set things up with my vanilla (its provided by Arch Linux as-is) copy of clang-7 I get
```
DEAL_II_CXX_FLAGS_DEBUG = -Og -ggdb -Wa,--compress-debug-sections
```
i.e., AFAICT things work fine for me. The `DEAL_II_HAVE_USABLE_FLAGS_DEBUG` test also passes.

I don't see any harm in adding this fix but I suspect there is something unusual going on with your compiler.

**Comment by masterleinad** [comment]
Yes, it is quite interesting that with this modification the whole test suite passes.

**Comment by masterleinad** [comment]
Yes, it is quite interesting that with this modification the whole test suite passes.

**Comment by masterleinad** [comment]
Yes, it is quite interesting that with this modification the whole test suite passes.

**Comment by bangerth** [comment]
This seems reasonable to me. Can we let @tamiko take a look as well?

**Comment by masterleinad** [comment]
@tamiko What's your opinion here?

**Comment by drwells** [comment]
Ping @tamiko :)

**Comment by drwells** [comment]
I'll try to run the new CI tester on this. Lets see what happens.

Either way, lets merge this as soon as the tester is happy.

**Comment by masterleinad** [comment]
I can rebase if you prefer that.

**Comment by drwells** [comment]
That was probably needed to reboot the CI tester.

**Pull request merged**
