### PR TITLE
Make serialization work with older GCC versions as well.

### LINKED ISSUE #4294: New test failures
I get these test failures, likely as a result of #4291 (@danshapero?):
```
        2047 - bits/refine_and_coarsen_for_active_cell_index_05.debug (Failed)
        7882 - serialization/triangulation_01.debug (Failed)
        7884 - serialization/triangulation_02.debug (Failed)
        7906 - sharedtria/tria_load_01.mpirun=2.debug (Failed)
```
The first of these reads as follows:
```
2047: /usr/include/c++/4.8.2/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >; _Args = {const std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >&}; _Tp = std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >]’:                                                                                                  
2047: /usr/include/c++/4.8.2/bits/alloc_traits.h:254:4:   required from ‘static typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type std::allocator_traits<_Alloc>::_S_construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >; _Args = {const std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >&}; _Alloc = std::allocator<std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > > >; typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type = void]’           
2047: /usr/include/c++/4.8.2/bits/alloc_traits.h:393:57:   required from ‘static decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) std::allocator_traits<_Alloc>::construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >; _Args = {const std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >&}; _Alloc = std::allocator<std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > > >; decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) = <type error>]’                       
2047: /usr/include/c++/4.8.2/bits/stl_vector.h:906:34:   required from ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >; _Alloc = std::allocator<std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > > >; std::vector<_Tp, _Alloc>::value_type = std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >]’                                                             
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/bundled/boost-1.62.0/include/boost/serialization/collections_load_imp.hpp:96:9:   required from ‘typename boost::disable_if<boost::serialization::detail::is_default_constructible<typename T::value_type>, void>::type boost::serialization::stl::collection_load_impl(Archive&, T&, boost::serialization::collection_size_type, boost::serialization::item_version_type) [with Archive = boost::archive::text_iarchive; T = std::vector<std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >, std::allocator<std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > > > >; typename boost::disable_if<boost::serialization::detail::is_default_constructible<typename T::value_type>, void>::type = void]’
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/bundled/boost-1.62.0/include/boost/serialization/vector.hpp:91:57:   required from ‘void boost::serialization::load(Archive&, std::vector<U, Allocator>&, unsigned int, mpl_::false_) [with Archive = boost::archive::text_iarchive; U = std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > >; Allocator = std::allocator<std::unique_ptr<dealii::internal::Triangulation::TriaLevel<3>, std::default_delete<dealii::internal::Triangulation::TriaLevel<3> > > >; mpl_::false_ = mpl_::bool_<false>]’
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/bundled/boost-1.62.0/include/boost/serialization/vector.hpp:159:44:   [ skipping 28 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/bundled/boost-1.62.0/include/boost/archive/detail/common_iarchive.hpp:66:40:   required from ‘void boost::archive::detail::common_iarchive<Archive>::load_override(T&) [with T = dealii::Triangulation<3, 3>; Archive = boost::archive::text_iarchive]’
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/bundled/boost-1.62.0/include/boost/archive/basic_text_iarchive.hpp:70:9:   required from ‘void boost::archive::basic_text_iarchive<Archive>::load_override(T&) [with T = dealii::Triangulation<3, 3>; Archive = boost::archive::text_iarchive]’
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/bundled/boost-1.62.0/include/boost/archive/text_iarchive.hpp:82:54:   required from ‘void boost::archive::text_iarchive_impl<Archive>::load_override(T&) [with T = dealii::Triangulation<3, 3>; Archive = boost::archive::text_iarchive]’
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/bundled/boost-1.62.0/include/boost/archive/detail/interface_iarchive.hpp:68:9:   required from ‘Archive& boost::archive::detail::interface_iarchive<Archive>::operator>>(T&) [with T = dealii::Triangulation<3, 3>; Archive = boost::archive::text_iarchive]’
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/tests/bits/refine_and_coarsen_for_active_cell_index_05.cc:123:10:   required from ‘void check() [with int dim = 3]’
2047: /home/fac/f/bangerth/p/deal.II/1/dealii/tests/bits/refine_and_coarsen_for_active_cell_index_05.cc:170:13:   required from here
2047: /usr/include/c++/4.8.2/ext/new_allocator.h:120:4: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = dealii::internal::Triangulation::TriaLevel<3>; _Dp = std::default_delete<dealii::internal::Triangulation::TriaLevel<3> >]’
2047:   { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
2047:     ^
```
I'll look at the others later if nobody beats me to it.

### PR DESCRIPTION
**Pull request by bangerth**
This fixes #4294. Supersedes #4327.

### CODE REVIEW

**Comment by bangerth** [comment]
This is basically like #4327, but I can verify that it actually works on my machine. @danshapero -- does this work for you as well?

**Comment by danshapero** [comment]
Yes this works for me. Turns out I had an old installation of deal.II-8.5 on my machine. I was getting all these weird errors from boost because the headers from the old version were being included instead of the new ones.

**Comment by bangerth** [comment]
OK, great. May I ask for a review in that case from someone?

**Comment by drwells** [comment]
This works for me with GCC 4.8 and GCC 6.3.

**Pull request merged**
