### PR TITLE
add note on discontinuous coefficient

### PR DESCRIPTION
**Pull request by kostyfisik**

### CODE REVIEW

**Comment by kostyfisik** [comment]
Squashing finished with the message 

On branch discontinuous-note
Your branch and 'origin/discontinuous-note' have diverged,
and have 1 and 13 different commits each, respectively.

So I just created a new PR.

**Comment by davydden** [comment]
> On branch discontinuous-note
Your branch and 'origin/discontinuous-note' have diverged,
and have 1 and 13 different commits each, respectively.

FYI, the right way is to `git push --force`.

**Comment by kostyfisik** [comment]
@davydden  I`ve done it. It is a single commit in my branch in my repo here https://github.com/kostyfisik/dealii/commits/discontinuous-note , but it is still multiple commits in the original PR.

**Comment by davydden** [comment]
> I`ve done it.

What you did originally is squashed 13 commits on  your **local** branch into 1. Of course, the remote branch (on your github account) knows nothing about your modifications and that's what git is telling you. By doing 
```
git push --force
```
you would have overwritten those 13 commits in your previous branch with that single one.

After created another PR and pushed your local branch to another remote, probably you need to do be explicit where you want to push the branch, i.e. 

```
git push <your remote> discontinuous-note -f
```

**Comment by kostyfisik** [comment]
I will try to use `rebase` instead of `reset` next time (If I do remember it, it is a rare operation for me). Here I followed top link fromm google  http://stackoverflow.com/questions/7275508/is-there-a-way-to-squash-a-number-of-commits-non-interactively

**Comment by davydden** [comment]
> I will try to use rebase instead of reset next time

it does not matter whether you use `rebase` or `reset` to squash commits. The end result is the same.

**Comment by davydden** [comment]
@kostyfisik this is good writeup https://www.atlassian.com/git/tutorials/syncing

**Comment by bangerth** [comment]
It's just a doc change, so let's not bother with tests -- something is broken anyway.

**Comment by bangerth** [comment]
Thanks very much, @kostyfisik , for the addition! 

I appreciate you went around and around on this with us a couple of times. Your patience is greatly appreciated, and I hope it won't be the last contribution you have!

**Comment by kostyfisik** [comment]
Dear all! Thank you for your help, it made this contribution to be much better and nicely improved my knowledge of FEM.

**Pull request merged**
