### PR TITLE
Test cases for filtered_matrix in tests/lac

### PR DESCRIPTION
**Pull request by dakshinai**
Added test cases for lac/filtered_matrix

### CODE REVIEW

**Comment by tamiko** [comment]
Thanks for the work!

Please rebase onto master, <code>git remote update; git rebase origin/master</code> (or similar) and add an entry to <code>doc/news/changes.h</code> under "specific improvements".

**Comment by tamiko** [comment]
Or shall I do this for you?

**Comment by dakshinai** [comment]
Thank you. I'm not sure If can I do without write access. Could you please merge the changes for me?

**Comment by dakshinai** [comment]
I would also need your help to edit doc/news/changes.h or I can move the changes from my fork and request a merge

**Comment by bangerth** [comment]
There's no need for an addition to changes.h -- no user visible code was changed, only testcases.

**Comment by tamiko** [comment]
Merged. Thanks again for the work!

**Pull request closed without merging**
