### PR TITLE
Do not allow access to return value of tasks that ended in exceptions.

### LINKED ISSUE #15495: Threads::Task::return_value() should not be allowed when a task ends with an exception.
#15492 (and #15478) point out that we have a problem when a task ends in an exception. That's because in that case, the internal `return_value` object is left uninitialized, and while one can call `t.join` (see for example https://github.com/dealii/dealii/blob/master/tests/multithreading/task_01_exception.cc#L26-L51), there is nothing currently that prohibits calling `t.return_value()` *after* calling `join()`.

Note that https://github.com/dealii/dealii/blob/master/tests/multithreading/task_01_exception_02.cc only shows that the *first* call to `return_value()` yields an exception, but every successive call needs to result in aborting the program. In fact, the right place is in
```
      typename internal::return_value<RT>::reference_type
      TaskDescriptor<RT>::get()
      {
        wait();
        return returned_object.get();     // not allowed to work if we had an exception
      }
```

### PR DESCRIPTION
**Pull request by bangerth**
Fixes #15495.

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

**Comment by bangerth** [comment]
Fixed as requested.

**Comment by tamiko** [comment]
This triggers in a number of tests:
```
base/generate_normal_random_number_01.debug: RUN failed. ------ Partial output:
base/generate_normal_random_number_01.debug: RUN failed. ------ Additional output on stdout/stderr:
--------------------------------------------------------
An error occurred in line <235> of file </jenkins/workspace/dealii-serial_PR-15542/include/deal.II/base/thread_management.h> in function
    RT& dealii::Threads::internal::return_value<RT>::get() [with RT = std::pair<double, double>; dealii::Threads::internal::return_value<RT>::reference_type = std::pair<double, double>&]
The violated condition was: 
    value_is_initialized
Additional information: 
    You cannot read the return value of a thread or task if that value has
    not been set. This happens, for example, if a task or thread threw an
    exception.
--------------------------------------------------------
```

```
The following tests FAILED:
	244 - base/generate_normal_random_number_01.debug (Failed)
	3218 - multithreading/thread_local_storage_03.debug (Failed)
	3219 - multithreading/thread_local_storage_04.debug (Failed)
	3233 - multithreading/thread_validity_10.debug (Failed)
	3236 - multithreading/thread_validity_13.debug (Failed)
Errors while running CTest
```

**Comment by bangerth** [comment]
Let me reconsider this once #15555 is merged. I believe that some of the failing tests will go away there because the class that triggers the issue is going to go away.

**Comment by bangerth** [comment]
Seems to work now!

**Pull request merged**
