### PR TITLE
fixes a typo in step-3 tutorial doc (convergence topic in results/extensions)

### PR DESCRIPTION
**Pull request by krishnakumarg1984**

### CODE REVIEW

**Comment by masterleinad** [comment]
Thanks for fixing this! Please provide a valid name and e-mail address in your commit:
```
invalid author 'Krishnakumar' without firstname and lastname

hint: for possible solutions, consult the webpage:

      https://github.com/dealii/dealii/wiki/Indentation#commit-authorship
```

**Comment by tjhei** [comment]
@krishnakumarg1984 thanks for fixing the author and email. One more thing: the email krishna.kumar@ucl.ac.uk that you used to commit is not associated with your github account. Can you go into your github.com settings and add this as a secondary email address, please? Otherwise your commits here show up with a grey icon instead of your user.

**Comment by krishnakumarg1984** [comment]
@tjhei  Yes. Done.

**Comment by tjhei** [comment]
> It seems that `Travis` is still not happy.

Yes, please rebase and squash the commits. The offender is 0e987237b8

**Comment by bangerth** [comment]
@masterleinad -- if you're ok with it, would you please release your block on this PR?

**Comment by masterleinad** [comment]
> @masterleinad -- if you're ok with it, would you please release your block on this PR?

`Travis` still reports an invalid author name (but doesn't return an error code, see #9229).

**Comment by krishnakumarg1984** [comment]
I think I am messing things up here.  If people agree, shall we close this out, and I can try again making a fresh PR?

**Comment by bangerth** [comment]
Superseded by #9246.

**Comment by tjhei** [comment]
> Superseded by #9246.

that looks like an unrelated change (step 4 vs step 3)

**Comment by bangerth** [comment]
Oh, whoops. But yes, to the original question: It's ok to close this and come up with a new PR.

**Comment by krishnakumarg1984** [comment]
Closing this with PR #9270

**Pull request closed without merging**
