### PR TITLE
Add Tpetra tests that are already working.

### PR DESCRIPTION
**Pull request by bangerth**
This breaks out the 78 of the tests in #16611 that are already working on my system. I thought that's useful to make sure these don't regress while we work on the remaining Tpetra issues.

@jpthiele @kinnewig FYI

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

**Comment by jpthiele** [comment]
So with the 12 merged ones we are already at 90 tests. 
Thats really good!

**Comment by masterleinad** [comment]
I'm not quite sure why the `documentation` part of the `indent` CI is a failing. It says:
```
/home/runner/work/dealii/dealii/doc/news/9.4.0-vs-9.5.0.h:1009: warning: explicit link request to 'point_gradients()' could not be resolved
deprecated:85: warning: explicit link request to 'Vector< Number >' could not be resolved
warning: Inheritance graph for 'AlignedVector' not generated, too many nodes (57), threshold is 50. Consider increasing DOT_GRAPH_MAX_NODES.
error: could not copy file /home/runner/work/dealii/dealii/doc/doxygen/images/dgp_doesnt_contain_p.png to /home/runner/work/dealii/dealii/build/doc/doxygen/./deal.II/dgp_doesnt_contain_p.png
warning: Inheritance graph for 'SmartPointer' not generated, too many nodes (140), threshold is 50. Consider increasing DOT_GRAPH_MAX_NODES.
warning: Inheritance graph for 'Subscriptor' not generated, too many nodes (225), threshold is 50. Consider increasing DOT_GRAPH_MAX_NODES.
warning: Inheritance graph for 'Table' not generated, too many nodes (58), threshold is 50. Consider increasing DOT_GRAPH_MAX_NODES.
warning: Inheritance graph for 'Tensor' not generated, too many nodes (66), threshold is 50. Consider increasing DOT_GRAPH_MAX_NODES.
```
but we only change tests here.

**Comment by jpthiele** [comment]
All but the 'copy file' errors are suppressed for the actual check but the file is there.
So maybe some fluke. I think I had that happen once before and not changing anything but running it anew made that error go away.

**Comment by bangerth** [comment]
Yes, I've puzzled over this for one of my previous PRs as well. It must be spurious.

**Comment by masterleinad** [comment]
Seems to be fine now after rerunning. 🤷‍♂️

**Pull request merged**
