### PR TITLE
GitHub CI: update Ubuntu version

### PR DESCRIPTION
**Pull request by peterrum**
... since `ubuntu-18.04` is deprecated

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

**Comment by masterleinad** [comment]
Looks like this needs https://github.com/dealii/dealii/pull/14339 and thus needs to be rebased.

**Comment by peterrum** [comment]
@masterleinad Do you know which packages have to be loaded for nvvm? See: https://github.com/dealii/dealii/actions/runs/3250615681/jobs/5334525450.

**Comment by peterrum** [comment]
> Looks like this needs https://github.com/dealii/dealii/pull/14339 and thus needs to be rebased.

This is already part of the PR. These are new ones.

**Comment by masterleinad** [comment]
Looks like we need `cuda-11` for `gcc 9` instead.

**Comment by peterrum** [comment]
It seems it is not deprecated anymore!? Let's close this PR!

**Pull request closed without merging**
