### PR TITLE
Avoid comment from grid_in.cc showing up in doc of read_vtk.

### PR DESCRIPTION
**Pull request by simonsticko**
By changing the /// to // in the cc-file.

See end of https://www.dealii.org/current/doxygen/deal.II/group__simplex.html#ga058cd187cea704428ac1118410cd0fb8

### CODE REVIEW

**Review by peterrum — APPROVED** [review]

**Comment by bangerth** [comment]
Ha, that's pretty funny :-) Do we have other places where we use `////`?

**Comment by simonsticko** [comment]
> Ha, that's pretty funny :-) Do we have other places where we use `////`?

There are a lot repeated `/` in in grid_in.cc. Comments like this:
```
///////////////////Declaring storage and mappings//////////////////
```
It guess this could have been due to clang-format line breaking and by accident making it exactly 3 `/`.

**Comment by bangerth** [comment]
Want to write a patch that replaces these kinds of things by, say, `// ------------ text --------------` or similar?

**Comment by simonsticko** [comment]
Sure, I shall consult my regular expressions.

**Pull request merged**
