### PR TITLE
Enable cubic simplex output by DataOut

### PR DESCRIPTION
**Pull request by peterrum**

### CODE REVIEW

**Review by drwells — APPROVED** [review]

**Comment by tjhei** [comment]
some tests are broken...

**Review by kronbichler — APPROVED** [review]
OK once the test failure due to changed output (?) have been addressed.

**Comment by tjhei** [comment]
This deserves a change log entry.

**Comment by peterrum** [comment]
> OK once the test failure due to changed output (?) have been addressed.

Fix. I forgot that we classify lines both as simplices and hypercubes^^

> This deserves a change log entry.

Done.

**Review by kronbichler — APPROVED** [review]

**Pull request merged**
