### PR TITLE
Test all examples.

### PR DESCRIPTION
**Pull request by marcfehling**
- Ensure that there is a diff file for every example.
- Add remaining examples as `run_only` tests.

### CODE REVIEW

**Review by drwells — APPROVED** [review]

**Review by tjhei — APPROVED** [review]

**Comment by tjhei** [comment]
excellent!

**Comment by marcfehling** [comment]
We need to ensure that the remaining examples run in a reasonable time.

Let's check the runtimes of the new tests on the github runners before merging.

**Review by tamiko — APPROVED** [review]

**Review by tamiko — CHANGES_REQUESTED** [review]
We need to lower the computational cost of at least the following tests:
```
The following tests FAILED:
	 89 - examples/step-66.debug (Timeout)
	 96 - examples/step-71.debug (Failed)
	108 - examples/step-83.debug (Timeout)
```

**Comment by marcfehling** [comment]
> We need to lower the computational cost of at least the following tests:

I'll make some adjustments.

Those are the ones the github testers cover, but there are still tests with dependencies we won't run. Well I guess if we merge this at some point, that the regression tester will kindly remind us of the remaining examples :grin:

**Comment by tamiko** [comment]
@marcfehling Let me simply run it on the regression tester for the debian-13 variant as well.

**Comment by marcfehling** [comment]
There was a default parameter file missing for step-71. github testers pass now. I suggest to do the fine-tuning later.

**Review by masterleinad — APPROVED** [review]

**Review by tamiko — APPROVED** [review]
This adds 4 minutes to the total runtime of one regression tester configuration.

**Pull request merged**
