### PR TITLE
Failing test for mapping_fe_field with fe_bernstein

### PR DESCRIPTION
**Pull request by mtezzele**
I open this PR with a failing test. The combination MappingFEField and FE_Bernstein seems to have problems even with simple triangulations and small degree when FEValues performs do_reinit method. I can not figure out where is the problem and why it works using an FE_Q instead of an FE_Bernstein.

### CODE REVIEW

**Comment by mtezzele** [comment]
I also underline the presence of issue https://github.com/dealii/dealii/issues/941

**Comment by luca-heltai** [comment]
Since this is only a test, I'll go ahead and merge.

**Comment by bangerth** [comment]
Hm, this of course has the undesirable side effect of creating a test failure for all test results at http://cdash.kyomu.43-1.org/index.php?project=deal.II&display=project :-(

**Comment by luca-heltai** [comment]
But that's exacly what tests are for, right? If there is a bug in the library, a test should fail. And this is exactly what this test does: it exposes a bug....

I'm working on a fix...

**Pull request merged**
