### PR TITLE
cleanup typedefs in DataOut

### PR DESCRIPTION
**Pull request by tamiko**
The goal is to support (interpolated) coarser output of a solution with
distributed data structures. The subtle problem here lies in the fact that
we can not simply iterate on a (local) coarser level and output the
solution - we have to communicate the ghost layer to do the interpolation
first; secondly, we also have to create a partition on the desired coarser
level. But that pretty much sounds like multigrid!

So my idea is as follows: Suppose you have a distributed solution
`solution`. We can then create a (matrix free) multrigrid transfer as
follows:
```
unsigned int coarsening_steps = 2;
vector_type solution_vector;

MGConstrainedDoFs constrained_dofs;
MGTransferMatrixFree<dim, Number> transfer;

MGLevelObject<vector_type> output_vector;

const auto max_level = triangulation.n_global_levels() - 1;
const auto output_level = max_level - std::min(coarsening_steps, max_level);

constrained_dofs.initialize(dof_handler);
transfer.initialize_constraints(constrained_dofs);
transfer.build(dof_handler);
transfer.interpolate_to_mg(dof_handler, output_vector, solution_vector);
```
So, the only step left over is to actually output said level. For example
via
```
MyDataOut<dim> data_out;
data_out.attach_dof_handler(dof_handler);
data_out.add_data_vector(output_vector);
```
where `MyDataOut` is derived from `dealii::DataOut` and overrides the
`first_cell()` and `next_cell()` functions to iterate over a fixed level.

With the current functionality I think we can integrate this quite nicely.
The following might work:
 - [x] remove unnecessary `active_cell_iterator`s from `DataOut` and `DataOut_DoFData`
 - [ ] improve the `first_locally_owned_cell` and `next_locally_owned_cell`
       member functions to use
       `cell->level_subdomain_id() == triangulation.locally_owned_subdomain`
 - [ ] improve `ParallelDataBase<dim, spacedim>::reinit_all_fe_values` to
       initialize with a `DoFHandler::level_cell_iterator` if the current
       cell is not active.
 - [ ] change `get_function_values` (and similar) to work on level dofs
       instead of dofs if the cell is not active.

@kronbichler *ping*

### CODE REVIEW

**Comment by bangerth** [comment]
/rebuild

Looks good to me. Can you please move your list of things that need to be done to a separate issue (not a pull request). I have a few ideas that I'd like to state there.

**Comment by peterrum** [comment]
@bangerth This PR is actually closed (isn't it @tamiko?). We decided on proceeding with PR #9100 and there is also an issue #9099.

**Comment by bangerth** [comment]
Well, the PR is still open and has, what I think, useful stuff :-)

**Comment by bangerth** [comment]
I found #9099 later.

**Comment by peterrum** [comment]
If you want you can also check out the discussion in PR #9098 ;)

**Comment by tjhei** [comment]
data_out/data_out_08.debug:
```
/jenkins/workspace/dealii_PR-9096/tests/data_out/data_out_08.cc: In instantiation of ‘typename dealii::DataOut<dim>::cell_iterator FilteredDataOut<dim>::first_cell() [with int dim = 2; typename dealii::DataOut<dim>::cell_iterator = dealii::TriaIterator<dealii::CellAccessor<2, 2> >]’:
/jenkins/workspace/dealii_PR-9096/tests/data_out/data_out_08.cc:151:1:   required from here
/jenkins/workspace/dealii_PR-9096/tests/data_out/data_out_08.cc:73:49: error: no type named ‘active_cell_iterator’ in ‘class dealii::DataOut<2, dealii::DoFHandler<2, 2> >’
     typename DataOut<dim>::active_cell_iterator cell =
                                                 ^
/jenkins/workspace/dealii_PR-9096/tests/data_out/data_out_08.cc:73:49: error: no type named ‘active_cell_iterator’ in ‘class dealii::DataOut<2, dealii::DoFHandler<2, 2> >’
```

**Comment by bangerth** [comment]
@tamiko : Ping?

**Comment by tamiko** [comment]
@bangerth Back alive and kicking.

**Pull request merged**
