### PR TITLE
Adjust test output.

### PR DESCRIPTION
**Pull request by bangerth**
This test seems to provide different results depending on what version
of NETIS is being used. At least this is suggested by the fact that
the results from the official tester are different than the original
results as added by Denis Davydov. Use the values from the official
'tester' machine.

I've looked whether any of the other testers succeed with these
tests, but haven't been able to find any evidence that they
actually run these tests at all. The tests need METIS which
probably not a lot of people have installed. So it may simply
be that nobody but me actually tried to run these tests, and
that that is why they don't show up among the failing
tests for all of the other regression tester machines.

### CODE REVIEW

**Comment by davydden** [comment]
Didn't know that `metis` leads to different partition for different versions. 
Is there a way to have different output for different versions of `metis`?
which one do you use? 

I just re-run tests
```
$ ctest -R "sharedtria"
Test project /Users/davydden/libs-sources/deal.ii/builds/fe_enriched
    Start 562: sharedtria/dof_01.mpirun=3.debug
1/6 Test #562: sharedtria/dof_01.mpirun=3.debug ......   Passed    8.35 sec
    Start 563: sharedtria/dof_01.mpirun=3.release
2/6 Test #563: sharedtria/dof_01.mpirun=3.release ....   Passed    6.03 sec
    Start 564: sharedtria/dof_02.mpirun=3.debug
3/6 Test #564: sharedtria/dof_02.mpirun=3.debug ......   Passed    7.05 sec
    Start 565: sharedtria/dof_02.mpirun=3.release
4/6 Test #565: sharedtria/dof_02.mpirun=3.release ....   Passed    6.06 sec
    Start 566: sharedtria/tria_01.mpirun=3.debug
5/6 Test #566: sharedtria/tria_01.mpirun=3.debug .....   Passed    5.96 sec
    Start 567: sharedtria/tria_01.mpirun=3.release
6/6 Test #567: sharedtria/tria_01.mpirun=3.release ...   Passed    5.37 sec
```
and that's with metis `5.1.0.`

If one to keep only single output file, i would suggest to keep the one which corresponds to the most recent version, which is 5.1.0, AFAIK and try to update the tester machine to have the same.

**Comment by bangerth** [comment]
> Didn't know that |metis| leads to different partition for different
> versions.

In reality, I have no idea what causes this. I don't have an 
installation of METIS on this machine, but had PETSc download and 
install it as part of the PETSc installation. The version they chose to 
download is 5.0.2.

**Comment by davydden** [comment]
>In reality, I have no idea what causes this. I don't have an
>installation of METIS on this machine, but had PETSc download and
>install it as part of the PETSc installation. The version they chose to
>download is 5.0.2.

that must have been an old installation of PETSc. According to their bitbucket at the moment they build with 5.1.0.: https://bitbucket.org/petsc/pkg-metis/commits/all

can you try to re-build/upgrade PETSc to `3.6.1` on that machine?

**Comment by bangerth** [comment]
Yes, it was PETSc 3.4.4. I probably ought to do that. I'll eventually get to it.

**Comment by tjhei** [comment]
@bangerth you pushed this branch to dealii and not your own repo, can we delete it?

**Comment by bangerth** [comment]
Yes. How embarrassing. It was on my only clone whose origin is the main repository and I apparently didn't pay attention.

**Comment by bangerth** [comment]
Hm, I'm running Metis 5.1.0 now on my system and it also starts to fail the `metis/metis_{01,02,03,01a}` tests, *in addition* to the `sharedtria` tests. What to do in this case?

**Comment by bangerth** [comment]
For complete reference, the various `metis` tests work with Metis 5.0.2 on my machine (via PETSc 3.4.4) and fail with Metis 5.1.0 (via PETSc 3.6.1).

**Comment by davydden** [comment]
so does `sharedtria` tests fail for you on `5.1.0`? I suppose they also fail for you for `5.0.2`?

If `sharedtria` test would work for you for `5.1.0`, one could update other tests to comply with `5.1.0` and add a note that the output depends on a version of metis used.

Alternative is to encode metis version in tests output, something like `my-test.metis=true:510.mpi=3.output`

**Comment by tamiko** [comment]
> Alternative is to encode metis version in tests output, something like
> `my-test.metis=true:510.mpi=3.output`

"my-test.metis=5.1.0.mpirun=3.output" it is [1].

Best,
Matthias

[1]
http://dealii.org/developer/developers/testsuite.html#restrictfeature

**Comment by davydden** [comment]
> "my-test.metis=5.1.0.mpirun=3.output" it is [1].

it's a minimum version, not an exact match:
```
Furthermore, a test can be restricted to be run only for a specific minimum version of a feature being available being available. For example
category/test.with_trilinos=11.14.1.output
will only be run if (a) trilinos is available, i.e., DEAL_II_WITH_TRILINOS=TRUE and (b) if trilinos is at least of version 11.14.
```

perhaps one could distinguish between `trilinos=11.14.1` and `trilinos>11.14.1`?

**Comment by davydden** [comment]
for a reference, `metis/metis_{01,02,03,01a}` fail for me on OSX with `5.1.0` installed via `Homebrew`. According to PETSc bitbucket, they do not modify `5.1.0` much https://bitbucket.org/petsc/pkg-metis/commits/all so it shall be equivalent to the one installed by PETSc via `--download-metis`.

**Comment by tamiko** [comment]
@bangerth

> The tests need METIS which probably not a lot of people have installed.

The reason why simserv04 does not provide metis is the fact that the link interface still contains metis-4.

**Comment by tamiko** [comment]
*ups*

**Comment by bangerth** [comment]
I don't think I've quite understood what our test results mean:

* For @davydden, Metis 5.1.0 (i) works for the sharedtria tests, (ii) does not work for the metis tests, both using the output files currently in git

* For @bangerth, Metis 5.0.2 (i) works for the metis tests, (ii) does not work for the sharedtria tests.

* For @bangerth, Metis 5.1.0 *both* sets of tests fail currently. For example, for tria_01, I need these changes:
```
trunk/xx> diff -c ../dealii/tests/sharedtria/tria_01.with_metis\=true.mpirun\=3.output tests/sharedtria/tria_01.debug/mpirun\=3/output  
*** ../dealii/tests/sharedtria/tria_01.with_metis=true.mpirun=3.output  2015-08-21 14:43:32.821294904 -0500
--- tests/sharedtria/tria_01.debug/mpirun=3/output      2015-08-26 06:43:35.132173241 -0500
***************
*** 4,29 ****
   n_levels: 3
   n_global_levels: 3
  
! DEAL:0:2d::subdomains: 0 1 0 1 2 1 2 
  DEAL:0:3d:: locally_owned_subdomain(): 0
   n_active_cells: 15
   n_levels: 3
   n_global_levels: 3
  
! DEAL:0:3d::subdomains: 0 2 0 1 0 0 0 2 2 2 2 1 1 1 1 
  
  DEAL:1:2d:: locally_owned_subdomain(): 1
   n_active_cells: 7
   n_levels: 3
   n_global_levels: 3
  
! DEAL:1:2d::subdomains: 0 1 0 1 2 1 2 
  DEAL:1:3d:: locally_owned_subdomain(): 1
   n_active_cells: 15
   n_levels: 3
   n_global_levels: 3
  
! DEAL:1:3d::subdomains: 0 2 0 1 0 0 0 2 2 2 2 1 1 1 1 
  
  
  DEAL:2:2d:: locally_owned_subdomain(): 2
--- 4,29 ----
   n_levels: 3
   n_global_levels: 3
  
! DEAL:0:2d::subdomains: 0 1 0 2 2 1 1 
  DEAL:0:3d:: locally_owned_subdomain(): 0
   n_active_cells: 15
   n_levels: 3
   n_global_levels: 3
  
! DEAL:0:3d::subdomains: 0 1 0 2 0 0 0 2 2 1 1 2 2 1 1 
  
  DEAL:1:2d:: locally_owned_subdomain(): 1
   n_active_cells: 7
   n_levels: 3
   n_global_levels: 3
  
! DEAL:1:2d::subdomains: 0 1 0 2 2 1 1 
  DEAL:1:3d:: locally_owned_subdomain(): 1
   n_active_cells: 15
   n_levels: 3
   n_global_levels: 3
  
! DEAL:1:3d::subdomains: 0 1 0 2 0 0 0 2 2 1 1 2 2 1 1 
  
  
  DEAL:2:2d:: locally_owned_subdomain(): 2
***************
*** 31,41 ****
   n_levels: 3
   n_global_levels: 3
  
! DEAL:2:2d::subdomains: 0 1 0 1 2 1 2 
  DEAL:2:3d:: locally_owned_subdomain(): 2
   n_active_cells: 15
   n_levels: 3
   n_global_levels: 3
  
! DEAL:2:3d::subdomains: 0 2 0 1 0 0 0 2 2 2 2 1 1 1 1 
  
--- 31,41 ----
   n_levels: 3
   n_global_levels: 3
  
! DEAL:2:2d::subdomains: 0 1 0 2 2 1 1 
  DEAL:2:3d:: locally_owned_subdomain(): 2
   n_active_cells: 15
   n_levels: 3
   n_global_levels: 3
  
! DEAL:2:3d::subdomains: 0 1 0 2 0 0 0 2 2 1 1 2 2 1 1 
  
```

Can someone make sense of this? Does it mean that we don't just have differences between METIS versions, but also between platforms? Could someone else try?

**Comment by tjhei** [comment]
METIS 5.1.0 as part of petsc-3.6.0 produces the same diffs you get, @bangerth .

I assume METIS uses rand() somewhere and that differs between platforms/compilers/versions.

**Comment by tjhei** [comment]
Yep: https://stackoverflow.com/questions/31299159/metis-different-results-on-different-os

**Comment by bangerth** [comment]
Bummer. If the METIS people were any kind of responsible software maintainers then this would have been fixed a long time ago :-( 

We don't really have the luxury to pass that flag during compilation when using METIS via PETSc. What do we do? I feel tempted to simply say that the files that we need for the "official" tester are the ones that are checked in as the canonical `.output` file, and that variations for other platforms can be added if we can figure out the appropriate filename additions. What do others think?

(The patch as it currently stands works only for METIS 5.0.1. If we do merge anything, let me update the output to a more recent PETSc with METIS 5.1 at least.)

**Comment by tamiko** [comment]
> I feel tempted to simply say that the files that we need for the "official" tester are the ones that are checked in as the canonical .output file, and that variations for other platforms can be added if we can figure out the appropriate filename additions.

It might be finally time to think about multiple comparison files in test comparisons...

If it is just a platform problem, i.e., GNU/Linux versus Mac, we could use
```
   .compiler=Clang>=5.0.0.
   .compiler=Clang<5.0.0.
   .compiler=Clang=no.
```
for the time being.

**Comment by tjhei** [comment]
We used to have different output files for various OS and compiler versions in the old days (old testsuite) and it was a nightmare to maintain.

I vote for keeping it as simple as possible and use what the official tester wants. Instead of adding exceptions for different OS/compilers, make the tests more robust or just accept that they fail if you have an exotic configuration.

**Comment by tamiko** [comment]
But what should be the "official tester"? We by now have at least 2 different testing sites that I would consider "official".

@tjhei My idea is to just have multiple comparison files. A possibility is the following layout
```
test.cc
test.output/comparison1
test.output/comparison2
test.output/comparison3
```
<code>test</code> succeeds if the output is equal to one of the comparison files.

This would also greatly reduce the necessity for version constraints.

**Comment by tjhei** [comment]
> My idea is to just have multiple comparison files. test succeeds if the output is equal to one of the comparison files.

That is much better than trying to pinpoint specific platforms/library versions, neat idea. I am in favor of this solution as long as we use it sparingly.

Can we make it work without stuffing the files into a directory by adding something like ```alternative=1``` or something to the filenames?

**Comment by bangerth** [comment]
> But what should be the "official tester"? We by now have at least 2
> different testing sites that I would consider "official".

The advantage of 'tester' is that it runs the same configuration every 
time. If it produces one more failure for one run than for the line 
under it, you know that it's because the code changed not because the 
configuration changed.


> @tjhei <https://github.com/tjhei> My idea is to just have multiple
> comparison files. A possibility is the following layout
>
> |test.cc
> test.output/comparison1
> test.output/comparison2
> test.output/comparison3
> |

The problem we had previously was that we added files that then got out 
of date. Whoever changes a test, or changes code that is being tested, 
will likely only update one of the output files. We ended up with 
hundreds of files that were never exercised any more simply because you 
have no way of knowing whether any given file is ever used.

**Comment by bangerth** [comment]
On 08/26/2015 01:21 PM, Timo Heister wrote:
> Can we make it work without stuffing the files into a directory by
> adding something like |alternative=1| or something to the filenames?

I thought of simply naming them
   test.output.1
   test.output.2
So any of test.output* will match. As explained in the other post, I 
think this will lead to a situation where we end up with output files 
that are never exercised and that are out of date. This is what happened 
to us before after all.

**Comment by tjhei** [comment]
> As explained in the other post, I
think this will lead to a situation where we end up with output files
that are never exercised and that are out of date. This is what happened
to us before after all.

It also makes it very difficult to introduce or update tests, yes. But the same holds for abusing the conditions in the current system (e.g. macos=yes.metis<=5.0.output, etc.). I like the beauty of just having a list of outputs and passing if any output is identical. I would only use it for tests where we are not in control (metis rand() for example).

I see the following options:
1. Live with many failing tests on different machines.
2. Create a mess with conditions and version numbers (bad idea).
3. Make tests less rigorous (we have done this with SolverControl, but I struggle to see a good way of doing this for the metis tests except not producing any output).
4. Introduce alternative output (as described above).

**Comment by tamiko** [comment]
> The advantage of 'tester' is that it runs the same configuration every
time. If it produces one more failure for one run than for the line
under it, you know that it's because the code changed not because the
configuration changed.

I disagree. this does not imply any special "blessing" that distinguishes it
from the other testing sites. I do not want to have tests that are known to 
fail on every platform except for one machine with one configuration.

> The problem we had previously was that we added files that then got out
of date.

Previously we abused the mechanism to account for small differences in
round-off errors (because we did not had numdiff available).  Right now, the only
instances are:
```
./bits/find_cell_4.compiler=Intel=false.release.output
./bits/find_cell_4.compiler=Intel=true.release.output
./bits/find_cell_5.compiler=Intel=false.release.output
./bits/find_cell_5.compiler=Intel=true.release.output
./bits/find_cell_alt_4.compiler=Intel=false.release.output
./bits/find_cell_alt_4.compiler=Intel=true.release.output
./bits/find_cell_alt_5.compiler=Intel=false.release.output
./bits/find_cell_alt_5.compiler=Intel=true.release.output
./fe/abf_projection_01.compiler=Intel=no.release.output
./fe/abf_projection_01.compiler=Intel=yes.release.output
```
I'm not too terribly worried about this getting out of control if we add maybe a
dozen of simultaneous output overrides for sharedtria.

**Comment by tamiko** [comment]
> Can we make it work without stuffing the files into a directory by adding something like alternative=1 or something to the filenames?

This is kind of a problem. A directory is something that I can handle similarly to an output file throughout the cmake code (by not distinguishing between files and directories). The only logic that has to be improved is the comparison in <code>run_test.sh</code>. If we go for individual files I would have to introduce a completely reworked logic.

> I like the beauty of just having a list of outputs and passing if any output is identical. I would only use it for tests where we are not in control (metis rand() for example).

This is very much my thought.

**Comment by tamiko** [comment]
Further, this has the benefit that we could just remove the compiler match and compiler version constraint logic. (For features I'd like to keep the version comparison).

**Comment by tamiko** [comment]
Ah, and we could solve this opencascade iges test failure...

@tjhei @bangerth Did we come to a conclusion?

**Comment by bangerth** [comment]
Superseded by #1458, this time from a branch from my own repository.

**Pull request closed without merging**
