### PR TITLE
Disable a fallback option in the BatchOptimizer

### PR DESCRIPTION
**Pull request by jppelteret**
This is what is promised in the documentation, and I forgot to change the behaviour everywhere.

### CODE REVIEW

**Comment by jppelteret** [comment]
@tamiko FYI.

**Comment by jppelteret** [comment]
@Rombur I told you that I removed this fallback option, but it looks like I only did it in one out of two places. Oops!

**Comment by tamiko** [comment]
I guess this won't be seen by the CI at all (the header has a `DEAL_II_WITH_SYMENGINE` header guard.

**Comment by tamiko** [comment]
Indenting successful and serial compilation worked as well.

**Pull request merged**
