### PR TITLE
Remove void cast mpi

### PR DESCRIPTION
**Pull request by PapaKwansa**
I added [[maybe_unused]] command to replace the (void) x command
17247

### CODE REVIEW

**Comment by masterleinad** [comment]
Looks like you only want to keep https://github.com/dealii/dealii/pull/17503/commits/c57f127cde95f9ec93842d32e5a0e18d7950af87.

**Comment by marcfehling** [comment]
Your pull request contains more commits than you intended to.

In your deal.II folder, can you try the following:
```
git fetch upstream
git checkout remove_void_cast_mpi
git rebase upstream/master
git push -f origin remove_void_cast_mpi
```

**Review by tamiko — APPROVED** [review]

**Comment by tamiko** [comment]
@PapaKwansa You'll need to update your git configuration:
```
Invalid author 'Henry' without firstname and lastname

For possible solutions, consult the following page:
      https://github.com/dealii/dealii/wiki/Commit-authorship
```

**Review by masterleinad — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]

**Review by tjhei — APPROVED** [review]

**Pull request merged**
