### PR TITLE
Fix wrong reference to variable in test.

### PR DESCRIPTION
**Pull request by bangerth**
This fixes @tjhei's comment in #1909 post-merge.

### CODE REVIEW

**Comment by tjhei** [comment]
As I said, I would prefer we do the same thing in the test that we use in the code in fe/ which is:
```
t.reinit(2,3);
t.fill(numbers::signaling_nan<double>());
```
and not what you do here. See https://github.com/tjhei/dealii/commit/29428e18219a17337a8be9fa03932274a044e1da

**Comment by bangerth** [comment]
Hm, you're right -- I'm calling the wrong constructor :-(

I'll get back to this.

**Comment by bangerth** [comment]
OK, I think I finally have this right...

**Comment by tjhei** [comment]
Yes. :-)

**Pull request merged**
