### PR TITLE
Save solution time into tecplot ascii files for animating time depend…

### PR DESCRIPTION
**Pull request by cpraveen**
Transient data can be animated in tecplot if we save solution time into the tecplot files. This can be used as

      DataOutBase::TecplotFlags flags(NULL, NULL, solution_time);
      data_out.set_flags (flags);
      data_out.write_tecplot (output);

If you have more strands, the ```strand_id``` must be given as last argument to the ```TecplotFlags``` constructor.

### CODE REVIEW

**Comment by cpraveen** [comment]
I closed my old pull request https://github.com/dealii/dealii/pull/1454 since it was messed up and opened this new one.

**Comment by tjhei** [comment]
Sorry to bring this up again. Can you explain to me how you would use different strand ids?

**Comment by cpraveen** [comment]
I have not used multiple strands myself, so what I am saying is my interpretation from reading the tecplot manual. If you have, e.g., two subdomains, you can save the solution of the two domains with different zone names into the tecplot files. But you must assign one strandid for domain 1 and another for domain 2. Then tecplot knows which zones represent which domain and can then interpolate in time for animation.

**Comment by cpraveen** [comment]
This page has some discussion on this http://www.tecplot.com/blog/2011/01/06/making-the-most-of-your-time/

**Comment by tjhei** [comment]
My understanding is that these IDs only matter if you have more than one zone in a single file (what we don't support). From the link it also looks like you an assign/overwrite the ID in the GUI.

Considering the reasons above and because you have not tested the feature, I don't see why we should export anything but strandid=1. Or do you disagree? If you feel strongly about it, we can leave it in of course.

**Comment by cpraveen** [comment]
If you set the strandid in the tecplot file, then you dont need to use the gui. All zones need not be in the same file. Then tecplot uses the strandid to get all the zones that represent the same solution but at different times. 

Anyway, since it is not clear how to use multiple strands, I have removed it and updated the pull request. Now you can only set the solution time.

**Comment by bangerth** [comment]
Great, thanks. I've merged this so we can move forward. Can you (in a separate pull request) add a sentence to `doc/news/changes.h` that lists the new flag?

**Pull request merged**
