### PR TITLE
FEFieldFunction: Detect case when some points were not found

### PR DESCRIPTION
**Pull request by kronbichler**
Fixes failing test https://cdash.43-1.org/test/5908767
Follow-up to #11276.

### CODE REVIEW

**Review by peterrum — APPROVED** [review]

**Comment by kronbichler** [comment]
I have a few test failures in other `fe_field_function` tests that I need to investigate tomorrow morning, so let us wait with merging until then.

**Comment by kronbichler** [comment]
It turns out that I had forgotten about the case where multiple points sit on the same cell - fortunately, we already have the infrastructure for a simple solution by returning the full search result including invalid points.

**Review by luca-heltai — APPROVED** [review]

**Comment by peterrum** [comment]
@kronbichler 

```
The following tests FAILED:

	2219 - numerics/generalized_interpolation_05.debug (Failed)
	2251 - numerics/generalized_interpolation_04.debug (Failed)
	2265 - numerics/generalized_interpolation_02.debug (Failed)
```

**Comment by kronbichler** [comment]
The test failures of `generalized_interpolation` are kind of annoying. They all fail for similar reasons: For `FE_RaviartThomas<2>(2)` we get points that happen to be outside the domain by roundoff errors, i.e., less than 1e-15 - that is enough for the point search to fail. I do not know whether we did not notice that before #11276, but it seems that the test itself is brittle. I would vote to ignore the RT(2) and Nedelec(2) elements from it - maybe @tamiko who wrote that in 2017 recalls what should happen here?

**Comment by kronbichler** [comment]
I looked more into this - I suggest we remove the quadratic Nedelec and Raviart-Thomas cases for now because the evaluation at the boundary/slightly outside of the domain with the generalized interpolation is somewhat of a special case, and needs more care after the release. On the other hand, the error message returned by `FEFieldFunction` now is useful for the release.

**Review by peterrum — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]
Looks good to me.

**Pull request merged**
