### PR TITLE
Fix missing call to update_cell_relations()

### PR DESCRIPTION
**Pull request by elauksap**
This fixes the error mentioned [here](https://github.com/dealii/dealii/pull/11515#issuecomment-770244795).

@peterrum

### CODE REVIEW

**Review by peterrum — APPROVED** [review]

**Comment by peterrum** [comment]
Thanks!

**Comment by elauksap** [comment]
Thank you @peterrum, sorry for the bug!

**Comment by peterrum** [comment]
> sorry for the bug!

Bugs are part of the job of a developer ;) You don't want to know how often I had to fix my own typos and bugs!

**Comment by peterrum** [comment]
```
The following tests FAILED:

	  6 - p4est.debug (Failed)

Errors while running CTest
```

**Pull request merged**
