### PR TITLE
Fix bug in FEFaceEvaluationSelector::process_and_io

### PR DESCRIPTION
**Pull request by peterrum**
in reference to https://github.com/dealii/dealii/pull/10809#issuecomment-672926930

### CODE REVIEW

**Comment by drwells** [comment]
Is there any sensible comment that you could add to this to explain the very long check?

**Comment by peterrum** [comment]
@drwells Done!

**Comment by drwells** [comment]
I think you rebased but didn't add the comment.

**Comment by peterrum** [comment]
Oops. But now!

**Pull request merged**
