### PR TITLE
deprecates static support_distributed_data member of vector declarations

### PR DESCRIPTION
**Pull request by koecher**
Deprecates the `static const bool supports_distributed_data` member. This field should not be used and should be removed in a future release.
Instead of using this member, the vector type trait `is_serial_vector< VectorType >::value` delivers the information about the support for distributed storage.

### CODE REVIEW

**Comment by koecher** [comment]
ops, sorry the error is
`vector.h:175:49: error: expected ‘;’ at end of member declaration
   static const bool supports_distributed_data = false DEAL_II_DEPRECATED;`
Does anyone know how to deprecate a member variable correctly?

**Comment by drwells** [comment]
I believe that the correct way to do this is to write

```cpp
  static const bool supports_distributed_data DEAL_II_DEPRECATED = false;
```

i.e., the deprecation attribute should go before the definition part.

**Comment by koecher** [comment]
Yes looks good, but the compilations still runs. (I've missed the point that there is an initialization).

**Comment by davydden** [comment]
> Yes looks good, but the compilations still runs

you can already push it here so that the tester is busy running as well...

**Comment by drwells** [comment]
While this has the right result when we compile it, it confuses doxygen greatly:

screenshot

**Comment by drwells** [comment]
I am not really sure how to fix doxygen's output here. Another thing to do is put the note in the `deprecated` section.

**Comment by bangerth** [comment]
doxygen has a tag for this: `@deprecated`. Let's put this into the documentation. We can then, in `doc/doxygen/options.dox.in` define `DEAL_II_DEPRECATED` to the empty string. This way doxygen doesn't see the annotation in the code, only in the comments.

**Comment by koecher** [comment]
@drwells it seems that there is (unfortunately) a miss of a doxygen `@enddeprecated` (does not compile correctly for me)

@bangerth I've putted a `@deprecated` and an additional note section with a nested `@code` section, since the type trait is something new.

The only solution to this (which I see), is to remove the hole `@note` section and put it as one-line comment using `<code>...</code>`. At least on my notebook, the result for such an approach looks acceptable. Any better ideas?

**Comment by bangerth** [comment]
`@deprecated` starts a paragraph that explains the deprecation. There is no `@enddeprecate` because it really is only a single paragraph.

See https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmddeprecated

So if you take the newline after `@deprecate` away in your patch, then it should come out alright.

**Comment by drwells** [comment]
I think the problem @koecher described is this:

deprecat

namely the black side bar ends and it looks a bit odd. I don't think that there is a way to put a code block in a deprecation block, so we should just use `<code>...</code>` unless someone can find a better alternative.

what I wrote should read 'the type trait value', but that is a seperate problem.

**Comment by bangerth** [comment]
Yes, moving the code inline seems like the right way to go.

**Comment by drwells** [comment]
@koecher Could you please also make the change @bangerth suggested to `doc/doxygen/options.dox.in`? Otherwise this is done.

**Comment by koecher** [comment]
@bangerth: I do not understand what you want to place in `doc/doxygen/options.dox.in`. Now there is only an oneline deprecation string, which is parsed correctly on my local machine.

**Comment by drwells** [comment]
@koecher All that @bangerth requested, if I understand correctly, is to add one line to the file `doc/doxygen/options.dox.in`:

```sh
PREDEFINED = DOXYGEN=1 \
             DEBUG=1 \
             DEAL_II_USE_MT_POSIX=1 \
             DEAL_II_WITH_ARPACK=1 \
             [...]
             DEAL_II_DISABLE_EXTRA_DIAGNOSTICS= \
             DEAL_II_DEPRECATED = \ # <--- add this line, setting the macro equal to one space
             DEAL_II_P4EST_VERSION_GTE=1 \
             DEAL_II_TRILINOS_VERSION_GTE=1
```

my copy of doxygen needs this to render things correctly.

**Comment by bangerth** [comment]
Yes, correct. The suggestion to let doxygen remove `DEAL_II_DEPRECATED` (by defining it to the empty string whenever doxygen runs) was to address the problem with the rendering reported by @drwells in a comment further up.

**Comment by koecher** [comment]
@bangerth @drwells alright, I've added this to the last commit.
Since this commit addresses a problem not belonging directly to this PR, shall I squash the 2 commits together, or not?

**Comment by bangerth** [comment]
It's ok as is with the two commits.

OK to merge once the tester is happy with it.

**Comment by bangerth** [comment]
Thanks, by the way!

**Comment by koecher** [comment]
You are welcome.

**Pull request merged**
