### PR TITLE
update clang-format infrastructure to version 11

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Comment by tamiko** [comment]
@masterleinad *ping* Mind to run `compile_clang_format` on your epicly old glibc system and send me the binaries via e-mail? :smiley_cat:

**Comment by marcfehling** [comment]
Related to #11106 and #11108.

**Comment by tamiko** [comment]
@luca-heltai *ping* Mind to run compile_clang_format (on this branch) on your mac? (ideally so that the resulting binary runs on any 64bit intel Mac)

**Comment by tamiko** [comment]
Part of #11108 now

**Pull request closed without merging**
