### PR TITLE
Add static member data for SymmetricTensor rank.

### PR DESCRIPTION
**Pull request by jppelteret**
This is consistent with what is done for the `Tensor` class.

### CODE REVIEW

**Comment by kronbichler** [comment]
It's easy enough to just scroll through the same pattern... ;-)

**Comment by jppelteret** [comment]
I was just surprised, because your feedback took less time than it took me to write a comment and add a label to another PR 😄

**Comment by kronbichler** [comment]
It must be because our locations are reasonably close geographically. German internet infrastructure would allow for that over longer distances... :smile:

**Comment by jppelteret** [comment]
Hmm... these 3 tests fail:
```sh
The following tests FAILED:
	258 - dofs/interpolate_q_system_mixed_01.debug (Failed)
	1590 - grid/intergrid_constraints.debug (Timeout)
	2542 - bits/step-15.debug (Failed)
Errors while running CTest
```
I think that this branch is based this off an old `master`. Should I rebase and run the tests again?

**Comment by bangerth** [comment]
Yes, let's err on the safe side -- if you could rebase, we could be sure.

**Pull request merged**
