### PR TITLE
Fix call to compress in reinit of Trilinos sparse matrix

### LINKED ISSUE #661: trilinos/assemble_matrix_parallel_01 fails
The trilinos/assemble_matrix_parallel_01 test currently fails. We call
```
  test_matrix.reinit (reference_matrix);
```
which ends up here:
```
void
  SparseMatrix::reinit (const SparseMatrix &sparse_matrix)
  {
    if (this == &sparse_matrix)
      return;

    column_space_map.reset (new Epetra_Map (sparse_matrix.domain_partitioner()));
    matrix.reset ();
    nonlocal_matrix_exporter.reset();
    matrix.reset (new Epetra_FECrsMatrix
                  (Copy, sparse_matrix.trilinos_sparsity_pattern(), false));
    if (sparse_matrix.nonlocal_matrix != 0)
      nonlocal_matrix.reset (new Epetra_CrsMatrix
                             (Copy, sparse_matrix.nonlocal_matrix->Graph()));
    else
      nonlocal_matrix.reset();

    compress(VectorOperation::insert);                // <--------- TROUBLE
  }
```
I suspect that we don't actually need to call compress here because we just copy stuff. If anything, maybe we should at one point enforce that one calls `compress` on the source matrix. In any case, the call fails with the exception
```
--------------------------------------------------------
An error occurred in line <1012> of file </u/bangerth/p/deal.II/1/dealii/source/lac/trilinos_sparse_matrix.cc> in function
    void dealii::TrilinosWrappers::SparseMatrix::compress(dealii::VectorOperation::values)
The violated condition was: 
    ((last_action == Add) && (operation!=::dealii::VectorOperation::insert)) || ((last_action == Insert) && (operation!=::dealii::VectorOperation::add))
The name and call sequence of the exception was:
    ExcMessage("Operation and argument to compress() do not match")
Additional Information: 
Operation and argument to compress() do not match
--------------------------------------------------------
```
but I don't feel confident in my ability to understand what is happening in all of these `reset` calls and copy constructors.

@kronbichler : Can you help out?

### PR DESCRIPTION
**Pull request by kronbichler**
Fixes #661

### CODE REVIEW

**Comment by kronbichler** [comment]
It turns out that this was easy to fix: We just forgot to set the flag last_action appropriately (this is what we do some other reinit() methods).

**Comment by tjhei** [comment]
I don't understand why this generated an error though. ```last_action``` should be ```zero``` from the constructor or the last call to ```compress()``` unless somebody forgot to call ```compress()``` before calling ```reinit()```, or not?

**Comment by tjhei** [comment]
But I don't see any harm in accepting this PR of course (we should add an ```assert_is_compressed()``` at the beginning of reinit once that exists down the road).

**Comment by kronbichler** [comment]
The reason for the error is how tests/trilinos/assemble_matrix_parallel_01.cc works: It runs through several iterations and the test_matrix that runs the previously offending code still holds values from the assembly that was done before (and is remembered by last_action). Unless we set 'last_action = Zero' at the end of compres() because it leaves the matrix unmodified, manually re-setting the value is necessary and indeed done in the reinit() methods.

**Comment by bangerth** [comment]
@tjhei: If you're happy with it, feel free to merge.

**Comment by bangerth** [comment]
And @kronbichler : Thanks for fixing it so quickly!

**Comment by tjhei** [comment]
Sorry, I still don't understand. I think the test is broken because we forget to call ```compress()``` at the end of assembly. It doesn't make sense to do:
```
matrix.reinit(...);
matrix.add(....);
matrix.reinit(...);
```
and it is correct that this triggers an exception.

So I would be in favor of fixing the test instead of this patch. Or am I missing something?

**Comment by kronbichler** [comment]
@tjhei you are right that the test should call compress(), even though the results of the test are fine because compress() does not do anything when not used with MPI (at least for the way we initialize the Epetra_CrsMatrix objects). The related test assemble_matrix_parallel_02.cc that does run in parallel indeed includes the compress() calls.

However, the original reason for fixing the source code is still there, even though this particular test should not necessarily trigger it: No matter in which state I leave a matrix, a call to reinit() should wipe it all away and let me start anew. This is what we could not guarantee before.

**Comment by tjhei** [comment]
> No matter in which state I leave a matrix, a call to reinit() should wipe it all away and let me start anew. 

I understand the reasoning but I prefer code that helps me find bugs in the parallel case. I wasn't aware that you don't require compress() if you are running with one MPI rank.

Should we merge as is and put this on our list for the future instead? Or what do you suggest we do?

**Comment by guidokanschat** [comment]
I'm with Martin, that reinit should clean the matrix no matter what. Throwing an error message that the matrix was not compressed just before deleting it seems unusual, since the error becomes obsolete within the function. Therefore, I'm for merging.

**Comment by tjhei** [comment]
Okay, go ahead and merge, if you agree Martin.

**Comment by kronbichler** [comment]
The reason why we do not force compress() with one processor is that the way we use Epetra_CrsMatrix does not need it - it writes the data directly into the correct matrix positions and does not need to do anything. Things would be different if we allowed matrices to set their sparsity pattern while writing entries.
So I agree that we should look into this once more when we address the check assert_is_compressed() state as discussed in #655.

**Pull request merged**
