### PR TITLE
Remove (empty) default constructor for ArrayView

### PR DESCRIPTION
**Pull request by masterleinad**
All the member variables for `ArrayView` are currently declared `const`. Hence, an empty constructed object can never point to anything useful.

### CODE REVIEW

**Comment by bangerth** [comment]
I suspect that we don't want `std::vector<ArrayView>` to work, or similar. Or do we?

**Comment by davydden** [comment]
./run-tests

**Comment by drwells** [comment]
I think that we should keep this so that `ArrayView`s are default constructible. It might be useful to put them in containers later on.

**Comment by masterleinad** [comment]
> It might be useful to put them in containers later on.

That does not require a default constructor necessarily (only if you want the objects to be default initialized).

I am not opposed to allow to modify the member variables if we decide to do so. I am just not happy that we are somewhere in between by having a constructor that always creates an object that can never be used.

**Comment by drwells** [comment]
Its been merged, but I checked and this is okay. We can do things like
 
```cpp
  double a = 0.0;
  std::array<ArrayView<double>, 2> views2 {{{&a, 1}, {&a, 1}}};
```

which is, I think, the extent of what makes sense to do with this class.

**Pull request merged**
