### PR TITLE
Doxygen: Ensure that opening and closing glossary quotes are on the same line

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Comment by tamiko** [comment]
This should hopefully fix some of the tutorial steps such as step-1: https://www.dealii.org/current/doxygen/deal.II/step_1.html

There are unfortunately a few more places with opening and closing quotes on different lines. These here were just easy to find...

**Review by peterrum — APPROVED** [review]

**Comment by tamiko** [comment]
This fixed some of the tutorial steps: https://www.dealii.org/developer/doxygen/deal.II/step_1.html

I wll apply this (and all related fixes) for the documentation and regenerate the documentation for 9.3.3

**Comment by bangerth** [comment]
The command
```
egrep -r '\@ref [^\"]*\"[^\"]+$' include/ examples/
```
suggests that you found all places of this kind.

**Comment by bangerth** [comment]
@tjhei used to have a script that prevented exactly this from happening. I thought it was part of the indentation checker, but that doesn't appear to be the case any more. I don't remember what happened to it.

**Comment by tjhei** [comment]
No, this is one of the manual release steps using a python script.

**Pull request merged**
