### PR TITLE
CMake: require MPI 3.0

### LINKED ISSUE #13447: drop MPI 2.x support
I would like to suggest that we drop MPI 2.0 support. The 3.0 standard was released in 2012.

I have the following reasons:
- We are not testing MPI 2.0 (I am not even sure if we compile)
- It is difficult to go back that far (OpenMPI 1.8.x and MPICH 3.0.x are both MPI 3.0 and from 2015/2016)
- I would like to support big messages and large IO and that does not work correctly with MPI 2.0 (``create_mpi_data_type_n_bytes``)
- OpenMPI devs already call 1.10 and older "ancient" on their website :-)

Thoughts?

### PR DESCRIPTION
**Pull request by tamiko**
Closes #13447

### CODE REVIEW

**Comment by tamiko** [comment]
@tjhei Something like this should do the trick.

**Review by kronbichler — APPROVED** [review]

**Comment by kronbichler** [comment]
I think we have a few places where we choose different implementations in case there is no MPI-3 support.

**Comment by tjhei** [comment]
Yes, I am happy to let my students take care of those.

**Review by tjhei — APPROVED** [review]

**Comment by tjhei** [comment]
Thank you, @tamiko

**Pull request merged**
