### PR TITLE
Use American English spelling.

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Comment by jppelteret** [comment]
Whoops. [Did I do that?](https://www.youtube.com/watch?v=xz3ZOoYSMuw)

**Comment by bangerth** [comment]
I wasn't going to call anyone out by name, but it's curious how many places I found in step-44 ;-)

**Comment by jppelteret** [comment]
I guess you all had pretty low standards back in 2012! ;-)

**Comment by drwells** [comment]
That's a lot of zees (not zeds) 🇺🇸 :)

**Comment by jppelteret** [comment]
Some patriot should offer to set up a freedom-bot to target my PR's and to prevent me from using _þe Olde English_!

**Comment by drwells** [comment]
Typically the old informal second person pronoun 'Ye' is used there, but I appreciate your use of a good old fashioned thorn :)

If I had more time I would set up a bot with exactly 1776 grammatical checks that launches a bald eagle upon successful completion, but, alas, I need to apply for jobs this fall :(

**Comment by bangerth** [comment]
Oh, @jppelteret is South African. He won't feel the sting of your 1776 barb!

**Comment by drwells** [comment]
I don't mean to sting anyone. Its just a very free number :)

**Comment by jppelteret** [comment]
@drwells I was somewhat surprised to discover that the whole expression as a sign of old English [might be bogus](http://io9.gizmodo.com/ye-olde-is-fake-old-english-and-youre-mispronouncing-1679780566). Regardless, I doubled down with the use of thorn... You know what they say: "When you're in for an original Queen's coinage penny, you're in for a British monetary pound sterling."

Will this AE/BE back and forth ever get old? :-)

**Comment by drwells** [comment]
I've heard that one before.

Honestly, I don't really notice the British English. I think that using a zee (not zed) is more common in spelling those words over on this side of the pond but I see it spelt (spelled?) both ways.

**Pull request merged**
