### PR TITLE
Move a reference to references.bib.

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Comment by tjhei** [comment]
travis complains:
```
/home/travis/build/dealii/dealii/include/deal.II/numerics/error_estimator.h:50: warning: unable to resolve reference to `KGZB83' for \ref command
```
I think you need to use ``@cite``

**Comment by tjhei** [comment]
By the way, I love that we check doxygen now as part of the CI. Thanks, @masterleinad . :+1:

**Comment by bangerth** [comment]
Done.

**Comment by masterleinad** [comment]
`clang-format` still doesn't like the formatting. :slightly_smiling_face:

**Comment by bangerth** [comment]
Good grief. How many ways are there to get this wrong? :-(

**Pull request merged**
