### PR TITLE
Delete default constructor FESystem

### PR DESCRIPTION
**Pull request by peterrum**
As requested in https://github.com/dealii/dealii/issues/11964#issuecomment-808898044.

### CODE REVIEW

**Review by masterleinad — COMMENTED** [review]
Alternatively, you might just check for `sizeof...(FEPairs)>0` in the `FESystem(FEPairs &&...)` constructor. I think I like that better since it's more concise.

**Comment by bangerth** [comment]
I like the deleted default constructor better. If someone does what happened in the case where this was found, the intention was almost certainly not to create an `FESystem` with zero components -- in other words, there was no intention to call this constructor with a zero-element list, and it would be confusing to see the error message come from that place.

**Comment by bangerth** [comment]
It might make sense to *also* put a `static_assert` into the variadic constructor. It will never trigger but serve as useful documentation. It would certainly make sense to `Assert` that the `std::initializer_list` constructor gets a non-empty list. But that is all separate from the current patch.

**Review by marcfehling — APPROVED** [review]

**Pull request merged**
