### PR TITLE
Improve 2d transfinite guess

### PR DESCRIPTION
**Pull request by drwells**
This is a followup to #5755. The bug is the following: we assume, when computing chart points, that if we have eight surrounding points then we can form initial guesses of chart points by assuming we have the eight vertices of a cube. This doesn't work well in 2D: in the case pointed out on the forum the initial guess was sufficiently inaccurate that we could not converge at all.

This PR makes things more robust and adds a 2D-specific initial guess that performs much better.

@kronbichler I don't quite understand why you added the eight point optimization. The main time this is called we will have the standard (twenty-something) number of bounding points for a hex; is this right?

### CODE REVIEW

**Comment by kronbichler** [comment]
> @kronbichler I don't quite understand why you added the eight point optimization. The main time this is called we will have the standard (twenty-something) number of bounding points for a hex; is this right?

There are two cases: One is when we refine the mesh, where we indeed have the 26 surrounding points of a cell. The second case is when we evaluate the mapping support points of `MappingQGeneric` where we compute all new points from the eight vertex points, since the transfinite interpolation can handle all intermediate points properly. That case was showing up much more prominently in my profiles and it appeared to be a simple solution. The optimization should not do much in the other case. If we say that all the whistles and bells for finding the initial guesses are too messy, I am not insisting in keeping that optimization in, because it is around a factor of 2-3 for the `pull_back` operations, and those are not always the dominating part either.

**Comment by drwells** [comment]
@kronbichler I think the optimizations are worth keeping. The only thing I would like to change is adding some way to differentiate between the eight vertices of a cube and the eight surrounding points on a hex face.

The tester's output EPS file is about 1% off from mine. I'll try to fix this later today.

**Comment by kronbichler** [comment]
> The only thing I would like to change is adding some way to differentiate between the eight vertices of a cube and the eight surrounding points on a hex face.

I see and agree that that's definitely worth having and not done yet. Your patch already does revert at the position this fails, so we might want to replace the distinction into `dim==2` or `dim==3` to detect the two situations from what the fourth point gave, i.e., whether `x_4-x_0` is almost orthogonal to `x_1-x_0` and `x_2-x_0` or almost collinear with `x_2-x_0`. Do you think that would make sense?

**Comment by drwells** [comment]
I implemented an orthogonality check.

I reran the transfinite tests and it looks like none of them ever get to 

https://github.com/dealii/dealii/pull/5761/files#diff-98c525c75b4c0a26fe6edf5026313894R1952

@kronbichler would you mind profiling these changes? Alternatively, I can do it if you can send me your code.

I don't think that the latest round of changes fixes the new test: I am surprised that something as innocuous as saving a circular grid to VTK can lead to differences as large as 10% in the computed solution.

**Comment by drwells** [comment]
The failing serial test is the test that I added, in debug mode. The bug is *probably* unrelated to the current change and is surprisingly subtle (I am still trying to figure out what is going on). It looks like some manifold descriptions are propagated incorrectly but only with certain compilers.

Here is what I get when I compile with my local copy of GCC 4.8.4:
center-gcc48
which, I believe, matches the output on the serial tester, and with GCC 7.2:
center-gcc7

Notably, I can only reproduce the failure with my at-home install of GCC 4.8: the copy of GCC 4.8 on my red hat work station does not exhibit the wobbles (i.e., it matches the GCC 7.2 output).

**Comment by drwells** [comment]
OK, that was irritating: there was a `abs` (*not* `std::abs`) in some logic that determined whether or not to set a manifold id that, of course, defaulted to the standard C `int abs(int)` 😭

**Comment by drwells** [comment]
Whats even worse is that newer versions of GCC seem to have leaked `std::abs` into the global namespace.

**Comment by kronbichler** [comment]
I had a look at my test program and it seems to have seen some slowdown with this PR. Here are three calls, first on master:
```
Level 3
Time refine grid: 0.33965
Time boundary conditions: 0.254398
Time integrate difference 3.61238
Level 4
Time refine grid: 3.42111
Time boundary conditions: 1.02849
Time integrate difference 29.2927
```
then with this PR:
```
Level 3
Time refine grid: 0.340383
Time boundary conditions: 0.252121
Time integrate difference 3.73823
Level 4
Time refine grid: 3.3144
Time boundary conditions: 1.03073
Time integrate difference 29.2317
```
The "integrate difference" part creates the mapping support points on the whole grid for `fe_degree=4`, `mapping_degree=6`, "boundary conditions" does the same on the boundary, whereas "refine grid" does the 26-point average calls. The timings have not changed much, so I think it is safe to apply this patch. I have not had the time to look into how often we call the `compute_transfinite_interpolation` function now, but I guess it has not changed much.

**Comment by drwells** [comment]
Thank you for the review. At least the slowdowns are small.

I suspect that the slight slowdown is due to the differentiation between the 2D and 3D cases, i.e., we compute an angle that we did not before.

**Comment by kronbichler** [comment]
It might also be simply jitter, as the timing differences are not really conclusive and in favor of one implementation in all cases, 3 are faster with the new code, 3 are faster with the old one.

**Comment by drwells** [comment]
Adding the quadrilateral case seems to help a lot: I see a 10% improvement in my polar benchmark.

**Comment by kronbichler** [comment]
Great work! So we have the new test and the improved fix in place and are ready to merge. I will wait for a few hours (or until tomorrow morning) before pulling the trigger, in case someone else wants to add something.

**Comment by drwells** [comment]
Thanks :)

**Pull request merged**
