### PR TITLE
Add operator assigning a scalar to a Tensor<0>.

### PR DESCRIPTION
**Pull request by jppelteret**
Relates to #5829.

### CODE REVIEW

**Comment by masterleinad** [comment]
That looks reasonable for fixing #5829. What's the reason for the `WIP` label?

**Comment by jppelteret** [comment]
@masterleinad Thanks, I forgot to remove the label after adding the other two commits.

**Comment by masterleinad** [comment]
Just to be sure: Does this fix any issue you were having or is this just an attempt to fix #5829?

**Comment by jppelteret** [comment]
Both.

**Comment by jppelteret** [comment]
I don't have `icc` to test this against, but it for sure fixes some other tests that I'll be committing at a later date.

**Comment by masterleinad** [comment]
Let's merge then.

**Pull request merged**
