### PR TITLE
Periodicity constraints: skip artificial cell face dofs

### PR DESCRIPTION
**Pull request by tileuzhan-mukhamet**
See  #17917

### CODE REVIEW

**Comment by peterrum** [comment]
Could you add a test how one can trigger this issue. I had also problems with PBC and artificial cells, see https://github.com/dealii/dealii/pull/16632.

**Review by kronbichler — APPROVED** [review]
Thank you for adding the test.

**Comment by kronbichler** [comment]
Can you please run the `./contrib/utilities/indent` script again, such that it runs on the test case, and push the updated test file again?

**Review by peterrum — APPROVED** [review]

**Pull request merged**
