### PR TITLE
github: run all github actions on draft PRs as well

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Review by marcfehling — APPROVED** [review]
Looks good to me!

Alternatively, we could store the result of the conditional once as a [`env` variable](https://docs.github.com/en/actions/learn-github-actions/variables) and refer to it on all runners. We would need to define it in each yaml file I believe. But I don't think it's worth the effort here.

**Review by masterleinad — APPROVED** [review]

**Comment by marcfehling** [comment]
Defining [github actions variables on the repository level](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository) would be an elegant solution. This would not require to modify the repository itself if we want to run our CI on draft PRs. What do you think @tamiko?

**Comment by tamiko** [comment]
@marcfehling I think this would be the better solution. I'll have a look at it over the coming days! :-)

**Review by tjhei — APPROVED** [review]

**Comment by tamiko** [comment]
Let us merge for now - I'll come up with a fancier solution prior to when we need it again :-)

**Pull request merged**
