### PR TITLE
cmake: add an option to disable SIMD in VectorizedArray

### PR DESCRIPTION
**Pull request by davydden**

### CODE REVIEW

**Comment by davydden** [comment]
It is rarely needed, but I also don't see a reason for hacking deal.II every time such need arises. I am certainly not the first one who would like to do this 😄

**Comment by bangerth** [comment]
Can't you just do this by doing
```
  export CXXFLAGS="-march=something that doesn't support SIMD"
```
?

**Comment by davydden** [comment]
I guess I could. 

since there is more than one developer who does not see the need in this feature, I guess I will just close the PR.

**Comment by tamiko** [comment]
We have reserved `DEAL_II_WITH` for (external) features and `DEAL_II_HAVE` for configuration options such as SIMD support. I am not a huge fan of promoting something to `DEAL_II_WITH` (and showing up in the summary) if it does not toggle some internal feature (such as 64 bit support, complex values, external libraries, etc.)

That said, we already have two configuration options `DEAL_II_HAVE_SSE2`, and `DEAL_II_HAVE_OPENMP_SIMD`. You can simply set them on the command line overriding the autodetection:
```
cmake -DDEAL_II_HAVE_SSE2=FALSE -DDEAL_II_HAVE_OPENMP_SIMD=false [...]
```

That said I am not a huge fan of introducing yet another boolean that globally alters the configuration. (For example, `-DDEAL_II_HAVE_OPENMP_SIMD=true -DDEAL_II_WITH_SIMD=no` is just confusing. What argument wins now?)

Alternatively, what about simply using `DEAL_II_ALLOW_PLATFORM_INTROSPECTION`? It is actually meant for situations like these: Disable any autodetection of compiler and architecture features and rely on the user to specify what they want on the command line. (This will need pr #7681 to work properly.)

**Comment by tjhei** [comment]
I agree with @tamiko that another flag is not a great idea.

Would it be possible to allow overwriting DEAL_II_COMPILER_VECTORIZATION_LEVEL instead?

**Comment by tamiko** [comment]
@tjhei We could but that again would create some confusion:
```
cmake -DDEAL_II_HAVE_SSE2=true -DDEAL_II_HAVE_AVX=false -DDEAL_II_COMPILER_VECTORIZATION_LEVEL=3 [...]
```
I think that the configuration options `HAVE_SSE2`, `HAVE_AVX`, `HAVE_AVX512` are more intuitive (and we should keep our numerical value for vectorization level an internal detail).

**Comment by davydden** [comment]
> I think that the configuration options HAVE_SSE2, HAVE_AVX, HAVE_AVX512 are more intuitive

IMO they are not as you have all those booleans, but what count is the first `TRUE` for largest SIMD:
```
IF(DEAL_II_HAVE_AVX512)		IF(DEAL_II_HAVE_AVX512)
  SET(DEAL_II_COMPILER_VECTORIZATION_LEVEL 3)		  SET(DEAL_II_COMPILER_VECTORIZATION_LEVEL 3)
ELSEIF(DEAL_II_HAVE_AVX)		ELSEIF(DEAL_II_HAVE_AVX)
  SET(DEAL_II_COMPILER_VECTORIZATION_LEVEL 2)		  SET(DEAL_II_COMPILER_VECTORIZATION_LEVEL 2)
ELSEIF(DEAL_II_HAVE_SSE2)		ELSEIF(DEAL_II_HAVE_SSE2)
  SET(DEAL_II_COMPILER_VECTORIZATION_LEVEL 1)		  SET(DEAL_II_COMPILER_VECTORIZATION_LEVEL 1)
ELSE()		ELSE()
  SET(DEAL_II_COMPILER_VECTORIZATION_LEVEL 0)		  SET(DEAL_II_COMPILER_VECTORIZATION_LEVEL 0)
ENDIF()
```

> Alternatively, what about simply using DEAL_II_ALLOW_PLATFORM_INTROSPECTION? It is actually meant for situations like these: Disable any autodetection of compiler and architecture features and rely on the user to specify what they want on the command line.

IMO that disables too much. It is used in `boost` configure and in `cxx`, whereas what I would want to control is only `DEAL_II_COMPILER_VECTORIZATION_LEVEL`. So from that perspective

> Would it be possible to allow overwriting DEAL_II_COMPILER_VECTORIZATION_LEVEL instead?

would be a good solution which does not introduce any new flags.

**Comment by davydden** [comment]
> One thing I wanted to point out is that what we control with DEAL_II_VECTORIZATION_LEVEL is actually the SIMD width we use with intrinsics, not the overall vectorization a compiler might apply. 

That's the main reasons I thought it's good to have some control over this instead of working with compiler flags `CXXFLAGS="-march=..."`.

> I also agree with the consensus that we should be conservative in adding additional global booleans. 

I see the issue here and also agree with this.

**Comment by davydden** [comment]
ok, let's close this for good
```
cmake ../ -DDEAL_II_HAVE_AVX=FALSE -DDEAL_II_HAVE_SSE2=FALSE
```
does what I want (i.e. sets `DEAL_II_COMPILER_VECTORIZATION_LEVEL=0`).

**Comment by davydden** [comment]
@tamiko A naive `CMake` question:

I can disable vectorization via
```
cmake ../ -DDEAL_II_HAVE_AVX=FALSE -DDEAL_II_HAVE_SSE2=FALSE
```
but I can't re-enable it with `TRUE`. Should not we declare them as options?

**Comment by tamiko** [comment]
@davydden Can you check again? On my machine
```
cmake ../ -DDEAL_II_HAVE_AVX=true -DDEAL_II_HAVE_SSE2=true
```
works just fine.

**Comment by davydden** [comment]
@tamiko 

indeed, my bad. Probably just looked at the wrong place, works as expected:

```
$cmake ../ -DDEAL_II_HAVE_AVX=FALSE -DDEAL_II_HAVE_SSE2=FALSE
<blablah>
$ grep VECTORIZATION detailed.log
#        DEAL_II_COMPILER_VECTORIZATION_LEVEL: 0
$cmake ../ -DDEAL_II_HAVE_AVX=true -DDEAL_II_HAVE_SSE2=true
<blablah>
CMake Warning:
  Manually-specified variables were not used by the project:

    DEAL_II_HAVE_SSE2
$grep VECTORIZATION detailed.log
#        DEAL_II_COMPILER_VECTORIZATION_LEVEL: 2
```

**Pull request closed without merging**
