### PR TITLE
github-actions: simplify oneAPI setup with external action.

### PR DESCRIPTION
**Pull request by marcfehling**
This means we have one less thing to worry about.

See: https://github.com/rscohn2/setup-oneapi

### CODE REVIEW

**Review by masterleinad — COMMENTED** [review]
How stable (and future-proof) is this action? What we are doing right now at least follows https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2024-0/apt.html#GUID-B1770241-0BBB-4E9C-B85B-9268CA66F15C.

**Comment by marcfehling** [comment]
The author works for Intel and is actively involved in the oneAPI project, including [oneapi-src/oneapi-ci](https://github.com/oneapi-src/oneapi-ci). Developing a github action was an early request in https://github.com/oneapi-src/oneapi-ci/issues/31. It seems like the author of this action took the matter into his own hands.

This action is not using the Intel repository, but relies on links to the individual Intel packages, see [rscohn2/setup-oneapi/src/main.js](https://github.com/rscohn2/setup-oneapi/blob/main/src/main.js). In addition to caching (as we do already), it also deletes unused files from the installation (pruning), which is a step forward from our approach.

I believe it is worthwhile to adopt this action, to (A) centralize the oneAPI installation and no longer have to take care of it ourselves, and (B) by promoting this action and the efforts of the author to show that there is a demand. However, I do not know what they have in mind for the future of this action, but I hope they consider making it _more official_ by moving it into the `oneapi-src` group.

**Comment by bangerth** [comment]
I don't know enough about the CI setup to say which way to go. Someone want to give a thumbs up/down on this?

**Review by masterleinad — APPROVED** [review]
Fine with me.

**Pull request merged**
