### PR TITLE
Satsfy my OCD.

### PR DESCRIPTION
**Pull request by bangerth**
This one section heading has spaces in different ways than all of the other section headings
in this file. That clearly can't stand.

### CODE REVIEW

**Comment by drwells** [comment]
As always, I appreciate the fact that you are willing to take time to fix these small things :)

**Comment by drwells** [comment]
Timezones are funny; I was here when you said it was midnight and you were going to sleep, and I am here now...

**Comment by bangerth** [comment]
Yes. I talk to my wife in the morning when it's evening for her, and in the evening when it's morning for her.

Btw, did my misspelled $SUBJECT bother your OCD? ;-)

**Comment by drwells** [comment]
It was late enough that i did not even notice.

**Pull request merged**
