### PR TITLE
Introduce new namespace MatrixFreeTools

### PR DESCRIPTION
**Pull request by peterrum**
As proposed in https://github.com/dealii/dealii/pull/9343#issuecomment-600338945. Once we have agreed on the name of the namespace and the file location and this PR has been merged, I will move the content of #9343 into the new namespace.

### CODE REVIEW

**Comment by tjhei** [comment]
The name ``MatrixFreeTools`` would nicely mirror ``GridTools``, ``DoFTools``, etc. .

**Comment by peterrum** [comment]
`MatrixFreeTools` sounds good! But I'll wait another couple of hours before updating. Maybe there some other ideas!

**Comment by nfehn** [comment]
In case of the ``Utilities`` naming, something like ``Utilities::MatrixFree`` might be better? By the way, this is not a vote against ``MatrixFreeTools``.

**Comment by peterrum** [comment]
There have been 3 votes for `MatrixFreeTools`! I have changed the name of the namespace. Can we merge it like this?

**Pull request merged**
