### PR TITLE
Make C++17 support independent of the special math functions.

### LINKED ISSUE #7014: Apple LLVM 9.1.0 C++17 issues
the current `master` branch gives issues with c++17"
```
C++17 support was requested (DEAL_II_WITH_CXX17=ON) but it is not supported
  by the current compiler.

  Please disable C++17 support, i.e.  configure with

      -DDEAL_II_WITH_CXX17=FALSE,
```

AFAIK `Apple LLVM version 9.1.0` supports C++17.

### PR DESCRIPTION
**Pull request by drwells**
Clang does not yet have these, but supports a large subset of C++17. Since these are a library feature its easy enough to just fall back to boost.

Fixes #7014.

@davydden since you have a compiler that does not support this, would you mind checking this patch with your set up to ensure that you get both C++17 and *not* `DEAL_II_CXX17_SPECIAL_MATH_FUNCTIONS`?

### CODE REVIEW

**Comment by davydden** [comment]
tester is not happy

```
In file included from /home/bob/source/source/base/function_lib.cc:20:
/home/bob/source/include/deal.II/base/std_cxx17/cmath.h:37:9: error: no member named 'cyl_bessel_j' in namespace 'std'; did you mean 'boost::math::cyl_bessel_j'?
  using std::cyl_bessel_j;
        ^~~~~~~~~~~~~~~~~
        boost::math::cyl_bessel_j
```

I will see if it works locally for me...

**Comment by davydden** [comment]
the test fails correctly:
```
Performing C++ SOURCE FILE Test DEAL_II_HAVE_CXX17_SPECIAL_MATH_FUNCTIONS failed with the following output:
Change Dir: /Users/davydden/libs-sources/deal.ii/deal.ii/_build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_0176d/fast"
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_0176d.dir/build.make CMakeFiles/cmTC_0176d.dir/build
Building CXX object CMakeFiles/cmTC_0176d.dir/src.cxx.o
/Users/davydden/spack/opt/spack/darwin-highsierra-x86_64/clang-9.1.0-apple/openmpi-3.1.1-2xylhvd6lp2jpum6aifbyh2fuvon2zpn/bin/mpic++    -DDEAL_II_HAVE_CXX17_SPECIAL_MATH_FUNCTIONS -march=native -std=c++17 -Werror   -o CMakeFiles/cmTC_0176d.dir/src.cxx.o -c /Users/davydden/libs-sources/deal.ii/deal.ii/_build/CMakeFiles/CMakeTmp/src.cxx
/Users/davydden/libs-sources/deal.ii/deal.ii/_build/CMakeFiles/CMakeTmp/src.cxx:6:14: error: no member named 'cyl_bessel_j' in namespace 'std'
        std::cyl_bessel_j(1.0, 1.0);
        ~~~~~^
/Users/davydden/libs-sources/deal.ii/deal.ii/_build/CMakeFiles/CMakeTmp/src.cxx:7:14: error: no member named 'cyl_bessel_jf' in namespace 'std'
        std::cyl_bessel_jf(1.0f, 1.0f);
        ~~~~~^
/Users/davydden/libs-sources/deal.ii/deal.ii/_build/CMakeFiles/CMakeTmp/src.cxx:8:14: error: no member named 'cyl_bessel_jl' in namespace 'std'
        std::cyl_bessel_jl(1.0, 1.0);
        ~~~~~^
3 errors generated.
make[2]: *** [CMakeFiles/cmTC_0176d.dir/src.cxx.o] Error 1
make[1]: *** [cmTC_0176d/fast] Error 2
```

**Comment by davydden** [comment]
from the clean directory Cmake does not pick up C++17, I looked at PR and I don't understand why would that be the case...

**Comment by masterleinad** [comment]
@drwells I fixed the preprocessor directives in `std_cxx17/cmath.h` and made sure that `DEAL_II_CXX17_SPECIAL_MATH_FUNCTIONS` is not required for `C++17` support.
Feel free to squash or discard as you like.

**Comment by masterleinad** [comment]
@davydden Can you try again?

**Comment by davydden** [comment]
nope, still: `DEAL_II_WITH_CXX17 = OFF`

**Comment by davydden** [comment]
[CMakeLogs.zip](https://github.com/dealii/dealii/files/2265700/CMakeLogs.zip)

**Comment by masterleinad** [comment]
For me the relevant `CMake` output is
```
 -- Include /mnt/data/darndt/Sources/dealii-clang-6.0.0/cmake/checks/check_01_cxx_features.cmake
 -- Using C++ version flag "-std=c++17"
 -- Performing Test DEAL_II_HAVE_CXX17_ATTRIBUTES
 -- Performing Test DEAL_II_HAVE_CXX17_ATTRIBUTES - Success
 -- Performing Test DEAL_II_HAVE_CXX17_IF_CONSTEXPR
 -- Performing Test DEAL_II_HAVE_CXX17_IF_CONSTEXPR - Success
 -- Performing Test DEAL_II_HAVE_CXX14_MAKE_UNIQUE
 -- Performing Test DEAL_II_HAVE_CXX14_MAKE_UNIQUE - Success
 -- Performing Test DEAL_II_HAVE_CXX14_CONSTEXPR_STDMAXMIN
 -- Performing Test DEAL_II_HAVE_CXX14_CONSTEXPR_STDMAXMIN - Success
 -- Performing Test DEAL_II_HAVE_CXX14_CLANGAUTODEBUG_BUG_OK
 -- Performing Test DEAL_II_HAVE_CXX14_CLANGAUTODEBUG_BUG_OK - Success
 -- Performing Test DEAL_II_HAVE_CXX11_FEATURES
 -- Performing Test DEAL_II_HAVE_CXX11_FEATURES - Success
 -- Performing Test DEAL_II_HAVE_CXX11_FUNCTIONAL_LLVMBUG20084_OK
 -- Performing Test DEAL_II_HAVE_CXX11_FUNCTIONAL_LLVMBUG20084_OK - Success
 -- Performing Test DEAL_II_HAVE_CXX11_MACOSXC99BUG_OK
 -- Performing Test DEAL_II_HAVE_CXX11_MACOSXC99BUG_OK - Success
 -- Performing Test DEAL_II_HAVE_CXX11_ICCNUMERICLIMITSBUG_OK
 -- Performing Test DEAL_II_HAVE_CXX11_ICCNUMERICLIMITSBUG_OK - Success
 -- Performing Test DEAL_II_HAVE_CXX11_ICCLIBSTDCPP47CXX11BUG_OK
 -- Performing Test DEAL_II_HAVE_CXX11_ICCLIBSTDCPP47CXX11BUG_OK - Success
 -- Performing Test DEAL_II_COMPILER_DEFAULTS_TO_CXX11_OR_NEWER
 -- Performing Test DEAL_II_COMPILER_DEFAULTS_TO_CXX11_OR_NEWER - Success
 -- DEAL_II_WITH_CXX14 successfully set up
 -- DEAL_II_WITH_CXX17 successfully set up
 -- Performing Test DEAL_II_HAVE_CXX11_IS_TRIVIALLY_COPYABLE
 -- Performing Test DEAL_II_HAVE_CXX11_IS_TRIVIALLY_COPYABLE - Success
 -- Performing Test DEAL_II_HAVE_CXX17_SPECIAL_MATH_FUNCTIONS
 -- Performing Test DEAL_II_HAVE_CXX17_SPECIAL_MATH_FUNCTIONS - Failed
```
What do you get?

**Comment by davydden** [comment]
```
-- Include /Users/davydden/libs-sources/deal.ii/deal.ii/cmake/checks/check_01_cxx_features.cmake
-- Performing Test DEAL_II_HAVE_FLAG_stdcxx17
-- Performing Test DEAL_II_HAVE_FLAG_stdcxx17 - Success
-- Using C++ version flag "-std=c++17"
-- Performing Test DEAL_II_HAVE_CXX17_ATTRIBUTES
-- Performing Test DEAL_II_HAVE_CXX17_ATTRIBUTES - Success
-- Performing Test DEAL_II_HAVE_CXX17_IF_CONSTEXPR
-- Performing Test DEAL_II_HAVE_CXX17_IF_CONSTEXPR - Success
-- Performing Test DEAL_II_HAVE_CXX17_SPECIAL_MATH_FUNCTIONS
-- Performing Test DEAL_II_HAVE_CXX17_SPECIAL_MATH_FUNCTIONS - Failed
-- Performing Test DEAL_II_NON_CONSTEXPR_LAMBDA
-- Performing Test DEAL_II_NON_CONSTEXPR_LAMBDA - Success
-- Performing Test DEAL_II_HAVE_FLAG_stdcxx14
-- Performing Test DEAL_II_HAVE_FLAG_stdcxx14 - Success
-- Performing Test DEAL_II_HAVE_CXX14_MAKE_UNIQUE
-- Performing Test DEAL_II_HAVE_CXX14_MAKE_UNIQUE - Success
-- Performing Test DEAL_II_HAVE_CXX14_CONSTEXPR_STDMAXMIN
-- Performing Test DEAL_II_HAVE_CXX14_CONSTEXPR_STDMAXMIN - Success
-- Performing Test DEAL_II_HAVE_CXX14_CLANGAUTODEBUG_BUG_OK
-- Performing Test DEAL_II_HAVE_CXX14_CLANGAUTODEBUG_BUG_OK - Success
-- Performing Test DEAL_II_HAVE_CXX11_FEATURES
-- Performing Test DEAL_II_HAVE_CXX11_FEATURES - Success
-- Performing Test DEAL_II_HAVE_CXX11_FUNCTIONAL_LLVMBUG20084_OK
-- Performing Test DEAL_II_HAVE_CXX11_FUNCTIONAL_LLVMBUG20084_OK - Success
-- Performing Test DEAL_II_HAVE_CXX11_MACOSXC99BUG_OK
-- Performing Test DEAL_II_HAVE_CXX11_MACOSXC99BUG_OK - Success
-- Performing Test DEAL_II_HAVE_CXX11_ICCNUMERICLIMITSBUG_OK
-- Performing Test DEAL_II_HAVE_CXX11_ICCNUMERICLIMITSBUG_OK - Success
-- Performing Test DEAL_II_HAVE_CXX11_ICCLIBSTDCPP47CXX11BUG_OK
-- Performing Test DEAL_II_HAVE_CXX11_ICCLIBSTDCPP47CXX11BUG_OK - Success
-- Performing Test DEAL_II_COMPILER_DEFAULTS_TO_CXX11_OR_NEWER
-- Performing Test DEAL_II_COMPILER_DEFAULTS_TO_CXX11_OR_NEWER - Failed
-- Using C++ version flag "-std=c++14"
-- DEAL_II_WITH_CXX14 successfully set up
-- Performing Test DEAL_II_HAVE_ATTRIBUTE_FALLTHROUGH
-- Performing Test DEAL_II_HAVE_ATTRIBUTE_FALLTHROUGH - Failed
-- Performing Test DEAL_II_HAVE_CXX11_IS_TRIVIALLY_COPYABLE
-- Performing Test DEAL_II_HAVE_CXX11_IS_TRIVIALLY_COPYABLE - Success
-- Performing Test DEAL_II_HAVE_FP_EXCEPTIONS
-- Performing Test DEAL_II_HAVE_FP_EXCEPTIONS - Failed
-- Performing Test DEAL_II_HAVE_COMPLEX_OPERATOR_OVERLOADS
-- Performing Test DEAL_II_HAVE_COMPLEX_OPERATOR_OVERLOADS - Failed
```

**Comment by drwells** [comment]
Those are silly mistakes. I should stop writing code late at night. Thanks for the fix, @masterleinad!

**Pull request merged**
