### PR TITLE
Enable FEFaceValues for wedges and pyramids

### PR DESCRIPTION
**Pull request by peterrum**
~Only the last commit is relevant. The others are from #10764 and #11317.~

### CODE REVIEW

**Comment by peterrum** [comment]
I have rebased this branch.

**Review by drwells — APPROVED** [review]
I think this is fine but I'm concerned about how much geometric information that's pretty basic (like the vertices and areas of reference cell faces) that's encoded into this file. Should we open an issue to track this and possibly move these tables into `reference_cell.h`? Do you think its worth generalizing these?

**Comment by peterrum** [comment]
@drwells I am on it https://github.com/dealii/dealii/issues/11352 point 5 ;)

**Comment by drwells** [comment]
Other more important PRs depend on this so I am willing to merge this as-is.

**Pull request merged**
