### PR TITLE
Use AE spelling 'disk' instead of BE spelling 'disc'.

### PR DESCRIPTION
**Pull request by bangerth**
/rebuild

### CODE REVIEW

**Comment by bangerth** [comment]
See https://en.wiktionary.org/wiki/disk#Usage_notes

**Comment by masterleinad** [comment]
Travis is stuck here.

**Comment by jppelteret** [comment]
> Travis is stuck here.

Insert obligatory joke about it objecting the dismissal of the queen's English.

**Comment by bangerth** [comment]
Rebased -- let's see what happens now.

**Pull request merged**
