### PR TITLE
Remove whitespace in get fe by name

### LINKED ISSUE #2099: Improve finite element name parsing
As noted in #2098 by @asartori86, some functions which interpret strings as finite element spaces seemingly cannot handle extra whitespace:

```
An error occurred in line <1480> of file </apps/src/dealii/source/fe/fe_tools.cc> in function
    dealii::FiniteElement<dim, spacedim>* dealii::FETools::internal::{anonymous}::get_fe_from_name_ext(std::string&, const std::map<std::basic_string<char>, std::shared_ptr<const dealii::Subscriptor> >&) [with int dim = 3; int spacedim = 3; std::string = std::basic_string<char>]
The violated condition was: 
    fe_name_map.find(name_part) != fe_name_map.end()
The name and call sequence of the exception was:
    ExcInvalidFEName(name)
Additional Information: 
Can't re-generate a finite element from the string '                                         FE_DGPMonomial(0)-      FE_DGPMonomial(0)]'.
```

We should improve the parser so that it does not get thrown off by extra whitespace.

### PR DESCRIPTION
**Pull request by drwells**
This should close #2099. It fixes the issue in #2098, where `get_fe_by_name` choked if the string contained unexpected whitespace.

### CODE REVIEW

**Comment by bangerth** [comment]
I'm not opposed to this patch, but it doesn't fix the original problem (see #2098, #2099).

**Comment by tjhei** [comment]
My first thought was that it is somewhat weird, but it won't do any harm or cause any problems, I guess.

**Comment by drwells** [comment]
I am not very familiar with this part of the library. @tjhei What do you mean by 'weird'? Can you think of anything strange that might happen with the 'string to FE' and 'FE to string' functions if we ignore whitespace?

**Comment by tjhei** [comment]
Weird in the sense that "F  E_D GQ   (1)  " is now a valid input, that is all. I don't see any other problem.

**Comment by drwells** [comment]
Yes, this is true. I would bet that at some point someone has tried to use
something like

```cpp
FiniteElement<2, 2>  *fe = FETools::get_fe_from_name<2>
  ("FESystem[FE_Q(1) - FE_Q(2)]");
```

and gotten funny errors; this is the case I was more concerned about.

**Comment by bangerth** [comment]
So maybe the right thing is to only remove spaces not located between two characters in the class `[a-zA-Z0-9_]`?

**Comment by tjhei** [comment]
I am not sure that is worth the effort. Maybe we should just merge it and move on? @bangerth ?

**Comment by drwells** [comment]
I have been meaning to fix this. I will get around to the suggested improvement soon.

**Comment by bangerth** [comment]
Yes, I'm ok with just merging. @drwells -- please merge if you're ok with the current state. I can't quite figure out from your last sentence whether you thought the current state is ok or if you were suggesting to spend more time on this.

**Comment by drwells** [comment]
I mean that I agree with your remark from two weeks ago that we should permit things like

```cpp
"FE_Q (1)"
```

but not
```cpp
"F E_Q(1)"
```

that is, permit whitespace between words.

**Comment by drwells** [comment]
The function now removes whitespace in the agreed upon places; this should be good to go.

**Pull request merged**
