### PR TITLE
Inhomogeneous constraints in Meshworker

### PR DESCRIPTION
**Pull request by jgedicke**
As follow up to the thread
https://groups.google.com/forum/#!topic/dealii/UoTWTXpl_lk
with title "using Meshworker with a ConstraintMatrix",
I modified Meshworker::Assembler::SystemSimple such that inhomogeneous constraints are treated correctly. In order to do so I had to modify the distribute_local_to_global that assembles an inhomogeneous vector such that it accepts two different index sets, one for the rows and one for the columns. This is necessary in Meshworker when an edge local matrix is assembled, since then the rows correspond to an element T_1 while the columns correspond to the neighboring element T_2. As it turns out this is only a minor modification of that function plus the respective changes in the header and the template instantiates.
The main changes are then done in simple.h for the SystemSimple class.
This has been tested for step-12 and step-16 and the test from Korosh Taebi from the google thread (as well as with my fourth order obstacle implementation).
Here is an updated version of Korosh Taebi's test that works with this branch 
[MeshWorkerConstraintMatrixTest.cc.zip](https://github.com/dealii/dealii/files/159973/MeshWorkerConstraintMatrixTest.cc.zip)
(Note that the SystemSimpleInhom.h that Korosh Taebi provides in the google thread does only work for uniform meshes and inhomogeneous constraints only, while this branch is a complete modification of SystemSimple to support the general case of mixed homogeneous and inhomogeneous constraints on uniform and adaptively refined meshes)

### CODE REVIEW

**Comment by jgedicke** [comment]
sorry, since this is my first try, I indeed needed three attempts to format the code correctly to pass the tests...
The last commit copies the files from #2308, that I did not touch myself.

**Comment by drwells** [comment]
This looks good, at a glance, but I am not familiar enough with `MeshWorker` (or `ConstraintMatrix`) to be comfortable in merging this myself.

The indentation issue in #2308 is unfortunate but it is logically a separate concern from this; would you mind getting rid of that last commit?

**Comment by davydden** [comment]
@jgedicke I am not sure if you indeed intended to close the PR, but in any case you could remove the last commit  by  `git rebase -i HEAD~XYZ`, where `XYZ` is the total number of commits.

**Comment by jgedicke** [comment]
sry yes I that happend accidentally, while learning some git voodoo

**Comment by jgedicke** [comment]
sry for the mess!
I created a clean new branch and will open a new pull request...

**Comment by jgedicke** [comment]
New pull request is #2312

**Pull request closed without merging**
