### PR TITLE
Use inheritance for TrilinosWrappers iterative solver AdditionalData.

### PR DESCRIPTION
**Pull request by jppelteret**
The AdditionalData structures for the various TrilinosWrappers solver
classes are now derived from that of SolverBase.

### CODE REVIEW

**Comment by jppelteret** [comment]
@Rombur It follows a discussion @bangerth and I were having in #4515. I don't think that this will break _everybody's_ code. Since I kept the `additional_data` members [in the derived solver classes](https://github.com/dealii/dealii/pull/4550/files#diff-b027be7a00775f687075caada99a9676R613), the only user's affected would be those that explicitly created a `TW::SolverGMRES::Additional_Data` in the scope of their solver and specifically reference the `restart_parameter`. I would assume that few do this.

What I could do is [reinstate this variable](https://github.com/dealii/dealii/pull/4550/files#diff-b027be7a00775f687075caada99a9676L627) - although this would result in data duplication, it would prevent the code breakage that you're worried about. What do you think?

**Comment by bangerth** [comment]
@jppelteret -- can you tell me again why the `gmres_restart_parameter` needs to be in the base class? I suppose it is because of this function in the base class, right?
```
  template<typename Preconditioner>
  void
  SolverBase::do_solve(const Preconditioner &preconditioner)
  {
    int ierr;

    // Next we can allocate the AztecOO solver...
    solver.SetProblem(*linear_problem);

    // ... and we can specify the solver to be used.
    switch (solver_name)
      {
      case cg:
        solver.SetAztecOption(AZ_solver, AZ_cg);
        break;
      case cgs:
        solver.SetAztecOption(AZ_solver, AZ_cgs);
        break;
      case gmres:
        solver.SetAztecOption(AZ_solver, AZ_gmres);
        solver.SetAztecOption(AZ_kspace, additional_data.gmres_restart_parameter);
...
```
If you can confirm that this is correct, let me play with changing that to something of the form
```
  SolverGMRES::AdditionalData *gmres_additional_data
   = dynamic_cast<SolverGMRES::AdditionalData *>(&additional_data);
  Assert (gmres_additional_data != 0, ...);
        solver.SetAztecOption(AZ_kspace, gmres_additional_data->gmres_restart_parameter);
```
Presumably, we only get to this point if we really are using a SolverGMRES object.

Although, on second thought, the object the function is accessing is the *base class's copy* of the `AdditionalData` object, which is really only of type `SolverBase::AdditionalData`. So the dynamic cast will always fail. We would need a way to access the objects of the derived class...

**Comment by jppelteret** [comment]
> I suppose it is because of this function in the base class, right?

Yip, that's exactly it.

> the object the function is accessing is the base class's copy of the AdditionalData object, which is really only of type SolverBase::AdditionalData

Correct again. Also @kronbichler pointed out that `SolverBase` can be used as a type of solver selector (I'm making the assumption that he does so), so moving this parameter out of the base class `AdditionalData` would break that functionality altogether.

**Comment by bangerth** [comment]
Hm, uhm. That's unfortunate. I guess what it means is that we would have to mirror *all* flags in derived classes in the base class. That's unfortunate. Of course, we haven't seen that in the past because all but one of the solvers don't actually define any flags at all...

**Pull request merged**
