### PR TITLE
Add a more general fallthrough attribute.

### PR DESCRIPTION
**Pull request by drwells**
GCC7 raises implicit fallthrough warnings in a lot of places when we compile without C++17 support. This patch adds a second check for the GCC extension `__attribute__((fallthrough))` that works in C++11 and C++14 and fixes these warnings.

### CODE REVIEW

**Comment by bangerth** [comment]
Looks good. OK to merge once the tester is happy.

**Comment by Rombur** [comment]
I am not against this but boost has already a portable implementation of `fallthrough` http://www.boost.org/doc/libs/1_64_0/libs/config/doc/html/boost_config/boost_macro_reference.html#boost_config.boost_macro_reference.boost_helper_macros

**Comment by drwells** [comment]
My main goal with this patch was to silence the warnings I get in GCC7 when compiling without C++17. We should keep this in mind if clang ever starts complaining about implicit fall throughs.

**Comment by masterleinad** [comment]
@drwells Just out of curiosity: What's the reason for using GCC7 without `-std=c++17`?

**Comment by bangerth** [comment]
I think it's ok to have our own detection code for this. I don't particularly like the fact that BOOST figures out whether something works or not by checking compiler versions. It seems much more robust to use cmake macros, as @drwells does here.

**Comment by drwells** [comment]
@masterleinad My workstation has GCC 4.8 and my laptop has GCC 7.1. I usually just compile everything in C++11 mode in both places to avoid accidentally adding a C++14ism or C++17ism that the workstation won't understand.

**Pull request merged**
