### PR TITLE
Clean up some p4est-related code.

### PR DESCRIPTION
**Pull request by bangerth**
Specifically, commit daf3146 (via #3625) introduced a dimension dependent dispatch
mechanism that allowed writing some code in a more generic way. The idea was right,
but the approach duplicated the dispatching because we already have a dispatching
mechanism via the internal::p4est::functions classes.

This patch simply merges the two approaches. It also allows to move some
code out of distributed/tria.cc into distributed/p4est_wrappers.cc, at the
cost of some code churn. The patch does not actually change any kind of
functionality -- it just moves things.

### CODE REVIEW

**Comment by kronbichler** [comment]
This looks nice!

**Comment by bangerth** [comment]
I'm impressed you read through it in such a short amount of time :-)

**Comment by kronbichler** [comment]
Well, I just checked that you really only "moved" code around... ;-)

**Comment by tjhei** [comment]
I am seeing
```
Test multigrid/transfer_system_adaptive_06.debug: BUILD
===============================   OUTPUT BEGIN  ===============================
multigrid/transfer_system_adaptive_06.debug: BUILD failed. Output:
[  0%] Generating transfer_system_adaptive_06.debug/interrupt_guard.cc
Scanning dependencies of target transfer_system_adaptive_06.debug
[100%] Building CXX object CMakeFiles/transfer_system_adaptive_06.debug.dir/transfer_system_adaptive_06.cc.o
[  0%] Building CXX object CMakeFiles/transfer_system_adaptive_06.debug.dir/transfer_system_adaptive_06.debug/interrupt_guard.cc.o
Linking CXX executable transfer_system_adaptive_06.debug/transfer_system_adaptive_06.debug
/home/bob/build-clang/lib/libdeal_II.g.so.8.5.0-pre: undefined reference to `void dealii::internal::p4est::functions<3>::iterate<3>(p8est*, p8est_ghost_t*, void*)'
/home/bob/build-clang/lib/libdeal_II.g.so.8.5.0-pre: undefined reference to `void dealii::internal::p4est::functions<2>::iterate<2>(p4est*, p4est_ghost_t*, void*)'
/home/bob/build-clang/lib/libdeal_II.g.so.8.5.0-pre: undefined reference to `void dealii::internal::p4est::functions<2>::iterate<3>(p4est*, p4est_ghost_t*, void*)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by bangerth** [comment]
@tjhei: I had already fixed this by the time the tester was done. Can you try again with the current version of the patch? I suppose you meant that that was on a system separate from the tester? Because the tester is happy.

**Comment by tjhei** [comment]
> I had already fixed this by the time the tester was done

Ah, okay. No, I just looked at the tester output.

**Pull request merged**
