### PR TITLE
Revert the effect of ReflowComments

### PR DESCRIPTION
**Pull request by masterleinad**
I went back to the commit applying clang-tidy and changed `.clang-format` to the current version (including `ReflowComments: false`). Then I rebased the current master on top of it fixing some merge-conflicts. The result here is the diff after indenting again.

It certainly shows some more issues we currently have in tests. It's more or less impossible to copy our error messages verbatim into comments.

Do people like this approach better than the one in #6814?

### CODE REVIEW

**Comment by drwells** [comment]
Though its a lot more work, I have a slight preference for the manual (or assisted by clang format) version for a few reasons:
1. We can finally get rid of all comments starting at line 36 (the old style).
2. Some of the comments contain old code that could use style improvements (e.g., `> >` or `typename Triangulation<dim>::active_cell_iterator`)
3. Automatic comment wrapping is quite useful.

Either way: lets mark all of the current indentation PRs as WIP until we settle on a course of action. It doesn't make sense to merge them if we will just revert the changes by commiting this.

**Comment by masterleinad** [comment]
In my opinion, it doesn't hurt to apply the manual patches anyway and rebase this PR afterwards. Apparently, this is necessary already.

I also prefer the manual approach and think that it is feasible. Nevertheless, we have to be aware that there are cases, e.g. printing error messages, where it is difficult to find a reasonable indentation restricted to 80 characters per line.

**Comment by masterleinad** [comment]
Have a look at https://github.com/dealii/dealii/pull/6822/files#diff-aa664de2811ebf87ef58718b7d89a09dR82

**Comment by drwells** [comment]
Good catch. I think its reasonable to manually re-flow this to fit the 80 character length:

```cpp
  /**
   * --------------------------------------------------------
   * An error occurred in line <749>
   * of file <source/numerics/derivative_approximation.cc> in function
   *     void DerivativeApproximation::approximate(...)
   * [with DerivativeDescription = DerivativeApproximation::Gradient<3>, int
   *  dim = 3, DoFHandlerType = DoFHandler, InputVector = Vector<double>]
   * The violated condition was:
   *     determinant(Y) != 0
   * The name and call sequence of the exception was:
   *     ExcInsufficientDirections()
   * Additional Information:
   * (none)
   * --------------------------------------------------------
   * @endcode
   * As can easily be verified, this can only happen on very coarse grids, when
   */
```

**Comment by drwells** [comment]
Its been a busy week and I forgot about this discussion.

Given #6866 et al, I think it would be best to keep the reflow option on (so that all lines are limited to 80 characters) and just fix things up manually as we find them.

That being said, there is surely room for disagreement on the way to proceed, so I propose we just vote:
vote :+1: to continue manually fixing up `@code`/`@endcode` et al
vote :tada: to disable reflowing and go back to the old python script

**Comment by masterleinad** [comment]
I interpret the response to the vote here and in #6814 that most people don't care whether we keep `ReflowComments` or not (as long as the issue is fixed in the end). The voters agree on fixing the files manually, so I will remove the `Do not merge` labels from the other PRs.
I would like to keep this PR open as a reference as long as we haven't looked into all the relevant files.

**Comment by bangerth** [comment]
We got ourselves in a bit of a pickle: we broke a good number of comments, and we keep finding other places and kinds of breakages. At the same time, I'm not sure we're still in a position to automatically undo any of this -- we may just have to do it by hand :-(

Regardless, however, it turns out that it's not trivial to restrict comments that show formatted text to 80 columns. It's also highly annoying if one has carefully arranged a formatted code block just to see `make indent` destroy it again. Since the goal was to arrange everything to 80 characters, and since we've achieved this for the vast majority of the comments -- and taking into account that this will remain the vast majority even if we furiously continue to write documentation :-) -- there is probably little harm in switching off `ReflowComments`: it only affects new comments, not all of the old ones.

So that's what I would suggest, in order to make the manual changes suggested by #6814 and other issues easier to achieve.

**Comment by masterleinad** [comment]
I am trying to fit everything into 80 characters such that we can go in either way for `ReflowComments`.

**Comment by bangerth** [comment]
I think we've concluded that we don't want to go back to the previous comments, right? This patch has also already accumulated a number of conflicts already. Should we just close it?

**Comment by drwells** [comment]
@bangerth I believe the conclusion was to manually reflow comments (and @masterleinad did most of the work to that end), so we should close this.

**Pull request closed without merging**
