### PR TITLE
Use std::shared_mutex in get_fe_by_name().

### PR DESCRIPTION
**Pull request by bangerth**
Related to #16168 . We have again one place that writes, and multiple that read. We can use a `std::shared_mutex` for that.

### CODE REVIEW

**Comment by bangerth** [comment]
I pushed a second commit that addresses an unrelated problem (but in a place that touches the same lines): We have a global variable declared in a `.h` file. We mark it as `static`, but that's the wrong thing. What we really want is to reference a single global variable, which we can do by marking it as `extern` and then providing the definition in the `.cc` file.

**Comment by bangerth** [comment]
I believe that the failing CI check is an out-of-memory problem.

**Comment by bangerth** [comment]
I restarted the one failing CI check, but it failed again because of the out-of-memory issue. The remaining checks all succeed.

**Comment by bangerth** [comment]
Ping?

**Review by drwells — APPROVED** [review]

**Review by Rombur — APPROVED** [review]

**Pull request merged**
