### PR TITLE
Add test to show incompatibility between Sacado and FEValues interface

### PR DESCRIPTION
**Pull request by jppelteret**
Relates to #4706

### CODE REVIEW

**Comment by masterleinad** [comment]
Please look into the indentation :wink:.

**Comment by bangerth** [comment]
So does the test work or fail right now? If it fails, we shouldn't merge it, right?

If it fails, can you copy paste the error here?

**Comment by jppelteret** [comment]
It fails so far:

```
1002: /Users/jp/Programs/GitHub/deal.II/dealii/tests/trilinos/sacado_fevalues.cc:58:17: error: no matching member function for call to 'get_function_values'
1002:       fe_values.get_function_values(solution, local_values);
1002:       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
1002: /Users/jp/Programs/GitHub/deal.II/dealii/tests/trilinos/sacado_fevalues.cc:80:5: note: in instantiation of function template specialization 'test<Sacado::Fad::DFad<double>, 2>' requested here
1002:     test<Sacado::Fad::DFad<double>>();
1002:     ^
1002: /Users/jp/Programs/GitHub/deal.II/dealii/include/deal.II/fe/fe_values.h:1713:8: note: candidate function [with InputVector = dealii::Vector<double>] not viable: no known conversion from 'std::vector<DFad<double> >' to 'std::vector<typename Vector<double>::value_type> &' (aka 'vector<double> &') for 2nd argument
1002:   void get_function_values (const InputVector &fe_function,
1002:        ^
1002: /Users/jp/Programs/GitHub/deal.II/dealii/include/deal.II/fe/fe_values.h:1730:8: note: candidate function [with InputVector = dealii::Vector<double>] not viable: no known conversion from 'std::vector<DFad<double> >' to 'std::vector<Vector<typename Vector<double>::value_type> > &' (aka 'vector<Vector<double> > &') for 2nd argument
1002:   void get_function_values (const InputVector       &fe_function,
```

**Comment by luca-heltai** [comment]
We should decide over the interface:

~~~
void get_function_values (const InputVector &fe_function, ...)
~~~
should really read something like
~~~
void get_function_values_from_local_vector (const InputVector &fe_function, ...)
~~~
or simply
~~~
void get_local_function_values (const InputVector &fe_function, ...)
~~~

**Comment by bangerth** [comment]
Hm, but the compiler isn't wrong here. You're passing a `Vector<double>` in, so you should expect a `Vector<double>` or `std::vector<double>` out, no? You want the conversion to the `DFad` type to happen at the same time, but I think that extends past what that function can be expected to do.

Or what do you think?

**Comment by tamiko** [comment]
In reference to #4704

**Comment by jppelteret** [comment]
Superseded by #4742 (equivalent test will be incorporated into that PR)

**Pull request closed without merging**
