### PR TITLE
Correct typo (math rendering)

### PR DESCRIPTION
**Pull request by mwichro**
Tiny thing but a bit annoying: remove `Undefined control sequence \matbf` error in the documentation

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
Thanks!

**Comment by masterleinad** [comment]
Would you mind fixing the indentation?
```
diff --git a/include/deal.II/fe/fe_interface_values.h b/include/deal.II/fe/fe_interface_values.h
index 17b1813c..fe4e9257 100644
--- a/include/deal.II/fe/fe_interface_values.h
+++ b/include/deal.II/fe/fe_interface_values.h
@@ -871,8 +871,8 @@ namespace FEInterfaceViews
     //@{
 
     /**
-     * Return the average vector $\average{\mathbf{u}}=\frac{1}{2}(\mathbf{u_1} +
-     * \mathbf{u_2})$ on the interface for the shape
+     * Return the average vector $\average{\mathbf{u}}=\frac{1}{2}(\mathbf{u_1}
+     * + \mathbf{u_2})$ on the interface for the shape
      * function @p interface_dof_index in the quadrature point @p q_point.
      */
     value_type
Error: Process completed with exit code 1.
```

**Review by bangerth — APPROVED** [review]

**Review by marcfehling — APPROVED** [review]

**Review by jppelteret — APPROVED** [review]
Thanks for the fix @mwichro. Perhaps you wouldn't mind fixing the indentation as @masterleinad indicated.

**Comment by mwichro** [comment]
@jppelteret of course, thank you!

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
@mwichro Did you forget to push the commit that fixes the indentation?

**Pull request merged**
