### PR TITLE
Polynomials_bdm Documentation Edit

### PR DESCRIPTION
**Pull request by alistairbntl**
- The documentation suggests that the given functions are the
    the bdm shape functions when in fact they are the basis functions
    used to construct the bdm shape functions. I've reworded the
    documentation to clarify this point.

### CODE REVIEW

**Comment by bangerth** [comment]
I don't actually know the BDM well enough, but are you sure that that's just the basis, or if these are indeed the shape functions?

**Comment by bangerth** [comment]
What I mean is: you've stated this in the description of the PR above, but have you verified?

**Comment by tjhei** [comment]
Yes, these form _a_ basis (but not _the_ basis) of BDM1 in 2d. This is the documentation of ```PolynomialsBDM``` not ```FE_BDM``, though. I think these are the polynomials returned by this class, no? If yes, it might be more appropriate to state that:
"These are the polynomials returned for k=1 in 2d and are used to construct the shape functions of BDM1:" or something like that.

**Comment by alistairbntl** [comment]
Yes, I'm nearly certain what's written now is correct.
The actual 'shape functions' are constructed in the fe_bdm class which uses the polynomials_bdm as part of the construction.
When I was unable to produce the output of these 'shape functions' with the fe_bdm class, I realized (and confirmed with a short program) that these functions are actually the raw basis functions used to construct the BDM space.

**Comment by bangerth** [comment]
@tjhei -- ah, completely missed this. Thanks.

@alistairbntl -- great, thanks for confirming! (And of course many thanks also for the patch!)

**Pull request merged**
