### PR TITLE
Make coding style more uniform.

### PR DESCRIPTION
**Pull request by bangerth**
Exceedingly boring, and completely unnecessary, but still nice to have a uniform
code style.

### CODE REVIEW

**Comment by davydden** [comment]
Hopefully u didn't do it by hand ;-)

Ok to merge if tester pass as Github can't even show diffs saying that the page takes too long to load ;-)

**Comment by bangerth** [comment]
I'm pretty sure @drwells has written patches of this kind and length by hand in the past...

**Comment by masterleinad** [comment]
So this is doing basically the same as `SpaceAfterTemplateKeyword=true` in a .clang-format file. Hopefully, we can find a way to include clang-format in our indenting process and do these kind of things automatically...

**Comment by jppelteret** [comment]
These guys have a bot that pops up with patches for documentation fixes: 
https://github.com/isuruf/symengine/pull/20 

Pretty cool, but black magic to me. Maybe we could do something similar?

**Comment by bangerth** [comment]
Yes, bot-generated patches are definitely weird...

**Comment by drwells** [comment]
I am a year late to the party but I just saw this comment from #6686. I think I enjoy suffering sometimes...

**Pull request merged**
