### PR TITLE
Fix FE_Nedelec::convert_generalized_support_point_values_to_dof_values (kind of)

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Comment by tamiko** [comment]
This test fails with an assertion:
```
--------------------------------------------------------
An error occurred in line <368> of file <../include/deal.II/base/point.h> in function
    Number dealii::Point<dim, Number>::operator()(unsigned int) const [with int dim = 1; Number = double]
The violated condition was:
    ((int) index) < (dim)
Additional information:
    Index 1 is not in the half-open range [0,1).
--------------------------------------------------------


Thread 1 "interpolate_ned" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fffbb0e3078 in __GI_abort () at abort.c:89
#2  0x00007ffff48fd7de in dealii::(anonymous namespace)::internal_abort (exc=...) at ../source/base/exceptions.cc:444
#3  0x00007ffff48fe5de in dealii::deal_II_exceptions::internals::abort (exc=...) at ../source/base/exceptions.cc:479
#4  0x000055555557d752 in dealii::deal_II_exceptions::internals::issue_error<dealii::StandardExceptions::ExcIndexRange> (handling=dealii::deal_II_exceptions::internals::abort_on_exception,
    file=0x7ffff5922c18 "../include/deal.II/base/point.h", line=368,
    function=0x7ffff618e9c0 <_ZZNK6dealii5PointILi1EdEclEjE19__PRETTY_FUNCTION__> "Number dealii::Point<dim, Number>::operator()(unsigned int) const [with int dim = 1; Number = double]",
    cond=0x7ffff590c738 "((int) index) < (dim)", exc_name=0x7ffff5922be8 "dealii::ExcIndexRange(((int) index),0,(dim))", e=...)
    at /home/tamiko/workspace/dealii/include/deal.II/base/exceptions.h:291
#5  0x00007ffff20f9c05 in dealii::Point<1, double>::operator() (index=1, this=0x5555556a6bc0) at ../include/deal.II/base/point.h:368
#6  dealii::FE_Nedelec<2>::convert_generalized_support_point_values_to_dof_values (this=0x7fffffffca20, support_point_values=..., nodal_values=...) at ../source/fe/fe_nedelec.cc:3178
#7  0x000055555558239a in check1<2> (f=..., degree=<optimized out>) at /home/tamiko/workspace/dealii/tests/fe/interpolate_nedelec.cc:38
#8  0x0000555555571651 in main () at /home/tamiko/workspace/dealii/tests/fe/interpolate_nedelec.cc:49
```

**Comment by bangerth** [comment]
Uhm, what do you want us to do with this PR? Merge a test that we know fails?

**Comment by bangerth** [comment]
For the record, this is the piece of code:
```
          for (unsigned int i = 0; i < system_matrix.m (); ++i)
            for (unsigned int j = 0; j < system_matrix.n (); ++j)
              for (unsigned int q_point = 0; q_point < n_edge_points;
                   ++q_point)
                system_matrix (i, j)
                += boundary_weights (q_point, j)
                   * lobatto_polynomials_grad[i + 1].value
                   (this->generalized_face_support_points[q_point]
                    (1));
```
I assume the issue is in the last line: `generalized_*face*_support_points` holds 1d points when in 2d, and taking the component with index 1 is never going to work.

The cheap fix would be to change the 1 into a 0. That's the only reasonable choice given the location of the code. The hard part would be to convince oneself that the result is correct.

**Comment by tamiko** [comment]
@bangerth Well, ideally I want to fix the problem with this pull request. :-D (Hence the WIP).

**Comment by tamiko** [comment]
@bangerth I'll have a look. Checking for correct representation of functions in the polynomial subspace (for higher degree) is at least some sort of "poor man's testing" that I can do. :-)

**Comment by bangerth** [comment]
Yes, correct representation in the subspace is the way to test these things.

**Comment by tamiko** [comment]
Rebased onto #4999 - thus the mess.

A bit of progress, but not much:
```
275: + DEAL::FE_Nedelec<2>(0) 4  vector 0.00000                                                                      
275: + DEAL::FE_Nedelec<2>(1) 12  vector 0.00000        
275: + DEAL::FE_Nedelec<2>(2) 21  vector 5.55112e-17
275: + DEAL::FE_Nedelec<2>(1) 12  vector 0.343649                                                                       
275: + DEAL::FE_Nedelec<2>(2) 21  vector 1.11022e-16                                                      
275: + DEAL::FE_Nedelec<2>(2) 21  vector 1.58727e-16                                                       
275: + DEAL::FE_Nedelec<2>(3) 32  vector 1.17788e-15                   
275: + DEAL::FE_Nedelec<3>(1) 56  vector 5.55112e-17               
275: + DEAL::FE_Nedelec<3>(2) 117  vector 1.11022e-16                               
275: + DEAL::FE_Nedelec<3>(2) 117  vector 0.128996                                              
275: + DEAL::FE_Nedelec<3>(3) 208  vector 0.241009 
```

**Comment by tamiko** [comment]
@bangerth Well, this fixes at least lower order interpolation. What about we merge it?

**Pull request merged**
