### PR TITLE
Simplify logic in RepartitioningPolicyTools::FirstChildPolicy

### PR DESCRIPTION
**Pull request by peterrum**

### CODE REVIEW

**Review by bangerth — APPROVED** [review]
Yes, very nice! This also removes an implicit assumption about how exactly our data structures are laid out.

**Review by kronbichler — APPROVED** [review]

**Comment by peterrum** [comment]
> Yes, very nice! This also removes an implicit assumption about how exactly our data structures are laid out.

@bangerth I don't even know why I did not implement it like this in the first place. It is called first-child policy, i.e., `child(0)`...

**Comment by bangerth** [comment]
On 3/3/22 09:36, Peter Munch wrote:
> It is called first-child policy, i.e., |child(0)|...

Ha, I didn't make that connection either. Our minds are just funny sometimes!

**Pull request merged**
