### PR TITLE
Mark some variables as const in the high order VTK output

### LINKED ISSUE #6999: Address comments in #6994
It would be good for us to attend to the few remaining comments listed in #6994.

### PR DESCRIPTION
**Pull request by kronbichler**
Fixes #6999, which addresses some issues left in #6994.

### CODE REVIEW

**Comment by davydden** [comment]
would you mind using `initlog`? I think that's the only comment from @jppelteret that is not addressed in this PR.

**Comment by kronbichler** [comment]
Thanks for checking so carefully, I forgot that one. Fixed now.

**Comment by jppelteret** [comment]
Thanks for making these fixes @kronbichler!

**Pull request merged**
