### PR TITLE
Simplify typos workflow.

### PR DESCRIPTION
**Pull request by marcfehling**
Follow-up to #17564, #17482.

### CODE REVIEW

**Comment by marcfehling** [comment]
We also check filenames which do not have a `line_num` key. That's why the CI currently fails, as we try to create the line_num in the python script.

https://github.com/dealii/dealii/blob/855fbcfd338c484f02c42bc0f425fbbaa08d6724/.github/workflows/typos.yml#L59-L61

This leads to hard to read errors:
```
Warning: perhaps "iy" should be "it".
Traceback (most recent call last):
  File "<string>", line 11, in <module>
KeyError: 'line_num'
Warning: perhaps "iy" should be "it".
```

**Comment by marcfehling** [comment]
I updated the filename, but there are still plenty of typos reported (in the new version of typos).

**Comment by marcfehling** [comment]
Okay, back to the beginning. Let's clean up the typos check first.

- The old version 1.19.0 worked for our repository, so let's stick to that version for now.

- I simplified the `typos` check that it only runs the corresponding `github-action`, and moved it into the `indent.yml` file.

- `dependabot` now ignores any update on `typos` for the moment.

**Comment by marcfehling** [comment]
To give you an example how this version reports errors, I pushed a previous typo to a separate branch, and the CI caught it like this:
https://github.com/marcfehling/dealii/actions/runs/10461880254/job/28971092746

**Review by kronbichler — APPROVED** [review]

**Review by gassmoeller — APPROVED** [review]
Yes, I think this makes sense. As I mentioned in #17564 fixing the typos version is a good choice, because the version bump can introduce false positive typo reports. I forgot that we ignored typos for dependabot in ASPECT and didnt include it in my PR.

This change will mean a bit less convenience features, i.e. no file with suggested fixes and no warnings on the PR page. But I guess the simplification is worth it (your suggestion is actually closer to what I originally proposed for ASPECT before it was changed during review). :+1:

**Pull request merged**
