### PR TITLE
[RFC] Add a testcase that current fails.

### PR DESCRIPTION
**Pull request by bangerth**
This shows a failure inside Trilinos's AztecOO package when one tries to solve
a linear system with a perfectly SPD matrix and a preset solution vector (the
problem does not occur when the solution vector is not preset). With the preset
solution, we get this error:

1: --------------------------------------------------------
1: An error occurred in line <282> of file </u/bangerth/p/deal.II/1/dealii/source/lac/trilinos_solver.cc> in function
1:     void dealii::TrilinosWrappers::SolverBase::do_solve(const dealii::TrilinosWrappers::PreconditionBase&)
1: The violated condition was:
1:     false
1: The name and call sequence of the exception was:
1:     ExcMessage('AztecOO::Iterate error code -3: ' 'loss of precision')
1: Additional Information:
1: AztecOO::Iterate error code -3: loss of precision
1: --------------------------------------------------------

### CODE REVIEW

**Comment by bangerth** [comment]
Calling on our Trilinos experts for help. @Rombur @kronbichler Any idea what may be going on here?

**Comment by Rombur** [comment]
With deal.II solver, I get:
Convergence step 18 value 0
and with Trilinos, I get:
Iterative method reported convergence failure in step 18. The residual in the last step was 2.63865e-17.
and your tolerance is 2.5946e-17 

So I'm not sure there is anything wrong with Trilinos. It looks to me that your are at machine precision. You should probably try to scale the matrix.

**Comment by bangerth** [comment]
I tried multiplying the rhs and preset solution by 1e12 and it didn't make a difference (as it should). Machine precision is only relevant in a relative sense, so I don't think it should matter here.

But so you're saying that you get a regular iteration failure, not the AztecOO message? What Trilinos version are you working with?

**Comment by Rombur** [comment]
Trilinos returns an integer. I commented the code in deal.II that throws the exception to see what was the residual.

**Comment by Rombur** [comment]
Multiplying the rhs by 1e12 fixed it for me. It converges without any problem. If you don't multiply the rhs by 1e12 all the elements in the vector solution are around 1e-13 and 1e-16. You are multiplying terms that 15 orders of magnitude of difference and then you add them. You should have some pretty bad round-off error, shouldn't you ?

**Comment by bangerth** [comment]
But what happens if you multiply *both* `f` and `u` by 10^12?

Round-off only happens if you *add* numbers of different size, not if you multiply them. Here, A is large and u,f are small. So computing the residual `f-Au` should not be a problem: you don't lose in the product of `A` and `u`, and the sizes of `f` and `Au` are comparable so it should also be ok. That's why I say that the right test multiplies both `f` and the preset `u` by the same factor.

**Comment by bangerth** [comment]
So, if I multiply both u and f by 1e12, the failure still happens. If I multiply both with 1e18, the failure disappears. I can only imagine that AztecOO has an absolute tolerance programmed in somewhere. That of course doesn't make any sense.

**Comment by Rombur** [comment]
So I looked in Aztec. What happens is that Aztec computes the residual inside CG and uses it to check the convergence. Then, it compares this residual to the "true" residual. The loss of accuracy is triggered if 
```
fabs(residual - true_residual) > residual_tolerance
```
Given that deal.II solver has a residual of 0 after 18 steps and that Trilinos also stops after 18 steps, I guess it also finds a residual of zero. Then, it compares the computed residual with the true residual, which is 2.6e-17. Since this is larger than the tolerance the error is triggered. When you multiply the rhs by 1e18, the difference between the computed residual and the true residual is below the tolerance, so everything is fine.

**Comment by bangerth** [comment]
So would you agree that the real test they use should actually be of the form
```
  fabs(residual - true_residual) > some_eps * residual_tolerance/fabs(max(residual ,true_residual)
)
```
? Using absolute residuals wouldn't make much sense if you happened to have a small rhs vector.

**Comment by tjhei** [comment]
That would make sense. The questions is how we want to deal with this problem for now. There is a way to scale the linear system inside AztecOO with an ```AZ_SCALING`` object, but the documentation is somewhat "terse" [1].

[1]: http://trilinos.org/docs/dev/packages/aztecoo/doc/html/structAZ__SCALING.html

**Comment by Rombur** [comment]
Actually, this condition depends on the convergence criteria given to AztecOO. In deal.II, we use the non-scaling criteria, i.e. the comparison is done on the absolute value. If we choose an other criteria for example a relative tolerance on the rhs, the residuals are scaled in the comparison.

**Comment by kronbichler** [comment]
I could not reproduce this on all my Trilinos installations, but I agree on the problem.
@Rombur So the culprit is setting 'AZ_conv' to 'AZ_noscaled' in trilinos_solver.cc:263? I tried AZ_r0 (residual must be reduced by the given value) and AZ_rhs (residual must be smaller than the right hand side norm times the given tolerance; without solution preset, the same as AZ_r0). The full list of options is
AZ_r0,AZ_rhs,AZ_Anorm,AZ_noscaled,AZ_sol,AZ_weighted,AZ_expected_values,AZ_inf_noscaled
as far as I can see from the file packages/aztecoo/src/az_aztecf.h

@Rombur which settings should work? Can we use any of these settings for our code? It might be problematic that we use absolute tolerances for our SolverControl structure but my initial tests did not help.

**Comment by Rombur** [comment]
If I change AZ_noscaled to AZ_rhs, I get something really strange. Trilinos still returns a loss of precision but the residual returned by deal.II is zero...
Maybe instead of throwing an error before we check the residual, we could throw it only if our check fails.
Also since we get slightly different results using AZ_noscaled and AZ_rhs, we could let the user decide the convergence criteria using the AdditionalData structure.

**Comment by Rombur** [comment]
@bangerth Do you get this error somewhere else than on the quarks? I tried on my laptop with the same version of gcc (gcc 4.9.1) and the test passes without any problem. Also deal.II solver needs once less iteration to converge on my laptop.

The only difference is that on my laptop, I'm using the precompiled GCC while on the quarks I'm using the GCC that you compiled. Maybe you compiled GCC with different flags?

**Comment by bangerth** [comment]
Bruno and I had a conversation about this yesterday. I can't reproduce on my laptop. It may in fact be a machine or compiler specific thing.

@Rombur : Can you reference the place from where you copied the condition that fails? I'd like to take a look at that place in AztecOO to understand what's happening.

**Comment by Rombur** [comment]
The error is thrown at packages/aztecoo/src/az_cg.c: 406
The condition is check at packages/aztecoo/src/az_util.c: 1418
The quantities checked are computed at packages/aztecoo/src/az_convergence.c: 73 
In deal.II, we use the condition AZ_noscaled.

Be careful when you read the comments they don't always match the code.

**Pull request closed without merging**
