### PR TITLE
Introduce DEAL_II_UNREACHABLE().

### PR DESCRIPTION
**Pull request by bangerth**
See #16536 .

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]

**Comment by masterleinad** [comment]
I find the name confusing if the macro doesn't mimic `std::unreachable`. Since you are replacing `Assert(false, ExcInternalError)` here, I would rather go for `DEAL_II_INTERNAL_ERROR` or so.

**Comment by bangerth** [comment]
What I meant to indicate is that it is a *very specific* internal error, namely that we run into a place where we shouldn't be able to get. We have historically used `ExcInternalError` to indicate this, but I think it's worth thinking about whether that's the right name. I'm open to other suggestions.

I hear what you're saying about not doing the same thing as `std::unreachable()`. `std::unreachable()` is defined as *telling* the compiler that we can't get here. My macro `DEAL_II_UNREACHABLE()` in contrast is about *checking* that we don't get here, and aborting the program if we do. I would not be greatly surprised if compiler writers *implement* the former to do the latter, but that's a different question. Perhaps `DEAL_II_SHOULDNT_GET_HERE()` is a better name, even if longer?

**Comment by bangerth** [comment]
Anyone got a better name given that @masterleinad is unhappy about the current one?

**Comment by tamiko** [comment]
@bangerth I am happy with any naming choice but I do see @masterleinad 's point. So what about `DEAL_II_ASSERT_UNREACHABLE()` [1]? Because in effect you are asserting that the code position is unreachable. :-)

[1] `DEAL_II_ENSURE_UNREACHABLE()` is slightly worse.

**Comment by masterleinad** [comment]
`DEAL_II_ASSERT_UNREACHABLE` sounds good to me.

**Review by masterleinad — APPROVED** [review]

**Comment by bangerth** [comment]
I changed the name as suggested!

**Review by tamiko — APPROVED** [review]

**Pull request merged**
