### PR TITLE
Fix mentioning of sum variant for Tensor

### PR DESCRIPTION
**Pull request by masterleinad**
Improves #5962.

### CODE REVIEW

**Comment by bangerth** [comment]
Ah, `@relatesalso` must be new. We use `@relates` in a lot of places and I've always been bothered by the fact that the documentation then no longer shows up in the namespcae it was placed in. Should we use it in more places? 

And does the doxygen version we use on the periodic doc build support `@relatesalso`?

**Comment by davydden** [comment]
Nice, thanks!

**Comment by masterleinad** [comment]
> And does the doxygen version we use on the periodic doc build support @relatesalso?

Yes, that seems to work: https://www.dealii.org/developer/doxygen/deal.II/namespaceUtilities_1_1MPI.html#add36cb2862973c06be029415bc72c524

> Ah, @relatesalso must be new. We use @relates in a lot of places and I've always been bothered by the fact that the documentation then no longer shows up in the namespcae it was placed in. Should we use it in more places?

The question is whether we ever use `@relates` purposefully to move documentation. Probably, it doesn't hurt to have the same documentation at multiple places.

**Comment by bangerth** [comment]
On 02/27/2018 01:30 PM, Daniel Arndt wrote:
> The question is whether we ever use |@relates| purposefully to move 
> documentation. Probably, it doesn't hurt to have the same documentation 
> at multiple places.

I don't think we purposefully move documentation. And I see no reason 
not to list things twice.

**Comment by davydden** [comment]
same here, i don't mind mentioning things twice.

**Pull request merged**
