### PR TITLE
[9.0] Release tasks step 8: remove unfinished steps

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Comment by drwells** [comment]
This just removes two folders so I think we can merge as-is.

**Comment by drwells** [comment]
step-50 runs and produces nice output, but the `results.dox` file is completely out of date (indeed, I only need 10 CG iterations for *every* mesh refinement cycle). I do not believe that we should include it unless someone is willing to rewrite it.

**Comment by drwells** [comment]
(by 'rewrite it' I mean the results file)

**Comment by bangerth** [comment]
I agree that we should only include programs that are indeed finished and complete. We have a reputation for good documentation, let's not  put something up that's not complete or correct.

**Pull request merged**
