### PR TITLE
Add constexpr to Point ctor and member functions with unit test

### LINKED ISSUE #16243: Modernize Tensor and Point
It all begins when I want a constexpr Point in my project. I felt it strange that dealii does not support constexpr `Point<dim>` while `Tensor` does.

### Modernize some member functions
Since we require C++14 nowadays (btw the README did not list c++14 **as mandatory** but only in the changes #13665), we could remove some outdated workarounds in these antiques.
- add as many constexpr as possible to `Point<dim>`
- use `= default` instead of explicit define Point::Point()
- use `std::array` instead of c-style array for `Tensor::values`
- The Point ctors that accepts one, two, three Number for 1,2,3D points only is weird, should we consider a better way for it?
  - `std::initializer_list` and check for size
  - use `Point(const Number = {}, const Number = {}, const Number = {})` and define them explicitly with different dim

In addition, there is a strange macro if in `Tensor::operator[]`, do we have an unexpected `#endif` here?
image

### Opinions about Point<0>
Though it is a workaround for `Quadrature<1>` to accept sub quadrature. I think it is better to add a specialization for Quadrature<0> that deletes certain ctor than to allow `dim == 0` for Tensor and Point.

### PR DESCRIPTION
**Pull request by RichardYCJ**
This will close #16243

### CODE REVIEW

**Comment by bangerth** [comment]
If you want, add a second commit that adds a file to `doc/news/changes/minor` (in the same format as the files there) that explains what you changed in a sentence or two!

**Review by masterleinad — APPROVED** [review]

**Comment by bangerth** [comment]
I see now why you made the change in `geometry_info.h`. Currently, we get this error:
```
In static member function ‘static unsigned int dealii::GeometryInfo<dim>::child_cell_on_face(const dealii::RefinementCase<dim>&, unsigned int, unsigned int, bool, bool, bool, const dealii::RefinementCase<(dim - 1)>&) [with int dim = 2]’,
    inlined from ‘static unsigned int dealii::GeometryInfo<dim>::face_to_cell_vertices(unsigned int, unsigned int, bool, bool, bool) [with int dim = 2]’ at /__w/dealii/dealii/include/deal.II/base/geometry_info.h:4763:28,
    inlined from ‘unsigned int dealii::ReferenceCell::face_to_cell_vertices(unsigned int, unsigned int, unsigned char) const’ at /__w/dealii/dealii/include/deal.II/grid/reference_cell.h:1899:56,
    inlined from ‘dealii::Point<dim> dealii::ReferenceCell::closest_point(const dealii::Point<dim>&) const [with int dim = 3]’ at /__w/dealii/dealii/source/grid/reference_cell.cc:1020:46:
/__w/dealii/dealii/include/deal.II/base/geometry_info.h:4444:57: error: ‘subcells[0][2][<unknown>][2]’ may be used uninitialized [-Werror=maybe-uninitialized]
 4444 |   return subcells[face_flip][ref_case - 1][face][subface];
      |                                                         ^
/__w/dealii/dealii/include/deal.II/base/geometry_info.h: In member function ‘dealii::Point<dim> dealii::ReferenceCell::closest_point(const dealii::Point<dim>&) const [with int dim = 3]’:
/__w/dealii/dealii/include/deal.II/base/geometry_info.h:4429:5: note: ‘subcells’ declared here
 4429 |     subcells[2][RefinementCase<2>::isotropic_refinement][faces_per_cell]
      |     ^~~~~~~~
```
I must admit that I don't understand where that comes in. The place in question is here:
```
  const unsigned int
    subcells[2][RefinementCase<2>::isotropic_refinement][faces_per_cell]
            [max_children_per_face] = {
              {
                // Normal orientation (face_flip = false)
                {{0, 0}, {1, 1}, {0, 1}, {0, 1}}, // cut_x
                {{0, 1}, {0, 1}, {0, 0}, {1, 1}}, // cut_y
                {{0, 2}, {1, 3}, {0, 1}, {2, 3}}  // cut_xy, i.e., isotropic
              },
              {
                // Flipped orientation (face_flip = true)
                {{0, 0}, {1, 1}, {1, 0}, {1, 0}}, // cut_x
                {{1, 0}, {1, 0}, {0, 0}, {1, 1}}, // cut_y
                {{2, 0}, {3, 1}, {1, 0}, {3, 2}}  // cut_xy, i.e., isotropic
              }};

  return subcells[face_flip][ref_case - 1][face][subface];
```
Nothing here seems to relate to `Point`. Anyone has any ideas about this?

**Comment by bangerth** [comment]
@RichardYCJ Can you try what happens when you rebase this patch on top of the current `master` branch (which now contains #16266)?

**Comment by RichardYCJ** [comment]
The error still persists.

Actually `dealii::Point<dim> dealii::ReferenceCell::closest_point(const dealii::Point<dim>&) const [with int dim = 3]` at **source/grid/reference_cell.cc:1020:46** should not invoke `static unsigned int dealii::GeometryInfo<dim>::child_cell_on_face(...) [with int dim = 2]` at **include/deal.II/base/geometry_info.h:4444:57** but the compiler inline it anyway.

I've tried (538756628f6d3648a1900f36db449d78a32910b5) to use **constexpr if** to avoid it but that seems not to work.

**Comment by RichardYCJ** [comment]
To me, `ReferenceCell` should be a template class `ReferenceCell<dim>` that splits different dimensions into different member specializations. This can avoid unexpected instantiation of another dimensional function that will never be reached.

**Comment by RichardYCJ** [comment]
It works! Should I leave this commit or rebase to the new pr after merger?

**Comment by bangerth** [comment]
Please rebase. The last commit should go away in the process.

**Review by masterleinad — APPROVED** [review]

**Comment by bangerth** [comment]
Excellent, thank you for the contribution -- I hope many more are to come!

**Pull request merged**
