### PR TITLE
Let FETools::compute_node_matrix() return its result, rather than take it by reference

### PR DESCRIPTION
**Pull request by bangerth**
This is an incompatible change: `FETools::compute_node_matrix()` used to return its data via reference as one of its arguments. This change now lets the function return it as a regular return object.

There are multiple dimensions to this patch:
* One may argue that it would be more efficient to make this change if we had move constructors for type `FullMatrix` (see #898), it doesn't really matter: This function is only called during construction of elements such as RT, ABF, BDM. That is, typically once (or a small number of times) per program run. So I'm not overly concerned about runtime.
* The change is incompatible, but the function was so poorly documented before that I seriously doubt that anyone was actually calling it from user code. It also only serves a really narrow use case.

I find the resulting code just a bit nicer -- both because it saves a line, and because it removes one of those few functions for which the calling convention is reversed: the previous function took the output argument *first*, not *last* as everywhere else.

I could be talked into retaining the old function as an overload that is marked as deprecated, if anyone feels particularly strongly about it.

### CODE REVIEW

**Comment by bangerth** [comment]
Also a follow-up to #3807.

**Comment by drwells** [comment]
@bangerth with RVO I doubt that we would need the move constructor anyway: since there is only one possible object that can be returned any decent optimizing compiler should be able to handle this case.

**Comment by bangerth** [comment]
Yes, that is correct.

I decided to re-add the original function anyway -- we do want to stay backward compatible, and the effort is small here. Give me a minute to see if it still compiles.

**Comment by bangerth** [comment]
OK, new version added -- still compiles.

**Pull request merged**
