### PR TITLE
Fix compilation with boost 1.78.

### LINKED ISSUE #13037: Compatibility with Boost 1.77 and upcoming Boost 1.78
Opening a more detailed issue in favor of #12732 : It is currently not possible to compile against boost 1.77 and 1.78 with (at least) the following three major issues:

(a) The following code in https://github.com/dealii/dealii/blob/master/source/grid/grid_tools.cc#L5634
```
const auto leaf = b_tree.qbegin(bgi::nearest(points[i], 1));
```
triggers
```
.../boost/geometry/algorithms/detail/comparable_distance/interface.hpp:122:21: error: ‘apply’ is not a member of ‘boost::geometry::dispatch::distance<dealii::Point<1>, boost::geometry::model::box<boost::geometry::model::point<double, 1, boost::geometry::cs::cartesian> >, boost::geometry::strategies::distance::detail::comparable<boost::geometry::strategies::distance::cartesian<> >, boost::geometry::point_tag, boost::geometry::box_tag, boost::geometry::strategy_tag_distance_point_box, false>’
```

(b) Just trying to compile `grid_tools.cc` fails with:
```
[... static assert triggers because of: ...]
.../boost/geometry/algorithms/not_implemented.hpp: In instantiation of ‘struct boost::geometry::nyi::not_implemented_error<boost::geometry::point_tag
, boost::geometry::box_tag>’
[... due to: ...]
.../boost/geometry/algorithms/dispatch/distance.hpp:123:8:   required from ‘struct boost::geometry::dispatch::distance<dealii::Point<1>, boost::geometry::model::box<boost::geometry::model::point<double, 1, boost::geometry::cs::cartesian> >, boost::geometry::strategies::distance::detail::comparable<boost::geometry::strategies::distance::cartesian<> >, boost::geometry::point_tag, boost::geometry::box_tag, boost::geometry::strategy_tag_distance_point_box, false>’
```

So I am a bit at a loss here. Does this imply that we lost support for our bounding box implementation due to some internal restructuring? If yes, what shall we do? We will need support with newer versions of boost rather sooner than later.

### PR DESCRIPTION
**Pull request by drwells**
Fixes #13037 - I can now compile the library with 1.78 on my desktop.

I bisected (fortunately Boost.Geometry a header-only library so adding the include directory sufficed) and
https://github.com/boostorg/geometry/commit/6eb9e238bcb37e26dc31d16acf826784a2ba30f4 is where this problem starts for us. See also https://github.com/boostorg/geometry/issues/792 - the easiest fix for all such issues is to just include the project header `boost/geometry/geometry.hpp`.

In this particular case, if you look at the commit which causes `grid_tools.cc` fails to compile, its because we were relying on some implicit includes. In particular, we need the distance header to find the distance between points and boxes.

### CODE REVIEW

**Review by tamiko — APPROVED** [review]

**Comment by tamiko** [comment]
@drwells This is amazingly small fix! Would you mind reverting the CMake check for 1.77? I am verifying that deal.II builds against 1.77 as we speak.

**Comment by drwells** [comment]
I can add it to this PR, but you mentioned here

https://github.com/dealii/dealii/issues/12817#issuecomment-941045199

that there is another problem with Boost.Math - this fix may not be sufficient to get things working with 1.77.

**Review by bangerth — APPROVED** [review]

**Comment by drwells** [comment]
My hybrid boost 1.78 and boost.Geometry 1.77 setup avoids the distance problem so we can probably skip reverting 4e0698c138f8661689f967e481881cf350486462.

**Comment by tamiko** [comment]
@drwells Roger, let's leave for now but for the record: I was able to compile dealii 9.3.1 with this PR against boost 1.77. At least against boost 1.77 with a couple of patches...

**Comment by drwells** [comment]
To be clear, do you mean that we should remove b15edaa4a8bc556e551904285ce11d421daf2659 from this PR?

**Comment by tamiko** [comment]
@drwells I missed the fact that you added it. Let's keep the revert.

**Comment by bangerth** [comment]
Do you want to propose this for backporting to the 9.3 branch?

**Pull request merged**
