### PR TITLE
Remove most <> from tutorials

### PR DESCRIPTION
**Pull request by peterrum**
Or is there an educational purpose in keeping these?

Currently, there are lot of places where s.th. like this is written:
```cpp
SolverRichardson<> solver(solver_control);
```
For the tutorials, I feel it would have more benefit to be explicit about the type:
```cpp
SolverRichardson<Vector<double>> solver(solver_control);
```
or simply write (as proposed by this PR):
```cpp
SolverRichardson solver(solver_control);
```

### CODE REVIEW

**Comment by masterleinad** [comment]
Users often start off from one of the example steps and I think they might face another unexpected problem if the default template argument is used in the tutorial but they changed the vector type.
Hence, I would prefer
```
SolverRichardson<Vector<double>> solver(solver_control);
```
over
```
SolverRichardson solver(solver_control);
```
(admitting that the current syntax looks more like the latter version).

**Comment by bangerth** [comment]
I think that it is this C++17 extension: https://en.cppreference.com/w/cpp/language/class_template_argument_deduction

**Comment by masterleinad** [comment]
Yes, https://godbolt.org/z/uwiZos.

**Comment by masterleinad** [comment]
Admittedly, I wasn't so sure if `CTAD` applied here after seeing that all of the `github` CI and `appveyor` succeded. It seems that they all support C++17.

**Comment by peterrum** [comment]
Thanks for the info! I have made the change!

**Pull request merged**
