### PR TITLE
Remove VectorView.

### PR DESCRIPTION
**Pull request by drwells**
We previously deprecated this class in #5278: see that PR for the justification. I am working on some cleanups to `Vector` which redo its memory management and makes the implementation of `VectorView` impossible.

### CODE REVIEW

**Comment by masterleinad** [comment]
Are you going to merge the functionality of `VectorView` into `Vector` as requested/proposed in #5627?

**Comment by drwells** [comment]
@masterleinad do you mean `ArrayView`?

I do not plan on adding any extra functionality to `ArrayView` in this PR. We frequently create things like `ArrayView<Point<spacedim>>`; it doesn't make sense to define linear algebra operations with that kind of array. 

The issues with `VectorView` come from how it inherits from `Vector` and hence it ends up breaking the Liskov substitution principle a lot. Therefore, the right way to implement a 'linear algebra vector view' would be to add a new class (probably inheriting from `ArrayView`) that has an interface similar to `Vector` but does not have any memory management functions. Such a class may not be necessary: `TensorProductMatrix::vmult` just uses `ArrayView`s and does not seem to require anything more.

However, adding such a class would require adding interfaces aware of it to `LAPACKFullMatrix`, `FullMatrix`, etc. and is way beyond the scope of this PR :)

**Comment by masterleinad** [comment]
No, I was referring to https://github.com/dealii/dealii/issues/5627#issuecomment-352192047 and https://github.com/dealii/dealii/issues/5627#issuecomment-352291320.
Anyway, I am fine with this PR but don't want to merge directly due to the discussions in #5627.

**Comment by drwells** [comment]
@masterleinad Whoops; I completely missed that last paragraph in #5627. I now understand your original question.

I do not plan on adding the replacement functionality to `Vector` (i.e., implement a non-owning mode) in this PR. I am glad that you brought it up: I'd like to remove `VectorView` now so that we can clean up `Vector`'s memory management (we can delete a ton of code if we just use `AlignedVector`); this won't work if we elect to merge `VectorView` and `Vector` so I will hold off for now.

I would prefer to not merge the two since it will require making `Vector` a lot more complicated for something we do not use at all in the library itself. I think others disagree; should we vote on this?

**Comment by bangerth** [comment]
I'm in favor of merging as the patch stands. Are 4 approving reviews good enough?

**Comment by masterleinad** [comment]
I'll merge tomorrow if there are no objections until then.

**Pull request merged**
