### PR TITLE
Remove DEAL_II_WITH_SIMPLEX_SUPPORT

### PR DESCRIPTION
**Pull request by peterrum**

### CODE REVIEW

**Review by marcfehling — APPROVED** [review]

**Comment by marcfehling** [comment]
A few tests fail on the `gcc-serial` runner:
```
The following tests FAILED:
	225 - simplex/step-12c.debug (Failed)
	246 - simplex/matrix_free_02.debug (Failed)
```

**Review by tjhei — APPROVED** [review]
Looks good. Did you all agree to do this step before the release? Makes sense to me. No harm ...

**Comment by peterrum** [comment]
> Looks good. Did you all agree to do this step before the release? Makes sense to me. No harm ...

Yes, we did. Independent experience showed that enabling the flag per default did not harm.

**Pull request merged**
