### PR TITLE
 Replace HyperShellBoundary by SphericalManifold in tests

### PR DESCRIPTION
**Pull request by masterleinad**
The changes in the output seem to be sufficiently small to be OK.
Tests that changed are:
- `tests/bits/volume_2.cc` where we now also log the relative error. The increase in the error can be explained by `FESubfaceValues` placing the artificial center not with respect to the manifold. This is way the out put for `FEFaceValues` is more accurate.
- `tests/codim_one/extract_boundary_mesh_03.cc` and `tests/codim_one/extract_boundary_mesh_04.cc` where we relaxed the absolute threshold from `0.` to a relative threshold of magnitude `1.e-15`.
- `tests/grid/normal_vector_02.cc` where we additionally log the normal vectors.

The `Clean up` commit replaces all `add_boundary` calls by `add_manifold` and the `grid/tria_boundary_lib.h` header by the `grid/manifold_lib.h` header (except for the `codim_one/extract_boundary_mesh_10.cc` for which it doesn't make sense to replace `Boundary` by `Manifold`).

Based on #5711. Related to #4921.

### CODE REVIEW

**Comment by bangerth** [comment]
I'll be happy to take another look once we have figured out what to do in #5711.

**Comment by kronbichler** [comment]
Now that #5711 is merged can you rebase so I and @bangerth can have a final look?

**Comment by masterleinad** [comment]
I rebased and fixed a missing `else` in `SphericalManifold::normals_at_vertices` that was detected.

**Pull request merged**
