### PR TITLE
GC: compressed weights -> AlignedVector

### PR DESCRIPTION
**Pull request by peterrum**

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]
Looks good.

**Review by tjhei — APPROVED** [review]
Perfect, this fixes the segfaults on my AMD workstation when running ``ctest -R global-coarsen``.

**Comment by tjhei** [comment]
thanks, @peterrum ! :-)

**Comment by peterrum** [comment]
Thanks for checking @tjhei!

**Comment by kronbichler** [comment]
I am surprised that we did not see it before, because typically inside an `std::vector` with AVX-512 there is a 75% chance of getting an unaligned access (that segfault when loading a plain `VectorizedArray` aka `__m512d`).

**Comment by tjhei** [comment]
@kronbichler Would it make sense to check alignment in debug mode in the constructor of ``VectorizedArray<double>``?

**Pull request merged**
