### PR TITLE
Add assertions that we can only combine elements defined on the same reference cell.

### PR DESCRIPTION
**Pull request by bangerth**
This would have made it much simpler to spot the issue in #17000.

### CODE REVIEW

**Review by drwells — CHANGES_REQUESTED** [review]
I'd like to reduce duplication a little bit.

**Comment by bangerth** [comment]
I moved the assertions into the `initialize()` function as suggested. My original thought was that I want to catch the error in the first place possible, which would have been at the top of the constructor, not in a place we call from there. But what you suggest makes sense.

That said, in reality we never actually catch the error there. That's because before we even get to run the body of the constructor, we initialize the member variables and the base classes, and call functions in `FETools::Compositing` that *also* have these assertions. That's where we currently trigger the assertion for the first time. I added the assertions *also* to `FESystem` because I wanted to make sure that all places that have the assumption that the reference cell must be the same are independently guarded.

**Comment by drwells** [comment]
Thanks :)

> That's where we currently trigger the assertion for the first time.

Yes, but as always "it's not paranoia if they're actually out to get you". We should always assert things that we expect to be true.

**Review by drwells — APPROVED** [review]

**Comment by bangerth** [comment]
> Yes, but as always "it's not paranoia if they're actually out to get you".

Ha, I love this! And our users (us included) are definitely out to get us!

**Review by kronbichler — APPROVED** [review]

**Pull request merged**
