### PR TITLE
CMake: Simplify some logic in DEAL_II_ADD_TEST and add verbose error messages

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Comment by tamiko** [comment]
```
  A comparison file (ending in .output or .run-only) has been picked up with
  multiple suitable source files or parameter files:

  /jenkins/workspace/dealii_PR-13392/tests/sundials/arkode_01.cc
  /jenkins/workspace/dealii_PR-13392/tests/sundials/arkode_01.prm

  There must be exactly one source or parameter file.
```

:sunglasses:

**Review by masterleinad — APPROVED** [review]
Looks OK to me.

**Comment by tamiko** [comment]
@tjhei 
> I didn't even know about the .prm as a test feature. How does that even work without an executable?

:sunglasses: 

Yes, these tests need an executable target. For this the CMake variable `${TEST_TARGET}` (or `${TEST_TARGET_(DEBUG|RELEASE)}`) has to be set accordingly [1].

[1] https://www.dealii.org/developer/users/testsuite.html

**Comment by tamiko** [comment]
@tjhei *ping*

**Comment by tamiko** [comment]
Applied the suggested change and rebased to resolve the merge conflict.

**Pull request merged**
