### PR TITLE
Move DataOutInterface<dim,spacedim>::get_vector_data_ranges () to header...

### PR DESCRIPTION
**Pull request by l-korous**
....

### CODE REVIEW

**Comment by bangerth** [comment]
We almost never define functions within the class declaration itself. But it's ok if you moved the definition to the bottom of the `.h` file (after the class declaration) where we typically define inline and template functions.

This patch is ok if you could do that.

**Comment by l-korous** [comment]
Now when I think about it, it would be more coherent with the rest of the library if the proper instantiations were in the file \source\base\data_out_base.inst.in.

I only moved it to the header file so that I did not to explicitly specify the instantiations.

What do you think?

**Comment by bangerth** [comment]
I don't think you should have to. The function has no template parameters of its own. If you instantiate the class `DoFHandlerInterface<dim,spacedim>` for a particular choice of `dim,spacedim` (as is done in the `.inst.in` file), then this should instantiate all of its member functions as well. This includes the member function you are currently considering here.

You only need to explicitly list member functions for instantiation if they have *additional* template arguments of themselves.

**Comment by bangerth** [comment]
Any news?

**Comment by l-korous** [comment]
Hi, the issue got away for me. I am not able to tell if this is because we stopped needing to call this method or because I overlooked something in the first place. I am closing this anyhow.

**Pull request closed without merging**
