### PR TITLE
Assert that AffineConstraints got index sets when running in parallel.

### LINKED ISSUE #15987: Add check in AffineConstraints that user provided index set arguments when running in parallel.
This will be easy after #15789 is in. It's just a reminder for myself to do it.

### PR DESCRIPTION
**Pull request by bangerth**
Fixes #15987. In reference to #15375.

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]
Very good, this helps to avoid a common bug.

**Comment by kronbichler** [comment]
Talking about bugs, this is what the CI reports:
```
The following tests FAILED:
	2142 - gla/block_vec_02.mpirun=2.debug (Failed)
	2143 - gla/block_vec_02.mpirun=4.debug (Failed)
	2176 - gla/vec_03.mpirun=10.debug (Failed)
	2177 - gla/vec_03.mpirun=4.debug (Failed)
	2715 - hp/field_transfer_05.mpirun=2.debug (Failed)
	3070 - lac/linear_operator_12.mpirun=2.debug (Failed)
	3073 - lac/linear_operator_12a.mpirun=2.debug (Failed)
	3916 - matrix_free/poisson_dg_hp.mpirun=2.debug (Failed)
	4326 - mpi/fe_tools_extrapolate_01.mpirun=3.debug (Failed)
	4329 - mpi/fe_tools_extrapolate_02.mpirun=3.debug (Failed)
	4332 - mpi/fe_tools_extrapolate_03.mpirun=10.debug (Failed)
	4333 - mpi/fe_tools_extrapolate_03.mpirun=3.debug (Failed)
	4336 - mpi/fe_tools_extrapolate_04.mpirun=3.debug (Failed)
	4339 - mpi/fe_tools_extrapolate_05.mpirun=3.debug (Failed)
	4342 - mpi/fe_tools_extrapolate_06.mpirun=10.debug (Failed)
	4401 - mpi/hp_integrate_difference.mpirun=10.debug (Failed)
	4402 - mpi/hp_integrate_difference.mpirun=4.debug (Failed)
	4475 - mpi/interpolate_04.mpirun=10.debug (Failed)
	4476 - mpi/interpolate_04.mpirun=4.debug (Failed)
	4480 - mpi/interpolate_to_different_mesh_01.mpirun=3.debug (Failed)
	4482 - mpi/interpolate_to_different_mesh_02.mpirun=3.debug (Failed)
	4574 - mpi/multigrid_adaptive.mpirun=4.debug (Failed)
	4577 - mpi/multigrid_uniform.mpirun=4.debug (Failed)
	4864 - mpi/parallel_vector_back_interpolate.mpirun=4.debug (Failed)
	4866 - mpi/parallel_vector_back_interpolate_02.mpirun=4.debug (Failed)
	4868 - mpi/parallel_vector_interpolate.mpirun=4.debug (Failed)
	5063 - mpi/step-37.mpirun=7.debug (Failed)
	5150 - mpi/trilinos_distribute_03.mpirun=2.debug (Failed)
	5255 - multigrid/mg_data_out_05.mpirun=2.debug (Failed)
	5406 - multigrid-global-coarsening/mg_data_out_05.mpirun=2.debug (Failed)
	5409 - multigrid-global-coarsening/mg_transfer_a_01.mpirun=2.debug (Failed)
	5413 - multigrid-global-coarsening/mg_transfer_a_03.mpirun=2.debug (Failed)
	5419 - multigrid-global-coarsening/mg_transfer_p_01.mpirun=2.debug (Failed)
	5422 - multigrid-global-coarsening/mg_transfer_p_02.mpirun=2.debug (Failed)
	5427 - multigrid-global-coarsening/mg_transfer_p_04.mpirun=4.debug (Failed)
	5430 - multigrid-global-coarsening/mg_transfer_p_05.mpirun=4.debug (Failed)
	5432 - multigrid-global-coarsening/mg_transfer_p_06.mpirun=4.debug (Failed)
	5467 - multigrid-global-coarsening/non_nested_transfer_01.mpirun=2.debug (Failed)
	5470 - multigrid-global-coarsening/non_nested_transfer_02.mpirun=2.debug (Failed)
	5473 - multigrid-global-coarsening/non_nested_transfer_03.mpirun=2.debug (Failed)
	5476 - multigrid-global-coarsening/non_nested_transfer_04.mpirun=2.debug (Failed)
	6403 - remote_point_evaluation/vector_tools_evaluate_at_points_02.mpirun=8.debug (Failed)
	6830 - simplex/step-67.mpirun=2.debug (Failed)
	7166 - trilinos/direct_solver_3.mpirun=2.debug (Failed)
```

**Comment by bangerth** [comment]
Yes, I saw that too. It's perhaps not surprising that a whole lot of tests fail :-(

**Comment by bangerth** [comment]
The only good thing I can see in all of these failing tests is that the patch catches actual errors...

**Review by kronbichler — APPROVED** [review]
Great, thank you. I will have a look at the tester, there might be some more uncovered bugs. Indeed, this is a common flaw we have in many pieces, and it is good to finally address it.

**Pull request merged**
