### PR TITLE
Add function to access timer data from within program

### PR DESCRIPTION
**Pull request by class4kayaker**
Implementation of the function suggested in geodynamics/aspect#1566, including a small test.

### CODE REVIEW

**Comment by drwells** [comment]
This looks good to me. Since this is a new feature, though, would you mind doing the following C++11 things? What you have is valid but we can make things a bit nicer with the new language features.

1. Use `enum class` instead of `enum`.
2. Rewrite
```cpp
for (std::map<std::string, Section>::const_iterator
     i = sections.begin(); i!= sections.end(); ++i)
```
as
```cpp
(for const auto &section : sections)
```
(or whatever reference variable name you think is best).

**Comment by drwells** [comment]
Also, would you please add a changelog entry documenting this addition?

**Comment by kronbichler** [comment]
> Use `enum class` instead of `enum`.

I'm not sure about this one: There are already two `enum` definitions inside this class, so making the new data structure an `enum class` seems inconsistent because one needs to specify the scope for `TimerOutput::OutputData::total_wall_time` as opposed to the unscoped names of `OutputFrequency` and `OutputType`. Thus, given the previous design my feeling is that blending two variants of enums with different scopes is worse than sticking with the old (albeit non-ideal) naming scheme.

**Comment by drwells** [comment]
I did not think of that: lets not mix `enum` implementations

**Comment by class4kayaker** [comment]
Changelog entry added and uses auto for loop.

**Comment by drwells** [comment]
This looks good. I have one more request: would you mind squashing these down into a single commit? Otherwise this is ready to go.

**Comment by class4kayaker** [comment]
Squashed and rebased onto master

**Comment by drwells** [comment]
Thanks!

**Pull request merged**
