### PR TITLE
Make ArrayView objects from boost::container::small_vector.

### PR DESCRIPTION
**Pull request by bangerth**
In #16103 and then in #16123 , I introduced `AffineConstraints::add_constraint()` that takes an `ArrayView` object of the array of rhs pairs for a constraint. In the library, we typically use `std::vector` for this array, but we typically know that these arrays are pretty small and it would be nice to use `boost::container::small_vector` for that. For this to work, I need to be able to create `ArrayView` objects from `boost::container::small_vector`. This patch does that.

### CODE REVIEW

**Comment by drwells** [comment]
I don't have particularly strong feelings about it either way, but is there a significant advantage to adding another constructor over the existing alternatives of
```cpp
boost::container::small_vector<int, 4> ints(n);
make_array_view(ints.begin(), ints.end()); // 1
make_array_view(ints.data(), ints.size()); // 2
```
for these use cases?

**Comment by bangerth** [comment]
I would be happy to put that on my TODO list as a follow-up, if you allow me to defer coming up with the generic alternative to a separate PR. For the moment, I have pending patches that rely on this, and so I wouldn't mind if we were to merge this...

**Review by kronbichler — APPROVED** [review]
I am ok with deferring the generic solution to a later PR, but I would be very happy if we could implement that because the number of specializations keep increasing.

**Comment by bangerth** [comment]
Yes, I marked #16135 as for the next release. I hope to get to it much sooner.

**Pull request merged**
