### PR TITLE
Change Assert to AssertThrow in the tests.

### LINKED ISSUE #598: Assert vs AssertThrow in the testsuite
@Rombur writes:
...................
I checked in the testsuite and we use Assert 2644 times and AssertThrow 63 times. I found several tests that do nothing in release in mode :( Should we just change all of the Assert to AssertThrow or go through all the tests and see what's appropriate ?
...................

It's a good question. I don't know what to do. We could:
- Ignore the issue. Most of these tests probably still produce output that is indicative of whether the code worked. We run 7200 tests, if even 100 of those don't do anything in release mode, then that's still only 1%.
- Make a wholesale change. We have a few tests that explicitly want exceptions instead of aborts from `Assert` but that I think they can only (and probably do) only run in debug mode.
- Other options?

### PR DESCRIPTION
**Pull request by Rombur**
This fixes #598 It's not perfect but it's much better than what we had. I've run the testsuite and it's seems to work (http://cdash.kyomu.43-1.org/buildSummary.php?buildid=5031the warnings are due to the version of openmpi, I'm using).

### CODE REVIEW

**Comment by bangerth** [comment]
Before we do this, I'd like to share an observation I mad the other day. If you run into a testcase that uses AssertThrow or throws an exception directly, then right now you simply end up with a testcase that silently aborts. It will return a nonzero error code, but the exception is not printed on the screen. So, if we change `Assert` to `AssertThrow` everywhere, we will have to learn to deal with testcases that *look* like the run through just fine when you call them by hand on the command line, but that do not in fact. They're also much more awkward to debug since the debugger no longer just stops at the site of the error :-(

**Comment by Rombur** [comment]
I can go back and add ```try``` and ```catch``` in all the tests.  If I can catch all the exceptions at once it will be easy. I could also just create a new ```Assert``` that also works in release mode.

**Comment by tamiko** [comment]
Please give me half a day to think about this. :-)

@bangerth: This is a bit surprising. A test should set <code>abort_on_exception</code> to false which implies that all <code>Assert</code> are also thrown (<code>exception.cc:336</code>). Or what am I missing?

**Comment by bangerth** [comment]
@tamiko : Only a few tests actually set `abort_on_exception` to false. The vast majority do actually abort the program and print the error message.

**Comment by bangerth** [comment]
We could also try to investigate why this piece in `exceptions.cc` doesn't seem to work:

```
// Newer versions of gcc have a very nice feature: you can set a verbose
// terminate handler, that not only aborts a program when an exception is
// thrown and not caught somewhere, but before aborting it prints that an
// exception has been thrown, and possibly what the std::exception::what()
// function has to say. Since many people run into the trap of not having a
// catch clause in main(), they wonder where that abort may be coming from.
// The terminate handler then at least says what is missing in their
// program.
#ifdef DEAL_II_HAVE_VERBOSE_TERMINATE
namespace __gnu_cxx
{
  extern void __verbose_terminate_handler ();
}

namespace
{
  struct preload_terminate_dummy
  {
    preload_terminate_dummy()
    {
      std::set_terminate(__gnu_cxx::__verbose_terminate_handler);
    }
  };

  static preload_terminate_dummy dummy;
}
#endif
```

**Comment by tjhei** [comment]
> right now you simply end up with a testcase that silently aborts

This is because we are not writing cout/cerr into the test output file, right? If I run a test with ```ctest -V``` I can see exception information on the screen with Assert and AssertThrow.

**Comment by bangerth** [comment]
Uh, maybe I misremember? I had a case where an exception was thrown via `throw "error text"` and nothing was shown on the screen. If you have `AssertThrow` instead of `throw`, you do get text on the screen? In that case, I'm retracting my objections.

**Comment by tjhei** [comment]
If I do ```throw "bla"``` I get
```
    terminate called after throwing an instance of 'char const*'
    Aborted (core dumped)
```
on screen. If I use ```Assert``` or ```AssertThrow``` I get a nice exception msg. Of course neither of these is part of the test output.

**Comment by tamiko** [comment]
> This is because we are not writing cout/cerr into the test output file, right?

Exactly - we're not doing this at the moment.

**Pull request merged**
