### PR TITLE
CMake: adjust tbb path glob to "lib/intel64/gcc*" layout

### PR DESCRIPTION
**Pull request by tamiko**
See #13179

### CODE REVIEW

**Comment by tamiko** [comment]
@marcfehling As a stop-gap solution let's try this one.

**Comment by tamiko** [comment]
@marcfehling  Looking better:

```
-- Include /home/runner/work/dealii/dealii/cmake/configure/configure_1_tbb.cmake
-- Found TBB_LIBRARY
-- Found TBB_DEBUG_LIBRARY
-- TBB_INCLUDE_DIR not found! The call was:
--     FIND_PATH(TBB_INCLUDE_DIR tbb/tbb_stddef.h HINTS /opt/intel/oneapi/tbb/2021.5.0 PATH_SUFFIXES include include/tbb tbb)
-- Found TBB_INCLUDE_DIR
--   TBB_VERSION: 2021.5
--   TBB_LIBRARIES: debug;/opt/intel/oneapi/tbb/2021.5.0/lib/intel64/gcc4.8/libtbb_debug.so;optimized;/opt/intel/oneapi/tbb/2021.5.0/lib/intel64/gcc4.8/libtbb.so
--   TBB_INCLUDE_DIRS: /opt/intel/oneapi/tbb/2021.5.0/include
--   TBB_USER_INCLUDE_DIRS: /opt/intel/oneapi/tbb/2021.5.0/include
-- Found TBB
-- DEAL_II_WITH_TBB successfully set up with external dependencies.
```

**Review by marcfehling — APPROVED** [review]
> @marcfehling Looking better

Nice!

**Review by bangerth — APPROVED** [review]

**Pull request merged**
