### PR TITLE
Modify hessian computations from numerical to analytical differentiation

### PR DESCRIPTION
**Pull request by maieneuro**
This is the same #1272 but from an issue branch rather than master.

### CODE REVIEW

**Comment by bangerth** [comment]
I ran the testsuite on this patch and these are the failures I currently get:
```
        1808 - bits/fe_field_function_03.debug (Failed)
        1809 - bits/fe_field_function_03.release (Failed)
        2142 - bits/fe_field_function_03_vector.debug (Failed)
        2143 - bits/fe_field_function_03_vector.release (Failed)
        3676 - deal.II/fe_values_view_07.debug (Failed)
        3677 - deal.II/fe_values_view_07.release (Failed)
        3753 - deal.II/fe_values_view_13.debug (Failed)
        3754 - deal.II/fe_values_view_13.release (Failed)
        6721 - multigrid/step-39-03.debug (Failed)
        6722 - multigrid/step-39-03.release (Failed)
```
Do these fail for you as well? I think in many of these cases, the new output might be more accurate, but I will only get to investigate tomorrow.

If these tests fail for you as well and you convince yourself that the new output is more correct than the old one, please commit the new output instead of the previous one on top of the current commit. Or leave it to me for tomorrow.

Other than that, the patch looks good to me! Thanks a lot for working on this!

**Comment by maieneuro** [comment]
Yes, these were the floating point errors I was referring to. Fixed the test output files so the test pass now.

**Comment by bangerth** [comment]
Great, thanks for your patience with this! May I ask you to create a follow-up pull request that adds an entry to `doc/news/changes.h` about the fact that some elements now compute second derivatives analytically rather than by finite differences?

**Comment by maieneuro** [comment]
Thanks. I'll do that shortly.

**Comment by bangerth** [comment]
As for the original goal of computing third derivatives: I would do it in steps where in the first step you add the Hessians of the mapping to the `internal::FEValues::MappingRelatedData`, add the corresponding update flag, and implement the computation of this field in the different mapping classes. Then let's commit that. In a second step, you implement computing the third derivatives using the above in the finite element classes. But let's go in small, self-contained steps -- you already saw how difficult it is to keep large patches alive as other development is going on :-)

**Comment by maieneuro** [comment]
Yes, that's a good idea. The first small patch will be a minor optimization to fe_poly_tensor to initialize the scratch data in get_data instead of instantiating vectors every time fill_*_values is called. I'll include the changes.log entry with that. Then I'll move on to implementing mapping transform() for Tensor<3,dim> objects which will make changing hessian computations to analytical in fe_poly_tensor analogous to fe_poly. After that I'll do the jacobian_hessians and hessian_grads in the reference element.

Thanks a lot for the guidance so far.

**Comment by bangerth** [comment]
Good plan. Make sure you always pull from upstream before you create a branch to work on. Changelog entries are only necessary for changes that affect what a user gets to see.

As for the optimization, also take a look at the discussion in #1305.

**Pull request merged**
