### PR TITLE
Takeover (part of #7371): Fix an issue with CSS on Firefox.

### PR DESCRIPTION
**Pull request by masterleinad**
@drwells requested to update the `css` file also for the documentation of version 9.
Let us just take it over to that branch then.

### CODE REVIEW

**Comment by masterleinad** [comment]
Do we need to create a release already? Is it a problem if the branch and the last release are not in sync?

**Comment by drwells** [comment]
Thats a good point; I leapt to the conclusion that we would try to push out 9.0.2 ASAP.

**Comment by bangerth** [comment]
I see no reason why we shouldn't gradually accumulate patches on the release branch that could eventually become a 9.0.2 release. Though I'm much more interested in releasing 9.1 at one point :-)

So: OK with me!

**Comment by masterleinad** [comment]
Can we then merge this?

**Comment by drwells** [comment]
Yes :)

**Comment by masterleinad** [comment]
Thanks!

**Pull request merged**
