### PR TITLE
make test scalapack_10_b shorter

### PR DESCRIPTION
**Pull request by BenBrands**
PR as result of #5958 
ping @davydden & @drwells

### CODE REVIEW

**Comment by davydden** [comment]
could you please run indentation script?

**Comment by davydden** [comment]
./run-tests

**Comment by drwells** [comment]
This lowers the run time to the much more reasonable 30s with oversubscription: much better than 297s.

**Comment by drwells** [comment]
I don't think any of the testers will actually execute scalapack tests so I suggest we merge as-is without running them.

**Pull request merged**
