### PR TITLE
Enable PYTHON_BINDINGS in linux-release-serial

### PR DESCRIPTION
**Pull request by peterrum**

### CODE REVIEW

**Comment by luca-heltai** [comment]
This won't work, unless we enable building through a docker image.

~~~
CMake Error at contrib/python-bindings/CMakeLists.txt:28 (MESSAGE):
  DEAL_II_COMPONENT_PYTHON_BINDINGS has unmet configuration requirements:
  Python bindings require an external boost library, but deal.II was
  configured with bundled boost.
~~~

**Comment by luca-heltai** [comment]
Or unless we install boost python

**Review by luca-heltai — APPROVED** [review]

**Comment by peterrum** [comment]
Let's wait. My hope is that the test fails (since I have not rebased yet with your fix).

**Comment by peterrum** [comment]
@luca-heltai I am a bit confused why the test has passed. It definitely compiled the python stuff:
```
[ 98%] Building CXX object contrib/python-bindings/source/CMakeFiles/PyDealII_release.dir/export_cell_accessor.cc.o
[ 98%] Building CXX object contrib/python-bindings/source/CMakeFiles/PyDealII_release.dir/export_point.cc.o
[ 98%] Building CXX object contrib/python-bindings/source/CMakeFiles/PyDealII_release.dir/export_triangulation.cc.o
[ 98%] Building CXX object contrib/python-bindings/source/CMakeFiles/PyDealII_release.dir/export_mapping.cc.o
[ 98%] Building CXX object contrib/python-bindings/source/CMakeFiles/PyDealII_release.dir/export_manifold.cc.o
[ 98%] Building CXX object contrib/python-bindings/source/CMakeFiles/PyDealII_release.dir/export_quadrature.cc.o
[ 98%] Building CXX object contrib/python-bindings/source/CMakeFiles/PyDealII_release.dir/cell_accessor_wrapper.cc.o
[ 98%] Building CXX object contrib/python-bindings/source/CMakeFiles/PyDealII_release.dir/tria_accessor_wrapper.cc.o
[100%] Building CXX object contrib/python-bindings/source/CMakeFiles/PyDealII_release.dir/point_wrapper.cc.o
[100%] Building CXX object contrib/python-bindings/source/CMakeFiles/PyDealII_release.dir/triangulation_wrapper.cc.o
[100%] Building CXX object contrib/python-bindings/source/CMakeFiles/PyDealII_release.dir/mapping_wrapper.cc.o
[100%] Building CXX object contrib/python-bindings/source/CMakeFiles/PyDealII_release.dir/manifold_wrapper.cc.o
[100%] Building CXX object contrib/python-bindings/source/CMakeFiles/PyDealII_release.dir/quadrature_wrapper.cc.o
[100%] Building CXX object contrib/python-bindings/source/CMakeFiles/PyDealII_release.dir/reference_cell_wrapper.cc.o
[100%] Linking CXX shared module ../../../lib/python2.7/site-packages/PyDealII/Release.so
[100%] Built target PyDealII_release
``` 
but it skipped the `export_reference_cell.cc` file what has been just removed later on?

**Comment by luca-heltai** [comment]
Uh? I have no idea how it passed... but at least now we compile also the wrappers.

**Pull request merged**
