### PR TITLE
VectorTools::project_boundary_values documentation edit.

### PR DESCRIPTION
**Pull request by alistairbntl**
- Added a few lines explaining that the behavior of this function
    can change depending on which space the FE lives in.

### CODE REVIEW

**Comment by bangerth** [comment]
Before we go with this patch, I'd actually like to understand the problem a bit better.

I don't actually see how the function differs in behavior based on the conformity of the FE space. What *is* true is that the `project_boundary_values` function only computes the values of those degrees of freedom that are located on the boundary. This implies that, for example, for the `FE_RaviartThomas` element, it can only compute the normal velocity because the DoFs on the boundary only describe the normal velocity but have no tangential component. Those DoFs that have tangential velocity components on the boundary have their support points on faces that (in general) are not part of the boundary, and so the tangential velocity remains unconstrained by this function.

How exactly is your FE space defined, and what does that imply for the considerations above?

**Comment by alistairbntl** [comment]
Thanks for the feedback.

After reading your comments and re-reading the documentation, I understand what is being communicated in the documentation better.  That said, I do find the integral equation shown in the `project_boundary_values` documentation confusing.  If I understand what you've told me, doesn't the specific structure of these integrals depend on the nature of the boundary DoF?  For example, I don't see how the integrals shown in the documentation represent the boundary DoF for RT elements.  Am I missing something obvious here?

Next, let me describe some behavior I've encountered using this function which I find confusing (and I hoped to clarify with this patch).  A full description of the FE I'm testing would be a bit challenging here but I think the following characteristics are most relevant to this discussion:

- The elements are quadratic 2D 'macro elements' (that is, the function space used to construct the FE basis includes four distinct, but continuous quadratic polynomials defined on a four triangle partition of the reference quadrilateral)
- The FE has 16 DoF - two at each node (the function value for the x and y components) and two along each face (one for the face integral of the x component and one for the face integral of the y component)

Therefore, the boundary DoFs for this FE include the function evaluations of the x and y components for the two boundary nodes and an integral for the x and y components along the boundary edge.
Originally I had mistakenly set the `FiniteElementData` to `Hdiv` and tried to impose Dirichlet boundary conditions using `project_boundary_values`.  When I did this, my solution only had the normal component of the boundary conditions imposed.
After correcting the `FiniteElementData` setting to `H1`,  the solution had the correct Dirichlet boundary conditions for both the x and y components of the solution.  Since the DoF on the boundary are the same in both cases, I assumed the flag triggered a change in how the boundary projection was calculated.

**Comment by alistairbntl** [comment]
@bangerth - have you had a chance to look at my comments?

**Comment by bangerth** [comment]
@alistairbntl -- reading through your description again, and looking cursorily through the code, what confuses me is that declaring the conformity of your finite element (`Hdiv` vs `H1`) makes any kind of difference. The implementation of the `project_boundary_values()` function does not reference the conformity. Where I think this is happening is in `matrix_creator.templates.h`, in function `create_boundary_mass_matrix_1`, after around line 970 (after applying #2582) -- there is some code that deals with `Hdiv` conformity, but I actually have no idea what the code does.

I think we would come to a better understanding if someone could figure out (and maybe write better comments) what the code with the `normal_adjustment` actually does.

**Comment by bangerth** [comment]
@alistairbntl -- oh, I didn't mean to shoot down your attempt at improving the situation. Do you have any ideas in the direction outlined in my previous comment?

**Comment by alistairbntl** [comment]
@bangerth --  I didn't take your comment as a shooting this down at all!  I've just been busy lately and this PR was getting stale so I thought I'd take it off the active list and reopen it once I'd figured out how to proceed.

That said, I have thought about your comments, but I still have some questions I need to answer before I can move forward.  Let me outline my current thinking for you:

- As you point out, the inner products used to build the `project_boundary_values()` system are calculated in the `create_boundary_mass_matrix_1` function as part of a `WorkStream`.  If we ignore the `normal_adjustment` vector for a moment, the `create_boundary_mass_matrix_1` function sets up the system of equations exactly as described by the boundary integrals shown in the `project_boundary_values` documentation.

- Now, for `H1` spaces, these boundary integrals are well defined as a result of the trace theorem.  However, for less regular spaces such as `Hdiv` and `Hcurl`, these boundary integrals may not be well defined.  Rather for `Hdiv` we only know the normal component of the function is in H^{1/2}(\Gamma) and for `Hcurl`, the tangential component is in H^{1/2}(\Gamma).  (Recall  H^{1/2}(\Gamma) is a dense subspace of L2(\Gamma)).

- Enter `normal_adjustment`.  `normal_adjustment` is a vector of vectors with `dim` components at each quadrature point.  All terms are initialized to 1, so unless the terms are modified, this vector has no impact on the inner product calculations.  

- The only situation in which `normal_adjustment` is modified (and thus affects the inner product calculations) is when `FiniteElementData` is set to `Hdiv`.  The following example illustrates the modification that is being made to `normal_adjustment` (as I currently understand it):

- Let the boundary point `p1` have a normal-vector (n_{1},n_{2}) such that n_{1}^{2} + n_{2}^{2} = 1.  If `FiniteElementData` is set to `Hdiv`, the `normal_adjustment` entry associated with `p1` will change from `(1,1)` to `(n_{1}^{2}, n_{2}^{2})`.

- The net result is that the inner product _almost_ calculates the normal component of the functions.  (To see the inner product calculation look at at lines 1013-1018 in `matrix_creator.templates.h` after applying #2582.)  In 2D, if either n_{1} = 0 or n_{2} =0, then this makes sense because (\phi_{i} \cdot n) (\phi_{j} \cdot n) = (\phi_{i,1} n_{1} \phi_{j,1} n_{1}) + (\phi_{i,2} n_{2} \phi_{j,2}n_{2} = n_{1}^{2} \phi_{i,1} \phi_{j,1} + n_{2}^{2} \phi_{i,2} \phi_{j,2}).  Otherwise, it seems to me that the cross terms like \phi_{i,1} \phi_{j,2} n_{1} n_{2} are missing.

- I'm still not sure what exactly is going on here and I need to do some more investigating.  In particular, all my test problems have either n_{1} =0 or n_{2} = 0.  I really need to investigate an example where this does not hold.
  
- Another thing that still confuses me is that nothing happens to `normal_adjustment` when `FiniteElementData` is set to `Hcurl` (the conditional statement on 979-980 is only triggered if `FiniteElementData` is `Hdiv`).  It seems there should be a `tangential_adjustment` that does something similar to `normal_adjustment`.  That said, in general, calculating the tangential component of a vector space is not as straight forward as the normal (for example, in 3d you can travel in different tangential directions) so its not clear to me how this should be resolved.

Overall I think I still have some more investigating to do before I can move forward with this PR.  I'm interested in resolving this and plan to get around to it, but I'm also working on some time sensitive projects that keep getting in the way!

**Pull request closed without merging**
