### PR TITLE
changed make_flux_sparsity_pattern to have the ability to add constraints

### PR DESCRIPTION
**Pull request by mathsen**
I needed the ability to incorporate Dirichlet boundary conditions on a level hierarchy with a flux sparsity pattern, so I changed make_flux_sparsity_pattern(), similar to make_sparsity_pattern() in MGTools.

### CODE REVIEW

**Comment by mathsen** [comment]
I guess the failed OSX serial test is because of a problem in the CI test suite?

````
2021-06-08T18:04:00.0133668Z ##[section]Starting: Request a runner to run this job
2021-06-08T18:04:01.1761109Z Can't find any online and idle self-hosted runner in current repository that matches the required labels: 'macos-latest'
2021-06-08T18:04:01.1761215Z Can't find any online and idle self-hosted runner in current repository's account/organization that matches the required labels: 'macos-latest'
2021-06-08T18:04:01.1761280Z Can't find any online and idle hosted runner in current repository's account/organization that matches the required labels: 'macos-latest'
2021-06-08T18:04:01.1761406Z Found online and busy hosted runners in current repository's account/organization that matches the required labels: 'macos-latest'. Waiting for one of them to get assigned for this job.
2021-06-08T18:04:01.3468908Z ##[section]Finishing: Request a runner to run this job
````

**Comment by drwells** [comment]
I think so.

This looks like a good feature so have. Could you add a test?

**Comment by mathsen** [comment]
@drwells OK, I just commited a change that implements a small test and compares the sparsity pattern from make_flux_sparsity_pattern() with constraints with one that comes from manually condensing the pattern. Bases on "tests/dofs/sparsity_pattern_05.cc"

**Comment by mathsen** [comment]
I just realized that in the first version of the test the example was so simple, that the resulting sparsity patterns with and without constraints were identical. I changed it a bit and now they are indeed different and the test fails if not condensing the pattern or directly eliminating it.

**Pull request merged**
