### PR TITLE
[WIP] MatrixFree: mark ghost vertices

### PR DESCRIPTION
**Pull request by peterrum**
FYI @sebproell

### CODE REVIEW

**Comment by peterrum** [comment]
@kronbichler  Please find attached the minimal test. The face visualized as arrow should be partition 1, however, is partition 2 as the code shows:

Screenshot from 2022-10-07 21-50-26

```cpp
// ---------------------------------------------------------------------
//
// Copyright (C) 2022 by the deal.II authors
//
// This file is part of the deal.II library.
//
// The deal.II library is free software; you can use it, redistribute
// it, and/or modify it under the terms of the GNU Lesser General
// Public License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
// The full text of the license can be found in the file LICENSE.md at
// the top level directory of deal.II.
//
// ---------------------------------------------------------------------

#include <deal.II/distributed/tria.h>

#include <deal.II/dofs/dof_handler.h>

#include <deal.II/fe/fe_nothing.h>
#include <deal.II/fe/fe_q.h>

#include <deal.II/grid/filtered_iterator.h>
#include <deal.II/grid/grid_generator.h>

#include <deal.II/matrix_free/fe_evaluation.h>
#include <deal.II/matrix_free/matrix_free.h>
#include <deal.II/matrix_free/tools.h>

#include <deal.II/numerics/data_out.h>
#include <deal.II/numerics/vector_tools.h>

using namespace dealii;

template <int dim>
void
test(const unsigned int n_refinements)
{
  using Number              = double;
  using VectorizedArrayType = VectorizedArray<Number>;
  using VectorType          = LinearAlgebra::distributed::Vector<Number>;
  using FECellIntegrator =
    FEEvaluation<dim, -1, 0, 1, Number, VectorizedArrayType>;
  using FEFaceIntegrator =
    FEFaceEvaluation<dim, -1, 0, 1, Number, VectorizedArrayType>;

  parallel::distributed::Triangulation<dim> tria(MPI_COMM_WORLD);
  GridGenerator::subdivided_hyper_rectangle(
    tria, {2, 2}, {0.0, 0.0}, {1.0, 1.0}, true);

  tria.refine_global(n_refinements);

  tria.signals.weight.connect([](const auto &cell, const auto /*status*/) {
    if (cell->center()[1] < 0.5)
      return 10u;
    else
      return 8u;
  });

  tria.repartition();

  DoFHandler<dim> dof_handler(tria);

  for (const auto &cell : filter_iterators(dof_handler.active_cell_iterators(),
                                           IteratorFilters::LocallyOwnedCell()))
    {
      if (cell->center()[1] < 0.5)
        cell->set_active_fe_index(0);
      else
        cell->set_active_fe_index(1);
    }

  dof_handler.distribute_dofs(
    hp::FECollection<dim>(FE_Q<dim>(1), FE_Nothing<dim>(1)));

  typename MatrixFree<dim, Number, VectorizedArrayType>::AdditionalData data;
  data.tasks_parallel_scheme = MatrixFree<dim, double>::AdditionalData::none;
  data.mapping_update_flags  = update_gradients;
  data.mapping_update_flags_boundary_faces = update_gradients;
  data.mapping_update_flags_inner_faces =
    update_gradients | update_quadrature_points;
  // data.overlap_communication_computation = false;

  MatrixFree<dim, Number, VectorizedArrayType> matrix_free;
  matrix_free.reinit(MappingQ1<dim>(),
                     dof_handler,
                     AffineConstraints<Number>(),
                     QGauss<dim>(2),
                     data);

  VectorType dst, src;

  {
    const auto cell_0 = tria.create_cell_iterator(CellId("1_3:322"));
    const auto cell_1 = tria.create_cell_iterator(CellId("3_3:100"));

    using Wrapper =
      internal::MFClassWrapper<MatrixFree<dim, Number, VectorizedArrayType>,
                               VectorType,
                               VectorType>;
    Wrapper wrap(
      nullptr,
      [&](const auto &matrix_free, auto &, const auto &, const auto range) {
        for (unsigned int cell = range.first; cell < range.second; ++cell)
          for (unsigned int v = 0;
               v < matrix_free.n_active_entries_per_face_batch(cell);
               ++v)
            {
              const auto cell_a =
                matrix_free.get_face_iterator(cell, v, true).first;
              const auto cell_b =
                matrix_free.get_face_iterator(cell, v, false).first;

              if (((cell_0 == cell_a) && (cell_1 == cell_b)) ||
                  ((cell_0 == cell_b) && (cell_1 == cell_a)))
                std::cout << "found!" << std::endl;
            }
      },
      nullptr);

    internal::MFWorker<MatrixFree<dim, Number, VectorizedArrayType>,
                       VectorType,
                       VectorType,
                       Wrapper,
                       true>
      worker(
        matrix_free,
        src,
        dst,
        false,
        wrap,
        &Wrapper::cell_integrator,
        &Wrapper::face_integrator,
        &Wrapper::boundary_integrator,
        MatrixFree<dim, Number, VectorizedArrayType>::DataAccessOnFaces::none,
        MatrixFree<dim, Number, VectorizedArrayType>::DataAccessOnFaces::none);

    const auto &partition_row_index =
      matrix_free.get_task_info().partition_row_index;

    for (unsigned int part = 0; part < partition_row_index.size() - 2; ++part)
      {
        std::cout << part << std::endl;
        for (unsigned int i = partition_row_index[part];
             i < partition_row_index[part + 1];
             ++i)
          {
            worker.face(i);
          }
      }
  }

  {
    DataOut<dim> data_out;
    data_out.attach_dof_handler(dof_handler);

    dealii::Vector<float> partitioning(tria.n_active_cells());
    for (unsigned int j = 0; j < partitioning.size(); ++j)
      partitioning = tria.locally_owned_subdomain();
    data_out.add_data_vector(partitioning, "partitioning");
    data_out.build_patches();

    data_out.write_vtu_in_parallel("solution.vtu", MPI_COMM_WORLD);
  }
}

int
main(int argc, char **argv)
{
  Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv, 1);

  test<2>(3);
}
```

**Comment by kronbichler** [comment]
Indeed, the case of `FE_Q` has not been considered thoroughly in the design of the face integrals. I think the solution is to make the face integrals check if any of the involved cells are at the "boundary" and ensure that the assignment to partitions is right, but it is probably complicated to introduce this in a clean way.

**Comment by peterrum** [comment]
> I think the solution is to make the face integrals check if any of the involved cells are at the "boundary" and ensure that the assignment to partitions is right, but it is probably complicated to introduce this in a clean way. 

I am not sure what you mean. Is the check possible only based on geometric information?

**Comment by peterrum** [comment]
@kronbichler Thank you for the feedback. I am not sure I got all your comments, but I think I have identified the root cause. The two cells next the problematic face have different partitions (1 vs. 2). This is explainable since one cell has `FE_Q` and the other `FE_Nothing`. This has the effect that the  code here:

https://github.com/dealii/dealii/blob/a95f7e5f2e7d15c10670ee93313dd357178a18b3/include/deal.II/matrix_free/face_setup_internal.h#L892-L936

picks the larger index (here 2) instead of the lower one (here 1). I have updated the test from the above commit. 

Currently, I am not sure what is the logic in taking the larger index and if it would be possible to take the lower one. In anyway, the code might need to modified: 1) loop over all partitions and determine the partitions of the faces and 2) set up the CRS storage. At the moment both steps are done together, which is possible since the higher partition is taken.

**Comment by kronbichler** [comment]
The choice of the higher index is by design: For a pure DG computation, we want to be able to perform the cell operation before the face accesses the data for the first time. You could think of this approach to be chosen to fit a "pre" operation on the level of cells. This is arbitrary to some extent, as the choice of moving the cell integral *always* to the end and switching cell and face integrals would allow to fit a "post" operation at the end of the cell integral. Which one of the two to choose is arbitrary to some extent, and I would today say that choosing a post approach might allow for slightly more overlap (to be done by hand, e.g. when applying an inverse mass matrix afterwards), but the caveat would be the MPI communication in a face-by-face scenario. Back in 2015 or 2016 when this choice was made, the data locality implications were not clear to me and we did not have time to investigate in detail, so the preference was given to the "pre" setup as it might interact well with the ADER DG setup that was one of the main applications at the time. (I think in the end we did not move that code to the public repository as the MPI exchange would need another roundtrip, as a cell-based loop would have been better, but that is another story.)

We could change this policy, as I am not aware of codes using the property explicitly, but the question is if that alone fixes the problem. My idea went in a different direction: We explicitly need to look into the indices that each cell handles and check if those depend on other MPI ranks, and then align the face integrals to the indices of the two adjacent cells, and decide whether they go into the MPI-part (index 1) or one of the other two parts (index 0 or 2). The last step is then to make sure that we adhere to the desired dependency between cells and faces (cell integrals always touch the DoFs in a DG sense first).

**Comment by kronbichler** [comment]
We could do that for the moment, but it would be good to open an issue with the reasoning given here, so we can later come back to it.

**Comment by peterrum** [comment]
Closing in favor of https://github.com/dealii/dealii/pull/14553.

**Pull request closed without merging**
