### PR TITLE
Replace the use of VECTORS_WITH_MATRIX by VECTOR_TYPES in .inst.in files.

### LINKED ISSUE #3922: Clean up names of template instantiation groups
As #3903 shows, the names we use for groups of expandable template arguments no longer match how they are used. In particular, #3903 leaves a few TODOs in the template-instantiations.in file. We should clean this up by looking at where a group is used, and what the appropriate name of the group should be.

### PR DESCRIPTION
**Pull request by bangerth**
This requires also adding a couple of include files, and removing
duplicate instantiatiosn.

Fixes #3922.

### CODE REVIEW

**Comment by bangerth** [comment]
Let's see what happens with this patch...

/rebuild

**Comment by masterleinad** [comment]
Looking at the previous instantiations and the errors for complex scalar types, it looks like only instantiating for real values is more appropriate in MGTransferPrebuilt.

**Comment by bangerth** [comment]
These are the errors I get for one of the tests:
```
libdeal_II.g.so.9.2.0-pre: error: undefined reference to 'void SparseMatrix<double>::vmult<LinearAlgebra::Vector<double>, LinearAlgebra::Vector<double> >(LinearAlgebra::Vector<double>&, LinearAlgebra::Vector<double> const&) const'
libdeal_II.g.so.9.2.0-pre: error: undefined reference to 'void SparseMatrix<double>::Tvmult_add<LinearAlgebra::Vector<double>, LinearAlgebra::Vector<double> >(LinearAlgebra::Vector<double>&, LinearAlgebra::Vector<double> const&) const'
libdeal_II.g.so.9.2.0-pre: error: undefined reference to 'void SparseMatrix<float>::vmult<LinearAlgebra::Vector<float>, LinearAlgebra::Vector<float> >(LinearAlgebra::Vector<float>&, LinearAlgebra::Vector<float> const&) const'
libdeal_II.g.so.9.2.0-pre: error: undefined reference to 'void SparseMatrix<float>::Tvmult_add<LinearAlgebra::Vector<float>, LinearAlgebra::Vector<float> >(LinearAlgebra::Vector<float>&, LinearAlgebra::Vector<float> const&) const'
libdeal_II.g.so.9.2.0-pre: error: undefined reference to 'std::enable_if<!std::is_same<LinearAlgebra::distributed::Vector<float, MemorySpace::Host>::value_type, double>::value, void>::type TrilinosWrappers::SparseMatrix::vmult<LinearAlgebra::distributed::Vector<float, MemorySpace::Host> >(LinearAlgebra::distributed::Vector<float, MemorySpace::Host>&, LinearAlgebra::distributed::Vector<float, MemorySpace::Host> const&) const'
libdeal_II.g.so.9.2.0-pre: error: undefined reference to 'void TrilinosWrappers::SparseMatrix::Tvmult_add<LinearAlgebra::distributed::Vector<float, MemorySpace::Host> >(LinearAlgebra::distributed::Vector<float, MemorySpace::Host>&, LinearAlgebra::distributed::Vector<float, MemorySpace::Host> const&) const'
libdeal_II.g.so.9.2.0-pre: error: undefined reference to 'void SparseMatrix<double>::vmult<LinearAlgebra::distributed::BlockVector<double>, LinearAlgebra::distributed::BlockVector<double> >(LinearAlgebra::distributed::BlockVector<double>&, LinearAlgebra::distributed::BlockVector<double> const&) const'
libdeal_II.g.so.9.2.0-pre: error: undefined reference to 'void SparseMatrix<double>::Tvmult_add<LinearAlgebra::distributed::BlockVector<double>, LinearAlgebra::distributed::BlockVector<double> >(LinearAlgebra::distributed::BlockVector<double>&, LinearAlgebra::distributed::BlockVector<double> const&) const'
libdeal_II.g.so.9.2.0-pre: error: undefined reference to 'void SparseMatrix<float>::vmult<LinearAlgebra::distributed::BlockVector<float>, LinearAlgebra::distributed::BlockVector<float> >(LinearAlgebra::distributed::BlockVector<float>&, LinearAlgebra::distributed::BlockVector<float> const&) const'
libdeal_II.g.so.9.2.0-pre: error: undefined reference to 'void SparseMatrix<float>::Tvmult_add<LinearAlgebra::distributed::BlockVector<float>, LinearAlgebra::distributed::BlockVector<float> >(LinearAlgebra::distributed::BlockVector<float>&, LinearAlgebra::distributed::BlockVector<float> const&) const'
libdeal_II.g.so.9.2.0-pre: error: undefined reference to 'void SparseMatrix<double>::vmult<TrilinosWrappers::MPI::BlockVector, TrilinosWrappers::MPI::BlockVector>(TrilinosWrappers::MPI::BlockVector&, TrilinosWrappers::MPI::BlockVector const&) const'
libdeal_II.g.so.9.2.0-pre: error: undefined reference to 'void SparseMatrix<double>::Tvmult_add<TrilinosWrappers::MPI::BlockVector, TrilinosWrappers::MPI::BlockVector>(TrilinosWrappers::MPI::BlockVector&, TrilinosWrappers::MPI::BlockVector const&) const'
libdeal_II.g.so.9.2.0-pre: error: undefined reference to 'void SparseMatrix<double>::vmult<PETScWrappers::MPI::BlockVector, PETScWrappers::MPI::BlockVector>(PETScWrappers::MPI::BlockVector&, PETScWrappers::MPI::BlockVector const&) const'
libdeal_II.g.so.9.2.0-pre: error: undefined reference to 'void SparseMatrix<double>::Tvmult_add<PETScWrappers::MPI::BlockVector, PETScWrappers::MPI::BlockVector>(PETScWrappers::MPI::BlockVector&, PETScWrappers::MPI::BlockVector const&) const'
```
Clearly there is more work necessary...

**Comment by masterleinad** [comment]
@bangerth Do you want to work on this for the release?

**Comment by kronbichler** [comment]
Let us postpone this - it is not very important in comparison.

**Comment by bangerth** [comment]
Let's just close this. It's too thorny an issue and I don't think I want to spend more time on it.

**Pull request closed without merging**
