### PR TITLE
Add warning to pack_rtree_of_indices()

### PR DESCRIPTION
**Pull request by peterrum**
as stated here

https://github.com/dealii/dealii/blob/3c37cfefb28c7685dafb4434c5b5edf53d845d06/source/grid/grid_tools.cc#L5790-L5791

@luca-heltai Have you found in the meantime a workaround?

### CODE REVIEW

**Review by bangerth — APPROVED** [review]
I think this is ok by itself. If you wanted, it might be worth adding that it is probably only specific compilers on windows, and that it is because the compiler does not understand the code. "Does not work" reads a lot like "well, someone reported getting wrong results, but we really didn't care enough to figure out what is happening".

Is it obvious how the code one would have to write to "build a tree with pairs of point and id" is going to look like?

**Comment by luca-heltai** [comment]
> @luca-heltai Have you found in the meantime a workaround?

No. I've tried different solutions, but it looks like many VS compiler do not like some constrcuts of boost. I'm not sure if more recent versions of it have a working solution, but I'd go with the "safe" route.

**Review by luca-heltai — APPROVED** [review]

**Comment by peterrum** [comment]
> Is it obvious how the code one would have to write to "build a tree with pairs of point and id" is going to look like?

@bangerth I'll add an example!

**Comment by bangerth** [comment]
@peterrum Thanks -- I'll gladly accept this patch if you added an example.

**Comment by bangerth** [comment]
@peterrum Ping?

**Comment by peterrum** [comment]
@bangerth I have added the example!

**Comment by peterrum** [comment]
@luca-heltai What do you think about the example?

**Pull request merged**
