### PR TITLE
Fix Tpetra for newer Trilinos

### PR DESCRIPTION
**Pull request by masterleinad**
Alternative to #15226.

### CODE REVIEW

**Comment by sebproell** [comment]
@masterleinad Thank you for your help! Unfortunately, I think this patch will not fix our (rather specific) problem: we use Trilinos 13.1. with Tpetra compiled without deprecated code (i.e. `sync` is not compiled) which you can set in Trilinos configuration options. Would it be reasonable to merge this PR and adapt the check in #15226 to only check for `sync` in versions <= 13.2?

fyi @c-p-schmidt Maybe you can try to compile our code with this patch to see whether my suspicion is correct?

**Comment by masterleinad** [comment]
@sebproell To the best of my knowledge, the functions were deprecated in https://github.com/trilinos/Trilinos/pull/8821 which first appeared in the 13.2.0  release (which is why I chose to check that one in this pull request).

**Comment by c-p-schmidt** [comment]
@sebproell You've been right. It does not compile with this patch.

**Comment by sebproell** [comment]
@c-p-schmidt I guess our problem is quite specific since the Trilinos we are using at our institute is not a clean release version (there is no 13.1 release tag...). I think we should update Trilinos on our side.

@masterleinad I think this patch is fine and no longer think we should solve the specific issue we have at our institute within deal.II :)

**Review by tamiko — APPROVED** [review]

**Review by peterrum — APPROVED** [review]

**Pull request merged**
