### PR TITLE
Misc. typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -I ../dealii-word-whitelist.txt --skip="./bundled"` where whitelist consists of:  
```
als
ans
buss
commend
ith
elemente
everytime
mapp
methode
nd
numer
perverse
pres
reenable
strat
substract
superceded
ue
uint
```

### CODE REVIEW

**Comment by bangerth** [comment]
Let's run the testsuite, though, since you're touching a few of the tests!

/run-tests

**Comment by bangerth** [comment]
@luzpaz: Do you know how to run the indentation script? We have a formalized way to indent the whole code base systematically, and the check that verifies that your patches follow this scheme fails:
https://travis-ci.org/dealii/dealii/builds/431305469?utm_source=github_status&utm_medium=notification

If you don't know how to do this, let me know and I'll do it for you.

**Comment by luzpaz** [comment]
@bangerth i do not know how to run said script

**Comment by masterleinad** [comment]
I checked locally that there are no new test failures with `clang`.

**Pull request merged**
