### PR TITLE
Fix ADOL-C CMake checks

### PR DESCRIPTION
**Pull request by jppelteret**
It seems that CMake doesn't always include the required flags that specify the C++ standard when checking that some source code compiles. So we therefore need to set the minimum required standard before using CHECK_CXX_SOURCE_COMPILES. Without this, on MacOS 10.15 I get errors like
```
Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test ADOLC_DOUBLE_CAST_CHECK failed with the following output:
Change Dir: /Users/jp/Development/Scratch/deal.II/dealii/macos/build/CMakeFiles/CMakeTmp

Run Build Command(s):<PATH>/bin/ninja-build cmTC_2d1ab && [1/2] Building CXX object CMakeFiles/cmTC_2d1ab.dir/src.cxx.o
FAILED: CMakeFiles/cmTC_2d1ab.dir/src.cxx.o 
<PATH>/bin/mpicxx  -I<PATH>/include -DADOLC_DOUBLE_CAST_CHECK -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -MD -MT CMakeFiles/cmTC_2d1ab.dir/src.cxx.o -MF CMakeFiles/cmTC_2d1ab.dir/src.cxx.o.d -o CMakeFiles/cmTC_2d1ab.dir/src.cxx.o -c src.cxx
In file included from src.cxx:2:
<PATH>/include/adolc/adouble.h:30:2: error: "please use -std=c++11 compiler flag with a C++11 compliant compiler"
#error "please use -std=c++11 compiler flag with a C++11 compliant compiler"
 ^
<PATH>/include/adolc/adouble.h:116:5: warning: explicit conversion functions are a C++11 extension [-Wc++11-extensions]
```

### CODE REVIEW

**Comment by jppelteret** [comment]
This might be related to https://cmake.org/Bug/view.php?id=15361 (now https://gitlab.kitware.com/cmake/cmake/-/issues/15361)

**Comment by tjhei** [comment]
I am not sure if this is the right way as we probably want to compile with the same flags we will use later on. Something like ``SET(CMAKE_REQUIRED_FLAGS ${DEAL_II_CXX_FLAGS_SAVED} )`` ? @tamiko ?

**Comment by tamiko** [comment]
This, is irritating. The check should always be run with the full saved flag of compiler options we are setting (and this implies C++14 support at the moment).

Do you see the message "C++14 support not available. Try to set -std=c++14 explicitly" when running cmake and would you mind attaching a full `detailed.log`.

**Comment by tamiko** [comment]
@jppelteret Would you mind testing the following:
```
diff --git a/cmake/checks/check_01_cxx_features.cmake b/cmake/checks/check_01_cxx_features.cmake
index 556a22da3a..4ec6854541 100644
--- a/cmake/checks/check_01_cxx_features.cmake
+++ b/cmake/checks/check_01_cxx_features.cmake
@@ -44,11 +44,8 @@
 # tests. Create a small macro to easily set CMAKE_REQUIRED_FLAGS
 #
 MACRO(_set_up_cmake_required)
-  # Let's put the user supplied `DEAL_II_CXX_FLAGS_SAVED` last so that we
-  # never override a user supplied -std=c++XY flag in our tests.
   RESET_CMAKE_REQUIRED()
   SET(CMAKE_REQUIRED_FLAGS "")
-  ADD_FLAGS(CMAKE_REQUIRED_FLAGS "${DEAL_II_CXX_FLAGS}")
   ADD_FLAGS(CMAKE_REQUIRED_FLAGS "${DEAL_II_CXX_FLAGS_SAVED}")
 ENDMACRO()
 
@@ -306,10 +303,17 @@ _set_up_cmake_required()
 _test_cxx14_support()
 
 IF(NOT DEAL_II_HAVE_CXX14)
-  MESSAGE(STATUS "C++14 support not available. Try to set -std=c++14 explicitly")
-  ENABLE_IF_SUPPORTED(DEAL_II_CXX_FLAGS "-std=c++14")
-  _set_up_cmake_required()
-  _test_cxx14_support()
+  #
+  # We failed to detect C++14 support. Let's make an attempt to set the
+  # -std= compiler flag. (But in order to minimize confusion let's not
+  # override any manually specified -std= variable set by the user.)
+  #
+  IF(NOT "${DEAL_II_CXX_FLAGS_SAVED}" MATCHES "-std=")
+    MESSAGE(STATUS "C++14 support not available. Try to set -std=c++14 explicitly")
+    ENABLE_IF_SUPPORTED(DEAL_II_CXX_FLAGS_SAVED "-std=c++14")
+    _set_up_cmake_required()
+    _test_cxx14_support()
+  ENDIF()
 ENDIF()
 
 IF(NOT DEAL_II_HAVE_CXX14)
```

**Comment by jppelteret** [comment]
> Do you see the message "C++14 support not available. Try to set -std=c++14 explicitly" when running cmake and would you mind attaching a full detailed.log.

Yeah, you hit the nail on the head! 
```
-- Include <PATH>/cmake/checks/check_01_cxx_features.cmake
-- Performing Test DEAL_II_HAVE_CXX14_FEATURES
-- Performing Test DEAL_II_HAVE_CXX14_FEATURES - Failed
-- Performing Test DEAL_II_HAVE_CXX14_CLANGAUTODEBUG_BUG_OK
-- Performing Test DEAL_II_HAVE_CXX14_CLANGAUTODEBUG_BUG_OK - Failed
-- Performing Test DEAL_II_HAVE_CXX11_FEATURES
-- Performing Test DEAL_II_HAVE_CXX11_FEATURES - Failed
-- Performing Test DEAL_II_HAVE_CXX11_FUNCTIONAL_LLVMBUG20084_OK
-- Performing Test DEAL_II_HAVE_CXX11_FUNCTIONAL_LLVMBUG20084_OK - Failed
-- C++14 support is disabled.
-- C++14 support not available. Try to set -std=c++14 explicitly
-- Performing Test DEAL_II_HAVE_FLAG_std=c__14
-- Performing Test DEAL_II_HAVE_FLAG_std=c__14 - Success
-- Configuration changed. Unsetting cached variable "DEAL_II_HAVE_CXX14_FEATURES" and rerunning checks.
-- Configuration changed. Unsetting cached variable "DEAL_II_HAVE_CXX14_CLANGAUTODEBUG_BUG_OK" and rerunning checks.
-- Configuration changed. Unsetting cached variable "DEAL_II_HAVE_CXX11_FEATURES" and rerunning checks.
-- Configuration changed. Unsetting cached variable "DEAL_II_HAVE_CXX11_FUNCTIONAL_LLVMBUG20084_OK" and rerunning checks.
-- Performing Test DEAL_II_HAVE_CXX14_FEATURES
-- Performing Test DEAL_II_HAVE_CXX14_FEATURES - Success
-- Performing Test DEAL_II_HAVE_CXX14_CLANGAUTODEBUG_BUG_OK
-- Performing Test DEAL_II_HAVE_CXX14_CLANGAUTODEBUG_BUG_OK - Success
-- Performing Test DEAL_II_HAVE_CXX11_FEATURES
-- Performing Test DEAL_II_HAVE_CXX11_FEATURES - Success
-- Performing Test DEAL_II_HAVE_CXX11_FUNCTIONAL_LLVMBUG20084_OK
-- Performing Test DEAL_II_HAVE_CXX11_FUNCTIONAL_LLVMBUG20084_OK - Success
-- C++14 support is enabled.
```

**Comment by jppelteret** [comment]
Will be fixed by #11331

**Pull request closed without merging**
