### PR TITLE
Add a test for FEInterfaceValues

### PR DESCRIPTION
**Pull request by bangerth**
This addresses the question I had in #8786 about #8660. It turns out that everything is, in fact, alright.

### CODE REVIEW

**Comment by tjhei** [comment]
can you please rebase to master, we need #8787 to run this test.

**Comment by tjhei** [comment]
?

**Comment by bangerth** [comment]
Erg, I accidentally pushed an already merged branch with the same name from the wrong machine onto this PR and then github closed the PR...

**Comment by bangerth** [comment]
It's back now!

**Comment by tjhei** [comment]
travis freaked out when this happened, so you might need to push again.

**Pull request merged**
