### PR TITLE
Save strandid and solutiontime into tecplot files

### PR DESCRIPTION
**Pull request by cpraveen**
This updates allows to save solution time into tecplot ascii files which makes it easy to animate time dependent date. It can used as

      DataOutBase::TecplotFlags flags(NULL, NULL, 1, elapsed_time);
      data_out.set_flags (flags);
      data_out.write_tecplot (output);

where ```elapsed_time``` is the time corresponding to the present solution.

### CODE REVIEW

**Comment by tjhei** [comment]
Can you explain what strand id is useful for and why the user might want to set it? (if we need this we should put it into the documentation too)

**Comment by cpraveen** [comment]
According to the tecplot manual:

```
Strand - A series of transient zones that represent the same part of a dataset at different times.
StrandID - An integer value defined for each transient zone (strand). 
```

If StrandID=0, then it is considered a static zone and is displayed at all times. If no StrandID is given, it is taken to be static zone.

In my own work, I have not used more than one strand.

In the comments in the code, I have made the same explanation. Is that not sufficient ?

**Comment by cpraveen** [comment]
As an e.g., if you have a fluid domain and a structure domain in your solution, you would assign different StrandID to each.

**Comment by tjhei** [comment]
> Is that not sufficient ?

Well, I still don't get what the consequence of changing that number is. It looks like to me it should always be 1 because we will always only have one "strand" inside a tecplot file anyway, or not? If that is the case, there is no reason to expose this to the user and always set it to 1 instead.

**Comment by cpraveen** [comment]
Most of the time, there would be only one strand, so there should be no need to assign a strandid. I will put the strandid as the last argument in the constructor of TecplotFlags.

**Pull request closed without merging**
