### PR TITLE
quick-test: do not use lapack/create_matrix.h in scalapack test

### PR DESCRIPTION
**Pull request by davydden**
fix this https://github.com/dealii/dealii/issues/6586#issuecomment-388655594

### CODE REVIEW

**Comment by drwells** [comment]
I am not sure if we want to turn around and break 9.0.0 yet again. Since the scalapack interface is new I suspect not many people will use it right away, so perhaps we can get away with leaving it for 9.0.1. Thoughts?

**Comment by davydden** [comment]
> I am not sure if we want to turn around and break 9.0.0 yet again.

although it's terrible idea in general, i would do this while we update the tarbal. We did it two hours ago and now found one more bug, I would rather fix it right away.

**Comment by davydden** [comment]
p.s. WIP as I am testing this PR (compilation takes about an hour on my notebook...)

**Comment by drwells** [comment]
I wrote a patch file based on this PR and applied it to the current (not yet posted) AUR build script and everything works.

**Comment by davydden** [comment]
@drwells i double checked this and the patch works on my machine.

**Pull request merged**
