### PR TITLE
Update bundled muParser to 2.3.3

### PR DESCRIPTION
**Pull request by drwells**
Related to #13577 - lets bundle a newer version of muParser. We previously updated muParser in #989.

### CODE REVIEW

**Review by bangerth — APPROVED** [review]
OK with me if it passes the test suite.

**Comment by marcfehling** [comment]
You changed code inside muparser in [5e99cf1](https://github.com/dealii/dealii/pull/13581/commits/5e99cf1feed8be3062c83405aa4b8bbcf85ed5bd) and [777ad8d](https://github.com/dealii/dealii/pull/13581/commits/777ad8ddcde13b7daa06f9f2ed03041a77300609). I just want to double check: Does the muparser license allow us to do that?

They use a BSD-2 License, see [here](https://github.com/beltoforion/muparser/blob/master/LICENSE), which allows modifications. So I think we're good.

**Comment by marcfehling** [comment]
The long way would be to propose your changes to the muparser project and ask for a new point release.

**Comment by drwells** [comment]
We should upstream some of these fixes. I think the anonymous union is an API stability problem but the other one is trivial.

To the best of my knowledge in

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are
    met:

the clause `with or without modification` covers our case.

**Review by marcfehling — APPROVED** [review]

**Comment by drwells** [comment]
Correction: I forgot that I deleted another patch in this PR. The union one is probably not acceptable since it changes the API and the `CMakeLists.txt` edit is purely on our end (we don't use their build system since we compile muParser directly into `deal_II.so` etc.) The older bugs have since been fixed.

**Comment by marcfehling** [comment]
@drwells: So, how do you propose to continue with this update? :-)

**Comment by drwells** [comment]
is there anything left to do? We could upstream some minor fixes to muParser but that wouldn't produce a new release any time soon, so its not directly relevant to this PR.

**Comment by bangerth** [comment]
Two people have approved, so if you (@drwells ) don't think that there's anything else to do, then let's merge.

As for upstreaming patches: That's always a good idea because it means that we don't have to maintain things we change ourselves. So I would suggest you go ahead with that if you have concrete patches.

**Comment by drwells** [comment]
This is approved so lets merge.

**Pull request merged**
