### PR TITLE
Revert "Merge pull request #11402 from pratikvn/fix-ginkgo-cmake"

### PR DESCRIPTION
**Pull request by Rombur**
#11402 breaks the CI. We configure deal.II to use C++17 but at compile time we use the default compiler on the system which does not support C++17.

### CODE REVIEW

**Review by peterrum — APPROVED** [review]

**Comment by bangerth** [comment]
Is this urgent? Does it break for everyone, or just if you have gingko installed?

**Comment by masterleinad** [comment]
> Is this urgent? Does it break for everyone, or just if you have gingko installed?

A fair share of our regression tests is broken (https://cdash.43-1.org/index.php?project=deal.II). If it fixes that, I'd consider it pretty urgent.

**Comment by bangerth** [comment]
Then let's revert once the testers are through.
@pratikvn -- can you think of an alternative way of achieving what you wanted?

/rebuild

**Review by bangerth — APPROVED** [review]

**Comment by pratikvn** [comment]
Sorry, I am a bit confused. We require only at most C++14.

**Comment by masterleinad** [comment]
Admittedly, I also don't quite understand how that pull request would have broken anything. It would be good to have a reproducer we can inspect. :slightly_smiling_face:

**Comment by Rombur** [comment]
> Sorry, I am a bit confused. We require only at most C++14.

What I think is happening is the following: the testing machine has a default compiler that does not support C++17 and additional compilers that do support C++17. With this PR, somehow, the configuration step correctly selects a compiler that supports C++17 but during compilation the default compiler, which does not support C++17, is selected. Because of this we try to compile C++17 code with a compiler that does not support it. 

I am not sure that it is what's happening. We need to wait for the testers to check that reverting this PR fixes the problem.

**Comment by tamiko** [comment]
The problem is that the ginkgo configuration exports a number of `GINKGO_CXX_FLAGS` containing a `-std=c++14` that our build system then dutifully adds to our compile flags.

**Comment by tamiko** [comment]
There is a second, much bigger issue why this pull request must be reverted for now, see my second comment on #11402

**Pull request merged**
