### PR TITLE
Fix test for nearest query for ArborXWrappers::DistributedTree

### PR DESCRIPTION
**Pull request by Rombur**
The test was committed by mistake. It actually did not compile. This PR fixes the test.

### CODE REVIEW

**Comment by drwells** [comment]
I tried this on my own and I get a bunch of other errors with ArborX 1.1:

```
[drwells@archway build-max-opt]$ ctest -VV -j6 -R 'arborx.*nearest.*mpirun.*debug'
UpdateCTestConfiguration  from :/home/drwells/Documents/Code/CPP/dealii-dev/build-max-opt/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/drwells/Documents/Code/CPP/dealii-dev/build-max-opt/DartConfiguration.tcl
Test project /home/drwells/Documents/Code/CPP/dealii-dev/build-max-opt
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1269
    Start 1269: arborx/distributed_tree_nearest.mpirun=2.debug

1269: Test command: /usr/bin/cmake "-DTRGT=arborx.distributed_tree_nearest.mpirun2.debug.test" "-DTEST=arborx/distributed_tree_nearest.mpirun=2.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/drwells/Documents/Code/CPP/dealii-dev/build-max-opt/tests/arborx" "-DGUARD_FILE=/home/drwells/Documents/Code/CPP/dealii-dev/build-max-opt/tests/arborx/distributed_tree_nearest.debug/interrupt_guard.cc" "-P" "/home/drwells/Documents/Code/CPP/dealii-dev/build-max-opt/share/deal.II/scripts/run_test.cmake"
1269: Test timeout computed to be: 600
1269: In file included from /home/drwells/Applications/arborx/include/ArborX_DistributedTree.hpp:16,
1269:                  from /home/drwells/Applications/arborx/include/ArborX.hpp:19,
1269:                  from /home/drwells/Documents/Code/CPP/dealii-dev/include/deal.II/arborx/access_traits.h:24,
1269:                  from /home/drwells/Documents/Code/CPP/dealii-dev/tests/arborx/distributed_tree_nearest.cc:20:
1269: /home/drwells/Applications/arborx/include/details/ArborX_DetailsDistributedTreeImpl.hpp: In instantiation of 'static void ArborX::Details::DistributedTreeImpl<DeviceType>::reassessStrategy(const ExecutionSpace&, const Predicates&, const DistributedTree&, Indices&, Offset&, Distances&) [with DistributedTree = ArborX::DistributedTree<Kokkos::HostSpace>; ExecutionSpace = Kokkos::Serial; Predicates = dealii::ArborXWrappers::BoundingBoxNearestPredicate; Indices = Kokkos::View<int*, Kokkos::Serial>; Offset = Kokkos::View<int*, Kokkos::HostSpace>; Distances = Kokkos::View<float*, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >; DeviceType = Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>]':
1269: /home/drwells/Applications/arborx/include/details/ArborX_DetailsDistributedTreeImpl.hpp:497:9:   required from 'static std::enable_if_t<(((Kokkos::is_view<IndicesAndRanks>{} && Kokkos::is_view<Offset>{}) && Kokkos::is_view<Ranks>{}) && Kokkos::is_view<Distances>{})> ArborX::Details::DistributedTreeImpl<DeviceType>::queryDispatchImpl(ArborX::Details::NearestPredicateTag, const DistributedTree&, const ExecutionSpace&, const Predicates&, Indices&, Offset&, Ranks&, Distances*) [with DistributedTree = ArborX::DistributedTree<Kokkos::HostSpace>; ExecutionSpace = Kokkos::Serial; Predicates = dealii::ArborXWrappers::BoundingBoxNearestPredicate; Indices = Kokkos::View<int*, Kokkos::Serial>; Offset = Kokkos::View<int*, Kokkos::HostSpace>; Ranks = Kokkos::View<int*, Kokkos::Serial>; Distances = Kokkos::View<float*, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace> >; DeviceType = Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>; std::enable_if_t<(((Kokkos::is_view<IndicesAndRanks>{} && Kokkos::is_view<Offset>{}) && Kokkos::is_view<Ranks>{}) && Kokkos::is_view<Distances>{})> = void]'
1269: /home/drwells/Applications/arborx/include/details/ArborX_DetailsDistributedTreeImpl.hpp:158:22:   required from 'static std::enable_if_t<(Kokkos::is_view<IndicesAndRanks>{} && Kokkos::is_view<Offset>{})> ArborX::Details::DistributedTreeImpl<DeviceType>::queryDispatch(ArborX::Details::NearestPredicateTag, const DistributedTree&, const ExecutionSpace&, const Predicates&, IndicesAndRanks&, Offset&) [with DistributedTree = ArborX::DistributedTree<Kokkos::HostSpace>; ExecutionSpace = Kokkos::Serial; Predicates = dealii::ArborXWrappers::BoundingBoxNearestPredicate; IndicesAndRanks = Kokkos::View<Kokkos::pair<int, int>*, Kokkos::HostSpace>; Offset = Kokkos::View<int*, Kokkos::HostSpace>; DeviceType = Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>; std::enable_if_t<(Kokkos::is_view<IndicesAndRanks>{} && Kokkos::is_view<Offset>{})> = void]'
1269: /home/drwells/Applications/arborx/include/ArborX_DistributedTree.hpp:97:60:   required from 'void ArborX::DistributedTree<MemorySpace, Enable>::query(const ExecutionSpace&, const Predicates&, Args&& ...) const [with ExecutionSpace = Kokkos::Serial; Predicates = dealii::ArborXWrappers::BoundingBoxNearestPredicate; Args = {Kokkos::View<Kokkos::pair<int, int>*, Kokkos::HostSpace>&, Kokkos::View<int*, Kokkos::HostSpace>&}; MemorySpace = Kokkos::HostSpace; Enable = void]'
1269: /home/drwells/Documents/Code/CPP/dealii-dev/include/deal.II/arborx/distributed_tree.h:110:27:   required from 'std::pair<std::vector<std::pair<int, int> >, std::vector<int, std::allocator<int> > > dealii::ArborXWrappers::DistributedTree::query(const QueryType&) [with QueryType = dealii::ArborXWrappers::BoundingBoxNearestPredicate]'
1269: /home/drwells/Documents/Code/CPP/dealii-dev/tests/arborx/distributed_tree_nearest.cc:71:54:   required from here
1269: /home/drwells/Applications/arborx/include/details/ArborX_DetailsDistributedTreeImpl.hpp:380:40: error: no matching function for call to 'ArborX::Sphere::Sphere(<brace-enclosed initializer list>)'                                                                 
1269:   380 |         radius_searches(i) = intersects(Sphere{
1269:       |                              ~~~~~~~~~~^~~~~~~~
1269:   381 |             getGeometry(Access::get(queries, i)), farthest_distances(i)});
1269:       |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1269: In file included from /home/drwells/Applications/arborx/include/details/ArborX_DetailsAlgorithms.hpp:18,
1269:                  from /home/drwells/Applications/arborx/include/details/ArborX_Predicates.hpp:14,
1269:                  from /home/drwells/Applications/arborx/include/details/ArborX_AccessTraits.hpp:18,
1269:                  from /home/drwells/Applications/arborx/include/ArborX_LinearBVH.hpp:15,
1269:                  from /home/drwells/Applications/arborx/include/details/ArborX_DetailsDistributedTreeImpl.hpp:21,
1269:                  from /home/drwells/Applications/arborx/include/ArborX_DistributedTree.hpp:16,
1269:                  from /home/drwells/Applications/arborx/include/ArborX.hpp:19,
1269:                  from /home/drwells/Documents/Code/CPP/dealii-dev/include/deal.II/arborx/access_traits.h:24,
1269:                  from /home/drwells/Documents/Code/CPP/dealii-dev/tests/arborx/distributed_tree_nearest.cc:20:
1269: /home/drwells/Applications/arborx/include/details/ArborX_Sphere.hpp:27:13: note: candidate: 'constexpr ArborX::Sphere::Sphere(const ArborX::Point&, double)'
1269:    27 |   constexpr Sphere(Point const &centroid, double radius) // FIXME
1269:       |             ^~~~~~
1269: /home/drwells/Applications/arborx/include/details/ArborX_Sphere.hpp:27:33: note:   no known conversion for argument 1 from 'const ArborX::Box' to 'const ArborX::Point&'
1269:    27 |   constexpr Sphere(Point const &centroid, double radius) // FIXME
1269:       |                    ~~~~~~~~~~~~~^~~~~~~~
1269: /home/drwells/Applications/arborx/include/details/ArborX_Sphere.hpp:24:3: note: candidate: 'constexpr ArborX::Sphere::Sphere()'
1269:    24 |   Sphere() = default;
1269:       |   ^~~~~~
1269: /home/drwells/Applications/arborx/include/details/ArborX_Sphere.hpp:24:3: note:   candidate expects 0 arguments, 2 provided
1269: /home/drwells/Applications/arborx/include/details/ArborX_Sphere.hpp:21:8: note: candidate: 'constexpr ArborX::Sphere::Sphere(const ArborX::Sphere&)'
1269:    21 | struct Sphere
1269:       |        ^~~~~~
1269: /home/drwells/Applications/arborx/include/details/ArborX_Sphere.hpp:21:8: note:   candidate expects 1 argument, 2 provided
1269: /home/drwells/Applications/arborx/include/details/ArborX_Sphere.hpp:21:8: note: candidate: 'constexpr ArborX::Sphere::Sphere(ArborX::Sphere&&)'
1269: /home/drwells/Applications/arborx/include/details/ArborX_Sphere.hpp:21:8: note:   candidate expects 1 argument, 2 provided
1269: make[3]: *** [CMakeFiles/arborx.distributed_tree_nearest.debug.dir/build.make:80: CMakeFiles/arborx.distributed_tree_nearest.debug.dir/distributed_tree_nearest.cc.o] Error 1
1269: make[2]: *** [CMakeFiles/Makefile2:445: CMakeFiles/arborx.distributed_tree_nearest.debug.dir/all] Error 2
1269: make[1]: *** [CMakeFiles/Makefile2:478: CMakeFiles/arborx.distributed_tree_nearest.mpirun2.debug.test.dir/rule] Error 2
1269: make: *** [Makefile:316: arborx.distributed_tree_nearest.mpirun2.debug.test] Error 2
1269: Test arborx/distributed_tree_nearest.mpirun=2.debug: BUILD
1269: ===============================   OUTPUT BEGIN  ===============================
1269: arborx/distributed_tree_nearest.mpirun=2.debug: BUILD failed. Output:
1269: Consolidate compiler generated dependencies of target arborx.distributed_tree_nearest.debug
1269: [ 16%] Building CXX object CMakeFiles/arborx.distributed_tree_nearest.debug.dir/distributed_tree_nearest.cc.o
1269: 
1269: 
1269: arborx/distributed_tree_nearest.mpirun=2.debug: ******    BUILD failed    *******
1269: 
1269: ===============================    OUTPUT END   ===============================
1269: Expected stage PASSED - aborting
1269: CMake Error at /home/drwells/Documents/Code/CPP/dealii-dev/build-max-opt/share/deal.II/scripts/run_test.cmake:144 (MESSAGE):
1269:   *** abort
1269: 
1269: 
1/1 Test #1269: arborx/distributed_tree_nearest.mpirun=2.debug ...***Failed   11.72 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =  12.92 sec

The following tests FAILED:
        1269 - arborx/distributed_tree_nearest.mpirun=2.debug (Failed)
Errors while running CTest
Output from these tests are in: /home/drwells/Documents/Code/CPP/dealii-dev/build-max-opt/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

all the other arborx tests pass.

**Comment by Rombur** [comment]
Yeah, you need to use ArborX `master`. There will be a release soon with the fix.

**Comment by drwells** [comment]
Got it - everything works with `master`.

Does the newer version require MPI? I was able to install arborx without MPI support by accident and that caused this test to fail for other reasons.

**Review by drwells — APPROVED** [review]

**Comment by Rombur** [comment]
> Does the newer version require MPI?

No it doesn't.

> I was able to install arborx without MPI support by accident and that caused this test to fail for other reasons.

I didn't think about that. Inside the library, we check that arborx is compiled with MPI support but this test gets enable as long as MPI and arborx are enable.

**Comment by drwells** [comment]
I think it would make sense to not permit deal.II with MPI and ArborX without MPI but we can handle that in another PR.

**Review by masterleinad — APPROVED** [review]

**Comment by Rombur** [comment]
> I think it would make sense to not permit deal.II with MPI and ArborX without MPI simultaneously but we can handle that in another PR.

Actually the fix is very simple, I just need to change the name of the output file. There is another test with the same problem, I will fix it too.

**Comment by drwells** [comment]
Oh yeah, I forgot that we could use feature tests like that when setting up tests.

**Review by drwells — APPROVED** [review]

**Pull request merged**
