### PR TITLE
Improve line continuations

### LINKED ISSUE #333: Allow continuation lines in ParameterHandler
_From [bange...@gmail.com](https://code.google.com/u/111126369971033778052/) on September 26, 2014 04:14:20_

There are situations where one would really like to extend long lines in parameter files to the next line, for example using a backslash at the end of a line in much the same way as the C preprocessor allows.

This could be done relatively easily using the functions in https://github.com/geodynamics/aspect/blob/master/source/main.cc This would mean that we report errors on the first line of a continuation block, but that's likely acceptable.

_Original issue: http://code.google.com/p/dealii/issues/detail?id=255_

### PR DESCRIPTION
**Pull request by drwells**
The implementation in #1520 is correct, but it only handles one of two `read_input` functions. This PR moves all of the continuation line logic (from #1520) into the version of `read_input` that accepts a `std::istream` since the other two input functions ultimately call that one.

The first five commits are cosmetic; the substantial changes are in the last two.

I went ahead and added my name to the changelog entry from last time. @asartori86 is this okay?

Closes #333.

### CODE REVIEW

**Comment by bangerth** [comment]
Ah, great. I had not realized that the previous patch didn't completely fix #333. Thanks for doing this!

Please update the couple of places I marked in individual commits and merge yourself.

**Comment by drwells** [comment]
@bangerth Not a problem. Perhaps I am the only one who uses the `std::istream` interface :)

**Comment by bangerth** [comment]
No, actually ASPECT also uses it (but handles continuation lines itself).

**Comment by asartori86** [comment]
> I went ahead and added my name to the changelog entry from last time. @asartori86 is this okay?

of course :)

**Pull request merged**
