### PR TITLE
remove data_interpretations in step-68

### PR DESCRIPTION
**Pull request by ZhouleiJoeStone**
an un-used variable data_interpretations in step-68 is removed

### CODE REVIEW

**Review by peterrum — COMMENTED** [review]
Thanks a lot for your contribution! Looks good. 

May I ask you to rebase your branch. There has been an issue with our indentation CI, but that should be fixed now on master.

**Review by peterrum — APPROVED** [review]
/rebuild

**Comment by ZhouleiJoeStone** [comment]
@peterrum 

Now, is my branch step-26_fix OK? 
I'm a newbee to use git and It's my first time to pull request.  I hope that what I have done is right.
Is there anything else that I should do?

**Comment by peterrum** [comment]
@ZhouleiJoeStone Yes. It looks me OK, I would be surprised if the tester should complain again. But let's see. If everything passes as expected, we will merge! Thanks again for your PR! Git is a very useful tool; learning does not harm!

**Review by kronbichler — APPROVED** [review]

**Comment by bangerth** [comment]
Very nice -- welcome to the authors of deal.II!

**Pull request merged**
