### PR TITLE
Add a copy operator to TrilinosWrappers::SparsityPatternIterators::Accessor.

### LINKED ISSUE #3541: Static analysis: include/deal.II/lac/trilinos_sparsity_pattern.h

### PR DESCRIPTION
**Pull request by bangerth**
Fixes #3541.

### CODE REVIEW

**Comment by drwells** [comment]
While this fixes the problem, since the copy constructor used by the Iterator is equal to the default copy constructor, I think that we could solve this in the same way as in #3573 and just let the compiler generate a default copy constructor.

**Comment by bangerth** [comment]
You're right. While looking at the code, I'm not seeing how this could ever have worked. I'll go with your route, add a test, and probably have to fix whatever is broken.

**Comment by drwells** [comment]
This looked like it worked to me... I'll have to check the next PR :)

**Comment by bangerth** [comment]
I wrote a test that segfaulted upon construction of *any* iterator, see #3586. That is, I couldn't even get to testing what is necessary to *copy* an iterator.

I will fix it all at the same time.

**Pull request closed without merging**
