### PR TITLE
Add tests for deal.II solvers with TpetraWrappers classes

### PR DESCRIPTION
**Pull request by jpthiele**
This ports the tests for Trilinos/Epetra to the new LinearAlgebra::TpetraWrappers classes.

### CODE REVIEW

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
Are these tests a subset of the ones in #16611 ?

**Comment by jpthiele** [comment]
> Are these tests a subset of the ones in #16611 ?

Yes they are. 

The `f = 1.;` line needed changing as that now throws an exception like in the LA::distributed::Vector when not seeting `f = 0.;`.

The output needed the correct mangled class name and I also updated the latter copyright year and removed the include for the vector header as that is one of the first line in the matrix header.

**Comment by bangerth** [comment]
OK. What I hear you say is that we don't lose anything if I remove the tests named identically here and in #16611 from #16611?

**Comment by jpthiele** [comment]
Exactly, and then we are at 77 (after rebase)

**Pull request merged**
