### PR TITLE
Fix documentation for face support points in fe

### PR DESCRIPTION
**Pull request by sairajat**
I guess there was a typo.

### CODE REVIEW

**Comment by kronbichler** [comment]
Thanks for fixing this issue @sairajat.

**Comment by bangerth** [comment]
@sairajat -- this problem also appears in `fe.h` and maybe other files in this direction. Could we interest you to fix these similarly?

**Comment by sairajat** [comment]
@bangerth  Yes Professor. Definitely.
But how do I find such issues?

**Comment by bangerth** [comment]
I just looked by hand into `include/deal.II/fe/fe.h` and searched for the function whose documentation you were modifying. You could either go through all of the `fe_*h` file in this directory, or do something like
```
  grep -n -r '<tt>cell->get_dof_indices</tt> function' include/deal.II/fe/*h
```
to search for places where the *old* text (before your patch) also appears.

Many thanks for finding the original issue and for being willing to look for other places as well!

**Comment by sairajat** [comment]
I see. I did not find any other function in ```include/deal.II/fe/fe.h``` that has the same problem anymore but I was wondering how to find such issue in other files.

I knew about grep but had never used it to find something inside of files :).

I will do it this weekend.

Thanks.

**Comment by sairajat** [comment]
by the way,  ```grep -n -r '<tt>cell->get_dof_indices</tt> function' include/deal.II/fe/*h``` 
using this in the deal directory returns empty.

I also used ``grep -n -r 'cell->get_dof_indices' include/deal.II/fe/*h``` This didnot find any problem but just 2 uses of the text in the code.

How should I look in other places then?

**Comment by bangerth** [comment]
Oh, I had for some reason thought that you were changing `fe_faceq.h`. But you changed the place that I pointed out, so there is nothing else that can be done -- my apologies for leading you down an unnecessary chase, but many thanks anyway for considering fixing more places! We appreciate every patch we can get!

**Comment by sairajat** [comment]
Oh I see. No problem. :)

**Pull request merged**
