### PR TITLE
Make sure all .h files include config.h.

### PR DESCRIPTION
**Pull request by bangerth**
Several in `particles/` were missing this.

### CODE REVIEW

**Comment by masterleinad** [comment]
In the end, It is sufficient to include `config.h` in every file only transitively and this is what we check with the `all-headers` test.

**Comment by masterleinad** [comment]
For me, the full list of header files that don't list `config.h` explicitly would be (`grep -Lr "config.h" include/deal.II`)
```
include/deal.II/algorithms/newton.h
include/deal.II/algorithms/newton.templates.h
include/deal.II/algorithms/operator.templates.h
include/deal.II/algorithms/theta_timestepping.h
include/deal.II/algorithms/theta_timestepping.templates.h
include/deal.II/algorithms/timestep_control.h
include/deal.II/base/auto_derivative_function.h
include/deal.II/base/derivative_form.h
include/deal.II/base/function.templates.h
include/deal.II/base/function_time.templates.h
include/deal.II/base/incremental_function.h
include/deal.II/base/mg_level_object.h
include/deal.II/base/parsed_function.h
include/deal.II/base/polynomials_adini.h
include/deal.II/base/polynomials_bernardi_raugel.h
include/deal.II/base/polynomials_bernstein.h
include/deal.II/base/polynomials_rannacher_turek.h
include/deal.II/base/qprojector.h
include/deal.II/base/quadrature_selector.h
include/deal.II/base/revision.h.in
include/deal.II/base/std_cxx1x/array.h
include/deal.II/base/std_cxx1x/bind.h
include/deal.II/base/std_cxx1x/condition_variable.h
include/deal.II/base/std_cxx1x/function.h
include/deal.II/base/std_cxx1x/mutex.h
include/deal.II/base/std_cxx1x/shared_ptr.h
include/deal.II/base/std_cxx1x/thread.h
include/deal.II/base/std_cxx1x/tuple.h
include/deal.II/base/std_cxx1x/type_traits.h
include/deal.II/base/symmetric_tensor.h
include/deal.II/base/symmetric_tensor.templates.h
include/deal.II/base/tensor_function.templates.h
include/deal.II/base/time_stepping.templates.h
include/deal.II/boost_adaptors/bounding_box.h
include/deal.II/boost_adaptors/point.h
include/deal.II/boost_adaptors/segment.h
include/deal.II/differentiation/ad/ad_number_traits.h
include/deal.II/distributed/fully_distributed_tria_util.h
include/deal.II/distributed/p4est_wrappers.h
include/deal.II/dofs/block_info.h
include/deal.II/fe/fe_dg_vector.templates.h
include/deal.II/fe/fe_interface_values.h
include/deal.II/fe/fe_nedelec_sz.h
include/deal.II/fe/fe_poly_face.h
include/deal.II/fe/fe_poly_face.templates.h
include/deal.II/fe/fe_poly.h
include/deal.II/fe/fe_poly.templates.h
include/deal.II/fe/fe_rannacher_turek.h
include/deal.II/fe/fe_tools_extrapolate.templates.h
include/deal.II/fe/fe_tools_interpolate.templates.h
include/deal.II/fe/fe_tools.templates.h
include/deal.II/lac/affine_constraints.templates.h
include/deal.II/lac/chunk_sparse_matrix.templates.h
include/deal.II/lac/constrained_linear_operator.h
include/deal.II/lac/cuda_kernels.templates.h
include/deal.II/lac/diagonal_matrix.h
include/deal.II/lac/exceptions.h
include/deal.II/lac/la_vector.templates.h
include/deal.II/lac/linear_operator_tools.h
include/deal.II/lac/matrix_lib.h
include/deal.II/lac/matrix_lib.templates.h
include/deal.II/lac/pointer_matrix.h
include/deal.II/lac/qr.h
include/deal.II/lac/relaxation_block.h
include/deal.II/lac/relaxation_block.templates.h
include/deal.II/lac/sparse_decomposition.templates.h
include/deal.II/lac/sparse_matrix_ez.templates.h
include/deal.II/lac/sparse_mic.h
include/deal.II/lac/sparse_mic.templates.h
include/deal.II/lac/sparse_vanka.templates.h
include/deal.II/lac/swappable_vector.templates.h
include/deal.II/lac/trilinos_tpetra_vector.templates.h
include/deal.II/lac/vector_element_access.h
include/deal.II/lac/vector_memory.templates.h
include/deal.II/lac/vector_operations_internal.h
include/deal.II/lac/vector.templates.h
include/deal.II/matrix_free/cuda_matrix_free.templates.h
include/deal.II/matrix_free/dof_info.h
include/deal.II/matrix_free/dof_info.templates.h
include/deal.II/matrix_free/evaluation_selector.h
include/deal.II/matrix_free/face_info.h
include/deal.II/matrix_free/face_setup_internal.h
include/deal.II/matrix_free/helper_functions.h
include/deal.II/matrix_free/mapping_info.h
include/deal.II/matrix_free/mapping_info.templates.h
include/deal.II/matrix_free/matrix_free.h
include/deal.II/matrix_free/matrix_free.templates.h
include/deal.II/matrix_free/operators.h
include/deal.II/matrix_free/shape_info.h
include/deal.II/matrix_free/shape_info.templates.h
include/deal.II/matrix_free/task_info.h
include/deal.II/meshworker/assembler.h
include/deal.II/meshworker/dof_info.templates.h
include/deal.II/meshworker/functional.h
include/deal.II/meshworker/integration_info.templates.h
include/deal.II/meshworker/output.h
include/deal.II/meshworker/simple.h
include/deal.II/meshworker/vector_selector.h
include/deal.II/meshworker/vector_selector.templates.h
include/deal.II/multigrid/mg_coarse.h
include/deal.II/multigrid/mg_matrix.h
include/deal.II/multigrid/mg_transfer_block.templates.h
include/deal.II/multigrid/mg_transfer_component.templates.h
include/deal.II/multigrid/mg_transfer_internal.h
include/deal.II/multigrid/mg_transfer.templates.h
include/deal.II/multigrid/multigrid.templates.h
include/deal.II/multigrid/sparse_matrix_collection.h
include/deal.II/numerics/data_out_dof_data.templates.h
include/deal.II/numerics/data_postprocessor.h
include/deal.II/numerics/dof_output_operator.templates.h
include/deal.II/numerics/error_estimator.templates.h
include/deal.II/numerics/fe_field_function.h
include/deal.II/numerics/fe_field_function.templates.h
include/deal.II/numerics/matrix_creator.templates.h
include/deal.II/numerics/point_value_history.h
include/deal.II/numerics/vector_tools.templates.h
include/deal.II/optimization/solver_bfgs.h
include/deal.II/particles/generators.h
include/deal.II/particles/particle_accessor.h
include/deal.II/particles/particle.h
include/deal.II/particles/particle_handler.h
include/deal.II/particles/property_pool.h
include/deal.II/physics/elasticity/kinematics.h
include/deal.II/physics/elasticity/standard_tensors.h
include/deal.II/physics/notation.h
include/deal.II/physics/transformations.h
```

**Comment by masterleinad** [comment]
We just need a decision if we really want them to be in every header file. If so, we should find a way to enforce it without checking manually.

**Comment by bangerth** [comment]
The solution with transitive inclusion is a bit fragile. My preference is to just *always* do the `#include <config.h>` first.

This patch does that for all files that were currently missing this.

**Comment by drwells** [comment]
```
[drwells@archway include]$ find ./ -name '*.h' | xargs grep -L '# *include <deal.II/base/config.h>'
./deal.II/base/std_cxx1x/mutex.h
./deal.II/base/std_cxx1x/thread.h
./deal.II/base/std_cxx1x/tuple.h
./deal.II/base/std_cxx1x/bind.h
./deal.II/base/std_cxx1x/function.h
./deal.II/base/std_cxx1x/condition_variable.h
./deal.II/base/std_cxx1x/shared_ptr.h
./deal.II/base/std_cxx1x/type_traits.h
./deal.II/base/std_cxx1x/array.h
./deal.II/base/config.h
```

This PR really does add `config.h` to all of our headers. Unless there are further objections to always including this I suggest we merge soon.

**Comment by bangerth** [comment]
> This PR really does add |config.h| to all of our headers.

What did you expect? If I do things, I do them right ;-)

**Comment by drwells** [comment]
Of course, but its not paranoia if they are actually out to get you :)

**Comment by bangerth** [comment]
:-)

**Pull request merged**
