### PR TITLE
Rename and deprecate MGLevelObject::clear()

### LINKED ISSUE #2560: Rename and deprecate MGLevelObject::clear()
`MGLevelObject` is in essence a container, and it has this member function:
```
  /**
   * Call @p clear on all objects stored by this object. This function is only
   * implemented for some @p Object classes, e.g. the PreconditionBlockSOR and
   * similar classes.
   */
  void clear();
```

This is in contrast to all other container classes' `clear()` functions, which deletes the *content of the container*, not of the *elements*. 

We should rename this function and deprecate its original spelling.

### PR DESCRIPTION
**Pull request by class4kayaker**
Fixes #2560.

Using clear_elements() as replacing method name, because I could not think of an obviously better/clearer name for the new function. Any suggestions for a better name would be appreciated.

### CODE REVIEW

**Comment by bangerth** [comment]
Are there any calls to this function anywhere? I typically test this by temporarily commenting out the old function declaration and seeing what doesn't compile.

**Comment by class4kayaker** [comment]
There are definitely some calls in the examples, but I do not know of any easy way to quickly check for where it might be called in the tests. I also noted other deprecated functions at the same time, so that might be worthwhile to consider as a separate issue.

I did a clean build while retaining the log before posting this, and there were no warnings about deprecated functions. I just used your suggested method to confirm that with my current build settings, there are no existing calls to MGLevelObject::clear() as well.

Is there a quick way to build all of the tests/examples as a single or small number of commands? If so, that might be a useful way to find all of the places that need to be modified.

**Comment by bangerth** [comment]
I would try something like the following, in the installation directory:
```
  # get the configuration step out of the way, so these messages don't clutter up later
  # compiler warnings and errors
  cd examples
  for i in step-* ; do
    (cd $i ; cmake .)
  done

  # now do the builds
  for i in step-* ; do
    (cd $i ; make)
  done
```
The second step may yield a few errors for steps you can't compile (because, for example, you don't have PETSc or similar), but you can typically see the errors you care about.

**Comment by class4kayaker** [comment]
While checking the examples, I noticed that I may have somehow skipped some locations where there was a call to clear. All of the missed cases were in include files, so would that have had an effect if I did not run install?.

Your suggested format worked for the examples, I think I can at least mock up an equivalent to run only a subset of tests. I should double check whether I can get the compile logs using that approach.

 Also, I did notice that in the examples I checked there were calls to other deprecated functions. Would it be best to include those correction with the fixes for MGLevelObject::clear despite not being directly related, handle all of the deprecated corrections as a separate pull request, or only handle the clear corrections for this pull request and handle all the other corrections separately? I am leaning towards the third option as the tidiest approach.

**Comment by bangerth** [comment]
Yes, handle separate things in separate pull requests. Feel free to open github issues for things you don't want to fix right away, and that are not related to this PR.

Tests: You're touching the multigrid stuff, so maybe running
```
  ctest -R multigrid
```
would be sufficient as it runs only that subset of tests that have "multigrid" somewhere in their name or path.

**Comment by class4kayaker** [comment]
I will open an issue for handling deprecated function calls in the examples as a separate issue then.

I did a grep on MGLevelObject, and am currently using a script to run all of the tests that showed up, logging to a file so I can easily get locations that need modified.

**Comment by bangerth** [comment]
Thanks! I merged this one because I didn't want to hold off on it any further given that it touches a bunch of files.

Could you, in a separate pull request, provide an entry to the `changes.h` file?

**Pull request merged**
