### PR TITLE
Add Kokkos::initialize and finalize to MPI_InitFinalize

### PR DESCRIPTION
**Pull request by Rombur**
We have a couple of tests that are using `MPI_InitFinalize` and `Kokkos::initialize/finalize`. This doesn't work because the destructor of `MPI_InitFinalize` needs Kokkos to be initialized. I've removed `Kokkos::initialize/finalize` from the tests.  I've also added `Kokkos::initialize/finalize` to `MPI_InitFinalize`. So there is a way for users to pass command line arguments to Kokkos.

### CODE REVIEW

**Review by masterleinad — CHANGES_REQUESTED** [review]
I think we should only try to initialize and finalize `Kokkos` if it wasn't initialized before.

**Comment by Rombur** [comment]
Kokkos should only be initialized after MPI because MPI can create resource binding that may impact Kokkos. Since this class call `MPI_Init`, Kokkos should not be initialized before the class is called.

**Comment by masterleinad** [comment]
So what do we do if someone is already using `Kokkos` and uses `MPI_InitFinalize` later? Is it OK to just break their code?

**Comment by Rombur** [comment]
> So what do we do if someone is already using Kokkos and uses MPI_InitFinalize later? Is it OK to just break their code?

We are already breaking their code. The only way it works is if they did

```c++
Kokkos::initialize()
{
  dealii::MPI_InitFinalize()
  ....
}
Kokkos::finalize()
```
If they didn't scope `MPI_IniFinalize`, we will call the `MPI_InitFinalize` destructor after Kokkos was finalized but the destructor will try to reinitialize Kokkos to clear `GrowingMemoryVector`. That's basically what happens in the failing tests.

**Comment by masterleinad** [comment]
Right, there was a bug in the test but this pull request can break working code even though it's not recommended to initialize `Kokkos` before `MPI`. I would be OK with that but I would like to hear someone else's opinion.

**Review by tjhei — APPROVED** [review]
I think this makes sense.

**Comment by marcfehling** [comment]
This patch could be responsible for two tests failing. Can you double-check?
https://ci.tjhei.info/job/dealii-mpi/job/master/170/pipeline-console/?selected-node=36#log-1445
```
The following tests FAILED:
	3702 - lac/parallel_vector_22.mpirun=4.debug (Failed)
	3704 - lac/parallel_vector_23.mpirun=4.debug (Failed)
```

**Comment by Rombur** [comment]
Yes, it's because we use static variable for `Kokkos::View` in these two tests so they get destroyed after regular variables. I don't see the point in using static variable in these tests.

**Pull request merged**
