### PR TITLE
Cleanups for the edge orientation code.

### LINKED ISSUE #3235: [Meta] Rewrite edge orientation code
The edge orientation code was originally written by Michael Anderson. It does well what it's supposed to do, but it doesn't follow our usual code conventions, and it is implemented twice: once for 2d, and once for 3d. Finally, it would be nice if it followed the algorithm and conventions used in the paper we currently have under review.

This github issues is simply a collector for all patches that re-implement this algorithm in a generic and modern way.

### PR DESCRIPTION
**Pull request by bangerth**
These are a few cleanups -- best reviewed for each commit individually --
to the edge orientation code. This is my last piece for #3235.

Fixes #3235.

### CODE REVIEW

**Comment by bangerth** [comment]
I think something went wrong with the tester. It doesn't seem related to this patch.

**Comment by bangerth** [comment]
For reference, I built this PR with gcc 4.4.7.

**Comment by bangerth** [comment]
Ping?

**Comment by drwells** [comment]
While (like the last commit) I don't fully understand the algorithm, I read the code and reran the testsuite and everything looks OK. Unless someone has objections I will merge this in the next few days.

**Comment by drwells** [comment]
Thanks for taking the time to tidy things up :)

**Pull request merged**
