### PR TITLE
Set boundary indicators in GridIn on vertices in 1d.

### LINKED ISSUE #1430: GridIn doesn't do boundary indicators in 1d
As reported by Jan Strebel: https://groups.google.com/forum/#!topic/dealii/WWWXN1czTOw

A simple mesh file with line elements and two endpoints marked by physical numbers 10 (left) and 20 (right):
```
$MeshFormat
2.2 0 8
$EndMeshFormat
$Nodes
11
1 0 0 0
2 1 0 0
3 0.1 0 0
4 0.2 0 0
5 0.3 0 0
6 0.4 0 0
7 0.5 0 0
8 0.6 0 0
9 0.7 0 0
10 0.8 0 0
11 0.9 0 0
$EndNodes
$Elements
12
1 15 2 10 1 1
2 15 2 20 2 2
3 1 2 100 1 1 3
4 1 2 100 1 3 4
5 1 2 100 1 4 5
6 1 2 100 1 5 6
7 1 2 100 1 6 7
8 1 2 100 1 7 8
9 1 2 100 1 8 9
10 1 2 100 1 9 10
11 1 2 100 1 10 11
12 1 2 100 1 11 2
$EndElements
```
When processing by a code like:
```
  Triangulation<1,3> tri;
  GridIn<1,3> grid_in;
  grid_in.attach_triangulation(tri);
  std::ifstream input_file("l.msh");
  grid_in.read_msh(input_file);

  for (auto cell = tri.begin_active(); cell != tri.end(); ++cell)
  {
    for (unsigned int face = 0; face < 2; ++face)
    {
      if (cell->at_boundary(face))
        printf("vertex %d has boundary indicator %d\n", cell->face_index(face), cell->face(face)->boundary_indicator());
    }
  }
```
The result is:
```
vertex 0 has boundary indicator 0
vertex 1 has boundary indicator 1
```
I would like to have seen boundary indicators 10 and 20.

### PR DESCRIPTION
**Pull request by bangerth**
We did not keep track of boundary indicators on vertices at all, even though
these are faces in 1d. Fix this.

Fixes #1430.

### CODE REVIEW

**Comment by bangerth** [comment]
I pushed a second commit that also fixes #1431.

**Comment by tamiko** [comment]
Looks good.

**Comment by bangerth** [comment]
Updated.

**Comment by tamiko** [comment]
@bangerth I took the liberty to correct "This this" to "Fix this" prior to merging.

**Pull request merged**
