### PR TITLE
Simplify some type computations in FEValuesViews.

### PR DESCRIPTION
**Pull request by bangerth**
Specifically, instead of using a nested class, just use a template type alias. While there, also fix a few places where we should have used the existing type alias but instead had repeated the same type computation used in the definition of the type alias.

This patch is pretty repetitive. It's unlikely going to be fun to look over, but at least should be very well covered by the test suite. I'll try not to write any such patches any more until the release and focus on the things that *actually* need to be done.

/rebuild

### CODE REVIEW

**Comment by bangerth** [comment]
I realized all of this when looking at what #12047 does.

**Review by drwells — APPROVED** [review]

**Comment by jppelteret** [comment]
This is an incompatible change (at least, I use these types in an external project) so I think that it should be documented as such.

**Comment by drwells** [comment]
That's a good point. Do we need to keep `OutputType` et al around to keep that code working?

**Comment by jppelteret** [comment]
@bangerth Do you perhaps need to change this https://github.com/dealii/dealii/blob/master/include/deal.II/meshworker/scratch_data.h#L45-L47 as well? I also see more instances of `OutputType` in `fe_values.inst.in` and these tests:
- tests/fe/fe_values_views_types.cc
- tests/fe/fe_values_view_get_function_from_local_dof_values_01.cc
- tests/fe/fe_values_view_get_function_from_local_dof_values_01.cc

**Comment by jppelteret** [comment]
> That's a good point. Do we need to keep OutputType et al around to keep that code working?

Its not a public project, so I don't mind fixing the breakage. But I think that it might be worth deprecating this, since I think that it's one of the only reliable mechanisms that we have for deducing an operation result type for a specified scalar type.

**Comment by masterleinad** [comment]
There are some failing tests
```
1674 - fe/fe_values_view_get_function_from_local_dof_values_01.debug (Failed)
1860 - fe/fe_values_views_types.debug (Failed)
3119 - meshworker/scratch_data_09d.debug (Failed)
3125 - meshworker/scratch_data_09b.debug (Failed)
3126 - meshworker/scratch_data_09c.debug (Failed)
3129 - meshworker/scratch_data_04.debug (Failed)
3132 - meshworker/scratch_data_09a.debug (Failed)
```

**Comment by bangerth** [comment]
Huh, who knew that that internal type calculation leaks out of these classes. That certainly was never the intention.

I can fix that tomorrow, and if you all insist, I can even keep the old `OutputType` classes. The backward compatible way -- which I would prefer -- is to document that one can get at that type using `decltype(fe_values[pressure].get_function_values(...))`. Would that be acceptable?

**Comment by jppelteret** [comment]
> if you all insist, I can even keep the old OutputType classes. 

Not necessary, from my point of view. Thanks for offering though!

> The backward compatible way -- which I would prefer -- is to document that one can get at that type using decltype(fe_values[pressure].get_function_values(...)). Would that be acceptable?

I'd be happy with us doing this.

**Review by jppelteret — CHANGES_REQUESTED** [review]
Hi @bangerth, I'm just going to temporarily block this PR from being merged so that we don't forget to document the incompatibility that it introduces.

**Comment by bangerth** [comment]
I brought the types back and deprecated them. I also added a changelog entry.

**Review by jppelteret — APPROVED** [review]

**Comment by jppelteret** [comment]
> I brought the types back and deprecated them. I also added a changelog entry.

Thanks a lot for doing that!

**Pull request merged**
