### PR TITLE
Fix single digit output time

### PR DESCRIPTION
**Pull request by drwells**
VTK files, based on when they are written, may save output with text like

```sh
#This file was generated by the deal.II library on 2015/7/6 at 17: 3:49
```

which, while correct, is a bit strange to read. This behavior may occur in other output file formats. I fixed this by creating a common class for building the date and time strings with zero padding.

### CODE REVIEW

**Comment by bangerth** [comment]
There is already a function `Utilities::System::get_time()`. Can you rewrite your patch by adding a function `Utilities::System::get_date()` and using these two functions in the relevant places? I think that would produce the shortest and most reusable code.

**Comment by drwells** [comment]
Wow, I don't know how I missed `Utilities::System::get_time` when I wrote that yesterday. I fixed that and updated the commit log.

**Comment by bangerth** [comment]
Thanks. If your goal was to always output it as YYYY/MM/DD with two digits month and day numbers, then this patch doesn't do that yet, though.

**Comment by drwells** [comment]
That was not my intent; I tried not to change the output format any more than getting rid of the spurious space.

**Comment by bangerth** [comment]
Ah, ok.

**Pull request merged**
