### PR TITLE
Massively lower some IDA solver tolerances.

### PR DESCRIPTION
**Pull request by drwells**
ida_02 presently fails with a numdiff difference of about 1e-6: this makes sense since that's the provided solver tolerance. We can get consistent results by making it a few orders of magnitude lower.

### CODE REVIEW

**Comment by drwells** [comment]
Part of #13703.

**Comment by kronbichler** [comment]
On the serial CI, the first test still seems to fail:
```
sundials/ida_01.debug: DIFF failed. ------ First 20 lines of numdiff output:
----------------
##2       #:2   <== 0.198666
##2       #:2   ==> 0.198669
@ Absolute error = 3.0000000000e-6, Relative error = 1.5100721815e-5
##2       #:3   <== 0.98005
##2       #:3   ==> 0.980067
@ Absolute error = 1.7000000000e-5, Relative error = 1.7346053773e-5
##2       #:4   <== 0.980056
##2       #:4   ==> 0.980067
@ Absolute error = 1.1000000000e-5, Relative error = 1.1223848433e-5
##2       #:5   <== -0.198643
##2       #:5   ==> -0.198669
@ Absolute error = 2.6000000000e-5, Relative error = 1.3088807559e-4
----------------
##3       #:2   <== 0.389414
##3       #:2   ==> 0.389418
@ Absolute error = 4.0000000000e-6, Relative error = 1.0271844361e-5
##3       #:3   <== 0.921051
##3       #:3   ==> 0.921061
@ Absolute error = 1.0000000000e-5, Relative error = 1.0857162090e-5
```

**Review by marcfehling — APPROVED** [review]
> ida_02 presently fails with a numdiff difference of about 1e-6: this makes sense since that's the provided solver tolerance. We can get consistent results by making it a few orders of magnitude lower.

You meant ida_01, right?

This change shouldn't increase runtime significantly, so to me this is fine.

**Comment by drwells** [comment]
Both, actually, and they both use the same `prm` file.

**Review by bangerth — APPROVED** [review]
This is ok with me. Do I understand @kronbichler 's comment as an objection?

**Review by masterleinad — APPROVED** [review]

**Pull request merged**
