### PR TITLE
Remove remaining deprecations

### PR DESCRIPTION
**Pull request by masterleinad**
Rebased on top of #15611.
Deprecated in:
- #12049 
- #11670
- #12219
- #11867
- #11751
- #12067

### CODE REVIEW

**Review by marcfehling — CHANGES_REQUESTED** [review]
I like that you cleaned up the vertex ordering tests, especially as in getting rid of `create_triangulation_compatibility()`. Looked very tedious.

You duplicated some code to ensure mesh compatibility among some tests. I would suggest to move these functions into a separate header file, or extend the existing one [`tests/test_grids.h`](https://github.com/dealii/dealii/blob/master/tests/test_grids.h) which right now only has mesh generators, but it would be predestined for the vertex reordering. Then we have everything in one spot.

**Comment by masterleinad** [comment]
@marcfehling See [`0096280` (#15629)](https://github.com/dealii/dealii/pull/15629/commits/0096280440b5ec48af25f810d0c405a94aa4703f).

**Review by marcfehling — APPROVED** [review]
> @marcfehling See [`0096280` (#15629)](https://github.com/dealii/dealii/pull/15629/commits/0096280440b5ec48af25f810d0c405a94aa4703f).

I like it!

Technically we could also use these functions on `tests/bits/neighboring_cells_at_two_faces.cc`, `tests/data/data_out_curved_cells.cc`, `tests/grid/grid_invert_02.cc`, and `tests/grid/line_coarsening_3d.cc` to preserve the original state of the test. Probably not necessary, I don't feel strong about it. How do you think about it?

**Comment by masterleinad** [comment]
> Technically we could also use these functions on `tests/bits/neighboring_cells_at_two_faces.cc`, `tests/data/data_out_curved_cells.cc`, `tests/grid/grid_invert_02.cc`, and `tests/grid/line_coarsening_3d.cc` to preserve the original state of the test. Probably not necessary, I don't feel strong about it. How do you think about it?

I would rather convert all the tests instead of using the new function but that seemed to be too much work.

**Review by tamiko — APPROVED** [review]

**Pull request merged**
