### PR TITLE
Try fixing symengine tests

### PR DESCRIPTION
**Pull request by masterleinad**
This is a stab at fixing the failing symengine tests likely caused by https://github.com/dealii/dealii/pull/17024. An alternative would be to just revert https://github.com/dealii/dealii/pull/17024 for the `symengine` tests which might still be good for tests this pull request doesn't fix.

### CODE REVIEW

**Comment by tjhei** [comment]
So, maybe it was on purpose that some of the output was not tested but sent to std::cout? I am not opposed to reverting that PR.

These tests only fail on @tamiko 's regression tester, right? So, we can also go ahead and merge this and see what happens afterwards.

**Review by tjhei — APPROVED** [review]

**Comment by bangerth** [comment]
All of these tests work on my laptop and the big machine at work. Do you happen to have diffs between the existing outputs and your alternative outputs?

**Comment by masterleinad** [comment]
> All of these tests work on my laptop and the big machine at work. Do you happen to have diffs between the existing outputs and your alternative outputs?

Most of them just update the `with_symengine_with_llvm` versions. The others are like
```diff
5,7c5,7
< DEAL::df_CQ_dC_symb_subs: 1.0*C*Q(C)
< DEAL::D2f_CQ_DC_dC_symb: 1.0*C*Derivative(Q(C), C) + 1.0*Q(C)
< DEAL::f_CQ_subs: 37.5
---
> DEAL::df_CQ_dC_symb_subs: C*Q(C)*1.0
> DEAL::D2f_CQ_DC_dC_symb: Q(C)*1.0 + C*Derivative(Q(C), C)*1.0
> DEAL::f_CQ_subs: 75.0*0.5
9c9
< DEAL::df_CQ_dC: subs: 15.0
---
> DEAL::df_CQ_dC: subs: 15.0*1.0
11,12c11,12
< DEAL::D2f_CQ_DC_dC: subs 1: 3.0 + 0.6*C
< DEAL::D2f_CQ_DC_dC: subs 2: 6.0
---
> DEAL::D2f_CQ_DC_dC: subs 1: 3.0*1.0 + 0.6*C*1.0
> DEAL::D2f_CQ_DC_dC: subs 2: 3.0 + 3.0*1.0
```
Locally I have a couple more tests failing that show differences in iteration counts that we are now recording and some of them also fail for unknown reasons.

**Comment by masterleinad** [comment]
`trilinos/solver_control_06` is failing in the `Jenkins: MPI` tester but that seems unrelated since I'm only modifying `symengine` test files.

**Review by kronbichler — APPROVED** [review]

**Comment by kronbichler** [comment]
Given the annoyance the high number of failing tests creates, I decided it is time to merge this. We can see how the testers react, otherwise we might need to go with #17106.

**Pull request merged**
