### PR TITLE
step-54: move input vtk to a separate folder to avoid its removal by …

### PR DESCRIPTION
**Pull request by davydden**
…make distclean

### CODE REVIEW

**Comment by davydden** [comment]
addresses [this](https://groups.google.com/d/msg/dealii/UG8yiMT6VcU/w0gIYVy4BwAJ) user request.

**Comment by tjhei** [comment]
You also need to fix the installation of the vtk in dealii/examples/CMakeLists.txt

**Comment by davydden** [comment]
@tjhei done

**Comment by tjhei** [comment]
Thanks. Did you test that it works?

**Comment by davydden** [comment]
yes, it did install step-54 fine with `input/initial_mesh_3d.vtk`

**Comment by tjhei** [comment]
:+1:

**Pull request merged**
