### PR TITLE
FETools::extrapolate: Working on the algorithm on distributed grids

### PR DESCRIPTION
**Pull request by msteigemann**
This is the second try to get the extrapolate function working on distributed parallel grids and it is still work in progress.
I use this function a lot also in parallel and it seems to work now, but detecting errors is not that easy and of course, there is always room for improvement.

### CODE REVIEW

**Comment by tamiko** [comment]
@msteigemann Please let us now when you consider your pull request ready for review (and remove the "WIP" tag).

From a first glance it looks good so far.

**Comment by msteigemann** [comment]
@tamiko From my point of view this is ready for review, but I left university and did not work on this since june, so maybe this needs some updates to current developments, I can check this.
How can I remove the WIP tag (sorry stupid question ...)?

**Comment by msteigemann** [comment]
From my point of view this is ready for review.

**Comment by masterleinad** [comment]
Rebased in PR  #2753

**Comment by drwells** [comment]
Lets keep any future discussion in #2753; we don't need two concurrent PRs for this.

We can open this particular PR again later if the branch is updated.

**Pull request closed without merging**
