### PR TITLE
Some fixes for the testsuite.

### PR DESCRIPTION
**Pull request by marcfehling**
I've configured deal.II in `debug` mode with `p4est` and `mpi` only, and found a couple of tests failing.

Either output files did not carry the corresponding flag, or shared Triangulations used auto partitioning while output files were created with Zoltan.

I've fixed those issues. For the latter, I've changed the tests to use zorder partitioning. We could instead also set `with_trilinos_with_zoltan` as a flag.

Also fixes https://github.com/dealii/dealii/pull/12430#discussion_r665016640.

---

There are a couple of tests that fail, but leave me puzzled.
```
  2375 - fullydistributed_grids/repartitioning_05.mpirun=4.debug (Failed)
  3882 - mpi/fe_tools_extrapolate_03.mpirun=3.debug (Failed)
```
- The `repartitioning_0x` tests all use `parallel::distributed::Triangulations` which require `p4est`, but only the `05` test fails? It's complaining about an invalid communicator.
- I have no idea what's going on in `fe_tools_extrapolate`. An assertion in the consensus algorithm fails.

@peterrum -- Can you have a look?

### CODE REVIEW

**Review by peterrum — APPROVED** [review]

**Comment by masterleinad** [comment]
> I've fixed those issues. For the latter, I've changed the tests to use zorder partitioning. We could instead also set `with_trilinos_with_zoltan` as a flag.

I think I would prefer that.

**Comment by masterleinad** [comment]
>   3882 - mpi/fe_tools_extrapolate_03.mpirun=3.debug (Failed)

Is failing on all configurations anyway: 
https://cdash.43-1.org/testSummary.php?project=1&name=mpi%2Ffe_tools_extrapolate_01.mpirun%3D3.debug&date=2021-07-04
I don't think you need to address that here.

**Comment by marcfehling** [comment]
> 
> 3882 - mpi/fe_tools_extrapolate_03.mpirun=3.debug (Failed)
> Is failing on all configurations anyway:

So does `fullydistributed_grids/repartitioning_05` as I just realized.

I'll clean up this PR with your suggestions and leave these two tests as they are for now.

**Review by masterleinad — APPROVED** [review]

**Pull request merged**
