### PR TITLE
Add hp hanging node face test.

### PR DESCRIPTION
**Pull request by marcfehling**
Related to #17595.

@bangerth suspects an issue in how we make hanging node constraints in the hp-case. This is a test case to investigate the issue.

@bangerth You can see in the output file that the suspicious entries show up quite frequently: 
```
DEAL::Case 0:
    21 20:  1.00000
    21 85:  -0.447214
    21 159:  0.447214
    ...
DEAL::Case 1:
    9 8:  1.00000
    9 60:  0.447214
    9 85:  -0.447214
    ...
```

### CODE REVIEW

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
As I mentioned before I left, I have convinced myself that the code to make hanging node constraints is probably correct, but that it's the merging that is wrong. I think this test is useful nonetheless. Let's merge it.

**Comment by bangerth** [comment]
(But you'll have to remove the WIP marker for that.)

**Comment by marcfehling** [comment]
To reduce the size of the output, I can add a call of `AffineConstraints::close()` which is not present in the test.

What do you think?

**Review by kronbichler — APPROVED** [review]

**Comment by bangerth** [comment]
I think we should just not allow any operations on objects that haven't been closed. It looks to me like we're missing an assertion in the `print()` function.

**Comment by bangerth** [comment]
Out of curiosity, how come calling `close()` *reduces* the size of the output? Resolving chains -- at least typically -- only increases the number of entries on the rhs of a constraints...

**Comment by marcfehling** [comment]
> Out of curiosity, how come calling close() reduces the size of the output?

Oh, that was a statement I made yesterday night before going to bed. You are right, the output should be larger.

>  It looks to me like we're missing an assertion in the `print()` function.

I agree.

I will add a call of `close` to this test.

**Comment by bangerth** [comment]
We know that this test output is wrong. Do you want us to merge this anyway, or should we wait until the bug is fixed?

**Comment by marcfehling** [comment]
This test is related to #17595, not #17599.

It does not use `make_consistent_in_parallel`, thus this test produces the correct output and is ready to be merged.

We should keep the other test from #17611 unmerged for now.

**Comment by bangerth** [comment]
Ah, I see. My bad for missing the difference.

**Pull request merged**
