### PR TITLE
Rename VectorTools::evaluate_at_points() -> VectorTools::point_values()

### PR DESCRIPTION
**Pull request by peterrum**
... to be consistent with `VectorTools::point_value()`.

If possible, I would like to make this change part of release 9.3, since this is a new function.

FYI @mschreter

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]
I think this is a good strategy.

**Comment by kronbichler** [comment]
I am in favor of putting this in for the 9.3 release branch, but we should aim for at least one more approval in that case, so let's wait for that.

**Review by marcfehling — APPROVED** [review]
Could you update the changelog as well? You mentioned `evaluate_at_points` in `doc/news/changes/major/20210228Munch-2`.

**Comment by marcfehling** [comment]
Since this function has been introduced in #11804 after the last release, I'm in favor in putting this in the 9.3 release branch as well.

**Comment by peterrum** [comment]
@marcfehling I have updated doc/news/9.2.0-vs-9.3.0.h directly. The other file does not exist anymore.

**Comment by marcfehling** [comment]
I'll merge early as only the changelog has been modified and all testers were happy earlier.

**Pull request merged**
