### PR TITLE
minor cleanup of LAPACKSupport

### PR DESCRIPTION
**Pull request by davydden**
those enums are not used at the moment:
```
$ ag "lower_triangle"
include/deal.II/lac/lapack_support.h
95:    lower_triangle = 4,
$ ag "upper_triangle"
include/deal.II/lac/lapack_support.h
93:    upper_triangle = 2,
````

 but I intend to utilzie them in future PRs.

### CODE REVIEW

**Comment by drwells** [comment]
If you intend on using them in the future then why do you want to remove them?

Either way they are not used anywhere. Would you mind adding a changelog entry (since this is incompatible)?

**Comment by davydden** [comment]
> If you intend on using them in the future then why do you want to remove them?

i don't remove anything, i just renamed them.

> Would you mind adding a changelog entry (since this is incompatible)?

will do.

**Comment by bangerth** [comment]
OK to merge once the tester is happy.

**Comment by drwells** [comment]
Whoops, I misread this patch (of course you did not remove them).

**Pull request merged**
