### PR TITLE
Add instantiations for MappingFEField

### PR DESCRIPTION
**Pull request by bangerth**
Also make it all compile if the template argument is anything other than the default.

### CODE REVIEW

**Comment by drwells** [comment]
@bangerth It looks like the changelog entry conflicts with something else. Could you please rebase?

**Comment by bangerth** [comment]
Rebased.

**Comment by kronbichler** [comment]
Why not go with the generic template instantiation framework here, i.e., add another `SERIAL_VECTORS` argument to the loop in `mapping_fe_field.inst.in`? This would save some space and also resolve the somewhat arbitrary selection of a Trilinos block vector whereas no block version is available for the `dealii` vectors (and they do not include our own distributed vector). Is there anything I miss?

**Comment by bangerth** [comment]
Excellent point. Patch is updated.

**Pull request merged**
