### PR TITLE
Changelog

### PR DESCRIPTION
**Pull request by resetius**
https://github.com/dealii/dealii/pull/10100

### CODE REVIEW

**Comment by drwells** [comment]
Thanks again for the fix!

**Comment by bangerth** [comment]
Thanks very much, and welcome to the list of authors of deal.II!

**Comment by resetius** [comment]
> Thanks very much, and welcome to the list of authors of deal.II!

Oh, I've already been here since 2017 :) But now I'm here twice :) https://www.dealii.org/authors.html
Alexey Ozeritskiy
Alexey Ozeritsky
This is one person recorded according to different transliteration rules :) You can leave any one record.

**Comment by bangerth** [comment]
Oh, interesting :-) In that case, good to see you back!

What version of the name do you use professionally? That's the one we should leave.

**Comment by resetius** [comment]
Alexey Ozeritskiy

**Comment by bangerth** [comment]
So it happened! Thanks for the feedback.

**Pull request merged**
