### PR TITLE
examples/step-4: Update indenting

### PR DESCRIPTION
**Pull request by tamiko**
In reference to #6774

### CODE REVIEW

**Comment by bangerth** [comment]
Other than the bilinear form, the lines you explicitly break here don't bother me too much. What's your rationale?

For the bilinear form, I would suggest doing as I commented on the step-3 patch already, namely using the opportunity to annotate the different parts of the formula with the mathematical symbols.

**Comment by tamiko** [comment]
@dealii/dealii *ping*

**Comment by drwells** [comment]
I like the added text in the weak form comments.

**Pull request merged**
