### PR TITLE
[9.2.] Take over #10168

### PR DESCRIPTION
**Pull request by tamiko**
do not print mesh in opencascade/stl_* tests

### CODE REVIEW

**Comment by tjhei** [comment]
okay, but let's check that #10168 passes first.

**Comment by tamiko** [comment]
@tjhei I don't think that you run opencascade tests on the CI :smile:

**Comment by masterleinad** [comment]
> @tjhei I don't think that you run opencascade tests on the CI smile

Yes, there is `OpenCASCADE`: https://jenkins.tjhei.info/blue/organizations/jenkins/dealii/detail/PR-10161/2/pipeline

**Comment by tamiko** [comment]
@masterleinad @tjhei Interesting. Then I am surprised that these mesh generation tests were that stable on the docker configurations.

**Pull request merged**
