### PR TITLE
Move the function that generates a reference cell to GridGenerator.

### PR DESCRIPTION
**Pull request by bangerth**
@peterrum FYI

/rebuild

### CODE REVIEW

**Comment by drwells** [comment]
I believe this is missing the changes to `grid_generator.cc`.

**Comment by bangerth** [comment]
Yes, I must have made a mistake when committing. It's there now and works for me locally.

**Review by peterrum — APPROVED** [review]
FYI @nmuch

**Comment by masterleinad** [comment]
This has conflicts now.

**Comment by bangerth** [comment]
Merge conflict should be fixed.

**Review by peterrum — APPROVED** [review]
Thx!

**Pull request merged**
