### PR TITLE
Step 40 as a simplex test

### PR DESCRIPTION
**Pull request by michelebucelli**
Step 40 (Laplace problem using a fully distributed triangulation) as a simplex test.

### CODE REVIEW

**Review by peterrum — APPROVED** [review]
Excellent! Thanks a lot!

**Review by tamiko — APPROVED** [review]

**Comment by bangerth** [comment]
The windows test failure is spurious, but on Linux, the test actually fails with a different output on 4 processors. @michelebucelli -- can you check that the test actually succeeds on your machine?

**Comment by michelebucelli** [comment]
@bangerth I confirm the test passes on my machine. The same thing happens with my other pull request #11551 for step 17. I will be running the test on a different machine shortly to see if I can reproduce the error. I remark that also the test with a single process fails, and both tests appear to print some error message, instead of a valid but different than expected output.

**Comment by bangerth** [comment]
Thanks for checking -- let us know what you find! We've been letting this PR sit for too long, and it would be good to get it merged!

**Comment by michelebucelli** [comment]
I built and ran the test on a different machine and it passes there too. That machine uses the same set of dependency libraries (Boost, PETSc etc.) as my personal one, so if something is wrong due to some library version mismatch that wouldn't be caught.

**Comment by bangerth** [comment]
I tried and it works on my local machine.

Can you try to rebase your commit on current "master"? This should also make the merge commits you currently have go away.

**Comment by peterrum** [comment]
I'll try to wrap this PR up in the next days.

**Comment by peterrum** [comment]
@michelebucelli Sorry for the delay! It has been some busy months/weeks. Your two PRs are very much appreciated!

**Comment by michelebucelli** [comment]
@peterrum Don't worry about it, it's totally understandable! Thank you for the great work in developing dealii!

**Pull request merged**
