### PR TITLE
Better document FESystem.

### PR DESCRIPTION
**Pull request by bangerth**
A good investigative Friday afternoon occupation spurred by an
innocent-looking question by Marek Capek on the mailing list. It
turns out to be surprisingly difficult to call the FESystem
constructor that takes a vector of base elements as pointers,
and yet not create a memory leak. Fun stuff :-)

### CODE REVIEW

**Comment by tjhei** [comment]
Sorry for being slightly off topic: I have thought about this problem a while ago and came to the conclusion that a .reinit() would be an elegant solution. Thoughts?

**Comment by bangerth** [comment]
Probably. I think that if you have to spend two pages describing how to calla function, then its interface is poorly designed and should be replaced :-)

The reinit might be useful but it is not useful if you want to make your member variable const. For better or worse, we're also stuck with the interface we have, at least for the foreseeable future...

**Comment by tjhei** [comment]
One more suggestion to avoid the awkwardness of the ```VectorElementDestroyer```: how about we add a constructor that takes a ```std::vector< std::unique_ptr<FE> >```?

**Comment by bangerth** [comment]
Yes, I thought about that too. It's clearly the way to go. Problem is that `std::unique_ptr` is a C++11 thing, and that there is not replacement in BOOST. That's also the reason why we still have places with `std::auto_ptr` which is deprecated but for which we don't have a good replacement.

**Comment by bangerth** [comment]
Of course, we could add such a constructor and guard it with `#ifdef DEAL_II_USE_CXX11`.

**Comment by tjhei** [comment]
What do you think of adding a constructor with autoptr then?

**Comment by bangerth** [comment]
Since `autoptr` is deprecated I would rather not do that. I think the way forward is to do something like
```
  namespace std_cxx11 {
#ifdef DEAL_II_USE_CXX11
    using std::unique_ptr;
#else
    template <typename T> class unique_ptr {
      // implement in terms of std_cxx11::shared_ptr by just implementing the
      // necessary methods
    };
#endif
  }
```
This gives us a way forward with replacing all of the locations where we currently use `auto_ptr`. But that's for a separate patch if you allow me to.

**Comment by tjhei** [comment]
> But that's for a separate patch if you allow me to.

Makes sense. We can always remove the ```VectorElementDestroyer``` stuff later.

**Comment by tjhei** [comment]
Good idea to reimplement unique_ptr using auto_ptr. Let me know if you want me to add the FESystem constructor.

**Pull request merged**
