### PR TITLE
Add DiscreteTime::serialize() and DiscreteTime::memory_consumption()

### PR DESCRIPTION
**Pull request by pcafrica**
As the title says.

Solves #17250 and is a requirement for #12429.

### CODE REVIEW

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
Excellent, thank you! This looks great to me, and I'll update step-83 accordingly once this is merged. I will gladly let you add a test in `tests/serialization/` as a follow-up if you had a minute to write one!

**Comment by bangerth** [comment]
Feel free to also add a changelog entry, either here or in a separate patch.

**Review by blaisb — APPROVED** [review]

**Comment by pcafrica** [comment]
I'm adding a test and a changelog entry in a few minutes :)

**Pull request merged**
