### PR TITLE
Use lambdas to make some code simpler.

### PR DESCRIPTION
**Pull request by bangerth**
I needed to do something fun, so I made a piece of code a bit simpler by
using lambdas. The changes are probably best viewed side-by-side. Note that
I had to capture two of the variables by value, rather than the default reference,
to make sure I get the current value in the loop.

### CODE REVIEW

**Comment by drwells** [comment]
I have a related question to this: should we consider `std::bind` deprecated in favor of lambdas?

**Comment by tamiko** [comment]
@bangerth Couldn't you have at least squeezed one line less out of your change set :-P
+14 -15 would have looked much nicer!

**Comment by bangerth** [comment]
@drwells -- I actually like `std::bind`: it nicely documents what one is actually doing. And, after some getting used to, the syntax with `placeholders::_1` is actually quite nicely self-documenting. I would venture the guess that you'd need more lines of code with lambdas. So I would vote no.

@tamiko -- but the cyclomatic complexity is way smaller: only one loop, instead of two!

**Comment by bangerth** [comment]
I'm going to add that this patch was surprisingly painful to write: if you have a syntax error in the lambda itself, then my compiler (gcc 4.8) didn't tell me about this, but gave me a very long, impenetrable error that I am using a variant of `Threads::new_task` but am not defining it. (And that this is an error because of `-fno-permissive`.) Finding the real problem, and getting the patch to work was not a pleasant experience.

**Comment by bangerth** [comment]
Let's try this again...

**Comment by drwells** [comment]
@tjhei Is there something wrong with the tester? Things seem clogged.

**Comment by drwells** [comment]
Hmm. @bangerth would you mind rebasing and force pushing? That should reenable the tester, which seems to be working again.

**Comment by tjhei** [comment]
> Is there something wrong with the tester? Things seem clogged.

yes, the tubes were clogged. Hopefully things are better now.

**Comment by bangerth** [comment]
OK, I rebased. Let's see if that helps any.

**Pull request merged**
