### PR TITLE
Deprecate (hp::)DoFHandler::invalid_dof_index.

### PR DESCRIPTION
**Pull request by bangerth**
Also replace all uses by numbers::invalid_dof_index. I can't see a reason to
have both of these numbers, in particular because the only logical choice is
to have them have the same value.

This is a follow-up to #4526 and should be merged after that. Only the last of the commits here is actually new, compared to #4526. In preparation for #3511.

### CODE REVIEW

**Comment by drwells** [comment]
Should we merge this with the duplicated commits? I am not sure if GitHub is smart enough to handle this correctly.

**Comment by bangerth** [comment]
Rebased.

**Comment by drwells** [comment]
I used `grep -R [^s]::invalid_dof_index` on this patch and there are still a few places we need to fix:
1. It looks like we still use `DoFHandlerType::invalid_dof_index` in a few places (`dof_tools.cc`, `dof_tools_sparsity.cc`, and `dof_renumbering.cc`).
2. The documentation in `dof_tools.h` still references this value.

**Comment by bangerth** [comment]
Great catch -- your regex was better than mine :-) I amended the commit by all of the places so found.

**Comment by kronbichler** [comment]
Looks good to me, but I let @drwells do the merge.

**Comment by drwells** [comment]
I found (`grep -R [^:]invalid_dof_index`) one more that, without the namespace declaration, refers to the now deprecated variable: line 1077 of `hp/dof_handler.h`. That should be all of them.

**Comment by bangerth** [comment]
Good catch -- but that went away with one of my previous patches (#4533). So I think this should be ready now.

**Comment by drwells** [comment]
@bangerth It looks like we acquired a merge conflict: otherwise this is OK.

**Comment by bangerth** [comment]
I tried the fancy new merge conflict resolver on the github page. It creates a merge commit from master, but otherwise works pretty nicely. Should work now!

**Pull request merged**
