### PR TITLE
improve consistency of dim=1 objects in the library (p::d::Tria, KellyEstimator,...)

### PR DESCRIPTION
**Pull request by davydden**
The second commit is related to https://github.com/dealii/dealii/issues/5972

### CODE REVIEW

**Comment by tjhei** [comment]
can you add a test that creates a 1d ``p::d`` tria?

**Comment by davydden** [comment]
> can you add a test that creates a 1d p::d tria?

It is still in `AssertThrow(false, ExcNotImplemented())`. This PR is only to make things compile, but no attempt for implementation in 1D is here. I will do that separately.

**Comment by bangerth** [comment]
Would you mind keeping these commits for separate PRs? They are entirely unrelated.

**Comment by davydden** [comment]
> Would you mind keeping these commits for separate PRs? They are entirely unrelated.

yes, i can, it's jut recompilation time on my mac which takes forever (like 30min if I switch branches). But to be fair, they **are** related as they fix 1D mismatches in the library.

**Comment by davydden** [comment]
> Would you mind keeping these commits for separate PRs? They are entirely unrelated.

p.s. my idea was that changes are small enough to keep them within a single PR in separate commits.

**Comment by bangerth** [comment]
What I typically do in cases like this is make sure everything compiles and works, and then create two branches off master to which I cherry-pick the individual commits. These are then pushed for review.

**Comment by tjhei** [comment]
> It is still in AssertThrow(false, ExcNotImplemented()). This PR is only to make things compile, but no attempt for implementation in 1D is here. I will do that separately.

The test can skip execution of it for now. This will ensure that things can still be instantiated in the future.

**Comment by davydden** [comment]
> The test can skip execution of it for now. This will ensure that things can still be instantiated in the future.

ah, sure, i will add one.

**Comment by davydden** [comment]
@bangerth 

i have split this into several PRs

**Pull request closed without merging**
