### PR TITLE
Fix minor flaw in documentation in table.h

### PR DESCRIPTION
**Pull request by BenBrands**
Having worked with the class `Table` I think there is a minor flaw in the doc.

### CODE REVIEW

**Comment by drwells** [comment]
Shouldn't it be `size(i)`?

**Comment by davydden** [comment]
> Shouldn't it be size(i)?

Don’t think so.

**Comment by davydden** [comment]
@drwells or did u mean ‘size(0)’ and size(1)?

**Comment by BenBrands** [comment]
I think @davydden is right!

**Comment by kronbichler** [comment]
I would definitely agree with the (modified) suggestion of @drwells to use `t.size(0)` and `t.size(1)` because that is the most intuitive way to access the rows and columns of the table, rather than first getting the `TableIndices` field and then access its entries. Even though the implementation boils down to the same thing, of course.

**Comment by davydden** [comment]
> I would definitely agree with the (modified) suggestion of @drwells to use t.size(0) and t.size(1)

I also agree with that, it's much more intuitive. 

p.s. I misunderstood what @drwells meant by 

> Shouldn't it be size(i)

as those loops have indices `i` in them as well.

**Comment by drwells** [comment]
Yes, that's what I meant: I was looking at the documentation `TableBase::size(const unsigned int i)`;

I did not see (even though it is on the next line) the overload for the table indices; I have a slight preference for `size(0)` and `size(1)` but the original proposal also would have worked.

**Pull request merged**
