### PR TITLE
Fix step-16.

### LINKED ISSUE #6633: Step-16 multigrid performace regression
The output of step-16 on my machine is
```
DEAL::Cycle 0
DEAL::   Number of active cells:       20
DEAL::   Number of degrees of freedom: 25 (by level: 8, 25)
DEAL:cg::Starting value 0.510691
DEAL:cg::Convergence step 71 value 5.01342e-13
DEAL::Cycle 1
DEAL::   Number of active cells:       41
DEAL::   Number of degrees of freedom: 52 (by level: 8, 25, 41)
DEAL:cg::Starting value 0.455356
DEAL:cg::Convergence step 122 value 4.87066e-13
DEAL::Cycle 2
DEAL::   Number of active cells:       80
DEAL::   Number of degrees of freedom: 100 (by level: 8, 25, 61, 52)
DEAL:cg::Starting value 0.394469
DEAL:cg::Convergence step 304 value 9.71614e-13
DEAL::Cycle 3
DEAL::   Number of active cells:       161
DEAL::   Number of degrees of freedom: 190 (by level: 8, 25, 77, 160)
DEAL:cg::Starting value 0.322156
DEAL:cg::Convergence step 190 value 4.70318e-13
DEAL::Cycle 4
DEAL::   Number of active cells:       311
DEAL::   Number of degrees of freedom: 364 (by level: 8, 25, 86, 227, 174)
DEAL:cg::Starting value 0.279667
DEAL:cg::Convergence step 250 value 2.18493e-13
DEAL::Cycle 5
DEAL::   Number of active cells:       593
DEAL::   Number of degrees of freedom: 667 (by level: 8, 25, 89, 231, 490, 96)
DEAL:cg::Starting value 0.215917
DEAL:cg::Convergence step 277 value 9.50466e-13
DEAL::Cycle 6
DEAL::   Number of active cells:       1127
DEAL::   Number of degrees of freedom: 1251 (by level: 8, 25, 89, 274, 760, 417, 178)
DEAL:cg::Starting value 0.185906
DEAL:cg::Convergence step 282 value 9.09004e-13
DEAL::Cycle 7
DEAL::   Number of active cells:       2144
DEAL::   Number of degrees of freedom: 2359 (by level: 8, 25, 89, 308, 779, 1262, 817)
DEAL:cg::Starting value 0.141519
DEAL:cg::Convergence step 947 value 8.46910e-13
```

The linear solver takes hundreds of iterations to converge. This is entirely different with the documentation in step-16. Can someone take a look?

### PR DESCRIPTION
**Pull request by adamqc**
Fixes #6633.

### CODE REVIEW

**Comment by bangerth** [comment]
I think you should get credit for finding this. Would you mind putting an entry into `doc/news/changes/minor` for this fix?

**Comment by adamqc** [comment]
Will do tomorrow. It is 11pm in China, I’m out of office now.

**Comment by bangerth** [comment]
On 05/20/2018 11:12 PM, Ce Qin wrote:
> Will do tomorrow. It is 11pm in China,

I know, and you should definitely stop working :-) Unfortunately, I'm still at 
work on my lectures for tomorrow in Beijing :-(

**Comment by adamqc** [comment]
Such a pity, I’m in Chengdu so I can’t meet you. Hope you enjoy your time in China.

**Comment by bangerth** [comment]
On 05/20/2018 11:33 PM, Ce Qin wrote:
> Such a pity, I’m in Chengdu so I can’t meet you. Hope you enjoy your time in 
> China.

Tremendously! I'm sure I'll make it to Chengdu one day!

**Pull request merged**
