### PR TITLE
Step 3 tutorial: problem statement inconsistency 

### PR DESCRIPTION
**Pull request by christophkammer1989**
Documentation for step 3+4 tutorials states that Poisson problem is solved on domain [0,1]^dim. The code for the solver is implemented to solve Poisson problem on domain [-1,1]^dim.
Making pull request to resolve issue with inconsistent documentation,

### CODE REVIEW

**Comment by masterleinad** [comment]
Did you already want to fix something for `step-4`?

**Comment by christophkammer1989** [comment]
I didn't spot any other issues with the documentation. I only referenced 
step-4 because it builds on the problem statement from step-3.


Best,

Christoph

**Comment by christophkammer1989** [comment]
Should be all good now

**Comment by christophkammer1989** [comment]
Done, I think I just did that.. could you double-check if it worked? (my 
experience with git is limited)

**Comment by masterleinad** [comment]
> Done, I think I just did that.. could you double-check if it worked? (my experience with git is limited)

No, it didn't. You need to something like
```
git rebase -i 5060a34c72e78afdebda98ccc2e9395a43fedffd^
```
and then mark all but the first commit as `squash`. Finally, force-push to remote branch via
```
git push -f origin master
```

**Pull request merged**
