### PR TITLE
CMake: Considerably improve summary message

### PR DESCRIPTION
**Pull request by tamiko**
This commit restructures the summary output at the end of the configure
phase to take latest results of UI and CLI development into account:

[1] Norman, D. A. (2002). "Emotion & Design: Attractive things work
    better". Interactions Magazine, ix (4). pp. 36–42. Retrieved 20 April 2014.

### CODE REVIEW

**Comment by tamiko** [comment]
@bangerth Well, there is always this little gem (the old April's fools) that we could merge last minute :stuck_out_tongue:

**Comment by bangerth** [comment]
Again? Either way, I approve!

**Comment by bangerth** [comment]
But let me close this nonetheless before someone accidentally hits the merge button :-)

**Comment by davydden** [comment]
@tamiko out of curiosity, what's the output?

**Comment by tamiko** [comment]
@davydden 
```
[...]
-- Setting up testsuite
-- Setting up testsuite - Done
 ______________________________________________________________________________________________ 
/ ###                                                                                          \
| #                                                                                            |
| #  deal.II configuration:                                                                    |
| #        CMAKE_BUILD_TYPE:       DebugRelease                                                |
| #        BUILD_SHARED_LIBS:      ON                                                          |
| #        CMAKE_INSTALL_PREFIX:   /usr/local                                                  |
| #        CMAKE_SOURCE_DIR:       /home/tamiko/workspace/dealii                               |
| #                                (version 9.1.0-pre, shortrev a87e7595bd)                    |
| #        CMAKE_BINARY_DIR:       /home/tamiko/workspace/dealii/build                         |
| #        CMAKE_CXX_COMPILER:     GNU 7.3.0 on platform Linux x86_64                          |
| #                                /usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0/c++                  |
| #                                                                                            |
| #  Configured Features (DEAL_II_ALLOW_BUNDLED = ON, DEAL_II_ALLOW_AUTODETECTION = ON):       |
| #      ( DEAL_II_WITH_64BIT_INDICES = OFF )                                                  |
| #        DEAL_II_WITH_ADOLC set up with external dependencies                                |
| #        DEAL_II_WITH_ARPACK set up with external dependencies                               |
| #        DEAL_II_WITH_ASSIMP set up with external dependencies                               |
| #        DEAL_II_WITH_BOOST set up with external dependencies                                |
| #      ( DEAL_II_WITH_CUDA = OFF )                                                           |
| #        DEAL_II_WITH_CXX14 = ON                                                             |
| #        DEAL_II_WITH_CXX17 = ON                                                             |
| #        DEAL_II_WITH_GMSH set up with external dependencies                                 |
| #        DEAL_II_WITH_GSL set up with external dependencies                                  |
| #      ( DEAL_II_WITH_HDF5 = OFF )                                                           |
| #        DEAL_II_WITH_LAPACK set up with external dependencies                               |
| #        DEAL_II_WITH_METIS set up with external dependencies                                |
| #      ( DEAL_II_WITH_MPI = OFF )                                                            |
| #        DEAL_II_WITH_MUPARSER set up with external dependencies                             |
| #        DEAL_II_WITH_NANOFLANN set up with external dependencies                            |
| #        DEAL_II_WITH_NETCDF set up with external dependencies                               |
| #        DEAL_II_WITH_OPENCASCADE set up with external dependencies                          |
| #      ( DEAL_II_WITH_P4EST = OFF )                                                          |
| #      ( DEAL_II_WITH_PETSC = OFF )                                                          |
| #      ( DEAL_II_WITH_SCALAPACK = OFF )                                                      |
| #      ( DEAL_II_WITH_SLEPC = OFF )                                                          |
| #        DEAL_II_WITH_SUNDIALS set up with external dependencies                             |
| #        DEAL_II_WITH_THREADS set up with external dependencies                              |
| #      ( DEAL_II_WITH_TRILINOS = OFF )                                                       |
| #        DEAL_II_WITH_UMFPACK set up with external dependencies                              |
| #        DEAL_II_WITH_ZLIB set up with external dependencies                                 |
| #                                                                                            |
| #  Component configuration:                                                                  |
| #      ( DEAL_II_COMPONENT_DOCUMENTATION = OFF )                                             |
| #        DEAL_II_COMPONENT_EXAMPLES                                                          |
| #      ( DEAL_II_COMPONENT_PACKAGE = OFF )                                                   |
| #      ( DEAL_II_COMPONENT_PYTHON_BINDINGS = OFF )                                           |
| #                                                                                            |
| #  Detailed information (compiler flags, feature configuration) can be found in detailed.log |
| #                                                                                            |
| #  Run  $ make info  to print a help message with a list of top level targets                |
| #                                                                                            |
\ ###                                                                                          /
 ---------------------------------------------------------------------------------------------- 
        \  ^___^
         \ (ooo)\_______
           (___)\       )\/\
                ||----w |
                ||     ||
```

**Comment by davydden** [comment]
@tamiko 🤣 👍 ❤️

**Pull request closed without merging**
