### PR TITLE
Update PETSc compatibility stuff for SNES and TS

### PR DESCRIPTION
**Pull request by stefanozampini**
Remove old destroy_matrix

Depends on https://github.com/dealii/dealii/pull/15116

### CODE REVIEW

**Comment by stefanozampini** [comment]
Split of https://github.com/dealii/dealii/pull/15065

**Comment by bangerth** [comment]
Please rebase when #15116 is merged, and let us know when that has happened.

**Comment by stefanozampini** [comment]
@bangerth rebased

**Comment by stefanozampini** [comment]
@bangerth ping

**Review by luca-heltai — APPROVED** [review]

**Review by bangerth — APPROVED** [review]

**Pull request merged**
