### PR TITLE
Testsuite: Fix deal.II/grid_tools_halo_layer* tests

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Comment by bangerth** [comment]
That's a bit of a shame -- because you need to put everything into the header, and also because the previous interface made sure that whatever you passed as argument is indeed convertible to the interface we need, rather than finding about this at the calling site in library code.

Do you happen to know why the implicit conversion does not work?

**Comment by tamiko** [comment]
> Do you happen to know why the implicit conversion does not work?

I see at least half a dozen of bugfixes for 4.9 with respect to
std::function and conversion rules/properties. I'm not able to track it
down to a specific bug :-/

What I think that happens is that gcc-4.8* (and older) incorrectly
deduce that dealii::IteratorFilters::MaterialIdEqualTo is not a callable
object with respect to the std::function<...> object (it works for
boost-function). After that, inheritance deduction fails:

  ‘dealii::IteratorFilters::MaterialIdEqualTo’ is not derived from
  ‘const std::function<bool(const typename Container::active_cell_iterator&)>’

In my opinion the best course of action is to avoid those situations and
simply not use std::function as the only signature. And (with the
exception of the internal function) the code is small enough to be
present in the header.

**Comment by davydden** [comment]
i suppose dropping `gcc-4.8` in favour of newer versions is not an option?

**Comment by tjhei** [comment]
An alternative would be to make the argument a simple function pointer and just use std_cxx11::bind if you want to pass something else. We use that in other places (like threads/tasks).

> i suppose dropping gcc-4.8 in favour of newer versions is not an option?

No chance, my desktop (not maintained by me) is running ubuntu 12.04 with gcc 4.6 and I would like to continue to use deal.II. :-)

**Comment by bangerth** [comment]
Let's think about the way forward: broken compilers will eventually be replaced by working compilers, whereas workarounds will not (simply because we will forget that we worked around something, or because we want to stay backward compatible). We also probably agree that using std::function is the better design because it enforces the interface we want, and allows us to put the implementation into the .cc file.

In the current case, we can stick with the current design if we make sure that all of the places where we call this function contain an *explicit* cast to std::function. We've been doing the same for the calls to Threads::new_task in a number of places already. The only people suffering from this are users of compilers that cannot do the implicit conversion -- they, too, will have to use this workaround in their user codes. But that's not very difficult to do, and we could describe it in the documentation of the function if we wanted.

**Comment by tamiko** [comment]
I don't think that it is a terribly good idea to force a ```std::function``` into this signature over a loop over cells. The whole thread business is not a good analogy, because a call there is either linked to far greater runtime costs (setting up a thread), or the level of granularity can be chosen differently.

Furthermore, this interface switch is flexible - we can always switch back to a ```std::function``` object later.

**Comment by davydden** [comment]
I think these functions won't each much execution time as compared to assembly and solving linear systems. They are going to be called once during a setup, for non-linear problems that won't contribute to total solution time anything at all, IMO. I, personally, wouldn't worry about costs here.

**Comment by bangerth** [comment]
That's how I see it too. I've come to value conceptual clarity and good error messages over speed in unimportant places :-)

**Comment by tamiko** [comment]
*shrug* If this is such a highly philosophical mission, I submit.

**Comment by tamiko** [comment]
*hng* Stupid github.

**Comment by tamiko** [comment]
I'll just fix the test and reopen. Apparently, pushing a merged state closes the pull-request...

**Comment by tamiko** [comment]
@bangerth Just "fixes" the test now, not the problem. Please merge.

**Pull request merged**
