### PR TITLE
Fix warnings regarding extra';' and unused parameters

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes the warnings in https://cdash.kyomu.43-1.org/viewBuildError.php?type=1&buildid=12710
and https://cdash.kyomu.43-1.org/viewBuildError.php?type=1&buildid=12723

### CODE REVIEW

**Comment by drwells** [comment]
Thanks for taking the time to make these little fixes. 👍

**Comment by bangerth** [comment]
These sort of fixes were @drwells 's realm not so long ago! :-)

**Comment by bangerth** [comment]
It's too bad we don't use C++14 yet, or these could all have been implemented as template variables (http://en.cppreference.com/w/cpp/language/variable_template).

**Comment by bangerth** [comment]
OK to merge once the tester is happy.

/run-tests

**Comment by drwells** [comment]
True. Now I am reminiscing about the great typo fixing run of 2015 :)

This does remind me that I reran cppcheck recently and I don't believe that I submitted any changes (not that any are particularly severe).

**Pull request merged**
