### PR TITLE
[8.3] Do not mark Epetra_Map interfaces as deprecated: needs more work

### PR DESCRIPTION
**Pull request by kronbichler**
As discussed in #1215

### CODE REVIEW

**Comment by tjhei** [comment]
Looks good to me. Does "needs more work" mean you still want to add to this PR?

**Comment by kronbichler** [comment]
No, "needs more work" refers to the work I do on master. Sorry for the confusion :-)

**Comment by bangerth** [comment]
Since the deprecation markings are still active on master, could you add the note that was deleted from the changelog back to the one on master?

**Comment by bangerth** [comment]
(Patch is pre-approved -- please merge yourself.)

**Pull request merged**
