### PR TITLE
Generate the legend for the tutorial connection graph automatically.

### PR DESCRIPTION
**Pull request by bangerth**
This allows us to show the actual symbols for each kind, rather than having to
describe them in words.

Also update the way we draw lines between tutorials and code gallery codes.

### CODE REVIEW

**Comment by bangerth** [comment]
This moves toward resolving #1314.

**Comment by drwells** [comment]
The links on the graph for the code gallery entries just link to `dot_inline_dotgraph_1.svg` instead of the code gallery entry. I am not sure if they should link to anything in particular, but this behavior does not seem correct to me.

**Comment by bangerth** [comment]
They will. I already have the next patch ready that will achieve this (and more).

**Comment by drwells** [comment]
Okay, as long as you know this should be fine.

**Pull request merged**
