### PR TITLE
ScaLAPACKMatrix: remove small bug in parallel save/load

### PR DESCRIPTION
**Pull request by BenBrands**

### CODE REVIEW

**Comment by davydden** [comment]
I spoke with @BenBrands about testing this: it's not really possible as it depends on configuration of HDF5. So If I understood correctly, one would need to save with parallel configuration and load in serial  configuration to trigger the bug.

**Comment by davydden** [comment]
@BenBrands please add a changelog entry in `minor` section.

**Comment by bangerth** [comment]
On 08/09/2018 05:13 AM, Denis Davydov wrote:
> one would need to save with parallel configuration and load in serial 
> configuration to trigger the bug.

We have some tests that do this kind of thing. The way to achieve it is to run 
the test with N processors in MPI_COMM_WORLD, save, then create a subset 
communicator that has only one process and on that one load the data again 
(all other processes do nothing in that phase).

I'm pretty sure we have tests that do this kind of thing in the tests that 
check save/load of parallel triangulations.

**Comment by davydden** [comment]
> We have some tests that do this kind of thing

I think you misunderstood, not only it is related to MPI, but more importantly to the build of HDF5 and whether or not H5_HAVE_PARALLEL is defined. That’s the actual switch between the two self-written functions in Scalapack matrix.

**Comment by BenBrands** [comment]
I agree with @bangerth that save_parallel()/load_parallel() boil down to save_serial()/load_serial() when the process grid only contains one MPI process, even if pHDF5 is enabled. Using that one could mimic the behaviour of the serial functions and do a consistency check.
As I will not have time the next week to add such a test, I suggest to fix the bug and I will later on add a test. Do you agree, @davydden and @bangerth?

**Comment by davydden** [comment]
> I agree with @bangerth that save_parallel()/load_parallel() boil down to save_serial()/load_serial() when the process grid only contains one MPI process, even if pHDF5 is enabled.

Oh, if that’s how it works, then yes, sure. Then it’s me who misunderstood. Sorry about that.

**Pull request merged**
