### PR TITLE
Fix PETScWrappers::MatrixBase::set for 64bit and complex scalars

### PR DESCRIPTION
**Pull request by masterleinad**
Running the test suite with complex scalar type and 64bit indices `petsc_complex/element_access_01` and `petsc_complex/element_access_03` failed since `elide_zero_values==true` was implicitly assumed in `PETScWrappers::MatrixBase::set`.

### CODE REVIEW

**Comment by bangerth** [comment]
Well, this doesn't compile:
```
source/numerics/CMakeFiles/obj_numerics_debug.dir/matrix_creator_inst2.cc.o -c /home/bob/source/source/numerics/matrix_creator_inst2.cc
In file included from /home/bob/source/source/numerics/matrix_creator_inst2.cc:20:
In file included from /home/bob/source/source/numerics/matrix_creator.cc:16:
In file included from /home/bob/source/include/deal.II/numerics/matrix_creator.templates.h:41:
In file included from /home/bob/source/include/deal.II/lac/petsc_parallel_sparse_matrix.h:24:
/home/bob/source/include/deal.II/lac/petsc_matrix_base.h:1223:25: error: static_cast from 'const size_type *' (aka 'const unsigned int *') to 'PetscInt *' (aka 'int *') is not allowed
        col_index_ptr = static_cast<PetscInt *>(col_indices);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
How do the other, similar functions do this?

Would you mind putting together a test that ensures this doesn't happen to us again?

**Comment by bangerth** [comment]
Also, is there anything specific about the fact that you're using complex numbers? It would seem to me that the same problem should happen with other scalars, as long as we use 64-bit indices. My only explanation would be that we don't use the `set()` function in any of the tests, or that we don't run any testsuite with 64-bit PETSc.

**Comment by masterleinad** [comment]
Yes, I agree. It seems that we only use `set()` with a zero value and 64bit indices in `petsc_complex` tests.

**Comment by masterleinad** [comment]
Hmm... In other places, we simply use a C-style cast, but I cannot say that I like this. It's a bit unfortunate that `static_cast` can't convert an `unsigned int` pointer to an `int` pointer. So we are left with `reinterpret_cast`...

**Comment by masterleinad** [comment]
This compiles and passes all `petsc` tests both for 64bit and 32bit indices (and complex scalar type).

**Comment by drwells** [comment]
I don't understand why we need the 64bit index checks here. Since `types::global_dof_index` and `PetscInt` have to be the same size (though `PetscInt` is signed) shouldn't the same code work in both modes?

**Comment by masterleinad** [comment]
I tried to change as little as possible. All the tests also pass using the same code for 64bit indices for me.
Do you consider this to be safe?

**Comment by drwells** [comment]
I believe that what we have now is right but I don't think that we need to special case things for the 64 bit case: the same code should work with both 64 bit and 32 bit indices.

**Comment by masterleinad** [comment]
OK, I removed the special treatment for 64bit indices.

**Comment by drwells** [comment]
Does this work with 32 and 64 bit PETSc installations? If so we should merge this.

**Comment by masterleinad** [comment]
Yes, it passes all tests for both 32bit and 64bit PETSc installations (with and without complex scalar type) for me.

**Comment by drwells** [comment]
Good. Thanks for doing the extra macro cleanup; this looks nice :+1:

**Pull request merged**
