### PR TITLE
Fix some things cppcheck found.

### PR DESCRIPTION
**Pull request by drwells**
We haven't run cppcheck in awhile; here are some new things.

I also found a few cases where we used `0` or `NULL` instead of `nullptr`; those have also been fixed.

### CODE REVIEW

**Comment by bangerth** [comment]
OK to merge once the tester is happy.

/run-tests

**Comment by jppelteret** [comment]
@drwells There are a few more cases of `= 0` instead of `= null_ptr` floating around in [`differentiation/ad/ad_number_traits.h`](https://github.com/dealii/dealii/blob/master/include/deal.II/differentiation/ad/ad_number_traits.h). Would it perhaps be possible for you to add fixes for them to this patchset?

**Comment by bangerth** [comment]
Current build fails:
```

/home/bob/source/include/deal.II/lac/solver_bicgstab.h: In constructor â€˜dealii::SolverBicgstab<VectorType>::SolverBicgstab(dealii::SolverControl&, dealii::VectorMemory<VectorType>&, const dealii::SolverBicgstab<VectorType>::AdditionalData&)â€™:
/home/bob/source/include/deal.II/lac/solver_bicgstab.h:315:34: error: constructor delegation follows mem-initializer for â€˜class dealii::Solver<VectorType>â€™
   SolverBicgstab<VectorType>(data)
                                  ^
/home/bob/source/include/deal.II/lac/solver_bicgstab.h: In constructor â€˜dealii::SolverBicgstab<VectorType>::SolverBicgstab(dealii::SolverControl&, const dealii::SolverBicgstab<VectorType>::AdditionalData&)â€™:
/home/bob/source/include/deal.II/lac/solver_bicgstab.h:325:34: error: constructor delegation follows mem-initializer for â€˜class dealii::Solver<VectorType>â€™
   SolverBicgstab<VectorType>(data)
                                  ^
In file included from /home/bob/source/include/deal.II/lac/solver_selector.h:29:0,
                 from /home/bob/source/examples/step-44/step-44.cc:60:
/home/bob/source/include/deal.II/lac/solver_minres.h: At global scope:
/home/bob/source/include/deal.II/lac/solver_minres.h:150:59: error: ISO C++ forbids declaration of â€˜SolverQMRSâ€™ with no type [-fpermissive]
   SolverQMRS(const AdditionalData &data = AdditionalData());
                                                           ^
/home/bob/source/include/deal.II/lac/solver_minres.h:159:1: error: prototype for â€˜dealii::SolverMinRes<VectorType>::SolverMinRes(const dealii::SolverMinRes<VectorType>::AdditionalData&)â€™ does not match any in class â€˜dealii::SolverMinRes<VectorType>â€™
 SolverMinRes<VectorType>::SolverMinRes (const AdditionalData &)
 ^
/home/bob/source/include/deal.II/lac/solver_minres.h:91:3: error: candidates are: dealii::SolverMinRes<VectorType>::SolverMinRes(dealii::SolverControl&, const dealii::SolverMinRes<VectorType>::AdditionalData&)
   SolverMinRes (SolverControl        &cn,
   ^
/home/bob/source/include/deal.II/lac/solver_minres.h:83:3: error:                 dealii::SolverMinRes<VectorType>::SolverMinRes(dealii::SolverControl&, dealii::VectorMemory<VectorType>&, const dealii::SolverMinRes<VectorType>::AdditionalData&)
   SolverMinRes (SolverControl            &cn,
   ^
/home/bob/source/include/deal.II/lac/solver_minres.h: In constructor â€˜dealii::SolverMinRes<VectorType>::SolverMinRes(dealii::SolverControl&, dealii::VectorMemory<VectorType>&, const dealii::SolverMinRes<VectorType>::AdditionalData&)â€™:
/home/bob/source/include/deal.II/lac/solver_minres.h:172:28: error: constructor delegation follows mem-initializer for â€˜class dealii::Solver<VectorType>â€™
   SolverMinRes<VectorType>()
                            ^
/home/bob/source/include/deal.II/lac/solver_minres.h: In constructor â€˜dealii::SolverMinRes<VectorType>::SolverMinRes(dealii::SolverControl&, const dealii::SolverMinRes<VectorType>::AdditionalData&)â€™:
/home/bob/source/include/deal.II/lac/solver_minres.h:182:28: error: constructor delegation follows mem-initializer for â€˜class dealii::Solver<VectorType>â€™
   SolverMinRes<VectorType>()
                            ^
FAILED: /usr/bin/c++   -DDEBUG -DTBB_DO_ASSERT=1 -DTBB_USE_DEBUG -Iinclude -I/home/bob/source/include -I/home/bob/source/bundled/tbb41_20130401oss/include -I/home/bob/source/bundled/umfpack/UMFPACK/Include -I/home/bob/source/bundled/umfpack/AMD/Include -I/home/bob/source/bundled/boost-1.62.0/include -I/home/bob/source/bundled/muparser_v2_2_4/include -I/home/bob/libs/parmetis-4.0.3/include -I/home/bob/libs/oce-OCE-0.17/include/oce     -pedantic -fPIC -Wall -Wextra -Wpointer-arith -Wwrite-strings -Wsynth -Wsign-compare -Wswitch -Woverloaded-virtual -Wno-deprecated-declarations -Wno-literal-suffix -std=c++11 -Wno-parentheses -Wno-unused-local-typedefs -Og -ggdb -Wa,--compress-debug-sections -MMD -MT examples/CMakeFiles/step-51.debug.dir/step-51/step-51.cc.o -MF "examples/CMakeFiles/step-51.debug.dir/step-51/step-51.cc.o.d" -o examples/CMakeFiles/step-51.debug.dir/step-51/step-51.cc.o -c /home/bob/source/examples/step-51/step-51.cc
In file included from /home/bob/source/examples/step-51/step-51.cc:35:0:
/home/bob/source/include/deal.II/lac/solver_bicgstab.h: In constructor â€˜dealii::SolverBicgstab<VectorType>::SolverBicgstab(dealii::SolverControl&, dealii::VectorMemory<VectorType>&, const dealii::SolverBicgstab<VectorType>::AdditionalData&)â€™:
/home/bob/source/include/deal.II/lac/solver_bicgstab.h:315:34: error: constructor delegation follows mem-initializer for â€˜class dealii::Solver<VectorType>â€™
   SolverBicgstab<VectorType>(data)
                                  ^
/home/bob/source/include/deal.II/lac/solver_bicgstab.h: In constructor â€˜dealii::SolverBicgstab<VectorType>::SolverBicgstab(dealii::SolverControl&, const dealii::SolverBicgstab<VectorType>::AdditionalData&)â€™:
/home/bob/source/include/deal.II/lac/solver_bicgstab.h:325:34: error: constructor delegation follows mem-initializer for â€˜class dealii::Solver<VectorType>â€™
   SolverBicgstab<VectorType>(data)
                                  ^
```

As for additional changes -- they could also go into a separate patch if that makes things simpler.

**Comment by drwells** [comment]
It looks like we don't actually use the headers when compiling the library.

Regardless, I fixed the errors.

**Comment by bangerth** [comment]
I think your originally idea of using the delegating constructors was not wrong. You just had the call to the delegated constructor *after* initializing a member variable. It needs to be the first call in the member initializer list IIRC.

**Comment by drwells** [comment]
I liked the delegating constructor approach more too; perhaps I don't really understand it. I went with the other approach since it is not clear to me when the parent class gets set up: i.e., initializing the base class and then calling the delegating constructor doesn't make sense since the delegating constructor itself also sets up the base class. Is this correct?

**Comment by bangerth** [comment]
If you list a delegating constructor first in the base/member initializer list, then the compiler skips the call to the base class constructors (because the delegated-to constructor will do this). As a consequence, the delegated-to constructor has to come *first* in the base/member initializer list: otherwise, you'd initialize the current class's members *before* the base class is initialized.

**Pull request merged**
