### PR TITLE
Grid tools debug

### LINKED ISSUE #8517: GridTools::Cache does not in fact cache things sometimes :-)
Looking at #8516, here is some code in `GridTools::Cache` (in `source/grid/grid_tools_cache.cc`):
```
template <int dim, int spacedim>
  const RTree<
    std::pair<BoundingBox<spacedim>,
              typename Triangulation<dim, spacedim>::active_cell_iterator>> &
  Cache<dim, spacedim>::get_cell_bounding_boxes_rtree() const
  {
    if (update_flags & update_cell_bounding_boxes_rtree)
      {
        std::vector<std::pair<
          BoundingBox<spacedim>,
          typename Triangulation<dim, spacedim>::active_cell_iterator>>
                     boxes(tria->n_active_cells());
        unsigned int i = 0;
        for (const auto &cell : tria->active_cell_iterators())
          boxes[i++] = std::make_pair(mapping->get_bounding_box(cell), cell);

        cell_bounding_boxes_rtree = pack_rtree(boxes);
      }
    return cell_bounding_boxes_rtree;
  }
```
If the flag is set, it recomputes the bounding box and then returns it. The *idea* of course is that once computed, the cache will know about it the next time the function is called -- but it forgets to clear the flag in the update flags. Here is a function that does it correctly:
```
  template <int dim, int spacedim>
  const KDTree<spacedim> &
  Cache<dim, spacedim>::get_vertex_kdtree() const
  {
    if (update_flags & update_vertex_kdtree)
      {
        vertex_kdtree.set_points(tria->get_vertices());
        update_flags = update_flags & ~update_vertex_kdtree;     // *** clearing the flag ***
      }
    return vertex_kdtree;
  }
```

We should go through all of the `get_()` functions of this class to see whether they really do clear the respective flag in the `if()` block.

@mjayayadharan -- want to give this a try?

### PR DESCRIPTION
**Pull request by mjayadharan**
Fixes #8517.

### CODE REVIEW

**Comment by masterleinad** [comment]
Please create two separate pull requests if you are fixing unrelated issues.

Could you also add a test case that would fail prior to this pull request?

**Comment by tjhei** [comment]
And if you need help with anything @masterleinad said, talk to one of us!

**Comment by bangerth** [comment]
@mjayadharan -- come see me tomorrow and we'll fix the git issues.

@dealii/dealii : There's no test that can check this. What was happening is that we wanted to cache things, but forgot to set the flag that we had already computed something. The result wasn't wrong -- it was just inefficient: *Every* time we were looking up the information we re-computed it.

**Comment by mjayadharan** [comment]
I have separated two issues with this pull request. Now please take at look.

**Comment by bangerth** [comment]
/rebuild

OK to merge if it passes the tester (which I strongly suspect it will). Thanks for the patch, @mjayadharan !

**Comment by bangerth** [comment]
Fixes #8517.

**Comment by mjayadharan** [comment]
Glad that it worked out.

**Comment by luca-heltai** [comment]
Thanks for fixing my mistake!

:)

**Pull request merged**
