### PR TITLE
Add doxygen download action to indent

### PR DESCRIPTION
**Pull request by jpthiele**
This adds the action `ssciwr/doxygen-install` to download a more recent version of doxygen.
This change is necessary for the dark mode support of graphviz dot graphs proposed in #16013.

### CODE REVIEW

**Comment by jpthiele** [comment]
Some notes in the new warnings that are being generated and suppressed:
- ` multiple use of section label '<label>' while adding anchor` does not like all steps having a section named introduction and similar. It builds fine and they all link correctly in the respective steps. The only other way around it would be to have longer titles, i.e. Introduction to step-1, Results of step-1 but that would be somewhat tedious and it works anyways.
- `@copybrief/@copydetails or @copydoc target not found` it warns that it has not found it but inserts the correct documentation anyways so this is somewhat spurious
- `has @param documentation sections but no arguments` I just found out and check that this is a bug in doxygen 1.9.5, so we could bump the version in the `indent.yml` to 1.9.6 instead. 
- `explicit link request to` two were actual errors I just found. One referenced dealii::Vector<Number> but the namespace is removed for doxygen so that is completely correct. The other was in the changelogs and missing the `VectorTools` namespace as it was `VectorTools::point_values()/::point_gradients()` and so `point_gradients()` was flagged as unknown. The final error says it's located in `deprecated:77` which is not a file I was able to find so I have no idea what the problem is there. 
Should I or someone else find that reference than it might make sense to remove that warning from the suppressed list.

**Comment by jpthiele** [comment]
Update 1:
The `multiple use of section label` errors are relatively easy to fix by doing a search for `<a name="` and replace it by `<a name="XY` for step-XY or with`<a name="ABC-XYZ"` for changes from version A.B.C to X.Y.Z. 
I'd be happy to open a PR and change this in all existing files. 
The question to me is whether the changes header files are auto generated. If yes I would also update the script to add these prefixes.

**Comment by jpthiele** [comment]
> Update 1: The `multiple use of section label` errors are relatively easy to fix by doing a search for `<a name="` and replace it by `<a name="XY` for step-XY or with`<a name="ABC-XYZ"` for changes from version A.B.C to X.Y.Z. I'd be happy to open a PR and change this in all existing files. The question to me is whether the changes header files are auto generated. If yes I would also update the script to add these prefixes.

Also happy to add `-` or `_` after the prefixes to increase readability. Just let me know what you think because I would prefer not to edit all these files multiple times.

**Comment by jpthiele** [comment]
Update 2:
Some of the `@copydoc` etc. warnings can be fixed by removing `dealii::`. 
The big problem which seems to greatly confuse Doxygen is the large number of Triangulation classes. 
I get a lot of those errors in the `tria_base.h` files. Adding more specialized names like `parallel::Triangulation` shifted the error from recursive declaration to not found.

**Comment by jpthiele** [comment]
Due to #16051 the anchors warning should have to be suppressed anymore.

**Comment by jpthiele** [comment]
As fixes to the warnings are now split between multiple self-contained pull requests I will rebase and check if all warnings except for the already suppressed graph size warnings are removed then.

**Comment by bangerth** [comment]
@jpthiele What's the status here?

**Comment by jpthiele** [comment]
The question is still the chicken and egg problem with #16069 as it needs a newer doxygen version to 
fix all copydoc reference warnings.
I'd propose to suppress those warnings here for now so it can be merged and then remove the suppression 
in the other PR after merging the master branch with this PR in it.

If that is okay I'll add the suppressions at the latest on Thursday.

**Review by bangerth — COMMENTED** [review]
This is ok with me, but I don't know the CI infrastructure well. Can someone else take a look at this?

**Review by masterleinad — APPROVED** [review]

**Pull request merged**
