### PR TITLE
add more quick tests

### PR DESCRIPTION
**Pull request by davydden**
- [x] trilinos
- [x] arpack
- [x] metis+mpi
- [x] lapack
- [x] gsl
- [x] umfpack

in reference to https://github.com/dealii/dealii/issues/3230

### CODE REVIEW

**Comment by davydden** [comment]
this PR is ready for review.

**Comment by tjhei** [comment]
Some of your tests are not checking any of the computational result. I think there should be at least some checking inside (but it needs to be robust!).

If a test fails, does the current setup print the output/deallog if it does? Probably not too important, because you can find the output if necessary.

**Comment by davydden** [comment]
correct, none of them print anything, but it's how all `quick test` work at the moment. If they fail, you can check in `tests/quicktests.log` and `tests/output` for logs. 

If you want, i can switch at least some of the current tests and those in this PR to test something.

**Comment by davydden** [comment]
@tjhei :  I added asserts to some quick tests.

**Comment by tjhei** [comment]
:+1:

**Pull request merged**
