### PR TITLE
Add new relative path for new directory structure

### PR DESCRIPTION
**Pull request by guidokanschat**
With the new directory structure ``cmake .`` does not work anymore in the tutorial directories.

This patch adds the path ``../../../../../`` to the hints in ``CMakeLists.txt`` in order to find it again for the default installation.

### CODE REVIEW

**Comment by bangerth** [comment]
This patch of course raises the question whether we're well served by the new directory structure. It's almost impossible to find the tutorials now...

**Comment by guidokanschat** [comment]
It's indeed worth discussing whether we should only do this structure for packaging. Five directories down is quite far

**Comment by tamiko** [comment]
I agree. The current layout is a bit of an unintended side-effect...

**Comment by tjhei** [comment]
Should we revert this patch now?

**Comment by tamiko** [comment]
> Should we revert this patch now?

Yes.

I just remembered that the hint "../../../../../" might lead to a
segfault ina at least cmake 2.8.8 (maybe also later) when used in a
project located not that deep down the file hierarchy...

I'm sorry for the confusion that the removal of the "compat_feature"
component created.

**Pull request merged**
