### PR TITLE
Update test outputs

### LINKED ISSUE #6458: Fix fallout from 6446
As discussed elsewhere, this patch breaks (sorry) approximately 50 tests that
rely on the geometry generated by `hyper_shell(tria, Point<3>, r, R, 96)` since
the 96 cell grid is now computed in a different way. The following tests
currently fail on my workstation (there may be a few that are unrelated, such as
the slepc and PETSc failures; in particular there is a bug with 32 bit hypre):

- [x] mpi/no_flux_constraints.mpirun=9.debug (Failed)
- [x] mpi/no_flux_constraints.mpirun=9.release (Failed)
- [x] mpi/no_flux_constraints_02.mpirun=1.debug (Failed)
- [x] mpi/no_flux_constraints_02.mpirun=1.release (Failed)
- [x] mpi/no_flux_constraints_02.mpirun=9.debug (Failed)
- [x] mpi/no_flux_constraints_02.mpirun=9.release (Failed)
- [x] mpi/normal_flux_constraints.mpirun=9.debug (Failed)
- [x] mpi/normal_flux_constraints.mpirun=9.release (Failed)
- [x] mpi/p4est_3d_refine_04.mpirun=1.debug (Failed)
- [x] mpi/p4est_3d_refine_04.mpirun=1.release (Failed)
- [x] mpi/p4est_3d_refine_04.mpirun=10.debug (Failed)
- [x] mpi/p4est_3d_refine_04.mpirun=10.release (Failed)
- [x] mpi/p4est_3d_refine_04.mpirun=24.debug (Failed)
- [x] mpi/p4est_3d_refine_04.mpirun=24.release (Failed)
- [x] mpi/p4est_3d_refine_04.mpirun=4.debug (Failed)
- [x] mpi/p4est_3d_refine_04.mpirun=4.release (Failed)

### PR DESCRIPTION
**Pull request by tamiko**
In reference to #6458
Fixes #6458

### CODE REVIEW

**Comment by tamiko** [comment]
@drwells Do these changes actually make sense? I am worried that we broke more than just the mesh.

**Comment by drwells** [comment]
The changes in the first one seem reasonable: the mesh is different so we get a different number of cells near the north pole.

I have no idea what is going on with `reinit_preconditioner_01.cc`: that test doesn't even use a Triangulation.

**Comment by bangerth** [comment]
Can you take that change out then? I see the other tests fail here as well, but not the `reinit_preconditioner_01` one.

**Comment by tamiko** [comment]
> I have no idea what is going on with `reinit_preconditioner_01.cc`: that test doesn't even use a Triangulation. 

My guess: One of the libraries (maybe PETSc) tinkers with the number of
MPI processes.

Best,
Matthias

**Comment by tamiko** [comment]
@bangerth I have already done that two hours ago :-)

**Comment by tamiko** [comment]
Let me add the other test outputs here.

**Comment by tamiko** [comment]
@drwells @bangerth This should be all test output that has to be adapted. Fairly minimal.

**Comment by drwells** [comment]
/run-tests (not so useful but why not)

**Comment by drwells** [comment]
@tjhei It looks like tjhei-alpha is out.

**Comment by tamiko** [comment]
I will merge this for consistency - because this is already on the release branch ;-)

**Pull request merged**
