### PR TITLE
Use correct function names in test

### PR DESCRIPTION
**Pull request by jh66637**
I didn't think about changing the function names in the test. 

Small question: I always thought, that also new tests are run by the pipeline. Maybe this was naive?

### CODE REVIEW

**Comment by kronbichler** [comment]
Not all tests are run by the pipeline because executing almost 8k tests (in debug mode) on every PR and every push is a bit excessive. There is a selection run on the various case, the most comprehensive is "Jenkins serial" (that however excludes the MPI-based tests as the one here). So it was bad luck here. I did not notice it in the second review, either. I recommend to run a selection of tests (and the tests being added) locally as well.

**Comment by jh66637** [comment]
I see. Thank you for the clarification.

Let me run the tests locally before merging. This might take some time since compiling deal.II on my laptop takes forever and I do not have access to a better machine atm.

**Review by peterrum — APPROVED** [review]

**Comment by peterrum** [comment]
> Let me run the tests locally before merging. 

@jh66637  What are the results?

**Comment by jh66637** [comment]
Still compiling :/ I will ping you when I'm ready

**Comment by jh66637** [comment]
@peterrum The test passed on my machine :)

**Comment by bangerth** [comment]
On 2/2/24 02:25, Martin Kronbichler wrote:
> Not all tests are run by the pipeline because executing almost 8k tests 
> (in debug mode) on every PR and every push is a bit excessive.

To be clear not "excessive" in the sense of "unnecessary". Just 
excessive in the sense of "we do not have the resources".

**Comment by tamiko** [comment]
@bangerth @kronbichler I think it is time to bite the bullet and run one full configuration on a pull request. I will try to hook this up over the next days and we will chain it to our `/rebuild` and "ready to test" macros.

**Comment by bangerth** [comment]
I will offer again that if we can find setups to run tests that do not require docker, I can offer a number of machines with quite a large number of cores to run about as many checks as we can make use of.

**Comment by masterleinad** [comment]
> I will offer again that if we can find setups to run tests that do not require docker, I can offer a number of machines with quite a large number of cores to run about as many checks as we can make use of.

Would you be able to meet the requirements for self-hosted GitHub runners, see https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#requirements-for-self-hosted-runner-machines?

**Comment by tamiko** [comment]
@bangerth We would need to be able to control the userland under which the tests run. If docker is not an option, would it be possible to use singularity? https://docs.sylabs.io/guides/latest/user-guide/

**Comment by bangerth** [comment]
I'll have to talk to my sysadmin about it. We tried with docker, but between @tjhei and I we did not get things to run.

**Comment by bangerth** [comment]
I can meet the requirements @masterleinad lays out.

**Comment by tamiko** [comment]
@bangerth I can provide the singularity containers - either generated, or the definition files to generate them. In short, they download a specific Debian or Ubuntu version and install all dependencies that we need. After that the runner simply executes the test inside the singularity container. That's how the `-tng` variants of the regression tester are set up.

**Pull request merged**
