### PR TITLE
Remove deprecated Tensor functions.

### PR DESCRIPTION
**Pull request by drwells**
These were deprecated back in 2015.

### CODE REVIEW

**Comment by drwells** [comment]
Some tests failed:
```
	740 - fe/fe_project_3d.debug (Failed)

	1093 - base/full_tensor_06.debug (Failed)

	2903 - tensors/tensor_09.debug (Failed)

	3607 - adolc/helper_scalar_coupled_2_components_03_1.debug (Failed)

	3611 - adolc/helper_scalar_coupled_2_components_03_2.debug (Failed)

	3630 - adolc/tensor_ops_01.debug (Failed)

	3647 - adolc/tensor_functions_01_1.debug (Failed)

	3655 - adolc/tensor_functions_01_2.debug (Failed)
```
I will run the full test suite later to try and catch anything else.

**Comment by masterleinad** [comment]
I don't see more than that with my current configuration.

**Comment by bangerth** [comment]
The current CI status still shows these tests failing:
```
	740 - fe/fe_project_3d.debug (Failed)
	1093 - base/full_tensor_06.debug (Failed)
	2903 - tensors/tensor_09.debug (Failed)
	3607 - adolc/helper_scalar_coupled_2_components_03_1.debug (Failed)
	3611 - adolc/helper_scalar_coupled_2_components_03_2.debug (Failed)
	3630 - adolc/tensor_ops_01.debug (Failed)
	3647 - adolc/tensor_functions_01_1.debug (Failed)
	3655 - adolc/tensor_functions_01_2.debug (Failed)
```
@drwells -- do you know what's going on with these?

**Comment by drwells** [comment]
All of these tests use deprecated functions. It’s easy to fix; I will finish the patch today or tomorrow.

**Comment by drwells** [comment]
today or tomorrow turned into 'later this week'. My apologies; I have been traveling a lot.

**Comment by drwells** [comment]
This isn't a high priority item so I still haven't gotten to it (sorry). I think someone did something odd with the branch history.

**Comment by masterleinad** [comment]
I'll fix it.

**Comment by drwells** [comment]
I confirmed that @masterleinad's patch removes the remaining uses of tensor functions that were removed in this PR.

**Pull request merged**
