### PR TITLE
Rename the opencascade Manifold classes.

### PR DESCRIPTION
**Pull request by drwells**
A quick follow-up to #6582: we are now completely rid of `Boundary`, in both name and inheritance!

Manifolds have names ending in 'Manifold': now that Boundary is gone these names do not make sense.

For backwards compatibility, the old classes now simply inherit from the correctly-named Manifold versions. This requires marking some things that were private now as protected.

### CODE REVIEW

**Comment by jppelteret** [comment]
What about using a template alias for the old class and deprecating it (or would what's discussed [here](https://stackoverflow.com/q/19791904) be an issue for us)? That would save the switch of data from private to protected.

**Comment by drwells** [comment]
I originally went with inheritance because I did not think (and did not check, which was silly) that one could deprecate `using` declarations.

Disregarding my poor research, I am not sure if we want to be maximally pedantic/compatible, but we do sometimes check typeids of Manifold classes: inheritance allows us to get correct clones (i.e., if someone clones a `ProjectionBoundary` they may be surprised to get a `ProjectionManifold` back). We would lose this if we just used aliases.

**Comment by jppelteret** [comment]
> if someone clones a ProjectionBoundary they may be surprised to get a ProjectionManifold back

OK, with this in mind your implementation makes sense. Thanks for the explanation! 

(BTW I too did not know that one could deprecate using a template alias. The idea mystically popped into my head when I read the original PR comment :-)

**Comment by jppelteret** [comment]
Do any of the tests need updating? Or is this planned for another PR? I scanned through the changes and it looks good to me.

**Comment by drwells** [comment]
These classes already have a lot of tests, but all the tests are now for the older name: in principle I may have broken one of the clone functions for the newer name. I'll redo one of them to use the new names.

**Comment by bangerth** [comment]
On 05/13/2018 04:53 AM, Jean-Paul Pelteret wrote:
> (BTW I too did not know that one could deprecate using a template alias. The 
> idea mystically popped into my head when I read the original PR comment :-)

A typedef or template alias is still a declaration that introduces a name. 
Declarations are exactly the things that one should be able to annotate with 
deprecation attributes.

**Comment by luca-heltai** [comment]
How about we also move the old file name out of the way? I think should now be called `opencascade/manifold_lib.h`

**Comment by drwells** [comment]
@luca-heltai all of the classes (except, of course, the deprecated ones with names ending in `Boundary`) in this patch are declared in `opencascade/manifold_lib.h` already. I am not sure I understand your comment. What else should we move?

**Comment by luca-heltai** [comment]
@drwells , just ignore my last comments. I have not slept enough in the last days. I was confused by the fact that the boundary_lib.h file is still there (as it should be), and I underestimated (again) how precise and always to the point your PR are. :)

**Comment by drwells** [comment]
you flatter me @luca-heltai :)

**Pull request merged**
