### PR TITLE
Explicitly wait for tasks to be done.

### PR DESCRIPTION
**Pull request by bangerth**
While trying to figure out what's going on with the other thread work I'm doing, I ran into an issue that I didn't understand and that I think only works by accident. In any case, this patch seems to make it work.

/rebuild

### CODE REVIEW

**Comment by bangerth** [comment]
Related to #13018.

**Comment by bangerth** [comment]
Oh, good, this actually seems to work.

**Review by drwells — APPROVED** [review]
It makes sense that we should `wait()` here (e.g., for IO). Could someone else who works with threading double-check this?

**Comment by bangerth** [comment]
We did, implicitly, already: `std::future` in the implementations we use appears to wait. So there is no actual change in behavior, and we already had tests that check that we wait. It's just that I wanted that to be explicit.

**Comment by bangerth** [comment]
To maybe be a bit more explicit: The `TaskData` class has a member variable of type `std::future`. In the implementations we have the destructor of `std::future` blocks until the result is available, so the compiler-generated destructor of `TaskData` blocks as it executes the destructor of the class's member variable.

The patch in question here simply makes this explicit by writing a user-defined destructor that explicitly calls `wait()`, rather than leaving this to the destructor of the member variable.

**Comment by drwells** [comment]
Ah - as long as we are just formalizing current behavior this should be fine.

**Pull request merged**
