### PR TITLE
Fix test output.

### PR DESCRIPTION
**Pull request by bangerth**
This fixes something that must have been broken by #2710. There is a separate
output file for 64-bit runs, but I don't have such a branch running right now,
so it needs to be left for another pull-request.

### CODE REVIEW

**Comment by drwells** [comment]
Any idea why the sparsity pattern memory usage changed?

While not a substantial problem, this does point out that the calculation of memory consumption by `GnuplotFlags` is actually wrong since it does not take into account the elements of `space_dimension_labels`. I'll fix that in a follow up PR.

**Comment by bangerth** [comment]
Oh, good spot. I actually only saw the output differences for DataOut and assumed that it is the changes to GnuplotFlags. I didn't investigate either whether it actually was those changes (made in #2710), or anything else. I also completely missed that SparsityPattern apparently also changed. I don't know where this was from. Maybe #2690?

**Comment by kronbichler** [comment]
@bangerth I think this was #2619 but the 'bug' got lost among the other test failures.

**Comment by bangerth** [comment]
Maybe. The only change to what we store in memory that was part of #2619 was to store `max_vec_length` in a different data type. The other changes were only about return types of functions. It's interesting that that one change costs us 8 bytes...

**Comment by kronbichler** [comment]
>  It's interesting that that one change costs us 8 bytes

We increase the integer size from 4 to 8 bytes. That's four bytes. Since there are 3x4=12 bytes before that variable, the compiler needs to insert another 4 bytes of padding...

**Pull request merged**
