### PR TITLE
Fix number type in make_vectorized_array inside get_symmetric_gradient

### LINKED ISSUE #5218: Use an explicit NumberType template parameter value in FEEvaluation::get_symmetric_gradient
As pointed out in [Google Groups](https://groups.google.com/forum/#!topic/dealii/XMiScYGR-tA):
> line 4545 of /include/deal.II/matrix_free/fe_evaluation.h:
  VectorizedArray<Number> half = make_vectorized_array (0.5);

> 0.5 is interpreted as double and it leads to using `make_vectorized_array<double>`. That is OK if Number=double but for any other type (eg. float) it results is compilation error. It should be replaced by:
  VectorizedArray<Number> half = make_vectorized_array<Number> (0.5);

### PR DESCRIPTION
**Pull request by mwichro**
Fixes #5218. As discussed: https://groups.google.com/forum/#!topic/dealii/XMiScYGR-tA

edit (masterleinad): Reference to the respective issue.

### CODE REVIEW

**Comment by jppelteret** [comment]
Awesome. Thanks a lot for the fix @mwichro!

**Comment by jppelteret** [comment]
@mwichro Welcome to the group of deal.II contributors! Thanks again for your patch, and we hope that it won't be your last :-)

**Comment by masterleinad** [comment]
@jppelteret Amazing how you merged this a second after I modified the first comment to mention the issue! German internet infrastructure is really working well :wink:

**Comment by jppelteret** [comment]
We're in sync and on form today :-)

**Comment by jppelteret** [comment]
Aww, we didn't mean to leave anyone out. Come join the PR party 🎉

**Comment by mwichro** [comment]
Nice that everyone is here, so I can announce  that few days ago I've
finished my Stokes matrix-free solver! Now I'm testing it and working on
paper.

mwichro@Preludio:~/deal-ii-projects/StokeMatrixFree$ time mpirun -np 8
./StokesMatrixFree
Testing FESystem<2>[FE_Q<2>(2)^2] + FE_Q<2>(1)
Number of degrees of freedom: 738563
Vectorization for float: 8
Vectorization for double: 4
Stokes system coverged in 7 resudual: 1.64262e-06
Time solve (7 iterations)  (CPU/wall) 7.872s/9.18103s




Michał Wichrowski

2017-10-17 15:13 GMT+02:00 Jean-Paul Pelteret <notifications@github.com>:

**Comment by bangerth** [comment]
Oh, these are fantastic solve times for such a large problem! Would you be interested in eventually making this into a code gallery program? I think a lot of people would be interested in something like this, and that includes me! See http://dealii.org/code-gallery.html .

**Pull request merged**
