### PR TITLE
Fix DoFInfo::assign_ghosts for hp in parallel

### PR DESCRIPTION
**Pull request by peterrum**

### CODE REVIEW

**Comment by peterrum** [comment]
FYI @Rombur

**Review by Rombur — COMMENTED** [review]
Nice. Do you have a test for this? I also think this deserves an entry in the changelog.

**Review by drwells — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]

**Comment by peterrum** [comment]
@Rombur I have added a test.

**Review by kronbichler — APPROVED** [review]

**Review by Rombur — APPROVED** [review]
Thanks!

**Pull request merged**
