### PR TITLE
Fix tria::has_hanging_nodes for anisotropically refined meshes

### PR DESCRIPTION
**Pull request by luca-heltai**
Anisotropic refined meshes do not give the correct answer for calls to `has_hanging_nodes()`.

Working on a fix.

### CODE REVIEW

**Comment by peterrum** [comment]
References https://github.com/dealii/dealii/issues/13623.

**Comment by luca-heltai** [comment]
There might be a faster way, but this is only used in the anisotropic case, in serial, so for the moment, until it becomes critical in some applications, we could live with this slow fix.

**Comment by drwells** [comment]
Actually, on second thought - do we permit anisotropic refinement with `p::s::T`? If so we will need to do a reduction at the end.

**Comment by luca-heltai** [comment]
> ~Actually, on second thought - do we permit anisotropic refinement with `p::s::T`?

If it is shared, all processors will return the same value anyway.

> edit: perhaps we can cache this value in `NumberCache`?

Yes. Maybe in a followup PR?

**Review by masterleinad — APPROVED** [review]

**Pull request merged**
