### PR TITLE
Only instantiate TpetraWrappers::Vector for types that have explicit instantiations in Tpetra

### LINKED ISSUE #14815: Docker image has issues linking with Trilinos
It seems the latest docker image crashes when linking to Trilinos regarding functions that concern block vectors.
You can find the full error log here:
https://github.com/lethe-cfd/lethe/actions/runs/4232353570/jobs/7351986000

Here's an excerpt:

> `usr/local/lib/libdeal_II.so.9.5.0-pre: error: undefined reference to 'Tpetra::Classes::DistObject<std::complex<float>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::doExport(Tpetra::SrcDistObject const&, Tpetra::Classes::Export<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, Tpetra::CombineMode)'
> /usr/local/lib/libdeal_II.so.9.5.0-pre: error: undefined reference to 'Tpetra::Classes::DistObject<float, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::doExport(Tpetra::SrcDistObject const&, Tpetra::Classes::Export<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, Tpetra::CombineMode)'
> /usr/local/lib/libdeal_II.so.9.5.0-pre: error: undefined reference to 'Tpetra::Classes::DistObject<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::doImport(Tpetra::SrcDistObject const&, Tpetra::Classes::Import<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, Tpetra::CombineMode)'
> /usr/local/lib/libdeal_II.so.9.5.0-pre: error: undefined reference to 'Tpetra::Classes::MultiVector<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::operator=(Tpetra::Classes::MultiVector<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&)'
> /usr/local/lib/libdeal_II.so.9.5.0-pre: error: undefined reference to 'Tpetra::Classes::Vector<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Vector(Tpetra::Classes::Vector<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&)'`

And so on and so forth.
I have tested the latest master version of deal.II on my machine and I don't have this issue. Maybe it means that the Trilinos version on the Docker image is too old now?

### PR DESCRIPTION
**Pull request by masterleinad**
FIxes #14815.

### CODE REVIEW

**Comment by tjhei** [comment]
> Yes, fixing the docker image is always a little poking in the dark.

Just push your proposed changes to dealii/dealii with a branch name that starts with "docker", see https://github.com/dealii/dealii/blob/3b785178375a8ea233fada96cf987aed6d53583e/.github/workflows/docker.yml#L6

**Comment by blaisb** [comment]
> Also fixing the failures in https://github.com/dealii/dealii/actions/runs/4235947222/jobs/7360188695 (hopefully).
> 
> > @masterleinad Thanks! We will probably need to merge, since the docker image is only built once the PR is merged.
> 
> Yes, fixing the docker image is always a little poking in the dark. slightly_frowning_face

It is indeed...

**Comment by masterleinad** [comment]
> Just push your proposed changes to dealii/dealii with a branch name that starts with "docker", see

See https://github.com/dealii/dealii/tree/docker_restrict_tpetra_vector_instantiations

**Comment by masterleinad** [comment]
The tests are a bit tricky since the output will depend on the available number types. We only check for `double` in `TPETRA_IS_FUNCTIONAL` so I would just drop the tests for other number types for now.

**Review by peterrum — COMMENTED** [review]
Let's give this a try!

**Review by peterrum — APPROVED** [review]

**Pull request merged**
