### PR TITLE
Make particle iterators const references in range-based for loops.

### PR DESCRIPTION
**Pull request by bangerth**
I didn't convert them all so we can continue to test both ways to write a loop.

### CODE REVIEW

**Comment by bangerth** [comment]
@gassmoeller -- FYI.

**Comment by masterleinad** [comment]
> I didn't convert them all so we can continue to test both ways to write a loop.

Can you clarify this comment? Do you actually want to measure the difference in terms of performance between the two loop variants?

**Comment by bangerth** [comment]
I meant to say that there are other tests that I didn't touch. I have no doubt that the difference is really immeasurable.

**Pull request merged**
