### PR TITLE
Merge parallel::GridTools into GridTools

### LINKED ISSUE #5427: merge GridTools and parallel::GridTools
#5423 fixed the unity build: my compiler got confused between `GridTools` and `parallel::GridTools`. I suspect that adding this extra namespace will cause similar headaches in the future; in addition, since we already have some parallel stuff in plain old `GridTools`, I suggest that we just put everything in `GridTools`.

AFAIK this namespace did not exist in 8.5 so we can remove it now and not break too much stuff. Thoughts?

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #5427.

### CODE REVIEW

**Comment by drwells** [comment]
Could you add the following to `distributed/grid_tools.h` instead of removing it completely?

```cpp
#ifndef dealii_distributed_grid_tools_h
#define dealii_distributed_grid_tools_h
#warning "This file is deprecated and will be removed before the 9.0 release. Use <deal.II/grid/grid_tools.h> instead."

#endif
```

I'd rather not surprise anyone with compilation errors.

**Comment by bangerth** [comment]
Are there any recent changelog entries that announce new functions in the now removed namespace that ought to be updated? Since the namespace was only introduced after the new release, the changelog you add is probably more confusing than helpful, since nobody who reads the changelog entry even knew anything about the namespace that's being removed :-)

**Comment by masterleinad** [comment]
Fine, I updated the affected changelog entry instead of creating a new one.

**Pull request merged**
