### PR TITLE
Disable two ADOL-C tests in release configuration

### PR DESCRIPTION
**Pull request by tamiko**
It turns out that some optimizing compilers (gcc-7 onwards) are very
happy in happily optimizing away in case of undefined behavior (that we
are apparently encountering). Let's just disable these tests in release
configuration.

### CODE REVIEW

**Comment by tamiko** [comment]
@jppelteret *ping*

**Comment by tamiko** [comment]
Candidate for #8080

**Comment by tjhei** [comment]
Looks good (and is already in 9.1)... /rebuild

**Comment by jppelteret** [comment]
Thanks @tamiko !

**Pull request merged**
