### PR TITLE
Added diagnostic functions for `AffineConstraints`.

### PR DESCRIPTION
**Pull request by marcfehling**
Added functions `n_identities` and `n_inhomogeneities` for the `AffineConstraints` class.

I'm still trying to figure out why the `identity_constraints` test claims that there are 3 identity constraints in 3D. I count only 1 in the central line. Do you have an idea?

### CODE REVIEW

**Comment by marcfehling** [comment]
We do not unify dofs on lines in 3D, so dof duplicates should be treated by constraints:
https://github.com/dealii/dealii/blob/e413cbf8ac77606cf4a04e1e2fa75232c08533b4/source/dofs/dof_handler_policy.cc#L627-L637

---

This seems to be the case for the new test `hp/identity_constraints_01.cc`. In this test, there is one Q2 element facing one Q4 element, and the central dofs on each line on the interface are treated by constraints:
https://github.com/dealii/dealii/blob/c3872785c762666419e08dbdefcdf55418e5e182/tests/hp/identity_constraints_01.output#L10

---

However, in the more complex test `hp/identity_constraints_02.cc`, there is one constraint less reported:
https://github.com/dealii/dealii/blob/c3872785c762666419e08dbdefcdf55418e5e182/tests/hp/identity_constraints_02.output#L7

Here, there is one Q1, Q2, Q3, and Q4 element aligned on a 2x2 grid. It appears that on the central line on which 4 different elements are assigned, the identity constraint will not be set/recognized by `DoFTools::make_hanging_node_constraints()`.

This appears to be a bug. I have the suspicion that the `FiniteElementDomination` logic is responsible for this. I'll add another test...

**Comment by marcfehling** [comment]
I think my guess was correct. We use the most dominating element to identify the constraints. In the above scenario, the Q1 element is the most dominating one. Since it has no dofs on lines, we can not identify the dof duplicates on the central line and not formulate constraints.

I enhanced test `hp/identity_constraints_02.cc` to also use elements Q2, Q3, Q4, Q5. Then the Q2 element is the most dominating one, and the missing constraint appears again.
https://github.com/dealii/dealii/blob/b32461a3de59673d7a581a414d75df49081ad504/tests/hp/identity_constraints_02.output#L15

We check for domination in `DoFTools::make_hanging_node_constraints()` here:
https://github.com/dealii/dealii/blob/e413cbf8ac77606cf4a04e1e2fa75232c08533b4/source/dofs/dof_tools_constraints.cc#L1125-L1162

We should think about a adjusting the algorithm to identify constraints. @bangerth -- That is exactly the scenario we talked about today!

I'll open an issue when this PR gets merged.

**Review by drwells — APPROVED** [review]

**Comment by drwells** [comment]
I don't know the constraint code well enough to comment on some of these technical issues but the two new functions are straightforward and match the existing naming conventions, so lets merge.

**Pull request merged**
