### PR TITLE
Update test results.

### PR DESCRIPTION
**Pull request by bangerth**
These are the test results for METIS 5.1.0 via PETSc 3.6, on linux. 32-bit.

This supersedes #1412. For now, I am simply overwriting the existing output files. Did we decide how we want to deal with different versions and platforms? I can choose different filenames if people want -- suggestions welcome.

### CODE REVIEW

**Comment by bangerth** [comment]
64-bit test results also updated.

**Comment by tamiko** [comment]
> Did we decide how we want to deal with different versions and platforms? 

Not yet. I open an issue, we discuss there.

**Comment by tamiko** [comment]
@bangerth Just to get this straight: This pull request was intended to break the metis results on every machine except your personal desktop? [1] :-D

[1] http://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=11767

**Comment by bangerth** [comment]
I still need to switch the tester itself. Good point, will do next.

**Comment by bangerth** [comment]
(For completeness, the patch was actually developed on 'tester', but I didn't switch it to PETSc 3.6.1 so far. It should use that version with the next test.)

**Pull request merged**
