### PR TITLE
Disable intrinsics includes if DEAL_II_VECTORIZATION_LEVEL=0

### LINKED ISSUE #8075: Cannot compile with CUDA 10.1
The code does not code compile currently with CUDA 10.1 and possibly 9.2. We should try to fix this before the release and add one more configuration to the tester.

### PR DESCRIPTION
**Pull request by kronbichler**
This disables all includes to intrinsics headers in case `DEAL_II_VECTORIZATION_LEVEL=0` as suggested by https://github.com/dealii/dealii/pull/8125#issuecomment-491659211

This supersedes #8125 
This fixes #8075.

### CODE REVIEW

**Comment by Rombur** [comment]
Right now on `x86` we do not disable vectorization with CUDA but only in file that are compiled with nvcc.

**Comment by kronbichler** [comment]
So I guess the compiler complains that `x86intrin.h` is not available? So I guess it would work if we replaced it by `immintrin.h`? We can restructure the tests in cmake to make this happen.

**Comment by masterleinad** [comment]
The output is
```
/export/home/darndt/cuda-10.1/bin/nvcc  -DBOOST_NO_AUTO_PTR -I/export/home/darndt/dealii-cuda-10/build/source/lac -I/export/home/darndt/dealii-cuda-10/build/include -I/export/home/darndt/dealii-cuda-10/include -I/export/home/darndt/dealii-cuda-10/bundled/tbb-2018_U2/include -I/export/home/darndt/dealii-cuda-10/bundled/boost-1.62.0/include -I/export/home/darndt/dealii-cuda-10/bundled/umfpack/UMFPACK/Include -I/export/home/darndt/dealii-cuda-10/bundled/umfpack/AMD/Include -I/export/home/darndt/dealii-cuda-10/bundled/muparser_v2_2_4/include -isystem=/export/home/darndt/cuda-10.1/include  -Xcompiler "-fPIC -Wall -Wextra -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wsuggest-override -Wswitch -Wsynth -Wwrite-strings -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -fopenmp-simd -std=c++14 -Wno-parentheses -Wno-unused-local-typedefs -O2 -funroll-loops -funroll-all-loops -fstrict-aliasing -Wno-unused-local-typedefs" -arch=sm_61 -std=c++14 -x cu -c /export/home/darndt/dealii-cuda-10/source/lac/la_parallel_vector.cu -o CMakeFiles/obj_lac_release.dir/la_parallel_vector.cu.o
/export/home/darndt/dealii-cuda-10/bundled/boost-1.62.0/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(75): warning: variable "tmp" was set but never used

/export/home/darndt/dealii-cuda-10/bundled/boost-1.62.0/include/boost/mpl/print.hpp(64): warning: integer conversion resulted in a change of sign

/export/home/darndt/dealii-cuda-10/include/deal.II/base/thread_management.h(109): warning: attribute does not apply to any entity

/export/home/darndt/dealii-cuda-10/include/deal.II/base/thread_management.h(281): warning: attribute does not apply to any entity

/export/home/darndt/dealii-cuda-10/bundled/boost-1.62.0/include/boost/mpl/print.hpp(64): warning: integer conversion resulted in a change of sign

/export/home/darndt/dealii-cuda-10/include/deal.II/base/thread_management.h(109): warning: attribute does not apply to any entity

/export/home/darndt/dealii-cuda-10/include/deal.II/base/thread_management.h(281): warning: attribute does not apply to any entity

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(1761): error: identifier "__builtin_ia32_sqrtsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(1770): error: identifier "__builtin_ia32_sqrtss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(2728): error: identifier "__builtin_ia32_scalefsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(2737): error: identifier "__builtin_ia32_scalefss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11265): error: identifier "__builtin_ia32_scalefsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11274): error: identifier "__builtin_ia32_scalefss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1163): error: identifier "__builtin_ia32_reducesd" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1171): error: identifier "__builtin_ia32_reducess" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1179): error: identifier "__builtin_ia32_rangesd128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1189): error: identifier "__builtin_ia32_rangess128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1198): error: identifier "__builtin_ia32_rangesd128_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512dqintrin.h(1207): error: identifier "__builtin_ia32_rangess128_round" is undefined
```

**Comment by kronbichler** [comment]
@masterleinad what is the value of `DEAL_II_VECTORIZATION_LEVEL` in this case? I guess 1 - then I know what the error is.

**Comment by kronbichler** [comment]
I think that we just pull in `emmintrin.h` and no AVX512 intrinsics. Whereas `x86intrin.h` pulls in everything and thus also something that I believe is a compiler issue: It tries to emit `__builtin_ia32_rangess128_round` and symbols like in case the header is included, which makes no sense. This will be cured if we include `x86intrin.h` in the test for SSE2 and AVX.

**Comment by Rombur** [comment]
`DEAL_II_VECTORIZATION_LEVEL` is set to 1 for gcc and 0 for nvcc

**Comment by masterleinad** [comment]
> `DEAL_II_VECTORIZATION_LEVEL` is set to 1 for gcc and 0 for nvcc

Same for me.

**Comment by kronbichler** [comment]
@masterleinad @Rombur I forced-pushed with the proper fix in the cmake checks. Would you please re-run `cmake` on your configuration. It should now report
```
-- Performing Test DEAL_II_HAVE_SSE2
-- Performing Test DEAL_II_HAVE_SSE2 - Failed
-- Performing Test DEAL_II_HAVE_AVX
-- Performing Test DEAL_II_HAVE_AVX - Failed
-- Performing Test DEAL_II_HAVE_AVX512
-- Performing Test DEAL_II_HAVE_AVX512 - Failed
-- Performing Test DEAL_II_HAVE_ALTIVEC
-- Performing Test DEAL_II_HAVE_ALTIVEC - Failed
-- Performing Test DEAL_II_HAVE_OPENMP_SIMD
-- Performing Test DEAL_II_HAVE_OPENMP_SIMD - Success
```
The question is then only whether we want to be conservative like we are with my proposed change, or if we want to get the SSE vectorization as by @Rombur's reverted code.

**Comment by masterleinad** [comment]
@Rombur's pull request fails for me as well if `DEAL_II_COMPILER_VECTORIZATION_LEVEL==3`. Maybe not too surprising looking at the error message.
It seems `CUDA 10.1`'s nvcc simply doesn't allow for `AVX512` intrinsics in any code path anymore. This means that we need to be specific in the headers (like in @Rombur's pull request) and disallow `AVX512` with `CUDA` (>10.0?) support. A more sledgehammer approach would be to disable vectorization with `CUDA` completely,

**Comment by kronbichler** [comment]
@masterleinad but doesn't my patch help against that because we detect it early during `cmake` configuration by disabling the offending includes?

**Comment by Rombur** [comment]
Doesn't work for me

**Comment by masterleinad** [comment]
>  This will be cured if we include `x86intrin.h` in the test for SSE2 and AVX.

The new commit doesn't work either. The problem is that the `CMake` tests are performed with the `CXX` compiler and not with the `CUDA` compiler. `g++` doesn't have any problems with these headers, but we run into problems as soon as `nvcc` is invoked even if its just for the host part of `CUDA` code (where `g++` is used again).
This is similar to #7328.

**Comment by kronbichler** [comment]
Oh yes, I recall now. But isn't `nvcc` routed to `DEAL_II_VECTORIZATION_LEVEL=0` in `include/deal.II/base/config.h` because it defines `__CUDA_ARCH__`? Or is it that this part again comes from the gcc compiler after it has done the other checks? So I tend to second the suggestion

> A more sledgehammer approach would be to disable vectorization with CUDA completely

because there are so many places where things go wrong, as @masterleinad's attempt shows (it would also go wrong if we had AVX/AVX2 enabled; I guess @Rombur did only have the basic SSE2 path where we don't pull in `immintrin.h`/`x86intrin.h`). So, in essence, we would set the `ifdef` in `config.h` to `DEAL_II_WITH_CUDA` rather than simply `__CUDA_ARCH__`, right? If the two of you agree, I will add that check to this patch. The other things I did were not wrong, but they are apparently not sufficient.

**Comment by kronbichler** [comment]
Now I added the commit that disables vectorization. @Rombur can you try again?

**Comment by masterleinad** [comment]
Hmm... I still get
```
/export/home/darndt/cuda-10.1/bin/nvcc  -DBOOST_NO_AUTO_PTR -DDEBUG -DTBB_DO_ASSERT=1 -DTBB_USE_DEBUG -I/export/home/darndt/dealii-cuda-10/build/source/lac -I/export/home/darndt/dealii-cuda-10/build/include -I/export/home/darndt/dealii-cuda-10/include -I/export/home/darndt/dealii-cuda-10/bundled/tbb-2018_U2/include -I/export/home/darndt/dealii-cuda-10/bundled/boost-1.62.0/include -I/export/home/darndt/dealii-cuda-10/bundled/umfpack/UMFPACK/Include -I/export/home/darndt/dealii-cuda-10/bundled/umfpack/AMD/Include -I/export/home/darndt/dealii-cuda-10/bundled/muparser_v2_2_4/include -isystem=/export/home/darndt/cuda-10.1/include  -Xcompiler "-fPIC -Wall -Wextra -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wsuggest-override -Wswitch -Wsynth -Wwrite-strings -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -fopenmp-simd -std=c++14 -march=native -Wno-parentheses -Wno-unused-local-typedefs -O0 -ggdb " -arch=sm_61 -std=c++14 -G -x cu -c /export/home/darndt/dealii-cuda-10/source/lac/vector_memory.cu -o CMakeFiles/obj_lac_debug.dir/vector_memory.cu.o
/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11265): error: identifier "__builtin_ia32_scalefsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11274): error: identifier "__builtin_ia32_scalefss_round" is undefined

/export/home/darndt/dealii-cuda-10/include/deal.II/base/thread_management.h(109): warning: attribute does not apply to any entity

/export/home/darndt/dealii-cuda-10/include/deal.II/base/thread_management.h(281): warning: attribute does not apply to any entity

/export/home/darndt/dealii-cuda-10/bundled/boost-1.62.0/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp(75): warning: variable "tmp" was set but never used

/export/home/darndt/dealii-cuda-10/bundled/boost-1.62.0/include/boost/mpl/print.hpp(64): warning: integer conversion resulted in a change of sign

2 errors detected in the compilation of "/tmp/tmpxft_00003cd6_00000000-6_vector_memory.cpp1.ii".
```

**Comment by kronbichler** [comment]
You have `DEAL_II_WITH_CUDA` defined? Then I don't see how we could ever include anything like `avx512fintrin.h`. Can you find out who's including that file?

**Comment by Rombur** [comment]
This now works for me.

**Comment by masterleinad** [comment]
I still try to find the offending include for building with `-march=native`.

**Comment by masterleinad** [comment]
One of the offending headers is `tbb/task.h`.

**Comment by kronbichler** [comment]
Thanks @masterleinad - but that means it is somewhat out of our hands. It really seems that Nvidia tries to piss of Intel (by not compiling with AVX headers), and Intel seems to try to piss off Nvidia (by including the AVX headers). So we really need to recommend against `-march=native` once we have `nvcc` to avoid that this header gets pulled in?

**Comment by masterleinad** [comment]
What about disallowing `DEAL_II_WITH_THREADS=ON` when enabling `CUDA` support? This is at least something we can control easily...

**Comment by kronbichler** [comment]
> What about disallowing DEAL_II_WITH_THREADS=ON when enabling CUDA support? This is at least something we can control easily...

The question is whether that would be too aggressive. I tried a bit to see where `tbb/task.h` picks up that header, but it is hidden in some machine-specific files (they are looking for TSX extensions, if I see it correctly, for which an include to `immintrin.h` is made).

**Comment by masterleinad** [comment]
I just want to save users from these hard to understand errors. On the other hand, it is probably OK to assume that people know what they are doing when explicitly requesting to compile for a given architecture. When disabling vectorization in `VectorizedArray` for `CUDA` anyway, there is probably also not so much gain in using these flags at all.
I think it is fine to put a warning in `doc/external-libs/cuda.html` then.

**Comment by kronbichler** [comment]
That would be perfect. Do you want to write that warning?

**Comment by kronbichler** [comment]
@Rombur @masterleinad can someone of you please approve so we can merge this?

**Pull request merged**
