### PR TITLE
SD map operations:  Add function to resolve explicit and cyclic dependencies

### PR DESCRIPTION
**Pull request by jppelteret**

### CODE REVIEW

**Comment by bangerth** [comment]
Ah, I reviewed this as part of #8033. I had just one comment, so let me approve this and you can merge yourself once you thought about my comment.

**Comment by jppelteret** [comment]
@bangerth Happy with 2d1628ae07fa2a62c5871f877dbd64bb9c118aa3?

**Comment by bangerth** [comment]
Yes, mostly. But there were other comments I had in #8033.

**Comment by jppelteret** [comment]
> Ah, I reviewed this as part of #8033. I had just one comment, so let me approve this and you can merge yourself once you thought about my comment

> Yes, mostly. But there were other comments I had in #8033.

?? I've had 3 hours sleep and apparently have a few PR's to fix. Perhaps you'd care to help me by pointing me to these other comments that you're referring to.

**Comment by jppelteret** [comment]
@bangerth I've given this another go in 86fa30e. I'm still not sure what other comments in #8033 you were referring to, but I hope that this somehow satisfies your concerns there.

**Comment by bangerth** [comment]
@jppelteret: You can see them here: https://github.com/dealii/dealii/pull/8033/commits/715f6719dfc1f2679b1407aa444f39b3ac8a63db

**Comment by bangerth** [comment]
Err, here https://github.com/dealii/dealii/pull/8033/commits/715f6719dfc1f2679b1407aa444f39b3ac8a63db

**Comment by bangerth** [comment]
Ah, darn. github translates the URL I paste to something that doesn't work. Try this: `https://github.com/dealii/dealii/pull/8033/commits/715f6719dfc1f2679b1407aa444f39b3ac8a63db`

**Comment by jppelteret** [comment]
> Ah, darn. github translates the URL I paste to something that doesn't work. Try this: https://github.com/dealii/dealii/pull/8033/commits/715f6719dfc1f2679b1407aa444f39b3ac8a63db

Thanks a lot! I've made the changes that you've suggested there.

**Comment by bangerth** [comment]
Well, the indentation tester is unhappy. Please fix and merge yourself once the testers are ok with it.

**Comment by jppelteret** [comment]
> Well, the indentation tester is unhappy. Please fix and merge yourself once the testers are ok with it.

Yip, will do! I also spotted that I forgot to make the change to `hash_old = std::move(hash_new);`, so I'm just rebuilding and testing that as well...

Thanks a lot for reviewing these PR's. Again, not the most interesting stuff ever written...

**Comment by jppelteret** [comment]
This one's also good to go.

**Pull request merged**
