### PR TITLE
Add step() and Tstep() methods to Chebyshev preconditioner for relaxation smoothers

### PR DESCRIPTION
**Pull request by kronbichler**
Relates to #2534.

@davydden This makes the interface of `PreconditionChebyshev` a bit more similar to Jacobi, SSOR etc. in the sense it allows its use in relaxation smoothers. Helps #3183 even though it does not solve it completely.

### CODE REVIEW

**Comment by kronbichler** [comment]
I also moved the old `parallel_multigrid_adaptive_02` file to `parallel_multigrid_adaptive_03`, basing it on `MGTransferMatrixFree` rather than `MGTransferPrebuilt` to drop the dependency on Trilinos for this test (git seems to have missed that move and lists a larger change than was actually made).

**Comment by davydden** [comment]
I guess `git` is confused because you are adding another unit test, which logically fits between  the current `parallel_multigrid_adaptive_01` and `parallel_multigrid_adaptive_02`?  

Maybe just don't rename `_02` to `_03` (but still introduce the change to `MGTransferMatrixFree`) and add the rest in subsequent numbers?

**Comment by kronbichler** [comment]
@davydden You are probably right, we could just switch `_02` and `_03`. It's a clearly changed thing (the base class) in between them.

**Comment by davydden** [comment]
It looks much better now, I will give it another look a bit later...

**Pull request merged**
