### PR TITLE
Clean up contrib/*, split parameter_gui into own repository

### PR DESCRIPTION
**Pull request by tamiko**
This pull request refactors parameter_gui into its own repository
  https://github.com/dealii/parameter_gui

and cleans up some old files

### CODE REVIEW

**Comment by bangerth** [comment]
What are your plans for the parameter GUI? I will admit that I don't know whether it's used by more than a handful of people and/or if it even still builds on recent Qt versions. But it would be a shame to not distribute it and force people to get it from a separate repository.

**Comment by tjhei** [comment]
> What are your plans for the parameter GUI?

It is in a separate repo now https://github.com/dealii/parameter_gui 

> I don't know whether it's used by more than a handful of people

I wouldn't be surprised if the number of users is <1.

> But it would be a shame to not distribute it and force people to get it from a separate repository.

I am in favor of this change to clean up the main repo.

**Comment by davydden** [comment]
> I am in favor of this change to clean up the main repo.

+1

**Comment by drwells** [comment]
I think that this is okay since we still support it.

I have compiled this successfully with recent versions of QT, but I have never used it personally.

**Comment by Rombur** [comment]
I think that @koecher said that he was using it. As long as it still exists, I think it's fine to move it.

**Comment by koecher** [comment]
@rombur I'll tested it once ago. Maybe some student of us still use the gui. So for me it would be okay to move or remove it.

**Comment by tamiko** [comment]
> What are your plans for the parameter GUI?

The plans are to maintain it in its own repository.

> But it would be a shame to not distribute it and force people to get it force people to get it from a separate repository.

We will still provide the parameter GUI in a separate git repository.

Further, I consider downloading/getting a separate repository on the same level of difficulty than configuring the build system to also build the (old) bundled component.

**Comment by bangerth** [comment]
But are we going to put it into the tar ball? I mean, surely there is a different level of complexity to cloning a separate github repository than to just add another `-D...=ON` flag to the configure line, no?

**Comment by tamiko** [comment]
> But are we going to put it into the tar ball?

No, I was not planning to include it into our deal.II release tarball.

**Comment by bangerth** [comment]
Hm. Then I don't really see the point.

What do others think?

**Comment by tamiko** [comment]
@bangerth Well, the idea is mainly to clean up the main repository and I would absolutely love to make this change. Especially, because this is the only external "contrib" package left.

In particular because
 - it is hardly used at all: I don't know of a single person using it (e.g., you yourself haven't compiled it for quite a while either).
 - enabling the component is a concious choice anyway (hardly anyone does it); so requiring to download another tarball/git repository is not that much of extra work
 - building the Parameter GUI requires a full Qt development toolchain
 - The program is *entirely orthogonal* to deal.II - it does not have any dependencies on it; it should have its own release cycle with its own tarball.
 - Further, the copyright line is different (copyrighted by Martin Steigemann and you).

**Comment by bangerth** [comment]
I think we both have valid points. I'm not going to fight your patch. If someone else wants to break the tie, go ahead and merge :-)

**Comment by tamiko** [comment]
I call for tie breakers :-D ;-)

**Comment by drwells** [comment]
I don't mind hitting the button. The fewer licenses we have in the library, the better.

**Pull request merged**
