### PR TITLE
Added clear_current_row() to TableHandler in case the current time step is rejected.

### PR DESCRIPTION
**Pull request by alrashedf**
With variable time stepping, the current time step is sometimes rejected. If TableHandler is used to track information about time steps, one needs to clear the information gathered so far and begin again. This function does that.

I'm open to changing the name of the function if another name is more suitable.

### CODE REVIEW

**Comment by tamiko** [comment]
*ping*

**Comment by alrashedf** [comment]
Will make changes soon. Have a defense to prepare for.

**Comment by bangerth** [comment]
Ah, no. I still wanted to finish this patch at one point or other. Are you going to open a different pull request, or are you just declaring defeat here? If the latter, let me know and I'll eventually finish this work.

**Comment by alrashedf** [comment]
I messed up the history of this branch so badly that github didn't map Timo's comments to the code lines correctly. I created this instead https://github.com/dealii/dealii/pull/664

**Pull request closed without merging**
