### PR TITLE
Fix get_shared_vector_data

### PR DESCRIPTION
**Pull request by peterrum**
The combined merge of #11075 and #11091 revealed a bug that prevents compiling master.

### CODE REVIEW

**Review by drwells — APPROVED** [review]

**Comment by drwells** [comment]
I'm surprised that both of those patches passed the CI but putting them together didn't. Did we do something incorrectly? I don't understand how this circumstance is even possible.

**Comment by peterrum** [comment]
```
    return &vec.shared_vector_data();
```
The first one: I did not expect that this function will be called (since the L:p:V does not have the SM capabilities yet).

```
  for (auto &p : matrix_free.get_dof_info().vector_exchanger_face_variants)
```
I am not sure about the second one. I normally run these test a couple of times an hour. Also, I guess this test is not run by CI!?

**Review by kronbichler — APPROVED** [review]

**Comment by bangerth** [comment]
All but two of the testers succeeded, the situation is already dire, so I'm taking the liberty of merging even though two tests are still pending.

**Comment by peterrum** [comment]
@bangerth  Thanks!

**Pull request merged**
