### PR TITLE
Fix Functions::Monomial::gradient

### PR DESCRIPTION
**Pull request by angelrca**
Fix to Functions::Monomial::gradient to allow the calculation of the gradient when both base and exponent are equal to zero for one or more components of the monomial.

### CODE REVIEW

**Comment by bangerth** [comment]
Great, thanks a lot!

**Comment by angelrca** [comment]
I have one last concern about the class. The line of the documentation of the class " Most of the time these exponents will of course be integers, but real exponents are of course equally valid" is not applicable to the case of a negative base integer with a real exponent. The result of the calculation of the monomial value in that case may be complex, but a nan will be returned instead because as far as I know std::pow can't be used to calculate complex roots. Does it make sense to use an assert to avoid that case?

**Comment by bangerth** [comment]
Yes, feel free to add such an assertion (at the time where the exponents are seen first by the class, not where they are used) and feel free to also clarify the documentation.

**Comment by angelrca** [comment]
I think the assertion needs to be placed in the evaluation because the function will only fail if the coordinates of the input Point are negative.

**Comment by bangerth** [comment]
Fair enough. Go with that then.

**Pull request merged**
