### PR TITLE
A workaround for MPI_Comm_free() before MPI_FINALIZE() error

### PR DESCRIPTION
**Pull request by jperryhouts**
A possible workaround for #2951

### CODE REVIEW

**Comment by drwells** [comment]
@jperryhouts If I understand your comments in #3019 correctly, this can be closed, right?

**Comment by jperryhouts** [comment]
@drwells No, sorry that comment was unclear. #3019 didn't work in its original form, so I needed to modify it. The comment referred to the first commit in that PR.

This and #3019 are both viable options as far as I can tell, but both may have unintended consequences which I'm hoping someone can spot.

**Comment by tamiko** [comment]
@tjhei @kronbichler *ping* What's your opinion on these changes?

**Comment by davydden** [comment]
@tamiko i think this solution is being more discussed https://github.com/dealii/dealii/issues/2951

**Comment by jperryhouts** [comment]
Superseded by #3041

**Pull request closed without merging**
