### PR TITLE
Simplify a few places using cell->as_dof_handler_iterator(..).

### PR DESCRIPTION
**Pull request by simonsticko**

### CODE REVIEW

**Review by peterrum — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]

**Comment by bangerth** [comment]
We fail with this error:
```
/home/dealii/libs/trilinos-release-13-2-0/lib/libstratimikosamesos2.so: error: undefined reference to 'Amesos2::KLU2<Tpetra::CrsMatrix<float, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >, Tpetra::MultiVector<float, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::KLU2(Teuchos::RCP<Tpetra::CrsMatrix<float, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const>, Teuchos::RCP<Tpetra::MultiVector<float, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >, Teuchos::RCP<Tpetra::MultiVector<float, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const>)'
/home/dealii/libs/trilinos-release-13-2-0/lib/libstratimikosamesos2.so: error: undefined reference to 'Amesos2::TachoSolver<Tpetra::CrsMatrix<float, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >, Tpetra::MultiVector<float, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >::TachoSolver(Teuchos::RCP<Tpetra::CrsMatrix<float, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const>, Teuchos::RCP<Tpetra::MultiVector<float, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >, Teuchos::RCP<Tpetra::MultiVector<float, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const>)'
/home/dealii/libs/trilinos-release-13-2-0/lib/libstratimikosbelos.so: error: undefined reference to 'Tpetra::MultiVector<float, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getVector(unsigned long) const'
/home/dealii/libs/trilinos-release-13-2-0/lib/libstratimikosbelos.so: error: undefined reference to 'Tpetra::MultiVector<float, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getLocalLength() const'
/home/dealii/libs/trilinos-release-13-2-0/lib/libstratimikosbelos.so: error: undefined reference to 'Tpetra::MultiVector<float, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getGlobalLength() const'
/home/dealii/libs/trilinos-release-13-2-0/lib/libstratimikosbelos.so: error: undefined reference to 'Tpetra::MultiVector<float, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getNumVectors() const'
/home/dealii/libs/trilinos-release-13-2-0/lib/libstratimikosbelos.so: error: undefined reference to 'Tpetra::MultiVector<float, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::get1dCopy(Teuchos::ArrayView<float> const&, unsigned long) const'
```
Is that at all related to this patch?

**Review by bangerth — APPROVED** [review]
Also, nice work! Thank you!

**Comment by simonsticko** [comment]
> We fail with this error:
> [...]
> Is that at all related to this patch?

I don't think so. The only changes in `source/` are in `non_matching` and does not relate to trilinos at all.

**Comment by bangerth** [comment]
That error is apparently gone, but this one still remains:
```
sharedtria/dof_05.mpirun=3.debug: RUN failed. ------ Additional output on stdout/stderr:


--------------------------------------------------------
An error occurred in line <2137> of file </jenkins/workspace/dealii-mpi_PR-15727/source/grid/tria_accessor.cc> in function
    dealii::TriaActiveIterator<dealii::DoFCellAccessor<dim, spacedim, false> > dealii::CellAccessor<dim, spacedim>::as_dof_handler_iterator(const dealii::DoFHandler<dim, spacedim>&) const [with int dim = 2; int spacedim = 2]
The violated condition was: 
    &this->get_triangulation() == &dof_handler.get_triangulation()
Additional information: 
    The triangulation associated with the iterator does not match that of
    the DoFHandler.
--------------------------------------------------------
```

**Comment by simonsticko** [comment]
> That error is apparently gone, but this one still remains:
> 
> ```
> sharedtria/dof_05.mpirun=3.debug: RUN failed. ------ Additional output on stdout/stderr:
> --------------------------------------------------------
> ```

Okey. I had to remove the change I had in `sharedtria/dof_05.cc`. We can not use the new function here, because the triangulations are not the same type, but corresponds to the same mesh.

**Review by peterrum — APPROVED** [review]

**Pull request merged**
