### PR TITLE
Adjust test output for Zoltan

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes the failing test https://cdash.kyomu.43-1.org/testSummary.php?project=1&name=sharedtria%2Fcommunicate_active_fe_indices_01.mpirun%3D3.debug&date=2017-12-02 for Zoltan.

### CODE REVIEW

**Comment by davydden** [comment]
are you sure you don't want to add an additional output instead?

**Comment by davydden** [comment]
Maybe the old file was generated prior to switch form `flip-coin` strategy for locally owned dofs to the one based on MPI rank....

**Comment by masterleinad** [comment]
It seems to be failing for 

> Maybe the old file was generated prior to switch form flip-coin strategy for locally owned dofs to the one based on MPI rank....

Might be... let me double check for the other cases locally.

**Comment by masterleinad** [comment]
OK. It seems that my idea with using different output files didn't actually work and therefore the Zoltan setup was never really tested. In the end, the `trilinos=true/false` was just ignored. I am not sure if this is worth fixing since it is only related to the testsuite, but we should keep this in mind.

**Pull request merged**
