### PR TITLE
Generalize the numbering in the Cuthill-McKee algorithm.

### LINKED ISSUE #5407: Make DoFRenumbering::Cuthill_McKee work with locally *relevant* DoFs in parallel
@stmcgovern wrote a piece of code that modifies step-40 to use a Cuthill-McKee renumbering in parallel. The idea was to simulate a downstream numbering by using the upstream-most DoFs on each processor as starting indices. It didn't work because some of the starting indices were only locally relevant, not locally owned DoFs as hoped for. I do, however, think that it would be nice if we could allow for this to actually work -- i.e., some of the starting indices are locally relevant, whereas we of course only renumber the locally owned ones.

For reference, here is the piece of code that triggers this:
```

  locally_owned_dofs = dof_handler.locally_owned_dofs();
  DoFTools::extract_locally_relevant_dofs(dof_handler, locally_relevant_dofs);
  //TODO: put out the sparsity patterns
  //Point<dim> direction (0,-1);
  //locally_owned_dofs = dof_handler.locally_owned_dofs();

  std::vector<types::global_dof_index> starting_indices;
  //starting_indices.clear();


  const QGauss<dim - 1> face_quadrature_formula(fe.degree + 1);
  FEFaceValues<dim> fe_face_values(fe, face_quadrature_formula,
                                   update_values | update_quadrature_points | update_normal_vectors |
                                       update_JxW_values);

  Tensor<1, dim> u;
  Point<dim> down{0,-1};
  std::vector< types::global_dof_index >dof_indices (fe.n_dofs_per_face(), 0);


  for (const auto &cell: dof_handler.active_cell_iterators())
    {
    if(cell->is_locally_owned())
      {

      for (unsigned int face = 0; face < GeometryInfo<dim>::faces_per_cell; ++face)
        {
          if ((cell->face(face)->at_boundary()) 
            || (cell->neighbor(face)->active()) && (cell->neighbor(face)->is_ghost()))
            {
              fe_face_values.reinit(cell, face);
              //for Q_2 this is in middle of face, dim=2 or what quadrature point to give?
              u=fe_face_values.normal_vector(1); 
              if(u*down< 0)
                {
                cell->face(face)->get_dof_indices(dof_indices);
                starting_indices.insert(std::end(starting_indices),
                                        std::begin(dof_indices), std::end(dof_indices));
               }
            }
        }
      }
   }

//  //remove duplicates by creating a set
 std::set<types::global_dof_index> no_duplicates_please (starting_indices.begin(),
                                                          starting_indices.end());
//  //back to vector for the DoFRenumbering function
starting_indices.clear();
starting_indices.assign(no_duplicates_please.begin(), no_duplicates_please.end());
//  starting_indices.insert(std::end(starting_indices),
//                                 std::begin(no_duplicates_please), std::end(no_duplicates_please));


  //starting_indices=locally_owned_dofs;
 // DoFTools::extract_locally_owned_dofs(dof_handler, starting_indices);
 DoFRenumbering::Cuthill_McKee(dof_handler,false, true, starting_indices);
```
This would sit right after the initial `distribute_dofs()` call in step-40.

### PR DESCRIPTION
**Pull request by bangerth**
Specifically, allow locally active, not only locally owned DoF indices as starting points. The reasoning for this is given in #5407.

Fixes #5407.

### CODE REVIEW

**Comment by masterleinad** [comment]
This looks good to me me but I would prefer if the choice of which DoFs to run the renumbering algorithm on would not depend on `starting_indices`. At least, I don't immediately see why they are strongly coupled.
Since we probably don't want the new algorithm to be the default (due to backward compatibility), what about a new flag?

**Comment by bangerth** [comment]
@masterleinad: You mean I should *always* renumber the locally active DoFs, whether or not the starting indices are a subset of the locally owned ones or not? That would make things substantially more expensive for the (common) case that only locally owned DoFs were provided as starting indices (including the *default* case where no starting indices were given at all).

Or maybe I misunderstand? In essence, the flag you propose is identical to "do the starting indices contain DoFs that are not locally owned?"

**Comment by masterleinad** [comment]
I was not aware that including the locally active indices would be much more expensive.
If you are saying that the actual benefit from including more DoFs general does not pay off in general, it clearly should not be the default.

**Comment by masterleinad** [comment]
The flag I was proposing would be identical to "do the renumbering on the locally active DoFs" regardless of the starting indices containing DoFs that are locally active or not. Does this make sense to you?

**Comment by bangerth** [comment]
Yes, basically all of the patch deals with translating indices if you have active indices in the set of starting indices. The actual renumbering happens in a `SparsityTools` function. So yes, it's significantly more expensive, I'm afraid.

**Comment by bangerth** [comment]
Re flag: I see what you want to do, but I don't see why you would want to do that -- I can't see a use case for it. Cuthill-McKee is a sort of black box algorithm for which the *overall, qualitative* properties of the renumbering are what people care about. The *exact outcome* of the algorithm is typically not important, and consequently I don't see why one would need to have overly fine-grained control over the details.

**Comment by masterleinad** [comment]
You need to run the indentation script.

**Comment by bangerth** [comment]
Now properly indented.

**Comment by masterleinad** [comment]
Since no one else seems to have a opinion on this, let's merge.

**Pull request merged**
