### PR TITLE
replace CMAKE_(SOURCE|BINARY)_DIR with relative paths to allow ADD_SUBDIRECTORY()

### PR DESCRIPTION
**Pull request by DAlexis**
Related to old issue https://github.com/dealii/dealii/issues/2393
(sorry for two years late...)

CMake variables fixed:
- CMAKE_SOURCE_DIR replaced by CMAKE_CURRENT_SOURCE_DIR or deal.II_SOURCE_DIR
- CMAKE_BINARY_DIR replaced by deal.II_BINARY_DIR

### CODE REVIEW

**Comment by DAlexis** [comment]
It is only replacing one CMake built-in variables with another that has the same value when we build deal.ii as a root project. If deal.ii is used anywhere as a subproject by i.e. `add_subdirectory(deal.ii)` new variables are correct instead of old ones.

**Comment by tamiko** [comment]
Thanks for your contribution! I'd like to think about this first before we are going ahead and merge it. I have added the "do not merge" Tag in the meantime.

**Comment by DAlexis** [comment]
OK, thank you!

**Comment by tamiko** [comment]
Please apply the following changes to the top level `CMakeLists.txt`:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index fee6b73072..fd21da1759 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -95,15 +95,15 @@ VERBOSE_INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/cmake/setup_cached_variables.cmake)
 PROJECT(deal.II CXX C)
 ENABLE_LANGUAGE_OPTIONAL(Fortran)
 
-VERBOSE_INCLUDE(${deal.II_SOURCE_DIR}/cmake/setup_deal_ii.cmake)
+VERBOSE_INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/cmake/setup_deal_ii.cmake)
 
-VERBOSE_INCLUDE(${deal.II_SOURCE_DIR}/cmake/setup_compiler_flags.cmake)
+VERBOSE_INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/cmake/setup_compiler_flags.cmake)
 
 #
 # Include information about bundled libraries:
 #
 IF(DEAL_II_HAVE_BUNDLED_DIRECTORY)
-  VERBOSE_INCLUDE(${deal.II_SOURCE_DIR}/bundled/setup_bundled.cmake)
+  VERBOSE_INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/bundled/setup_bundled.cmake)
 ENDIF()
 
 #
@@ -127,10 +127,10 @@ ENDFOREACH()
 #
 # Finalize the configuration:
 #
-VERBOSE_INCLUDE(${deal.II_SOURCE_DIR}/cmake/setup_cpack.cmake)
-VERBOSE_INCLUDE(${deal.II_SOURCE_DIR}/cmake/setup_custom_targets.cmake)
-VERBOSE_INCLUDE(${deal.II_SOURCE_DIR}/cmake/setup_finalize.cmake)
-VERBOSE_INCLUDE(${deal.II_SOURCE_DIR}/cmake/setup_write_config.cmake)
+VERBOSE_INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/cmake/setup_cpack.cmake)
+VERBOSE_INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/cmake/setup_custom_targets.cmake)
+VERBOSE_INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/cmake/setup_finalize.cmake)
+VERBOSE_INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/cmake/setup_write_config.cmake)
 
 ########################################################################
 #                                                                      #

```

**Comment by drwells** [comment]
Unfortunately, due to the issues @tamiko raised with this PR (in particular the problems with the test suite and the fact that deal.II is not intended for bundling) I don't think that there is any way to move forward right now. Hence I am going to close this for now: if we can figure out a solution for bundling that addresses the issues above we can always reopen this PR later.

**Comment by DAlexis** [comment]
Thank you for detailed explanation, it sounds reasonable

**Pull request closed without merging**
