### PR TITLE
Add a hint to the indention script

### LINKED ISSUE #9006: Improve indent error message
In the last few weeks, we had a lot of new user (which is good) who got during their first PR the following error message:

> invalid author 'MaxMustermann' without firstname and lastname

and in some cases we had to help them fix this issue. Could we improve the error message here 

https://github.com/dealii/dealii/blob/5e6bc00896e6eebccaaf0105f52c166dbcfe2005/contrib/utilities/indent_common.sh#L88

somehow?

Maybe with a link to a new (?) wiki entry, which describes a possible solution step by step.

ping @tjhei

### PR DESCRIPTION
**Pull request by peterrum**
closes #9006 

ping @masterleinad @tjhei

### CODE REVIEW

**Comment by tjhei** [comment]
can you please indent in the same way and link to https://github.com/dealii/dealii/wiki/Indentation instead?

**Comment by peterrum** [comment]
@tjhei done!

**Comment by tjhei** [comment]
can you also copy the blob down to the invalid email cases please?

**Comment by peterrum** [comment]
> can you also copy the blob down to the invalid email cases please?

done!

**Comment by tjhei** [comment]
thank you.

**Pull request merged**
