### PR TITLE
Check MSVC's constexpr support.

### PR DESCRIPTION
**Pull request by drwells**
We use constexpr for operator[] in Tensor - perhaps it will work here too.

### CODE REVIEW

**Comment by masterleinad** [comment]
Seems to work. :slightly_smiling_face:

**Comment by drwells** [comment]
If the CI passing here is enough to prove that this works for C++14 + MSVC then I'll go ahead and add some more functions like this.

**Comment by masterleinad** [comment]
> If the CI passing here is enough to prove that this works for C++14 + MSVC then I'll go ahead and add some more functions like this.

Yes, that's good enough for me.

**Comment by masterleinad** [comment]
BTW, https://github.com/masterleinad/dealii/actions/runs/338613981 shows the problems if you were to replace all places using `DEAL_II_CONSTEXPR`.

**Comment by rezarastak** [comment]
@masterleinad I think the problem you see is because of `standard_tensors.cc`. Currently there is `#define` statements which determines whether we want to define the constants in the header file or the source file. Now that we are using the `constexpr` feature directly, we must remove the initialization in the cc file altogether. For example, we shouldn't allow initialization of the constant here by replacing 

https://github.com/dealii/dealii/blob/2d712df2abcc2da14253ed41288146364607311a/source/physics/elasticity/standard_tensors.cc#L24-L30

with

```c++
template <int dim> 
constexpr SymmetricTensor<2, dim> Physics::Elasticity::StandardTensors<dim>::I;
```

That's my guess. The issue might be something else. I haven't tested my guess yet.

**Comment by drwells** [comment]
I'm not sure how to handle those difficult initialization cases but we should go ahead with the easy ones.

**Comment by bangerth** [comment]
@drwells There are a good number of compile failures here: https://jenkins.tjhei.info/blue/organizations/jenkins/dealii/detail/PR-11122/20/pipeline/ Can you take a look?

**Comment by drwells** [comment]
It looks like I converted a few cases that are actually a constexpr bug on a non-MSVC compiler - I need to convert those back and we should be set.

**Comment by tjhei** [comment]
Do you have access to an Intel compiler? It might be worth checking if things are okay with this PR as well.

**Comment by drwells** [comment]
There's one on a cluster here I can access. I'll check that next.

**Comment by bangerth** [comment]
What should we do here? The check that fails is for GCC 5.4 (the "CI" check), which I have battled to a substantial degree as well regarding `constexpr` in the last week.

**Comment by drwells** [comment]
I've had this on the back burner for awhile for various reasons. I'll try to return to this PR soon.

**Comment by drwells** [comment]
In particular, I should be able to finish it by installing my own copy of GCC 5.4 and then partially reverting the second commit.

**Comment by drwells** [comment]
I had to revert a bunch of code to get this to work with older versions of clang and GCC but this is now ready.

**Review by bangerth — APPROVED** [review]
Nice work!

**Pull request merged**
