### PR TITLE
Rename TensorPolynomials::compute() to ::evaluate().

### PR DESCRIPTION
**Pull request by bangerth**
We've used this kind of terminology in a number of other places. The point is
that we don't 'compute' the polynomial at that point; its form is fixed. Rather,
we 'evaluate' the polynomial for a particular value of its argument.

@GrahamBenHarper -- FYI.

Part of #1973.

### CODE REVIEW

**Comment by Rombur** [comment]
The format is wrong

**Comment by bangerth** [comment]
Khkhkh. Let's try this again...

**Comment by bangerth** [comment]
Seems to pass the testers now.

**Pull request merged**
