### PR TITLE
Cleanups for #6864 

### PR DESCRIPTION
**Pull request by marcfehling**
This pull request meets the inquiries of issue #6877 on pull request #6864.

See #6877 for discussion.

### CODE REVIEW

**Comment by marcfehling** [comment]
I did not change the <tt>Utilities::pack()</tt> and <tt>Utilities::unpack()</tt> functions, but the interface of <tt>p::d::Triangulation</tt> upon transfer, i.e. <tt>register_data_attach()</tt> and <tt>notify_ready_to_unpack()</tt>.

Do you mean those or did I miss your point?

**Comment by bangerth** [comment]
@davydden -- this patch only changes things that were introduced in #6864. I had wanted to have #6864 finished and merged because it's just such a big change, and therefore asked that the last few comments be addressed in separate PRs, rather than having to go through more rounds of reviews that only affect a small part of it.

**Comment by davydden** [comment]
Ah, yes, I miss-interpreted the changes. My bad.

**Pull request merged**
