### PR TITLE
Redefine Assert as AssertThrow in tests

### PR DESCRIPTION
**Pull request by masterleinad**
Implementing option 2 in https://github.com/dealii/dealii/pull/9502#issuecomment-584141754. Our clang-format options already make sure that `"../tests.h"` is always the last header file to include.

### CODE REVIEW

**Comment by drwells** [comment]
There are a few other headers in the test suite - could we also convert those while we are making this change?

**Comment by tjhei** [comment]
Can you please leave a comment in tests.h before the define to explain what this does and why we do this?

**Comment by masterleinad** [comment]
So what do we want to do with this? Are there any objections?

**Comment by drwells** [comment]
Unless someone objects I will merge later today.

**Pull request merged**
