### PR TITLE
Test for p::d::Tria::load(forest).

### PR DESCRIPTION
**Pull request by marcfehling**
Follow-up to #11715.

Adds assertions and a test.

### CODE REVIEW

**Comment by marcfehling** [comment]
I couldn't verify that my test passes.
For some reason, `ctest` ignores my whole `tests/mpi` folder right now...
I try to figure out if this is a local problem on the machines I use...

**Review by peterrum — APPROVED** [review]

**Comment by peterrum** [comment]
> I couldn't verify that my test passes.

Looks good to me. Thanks! I have added the "Do not merge" label until you have resolved the issue!

**Review by bangerth — APPROVED** [review]

**Comment by marcfehling** [comment]
> I have added the "Do not merge" label until you have resolved the issue!

There was a problem with my `CMakeCache`. The test passes now. Ready for merge!

**Pull request merged**
