### PR TITLE
Improve resolution in step 8.

### PR DESCRIPTION
**Pull request by chronictectonic**
Improved resolution to generate better looking figures (attached here).
step-8 x
step-8 y

### CODE REVIEW

**Comment by drwells** [comment]
Looks good! Would you please crop the images so that we do not see the coordinates axes?

**Comment by chronictectonic** [comment]
Thanks! I noticed that shortly after uploading.
step-8 x
step-8 y

**Comment by chronictectonic** [comment]
And the vector field
step-8 vectors

**Comment by bangerth** [comment]
This increases run-time of this program from 4 to 40 seconds -- which seems entirely reasonable.

@chronictectonic -- do you think you could come up with a small changelog entry that, in one line, explains what you changed? Let us know once you've got it added and we can merge!

**Comment by bangerth** [comment]
I've updated the pictures on the website with the ones from here.

**Comment by bangerth** [comment]
I've used the pictures in #8557, by the way. Thanks for creating them!

**Pull request merged**
