### PR TITLE
Make FiniteElement::operator== virtual.

### PR DESCRIPTION
**Pull request by bangerth**
Also provide a bit more documentation about what it does.

This is a follow-up to #6325, #6330, and all of the associated
tests. We might still want to add operator== to some of the
derived classes, but this is for sure the necessary first
step.

### CODE REVIEW

**Comment by bangerth** [comment]
Blocks #6156.

/run-tests

**Comment by bangerth** [comment]
Since the tester wasn't through yet, I've pushed another commit that strengthens the guarantees provided by this operator.

**Comment by davydden** [comment]
@bangerth can you please rebase, i think the tester failed for unrelated reasons.

**Comment by masterleinad** [comment]
OK. Let me correct myself. The test is failing because the `prolongation` matrices are not the same.

I would vote for not comparing the matrices. They are either set up while constructing or on-the-fly if needed. Hence, it should still be fine to call objects only differing in these two variables "equal".
Furthermore, these last checks might be quite expensive and might force these matrices to be recalculated in each call to `distribute_dofs`.

**Comment by bangerth** [comment]
Good point. I've taken these comparisons out again and documented why. Though that does not make me too comfortable -- I think there is value in comparing these matrices. But that may be for a different day.

Updated version now here. It passes the one wayward test. Glad we have this many tests checking everything :-)

**Pull request merged**
