### PR TITLE
Add unit test for make_flux_sparsity_pattern() with periodicity.

### PR DESCRIPTION
**Pull request by spco**
This is a unit test as a follow up to #3232. I've verified that before #3232 it fails. I've only put the simplest case in here, without checking anything about distributed meshes.

### CODE REVIEW

**Comment by tjhei** [comment]
excellent, thanks @spco !

**Comment by drwells** [comment]
I can confirm that this test fails without the recent patch :)

**Comment by tjhei** [comment]
> /run-tests

sadly we currently don't run the full testsuite because that would take too long (``TESTREGEX='all-headers|multigrid/transfer'`` ;-) ).

**Pull request merged**
