### PR TITLE
Get rid of create_triangulation_compatibility in the UCD reader.

### PR DESCRIPTION
**Pull request by drwells**
Also part of #8562.

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]

**Review by peterrum — APPROVED** [review]
Is here the same true as here https://github.com/dealii/dealii/pull/12039#pullrequestreview-635164672?

**Review by masterleinad — APPROVED** [review]

**Comment by drwells** [comment]
> Is here the same true as in [#12039 (review)](https://github.com/dealii/dealii/pull/12039#pullrequestreview-635164672)?

In this particular case, no. The old-style ordering is the same as UCD, so this function just does the reordering here instead of later - the end result is identical.

**Comment by drwells** [comment]
Then again some tests fail now so that may not be true for code that calls this code. I'll investigate.

**Comment by drwells** [comment]
The ouputs were slightly different since we used an acceptable (but different) reordering for hexahedra with negative volume - the commit I just pushed should fix the issue but it might mess up some output changed in #11784.

**Review by peterrum — APPROVED** [review]

**Review by Rombur — APPROVED** [review]

**Pull request merged**
