### PR TITLE
Implement a more generic method of converting between number types.

### PR DESCRIPTION
**Pull request by jppelteret**
This is particularly useful when needing to cast exotic number types to
a floating point numbers, such as might happen when converting between
tensor types.

### CODE REVIEW

**Comment by bangerth** [comment]
This looks reasonable, but there are two tests that I thought we had fixed a good while back (interpolate_q_system and step_15). Is your branch based on something several weeks old?

**Comment by jppelteret** [comment]
@bangerth Yes, I this is based off quite an old version of master. I'll
gladly rebase it but I can only do this tomorrow.

**Comment by bangerth** [comment]
No need -- I was just wondering whether it fails because of anything in this patch, or because it's rooted in something old.

**Pull request merged**
