### PR TITLE
Remove doxygen format from a comment block

### LINKED ISSUE #8203: doxygen: symengine doxygen blurb not visible
The following paragraph is not visible anywhere:
https://github.com/dealii/dealii/blob/master/include/deal.II/differentiation/sd/symengine_math.h#L34

@jppelteret where can we put it?

### PR DESCRIPTION
**Pull request by jppelteret**
Fixes #8203

### CODE REVIEW

**Comment by jppelteret** [comment]
I thought about putting this in the description of the [`Differentiation::SD::Expression` class](https://dealii.org/developer/doxygen/deal.II/classDifferentiation_1_1SD_1_1Expression.html), but I'm unsure if it makes sense or not. Opinions?

**Comment by jppelteret** [comment]
Actually, this discusses implementation details, so it really doesn't belong there. Lets leave this as is.

**Comment by tjhei** [comment]
> Opinions?

I think it is fine as is (this seems more like implementation detail to me)

**Comment by tjhei** [comment]
not important for 9.1...

**Pull request merged**
