### PR TITLE
Update step-71.cc

### PR DESCRIPTION
**Pull request by cdev911**
correcting typo

### CODE REVIEW

**Review by tjhei — APPROVED** [review]
Great, thank you! Even the smallest typo fix is very much appreciated.

**Comment by tjhei** [comment]
Hi @cdev911 . It looks like our indentation tester rejected your pull request. Would it be possible for you to set up your github profile and your local git config to show your first and last name?

See https://github.com/dealii/dealii/wiki/Commit-authorship for more information.

Thank you.

**Comment by cdev911** [comment]
Dear Timo Heiste,
Thank you for explaining the reason for the pull request failure. 
I followed the instruction in the link you provided and created a new pull request.
Regards,
Chaitanya Dev

**Comment by peterrum** [comment]
Closing, since you fixed this instance by https://github.com/dealii/dealii/pull/13624. Thanks!

**Pull request closed without merging**
