### PR TITLE
Refactor RPE::evaluate_and_process()

### PR DESCRIPTION
**Pull request by peterrum**

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]
It is good to use vectors rather than maps. However, I am also worried about the number of copies we're making and the back and forth. It would be instructive (though not really for this PR) to see how much memory is needed to communicate something big, say 1M or 5M data items per MPI rank, or theoretically explain the cost. I could be wrong, but I am worried that the metadata and copy operations might overwhelm the actual data.

**Comment by peterrum** [comment]
@kronbichler  Thanks for the review! I have fixed the typo.

**Comment by peterrum** [comment]
> It is good to use vectors rather than maps. However, I am also worried about the number of copies we're making and the back and forth. It would be instructive (though not really for this PR) to see how much memory is needed to communicate something big, say 1M or 5M data items per MPI rank, or theoretically explain the cost. I could be wrong, but I am worried that the metadata and copy operations might overwhelm the actual data.

@kronbichler Independently, I was working on a follow-up PR: #15163, which happens to eliminates two copying steps for communication. The root problem is that we support arbitrary types via a template parameter, which required the packing/unpacking. This is a bit unfortunate and we should have only supported data that can be nicely linearized... In practice, one would use scalar, vectorial, or tensorial quantities (the types returned by `FEPointEvaluation`). My wish is to support multiple components of scalar quantities just like `Tensor<1, dim, double>` but without the point of templating.

**Comment by bangerth** [comment]
The things that are linearizeable are exactly the ones for which `ArrayView` is good. It should be possible to do what you want exactly for overloads that take an `ArrayView` object.

**Pull request merged**
