### PR TITLE
remove CXX14 requirement from FE_Enriched as we switched to C++11 of …

### PR DESCRIPTION
**Pull request by davydden**
…gcc4.8 and alike

**UPDATE:**

this compiles with `4.8.5` on `Ubuntu`. Therefore i would say that this PR also fixes https://github.com/dealii/dealii/issues/3209

### CODE REVIEW

**Comment by masterleinad** [comment]
Are there any C++11 features apart from `delegating constructors` that are used and we didn't require before for `DEAL_II_WITH_CXX11`?

**Comment by davydden** [comment]
> Are there any C++11 features apart from delegating constructors that are used

to my knowledge -- not. But if you really want to check, i can try building with gcc 4.8, available on Ubuntu 16.04.

**Comment by masterleinad** [comment]
@davydden That would be great! Otherwise, I have no objections.

**Comment by bangerth** [comment]
Looks good to me as well.

**Comment by davydden** [comment]
the PR compiled fine on `gcc@4.8.5` from `Ubuntu`. I update the OP.

**Comment by masterleinad** [comment]
Is there anything else you want to address or can the `WIP` label be removed?

**Comment by davydden** [comment]
@masterleinad i just forgot to remove it.

**Comment by davydden** [comment]
i guess the tested is stuck, can someone re-run it with `/run-tests` or something?

**Pull request merged**
