### PR TITLE
Tests: output variants for opencascade 6.9.1

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Comment by drwells** [comment]
If possible, would you mind fixing the typo in the commit message?

**Comment by tamiko** [comment]
@drwells done.

**Comment by tamiko** [comment]
@drwells Would you mind to merge this, please? :-)

**Comment by davydden** [comment]
i have a feeling that this is the same as what i added in https://github.com/dealii/dealii/pull/3938 prior to this PR being merged.

**Comment by drwells** [comment]
@tamiko I must have missed that this was not merged. Sorry!

**Pull request merged**
