### PR TITLE
Turn off checking CXX flags for Win64 (fails for no apparent reason).

### PR DESCRIPTION
**Pull request by l-korous**

### CODE REVIEW

**Comment by bangerth** [comment]
I think it would actually be quite interesting to understand why it fails. Does it produce output in CMakeFiles/CMakeError.log?

In any case, can you adjust indentation so that the changed lines use the standard 2-character indent?

**Comment by bangerth** [comment]
(What I meant is: does the pre-existing check produce output whenever it fails, and if so what is that output? If one can't compile such a trivial program, it points to something fundamental that we will probably encounter in other tests as well that may then fail for reasons unrelated to what the test was really intended to do. For example, if a test for a LAPACK interface fails not because it can't find LAPACK but because of the same problem we encounter here, then that's no good.)

**Comment by l-korous** [comment]
I see - I will send what I will be able to find.

**Comment by bangerth** [comment]
Any news?

**Comment by l-korous** [comment]
Hi, sorry, I was probably getting such problems when using dealII as a sub-project in our CMake-governed application using dealII. Now when I test with clean dealII, I am able to run CMake on Win64 with no problems.

**Pull request closed without merging**
