### PR TITLE
Get vertices in CGAL order on face

### PR DESCRIPTION
**Pull request by jh66637**
Say I have the ```Mapping``` and a corresponding ```cell``` with dimension ```spacedim```. I want to get vertices in real coordinates of an ```face``` on that ```cell```. This is what can be done by introduced function. I am not sure if there are smarter ways to get the vertices on a face. If there are, I couldn't find any.
@fdrmrc @peterrum

### CODE REVIEW

**Comment by peterrum** [comment]
@jh66637 We have the open discussion here: https://github.com/dealii/dealii/pull/13569#issuecomment-1107817632. Personally, I have the feeling that you are doing two things at once: 1) extracting the face vertices and 2) permutation according to CGAL. I think these should be kept separate.

**Comment by jh66637** [comment]
If you prefer, I can split the function in two. If doing so, I would still like to keep a function which combines the two separate functions. 
I can give https://github.com/dealii/dealii/pull/13569#issuecomment-1107817632 a try tomorrow and use it here once it's merged.

**Comment by jh66637** [comment]
This should be merged after https://github.com/dealii/dealii/pull/14362

**Comment by jh66637** [comment]
Once the mapping can give the vertices of a face on a cell, this function can be used to determine the vertices on a face in CGAL order.

Depends on:
https://github.com/dealii/dealii/pull/14727

**Comment by jh66637** [comment]
@peterrum Since https://github.com/dealii/dealii/pull/14727 is merged I think this can be merged as well.

**Review by peterrum — APPROVED** [review]

**Comment by jh66637** [comment]
@peterrum I squashed the commits and it would be ready to merge from my side. Is there anything left to do before merging :)?

**Review by peterrum — APPROVED** [review]

**Pull request merged**
