### PR TITLE
Use std_cxx20::type_identity_t instead of identity<...>::type.

### PR DESCRIPTION
**Pull request by bangerth**
This uses the infrastructure in #14915.

### CODE REVIEW

**Review by masterleinad — COMMENTED** [review]
Didn't you want to deprecate `dealii::identity` in this pull request as well?

**Comment by bangerth** [comment]
I had meant for it to be a separate PR. Since this one already tested clean, can I postpone to a separate PR?

**Comment by masterleinad** [comment]
> I had meant for it to be a separate PR. Since this one already tested clean, can I postpone to a separate PR?

Sure. I would probably have done all of that in one pull request instead of three. 🙂

**Review by masterleinad — APPROVED** [review]

**Comment by bangerth** [comment]
Part of the issue is also that our CI turn-around times are just too long. Making a revision to a PR that has already tested cleanly basically delays getting things merged by a day. I'd rather have the big patch merged and the small addition pending, then have it all pending.

**Pull request merged**
