### PR TITLE
Support for RTNodal and FENothing in hp::FECollection

### PR DESCRIPTION
**Pull request by eldarkh**
This change adds the ability to use the Raviart-Thomas Nodal FE space with `FE_Nothing` in `hp::FECollection`. With this, one may implement multiphysics problems, e.g. coupled Stokes-Darcy, with vector-valued finite elements for Darcy in the same way as it is shown in Step-46 tutorial. A brief discussion of the issue can be found in Deal.II Google group [here](https://groups.google.com/forum/#!topic/dealii/1TMlwXffT8E).

### CODE REVIEW

**Comment by tjhei** [comment]
> would you mind adding a single test which illustrates the usage?

... and let us know if you need help with that!

**Comment by eldarkh** [comment]
@tjhei I am currently doing a test similar to `tests/hp/face_domination_02.cc` as it is similar to the way this is used. Should I also do tests similar to the `tests/hp/hp_line_dof_identities_rt_nodal.cc` (and the versions of quad, vertex dof identities) as I modified these functions as well?

**Comment by eldarkh** [comment]
I added the test that checks `face_domination` part. As the rest of my modifications involve only `FE_Nothing` I did not do any extra tests like `hp_line_dof_identities_rt_nodal`. Please let me know if any other tests are needed.

**Comment by eldarkh** [comment]
I added the required test for `face_domination`. As my changes only involve the case when other FE is `FE_Nothing` I did not do the `hp_line_dof_identities_rt_nodal` type tests.

**Comment by bangerth** [comment]
I agree this looks good.
OK to merge once the tester is happy.

**Comment by masterleinad** [comment]
Somehow the tester seem to be stuck on this...

**Comment by eldarkh** [comment]
@masterleinad Is it my test that is failing or my changes broke something else?

**Comment by masterleinad** [comment]
I ran a whole testsuite locally and results look good so I just merge.

**Pull request merged**
