### PR TITLE
matrix-free: remove deprecated mpi_communicator

### PR DESCRIPTION
**Pull request by davydden**
since we already have 8.5 branch, i think we can remove depricated mpi communicator.

~~running `$ ctest -R "matrix_free"` now...~~

all `$ ctest -R "matrix_free"` pass.

fixes https://github.com/dealii/dealii/issues/4123

### CODE REVIEW

**Comment by kronbichler** [comment]
While I don't disagree with removing this, I wonder why you are in such a hurry. Is there anything that makes your life more complicated? (It has only been 2.5 months since this feature was deprecated so even though I would remove it with this release I would have given it another two months or so.)

**Comment by masterleinad** [comment]
@davydden It's `deprecated` not `depricated` :wink:
I agree with @kronbichler  that we typically wait some more time.

**Comment by bangerth** [comment]
I might disagree. If it's been deprecated for one release, I would think that it's fair game to remove for the next at any point in the release process.

**Comment by kronbichler** [comment]
OK, consider my convinced in case you also get rid of the ugly `DEAL_II_DISABLE_EXTRA_DIAGNOSTICS` construction around that part, in lines `170` and `284` (after your change).

**Comment by davydden** [comment]
> I wonder why you are in such a hurry

Because I see like ten annoying warnings every time I compile my code ;-)

**Comment by kronbichler** [comment]
I did not see them due to the `gcc` compiler.

**Comment by davydden** [comment]
@kronbichler i got rid of `DEAL_II_DISABLE_EXTRA_DIAGNOSTICS`.

**Comment by kronbichler** [comment]
@davydden Would you please add an entry to the incompatibilities section in the changelog? (We will accumulate a number of removed things for this release, so do it similar as in the last release.)

**Pull request merged**
