### PR TITLE
reflow comments and ensure @ref is on a newline, some doxygen bugfixs

### PR DESCRIPTION
**Pull request by tamiko**
This is in preparation of running wrapcomments.py

Part of release step 0c/ (#8080)

### CODE REVIEW

**Comment by tjhei** [comment]
overlap with #8127 :-(
Sorry, I thought I would be in a better situation to do these fixes.

**Comment by tjhei** [comment]
> This is in preparation of running wrapcomments.py

don't do that. I think we decided to skip it as it just generates too much churn and has little value.

**Comment by kronbichler** [comment]
@tamiko please pull out the handful changes that still make sense now that #8127 is merged and I can merge. Or since it's so few and none is critical, we can also skip them altogether.

**Comment by tamiko** [comment]
@tjhei 
> don't do that. I think we decided to skip it as it just generates too much churn and has little value.

We never updated the release tasks! :-D

**Pull request closed without merging**
