### PR TITLE
fix some compiler warnings

### PR DESCRIPTION
**Pull request by richardschu**
reincarnation of #15219

### CODE REVIEW

**Review by peterrum — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]

**Review by bangerth — APPROVED** [review]

**Comment by masterleinad** [comment]
```
invalid author 'RichardSchussnig' without firstname and lastname
```

**Comment by richardschu** [comment]
> ```
> invalid author 'RichardSchussnig' without firstname and lastname
> ```

Thank you for the hint! :+1:

**Review by peterrum — COMMENTED** [review]
@richardschu Could you squash the commits?

**Pull request merged**
