### PR TITLE
Instantiate MatrixTools::apply_boundary_values also for complex values

### PR DESCRIPTION
**Pull request by masterleinad**
https://groups.google.com/g/dealii/c/tJKPan6rCa8 shows issues using `MatrixTools::apply_boundary_values` with `std::complex<>` values. I don't see a good reason not to instantiate these templates for all scalars.

### CODE REVIEW

**Review by bangerth — APPROVED** [review]
Would it be difficult to add a test?

**Comment by masterleinad** [comment]
@bangerth I added a test.

**Comment by masterleinad** [comment]
I fixed the indentation.

**Pull request merged**
