### PR TITLE
move FESystem's auxiliary functions to FETools and extend them to cov…

### PR DESCRIPTION
**Pull request by davydden**
…er the non-tensor product case of the enriched finite element

TODO:
- [x] do some basic unit tests (at least in `/fe`)
- [x] add cell/face tables functions
- [x] run full test suite.

in reference to this comment https://github.com/dealii/dealii/pull/2106#issuecomment-174331994

### CODE REVIEW

**Comment by davydden** [comment]
i did 
```
ctest -R 'fe_system`
```
but there are very few tests with `fe_system` in their name. Any ideas about other unit tests which use `FESystem`?

**Comment by davydden** [comment]
i found quite a lot `$ ag --cpp -l FESystem` now :smile:

**Comment by bangerth** [comment]
Running the entire `fe/` subdirectory via
```
  ctest -R fe/
```
also seems like a valid strategy.

**Comment by davydden** [comment]
will do...

**Comment by davydden** [comment]
the `fe/` test suite pass the same way as on `master` with 2 failing tests:
```
The following tests FAILED:
	4028 - fe/mapping_manifold_06.debug (Failed)
	4029 - fe/mapping_manifold_06.release (Failed)
	4040 - fe/mapping_q_manifold_01.debug (Failed)
	4041 - fe/mapping_q_manifold_01.release (Failed)
```
So it looks so far i have not broken anything.

**Comment by davydden** [comment]
i move a few things related to cell/face tables as well.

**Comment by davydden** [comment]
I will run the full test suite tomorrow to be sure that nothing got broken during copy-paste + those minor modifications...

**Comment by davydden** [comment]
```
99% tests passed, 13 tests failed out of 8242

Total Test time (real) = 12309.17 sec

The following tests FAILED:
	2620 - lac/schur_complement_01.debug (Failed)
	2621 - lac/schur_complement_01.release (Failed)
	3677 - slepc/step-36_parallel.mpirun=3.debug (Failed)
	3678 - slepc/step-36_parallel.mpirun=3.release (Failed)
	4083 - algorithms/newton_01.debug (Failed)
	4084 - algorithms/newton_01.release (Failed)
	5697 - manifold/spherical_manifold_07.debug (Failed)
	5698 - manifold/spherical_manifold_07.release (Failed)
	6087 - fe/mapping_manifold_06.debug (Failed)
	6088 - fe/mapping_manifold_06.release (Failed)
	6273 - fe/mapping_q_manifold_01.debug (Failed)
	6274 - fe/mapping_q_manifold_01.release (Failed)
	6753 - base/reference.debug (Failed)
````

**Comment by davydden** [comment]
None of these seem to be using `FESystem`.

**Comment by drwells** [comment]
Yes, those are also currently marked by the tester.

**Comment by bangerth** [comment]
As always, I missed asking for an entry in the changelog. Can you add this in a separate PR?

**Pull request merged**
