### PR TITLE
Doc/fix update flags h

### PR DESCRIPTION
**Pull request by saitoasukakawaii**
Fixed the bug of the third formula in doc/doxygen/headers/fix_update_flags_h.

### CODE REVIEW

**Review by drwells — APPROVED** [review]
Thanks!

**Comment by drwells** [comment]
The changes to the code are good. We need to fix authorship information before we merge - deal.II requires that all authors provide first and last names. The guide on how to do this (in particular, how to change authorship information for existing commits) is here:

https://github.com/dealii/dealii/wiki/Commit-authorship

Let us know if you need help figuring this out.

**Comment by saitoasukakawaii** [comment]
I have updated my information by the following code, any other I should do? I Thank you for your instruction.
> git config --global user.name "Huimin Chen"
> git config --global user.email "hkchm1997@gmail.com"
> git commit --amend --author="Huimin Chen <hkchm1997@gmail.com>"

**Comment by marcfehling** [comment]
You have successfully 

I think the best way to continue now is to squash your two commits into one. For this, you can follow this guide:

**Comment by marcfehling** [comment]
@saitoasukakawaii Please let us know if you need help!

**Comment by marcfehling** [comment]
Shortly before the upcoming release, I took the liberty and pushed directly to your branch.

You are still the author of the commit, which you can verify while you click on your commit here on github.

However, the gmail address you provided is not the one you used to create your github account (or rather it is not affiliated with your account). Thus, your username won't show up with the commit.

You have 3 options:
1. Add your gmail address to your github account.
2. Change the authorship of the commit again and use a mail address that is affiliated with your github account.
3. Leave everything as is and we will just merge the PR the way it is.

**Pull request merged**
