### PR TITLE
Fix orientation of triangular faces

### PR DESCRIPTION
**Pull request by peterrum**
... and add two tests.

Depends on #11509.

### CODE REVIEW

**Review by drwells — APPROVED** [review]

**Comment by drwells** [comment]
You'll need to rebase but otherwise 👍

**Comment by drwells** [comment]
Some of the matrix-free tests aren't passing anymore, like matrix_free/matrix_vector_faces_25.debug.

**Comment by peterrum** [comment]
@drwells I think now it should work.

**Review by drwells — APPROVED** [review]

**Pull request merged**
