### PR TITLE
Add Boost serialization function to CellData

### PR DESCRIPTION
**Pull request by peterrum**
This PR is part of the effort to introduce the new `parallel::fullydistributed::Triangulation` (see #8558). This triangulation will be optionally created in two steps: 
1. create the `p:f:ConstructionData` by a set of master processes and 
2. distributed it to the other processes. 

To pack the `ConstrcutionData`, I intend to use the Boost serialization capabilities. Since `ConstructionData` contains a list of `dealii::CellData`, this PR adds the `serialization`-function to `dealii::CellData`.

~~I think no test is needed.~~

### CODE REVIEW

**Comment by bangerth** [comment]
Thanks! I appreciate that you are willing to go along with our many requests to change your pull requests!

**Comment by peterrum** [comment]
Thanks! I right away rebase the other PR!

**Comment by peterrum** [comment]
> Thanks! I appreciate that you are willing to go along with our many requests to change your pull requests!

@bangerth It is a lot of work, I learn a lot, and the code definitely becomes better ;)

**Pull request merged**
