### PR TITLE
AffineConstraints Cleanup #1: Switch all tests to AffineConstraints<double>

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Comment by tamiko** [comment]
@davydden I want to run this through bob first.

**Comment by davydden** [comment]
> @davydden I want to run this through bob first. 

no worries, i did not add the magic-go-ahead-green-label 😄

**Comment by tamiko** [comment]
Passes the testsuite: https://cdash.kyomu.43-1.org/buildSummary.php?buildid=2619

**Comment by tamiko** [comment]
@dealii/dealii *ping* Please merge! :-)

**Pull request merged**
