### PR TITLE
Explicitely specify disabling of optimizations for MSVC build.

### PR DESCRIPTION
**Pull request by l-korous**
Turns out this is necessary to have correct CXX flags for debug build - MSVC does not provide /Od as default and selects /O2 for some reason. I debugged cmake in dealii and both DEAL_II_CXX_FLAGS and DEAL_II_CXX_FLAGS_DEBUG are OK (they do not produce the /O2) + CMAKE_CXX_FLAGS are not used & they do not contain it either (just checked to be sure) => so somehow apparently MSVC does.

### CODE REVIEW

**Comment by l-korous** [comment]
+ 1 more thing - MSVC is unhappy about FE_PolyFace class template - I believe it may be because the instantiations of this template are not explicitely specified. I wonder why it is so, I can try to debug it, but this is my first guess.

**Comment by bangerth** [comment]
On 08/10/2015 05:13 PM, l-korous wrote:
> 1 more thing - MSVC is unhappy about FE_PolyFace class template - I believe it
> may be because the instantiations of this template are not explicitely
> specified. I wonder why it is so, I can try to debug it, but this is my first
> guess.

Can you send the error message?

**Comment by tamiko** [comment]
@bangerth There is no error message involved - just no backtrace in debug mofde (as far as I understood).

**Comment by l-korous** [comment]
About the /Od addition - there is no error message, this is really just to disable the (probably default) selection of /O2

About the second issue - there is an error message, quite a few of them actually - but they do not make much sense, these are about incompatible definition / declaration of:
- FE_PolyFace<POLY,dim,spacedim>::get_data
- FE_PolyFace<POLY,dim,spacedim>::get_face_data
- FE_PolyFace<POLY,dim,spacedim>::get_subface_data
So my guess was to explicitly instantiate the template might help - maybe I can try to make it compile somehow if I knew why explicit instantiations are not used in this case.

**Comment by bangerth** [comment]
What I meant is show me the error message you get because of get_data.

It is true that FE_PolyFace is never *explicitly* instantiated, but it is *implicitly* instantiated in all of the files that `#include` `fe_poly_face.templates.h`. In principle, this should be enough, though there is of course the possibility of wonkiness of MSVC. If you show me the error, I may be able to tell what's going on.

**Comment by l-korous** [comment]
I perfectly understand you. They do not make any sense in reality, that is the problem. Here is one:


14>C:\hpfem\dealii\include\deal.II/fe/fe_poly_face.templates.h(95): error C2244: 'dealii::FE_PolyFace<POLY,dim,spacedim>::get_data' : unable to match function definition to an existing declaration
14>          definition:
14>          'dealii::FiniteElement<dim,spacedim>::InternalDataBase *dealii::FE_PolyFace<POLY,dim,spacedim>::get_data(const dealii::UpdateFlags,const dealii::Mapping<dim,spacedim> &,const dealii::Quadrature<dim> &) const'
14>          existing declarations:
14>          'dealii::FiniteElement<dim,spacedim>::InternalDataBase *dealii::FE_PolyFace<POLY,dim,spacedim>::get_data(const dealii::UpdateFlags,const dealii::Mapping<dim,spacedim> &,const dealii::Quadrature<dim> &) const'


-->> the definition and declaration are identical, this is what I meant by not making much sense, and it is why I deemed it may be an instantiation issue :-)

**Comment by bangerth** [comment]
Let's move the compiler error to a separate issue #1329.

The patch of adding /Od to the list of flags makes sense to me, but @tamiko knows this area better so I will let him merge the patch if he's ok with it.

**Pull request merged**
