### PR TITLE
Documentation fix for DerivativeForm

### PR DESCRIPTION
**Pull request by rezarastak**

### CODE REVIEW

**Comment by bangerth** [comment]
This pull request strictly improves the documentation -- thanks, @rezarastak !

At the same time, do you happen to know whether the documentation is actually correct? The description seems to suggest that different things happen based on the last template argument of the first argument, but this doesn't seem to be reflected in the function's implement!?

**Comment by rezarastak** [comment]
I agree that the current documentation of this function is (to some degree) confusing. Here is how I would define this function (in two separate ways):

1. If we treat DF as a tensor with rank (order+1), then the operation returns the single contraction of the last index of DF with the index of T
2. If we treat DF as the derivative of the mapping f() at point x, then the operation returns the linear approximation of the change of f(x) when we move x by vector T.
 
I personally prefer the second definition because it uses the concept of derivative and linear approximation. However, the first definition might be more precise syntactically. The author of the current documentation uses the notation (T * DF^T) to refer to the index contraction mentioned in the first definition. When DF is represented as a tensor with rank 1, DF does not have a well-defined transpose operation, and the transformation returns the dot product (DF . T) instead.

**Comment by bangerth** [comment]
@rezarastak -- thanks for figuring this out. Would you like to augment the documentation in this regard, expanding the description and using formulas as necessary?

**Comment by rezarastak** [comment]
Sure! I can improve the explanation for this function and submit a pull-request.

**Comment by bangerth** [comment]
That would be fantastic -- we appreciate ever one of these patches!

**Pull request merged**
