### PR TITLE
Add a bunch of dummy functions for TriaAccessor<0,1,spacedim>.

### LINKED ISSUE #13126: GridGenerator::flatten_triangulation() does not copy manifold ids of internal objects
As mentioned in the comments of #13117, `GridGenerator::flatten_manifold()` does not copy the manifold ids of internal objects.

### PR DESCRIPTION
**Pull request by bangerth**
To fix #13126 , I needed a bunch of functions in `TriaAccessor<0,1,spacedim>` to at least exist, though they will not be called. This patch adds them, but does not provide functional implementations (which doesn't matter, because as I mentioned, we don't actually call these functions).

/rebuild

### CODE REVIEW

**Comment by bangerth** [comment]
While looking at this, I realized that there are a bunch of places where one could mark function arguments as `const`. I do so in a second commit.

**Review by masterleinad — APPROVED** [review]
Looks OK to me.

**Comment by masterleinad** [comment]
```
/home/runner/work/dealii/dealii/include/deal.II/grid/tria_accessor.templates.h:1699:1: error: prototype for ‘void dealii::TriaAccessor<<anonymous>, <anonymous>, <anonymous> >::set_user_pointer(const void*) const’ does not match any in class ‘dealii::TriaAccessor<<anonymous>, <anonymous>, <anonymous> >’
 TriaAccessor<structdim, dim, spacedim>::set_user_pointer(const void *p) const
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/runner/work/dealii/dealii/include/deal.II/grid/tria.h:4462:0,
                 from /home/runner/work/dealii/dealii/include/deal.II/distributed/tria_base.h:28,
                 from /home/runner/work/dealii/dealii/include/deal.II/dofs/dof_handler.h:29,
                 from /home/runner/work/dealii/dealii/include/deal.II/dofs/dof_accessor.h:22,
                 from /home/runner/work/dealii/dealii/source/numerics/data_out.cc:18:
/home/runner/work/dealii/dealii/include/deal.II/grid/tria_accessor.h:1311:3: error: candidate is: void dealii::TriaAccessor<<anonymous>, <anonymous>, <anonymous> >::set_user_pointer(void*) const
   set_user_pointer(void *p) const;
   ^~~~~~~~~~~~~~~~
```

**Comment by bangerth** [comment]
Ah, I had a dirty tab still open in my editor. Let's see about this now...

**Comment by masterleinad** [comment]
```
/jenkins/workspace/dealii-tidy_PR-13142/include/deal.II/grid/tria_accessor.templates.h:1702:55: error: assigning to 'void *' from incompatible type 'const void *' [clang-diagnostic-error]

/jenkins/workspace/dealii-tidy_PR-13142/source/grid/tria_accessor.cc:1873:31: error: out-of-line definition of 'set_user_pointer' does not match any declaration in 'TriaAccessor<0, 1, spacedim>' [clang-diagnostic-error]
```

**Comment by bangerth** [comment]
I hate working on `tria_access.h` because whenever you change something, *everything* has to be recompiled. So I tend to hope for the best when I'm working on my laptop, and oftentimes that doesn't work out :-(

Let's see whether it works now...

**Comment by bangerth** [comment]
Seems to work now.

**Pull request merged**
