### PR TITLE
Fix warning about unininitialized values in finish_integrate_fast

### LINKED ISSUE #16012: Regression tester regressed 3ba99a
[start automated regression testsuite report]

Dear all,

this is the automated regression testsuite reporting a new regression between
- new revision: 3ba99a82342e4b97c9de160be6a3a3e50414977d  [regression testsuite results](https://cdash.dealii.org/index.php?project=deal.II&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=3ba99a)
- old revision: 39ae18961b529874ed29ce3ead3b9188f1cba628  [regression testsuite results](https://cdash.dealii.org/index.php?project=deal.II&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=39ae18)

Summary:
- :disappointed: new build warnings introduced for configuration [GNU-12.2.0-master-debian-10](https://cdash.dealii.org/build/2303) on site tester-tng
- :disappointed: new build warnings introduced for configuration [GNU-12.2.0-master-debian-11](https://cdash.dealii.org/build/2302) on site tester-tng
- :disappointed: new build warnings introduced for configuration [GNU-12.2.0-master-debian-12](https://cdash.dealii.org/build/2308) on site tester-tng
- :disappointed: new build warnings introduced for configuration [GNU-12.2.0-master-ubuntu-23.04](https://cdash.dealii.org/build/2309) on site tester-tng
- :disappointed: new build warnings introduced for configuration [GNU-12.3.0-master-debian-13](https://cdash.dealii.org/build/2307) on site tester-tng
- :disappointed: new build warnings introduced for configuration [GNU-12.2.1-master-autodetection-20230116](https://cdash.dealii.org/build/2310) on site tester-tos
- :disappointed: new build warnings introduced for configuration [GNU-13.1.1-master-64bit_indices-20230507](https://cdash.dealii.org/build/2322) on site tester-tos
- :disappointed: new build warnings introduced for configuration [GNU-13.1.1-master-autodetection-20230507](https://cdash.dealii.org/build/2305) on site tester-tos
- :disappointed: new build warnings introduced for configuration [GNU-13.1.1-master-minimal-20230116](https://cdash.dealii.org/build/2320) on site tester-tos
- :disappointed: new build warnings introduced for configuration [GNU-13.1.1-master-standalone_kokkos-20230507](https://cdash.dealii.org/build/2321) on site tester-tos
- :disappointed: new build warnings introduced for configuration [GNU-13.1.1-master-std=c++20-20230626](https://cdash.dealii.org/build/2313) on site tester-tos

I have identified the following pull requests as possible candidates:
- #15971 (authored-by: @bergbauer; merged-by: @peterrum)

Notes:
 - The regression reported above is a subset of the following full set of regressions compared to the baseline:
   - :disappointed: build warnings for configuration [GNU-12.2.0-master-debian-10](https://cdash.dealii.org/build/2303) on site tester-tng
   - :disappointed: build warnings for configuration [GNU-12.2.0-master-debian-11](https://cdash.dealii.org/build/2302) on site tester-tng
   - :disappointed: build warnings for configuration [GNU-12.2.0-master-debian-12](https://cdash.dealii.org/build/2308) on site tester-tng
   - :disappointed: build warnings for configuration [GNU-12.2.0-master-ubuntu-23.04](https://cdash.dealii.org/build/2309) on site tester-tng
   - :disappointed: build warnings for configuration [GNU-12.3.0-master-debian-13](https://cdash.dealii.org/build/2307) on site tester-tng
   - :disappointed: build warnings for configuration [GNU-12.2.1-master-autodetection-20230116](https://cdash.dealii.org/build/2310) on site tester-tos
   - :disappointed: build warnings for configuration [GNU-13.1.1-master-64bit_indices-20230507](https://cdash.dealii.org/build/2322) on site tester-tos
   - :disappointed: build warnings for configuration [GNU-13.1.1-master-autodetection-20230507](https://cdash.dealii.org/build/2305) on site tester-tos
   - :disappointed: build warnings for configuration [GNU-13.1.1-master-minimal-20230116](https://cdash.dealii.org/build/2320) on site tester-tos
   - :disappointed: build warnings for configuration [GNU-13.1.1-master-standalone_kokkos-20230507](https://cdash.dealii.org/build/2321) on site tester-tos
   - :disappointed: build warnings for configuration [GNU-13.1.1-master-std=c++20-20230626](https://cdash.dealii.org/build/2313) on site tester-tos
 - I will close and unpin this issue automatically once a full run is complete and compares cleanly to the baseline.
 - If closed I will reopen the issue if the testsuite run identified an additional regression compared to what I have reported so far.

[end automated regression testsuite report]

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #16012. Alternative to #16018.

### CODE REVIEW

**Comment by masterleinad** [comment]
@bergbauer FYI This fixes the warning for me.

**Comment by masterleinad** [comment]
> Does changing from n_q_points to n_q_batches [...] also fix the warning for you? Then we would not need an additional runtime if.

No, that's not enough. Since the stacktrace has `include/deal.II/matrix_free/fe_point_evaluation.h:2548` as the last node, it seems the compiler is assuming that the function could be called from something else than `FEPointEvaluation<n_components_, dim, spacedim, Number>::do_integrate()`.

**Review by kronbichler — APPROVED** [review]
I guess we could go with this patch, if you don't see a change in performance @bergbauer?

**Pull request closed without merging**
