### PR TITLE
CMake: do not use PUBLIC keyword for target_link_libraries for tests

### PR DESCRIPTION
**Pull request by tamiko**
In reference to #14947

### CODE REVIEW

**Comment by tamiko** [comment]
@sebproell @blaisb Would you mind quickly testing this variant?

I will add support for annotating `deal_ii_setup_target` and `deal_II_pickup_tests` with keywords in a separate PR. For the time being this should fix the immediate issue - at least if you don't use keywords in your own CMake configuration.

**Comment by blaisb** [comment]
@tamiko  This solution works perfectly fine in Lethe
Thanks again, it seems like more beer is owed :)

**Comment by sebproell** [comment]
@tamiko Is there already a clear and preferred way how to bring in deal.II in the future? 

Should I just do

```
target_link_libraries(mytarget PUBLIC ${DEAL_II_LIBRARIES)
```

instead of deal_ii_setup_target?

**Comment by blaisb** [comment]
@tamiko This branch works perfectly fine it seems :). For us it's a good to go fix. Nothing needs to be changed in the user code.

**Comment by masterleinad** [comment]
> Should I just do
target_link_libraries(mytarget PUBLIC ${DEAL_II_LIBRARIES)
instead of deal_ii_setup_target?

It seems that we are at least missing adding compile options to `dealii::dealii_debug`. We should probably fix that (together with separating warning flags).

**Comment by sebproell** [comment]
> It seems that we are at least missing adding compile options to dealii::dealii_debug. 

@masterleinad I think I Just experienced that but for *release*

```
 error: #error "Mismatch in vectorization capabilities: AVX was detected during configuration of deal.II and switched on, but it is apparently not available for the file you are trying to compile at the moment. Check compilation flags controlling the instruction set, such as -march=native."
```

**Comment by sebproell** [comment]
I am doing the following workaround now to get a somewhat nice `dealii::dealii` target:

```
if(deal.II_FOUND AND NOT TARGET dealii::dealii)
  add_library(_dealii_dealii INTERFACE)
  target_link_libraries(_dealii_dealii INTERFACE ${DEAL_II_TARGET})

  # NOTE: these lines can be removed once deal.II exports the compile options correctly
  set(_flags "${DEAL_II_CXX_FLAGS}")
  separate_arguments(_flags)
  target_compile_options(_dealii_dealii INTERFACE ${_flags})

  add_library(dealii::dealii ALIAS _dealii_dealii)
else()
  message(FATAL_ERROR "Could not find the required deal.II targets.")
endif()
```

I create this extra target so I don't need to distinguish `dealii::dealii_debug` and `dealii::dealii_release` in my CMake. Might be something we could export from deal.II as well? But as @masterleinad notes I now get deal.II's warning flags (that I don't want) on all my targets :/

**Comment by masterleinad** [comment]
> I create this extra target so I don't need to distinguish `dealii::dealii_debug` and `dealii::dealii_release` in my CMake. Might be something we could export from deal.II as well? But as @masterleinad notes I now get deal.II's warning flags (that I don't want) on all my targets :/

I gave it a shot at https://github.com/dealii/dealii/pull/14971. We should address the warning flags somewhere else, though.

**Comment by tamiko** [comment]
@sebproell In the future the preferred way will be to simply use the targets `dealii:deallii(|_debug|_release)`.

For the time being not all refactoring is done, so currently `deal_ii_setup_target(...)` is still the way to go if you do not want to set up compile and link options for your project (or targets) by hand.

**Comment by tamiko** [comment]
@masterleinad The `PUBLIC` keyword that I am removing here should have never been added in the first place :-(

In the interest of backwards compatibility I suggest we simply remove the `PUBLIC` keyword here and make `deal_ii_setup_target()` behave as expected.

I like the idea to have a `dealii::dealii` target that also exports compile options instead of making the macro more complicated. But let us discuss and change this on #14971

**Comment by sebproell** [comment]
@tamiko Thanks for the hints and thanks for all the work on modern CMake! The temporary solution is fine for me.

**Review by peterrum — APPROVED** [review]

**Pull request merged**
