### PR TITLE
fix parpack unit test

### PR DESCRIPTION
**Pull request by davydden**
fixes https://github.com/dealii/dealii/issues/4700

@masterleinad please check if this is indeed the case for you.

### CODE REVIEW

**Comment by masterleinad** [comment]
No, this doesn't fix the test for me. I still get
> 931: arpack/step-36_parpack_mf_02.mpirun=3.debug: DIFF failed. ------ First 8 lines of numdiff/diff output:
931: ----------------
931: ##1       #:2   <== 5931.69
931: ##1       #:2   ==> 5866.90
931: @ Absolute error = 6.4790000000e+1, Relative error = 1.1043310777e-2
931: ----------------
931: ##2       #:2   <== 5970.26
931: ##2       #:2   ==> 5931.69
931: @ Absolute error = 3.8570000000e+1, Relative error = 6.5023627330e-3
931: arpack/step-36_parpack_mf_02.mpirun=3.debug: DIFF failed. ------ First 50 lines diff output:
931: *** /mnt/data/darndt/Sources/dealii-gcc-7/tests/arpack/step-36_parpack_mf_02.with_mpi=true.with_p4est=true.with_arpack_with_parpack=true.mpirun=3.output	Wed Aug  9 22:17:24 2017
931: --- output	Sun Aug 13 19:28:40 2017
931: ***************
931: *** 1,6 ****
931:   DEAL::5931.69
931:   DEAL::5970.26
931:   DEAL::6035.05
931: - DEAL::6035.05
931:   DEAL::6099.84
931:   DEAL::Ok
931: --- 1,6 ----
931: + DEAL::5866.90
931:   DEAL::5931.69
931:   DEAL::5970.26
931:   DEAL::6035.05
931:   DEAL::6099.84
931:   DEAL::Ok

**Comment by davydden** [comment]
@masterleinad damn it, but that's a different flavour, meaning you get `6035` twice, but the 5th one is wrong... can you try locally further increase the number of arnoldi vectors?

**Comment by masterleinad** [comment]
``` const unsigned int num_arnoldi_vectors = 2*eigenvalues.size() + 40;``` works for me. Does it make sense to choose such a large value?

**Comment by davydden** [comment]
> Does it make sense to choose such a large value? 

frankly, I am not sure. I am surprised that it's so sensitive. I will update it to `40`...

**Comment by davydden** [comment]
the purpose of this test is to get the same values as from `SLEPc` and thereby confirm that interface to PArpack for mode `2` is working. So i would not bother to much about increasing the number further.

**Pull request merged**
