### PR TITLE
Update minimum compiler versions for C++17

### PR DESCRIPTION
**Pull request by masterleinad**
In reference to https://github.com/dealii/dealii/issues/15659#issuecomment-1622525032.

### CODE REVIEW

**Review by Rombur — APPROVED** [review]

**Review by bangerth — APPROVED** [review]

**Review by tamiko — APPROVED** [review]

**Comment by tamiko** [comment]
Beats me how this change can affect the Jenkins MPI variant (*ping* @tjhei : did you update the jenkins container?)
```
examples/step-40.mpirun=2.debug: BUILD successful.
examples/step-40.mpirun=2.debug: RUN successful.
examples/step-40.mpirun=2.debug: DIFF failed. ------ Source: /home/dealii/build/tests/examples/source/step-40.mpirun=2.with_p4est=true.with_petsc=true.output
examples/step-40.mpirun=2.debug: DIFF failed. ------ Result: /home/dealii/build/tests/examples/binary/step-40.debug/mpirun=2/output
Check /home/dealii/build/tests/examples/binary/step-40.debug/mpirun=2/output /home/dealii/build/tests/examples/source/step-40.mpirun=2.with_p4est=true.with_petsc=true.output
examples/step-40.mpirun=2.debug: DIFF failed. ------ Diff:   /home/dealii/build/tests/examples/binary/step-40.debug/mpirun=2/failing_diff
examples/step-40.mpirun=2.debug: DIFF failed. ------ First 20 lines of numdiff output:
----------------
##11      #:4   <== 8
##11      #:4   ==> 8Solver
@                                                     @@
##11      #:5   <== -
##11      #:5   ==> stopped
@                                                     @@
##11      #:6   <== 15
##11      #:6   ==> within
@                                                     @@
##11      #:7   <== iterations
##11      #:7   ==> 8
@                                                     @@
##11            <==
##11      #>8   ==> - 15 iterations
@ Line 11 in file "/home/dealii/build/tests/examples/source/step-40.mpirun=2.with_p4est=true.with_petsc=true.output" is shorter than expected!
----------------
##12      #:1   <== Solver
##12      #:1   ==> -
@                                                     @@


examples/step-40.mpirun=2.debug: ******    DIFF failed    *******
```

We should fix this text.

**Comment by tjhei** [comment]
No change on my side.

**Comment by tjhei** [comment]
Is this a race condi of std out?

**Comment by tamiko** [comment]
@tjhei It sure is.

**Comment by bangerth** [comment]
It seems to be happening on a lot of PRs. We *should* fix this.

**Pull request merged**
