### PR TITLE
PETSc nonlinear solver and ODE integrator

### PR DESCRIPTION
**Pull request by stefanozampini**
@bangerth This is the final PR with the solvers

### CODE REVIEW

**Review by peterrum — COMMENTED** [review]
@stefanozampini Thank you for the additions! May I ask you to split up the PR: nonlinear solver vs. ODE.

Regarding the tutorials. As stated somewhere else, I am not particular fond of adding a new topic to step-67, which focuses on matrix-free evaluation of a multi-component problem. Also adding a new version of step-15 is not something I like. Personally, I think step-77 should be extended to show alongside of KINSOL also NOX and SNES. Everything else will be a maintenance hell. Let's see what other have to say about this topic. I am particular picky about the last topic, since I am not a fan of adding a new tutorial number for every version of a code. If adding everything to the same code is not an option, than a/b/... or something similar (as in MFEM) would be still better.

**Comment by stefanozampini** [comment]
> Thank you for the additions! May I ask you to split up the PR: nonlinear solver vs. ODE.

I'd prefer to keep them together. The interfaces have so much in common, that any change we decide for one can go to the other. 

> Regarding the tutorials. As stated somewhere else, I am not particular fond of adding a new topic to step-67, which focuses on matrix-free evaluation of a multi-component problem.

As stated in step-67 docs, the PETSc code path shows the simplicity of going from one interface to another. I can drop it, but then there will be no tutorial example, only tests, and you know better than me that most users do not read them, or even search to find programming advice.

> I think step-77 should be extended to show alongside of KINSOL also NOX and SNES. Everything else will be a maintenance hell. 

I kind of agree with that; however, there are differences between packages that sometimes cannot be ignored. Also, IMHO deal.II first needs a unified and complete abstract interface for vectors that is not there yet. See also my comments on step-67 .

**Comment by luca-heltai** [comment]
Could you add also the output of the tests obtained by running with 2 or 3 mpi processes? 

This is easily done by copying the `output` file obtained with mpi to `test_xx.mpirun=3.output`.

**Comment by luca-heltai** [comment]
> > Thank you for the additions! May I ask you to split up the PR: nonlinear solver vs. ODE.
> 
> I'd prefer to keep them together. The interfaces have so much in common, that any change we decide for one can go to the other.
> 
> > Regarding the tutorials. As stated somewhere else, I am not particular fond of adding a new topic to step-67, which focuses on matrix-free evaluation of a multi-component problem.
> 
> As stated in step-67 docs, the PETSc code path shows the simplicity of going from one interface to another. I can drop it, but then there will be no tutorial example, only tests, and you know better than me that most users do not read them, or even search to find programming advice.
> 
> > I think step-77 should be extended to show alongside of KINSOL also NOX and SNES. Everything else will be a maintenance hell.
> 
> I kind of agree with that; however, there are differences between packages that sometimes cannot be ignored. Also, IMHO deal.II first needs a unified and complete abstract interface for vectors that is not there yet. See also my comments on step-67 .

Your call about splitting... keep in mind that it will take people more effort to go through the PR if you don't split this, and, as a consequence, it will take a lot more time to get this merged.

Instead, if you split this, the guys that are familiar with non-linear solver interfaces we have can look at one, and those that are familiar with the ODE interfaces we have will look at the other. These two groups are not always overlapping, and may not have the time/will/patience to go through the full PR if it is not split. 

I know the time you can allocate to deal.II is limited. If you want, I can take care of the splitting.

**Pull request closed without merging**
