### PR TITLE
move mapping tests from tests/bits to tests/mappings.

### PR DESCRIPTION
**Pull request by drwells**
Follow up to #2766.

### CODE REVIEW

**Comment by bangerth** [comment]
Since `fe/` is already the second biggest directory, and given #1581, how about creating a separate directory for the mapping tests?

**Comment by drwells** [comment]
Good idea.

**Comment by drwells** [comment]
Okay, they now live in the `tests/mappings/` directory.

**Comment by bangerth** [comment]
In reference to #1581.

**Pull request merged**
