### PR TITLE
Add a comment to GridTools::transform().

### PR DESCRIPTION
**Pull request by bangerth**
In response to looking at the comment at the top of #7441.

### CODE REVIEW

**Comment by jppelteret** [comment]
@drwells I guess this relates to a comment you made. Are you happy with what's written here? If so, we can merge this :-)

**Comment by bangerth** [comment]
I actually like the spaces at the beginning of the line, and we've done this in many many other places as well. It makes it clear that the whole paragraph is subservient to the `@note` tag.

**Comment by drwells** [comment]
Thats a good point. I only brought it up since the next paragraph is indented in a different way.

**Comment by drwells** [comment]
Since this just updates documentation lets merge :)

**Comment by bangerth** [comment]
Yes, I had toyed with the idea of indenting the next paragraph as well but then didn't want to mix different things in one patch...

**Pull request merged**
