### PR TITLE
Allow compilation with PETSc but without MPI.

### PR DESCRIPTION
**Pull request by bangerth**
I don't have a setup to test this, though. Let's see whether we can get confirmation from Tomáš Levý, who reported the problem on the mailing list.

### CODE REVIEW

**Review by tjhei — COMMENTED** [review]
My vote would be to disallow usage of PETSc when configuring without MPI.

**Comment by bangerth** [comment]
I could live with this, though I will point out that people use PETSc not only for its parallel capabilities, but also for eigenvalue problems (SLEPc), and now for its time steppers and nonlinear solvers. All of these also work without MPI. (They *also* work *with* MPI, and so there is little harm telling people to configure with MPI and then just not use it.)

**Comment by masterleinad** [comment]
> My vote would be to disallow usage of PETSc when configuring without MPI.

I agree. I don't think this is too much to ask of users and is also consistent with how we treat `Trilinos`.

**Comment by bangerth** [comment]
As reported on the mailing list, this seems to work. My suggestion is to go with it. (If approved, I will also create a version for the 9.5 branch.)

**Comment by tjhei** [comment]
My reason for not allowing this configuration is that we have 0 CI or regression tester coverage and none of the developers uses it. It is likely to break again (if it works at all in the first place).

**Review by tamiko — APPROVED** [review]

**Comment by tamiko** [comment]
Let us merge this PR as is and apply it to the release branch.

But for the future I agree with @tjhei - In principle we could add a PETSc without MPI variant ot the regression tester. But I don't think that the increased (we currently use 8-10h out of a budget of 12h on `tester-tos`) is worth the benefit.

Also, Debian/Ubuntu has a packaged PETSc available with MPI support enabled. So it is really a very minor ask for a user to either install this package - or if they want to have a newer one - to install build dependencies: `apt build-dep petsc slepc` and configure petsc/slepc with MPI support enabled.

**Pull request merged**
