### PR TITLE
Fix evenb typo.

### PR DESCRIPTION
**Pull request by drwells**

### CODE REVIEW

**Comment by tjhei** [comment]
looks good!

**Comment by bangerth** [comment]
Yes, this looks great. Thanks for fixing the typo!

/rebuild

**Comment by masterleinad** [comment]
This is just documentation. No need to run `CI`.

**Comment by tamiko** [comment]
I agree.

**Comment by luca-heltai** [comment]
Actually, could you please move both lines a bit to the right, to improve readability?

**Comment by luca-heltai** [comment]
Actually, could you please move both lines a bit to the right, to improve readability?

**Pull request merged**
