### PR TITLE
Improve mesh quality of quarter hyper ball

### PR DESCRIPTION
**Pull request by kronbichler**
This PR is a preparation for #8198 .

I observed that the mesh quality of the `quarter_hyper_ball` functions are not as good as they could be. Thus, I adjusted the relevant parameters a bit, producing the picture on the right (left is the old variant):
  

The 3D pictures changed like this:
  

The idea of choosing the point is to equilibrate the minimal singular value of the Jacobian in the crossing point between the 3 cells. If we agree on this, I will add the new pictures to the documentation of the class.

### CODE REVIEW

**Comment by drwells** [comment]
I think we should add a changelog entry since this is technically an incompatibility.

**Comment by tamiko** [comment]
@drwells But a very minor one. We had more severe changes in our mesh generators in the past.
But yes, maybe a minor changes changelog entry?

**Comment by kronbichler** [comment]
I added a changelog entry and the two new pictures for the manual.

**Comment by kronbichler** [comment]
I have adapted the output of the two affected tests as well.

**Pull request merged**
