### PR TITLE
Use more 'if constexpr' in the matrix-free code.

### PR DESCRIPTION
**Pull request by drwells**
This doesn't significantly help compile times right now:
- with patch and make -j2 object_matrix_free_release: 17:15
- on master and make -j2 object_matrix_free_release: 17:08

but I suspect it will help us clean things up in other ways in the future.

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]
This looks good to me. I have a patch locally that will conflict with this one (not sure if I manage to finish it today), but let's go with this one first either way.

**Comment by kronbichler** [comment]
You get some warnings about unused variables now with `if constexpr`. This requires some extra work, but it is one of the cleanups down the road you mentioned.

**Comment by drwells** [comment]
It looks like some versions of GCC consider variables unused in the following case:
```cpp
int a = 42;
if constexpr (cond)
  {
    std::cout < "a = " << a << std::endl;
  }
else
  {
    std::cout << "no a" << std::endl;
  }
```
I think I fixed all of them.

**Comment by marcfehling** [comment]
There are a few more:

```
include/deal.II/matrix_free/evaluation_kernels_hanging_nodes.h:1558:12: error: variable ‘vv’ set but not used [-Werror=unused-but-set-variable]
 1558 |               const auto vv =
      |            ^ 
include/deal.II/matrix_free/evaluation_kernels_hanging_nodes.h:1537:16: error: variable ‘given_degree’ set but not used [-Werror=unused-but-set-variable]
 1537 |       const unsigned int given_degree =
      |                ^~~~~~~~~~~~
```

```
include/deal.II/matrix_free/evaluation_kernels_hanging_nodes.h:194:38: error: variable ‘weights‘ set but not used [-Werror=unused-but-set-variable]
  194 |       const Number *DEAL_II_RESTRICT weights =
      |                                      ^~~~~~~
include/deal.II/matrix_free/evaluation_kernels_hanging_nodes.h:189:53: error: parameter ‘values‘ set but not used [-Werror=unused-but-set-parameter]
  189 |       Number                                       *values)
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
```

**Comment by drwells** [comment]
It's interesting that they fixed this in newer versions of GCC - I'll see if I can find an older one which prints out all of these warnings.

**Comment by bangerth** [comment]
I mean it's not wrong -- the variable really *is* unused!

**Comment by kronbichler** [comment]
This is now in a bit of a stale state, with several conflicts from (my) pull requests doing some refactoring. @drwells do you need some help here, or how should we proceed?

**Comment by drwells** [comment]
I haven't had time to work on this recently and it's a low-priority improvement - lets just close this one and keep refactoring bit-by-bit.

**Pull request closed without merging**
