### PR TITLE
Removed ansi flag from intel compiler setup

### PR DESCRIPTION
**Pull request by nabw**
Small PR to remove -ansi flag from intel compiler, which conflicts with c++14 and thus does not allow for configuration.

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
Looks good! Also, see https://godbolt.org/z/n87nvd.

**Review by tamiko — APPROVED** [review]

**Comment by nabw** [comment]
> Looks good! Also, see https://godbolt.org/z/n87nvd.

fantastic reference, I had no idea about this. Thanks!

**Comment by bangerth** [comment]
Took us only 18 years to realize that C++ is no longer standardized by ANSI but by ISO ;-)

**Pull request merged**
