### PR TITLE
Improve an error message.

### PR DESCRIPTION
**Pull request by bangerth**
Based on a recent inquiry on the mailing list.

### CODE REVIEW

**Comment by drwells** [comment]
I think that there is a grammatical problem with this sentence: shouldn't it be "you cannot pass ... unless the Triangulation is embedded in a higher space"?

**Comment by bangerth** [comment]
Hm. I think it's correct the way it's written -- the error message is produced by the `FEValues` class. The error message tries to point out that you can pass this flag only to the *related* classes `FE{Face,Subface}Values` but not `FEValues`, *unless* the latter refers to an embedded domain.

**Comment by bangerth** [comment]
What do you think of this version?

**Comment by bangerth** [comment]
(I made the edit with the online github editor because I don't have a clean tree right now locally. If you wanted to merge this version, feel free to merge-after-squash.)

**Comment by drwells** [comment]
You are correct (there was nothing wrong with the original error message).

This revised error message is a lot easier to understand; thanks!

**Pull request merged**
