### PR TITLE
Fix a rather insidious bug in MappingQ.

### LINKED ISSUE #2469: Error when plotting curved interior cells with vtk
As reported here, https://groups.google.com/forum/#!topic/dealii/_uk1JDakBLc , there is a bug somewhere in `DataOut::build_patches` or `DataOut::build_one_patch` when using curved geometries. My best guess is that we compute the location of points on the edges of the inner square using the manifold of the square, rather than the manifold of the edge. This then leads us to assume straight edges for the inner square but curved edges for the outer cells.

Test program by Sebastian Gonzalez-Pintor:

```

// Testing grids with Manifolds by approximating pi.

#include <deal.II/base/quadrature_lib.h>
#include <deal.II/base/convergence_table.h>

#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/tria_accessor.h>
#include <deal.II/grid/tria_iterator.h>
#include <deal.II/grid/tria_boundary_lib.h>
#include <deal.II/grid/tria.h>
#include <deal.II/grid/manifold_lib.h>
#include <deal.II/grid/grid_out.h>

#include <deal.II/dofs/dof_handler.h>
#include <deal.II/dofs/dof_accessor.h>

#include <deal.II/fe/fe_q.h>
#include <deal.II/fe/fe_values.h>
#include <deal.II/fe/mapping_q.h>

#include <deal.II/numerics/data_out.h>

// And this again is C++:
#include <iostream>
#include <fstream>
#include <cmath>

using namespace dealii;
using namespace std;

// mainly Step-10 without computing the perimeter
namespace Step10
{
  using namespace dealii;

  const long double pi = 3.141592653589793238462643;
  const double inner_radius = 1./(1. + std::sqrt(2));
  const double true_inner_area = pi*std::pow(inner_radius,2);
  const double true_outer_area = pi - true_inner_area;

  void compute_pi_by_area (const unsigned int n_degree)
  {
    std::cout << "Computation of Pi by the area:" << std::endl
              << "==============================" << std::endl;
    printf("[deg] \t[ TArea ] \t[TA - PI] \t[err(OA)] \t[err(IA)]\n\n");

    Vector<double> zeros;

    const Point<2> center (0,0);
    const SphericalManifold<2> boundary_description (center);

    for (unsigned int degree=1; degree <= n_degree; ++degree)
    {
        const QGauss<2> quadrature(degree);
        Triangulation<2> triangulation;
        GridGenerator::hyper_ball (triangulation, Point< 2 >(0.0,0.0), 1.0 );

        const MappingQ<2> mapping (degree, true);
        const FE_Q<2>     dummy_fe (1);
        DoFHandler<2> dof_handler (triangulation);
        FEValues<2> fe_values (mapping, dummy_fe, quadrature,
                             update_quadrature_points | update_JxW_values);

        for (Triangulation<2>::active_cell_iterator
          cell = triangulation.begin_active(); cell!=triangulation.end(); ++cell) 
          {
            if (cell->center().square() < 1.e-5)
              cell->set_material_id(1);
            else
              cell->set_material_id(0);
          }

        Triangulation<2>::active_cell_iterator
          cell = triangulation.begin_active(),
          endc = triangulation.end();

        for (; cell!=endc; ++cell) 
          if (cell->material_id() != 1)
            cell->set_all_manifold_ids (100);

        triangulation.set_manifold (100, boundary_description);

        dof_handler.distribute_dofs (dummy_fe); 

        zeros.reinit(triangulation.n_active_cells());
        cell = dof_handler.begin_active();
        for (unsigned int i = 0; cell!=endc; ++cell, ++i)
        {
          zeros[i] = static_cast<double>(cell->material_id());
        }

        double area_inner = 0;
        double area_outer = 0;
        cell = dof_handler.begin_active();
        for (; cell!=endc; ++cell)
        {
          fe_values.reinit (cell);
          for (unsigned int i=0; i < fe_values.n_quadrature_points; ++i)
          {
            if (cell->material_id() == 1)
              area_inner += fe_values.JxW (i);
            else
            area_outer += fe_values.JxW (i);
          }
        }
        const double area_total = area_outer + area_inner;

        printf(" %d \t%.3e \t%.3e \t%.3e \t%.3e\n",
               degree,
               (double)area_total,
               (double)std::fabs(pi - area_total),
               (double)(area_outer - true_outer_area),
               (double)(area_inner - true_inner_area));

        { // plotting the grid
          DataOut<2> data_out;
          data_out.attach_dof_handler (dof_handler);
          std::ostringstream ss;              
          ss <<  "d2" << "_p" << degree;
          data_out.add_data_vector (zeros, std::string("grid") );
          std::ofstream o_vtk ( ss.str() + ".vtk" );
          data_out.build_patches (mapping, 5, DataOut<2>::curved_inner_cells );
          data_out.write_vtk (o_vtk);
        }
    } // end for degree
  printf("\n");
  } // end compute_pi_by_area

} // end namespace

int main ()
{
  try
    {
      std::cout.precision (16);

      const unsigned int n_degree = 4;

      Step10::compute_pi_by_area (n_degree);
    }
  catch (std::exception &exc)
    {
      std::cerr << std::endl << std::endl
                << "----------------------------------------------------"
                << std::endl;
      std::cerr << "Exception on processing: " << std::endl
                << exc.what() << std::endl
                << "Aborting!" << std::endl
                << "----------------------------------------------------"
                << std::endl;

      return 1;
    }
  catch (...)
    {
      std::cerr << std::endl << std::endl
                << "----------------------------------------------------"
                << std::endl;
      std::cerr << "Unknown exception!" << std::endl
                << "Aborting!" << std::endl
                << "----------------------------------------------------"
                << std::endl;
      return 1;
    }
  return 0;
}
```

### PR DESCRIPTION
**Pull request by bangerth**
Calling MappingQ::clone() did not copy the
 use_mapping_q_on_all_cells flag that this
 mapping class gets passed to its constructor. This leads
 to wrong results if you wanted to use curved cells on
 interior cells and if such an object was used inside an
 hp::MappingCollection, for example. There are, in addition,
 several places in the library where one would pass a mapping,
 and the library would clone it into a member of such a collection,
 and these would also yield wrong results. An example is the use
 of DataOut::build_patches with a mapping that had this flag set
 upon construction.

This fixes at least #2469, but I could imagine that it also fixes a number
of other issues that are related to mappings and where we put a mapping
into an hp::MappingCollection (possibly internally in the library).

Fixes #2469.

### CODE REVIEW

**Comment by bangerth** [comment]
A couple of hours of debugging for a one-line change...

**Comment by tjhei** [comment]
> A couple of hours of debugging for a one-line change...

Ugh, I hope it was satisfying when you figured out how simple the fix is. :-)

**Comment by bangerth** [comment]
Very :-)

Give me a minute, I'm going to add a second test that also works in 3d.

**Comment by bangerth** [comment]
OK, 3d testcase now also here.

**Pull request merged**
