### PR TITLE
Boost develop patches

### PR DESCRIPTION
**Pull request by drwells**
I spent some time going through the recent changes to the boost libraries we use (including some development patches) and I extracted these changes.

The patches that were not also a part of 1.63 are all pretty trivial. I avoided adding any new features, just bug fixes, to keep this simple.

### CODE REVIEW

**Comment by bangerth** [comment]
I see no reason not to merge any of these, except that we haven't typically done this -- we just updated the entire boost library every once in a while. I assume you had a reason why you were looking at the boost patches?

**Comment by drwells** [comment]
To be honest, I was looking at #3924 and other recent changes to the serialization library and I then decided to also check the parameter tree and signals libraries, and things snowballed from there.

**Comment by tjhei** [comment]
I have a similar comment: if we merge this we are no longer technically bundling boost-1.62.

**Comment by drwells** [comment]
These are good points.

I think that, since we have not had any problems due to these patches, we are probably better off not shipping something that is not quite 1.62. Lets close this for now: if something comes up later we can just cherry pick this.

**Comment by bangerth** [comment]
I'm not opposed to the patch, just wanted to raise the question.

I'm nervous to change these kinds of things just before a release (assuming that we are actually moving towards one). What would you think of applying the patch immediately after the release? That would give us time to see whether things work.

**Pull request closed without merging**
