### PR TITLE
Fix symmetric_tensor_39.cc for non C++11 compilers

### PR DESCRIPTION
**Pull request by masterleinad**

### CODE REVIEW

**Comment by jppelteret** [comment]
What was the "non-c++11" part of this PR?

**Comment by masterleinad** [comment]
`std::ofstream` does not accept `std::string` as parameter before C++11.

**Comment by davydden** [comment]
indeed http://www.cplusplus.com/reference/fstream/ofstream/ofstream/

**Comment by jppelteret** [comment]
Cool, thanks! I (re-)learned something today :-)

**Pull request merged**
