### PR TITLE
Document exception behavior for threads.

### PR DESCRIPTION
**Pull request by bangerth**
I apparently wrote this patch quite a while ago and forgot to submit it. 

/rebuild

### CODE REVIEW

**Comment by drwells** [comment]
I am trying to understand this patch and I think I am missing something.

- `Thread::return_value()` calls `Thread::join()`
- `Thread::join()` calls `ThreadDescriptor::join()`
- `ThreadDescriptor::join()` calls `std::thread::join()`
- According to at least https://en.cppreference.com/w/cpp/thread/thread/join `std::thread::join()` doesn't throw these kinds of exceptions (it will throw if we try to join twice).

where does the exception actually get thrown?

**Comment by bangerth** [comment]
You are right. It appears that there is a reason why I hadn't submitted the patch :-)

My belief was probably that `std::thread` allows one to extract a `std::future`, which stores exceptions. But that isn't apparently the case. It might be nice if it did, though I'm not sure it's worth the effort to come up with a scheme to store exceptions thrown on subsidiary threads, and then re-throw them whenever someone calls `join()`. Thoughts?

**Comment by drwells** [comment]
We could do this with `std::exception_ptr`. I think it's the right thing to do if we already do it for futures.

**Comment by bangerth** [comment]
Let's close this. The `Threads::Thread` class along with all of the `new_thread()` functions (see #13116) are deprecated. It is not worth working on extending functionality of the existing classes.

**Pull request closed without merging**
