### PR TITLE
Fix compilation with complex-valued PETSc

### PR DESCRIPTION
**Pull request by masterleinad**
Currently, there are some issues when building with complex-valued PETSc as also reported here.
- The `Sundials` interface seems to be incompatible with complex-valued types, so simply disable the offending methods.
- `FETools::convert_generalized_support_point_values_to_dof_values` is instantiated by `FETools::interpolate` for `PETScVector::scalar_type`. This currently causes `undefined references` as was also observed in https://groups.google.com/forum/#!topic/dealii/YC5kB_2tipk. This PR provides a suitable version for `std::complexy<number>` by just splitting the work into the imaginary and the real part.

### CODE REVIEW

**Comment by bangerth** [comment]
What is supposed to happen when you use SUNDIALS with complex PETSc? Does SUNDIALS even support that and our interfaces just don't?  Right now you'll just get a linker error.

**Comment by masterleinad** [comment]
> Right now you'll just get a linker error.

Actually, you get compile errors like
```
source/sundials/copy.cc:126:30: error: assigning to 'realtype' (aka 'double') from incompatible type 'PetscScalar' (aka 'complex<double>')
          NV_Ith_P(dst, i) = src[is.nth_index_in_set(i)];
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
source/sundials/copy.cc:147:30: error: assigning to 'realtype' (aka 'double') from incompatible type 'value_type' (aka 'complex<double>')
          NV_Ith_P(dst, i) = src[is.nth_index_in_set(i)];
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
source/sundials/copy.cc:126:30: error: assigning to 'realtype' (aka 'double') from incompatible type 'PetscScalar' (aka 'complex<double>')
          NV_Ith_P(dst, i) = src[is.nth_index_in_set(i)];
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
source/sundials/copy.cc:147:30: error: assigning to 'realtype' (aka 'double') from incompatible type 'value_type' (aka 'complex<double>')
          NV_Ith_P(dst, i) = src[is.nth_index_in_set(i)];
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by masterleinad** [comment]
In the end, it is the type `realtype` defined by Sundials in `sundials_types.h` that is conflicting here.
If I read this file correctly, it can either be `float`, `double` or `long double`. I also can't find `complex` in the sundials folder or in the documentation of one the packages, but I am clearly not the expert here.
 
Maybe, @luca-heltai can shed some light on this.

**Comment by bangerth** [comment]
With "right now" I meant "with your current patch": you can create such an object even if you've configured PETSc with complex numbers, but because the class is not instantiated in that case, you'll just get a linker error after your patch. 

If SUNDIALS doesn't support complex numbers, then there is clearly nothing we can do about it. I was just wondering whether there may be a better error message than a linker error. Maybe we should put a `static_assert` into the SUNDIALS class that checks that if we configured with PETSc, the PETScScalar type is a real type?

**Comment by masterleinad** [comment]
> With "right now" I meant "with your current patch": you can create such an object even if you've configured PETSc with complex numbers, but because the class is not instantiated in that case, you'll just get a linker error after your patch.

Sorry, I totally misunderstood what you meant. Still, this patch removes `SUNDIALS::internal::copy` for `PETScWrappers::MPI::Vector` and `PETScWrappers::MPI::BlockVector` completely. Hence, the result would rather be `no matching function` than `undefined reference`.

Now, I put a `static_assert` into the `IDA` and `ARKode` class to check for `PETSc` complex scalar type. Since the `copy` functions are only designed for internal use that should hopefully be sufficient.

**Comment by bangerth** [comment]
Yes, great. Thank you!

**Pull request merged**
