### PR TITLE
Make channel limits consistent.

### PR DESCRIPTION
**Pull request by drwells**
This class uses the MPI partitioner that is okay with channel numbers up to 200.

### CODE REVIEW

**Comment by tjhei** [comment]
I think I did this on purpose, see https://github.com/dealii/dealii/blob/d780fd0cc4fb6388987f2ec0b841783bebc77d1b/include/deal.II/lac/la_parallel_block_vector.templates.h#L262-L267

Can you add an assert that the value is <=100 in the code here, instead?

**Comment by drwells** [comment]
Ah - makes sense. Fixed!

**Comment by drwells** [comment]
I just force pushed another change to use `AssertIndexRange`.

**Comment by kronbichler** [comment]
This causes some test failures like the one here:
https://cdash.43-1.org/testDetails.php?test=28781764&build=3829
We need to increase the limit to 200 because block vectors use the range between 100 and 200 and we cannot know from within the vectors if they are used in separation or as part of a block vector.

**Comment by drwells** [comment]
I'll push a quick fix.

**Pull request merged**
