### PR TITLE
Instantiate make_periodicity_constraints for all scalar numbers

### PR DESCRIPTION
**Pull request by kronbichler**
Alternative to #13651. This attempts to instantiate for all numbers we instantiate `AffineConstraints`. FYI @NiklasWik

### CODE REVIEW

**Comment by NiklasWik** [comment]
Ah! It was just `number(1.)`..

**Comment by kronbichler** [comment]
At least for my compiler, but other compilers might possibly interpret things differently.

**Review by jppelteret — APPROVED** [review]

**Comment by jppelteret** [comment]
Thanks @NiklasWik and @kronbichler for the extension!

**Comment by tamiko** [comment]
Very nice! And I always thought we'd have to get the interpolation matrices casted to float as well.

**Pull request merged**
