### PR TITLE
Add the PETSc SNES version of step-77 as a test.

### PR DESCRIPTION
**Pull request by bangerth**
This is mostly taken from #15067 and only lightly adapted to fit into the test suite. The test runs for <10 seconds.

### CODE REVIEW

**Comment by bangerth** [comment]
Now also with versions that run on one and two processes.

**Comment by bangerth** [comment]
The one failing check is the unrelated test case that's currently broken in master.

**Review by peterrum — APPROVED** [review]

**Comment by masterleinad** [comment]
@bangerth I get
```
5470: [0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
5470: [0]PETSC ERROR: See https://petsc.org/release/overview/linear_solve_table/ for possible LU and Cholesky solvers
5470: [0]PETSC ERROR: Could not locate a solver type for factorization type LU and matrix type mpiaij.
5470: [0]PETSC ERROR: See https://petsc.org/release/faq/ for trouble shooting.
5470: [0]PETSC ERROR: Petsc Release Version 3.19.2, Jun 01, 2023 
5470: [0]PETSC ERROR: /Users/6da/Software/dealii_new/build/tests/petsc/step-77-snes.debug/step-77-snes.debug on a  named MAC132268 by 6da Mon Jun 19 09:36:32 2023
5470: [0]PETSC ERROR: Configure options --prefix=/opt/homebrew/Cellar/petsc/3.19.2 --with-debugging=0 --with-scalar-type=real --with-x=0 --CC=mpicc --CXX=mpicxx --FC=mpif77 --FC=mpif90 MAKEFLAGS=$MAKEFLAGS
5470: [0]PETSC ERROR: #1 MatGetFactor() at /private/tmp/petsc-20230531-55000-2zpjx7/petsc-3.19.2/src/mat/interface/matrix.c:4739
5470: [0]PETSC ERROR: #2 PCSetUp_LU() at /private/tmp/petsc-20230531-55000-2zpjx7/petsc-3.19.2/src/ksp/pc/impls/factor/lu/lu.c:80
5470: [0]PETSC ERROR: #3 PCSetUp() at /private/tmp/petsc-20230531-55000-2zpjx7/petsc-3.19.2/src/ksp/pc/interface/precon.c:994
5470: [0]PETSC ERROR: #4 PCApply() at /private/tmp/petsc-20230531-55000-2zpjx7/petsc-3.19.2/src/ksp/pc/interface/precon.c:438
5470: [0]PETSC ERROR: #5 vmult() at /Users/6da/Software/dealii_new/source/lac/petsc_precondition.cc:1140
5470: [0]PETSC ERROR: #6 PCApply_Shell() at /private/tmp/petsc-20230531-55000-2zpjx7/petsc-3.19.2/src/ksp/pc/impls/shell/shellpc.c:110
5470: [0]PETSC ERROR: #7 PCApply() at /private/tmp/petsc-20230531-55000-2zpjx7/petsc-3.19.2/src/ksp/pc/interface/precon.c:441
5470: [0]PETSC ERROR: #8 KSP_PCApply() at /private/tmp/petsc-20230531-55000-2zpjx7/petsc-3.19.2/include/petsc/private/kspimpl.h:381
5470: [0]PETSC ERROR: #9 KSPSolve_PREONLY() at /private/tmp/petsc-20230531-55000-2zpjx7/petsc-3.19.2/src/ksp/ksp/impls/preonly/preonly.c:21
5470: [0]PETSC ERROR: #10 KSPSolve_Private() at /private/tmp/petsc-20230531-55000-2zpjx7/petsc-3.19.2/src/ksp/ksp/interface/itfunc.c:898
5470: [0]PETSC ERROR: #11 KSPSolve() at /private/tmp/petsc-20230531-55000-2zpjx7/petsc-3.19.2/src/ksp/ksp/interface/itfunc.c:1070
5470: [0]PETSC ERROR: #12 SNESSolve_NEWTONLS() at /private/tmp/petsc-20230531-55000-2zpjx7/petsc-3.19.2/src/snes/impls/ls/ls.c:219
5470: [0]PETSC ERROR: #13 SNESSolve() at /private/tmp/petsc-20230531-55000-2zpjx7/petsc-3.19.2/src/snes/interface/snes.c:4644
5470: libc++abi: terminating with uncaught exception of type dealii::LACExceptions::ExcPETScError: 
```
for this test. Do you still know how you configured `PETSc` so that you could use a LU preconditioner with parallel matrices? https://petsc.org/release/overview/linear_solve_table/ shows that you would need `MKL` or `CPardiso`.

**Comment by bangerth** [comment]
I have no idea what is happening here. This works just fine on my laptop. What is happening for others? Check what happens with
```
> ctest -V -R petsc/step-77-snes.mpirun=2.debug
```

**Comment by stefanozampini** [comment]
@masterleinad You need `superludist` or `mumps` support for parallel LU.

**Pull request merged**
