### PR TITLE
Bugfix: Make icc happy, do not use undefined macros in vecrotization check

### PR DESCRIPTION
**Pull request by tamiko**
This hopefully fixes
  https://cdash.kyomu.43-1.org/viewBuildError.php?buildid=7569

### CODE REVIEW

**Comment by kronbichler** [comment]
I have seen this error but could not reproduce it on my machine (with version 16, I have not checked version 17). Was this on a clean install? I don't understand why intel does not detect `__AVX__`. Should it be `__AVX` instead? If yes, we might change the checks into `defined(__AVX__) || defined(__AVX)`. Could you please try that?

**Comment by bangerth** [comment]
This seems like the wrong workaround. Doesn't the fact that we get the error message mean that AVX isn't enabled for this build, although we thought that it would?

**Comment by kronbichler** [comment]
@bangerth The problem is that our detection in cmake does not explicitly look for the definition `__AVX__` but rather that the intrinsics from AVX we are using are functional. I thought that all compilers would define the preprocessor macro `__AVX__` but I was wrong apparently (interestingly, some Intel compilers do define them, like mine).

**Comment by bangerth** [comment]
But then aren't we still inconsistent in some way? If even between this error message and the builtins we are actually using?

**Comment by davydden** [comment]
@tamiko can you check which macros are actually supported by this version, should probably be similar to [gcc](__AVX__ (Windows*, Linux*)).

**Comment by kronbichler** [comment]
I tried the line by @davydden both with Intel 16.0.1 (gcc version 5.3.0 compatibility), 16.0.1 (gcc version 4.8.5 compatibility) and 17.0.2 (gcc version 6.3.0 compatibility) and on all systems I get (with `-xhost`):
```
....
#define __SSE2__ 1
#define __SSE2_MATH__ 1
#define __SSE3__ 1
#define __SSSE3__ 1
#define __SSE4_1__ 1
#define __SSE4_2__ 1
#define __SSE__ 1
#define __SSE_MATH__ 1
#define __MMX__ 1
#define __AVX__ 1
#define __AVX_I__ 1
#define __AVX2__ 1
#define __FMA__ 1
```
thus showing that everything is fine. @tamiko can you please check that on your system and also that the configuration options and compilation options are the same?

**Comment by tamiko** [comment]
No, I do not have an ICC license and thus cannot check anything.
Whoever runs [1] shall fix their userland I'd say.

[1] https://cdash.kyomu.43-1.org/buildSummary.php?buildid=7606

**Comment by tjhei** [comment]
> macro __AVX__ but I was wrong apparently (interestingly, some Intel compilers do define them, like mine).
```
$ icc -v
icc version 16.0.1 (gcc version 4.6.0 compatibility)
$ icc -E -dM - < /dev/null
...
#define __SSE2__ 1
#define __SSE2_MATH__ 1
#define __SSE__ 1
#define __SSE_MATH__ 1
#define __MMX__ 1
```
but no __AVX__. What do we do about this?

**Comment by davydden** [comment]
> gcc version 4.6.0 compatibility

that's a bit too low and won't provide C++11 feature we currently require.

**Comment by tjhei** [comment]
That is annoying. Interestingly, configuration works and we do detect c++11 support.

**Comment by masterleinad** [comment]
Same here for intel-17
```
$ icc -v
icc version 17.0.1 (gcc version 5.0.0 compatibility)
$ icc   -dM -E -x c /dev/null | tail
#define __pentiumpro 1
#define __pentiumpro__ 1
#define __pentium4 1
#define __pentium4__ 1
#define __tune_pentium4__ 1
#define __SSE2__ 1
#define __SSE2_MATH__ 1
#define __SSE__ 1
#define __SSE_MATH__ 1
#define __MMX__ 1
```

**Comment by masterleinad** [comment]
But I can compile without problems :confused:

**Comment by kronbichler** [comment]
@masterleinad @tjhei You need to add an instruction set specification such as `-xhost` or `-xavx` or `-core-avx2` to get AVX. I thought the conclusion from that post in May was clear: One should not mix different instruction sets in debug and release mode because our detection mechanism regarding `DEAL_II_COMPILER_VECTORIZATION_LEVEL` does not support different settings. We could change that by introducing different flags, though. But I do not see the current problem.

**Comment by bangerth** [comment]
@tjhei -- to add to @kronbichler 's comment: You get flags such as `__MMX__` and `__SSE2__` defined because these are part of the x86_64 minimal requirements: when AMD came out with the first Opteron processors on which the current 64-bit ABI was defined, they already had MMX and SSE2. So *every* processor on which x86_64 runs has these capabilities, and every compiler can assume that they exist. For higher capabilities (e.g., AVX) you have to provide the correct flag that tells the compiler to assume these capabilities are present.

**Comment by tjhei** [comment]
> But I do not see the current problem.

The current problem is that I configure deal.II with icc with standard options and the compilation fails due to the check in vectorization.h.

> For higher capabilities (e.g., AVX) you have to provide the correct flag that tells the compiler to assume these capabilities are present.

Well, I still want to compile without specifying AVX-stuff.

**Comment by kronbichler** [comment]
Is this unrelated from #4976? Do you have an error message around that points to that it indeed is the `AVX` part and not the SSE2 part that might be fixed by #4978?

**Comment by tjhei** [comment]
This is with ICC not wih MSVC. Configuration gives:
```
-- Performing Test DEAL_II_HAVE_SSE2
-- Performing Test DEAL_II_HAVE_SSE2 - Success
-- Performing Test DEAL_II_HAVE_AVX
-- Performing Test DEAL_II_HAVE_AVX - Success
```
and I am getting
```
/ssd/auto/ssd-auto-deal-intel/dealii/include/deal.II/base/vectorization.h(46): error ...
```
which is ``__AVX__`` (as it is not defined, see above).

Note that #4978 will "fix" this problem by disabling vectorization because the macro will be checked at configure time now.

**Comment by kronbichler** [comment]
OK, that's interesting that `icc` understands the AVX instructions without having the AVX instructions enabled officially and the AVX flag. Just to make sure: You see the error in both the debug and the release build? From your other posts I assume that `__AVX__` gets indeed enabled if you add a `-xhost` or `-xavx` flag to the compiler? If the answer is yes to both posts, I think #4978 should be fine because it avoids the original error and eagerly enabling some instructions that are later not used. Still it keeps the cross-checking enabled in case the flags are not consistent during compilation of deal.II and a user program - which was the original reason to introduce them in #4311. Except for the case where we have SSE2 at configure/compile time but not in the user project, which should be rare.

**Comment by tjhei** [comment]
> You see the error in both the debug and the release build?

Yes.

> From your other posts I assume that __AVX__ gets indeed enabled if you add a -xhost or -xavx flag to the compiler?

I have not specified xhost or other flags.

**Comment by tjhei** [comment]
If I specify DEAL_II_CXX_FLAGS="-xHost" I am getting
```
icpc: command line remark #10382: option '-xHOST' setting '-xCORE-AVX2'
```
but we set
```
#define DEAL_II_COMPILER_VECTORIZATION_LEVEL 2
```
and things seem to compile.

**Comment by kronbichler** [comment]
I guess we give #4978 a shot then? You will not have the full width of vectorization in `VectorizedArray` but that can be added by `-xcore-avx2` and the rest of the library not building on AVX will still have the features enabled.

I'm still puzzled why the Intel compiler is enabling the AVX instructions. I guess it creates machine code for two paths aggressively, one more optimized one for AVX2 and one for the basic SSE2 instruction set - the former because it sees the CPU it compiles on and the latter because it cannot be sure that the user is going to run the executable/library on the same system.

**Comment by tjhei** [comment]
okay, sounds good. We should see the results on the cdash later (currently running without #4978 merged). Do you normally only set things like ``-xcore-avx2`` in release mode or for both?

**Comment by kronbichler** [comment]
I set those flags on both, i.e., `CMAKE_CXX_FLAGS="-xcore-avx2"` or whatever. That was my point above at https://github.com/dealii/dealii/pull/4440#issuecomment-325345836 that we need to have the same instruction set on both the debug and release build. Since we build the batches of cells in `MatrixFree` of the SIMD width, one would get completely different data structures in debug and release build which is rarely desired...

**Pull request closed without merging**
