### PR TITLE
Add get/set_mesh_smoothing to python bindings.

### PR DESCRIPTION
**Pull request by adamqc**

### CODE REVIEW

**Review by Rombur — COMMENTED** [review]
This looks good. It would be nice if instead of exposing an integer, we would use an `enum` (see [here](https://www.boost.org/doc/libs/1_80_0/libs/python/doc/html/tutorial/tutorial/object.html#tutorial.object.enums)).  Do you think that you could do it?

**Comment by adamqc** [comment]
I would like to have a try.

**Comment by adamqc** [comment]
I added the `enum dealii.MeshSmoothing` to the python bindings. Besides, I added two default arguments `mesh_smoothing` and `check_for_distorted_cells` to the constructor of `Triangulation`. Note that I still use `int` as the type of `smoothing`. The reason is that sometimes we may use the `bitwise or` result of several enums, which can not be converted to python `enum`.

The following python code works on my machine.
```python
import PyDealII.Release as dealii

tria = dealii.Triangulation('2D', '3D', mesh_smoothing=dealii.MeshSmoothing.none, check_for_distorted_cells=False)
print(tria.get_mesh_smoothing())
tria.set_mesh_smoothing(dealii.MeshSmoothing.maximum_smoothing)
print(tria.get_mesh_smoothing())

tria = dealii.Triangulation('3D')
print(tria.get_mesh_smoothing())
tria.set_mesh_smoothing(dealii.MeshSmoothing.limit_level_difference_at_vertices)
print(tria.get_mesh_smoothing())

tria = dealii.Triangulation('3D', dealii.MeshSmoothing.limit_level_difference_at_vertices | dealii.MeshSmoothing.do_not_produce_unrefined_islands)
print(tria.get_mesh_smoothing())
```

Feel free to point out if I am doing something wrong.

**Comment by Rombur** [comment]
This is great. Can you take the python code you used to check the code and add it as a test [here](https://github.com/dealii/dealii/blob/master/contrib/python-bindings/tests/triangulation_wrapper.py)

**Comment by adamqc** [comment]
This PR is ready for review now.

**Review by Rombur — APPROVED** [review]

**Comment by Rombur** [comment]
Thanks a lot for the PR

**Pull request merged**
