### PR TITLE
Detect a compiler bug that prevents compilation of complex Sacado::Rad.

### PR DESCRIPTION
**Pull request by jppelteret**

### CODE REVIEW

**Comment by bangerth** [comment]
I have no idea what the compiler is trying to tell me with this error message!

So do I understand things right that you're just not instantiating things for complex Rad types if the compiler has this particular bug? Wouldn't that just lead to linker errors with programs that may compile on some other platform? (Not that I have any better suggestion.)

**Comment by jppelteret** [comment]
Yes, thats correct. Specifically I end up having to guard some template specialisations
```c++
// in sacado_number_types.h
#ifdef DEAL_II_TRILINOS_CXX_SUPPORTS_SACADO_COMPLEX_RAD
    template<typename ADNumberType>
    struct ADNumberTraits<ADNumberType, typename std::enable_if<
      std::is_same<ADNumberType, std::complex<Sacado::Rad::ADvar<typename ADNumberType::value_type::ADVari::scalar_type> > >::value
      >::type>
      : NumberTraits<std::complex<typename ADNumberType::value_type::ADVari::scalar_type>, NumberTypes::sacado_rad>
    {};

...
#endif
```
and parts of some tests must be skipped 
```c++
// in ad_number_traits_02c.cc
#ifdef DEAL_II_TRILINOS_CXX_SUPPORTS_SACADO_COMPLEX_RAD
  deallog.push("std::complex< Sacado::Rad::ADvar<float> >");
  print_info<AD::ADNumberTraits<std::complex< Sacado::Rad::ADvar<float> > > >();
  deallog.pop();
#endif
```
There's further complications related to the symbolic differentiation stuff I've implemented, but let me just say that the current approach to working around this problem works for that as well.

**Comment by jppelteret** [comment]
FYI. I can confirm that I can successfully build this branch on both a machine that exhibits this issue and one that doesn't.

**Comment by bangerth** [comment]
OK to merge once the tester is happy.

/run-tests

**Comment by jppelteret** [comment]
@bangerth To prevent the possibility of linker errors, what I could do is use a `static_assert` to provide some meaningful compile-time error and prevent the accidental instantiation of this invalid specialisation. What I was thinking was this:
```c++
#ifdef DEAL_II_TRILINOS_CXX_SUPPORTS_SACADO_COMPLEX_RAD
    template<typename ADNumberType>
    struct ADNumberTraits<ADNumberType, typename std::enable_if<
      std::is_same<ADNumberType, std::complex<Sacado::Rad::ADvar<typename ADNumberType::value_type::ADVari::scalar_type> > >::value
      >::type>
      : NumberTraits<std::complex<typename ADNumberType::value_type::ADVari::scalar_type>, NumberTypes::sacado_rad>
    {};
#else
    template<typename ADNumberType>
    struct ADNumberTraits<ADNumberType, typename std::enable_if<
      std::is_same<ADNumberType, std::complex<Sacado::Rad::ADvar<typename ADNumberType::value_type::ADVari::scalar_type> > >::value
      >::type>
    {
      static_assert("Your compiler does not support the use of this auto-differentiable number type.");
    };
#endif
```
Although we would never instantiate this specialisation from within the library, in theory a user could try to use this unsupported number type and trigger this case. In fact, I think thats exactly what happened when the tests in #5392 failed. So having this (or something like it) could save someone some agony later.

BTW. I'm not at the point where I treat complex numbers as first-class citizens within this framework. I don't think it would be hard to extend what I've done, but I'd rather concentrate on getting the scalar-valued implementation integrated fully before extending it later.

**Comment by bangerth** [comment]
I think the `static_assert` as you outline is an excellent idea. Please merge yourself after putting this in!

**Pull request merged**
