### PR TITLE
add reference for Nguyen 2012

### PR DESCRIPTION
**Pull request by jiuhuahu**

### CODE REVIEW

**Comment by bangerth** [comment]
@jiuhuahu -- is this a paper that *uses* deal.II, or is it a paper you think we should reference somewhere in the documentation *of* deal.II?

**Comment by jiuhuahu** [comment]
> @jiuhuahu -- is this a paper that _uses_ deal.II, or is it a paper you think we should reference somewhere in the documentation _of_ deal.II?

Step-51 cited this paper in the Introduction section. It is a HDG review paper.

**Comment by bangerth** [comment]
Ah, I see. Can you replace the text in the introduction of step-51 ("(see the references in the recent HDG overview article by N.C. Nguyen and J. Peraire: Hybridizable discontinuous Galerkin methods for partial differential equations in continuum mechanics, Journal of Computational Physics, 2012, 231:18, 5955-5988. [DOI])." by something like this:

"(see the references in the recent HDG overview article by N.C. Nguyen and J. Peraire @cite{...})."

**Comment by jiuhuahu** [comment]
> Ah, I see. Can you replace the text in the introduction of step-51 ("(see the references in the recent HDG overview article by N.C. Nguyen and J. Peraire: Hybridizable discontinuous Galerkin methods for partial differential equations in continuum mechanics, Journal of Computational Physics, 2012, 231:18, 5955-5988. [DOI])." by something like this:
> 
> "(see the references in the recent HDG overview article by N.C. Nguyen and J. Peraire @cite{...})."

Sure.

**Comment by drwells** [comment]
@jiuhuahu Let me know when you have time to look at this again.

**Comment by jiuhuahu** [comment]
> @jiuhuahu Let me know when you have time to look at this again.

Thanks, David! Let's talk about this after all the talks today.

**Comment by bangerth** [comment]
@jiuhuahu -- nice, you're now one of the deal.II authors!

**Comment by bangerth** [comment]
Oh, well, actually, I forgot one step. Would you mind creating a follow-up pull request in which you add an entry to `doc/news/changes/minor` that summarizes your change?

**Comment by jiuhuahu** [comment]
> Oh, well, actually, I forgot one step. Would you mind creating a follow-up pull request in which you add an entry to `doc/news/changes/minor` that summarizes your change?

Sure. I will do that. Thanks!

**Comment by tjhei** [comment]
@jiuhuahu your commits are not associated with your github account. It this because your git config has a different email address than your github profile? If yes, can you add your address as a second address in your github settings? I can help you if you don't know what I mean.

**Comment by tjhei** [comment]
@bangerth the format for citing needs to be ``@cite NAME``. The formatting here broke doxygen, see #8505

**Comment by jiuhuahu** [comment]
> @jiuhuahu your commits are not associated with your github account. It this because your git config has a different email address than your github profile? If yes, can you add your address as a second address in your github settings? I can help you if you don't know what I mean.

Thanks, Timo. I set my git config email address to be jiuhuahu@tamu.edu, while the email address associate with my github is jiuhuahu115@gmail.com. I just add jiuhuahu@tamu.edu as a second email address in the github setting. Thanks for pointing it out!

**Comment by jiuhuahu** [comment]
> @bangerth the format for citing needs to be `@cite NAME`. The formatting here broke doxygen, see #8505

Thanks, Timo! You are right! Thanks for catching that!

**Comment by bangerth** [comment]
@tjhei -- ah bummer. I should have known :-(

**Pull request merged**
