### PR TITLE
Remove inverse constness

### PR DESCRIPTION
**Pull request by drwells**
This is part of an ongoing effort of mine to remove references to old versions of GCC.

Edit: I should have made the title of this clearer. There is currently a class with the name `InverseConstnessIterator` that only exists because of a limitation in GCC 2.95. It only existed so that one could compare `const` and non-`const` iterators.

### CODE REVIEW

**Comment by bangerth** [comment]
OK if you address the one issue of the copy constructor.

**Comment by drwells** [comment]
@bangerth Thank you for the feedback; I would have never realized that behavior (regarding the default copy constructor).

At least `is_const` is now in the standard library, though I don't think that alone will help us here. If anyone knows of a way to use `is_const` to clean things up I would like to hear about it.

I spent a long time last night thinking about what you wrote and I wrote something slightly different from what you recommended (though it is certainly possible that I did not understand your original comment). I modified the constructor with the `static_assert` so that it fails in the '`const` to non-`const`' case and added back the copy constructor with the same `const`ness value.

I also removed an (apparently unnecessary) `const_cast`.

**Comment by bangerth** [comment]
This looks good to me. Thanks for working through my suggestion -- I agree that it's a corner case anyone might have easily missed.

As for `is_const` -- I don't think you actually need it here. We explicitly pass a boolean value around, not some type `T` that may or may not be const. Or maybe I misunderstand?

**Comment by drwells** [comment]
The only reason I mentioned that is because you mentioned `requires`. I think the current implementation of Concepts allows checking for `const`, but we have a poor-man's version of that in the standard via `std::is_const`.

I suppose my point is there *may* be a more elegant way to do things with `std::enable_if` and `std::is_const` in place of the `Types` class, but I don't know enough about TMP to answer that question.

**Comment by drwells** [comment]
Confusingly, it looks like github stopped showing comments on outdated diffs. That's annoying.

**Comment by bangerth** [comment]
I'm thinking of `enable_if` as a crude workaround. What I'm looking forward to is something like this:
```
  template <bool Constness>
  class Iterator 
 {
    template <bool _Constness>
    Iterator (Iterator<_Constness> &it)
        requires (Constness==true || _Constness==true); // can't convert a const iterator to a non-const iterator
```
But at the pace at which concepts and similar things are standardized, this may actually find its way into C++20 and we can start using it around 2025 ;-)

**Pull request merged**
