### PR TITLE
cell bounding box tests for Simplex grids in 2d and 3d

### PR DESCRIPTION
**Pull request by nicola-giuliani**

### CODE REVIEW

**Review by peterrum — APPROVED** [review]

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
This patch currently fails the `CI` check with the following error message:
```
[ 16%] Generating simplex.cell_bounding_boxes_2d.debug/interrupt_guard.cc
Scanning dependencies of target simplex.cell_bounding_boxes_2d.debug
[ 50%] Building CXX object CMakeFiles/simplex.cell_bounding_boxes_2d.debug.dir/cell_bounding_boxes_2d.cc.o
Building CXX object CMakeFiles/simplex.cell_bounding_boxes_2d.debug.dir/simplex.cell_bounding_boxes_2d.debug/interrupt_guard.cc.o
Linking CXX executable simplex.cell_bounding_boxes_2d.debug/simplex.cell_bounding_boxes_2d.debug
Built target simplex.cell_bounding_boxes_2d.debug
Scanning dependencies of target simplex.cell_bounding_boxes_2d.debug.diff
Generating cell_bounding_boxes_2d.debug/output
simplex/cell_bounding_boxes_2d.debug: BUILD successful.
simplex/cell_bounding_boxes_2d.debug: RUN failed. ------ Return code 134
simplex/cell_bounding_boxes_2d.debug: RUN failed. ------ Result: /home/dealii/build/tests/simplex/cell_bounding_boxes_2d.debug/failing_output
simplex/cell_bounding_boxes_2d.debug: RUN failed. ------ Partial output:

simplex/cell_bounding_boxes_2d.debug: RUN failed. ------ Additional output on stdout/stderr:


--------------------------------------------------------
An error occurred in line <10520> of file </jenkins/workspace/dealii_PR-11531/source/grid/tria.cc> in function
    void dealii::Triangulation<<anonymous>, <anonymous> >::create_triangulation(const std::vector<dealii::Point<spacedim> >&, const std::vector<dealii::CellData<dim> >&, const dealii::SubCellData&) [with int dim = 2; int spacedim = 2]
The violated condition was: 
    false
Additional information: 
    You are attempting to use functionality that is only available if deal.II was configured with DEAL_II_WITH_SIMPLEX_SUPPORT enabled.
--------------------------------------------------------
```
Can you rename the `.output` files of your two new tests so that they contain the string `.with_simplex_support=on` like all of the other tests in this directory?

**Comment by bangerth** [comment]
This is fixed in #11536 now, but I would appreciate if you could nonetheless make the change here.

**Comment by nicola-giuliani** [comment]
@bangerth sure, this should be done now.

**Pull request merged**
