### PR TITLE
Set file permissions in the indentation script.

### PR DESCRIPTION
**Pull request by bangerth**
Addresses one of the issues mentioned in #5426.

### CODE REVIEW

**Comment by tjhei** [comment]
Can you please add another commit that sets an incorrect permission for one of the files so we can see if the travis CI reports an error?

**Comment by bangerth** [comment]
I pushed another commit.

Do we really use the branch's indentation script for the Travis CI run? This Travis run is triggered for *all* patches. Using a script that a user can modify in a PR seems like a security problem.

**Comment by bangerth** [comment]
The CI test failed with this error:
```
Running indentation test on Pull Request #5428
diff --git a/source/grid/tria.cc b/source/grid/tria.cc
old mode 100755
new mode 100644
```
That's exactly what is the correct answer for the commit I pushed. I'm going to remove the commit again now.

**Comment by bangerth** [comment]
OK, back to just the one commit we want.

**Comment by tjhei** [comment]
> That's exactly what is the correct answer for the commit I pushed. I'm going to remove the commit again now.

excellent, thank you!

**Pull request merged**
