### PR TITLE
Suppress some nvcc warnings

### PR DESCRIPTION
**Pull request by masterleinad**
There are a bunch of warnings emitted by `nvcc` we don't really care about. Of particular annoyance are:
-  unsigned_compare_with_zero
- integer_sign_change
- long double treated as double (mostly boost)
- non-template friend (boost)
- loop_not_reachable

Allowing `constexpr` `host` functions to be called in `device` code also limits the number of warnings.

### CODE REVIEW

**Review by bangerth — COMMENTED** [review]
The code changes are ok by me. I will leave the cmake changes to someone else.

**Review by Rombur — APPROVED** [review]

**Pull request merged**
