### PR TITLE
Provide more shape function pictures

### PR DESCRIPTION
**Pull request by bangerth**
These patches link to pictures of the shape functions by Manuel Quezada de Luna. The formatting of the HTML tables is copied from the FE_Q element -- it is not particularly pretty since it was redone by one of the doc scripts, but it works.

The pictures are already online but have a few flaws and will probably need to be redone in part.

### CODE REVIEW

**Comment by tjhei** [comment]
Looks good. Please astyle before merging yourself.

**Comment by kronbichler** [comment]
I like the idea, too. Let me add two comments, though:
Why did you add separate pictures for FE_DGPNonparametric? The respective files on the homepage are identical except for the png time stamp. Which is clear because the shape functions of FE_DGPNonparametric are the same as those for FE_DGP but not 'mapped' to the element topology. When evaluating the shape functions on [0,1]^2 the result must clearly be the same because no mapping is done.

My second comment is more of a suggestion and applies to the data already generated for FE_Q (I realized this when checking the comment for FE_DGQ): We should discourage users from using FE_Q with equidistant points for p >= 4 because the interpolation gets increasingly ill-conditioned with increasing polynomial degree. I think it would be very instructive to add 'good' basis functions for p=4, i.e., FE_Q<2>(QGaussLobatto<1>(5)) next to the equidistant FE_Q<2>(4) figures and pointing out the difference in the range of values as a measure of conditioning. E.g. the shape functions 4 and 5 (as numbered in the files) clearly show how the equidistant start to misbehave, function values exceed 1 and reach -0.5, whereas the GL points stay between around -0.2 and 1.

**Comment by bangerth** [comment]
FE_DGPNonparametric: Good point. I've removed the links again and simply linked to FE_DGP.

FE_Q: That's a fair point. I will ask Manuel if he's interested in creating more pictures of this kind. Is it ok if we do this incrementally, i.e., independent of the current patch?

**Comment by kronbichler** [comment]
Absolutely, I like the idea very much and it's good to progress in Manuel's pace, which is to just add things when they are ready.

**Pull request merged**
