### PR TITLE
Fix ParticleHandler serialization with p::f::T

### PR DESCRIPTION
**Pull request by pcafrica**
Serialization with serial triangulation is still not working.

@blaisb and I have just added two tests, which are replicas of `serialization/particle_handler_01.cc` but with a serial triangulation and a `p::f::T`, respectively.

@bangerth

### CODE REVIEW

**Comment by bangerth** [comment]
I take it that the output you checked in is what you *expect*, but don't actually get?

**Comment by blaisb** [comment]
> I take it that the output you checked in is what you _expect_, but don't actually get?

We removed this output temporarily. Most likely it will be similar to that. Output for test 4 is different however because find_cell_around_point() does not work right now with fullydistributed::triangulations

**Comment by bangerth** [comment]
Tell me when this is ready for review!

**Comment by pcafrica** [comment]
> Tell me when this is ready for review!

It is ready for review! More PRs will follow.

**Comment by blaisb** [comment]
@bangerth ready to review :)

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
In the interest of moving forward, let's get this merged.

If you would be so kind, would you mind annotating the tops of the new test cases what is different between the tests? The comment at the top of each of the test cases is the same, and it's difficult to spot in which ways they differ.

**Comment by blaisb** [comment]
@bangerth will do so right away

**Review by bangerth — APPROVED** [review]

**Pull request merged**
