### PR TITLE
Add output variants for SUNDIALS 7.

### PR DESCRIPTION
**Pull request by bangerth**
I was asked to try out a pre-release version of SUNDIALS 7. There are some test differences. These are the obvious ones, primarily ones where SUNDIALS 7 now seems to cache certain function evaluations where it previously called back into user code multiple times with the same inputs. So these are the safe changes. There are a couple more where the difference in output is not as obvious, and I will get to those at a later time. But I thought I might as well flush those out already.

For completeness, the ones that I still have to check are these:
```
22/32 Test #19: sundials/arkode_10.debug .............................***Failed   28.53 sec
23/32 Test #21: sundials/arkode_11.debug .............................***Failed   28.65 sec
28/32 Test #15: sundials/arkode_08.debug .............................***Failed   29.42 sec
```

### CODE REVIEW

**Comment by masterleinad** [comment]
What do the diffs loo like? Just fewer lines in the output?

**Comment by bangerth** [comment]
Yes:
```
> for i in arkode_09.output ida_03.output ida_05.output ; do echo $i ; diff $i $i.sundials7 ; done

arkode_09.output
4d3
< DEAL::Evaluating right hand side at t=0.00000 with y=1.00000

ida_03.output
46,49d45
< DEAL::Intermediate output:
< DEAL::  t =2.000000000
< DEAL::  y =0.01831563874  (exact: 0.01831563889)
< DEAL::  y'=-0.03663127757  (exact: -0.03663127778)

ida_05.output
279,282d278
< DEAL::Intermediate output:
< DEAL::  t =2.000000000
< DEAL::  y =0.01831563933  (exact: 0.01831563889)
< DEAL::  y'=-0.03663127916  (exact: -0.03663127778)
```

For the fourth file, `arkode_04.output`, the differences are within 1e-5:
```
> numdiff -a1e-5 arkode_04.output arkode_04.output.sundials7 

+++  Files "arkode_04.output" and "arkode_04.output.sundials7" are equal
```
But since our scripts test to absolute tolerances of 1e-6, I needed to add the output file.

**Comment by bangerth** [comment]
The one CI failure is due to #16649.

**Review by masterleinad — APPROVED** [review]

**Comment by bangerth** [comment]
Ping?

**Pull request merged**
