### PR TITLE
Make access to GridTools::Cache thread safe.

### LINKED ISSUE #8516: FEFieldFunction is not thread-safe (because GridTools is not threadsafe)
@mjayadharan showed me a piece of code that crashes in parallel. I can't say I completely understand why it does, but in looking into it, I think that the following is nonetheless a problem:

When one uses `FEFieldFunction` as an argument to places such as `MatrixTools::create_mass_matrix()` or a variety of other places that build stuff in parallel, one might get into the `vector_value_list` function from multiple threads at the same time:
```
  void
  FEFieldFunction<dim, DoFHandlerType, VectorType>::vector_value_list(
    const std::vector<Point<dim>> &                       points,
    std::vector<Vector<typename VectorType::value_type>> &values) const
  {
    Assert(...);

    std::vector<typename DoFHandlerType::active_cell_iterator> cells;
    std::vector<std::vector<Point<dim>>>                       qpoints;
    std::vector<std::vector<unsigned int>>                     maps;

    const unsigned int n_cells =
      compute_point_locations(points, cells, qpoints, maps);
```
So we can also compute `compute_point_locations()` multiple times in parallel:
```
  unsigned int
  FEFieldFunction<dim, DoFHandlerType, VectorType>::compute_point_locations(
    const std::vector<Point<dim>> &                             points,
    std::vector<typename DoFHandlerType::active_cell_iterator> &cells,
    std::vector<std::vector<Point<dim>>> &                      qpoints,
    std::vector<std::vector<unsigned int>> &                    maps) const
  {
    // Calling the GridTools routine and preparing output
    auto cell_qpoint_map =
      GridTools::compute_point_locations(cache, points, cell_hint.get());
  ...
```

From there, through a couple more places, we end up in the `GridTools::Cache` class, possibly again multiple times in parallel:
```
  Cache<dim, spacedim>::get_cell_bounding_boxes_rtree() const
  {
    if (update_flags & update_cell_bounding_boxes_rtree)
      {
        std::vector<std::pair<
          BoundingBox<spacedim>,
          typename Triangulation<dim, spacedim>::active_cell_iterator>>
                     boxes(tria->n_active_cells());
        unsigned int i = 0;
        for (const auto &cell : tria->active_cell_iterators())
          boxes[i++] = std::make_pair(mapping->get_bounding_box(cell), cell);

        cell_bounding_boxes_rtree = pack_rtree(boxes);
        ...
```
The issue is the assignment in this last line here, which is to a member variable of the `Cache` class. As part of the assignment, previous content is destroyed and new content is assigned. This can't work if it happens from multiple threads at the same time.

In other words, either the `FEFieldFunction` or the `GridTools::Cache` class will have to learn how to be thread-safe.

@luca-heltai -- FYI.

### LINKED ISSUE #17131: sigabrt in matrixcreator workstream inside VectorTools::project
For #17119 we are seeing crashes in tests/fe/fe_face_orientation_nedelec_0.cc and realized this also fails with TBB if we change the grain size of the workstream call to 1:
```
--- a/include/deal.II/numerics/matrix_creator.templates.h
+++ b/include/deal.II/numerics/matrix_creator.templates.h
@@ -781,7 +781,8 @@ namespace MatrixCreator
                                                       &rhs_vector);
       },
       assembler_data,
-      copy_data);
+      copy_data,
+      12,1);
 
     matrix.compress(VectorOperation::add);
   }
```

call stack:
```
#31 0x00007fffed9b31cb in dealii::WorkStream::run<void (*)(dealii::TriaActiveIterator<dealii::DoFCellAccessor<3, 3, false> > const&, dealii::MatrixCreator::internal::AssemblerData::Scratch<3, 3, double>&, dealii::MatrixCreator::internal::AssemblerData::CopyData<double>&), dealii::MatrixCreator::create_mass_matrix<3, 3, dealii::SparseMatrix<double> >(dealii::Mapping<3, 3> const&, dealii::DoFHandler<3, 3> const&, dealii::Quadrature<3> const&, dealii::SparseMatrix<double>&, dealii::Function<3, dealii::SparseMatrix<double>::value_type> const&, dealii::Vector<dealii::SparseMatrix<double>::value_type>&, dealii::Function<3, dealii::SparseMatrix<double>::value_type> const*, dealii::AffineConstraints<dealii::SparseMatrix<double>::value_type> const&)::{lambda(dealii::MatrixCreator::internal::AssemblerData::CopyData<double> const&)#1}, dealii::TriaActiveIterator<dealii::DoFCellAccessor<3, 3, false> >, dealii::MatrixCreator::internal::AssemblerData::Scratch<3, 3, double>, dealii::MatrixCreator::internal::AssemblerData::CopyData<double> >(dealii::TriaActiveIterator<dealii::DoFCellAccessor<3, 3, false> > const&, dealii::std_cxx20::type_identity<dealii::TriaActiveIterator<dealii::DoFCellAccessor<3, 3, false> > >::type const&, void (*)(dealii::TriaActiveIterator<dealii::DoFCellAccessor<3, 3, false> > const&, dealii::MatrixCreator::internal::AssemblerData::Scratch<3, 3, double>&, dealii::MatrixCreator::internal::AssemblerData::CopyData<double>&), dealii::MatrixCreator::create_mass_matrix<3, 3, dealii::SparseMatrix<double> >(dealii::Mapping<3, 3> const&, dealii::DoFHandler<3, 3> const&, dealii::Quadrature<3> const&, dealii::SparseMatrix<double>&, dealii::Function<3, dealii::SparseMatrix<double>::value_type> const&, dealii::Vector<dealii::SparseMatrix<double>::value_type>&, dealii::Function<3, dealii::SparseMatrix<double>::value_type> const*, dealii::AffineConstraints<dealii::SparseMatrix<double>::value_type> const&)::{lambda(dealii::MatrixCreator::internal::AssemblerData::CopyData<double> const&)#1}, dealii::MatrixCreator::internal::AssemblerData::Scratch<3, 3, double> const&, dealii::MatrixCreator::internal::AssemblerData::CopyData<double> const&, unsigned int, unsigned int) (begin=..., end=..., 
    worker=0x7fffed9a5a05 <dealii::MatrixCreator::internal::mass_assembler<3, 3, dealii::TriaActiveIterator<dealii::DoFCellAccessor<3, 3, false> >, double>(dealii::TriaActiveIterator<dealii::DoFCellAccessor<3, 3, false> > const&, dealii::MatrixCreator::internal::AssemblerData::Scratch<3, 3, double>&, dealii::MatrixCreator::internal::AssemblerData::CopyData<double>&)>, copier=..., sample_scratch_data=..., sample_copy_data=..., queue_length=12, chunk_size=1)
    at /ssd/deal-git/include/deal.II/base/work_stream.h:1151
#32 0x00007fffed97d649 in dealii::MatrixCreator::create_mass_matrix<3, 3, dealii::SparseMatrix<double> > (mapping=..., dof=..., q=..., matrix=..., rhs=..., rhs_vector=..., coefficient=0x0, constraints=...)
    at /ssd/deal-git/include/deal.II/numerics/matrix_creator.templates.h:767
#33 0x00007fffee3848bf in dealii::VectorTools::internal::do_project<3, 3, dealii::Vector<double>, dealii::Mapping, dealii::Quadrature> (mapping=..., dof=..., constraints=..., quadrature=..., function=..., vec_result=..., enforce_zero_boundary=false, 
    q_boundary=..., project_to_boundary_first=false) at /ssd/deal-git/include/deal.II/numerics/vector_tools_project.templates.h:539
#34 0x00007fffee37e1c6 in dealii::VectorTools::internal::project<dealii::Vector<double>, 3, 3> (mapping=..., dof=..., constraints=..., quadrature=..., function=..., vec_result=..., enforce_zero_boundary=false, q_boundary=..., 
    project_to_boundary_first=false) at /ssd/deal-git/include/deal.II/numerics/vector_tools_project.templates.h:821
#35 0x00007fffee37bd96 in dealii::VectorTools::project<3, dealii::Vector<double>, 3> (mapping=..., dof=..., constraints=..., quadrature=..., function=..., vec_result=..., enforce_zero_boundary=false, q_boundary=..., project_to_boundary_first=false)
    at /ssd/deal-git/include/deal.II/numerics/vector_tools_project.templates.h:952
#36 0x00007fffee37be18 in dealii::VectorTools::project<3, dealii::Vector<double>, 3> (dof=..., constraints=..., quadrature=..., function=..., vec=..., enforce_zero_boundary=false, q_boundary=..., project_to_boundary_first=false)
    at /ssd/deal-git/include/deal.II/numerics/vector_tools_project.templates.h:977
#37 0x00005555555cc2f2 in set_solution (vector=..., dof_handler=..., dof_handler_ref=..., u_ref=...) at /ssd/deal-git/tests/fe/fe_face_orientation_nedelec_0.cc:162
#38 0x00005555555cc575 in main () at /ssd/deal-git/tests/fe/fe_face_orientation_nedelec_0.cc:194

```

the crash happens randomly inside FEFieldFunction on one of the threads (double free or memory corruption). for example:
```
#10 0x00007fffdc6bb5dc in operator new(unsigned long) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff67b6347 in std::make_unique<dealii::FEValues<3, 3>, dealii::Mapping<3, 3> const&, dealii::FiniteElement<3, 3> const&, dealii::hp::QCollection<3> const&, dealii::UpdateFlags const&> () at /usr/include/c++/13/bits/unique_ptr.h:1070
#12 0x00007ffff678662f in dealii::hp::FEValuesBase<3, 3, dealii::FEValues<3, 3> >::select_fe_values (this=0x7fffffff8880, fe_index=0, mapping_index=0, q_index=0) at /ssd/deal-git/source/hp/fe_values.cc:191
#13 0x00007ffff679ba9b in dealii::hp::FEValues<3, 3>::reinit<false> (this=0x7fffffff8880, cell=..., q_index=0, mapping_index=0, fe_index=4294967295) at /ssd/deal-git/source/hp/fe_values.cc:328
#14 0x00007fffed636f4e in dealii::Functions::FEFieldFunction<3, dealii::Vector<double>, 3>::vector_value_list (this=0x7fffffffb240, points=std::vector of length 8, capacity 8 = {...}, values=std::vector of length 8, capacity 8 = {...})
    at /ssd/deal-git/include/deal.II/numerics/fe_field_function.templates.h:307
#15 0x00007fffed9a5f1e in dealii::MatrixCreator::internal::mass_assembler<3, 3, dealii::TriaActiveIterator<dealii::DoFCellAccessor<3, 3, false> >, double> (cell=..., data=..., copy_data=...)
    at /ssd/deal-git/include/deal.II/numerics/matrix_creator.templates.h:206
```

FYI @RyanMoulday.

### PR DESCRIPTION
**Pull request by bangerth**
I think this should fix #8516 and therefore fix #17131 and make #17119 possible.

@tjhei FYI. Can you take a look and see whether that fixes the problems you see? I think that this is independently useful/correct/fixing a bug, but it would be nice if it also fixes your problem.

### CODE REVIEW

**Comment by bangerth** [comment]
We crossed wires here with #17144. I took an approach that we've used elsewhere, namely that every mutable variable must either be atomic, or must have a corresponding mutex. In contrast, #17144 uses a single global mutex. That works, but I will admit that I like my approach better because it follows the general approach of using one mutex per `mutable` variable.

**Comment by bangerth** [comment]
The one CI failure seems unrelated: https://ci.tjhei.info/job/dealii-mpi/job/PR-17147/1/testReport/junit/projectroot.tests.examples.binary.step-18debug/mpirun=2/examples_step_18_mpirun_2_debug/

**Comment by tjhei** [comment]
> We crossed wires here

Apparently we did!

I am fine with either solution.

**Review by tjhei — APPROVED** [review]

**Comment by tjhei** [comment]
> Can you take a look and see whether that fixes the problems you see?

It seems to fix the issue, yes.

**Comment by tjhei** [comment]
test failure will be fixed in #17163

**Pull request merged**
