### PR TITLE
Parallelepiped 3d orientation fix

### PR DESCRIPTION
**Pull request by drwells**
I noticed this while working on #2578: for some (torturous) inputs `subdivided_parallelepiped` can generate cells with negative volume. This PR fixes that and adds a test.

### CODE REVIEW

**Comment by tjhei** [comment]
While this looks good, the ``colorized`` option will now do something unexpected if you decide to flip anything. I have no good idea how to fix this, though.

**Comment by drwells** [comment]
That's a good point and I do not really understand what colorizing does. Perhaps this function should just throw an exception instead of fixing the input?

I will try to understand the colorizing features better to see if there is a way to do both.

**Comment by tjhei** [comment]
> what colorizing does

basically giving face ``i`` a boundary id of ``i``.

> Perhaps this function should just throw an exception instead of fixing the input?

Maybe. Or only throw if ``colorize`` is true?

**Comment by drwells** [comment]
Unfortunately the colorization is changed in a nontrivial way (all of them seem rotated in some fashion) with the orientation fixes. I think that this is okay for two reasons:
1. Previously this function output triangulations where all of the cells had negative Jacobians for twisted input. Hence we are only altering the output for what was previously ill-formed output anyway.
2. This function calls `create_triangulation` before coloring faces. `create_triangulation` (as of 8.4) throws an exception (only) in 3D if any of the cells have negative volume, so no colorizing happens for the case this PR fixes anyway. This would be a separate issue, but with the last two patches this function should never create cells with negative Jacobians.

Hence, since I only change the coloring (versus 8.4) for what would be a triangulation consisting entirely of twisted cells anyway (and no one complained about the lack of colorizing in the 3D case) I think that it is okay to change the output here.

**Comment by bangerth** [comment]
I haven't looked at the patch, but just as a general remark: our usual approach has been that if a function gets arguments that make no sense as given, then we throw an exception and let the user fix it. It seems to me that what you do here is to try very hard to make sense of the arguments anyway, and come up with a reasonable interpretation that, however, leads to downstream problems with the coloring. I would have no problem if we required that the cases you try to cover are simply not allowed, by adding appropriate assertions and `@pre` (precondition) doxygen statements.

But then, as I said, I haven't looked at the code and will gladly let y'all figure it out and go back to mortgage applications and similar boring stuff :-(

**Comment by drwells** [comment]
> our usual approach has been that if a function gets arguments that make no sense as given, then we throw an exception and let the user fix it. 

That's a good point. My original motivation for trying to fix user input is that previous versions of this function allowed for 'bad' input. Some tests even relied on this behavior (though they did not try to compute anything with the triangulations).

Regarding coloring: it is probably right to raise exceptions with such input. Any user code relying on this behavior was probably horribly broken anyway.

> But then, as I said, I haven't looked at the code and will gladly let y'all figure it out and go back to mortgage applications and similar boring stuff :-(

I am terrible with paperwork and am very glad that I do not have to do such things and can spend my time fixing obscure bugs instead.

Conclusion: even though it breaks some tests it is probably best to just not accept such input. I will redo what I have to raise exceptions instead of `swap`ing.

**Comment by drwells** [comment]
This is ready for re-review.

**Pull request merged**
