### PR TITLE
Parallel distributed: Communicate active_fe_indices after deserializa…

### PR DESCRIPTION
**Pull request by marcfehling**
Follow-up to #8422. I just realized that we need to update the indices after deserialization as well to be consistent with the requirements in #8376. Sorry for any inconvenience.

### CODE REVIEW

**Comment by drwells** [comment]
I am surprised that we did not catch this before. Do we have any tests that serialize and deserialize an `hp::DoFHandler` in parallel?

**Comment by marcfehling** [comment]
The test `mpi/p4est_save_06` deals with parallel `hp::DoFHandler` serialization. In these tests however, we call `distribute_dofs()` immediately afterwards, which also takes care of communicating the `active_fe_indices` on ghost cells. In real applications, this would be the usual workflow.

We want to avoid confusion for users by communicating those during the refinement/seriailzation process and not only by calling `distribute_dofs()`. The amount of work added should be negligible.

**Comment by bangerth** [comment]
While the existing tests checks the "common" situation, can you clone the test and adjust the copy so that it verifies the condition you implement here?

**Comment by marcfehling** [comment]
Enhanced all tests related to the transfer of `active_fe_indices` to verify ghost cells as well.

**Comment by marcfehling** [comment]
ping -- most of the lines changed result from adding ghost related ones in the output file

**Pull request merged**
