### PR TITLE
Step-64 also depends on step-40.

### PR DESCRIPTION
**Pull request by bangerth**
It uses parallel distributed computations and so step-40 seems like a good
introduction to these issues.

### CODE REVIEW

**Comment by bangerth** [comment]
@masterleinad @Rombur @kronbichler: FYI.

**Comment by masterleinad** [comment]
Maybe, rather let `step-37` depend on `step-40`?

**Comment by kronbichler** [comment]
> Maybe, rather let step-37 depend on step-40?

I would definitely add that (if we do that, we can also remove the direct step-40 -> step-48 dependency). I think we simply forgot to update the graph when we switched to the parallel version of step-37 for the 8.5 release (or was it 8.4 already?).

**Comment by bangerth** [comment]
So you want something like this? 37 already depended on 40, but the format of the file was wrong and so the graph didn't show the dependency...

**Pull request merged**
