### PR TITLE
Remove compat feature

### LINKED ISSUE #421: [RFC] Remove <code>compat</code> feature
One question that I had on mind for quite a while now:
Do we still need the compat feature stuff? Specifically
 - <code>Make.global_options</code>
 - the awkward directory layout that forces a bunch of special code in the cmake configuration
 - installation of <code>make_dependencies</code> executable

If it is just about providing a Makefile includable configuration file (similar to <code>deal.IIConfig.cmake</code>) this could be done (in a backward incompatible manner) easily by providing the cmake configuration <code>deal.IIConfig.cmake</code> with Makefile compatible syntax.

### PR DESCRIPTION
**Pull request by tamiko**
This pull-request remove the compat feature and all associated files and
reintroduces a completely reworked Make.global_options that closely mimics
deal.IIConfig.cmake

Closes #421

Changes:

ff5e48d (Matthias Maier, 6 minutes ago)
   Provide a changes.h entry

119c2c1 (Matthias Maier, 13 minutes ago)
   Remove quirk

cc2d123 (Matthias Maier, 27 minutes ago)
   CMake: Export Makefile compatible definitions

   This commit reintroduces Make.global_options that closely mirrors the
   information and layout of the CMake project configuration
   deal.IIConfig.cmake.

   it is intended for sourcing in Makefiles.

636328a (Matthias Maier, 19 hours ago)
   CMake: Restructure library name creation and remove obsolete include

2362fcf (Matthias Maier, 2 days ago)
   Remove component COMPAT_FILES

### CODE REVIEW

**Comment by bangerth** [comment]
This far exceeds my cmake-fu. I would say give everyone a couple of days to comment and if nobody objects, merge it.

I like that we're moving towards a more standards compliant directory layout.

**Comment by luca-heltai** [comment]
It looks good to me.

**Comment by kronbichler** [comment]
Also from my perspective with only basic cmake literacy it looks fine.

**Comment by bangerth** [comment]
There were no objects, so let's go with it.

**Comment by bangerth** [comment]
Well, except the branch needs to be rebased. Please do and merge.

**Pull request merged**
