### PR TITLE
fix bug in symmetric tensor unrolled_to_component_indices function.

### PR DESCRIPTION
**Pull request by MFraters**
This pull request fixes what I believe to be a bug in the unrolled_to_component_indices function.

In short, I managed to reach the 'Assert(false, ExcInternalError());' statement on line 2451 of this file by requesting the index of a `SymmetricTensor<2,6>`. The first dim (6 in this case) values are handled by the statements on lines 2442 and 2443. The problem was that loop did not take into account and that therefore starting from `i == 15` the case would fall through to the assert.  

I will add a test later to illustrate the problem and that this fixes it.

for more info, before the change the loop was like this:
```
SymmetricTensor<2,6>::n_independent_components= 21, lpo_data_position = 1
c = 0, i = 6
c = 1, i = 6
c = 2, i = 6
c = 3, i = 6
c = 4, i = 6
c = 5, i = 6
c = 6, i = 6
c = 0, i = 7
c = 1, i = 7
c = 2, i = 7
c = 3, i = 7
c = 4, i = 7
c = 5, i = 7
c = 6, i = 7
c = 7, i = 7
c = 0, i = 8
c = 1, i = 8
c = 2, i = 8
c = 3, i = 8
c = 4, i = 8
c = 5, i = 8
c = 6, i = 8
c = 7, i = 8
c = 8, i = 8
c = 0, i = 9
c = 1, i = 9
c = 2, i = 9
c = 3, i = 9
c = 4, i = 9
c = 5, i = 9
c = 6, i = 9
c = 7, i = 9
c = 8, i = 9
c = 9, i = 9
c = 0, i = 10
c = 1, i = 10
c = 2, i = 10
c = 3, i = 10
c = 4, i = 10
c = 5, i = 10
c = 6, i = 10
c = 7, i = 10
c = 8, i = 10
c = 9, i = 10
c = 10, i = 10
c = 0, i = 11
c = 1, i = 11
c = 2, i = 11
c = 3, i = 11
c = 4, i = 11
c = 5, i = 11
c = 6, i = 11
c = 7, i = 11
c = 8, i = 11
c = 9, i = 11
c = 10, i = 11
c = 11, i = 11
c = 0, i = 12
c = 1, i = 12
c = 2, i = 12
c = 3, i = 12
c = 4, i = 12
c = 5, i = 12
c = 6, i = 12
c = 7, i = 12
c = 8, i = 12
c = 9, i = 12
c = 10, i = 12
c = 11, i = 12
c = 12, i = 12
c = 0, i = 13
c = 1, i = 13
c = 2, i = 13
c = 3, i = 13
c = 4, i = 13
c = 5, i = 13
c = 6, i = 13
c = 7, i = 13
c = 8, i = 13
c = 9, i = 13
c = 10, i = 13
c = 11, i = 13
c = 12, i = 13
c = 13, i = 13
c = 0, i = 14
c = 1, i = 14
c = 2, i = 14
c = 3, i = 14
c = 4, i = 14
c = 5, i = 14
c = 6, i = 14
c = 7, i = 14
c = 8, i = 14
c = 9, i = 14
c = 10, i = 14
c = 11, i = 14
c = 12, i = 14
c = 13, i = 14
c = 14, i = 14
c = 0, i = 15
c = 1, i = 15
c = 2, i = 15
c = 3, i = 15
c = 4, i = 15
c = 5, i = 15
c = 6, i = 15
c = 7, i = 15
c = 8, i = 15
c = 9, i = 15
c = 10, i = 15
c = 11, i = 15
c = 12, i = 15
c = 13, i = 15
c = 14, i = 15

--------------------------------------------------------
An error occurred in line <2453> of file <... dealii/include/deal.II/base/symmetric_tensor.h> in function
    constexpr dealii::TableIndices<2> dealii::internal::SymmetricTensorImplementation::unrolled_to_component_indices(unsigned int, const std::integral_constant<int, 2>&) [with int dim = 6]
The violated condition was: 
    false
Additional information: 
    This exception -- which is used in many places in the library -- usually indicates that some condition which the author of the code thought must be satisfied at a certain point in an algorithm, is not fulfilled. An example would be that the first part of an algorithm sorts elements of an array in ascending order, and a second part of the algorithm later encounters an element that is not larger than the previous one.

There is usually not very much you can do if you encounter such an exception since it indicates an error in deal.II, not in your own program. Try to come up with the smallest possible program that still demonstrates the error and contact the deal.II mailing lists with it to obtain help.

Stacktrace:
-----------
```

and now it completes the loop:
```
SymmetricTensor<2,6>::n_independent_components= 21, lpo_data_position = 1
c = 6, i = 6
c = 6, i = 7
c = 7, i = 7
c = 6, i = 8
c = 7, i = 8
c = 8, i = 8
c = 6, i = 9
c = 7, i = 9
c = 8, i = 9
c = 9, i = 9
c = 6, i = 10
c = 7, i = 10
c = 8, i = 10
c = 9, i = 10
c = 10, i = 10
c = 6, i = 11
c = 7, i = 11
c = 8, i = 11
c = 9, i = 11
c = 10, i = 11
c = 11, i = 11
c = 6, i = 12
c = 7, i = 12
c = 8, i = 12
c = 9, i = 12
c = 10, i = 12
c = 11, i = 12
c = 12, i = 12
c = 6, i = 13
c = 7, i = 13
c = 8, i = 13
c = 9, i = 13
c = 10, i = 13
c = 11, i = 13
c = 12, i = 13
c = 13, i = 13
c = 6, i = 14
c = 7, i = 14
c = 8, i = 14
c = 9, i = 14
c = 10, i = 14
c = 11, i = 14
c = 12, i = 14
c = 13, i = 14
c = 14, i = 14
c = 6, i = 15
c = 7, i = 15
c = 8, i = 15
c = 9, i = 15
c = 10, i = 15
c = 11, i = 15
c = 12, i = 15
c = 13, i = 15
c = 14, i = 15
c = 15, i = 15
c = 6, i = 16
c = 7, i = 16
c = 8, i = 16
c = 9, i = 16
c = 10, i = 16
c = 11, i = 16
c = 12, i = 16
c = 13, i = 16
c = 14, i = 16
c = 15, i = 16
c = 16, i = 16
c = 6, i = 17
c = 7, i = 17
c = 8, i = 17
c = 9, i = 17
c = 10, i = 17
c = 11, i = 17
c = 12, i = 17
c = 13, i = 17
c = 14, i = 17
c = 15, i = 17
c = 16, i = 17
c = 17, i = 17
c = 6, i = 18
c = 7, i = 18
c = 8, i = 18
c = 9, i = 18
c = 10, i = 18
c = 11, i = 18
c = 12, i = 18
c = 13, i = 18
c = 14, i = 18
c = 15, i = 18
c = 16, i = 18
c = 17, i = 18
c = 18, i = 18
c = 6, i = 19
c = 7, i = 19
c = 8, i = 19
c = 9, i = 19
c = 10, i = 19
c = 11, i = 19
c = 12, i = 19
c = 13, i = 19
c = 14, i = 19
c = 15, i = 19
c = 16, i = 19
c = 17, i = 19
c = 18, i = 19
c = 19, i = 19
c = 6, i = 20
c = 7, i = 20
c = 8, i = 20
c = 9, i = 20
c = 10, i = 20
c = 11, i = 20
c = 12, i = 20
c = 13, i = 20
c = 14, i = 20
c = 15, i = 20
c = 16, i = 20
c = 17, i = 20
c = 18, i = 20
c = 19, i = 20
c = 20, i = 20
```

### CODE REVIEW

**Comment by bangerth** [comment]
It would be nice to have a test for this case, though.

**Comment by MFraters** [comment]
> It would be nice to have a test for this case, though.

Yes, I agree. I think I have a good test but it requires me to rebuild to see whether it passes with the fix and fails in the old state. Will update the pull request when that is successful.

**Comment by MFraters** [comment]
I have expanded two tests. 

The first one is the const expression test, because that was my first attempt. Unfortunately this doesn't work for testing the unroll indices function because of the Assert. I left the expended test in anyway because it still expands coverage. The other expended test is the symmetric_tensor_24 test, and I can confirm that this failed in with the old code and with the fix, the test passes on my system.

**Comment by MFraters** [comment]
> Just drop the changes to `tensors/constexpr_symmetric_tensor.cc`. `if constexpr` only works with C++17 support while `DEAL_II_CONSTEXPR` should be usable with C++14.

Ah, oke, I will remove that commit then. 

> Can you still elaborate on why you guarded some of the cheks in that file for higher dimensions?

Sure. The determinant, second invariant and invert function are not implemented for higher dimension than 3. The third invariant is just the determinant, so it doesn't work in higher dimensions as well.

**Comment by masterleinad** [comment]
> Sure. The determinant, second invariant and invert function are not implemented for higher dimension than 3. The third invariant is just the determinant, so it doesn't work in higher dimensions as well.

OK. In the future, we might just call `FullMatrix` functions.

**Pull request merged**
