### PR TITLE
Rename private variables; fix changes.h entry

### PR DESCRIPTION
**Pull request by tamiko**
This commit renames some private variables intrdocued in pull request #1673
to fit our naming rules.

Further, fix some issues with the doxygen documentation.

### CODE REVIEW

**Comment by tamiko** [comment]
This does address all naming issues in pull request #1673.

The one ```AdditionalData``` type still has to be refactored to public inheritance.

**Comment by jppelteret** [comment]
Thanks @tamiko . I was just about to comment to @bangerth that I'd deal with these over the weekend. I appreciate you taking care of this on my behalf.

**Comment by bangerth** [comment]
Excellent, many thanks!

**Comment by jppelteret** [comment]
And apologies for the creating the problem in the first place :-(

**Comment by tamiko** [comment]
@jppelteret No, not at all. Your work is very much appreciated.

My merge was a bit on the "shoot first, ask questions later" side - so it is perfectly fine that I address any remaining issues.

**Pull request merged**
