### PR TITLE
Use AffineConstraints::add_constraint() throughout.

### PR DESCRIPTION
**Pull request by bangerth**
This patch replaces the `add_line()`, `add_entry/entries()`, and `set_inhomogeneity()` calls by `add_constraints() as introduced in #16103 .

There remain a number of places in the test suite where I will have to fix things before the old functions can be deprecated.

Related to #15375.

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]
Thanks. Even though it increases the number of lines because some places are more verbose, we now document much more clearly what is happening. I like this.

This will be in conflict with my change in #16133. Since you have been working with the `AffineConstraints` refactoring before I made these small improvements in the past days, I suggest we wait with my PR until this one is merged and then I will rebase.

**Comment by bangerth** [comment]
Ah, sorry for stepping on your patch here :-(

/rebuild

**Comment by kronbichler** [comment]
There are some tests failing on the serial CI,
```
The following tests FAILED:
	1998 - grid/grid_transform.debug (Failed)
	1999 - grid/grid_transform_02.debug (Failed)
	2000 - grid/grid_transform_03.debug (Failed)
	2001 - grid/grid_transform_3d.debug (Failed)
	2002 - grid/grid_transform_coefficient.debug (Failed)
	2426 - integrators/cochain_01.debug (Failed)
	3263 - non_matching/coupling_09.debug (Failed)
```
I checked two of them and they had the message
```
An error occurred in line <85> of file </jenkins/workspace/dealii-serial_PR-16145/include/deal.II/lac/affine_constraints.templates.h> in function
    void dealii::AffineConstraints<number>::add_constraint(dealii::AffineConstraints<number>::size_type, const dealii::ArrayView<const std::pair<unsigned int, number> >&, number) [with number = double; dealii::AffineConstraints<number>::size_type = unsigned int]
The violated condition was: 
    is_constrained(constrained_dof) == false
Additional information: 
    You cannot add a constraint for a degree of freedom that is already
    constrained.
```

**Comment by bangerth** [comment]
Yes, we had places where we constrain the same DoF twice -- a case we didn't disallow before but that I think is right we disallow now. Let's see if that last commit fixes this -- it does for the handful of tests you mention above.

**Comment by kronbichler** [comment]
Now it seems the cuda-11 clang target fails at compiling the library:
```
n file included from /home/runner/work/dealii/dealii/source/numerics/vector_tools_constraints.cc:17:
In file included from /home/runner/work/dealii/dealii/include/deal.II/numerics/vector_tools_constraints.templates.h:20:
In file included from /home/runner/work/dealii/dealii/include/deal.II/grid/manifold.h:24:
In file included from /home/runner/work/dealii/dealii/include/deal.II/base/array_view.h:26:
In file included from /home/runner/work/dealii/dealii/bundled/boost-1.70.0/include/boost/container/small_vector.hpp:27:
/home/runner/work/dealii/dealii/bundled/boost-1.70.0/include/boost/container/vector.hpp:2766:42: error: call to implicitly-deleted copy constructor of 'boost::container::dtl::insert_emplace_proxy_arg2<boost::container::small_vector_allocator<std::pair<unsigned int, double>, boost::container::new_allocator<void>>, std::pair<unsigned int, double> *, const unsigned int &, double>'
         ( new_buf, new_cap, raw_pos, n, insert_range_proxy);
                                         ^~~~~~~~~~~~~~~~~~
/home/runner/work/dealii/dealii/bundled/boost-1.70.0/include/boost/container/vector.hpp:1885:28: note: in instantiation of function template specialization 'boost::container::vector<std::pair<unsigned int, double>, boost::container::small_vector_allocator<std::pair<unsigned int, double>, boost::container::new_allocator<void>>, void>::priv_forward_range_insert_no_capacity<boost::container::dtl::insert_emplace_proxy_arg2<boost::container::small_vector_allocator<std::pair<unsigned int, double>, boost::container::new_allocator<void>>, std::pair<unsigned int, double> *, const unsigned int &, double>>' requested here
   BOOST_MOVE_ITERATE_0TO9(BOOST_CONTAINER_VECTOR_EMPLACE_CODE)
                           ^
/home/runner/work/dealii/dealii/include/deal.II/numerics/vector_tools_constraints.templates.h:252:44: note: in instantiation of function template specialization 'boost::container::vector<std::pair<unsigned int, double>, boost::container::small_vector_allocator<std::pair<unsigned int, double>, boost::container::new_allocator<void>>, void>::emplace_back<const unsigned int &, double>' requested here
                        constraint_entries.emplace_back(
                                           ^
/home/runner/work/dealii/dealii/include/deal.II/numerics/vector_tools_constraints.templates.h:1029:19: note: in instantiation of function template specialization 'dealii::VectorTools::internal::add_constraint<2>' requested here
                  add_constraint(dof_indices,
                  ^
/home/runner/work/dealii/dealii/include/deal.II/numerics/vector_tools_constraints.templates.h:1274:15: note: in instantiation of function template specialization 'dealii::VectorTools::internal::compute_nonzero_normal_flux_constraints_active_or_level<2, 2>' requested here
    internal::compute_nonzero_normal_flux_constraints_active_or_level(
              ^
/home/runner/work/dealii/dealii/bundled/boost-1.70.0/include/boost/container/detail/advanced_insert_int.hpp:417:25: note: copy constructor of 'insert_emplace_proxy_arg2<boost::container::small_vector_allocator<std::pair<unsigned int, double>, boost::container::new_allocator<void>>, std::pair<unsigned int, double> *, const unsigned int &, double>' is implicitly deleted because base class 'insert_nonmovable_emplace_proxy2<boost::container::small_vector_allocator<std::pair<unsigned int, double>, boost::container::new_allocator<void>>, std::pair<unsigned int, double> *, const unsigned int &, double>' has a deleted copy constructor
BOOST_MOVE_ITERATE_0TO9(BOOST_CONTAINER_ADVANCED_INSERT_INT_CODE)
                        ^
/home/runner/work/dealii/dealii/bundled/boost-1.70.0/include/boost/container/detail/advanced_insert_int.hpp:417:25: note: copy constructor of 'insert_nonmovable_emplace_proxy2<boost::container::small_vector_allocator<std::pair<unsigned int, double>, boost::container::new_allocator<void>>, std::pair<unsigned int, double> *, const unsigned int &, double>' is implicitly deleted because field 'm_p1' is of rvalue reference type 'double &&'
/home/runner/work/dealii/dealii/bundled/boost-1.70.0/include/boost/container/vector.hpp:3007:95: note: passing argument to parameter 'insert_range_proxy' here
      (T* const new_start, size_type new_cap, T* const pos, const size_type n, InsertionProxy insert_range_proxy)
                                                                                              ^
```

**Review by tamiko — APPROVED** [review]

**Comment by bangerth** [comment]
For the record:

Apparently `boost::small_vector::emplace_back` at some point loses track of the value category of one of the arguments and tries to create a `std::pair<unsigned int &, double>` with the reference still on the first argument. That leads to an object that can't be copied, and thus the error. The last commit works around this by explicitly creating the `std::pair<unsigned int, double>` (without reference) we need, and emplacing that at the end of the vector. That's perhaps not as pretty as it could be, but also not terrible.

**Pull request merged**
