### PR TITLE
Fix overwriting of unity files in reconfiguration.

### PR DESCRIPTION
**Pull request by drwells**
One flaw in the unity build system is that it always generates the unity inclusion files when the build system is (re)configured. This results in a lot of extra compilation.

This patch fixes the issue by first writing to a temporary file and then moving it only if it is not equal to the current unity file.

### CODE REVIEW

**Comment by tamiko** [comment]
Good catch!

In the past I have used CMakes `CONFIGURE_FILE(... ... COPY_ONLY)` to do the final copy from the temporary to the destination file. That way you don't need to do the md5 checksumming by hand. May I ask you to quickly test whether that works as well?

**Comment by drwells** [comment]
It is not obvious to me why CONFIGURE_FILE does that (I suppose that it is a nice built-in optimization) but that does work and is a bit less ad-hoc.

**Comment by bangerth** [comment]
Using `CONFIGURE_FILE` this way is a common idiom: it only overwrites the existing file if it really changed. It's been that way since the early autoconf days :-)

**Comment by drwells** [comment]
I have to admit that I have never had to write any autotools/autoconf/autowhatever code, so I don't know any of these tricks.

**Comment by drwells** [comment]
Regardless: thanks for the tip. Its always good learn new CMake things:)

**Pull request merged**
