### PR TITLE
FEEvaluationData: add virtual destructor

### PR DESCRIPTION
**Pull request by peterrum**
... to be able to cast to `FEEvaluation`.

### CODE REVIEW

**Comment by kronbichler** [comment]
Can you give an example use case? I assume you want to `dynamic_cast` to a certain case with an priori unknown number of components, e.g., from several objects with different numbers of components in a vector, so the dynamic cast should help you to infer the right template parameter for the actual evaluator?

**Comment by peterrum** [comment]
In my use case, I would like to have a `FEEvaluation` instance in class, however, I don't know at compile time how many components it needs.

**Comment by peterrum** [comment]
@kronbichler I have added a test!

**Review by kronbichler — APPROVED** [review]
OK, this sounds reasonable. As I always forget these things, can you check the number of additional instructions to be handled for construction and destruction when the class gets virtual? Not that one or two instructions (as I hope) matter much against the ~100 instructions we already have, but we should ensure it does not allocate/deallocate memory.

**Review by kronbichler — APPROVED** [review]

**Comment by kronbichler** [comment]
Failing test is unrelated.

**Comment by kronbichler** [comment]
I checked the instructions and it seems we spend one instruction in the constructor and zero in the destructor if we create an immediate object (on the stack), but there is a deallocation for dynamically allocated objects (e.g. inside a vector or shared/unique pointer).

**Pull request merged**
