### PR TITLE
try to fix sundials tests

### PR DESCRIPTION
**Pull request by davydden**
An attempt to fix tests by reducing the precision by 1 digit.

those tests are failing pretty much everywhere... (( 
https://cdash.kyomu.43-1.org/testSummary.php?project=1&name=sundials%2Fharmonic_oscillator_04.release&date=2017-11-13

https://cdash.kyomu.43-1.org/testSummary.php?project=1&name=sundials%2Fharmonic_oscillator_03.release&date=2017-11-11

common difs:
```
##64      #:4   <== 2.50005
##64      #:4   ==> 2.50004
@ Absolute error = 1.0000000000e-5, Relative error = 3.9999360010e-6
----------------
##67      #:4   <== 2.49989
##67      #:4   ==> 2.4999
```

```
##4       #:4   <== 2.49986
##4       #:4   ==> 2.49988
@ Absolute error = 2.0000000000e-5, Relative error = 8.0004480251e-6
----------------
##5       #:4   <== 2.49997
##5       #:4   ==> 2.49993
```

```
##29      #:2   <== 0.984677
##29      #:2   ==> 0.984676
@ Absolute error = 1.0000000000e-6, Relative error = 1.0155624794e-6
----------------
##31      #:2   <== 0.997044
##31      #:2   ==> 0.997043
```

Note that the middle one does not look like a round-off error, @luca-heltai ping.

### CODE REVIEW

**Comment by bangerth** [comment]
If the last digit differs only by one, then the real difference is in the next digit, and this is typically within the tolerance of numdiff. So usually we just *increased* the precision with which we output the solution by one digit. This should fix all of the cases you show except this one:
```
##4       #:4   <== 2.49986
##4       #:4   ==> 2.49988
@ Absolute error = 2.0000000000e-5, Relative error = 8.0004480251e-6
----------------
##5       #:4   <== 2.49997
##5       #:4   ==> 2.49993
```

**Comment by davydden** [comment]
That’s exactly why I didn’t increase the precision

**Comment by davydden** [comment]
@bangerth i pushed the version with increased precision. I am fine either way as long as it fixes the issue, but increase precision can also trigger other round-off errors in next digits.

**Comment by bangerth** [comment]
Hm, I didn't actually suggest that's what you should do -- I just wanted to point out that it's opposed to the direction we usually go. I don't know what the right solution is here. Do we know what causes the differences? Should we just reduce the number of time steps to get something with smaller differences?

**Comment by davydden** [comment]
Frankly, I don’t know. Hopefully @luca-heltai can comment.

**Comment by davydden** [comment]
p.s. 

> Should we just reduce the number of time steps to get something with smaller differences?

reducing won't help, i think as some of those differences are at the early stages.
Instead, we can output not every time step.

**Comment by davydden** [comment]
> Do you think that its worthwhile just dropping a comment about this above the if statement? 

done.

**Comment by jppelteret** [comment]
Thanks. Lets give @luca-heltai an opportunity to weigh in on this before merging.

**Pull request merged**
