### PR TITLE
Add get_prolongation_matrix() to FE_NedelecSZ.

### PR DESCRIPTION
**Pull request by kinnewig**
This implements `get_prolongation_matrix()` to `FE_NedelecSZ`. 
Furthermore, this also adds the corresponding test.

Unfortunately, it seems quite complicated to implement `get_restriction_matrix()`. Therefore, I only implemented `get_prolongation_matrix()`.

### CODE REVIEW

**Review by bangerth — COMMENTED** [review]
Looks good. Want to add a changelog entry too?

About the restriction matrices: What makes those more difficult than the prolongation matrix? Is it that the orientation of edges needs to be taken into account?

**Comment by kinnewig** [comment]
I have added a change log entry.

> About the restriction matrices: What makes those more difficult than the prolongation matrix? Is it that the orientation of edges needs to be taken into account?

I just looked at how the prolongation matrix and the restriction matrix are computed in the class FE_Nedelec. The implementation of the prolongation matrix is pretty straightforward. 
However, the computation of the restriction matrix is more complex. In FE_Nedelec, the class `initialize_restriction()` is used for that. That function assembles a system_matrix with FE_Nedelec functions with degree - 1 and then computes the projection from the higher to the lower order. As that function is quite lengthy, I haven't studied it in too much detail. I am not even sure if we have to do the same for FE_NedelecSZ...
And based on git blame, the function initialize_restriction() seems to be very old.

**Comment by bangerth** [comment]
OK, thanks for the explanation. I don't recall either. In principle at least this should not be too difficult, but I'm already happy with one step of progress, we don't have to everything all at once.

**Review by bangerth — APPROVED** [review]

**Pull request merged**
