### PR TITLE
move constructor for Quadrature

### LINKED ISSUE #2425: Move constructors for class Quadrature

### PR DESCRIPTION
**Pull request by danshapero**
Resolves #2425.

### CODE REVIEW

**Comment by bangerth** [comment]
Awesome. 

Travis says that something is wrong with the indentation. Can you fix this? Also, please add an entry about these move constructors to the changes.h file.

**Comment by danshapero** [comment]
Done, want me to rebase the branch into 1 commit?

**Comment by bangerth** [comment]
Yes, please at least merge the first and last commit. 

You'll also need to rebase to avoid the merge conflict.

**Comment by danshapero** [comment]
Woops, that should be fixed. Thanks for the patience, this is the first large project I've worked on.

**Pull request merged**
