### PR TITLE
use FEPE::get_normal_vector() to be consistent with FEE

### PR DESCRIPTION
**Pull request by jh66637**
As discussed in https://github.com/dealii/dealii/issues/15302 I am renaming `FEPE::get_normal_vector()` to be consistent with `FEE`

@bergbauer @kronbichler

### CODE REVIEW

**Review by peterrum — APPROVED** [review]
Are there no tests?

**Comment by jh66637** [comment]
I didn't find one. Let's wait if the pipeline fails, but I am pretty confident :)

**Comment by kronbichler** [comment]
Given #15302, we should wait to see what the consensus is on the general names.

**Comment by jh66637** [comment]
As discussed in https://github.com/dealii/dealii/issues/15302 I early-deprecated `get_normal_vector()` in favor of `normal_vector()`. To ensure user code does not break, I copied a test which uses `get_normal_vector()`. This test can be removed when `get_normal_vector()` is eventually completely removed.

**Review by kronbichler — APPROVED** [review]
I agree. However, can we wait with marking it as early deprecation until after the release? My point is that we will have a release in a few weeks, so deprecation warnings start essentially immediately for someone working with `master`. Since this is an interface used in many places, I would prefer to delay the cycle by one year. This means the feature will get deprecated in summer 2024 and removed in 2025, which is more feasible than 2023 and 2024 in my opinion.

**Comment by kronbichler** [comment]
Any additional comments? If not, I suggest to merge this PR in a day or so.

**Review by peterrum — APPROVED** [review]

**Pull request merged**
