### PR TITLE
[9.3.2] Revert "Remove copy from SUNDIALS::KINSOL"

### PR DESCRIPTION
**Pull request by masterleinad**
This reverts commit 422d57b78a191bec3eccbb9258076c21222b3037.

We discussed that we wanted to revert this for the 9.3.2 release to resolve https://github.com/dealii/dealii/issues/12594.

Note that I had to resolve some conflicts but don't have a configuration using Sundials at hand so it would be good if someone else could confirm that this actually works.

### CODE REVIEW

**Comment by tamiko** [comment]
@masterleinad I have quickly pushed a revert of  51b6f10 to this branch as well. I think we need this one as well :-)

**Comment by masterleinad** [comment]
I ended up reverting all the patches in the `sundials` directory and with that, I could get `step-77` working again. If somewhat has a better idea for a minimal set of commits to revert, I'm happy to try that of course.

**Comment by masterleinad** [comment]
Hmmm. `sundials/kinsol_01.debug` and `sundials/kinsol_02.debug` are still failing. Any help with this would be much appreciated.

**Comment by masterleinad** [comment]
OK. It works now.

**Pull request merged**
