### PR TITLE
Fix: 'iota' is not a member of 'std'

### LINKED ISSUE #7155: Compilation issue
Cross post from the mailing list: [**source/base/mpi.cc headers**](https://groups.google.com/forum/#!topic/dealii/UVJwgiIjbJo)

I had some trouble while compiling deal.II on my cluster:

```
[ 70%] Building CXX object source/fe/CMakeFiles/obj_fe_release.dir/fe_tools.cc.o
/home/mwichro/lib/dealii-9.0.0/source/base/mpi.cc: In function 'int dealii::Utilities::MPI::create_group(ompi_communicator_t* const&, ompi_group_t* const&, int, ompi_communicator_t**)':
/home/mwichro/lib/dealii-9.0.0/source/base/mpi.cc:129:7: error: 'iota' is not a member of 'std'
       std::iota(grp_pids.begin(), grp_pids.end(), 0);
       ^~~
/home/mwichro/lib/dealii-9.0.0/source/base/mpi.cc: In function 'int dealii::Utilities::MPI::create_group(ompi_communicator_t* const&, ompi_group_t* const&, int, ompi_communicator_t**)':
/home/mwichro/lib/dealii-9.0.0/source/base/mpi.cc:129:7: error: 'iota' is not a member of 'std'
       std::iota(grp_pids.begin(), grp_pids.end(), 0);
       ^~~
```

I fixed that by adding 
 #include <numeric> 
to  source/base/mpi.cc, according to https://cdcvs.fnal.gov/redmine/projects/larsoft/wiki/Updating_code_to_GCC_6

### PR DESCRIPTION
**Pull request by mwichro**
Fixes GCC compilation error:
 /source/base/mpi.cc:129:7: error: 'iota' is not a member of 'std'
That appears on newer gcc

Fixes #7155

### CODE REVIEW

**Comment by jppelteret** [comment]
@mwichro I edited your original comment to reference the issue that I opened a few minutes ago. When the PR is merged, the issue will be automatically closed.

**Comment by jppelteret** [comment]
@mwichro Unfortunately your commit didn't pass our "indentation test". Clang-format wants the headers to be in alphabetical order. You just need to swap the order of the adjacent headers (or, if you don't have it, download clang format via the instructions on our website, run `make indent`) and push the fixes to the branch. We should be able to squash the two commits on your behalf through the github interface.

**Comment by masterleinad** [comment]
> Sorry, my laptop has been stolen, and I still did not recover my deal.ii settings. Could someone fix this patch?

Sure.

**Comment by bangerth** [comment]
I wanted to squash&merge, but this is not enabled for our repository. I suspect it's going to be easy to find where to enable this, but I'll have to run -- if someone beats me to it, good -- otherwise I'll come back to it.

**Comment by drwells** [comment]
@bangerth I don't recall exactly where we had this discussion, but IIRC at some point in the past we came to a consensus that we wanted to have merge commits. I wouldn't mind voting on it again, but I think that we disabled it for a reason.

**Comment by bangerth** [comment]
Correct -- we want merge conflicts. But I wanted to squash the two commits here into one because the first one adds an include file and the second one just moves it around. It seems silly to keep two commits for this. It also doesn't really hurt -- it's just that the first one doesn't pass the indentation script because of the misplaced include statement.

**Comment by bangerth** [comment]
But I see now that "squash & merge" is described as not creating a merge commit.

Let's just not worry about it here!

**Comment by drwells** [comment]
> we want merge conflicts

Surely you mean merge *commits*, right?

**Comment by bangerth** [comment]
Obviously -- please read my mind ;-)

**Pull request merged**
