### PR TITLE
Add erfc function to FunctionParser.

### PR DESCRIPTION
**Pull request by jperryhouts**
It came up in an Aspect model earlier that it would be useful to have erfc available to the FunctionParser. I don't know of a more modular way to do it than to add it to the builtin functions.

### CODE REVIEW

**Comment by kronbichler** [comment]
The patch looks good. Would you mind adding a small test case for this feature? It would make sense to create a test `DEAL_SRC_DIR/tests/base/function_parser_08.cc` in analogy to `function_parser_05.cc` in the same directory.

If you have not set up deal.II tests yet, you find the basic information here: https://www.dealii.org/developer/developers/testsuite.html
(in particular section 3.8).

**Comment by luca-heltai** [comment]
ping @jperryhouts ?

**Comment by jperryhouts** [comment]
Oh, sorry. I'll add the test this weekend if I have a chance. Monday afternoon at the latest.

Thanks!

**Comment by jperryhouts** [comment]
OK, pending checks I think this is ready to go. Sorry for the delay.

**Comment by kronbichler** [comment]
Great, thanks!

**Pull request merged**
