### PR TITLE
Michelebucelli step 17 simplex cleanup

### PR DESCRIPTION
**Pull request by bangerth**
I can not figure out what is happening with #11757. That test works without problem on my laptop. So I'm pushing it from my machine to a separate PR -- let's see what happens here.

/rebuild

### CODE REVIEW

**Comment by bangerth** [comment]
It fails in the same way as in #11757 even though it works on my system. I'm stumped, and I can't even figure out what precisely the output is on the CI check. Anyone have insight?

**Comment by peterrum** [comment]
@bangerth https://github.com/dealii/dealii/pull/11551#issuecomment-764650004

But I didn't have time to work on that till now.

**Comment by bangerth** [comment]
Rebased on top of #11835.

**Comment by peterrum** [comment]
@bangerth You need to update the tests: the simplex folder has been removed in the meantime and the files/namespaces are also renamed.

**Comment by peterrum** [comment]
The log says:
```
--------------------------------------------------------------------------
[[38647,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: fv-az195-260

Another transport will be used instead, although this may result in
lower performance.

NOTE: You can disable this warning by setting the MCA parameter
btl_base_warn_component_unused to 0.
--------------------------------------------------------------------------
   Number of active cells:       200
   Number of degrees of freedom: 242 (by partition: 242)
   Solver converged in 10 iterations.
```

**Comment by bangerth** [comment]
Huh, what does that even mean? And why does this only happen for this one test, and reproducibly so?

**Comment by Rombur** [comment]
I have seen that warnings in multiple codes. It has to do with some permissions with Docker. For some communications, OpenMPI wants to use a protocol that cannot be used by default in Docker. We should just set the variable to ignore this warnings.

**Comment by bangerth** [comment]
Do you remember how to do that? Separately, why would that only happen to this one test? Does it happen to have an awkward communication pattern?

**Comment by Rombur** [comment]
> Do you remember how to do that?

Yes, it's pretty simple we can simply the environment variables in the jenkins configuration file like [here](https://github.com/ORNL-CEES/DataTransferKit/blob/master/.jenkins#L3-L10)

> Separately, why would that only happen to this one test?

Honestly, I have no idea why this happens for some communications but not others.

**Comment by peterrum** [comment]
I'll try to wrap this PR up in the next days.

**Comment by bangerth** [comment]
Thanks, @peterrum .

**Review by peterrum — APPROVED** [review]

**Pull request merged**
