### PR TITLE
WIP: Integration of Mesquite mesh smoother (+ Verdict quality assessor)

### PR DESCRIPTION
**Pull request by jppelteret**
Following a discussion with @bangerth, this is the full implementation of a wrapper to the Mesquite mesh smoother and Verdict cell quality assessor. I'm just putting the entire piece of work out there, and over time I'll commit smaller pieces of this huge PR. I definitely don't expect anyone to review this as is, but feel free to check it out and make some notes of things we could improve in its implementation.

Note: This works for `Tria` and `p::s::Tria` but not with `p::d::Tria`. This is because Mesquite needs to know the topology of the entire mesh. So I guess it could work with `p::d::Tria` with only 1 level of cells, but I've just disabled it outright. However, it does work with locally refined grids; Mesquite was not designed to work this way, but I figured out that this was possible by smoothing on a level-by-level basis and constraining shared vertices between the levels.

### CODE REVIEW

**Comment by jppelteret** [comment]
A reminder on the purpose of this: https://github.com/dealii/dealii/pull/5971#issuecomment-369842462

**Comment by Rombur** [comment]
I see someone is trying to inflate his stats by committing output files of more than 100,000 lines. That's it, I am adding a `printf` in each CUDA kernel :wink:

**Comment by jppelteret** [comment]
Aah, you caught me out! I'm only in it for the LOCs ;-D

Seriously though, we can evaluate the complexity of the test outputs at a later stage. Maybe they are overkill, but I can't remember offhand.

**Comment by drwells** [comment]
Like #5971 - I believe this can be closed since we are not going to include Mesquite.

**Comment by peterrum** [comment]
> I believe this can be closed since we are not going to include Mesquite.

@jppelteret Can we close this PR? Anyway I am removing the milestone.

**Comment by jppelteret** [comment]
So, after a long time I think that we'll close this PR. The rationale is documented in #12444.

**Pull request closed without merging**
