### PR TITLE
examples/step-69: use std::atomic::load()

### PR DESCRIPTION
**Pull request by tamiko**
This fixes a compilation issue with clang-4

Closes: #9665

### CODE REVIEW

**Comment by tamiko** [comment]
> Who is Dave?

https://www.youtube.com/watch?v=ARJ8cAGm6JE

@bangerth Remember the time when I nearly lost a bet with you?

**Comment by bangerth** [comment]
On 3/15/20 11:00 AM, Matthias Maier wrote:
> <https://www.youtube.com/watch?v=ARJ8cAGm6JE>
> 
> @bangerth <https://github.com/bangerth> Remember the time when I nearly lost a 
> bet with you?

No, what was the story? (I do know who Dave is, though ;-) )

**Comment by tamiko** [comment]
> No, what was the story? (I do know who Dave is, though ;-) )

You had a bet with me that no one of Rannacher's working group will be able to attribute the line "I am sorry Dave ..." to "2001: A Space Odyssey". You almost won - the last person I asked knew the line.

**Comment by bangerth** [comment]
On 3/15/20 7:19 PM, Matthias Maier wrote:
> You had a bet with me that no one of Rannacher's working group will be able to 
> attribute the line "I am sorry Dave ..." to "2001: A Space Odyssey". You 
> almost won - the last person I asked knew the line.
Ha :) So history repeats itself :-)

**Pull request merged**
