### PR TITLE
Prefer emplace_back to push_back.

### PR DESCRIPTION
**Pull request by drwells**
This PR uses the new `emplace_back` function to simplify a lot of code, usually something like

```cpp
std::vector<std::pair<types::global_dof_index, double>> vec;
[...]
vec.push_back(std::pair<types::global_dof_index, double>());
vec.push_back(std::pair<types::global_dof_index, double>(dof, var));
```

to
```cpp
std::vector<std::pair<types::global_dof_index, double>> vec;
[...]
vec.emplace_back();
vec.emplace_back(dof, var);
```

### CODE REVIEW

**Comment by masterleinad** [comment]
How did you choose/find the places to change? Did you run `clang-tidy` with `modernize-use-emplace`?

**Comment by drwells** [comment]
I have tried using clang tidy in the past but it always seemed to replace lines of code with lines containing invalid syntax. I just searched for `push_back` and then changed all the ones I could find which I thought would be clearer with `emplace_back`.

**Comment by bangerth** [comment]
So out of curiosity, what is the difference between the two functions? That `push_back` wants an object that it then copies into the correct location, whereas `emplace_back` constructs one in-place based on the given arguments (which it just forwards to the constructor)? If so, would `emplace_back(obj)` be roughly as efficient as `push_back(std::move(obj))`, assuming that that is valid and that the type of `obj` has a move constructor?

**Comment by drwells** [comment]
Yes (though slightly better, in most cases, than using the move constructor since there is never a temporary object).

**Comment by tamiko** [comment]
cppreference has a good example how the `emplace` functions can be used
to create an object in place [1] (without a call to the move
constructor).

[1] http://en.cppreference.com/w/cpp/container/vector/emplace_back

**Comment by bangerth** [comment]
Nice, thanks for the link! 

I have no objections and since it's been approved, let's merge!

**Pull request merged**
