### PR TITLE
Fail CUDA configuration for CMake version < 3.8

### PR DESCRIPTION
**Pull request by kalj**
New nice functionality in CMake 3.8 enables drastically simplified CUDA setup. See #4361

### CODE REVIEW

**Comment by kalj** [comment]
Fixed typo.

**Comment by kalj** [comment]
Let's start with this, and then we can simplify things in the configuration. @tamiko

**Comment by tamiko** [comment]
@kalj I would like to see the simplifications getting merged alongside this version constraint. There is no technical requirement for constraining the version yet :-)

**Comment by kalj** [comment]
@tamiko Sure, let's put this on hold then.

**Comment by tamiko** [comment]
I will close and we simply add this trivial change to a pr that actually updates/fixes the cuda stuff. :-)

**Pull request closed without merging**
