### PR TITLE
Remove output_file_name variable from tests

### PR DESCRIPTION
**Pull request by masterleinad**

### CODE REVIEW

**Comment by drwells** [comment]
Nice work. May I ask what prompted this change?

**Comment by masterleinad** [comment]
Well, nothing special. I was just copying a test that used `output_file_name` and realized that there lots of other places. Or are you asking for the command?

**Comment by tjhei** [comment]
Thanks. Better would have been to replace the whole block with ``initlog();``

**Comment by drwells** [comment]
@masterleinad I was just curious about why.

**Pull request merged**
