### PR TITLE
Make sure particles also copy their properties when switching property pools.

### LINKED ISSUE #11078: Particle test failures
#11059 caused a number of regressions, as speculated by @kronbichler in a comment in #11059:
```
  particle_handler_08
  particle_handler_11
  particle_handler_12
  particle_handler_13
  particle_handler_15
  particle_handler_16
  particle_handler_17
```
I verified that #11059 is really the cause.

I'll have to investigate.

### PR DESCRIPTION
**Pull request by bangerth**
This fixes a bug introduced in #11059. This used to accidentally work before #11059 because while we switched property pools, we accidentally kept a handle to the old property pool (which in turn worked because the then implementation of property pools didn't keep any state but simply allocated/deallocated memory on the heap). The solution is to copy properties from the old to the new property pool.

Fixes #11078.

### CODE REVIEW

**Review by blaisb — APPROVED** [review]
I know I have no say in this, but to me this seems like a very good PR. No comments here.

**Comment by bangerth** [comment]
@blaisb -- this is a community project. We value everyone's input, regardless of their formal status in the project. You're certainly a respected voice over here, and your input is valued!

**Comment by bangerth** [comment]
As an aside, this patch passed all of the local `particle_handler.*debug` tests. These are apparently not run by the testers, or we would have found the issue in #11059 already.

**Review by kronbichler — APPROVED** [review]

**Comment by blaisb** [comment]
> As an aside, this patch passed all of the local `particle_handler.*debug` tests. These are apparently not run by the testers, or we would have found the issue in #11059 already.

That sentence made me slightly confused :). Do you mean that the testers do not run the particles tests? I thought they did.

**Comment by blaisb** [comment]
> > As an aside, this patch passed all of the local `particle_handler.*debug` tests. These are apparently not run by the testers, or we would have found the issue in #11059 already.
> 
> That sentence made me slightly confused :). Do you mean that the testers do not run the particles tests or just not their debug version?

**Comment by kronbichler** [comment]
>  Do you mean that the testers do not run the particles tests or just not their debug version?

The CI testers (run for every PR) run all debug tests without MPI (around 4300 out of 6200+ tests in debug), as well as a subset of parallel tests (around 600). The parallel particle tests are not part of that selection.

On the other hand, the regression tests listed [here](https://cdash.43-1.org/index.php?project=deal.II) run all or almost all tests, but only around once per day. Here we tolerate some failures (e.g., one of our primary targets https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=12663 has 12 failures right now) that we aim to have fixed before every release at the latest.

**Pull request merged**
