### PR TITLE
Fix memory leak in ADOLC test

### PR DESCRIPTION
**Pull request by masterleinad**

### CODE REVIEW

**Comment by drwells** [comment]
Its probably not worth spending time to fix, but why are we using `new double[n]` and not `std::vector<double>(n)`?

**Comment by davydden** [comment]
> why are we using new double[n] and not std::vector<double>(n)?

@jppelteret probably knows 😄

**Comment by jppelteret** [comment]
@masterleinad Thanks for noticing this.

@drwells Primarily because this is how they demonstrate the libraries usage [in the manual](https://projects.coin-or.org/ADOL-C/browser/stable/2.1/ADOL-C/doc/adolc-manual.pdf?format=raw#page=8), but also because I lifted this test from somewhere else without too much thought. I use `std::vector` in our implementation though :-)

**Comment by drwells** [comment]
I was worried that this library had some crazy requirement on its types that would prevent us from putting them in containers so that is a relief to hear.

**Comment by jppelteret** [comment]
They did plenty of things to make our life difficult, but that was not one of them :-)

**Comment by bangerth** [comment]
I go by the general rule that if I see something that looks fishy, it's more likely a bug than some weird design :-)

**Pull request merged**
