### PR TITLE
Fixes pvtu tensor-valued output

### PR DESCRIPTION
**Pull request by jodlbauer**
Previously, pvtu output threw an exception (no more than 3 components supported), but the corresponding vtu output worked.
Basically copied the checks from the vtu part, taking tensor output into account.
Changed NumberOfComponents to n_components instead of 3.

### CODE REVIEW

**Comment by masterleinad** [comment]
Would you mind squashing your commits and provide a more telling commit message?

**Comment by jodlbauer** [comment]
Finally managed to squash the commit ...

**Comment by masterleinad** [comment]
Do you also have some kind of test at hand we could add?

**Comment by masterleinad** [comment]
Thanks!

**Pull request merged**
