### PR TITLE
Use @cite style for references in step-70.

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Comment by tjhei** [comment]
```
/home/travis/build/dealii/dealii/build/doc/doxygen/tutorial/step-70.h:151: warning: \cite command to 'Freund1995' does not have an associated number
/home/travis/build/dealii/dealii/build/doc/doxygen/tutorial/step-70.h:258: warning: \cite command to 'Freund1995' does not have an associated number
```

**Comment by bangerth** [comment]
Should be fixed now.

**Comment by tjhei** [comment]
```
/home/travis/build/dealii/dealii/build/doc/doxygen/tutorial/step-70.h:594: warning: \cite command to 'Freund95' does not have an associated number
```

**Comment by bangerth** [comment]
Fixed.

**Pull request merged**
