### PR TITLE
CMake: Ensure we use "-pthread" instead of "-lpthread" for thread support

### PR DESCRIPTION
**Pull request by tamiko**
We will need this in 9.4 as well.

### CODE REVIEW

**Comment by tamiko** [comment]
The difference for gcc-9.4.0 (on Ubuntu 20.04.1) is subtle: `-lpthread` results in a final linkage via `collect2 [...] -lpthread -lstdc++ [...]` whereas `-pthread` results in `collect2 [...] -lstdc++ -lpthread [...]` (and some different options for an lto plugin). The former unfortunately leads to linker errors if we happen to use threading facilities from the standard libraries directly <i>in the example step</i> directly.

**Review by tjhei — APPROVED** [review]
Awesome, thank you! Would you mind adding the DSO error message to the comments somewhere.

**Comment by tamiko** [comment]
@tjhei done.

**Review by tjhei — APPROVED** [review]

**Pull request merged**
