### PR TITLE
Trilinos utilities

### PR DESCRIPTION
**Pull request by drwells**
More work on #13949 - we should avoid including Trilinos headers outside of Trilinos-specific files.

### CODE REVIEW

**Review by marcfehling — APPROVED** [review]
Looks to me that you basically move code around.

Introducing `trilinos_utilities.h` might break some user code if they use the `Utilities::Trilinos` namespace. Could you also add a changelog?

**Comment by drwells** [comment]
Fixed!

**Review by marcfehling — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]

**Comment by drwells** [comment]
Let me rebase this and check with tpetra before we merge to avoid a problem like #14192.

**Pull request merged**
