### PR TITLE
fixes a typo in step-4 incorrectly quoting the tutorial wherein the ZeroFunction as first introduced

### PR DESCRIPTION
**Pull request by krishnakumarg1984**

### CODE REVIEW

**Comment by bangerth** [comment]
It again fails with the following message:
```
Running indentation test on Pull Request #9251
invalid author 'Krishnakumar' without firstname and lastname
hint: for possible solutions, consult the webpage:
      https://github.com/dealii/dealii/wiki/Indentation#commit-authorship
```
But the content is ok to merge.

**Comment by krishnakumarg1984** [comment]
OK, this is a bug in `Travis`! Let me explain.

I have basically done a clean-slate PR for this one, carefully ensuring things along every step of the way.

1.   I configured the user.name and user.email appropriately in global mode in git. I checked that these settings are correctly reflected in the user-wide `~/.git/config` file
2.  I now cloned my fork of deal.ii from my GitHub repo to my local hard drive. 
3. Made it even with the upstream `master`
4. Checked-out a completely new branch called `step4_krishna_fix_2`
5. Made these changes/fixes, committed them. Verified in the commit log that my full name and email address appears correctly
6. Pushed the changes in this branch to my GitHub fork, and then raised a PR to deal.ii's `master`


However, `Travis` shows error saying that my name is `Krishnakumar` which does not comply with the project's commit guidelines.  

I am suspecting this is a bug, because I have had a personal Travis account (private account) linked to my GitHub account, in which my account name is Krishnakumar.  Somehow, the CI system sees these PRs originating from my GitHub account, recognizes/associates this with my private Travis account (Krishnakumar), and the build checks fail.

See the below screenshots of a) the build failure, and b) my account name in Travis

image

image

The funny thing is, Travis does not allow me to edit my account name to reflect my full name (Krishnakumar Gopalakrishnan), which means I am left in a limbo state unable to make any PRs/commits to this project :(

**Comment by tjhei** [comment]
> However, `Travis` shows error saying that my name is `Krishnakumar` which does not comply with the project's commit guidelines.
> 
> I am suspecting this is a bug, because I have had a personal Travis account (private account) linked to my GitHub account, in which my account name is Krishnakumar. Somehow, the CI system sees these PRs originating from my GitHub account, recognizes/associates this with my private Travis account (Krishnakumar), and the build checks fail.

I first thought that this can't be what is happening, but I think you are correct: travis does not test your PR with hash b4be25708e but merging your PR into master. The merge commit is 7e5398c and the owner of that commit is your username (without a first&lastname).

Did you set your github firstname and lastname?

**Comment by tjhei** [comment]
And sorry for all the extra problems you had to go through to contribute. Your contributions are very much appreciated.

**Comment by krishnakumarg1984** [comment]
@tjhei Yes. Originally, I couldn't find a setting to change my name in Travis, but your prompt reminded me that I need to have my full name in GitHub profile (I have just now done this).

My changes are anyway very minuscule in the grand-scheme of things for a Wilkinson-prize winning software :).  But, truly appreciate the support of the developers here.
_______

### Long read  (slight aside) 
I do want to raise a concern/point to ponder over for the project's commit guidelines. The first name, last name concept might generally be a western view of writing down a full name. In some other cultures, this might not be wholly true. 

Quoting a relevant section from the [Wikipedia article on Surnames](https://en.wikipedia.org/wiki/Surname),
>Indian surnames may often denote caste, profession, and village and are invariably mentioned along with the personal names. However, hereditary last names are not universal. In Indian passports the surname is shown first. In telephone directories the surname is used for collation. In North Indian states the surname is placed after given names where it exists. __In parts of south India, surname is placed before personal name and in most cases it is only shown as an initial (for example 'S.' for Suryapeth)__.

In my personal instance, hailing from South India, I did not have a surname at all in any of my education/birth records (even though they were all in English). This is why my Github Profile didn't have a surname.  In my home state of Kerala, my official name is `Krishnakumar. G`, and in the neighbouring state of Tamil Nadu, the same person shall be named in documents as `G. Krishnakumar`.  When I applied for my Masters' program in the US in 2009, that's when I realised that passports and university applications needed to have more than 1 character in the last-name field, or else the software won't let me move forward.  Therefore, like most South Indians, I merely expanded my surname as my father's first name :)


I only went to such lengths with this explanation because deal.II truly is a global project with perhaps contributors from different backgrounds, and as its usage spreads to more parts of Asia/Africa, perhaps other contributors might come across some of these quirks.

**Comment by tjhei** [comment]
> @tjhei Yes. Originally, I couldn't find a setting to change my name in Travis, but your prompt reminded me that I may need to change the name to full name in the linked GitHub profile (I have just now done this).

Thank you. Github is still making problems after your change, so I ended up adding a mailmap entry (pushed to this PR). This should fix things, hopefully.



> I do want to raise a concern/point to ponder over for the project's commit guidelines. The first name, last name concept might generally be a western view of writing down a full name. In some other cultures, this might not be wholly true.

Yes, thanks for bringing this up. We will discuss and see how we can change this. The motivation for requiring this is that we had commits from people like "Roland" or "notxor", which made it hard to attribute this to people to give credit later on (see https://www.dealii.org/authors.html).

**Comment by masterleinad** [comment]
Let's just go with this approach here.

**Pull request merged**
