### PR TITLE
Avoid overloaded operator ambiguity with -std=c++20 and clang-10

### PR DESCRIPTION
**Pull request by tamiko**
Second try...

 - reimplement LinearIndexIterator::operator@@ as non-member variants

Closes: #10349

### CODE REVIEW

**Comment by tamiko** [comment]
Documentation will be put back in place in a minute. I first want to test whether this still allows comparison of `::iterator` and `::const_iterator`.

**Comment by drwells** [comment]
> I first want to test whether this still allows comparison of ::iterator and ::const_iterator.

I suspect that it will not because the accessors will have different types.

**Comment by drwells** [comment]
Let me try recompiling with clang to reproduce this.

**Comment by drwells** [comment]
Yup - I can get it. @tamiko do you have time to finish this tonight? If not I can put something together.

**Comment by tamiko** [comment]
@drwells What about I push what I have so far in a minute and you take it from there? (There is a second place where we run into an ambiguity problem).

**Comment by drwells** [comment]
sure :)

**Comment by drwells** [comment]
Do you also get errors with `TriaIterator`?

**Comment by tamiko** [comment]
@drwells Jup. I will take a break from this now. Feel free to take over. Let's have a chat tomorrow morning :-)

**Comment by drwells** [comment]
I think I can hack together a test for this that doesn't require compiling the library. Let me see if this works.

**Comment by bangerth** [comment]
I bet you were planning on that anyway, but just in case: Would you mind adding whatever collection of tests you have into the test suite?

**Comment by tamiko** [comment]
@drwells Have a look at the short testcase at: https://github.com/dealii/dealii/issues/10349
We still have to resolve that in the library (i.e., disabling C++20 support is not a long-term option).

**Comment by drwells** [comment]
@bangerth I can actually use `transpose_table_iterators_0` as a minimal test case that does not require compiling the library :)

**Comment by drwells** [comment]
This is too hard for this hour. I'll try again tomorrow.

**Comment by bangerth** [comment]
:-) Whatever works, though more tests work better ;-)

**Comment by tamiko** [comment]
*mhm* *mhm* *mhm*

Assuming that clang-10 is really correct about its C++20 standard interpretation this is a really big mess.

We rely heavily on operator overloading for most of our `LinearIndexIterator`, `TriaRawIterator` (etc.) class hierarchies. Basically most of our design pattern
  - to implement the `operator@@` family in some low-level class (`LinearIndexIterator`, `TriaAccessorBase`, etc.)
  - return different types `::iterator` and `::const_iterator` for `begin()` and `end()`
has now become ambiguous.

The only thing I managed so far was to gloss over certain places and get parts of the library compiled - but that doesn't guarantee that tests won't fail.

The clean C++20-conformant solution is to remove <b>all</b> logical comparison operators from our low-level classes and offer a single non-member space-ship operator for comparison on the highest level:
```
template<...>
template<typename T, ... constraints on T ...>
inline std::partial_ordering operator<=>(const Iterator<...> &, const T &) {
  // returning std::partial_ordering::less/equivalent/greater/unordered
}
```

**Comment by masterleinad** [comment]
This seems to work
```diff
diff --git a/cmake/checks/check_01_cxx_features.cmake b/cmake/checks/check_01_cxx_features.cmake
index eaa9ab20fa..a274b17c05 100644
--- a/cmake/checks/check_01_cxx_features.cmake
+++ b/cmake/checks/check_01_cxx_features.cmake
@@ -68,15 +68,15 @@ MACRO(_test_cxx20_support)
   CHECK_CXX_SOURCE_COMPILES(
     "
     #include <cmath>
-    #include <ranges>
+    //#include <ranges>
 
     #if __cplusplus < 201709L && !defined(_MSC_VER) && !defined(__INTEL_COMPILER)
     #  error \"insufficient support for C++20\"
     #endif
 
-    #if !(defined __cpp_lib_ranges) || (__cpp_lib_ranges < 201911)
-    #  error \"insufficient support for C++20\"
-    #endif
+    //#if !(defined __cpp_lib_ranges) || (__cpp_lib_ranges < 201911)
+    //#  error \"insufficient support for C++20\"
+    //#endif
 
     int main()
     {
diff --git a/include/deal.II/base/linear_index_iterator.h b/include/deal.II/base/linear_index_iterator.h
index a58c6c3609..3462eea08a 100644
--- a/include/deal.II/base/linear_index_iterator.h
+++ b/include/deal.II/base/linear_index_iterator.h
@@ -250,15 +250,13 @@ public:
    * the same entry in the same container.
    */
   bool
-  operator==(const DerivedIterator &) const;
+  operator==(const LinearIndexIterator &) const;
 
-#ifndef DEAL_II_HAVE_CXX20
   /**
    * Inverse of operator==().
    */
   bool
   operator!=(const DerivedIterator &) const;
-#endif
 
   /**
    * Comparison operator: uses the same ordering as operator<(), but also
@@ -449,16 +447,14 @@ inline typename LinearIndexIterator<DerivedIterator, AccessorType>::pointer
 template <class DerivedIterator, class AccessorType>
 inline bool
 LinearIndexIterator<DerivedIterator, AccessorType>::
-operator==(const DerivedIterator &other) const
+operator==(const LinearIndexIterator<DerivedIterator, AccessorType> &other) const
 {
-  const auto &other_2 = static_cast<decltype(*this) &>(other);
-  return accessor.container == other_2.accessor.container &&
-         accessor.linear_index == other_2.accessor.linear_index;
+  return accessor.container == other.accessor.container &&
+         accessor.linear_index == other.accessor.linear_index;
 }
 
 
 
-#ifndef DEAL_II_HAVE_CXX20
 template <class DerivedIterator, class AccessorType>
 inline bool
 LinearIndexIterator<DerivedIterator, AccessorType>::
@@ -466,7 +462,6 @@ operator!=(const DerivedIterator &other) const
 {
   return !(*this == other);
 }
-#endif
 
 
 
diff --git a/include/deal.II/base/std_cxx20/iota_view.h b/include/deal.II/base/std_cxx20/iota_view.h
index c190efc302..9a5950f3e8 100644
--- a/include/deal.II/base/std_cxx20/iota_view.h
+++ b/include/deal.II/base/std_cxx20/iota_view.h
@@ -17,11 +17,11 @@
 
 #include <deal.II/base/config.h>
 
-#ifdef DEAL_II_HAVE_CXX20
-#  include <ranges>
-#else
-#  include <boost/range/irange.hpp>
-#endif
+//#ifdef DEAL_II_HAVE_CXX20
+//#  include <ranges>
+//#else
+#include <boost/range/irange.hpp>
+//#endif
 
 DEAL_II_NAMESPACE_OPEN
 
@@ -29,7 +29,7 @@ namespace std_cxx20
 {
   namespace ranges
   {
-#ifndef DEAL_II_HAVE_CXX20
+    //#ifndef DEAL_II_HAVE_CXX20
     /**
      * A poor-man's implementation of std::ranges::iota_view using
      * boost's integer_range class. The two classes are not completely
@@ -44,9 +44,9 @@ namespace std_cxx20
      */
     template <typename IncrementableType, typename /*BoundType*/>
     using iota_view = boost::integer_range<IncrementableType>;
-#else
-    using std::ranges::iota_view;
-#endif
+    //#else
+    //    using std::ranges::iota_view;
+    //#endif
   } // namespace ranges
 } // namespace std_cxx20
 
diff --git a/include/deal.II/grid/tria_iterator.h b/include/deal.II/grid/tria_iterator.h
index cefda6d00c..55c1b4113f 100644
--- a/include/deal.II/grid/tria_iterator.h
+++ b/include/deal.II/grid/tria_iterator.h
@@ -379,16 +379,17 @@ public:
   /**
    * Compare for equality.
    */
+  template <typename OtherAccessor>
   bool
-  operator==(const TriaRawIterator &) const;
+  operator==(const TriaRawIterator<OtherAccessor> &) const;
 
-#  ifndef DEAL_II_HAVE_CXX20
+//#  ifndef DEAL_II_HAVE_CXX20
   /**
    * Compare for inequality.
    */
   bool
   operator!=(const TriaRawIterator &) const;
-#  endif
+//#  endif
 
   /**
    * Ordering relation for iterators.
diff --git a/include/deal.II/grid/tria_iterator.templates.h b/include/deal.II/grid/tria_iterator.templates.h
index e873c71ef4..106d92327a 100644
--- a/include/deal.II/grid/tria_iterator.templates.h
+++ b/include/deal.II/grid/tria_iterator.templates.h
@@ -82,15 +82,16 @@ TriaRawIterator<Accessor>::operator=(const TriaRawIterator<Accessor> &i)
 
 
 template <typename Accessor>
+template <typename OtherAccessor>
 inline bool
 TriaRawIterator<Accessor>::
-operator==(const TriaRawIterator<Accessor> &other) const
+operator==(const TriaRawIterator<OtherAccessor> &other) const
 {
   return accessor == other.accessor;
 }
 
 
-#ifndef DEAL_II_HAVE_CXX20
+//#ifndef DEAL_II_HAVE_CXX20
 template <typename Accessor>
 inline bool
 TriaRawIterator<Accessor>::
@@ -98,7 +99,7 @@ operator!=(const TriaRawIterator<Accessor> &other) const
 {
   return !(*this == other);
 }
-#endif
+//#endif
 
 
 template <typename Accessor>
diff --git a/source/dofs/dof_tools.cc b/source/dofs/dof_tools.cc
index 5c7f0d8f3b..a98d17648d 100644
--- a/source/dofs/dof_tools.cc
+++ b/source/dofs/dof_tools.cc
@@ -604,9 +604,8 @@ namespace DoFTools
       local_selected_dofs[i] = component_mask[local_component_asssociation[i]];
 
     // then loop over all cells and do work
-    std::vector<types::global_dof_index>         indices(fe.dofs_per_cell);
-    typename DoFHandlerType::level_cell_iterator c;
-    for (c = dof.begin(level); c != dof.end(level); ++c)
+    std::vector<types::global_dof_index> indices(fe.dofs_per_cell);
+    for (const auto &c : dof.cell_iterators_on_level(level))
       {
         c->get_mg_dof_indices(indices);
         for (unsigned int i = 0; i < fe.dofs_per_cell; ++i)
@@ -1105,10 +1104,7 @@ namespace DoFTools
 
     // this function is similar to the make_sparsity_pattern function, see
     // there for more information
-    typename DoFHandlerType::active_cell_iterator cell =
-                                                    dof_handler.begin_active(),
-                                                  endc = dof_handler.end();
-    for (; cell != endc; ++cell)
+    for (const auto &cell : dof_handler.active_cell_iterators())
       if (cell->subdomain_id() == subdomain_id)
         {
           const unsigned int dofs_per_cell = cell->get_fe().dofs_per_cell;
diff --git a/source/fe/fe_q_bubbles.cc b/source/fe/fe_q_bubbles.cc
index 464d23a9a7..ad7c7fdc51 100644
--- a/source/fe/fe_q_bubbles.cc
+++ b/source/fe/fe_q_bubbles.cc
@@ -137,10 +137,8 @@ namespace internal
               nc, std::vector<types::global_dof_index>(fe.dofs_per_cell));
 
             // now create the mass matrix and all the right_hand sides
-            unsigned int                                           child_no = 0;
-            typename dealii::DoFHandler<dim>::active_cell_iterator cell =
-              dh.begin_active();
-            for (; cell != dh.end(); ++cell, ++child_no)
+            unsigned int child_no = 0;
+            for (const auto &cell : dh.active_cell_iterators())
               {
                 fine.reinit(cell);
                 cell->get_dof_indices(child_ldi[child_no]);
@@ -161,6 +159,7 @@ namespace internal
                           fine.shape_value(i, q) * fe.shape_value(j, quad_tmp) *
                           fine.JxW(q);
                       }
+                ++child_no;
               }
 
             // now solve for all right-hand sides simultaneously
```
I am happy to clean this up a bit and open a pull request.

**Pull request closed without merging**
