### PR TITLE
Removed hp::DoFHandler.

### LINKED ISSUE #11222: Remove `hp::DoFHandler` and `DoFHandlerType`.
The ultimate goal of #10328 and #10333.

After introducing legacy classes (#11220) in the next 9.3 release, we might think of finally removing all the `hp::DoFHandler` leftovers in the following release.

---

For the 9.4 release, we need to consider the following:
- [x] Update template arguments to avoid `DoFHandlerType` and deprecate classes in `Legacy` namespace
#11221
- [x] Update tests to avoid `DoFHandlerType`
~#11241~, #11221
- [x] Remove `DOFHANDLER_TEMPLATE` from `template-arguments.in`
#11221

---

For the 9.5 release, let's get rid of:
- [ ] Remove all classes and functions with `DoFHandlerType` templates (including those in the `Legacy` namespace)
#13808
- [ ] Remove `hp::DoFHandler`
#13808

### LINKED ISSUE #12327: Simplify declaration of DataOutStack
#12322 made me look up the `DataOutStack` class, which has this beautiful declaration:
```
/**
 * @deprecated Use DataOutStack<dim, spacedim> instead.
 */
template <int dim, int spacedim = dim, typename DoFHandlerType = void>
class DataOutStack;


template <int dim, int spacedim, typename DoFHandlerType>
class DataOutStack : public DataOutStack<dim, spacedim, void>
{
public:
  DEAL_II_DEPRECATED
  DataOutStack()
    : DataOutStack<dim, spacedim, void>()
  {}
};


template <int dim, int spacedim>
class DataOutStack<dim, spacedim, void> : public DataOutInterface<dim + 1>
{
  ...
```
It is certainly innovative to derive `X<T>` from `X<void>` -- but also confusing :-)

I think we can remove this now.

### LINKED ISSUE #12340: Simplify declaration of MappingFEField
#12327 points out that `DataOutStack` has a funny declaration. It turns out that `MappingFEField` uses the same "trick" and should also be simplified correspondingly.

```
template <int dim,
          int spacedim            = dim,
          typename VectorType     = Vector<double>,
          typename DoFHandlerType = void>
class MappingFEField;

template <int dim, int spacedim, typename VectorType, typename DoFHandlerType>
class MappingFEField : public MappingFEField<dim, spacedim, VectorType, void>
{
public:
  DEAL_II_DEPRECATED
  MappingFEField(const DoFHandlerType &euler_dof_handler,
                 const VectorType &    euler_vector,
                 const ComponentMask & mask = ComponentMask())
    : MappingFEField<dim, spacedim, VectorType, void>(euler_dof_handler,
                                                      euler_vector,
                                                      mask)
  {}
...
```

### PR DESCRIPTION
**Pull request by marcfehling**
Closes #11222. Closes #12327. Closes #12340.

With the next release, we want to finally get rid of the remains of the `hp::DoFHandler` class.

This involves all occurrences of the now obsolete template parameter `DoFHandlerType` and classes of the `Legacy` namespace that we introduced for backwards compatibility.

PR will remain blocked until we branch off for the 9.4 release.

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]
Reviewing this patch is a significant pleasure.

**Comment by peterrum** [comment]
Maybe, let's wait till the actual release!?

**Comment by marcfehling** [comment]
> Maybe, let's wait till the actual release!?

So, now would be a good time :)

**Review by peterrum — APPROVED** [review]
Let's get this in!

**Pull request merged**
