### PR TITLE
Do not use a plain pointer in PolynomialsABF.

### PR DESCRIPTION
**Pull request by bangerth**
These objects are being copied by the FE_Poly* classes, so plain pointers without
dedicated copy constructors and operators are likely going to lead to memory
corruption. It's not clear to me how this ever worked, but it's easy to fix.

This will yield a merge conflict with #3752, which I will be happy to resolve.
I just wanted to put this up for review already.

### CODE REVIEW

**Comment by drwells** [comment]
You included the `unique_ptr` header but used `shared_ptr` in the code :). Which one did you mean to use?

**Comment by bangerth** [comment]
Fair point -- I tried `unique_ptr` first (simply wanting to clean things up), but it turns out that things don't compile. That meant that there is an actual bug to be fixed. So I used `shared_ptr`.

All updated now, also no longer with the merge conflict.

**Comment by drwells** [comment]
This should fix the problem but I have a few more picky questions.

1. Since all methods of `AnisotropicPolynomials` are `const` can we store a pointer to a constant instance here? That would make it clear that when these things are copied that this is just a shared resource.
2. Do we really need the pointer at all? It will make copying a little cheaper but we don't often need to do that.

**Comment by bangerth** [comment]
Excellent point. We don't need a pointer at all. Changed version attached!

**Pull request merged**
