### PR TITLE
Mixed mesh orientation

### PR DESCRIPTION
**Pull request by drwells**
In 2d, mixed meshes require quadrilaterals with non-standard face orientations. This patch makes that possible for isotropic refinement by generalizing the triangle orientation code to cover both 2d element types.

I'm working on a follow-up patch which gets rid of some of these assumptions in 2d for `FE_Q_Base` etc.

Part of #14667.

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]

**Comment by bangerth** [comment]
Oh, that's a bummer that we can no longer expect to only use standard orientation in 2d :-( I guess that had to happen at some point...

**Comment by drwells** [comment]
It is a bummer that, e.g., `FE_Q` et al have to account for this even when they won't be used that way 99% of the time. I don't think that there is a way to have a `FiniteElement` know whether or not it is in a mixed mesh.

**Comment by bangerth** [comment]
The `Triangulation` class has a function that can be used to query whether a mesh is purely hypercube. But I wouldn't be sure this is faster than what you're doing.

**Comment by drwells** [comment]
Oh, I see - I was thinking of the other mixed-mesh PR.

That would indeed be faster but I think using the same code path for triangles and quadrilaterals in all circumstances is much easier to understand. We can always go back and special-case quadrilaterals if we need to.

**Comment by kronbichler** [comment]
Regarding "much faster", I think we would need to benchmark it. If I remember correctly, I don't think any of those new functions is in the critical path; we do have the access to DoF indices but even there I am not sure how much it really changes, because we have separate paths for the standard case if I remember correctly.

**Pull request merged**
