### PR TITLE
Implement FE_Nothing::operator==().

### PR DESCRIPTION
**Pull request by bangerth**
This is a follow-up to #6367.

### CODE REVIEW

**Comment by bangerth** [comment]
I think this should still make it into 9.0.

**Comment by tamiko** [comment]
`-Werror` triggered an unrelated compilation error as it seems.

**Comment by tjhei** [comment]
> triggered an unrelated compilation error as it seems.

No, I think this was created in this PR, @tamiko

**Comment by bangerth** [comment]
Yes, this PR was buggy with regard to that one `-Werror` tester. Regardless, #6444 should fix the issue. Let's move on.

**Pull request merged**
