### PR TITLE
Do not warn about stuff to do with __attribute__.

### PR DESCRIPTION
**Pull request by bangerth**
This patch addresses the issue raised by @tamiko in #2042, namely disabling `-Wattributes`. The patch adds `-Wno-attributes` to the list of compile flags if available, the point being to silence warnings such as "can't inline a particular function call for a function that has been marked as always_inline".

I didn't want to put this into #2042 because
* It is conceptually a different issue
* I didn't want to put the check for the flag into the same place where I figure out whether `__attribute__((always_inline))` is supported because I think the question of suppressing this kind of warning is germane to other situations where we may use attributes as well; consequently, I think it is not directly tied to #2042 alone.
* I'm unclear what `-Wno-attributes` actually does, and so wanted to discuss this first.

About that last point, the documentation at https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html says this:
```
-Wno-attributes
Do not warn if an unexpected __attribute__ is used, such as unrecognized attributes, function attributes applied to variables, etc. This does not stop errors for incorrect use of supported attributes. 
```
So I'm not quite sure whether this really is the flag we want to enable. On the other hand, the warning message @tamiko shows in #2042 seems to suggest so.

@tamiko -- does this patch fix the problem you see? 

An internet search seems to suggest that the problem you are seeing actually comes from the fact that functions marked as `__attribute__((always_inline))` *also* need to be marked as `inline`, see for example here: http://sourceforge.net/p/opende/bugs/91/ . This would apply to the first two changes in #2042 in `tensor_accessors.h` where we have functions no previously marked as `inline`. All other changes there were to functions already so marked. But I don't know which declarations created the warnings you see.

### CODE REVIEW

**Comment by tamiko** [comment]
@bangerth Let me check whether I get any warnings with ```inline __attribute__((always_inline))```.

**Comment by bangerth** [comment]
@tamiko -- since #2042 is now merged, could you check whether you still get the warnings? If not, please just close this PR.

**Comment by bangerth** [comment]
@tamiko -- did you have a chance to observe whether we need this patch or not? If you don't get any warnings, then we should just close this PR.

**Comment by tamiko** [comment]
On Tue, Jan 19, 2016, at 11:08 CST, Wolfgang Bangerth <notifications@github.com> wrote:

> @tamiko -- did you have a chance to observe whether we need this patch
> or not?

Yes.

> If you don't get any warnings, then we should just close this PR.

We do not need this patch - I do not get any warnings. The PR can be
closed.

**Comment by kronbichler** [comment]
I checked on various versions of Intel, gcc, clang and do not get warnings.

**Pull request closed without merging**
