### PR TITLE
Uniformly separate return type from function declaration

### PR DESCRIPTION
**Pull request by bangerth**
With #6598 out of the way, here is something probably more controversial: We have a mixture of function declarations of the form
```
  short_type  function_name (arg list);
```
and
```
  some_long_type 
  function_name (arg list);
```
where the return type is on a separate line. 

astyle 3.1 has an option where it moves the return type consistently onto the previous line. Unsurprisingly, this introduces a *lot* of churn to the library. Here are two patches that do this for the .h/.cc files and for tests/, respectively.

I have only a mild preference for going this route -- I think it is more consistent and uniformity always makes reading the code easier. What do people think?

### CODE REVIEW

**Comment by bangerth** [comment]
Oh, and why not `examples/`? Because that requires more work. In the .h directory, we always have empty lines between each two functions and so separating the return type remains readable. But in `examples/` we have things like this:
```
class Step6
{
public:
  Step6 ();
  ~Step6 ();

  void
  run ();

private:
  void
  setup_system ();
  void
  assemble_system ();
  void
  solve ();
  void
  refine_grid ();
  void
  output_results (const unsigned int cycle) const;
```
This will require a bit of work, and I'm actually not sure whether I find it more readable here. That's because in the tutorial, we're a bit constrained in vertical space because we need to show commentary and code within no-scroll distance.

**Comment by masterleinad** [comment]
> astyle 3.1 has an option where it moves the return type consistently onto the previous line.

`clang-format` could do the same thing.

**Comment by davydden** [comment]
let's not merge this until we vote between astyle vs clang-format.

**Comment by bangerth** [comment]
@davydden -- I don't really see the connection. We either like this style or we don't. Both tools can give it to us, but the choice of style is independent of the choice of tool.

**Comment by davydden** [comment]
@bangerth 

> I don't really see the connection.

because if `.clang-format` will do the same but with a minor difference (say a white space somewhere) then you have another commit in a week with the same type of change and +50k additions and -30k removals.

**Comment by masterleinad** [comment]
This is superseded by #6667.

**Pull request closed without merging**
