### PR TITLE
Remove tests/mpi/coarse_grid_common.h.

### PR DESCRIPTION
**Pull request by drwells**
I found this curious header file while working on splitting up `tests/mpi/`.

The only functions in this header file that are actually used in this directory are some extra `LogStream::operator<<` overloads: those belong (logically) in `tests.h`.

### CODE REVIEW

**Comment by davydden** [comment]
Looks good to me.

**Comment by tjhei** [comment]
It looks like it is copied from distributed_grids/coarse_grid_common.h

Did you check that those tests still work (because they include these operators twice now).

**Comment by drwells** [comment]
Good question. I just ran all of those tests and they pass.

It looks like `distributed_grids/coarse_grid_common.h` does not contain another copy of the `operator<<` overloads.

**Comment by tjhei** [comment]
You are right, that was just the other functions. :+1:

**Pull request merged**
