### PR TITLE
Correction to BDM degree method

### PR DESCRIPTION
**Pull request by alistairbntl**
*The documentation says this function should return one less than
   the highest polynomial degree. This is consistent with the
   notation used in the literature on BDM polynomials and is what
   I would expect the function to return.
  *However, the function actually returns the degree of the highest
   polynomial degree because it calls PolynomialSpace.degree()
   (note: in this context, PolynomialSpace is the complete polynomial
   space of degree k, next then we add elements from k+1 to complete
   the BDM space) which specifically states it does not return the
   Maxmial degree of the polynomial, but the number of polynomials
   given to the constructor.
  *If I understand correctly, since the number of polynomials given
   to the constructor includes constants, this returns degree+1.
  *To correct this, one needs to be subtracted from the degree of
   the polynomial_space.
  *A typo in the 3D bdm_grad functions has also been corrected

### CODE REVIEW

**Comment by tjhei** [comment]
- is PolynomialsBDM::degree used anywhere (for example in FE_BDM?)
- did you check if any of the BDM tests change? If not, we should probably construct an example where it does make a difference.

**Comment by alistairbntl** [comment]
The only place I've encountered the method is in polynomials_bdm_01, but I haven't looked too hard.  Yes, this change does cause tests to fail (for example: polynomials_bdm_01.cc) but not in the way I expected.
Let me look into this further.  Should I included updated test output files as part of the PR?

**Comment by tjhei** [comment]
Yes, generally we want the tests to pass. So if you make a change to the code and the test output changes, you need to update it. Oh, and convince yourself and us that the change is correct. :-)

**Comment by alistairbntl** [comment]
Thanks @tjhei .  I think the commit is in good shape and all the bdm tests should pass now.

**Comment by kronbichler** [comment]
Could you please an entry to doc/news/changes.h (specific improvements section) where you state that FE_BDM::degree has been fixed? Thanks.

**Comment by alistairbntl** [comment]
@kronbichler: entry updated.  Thanks!

**Pull request merged**
