### PR TITLE
Remove diff from testsuite

### PR DESCRIPTION
**Pull request by drwells**
The test suite now officially requires numdiff. I discussed this with @tamiko.

I also fixed a minor configuration bug.

### CODE REVIEW

**Comment by drwells** [comment]
The large diff comes from converting our single binary output test to use base64 output.

**Comment by masterleinad** [comment]
Hmm.. Looks like the test you changed doesn't pass anymore. Does it work locally?

**Comment by drwells** [comment]
I got different output files on my laptop and workstation. I added the new file.

**Comment by masterleinad** [comment]
Hmm.. still failing and locally for me as well. I get 
[data_out_base_dx.txt](https://github.com/dealii/dealii/files/3508034/data_out_base_dx.txt)

**Comment by drwells** [comment]
Hm. I don't understand DX output so I am going to guess that this is somehow not reproducible between different machines.

**Comment by drwells** [comment]
AFAICT OpenDX is not as popular as it used to be (it looks like the last substantial commit on sourceforge was ten years ago). Would anyone mind if I solved this problem by deprecating our OpenDX code and then deleting the test?

**Comment by bangerth** [comment]
That seems reasonable though drastic. It also doesn't quite fix the issue here unless you decide that we don't need tests for deprecated features any more.

**Comment by drwells** [comment]
I am still not sure why the binary output is suddenly machine-dependent when translated to base64. There should be a way to fix this.

**Comment by drwells** [comment]
@bangerth 
> It also doesn't quite fix the issue here unless you decide that we don't need tests for deprecated features any more.

Ordinarily I support keeping tests for deprecated features, but I very strongly doubt that anyone has used DX for deal.II in the last five years, so I don't mind removing them in this particular case. I would still prefer to fix the test!

**Comment by drwells** [comment]
I fixed the issue: it turns out that DX has a line in the output for the time and date, which (duh) produces different results when converted to base64. I amended the test to delete that line so we should now be set.

**Pull request merged**
