### PR TITLE
typo in qtelles

### PR DESCRIPTION
**Pull request by nicola-giuliani**

### CODE REVIEW

**Comment by kronbichler** [comment]
Do we have a test for `QTelles` that would check this issue to prevent a similar problem to happen again?

**Comment by davydden** [comment]
Please add a changelog in “minor” category

**Comment by nicola-giuliani** [comment]
No, the tests on the singular integration use an exact integration of 1/r assuming that the singularity coincide with one of the vertices of the cell. In that case the problem does not occur.

**Comment by kronbichler** [comment]
@nicola-giuliani thanks for the info. Since you have observed this bug, would you mind adding a small test that does check this? That would be awesome.

**Comment by nicola-giuliani** [comment]
@kronbichler working on it :). It may take some time since I am not fluent in Maple or Mathematica. It will be added asap.

**Pull request merged**
