### PR TITLE
fix typos in step 47

### PR DESCRIPTION
**Pull request by zjiaqi2018**
fix typos in step 47.

### CODE REVIEW

**Comment by tjhei** [comment]
Hi Jiaqi, see the output of "indent": https://github.com/dealii/dealii/pull/10771/checks?check_run_id=929455686#step:4:4
```
invalid author 'Jiaqi_Zhang_CMDA3634_2018Spring' without firstname and lastname

hint: for possible solutions, consult the webpage:
      https://github.com/dealii/dealii/wiki/Indentation#commit-authorship
```

Let us/me know if you need help with that.

**Comment by zjiaqi2018** [comment]
> 
> 
> Hi Jiaqi, see the output of "indent": https://github.com/dealii/dealii/pull/10771/checks?check_run_id=929455686#step:4:4
> 
> ```
> invalid author 'Jiaqi_Zhang_CMDA3634_2018Spring' without firstname and lastname
> 
> hint: for possible solutions, consult the webpage:
>       https://github.com/dealii/dealii/wiki/Indentation#commit-authorship
> ```
> 
> Let us/me know if you need help with that.

Hello Timo,

Since it's my very last commit, do I just need to do git commit --amend --author="Jiaqi Zhang <zjiaqi@vt.edu>" and push to the same branch?

Thanks,
Jiaqi

**Comment by tjhei** [comment]
> Since it's my very last commit, do I just need to do git commit --amend --author="Jiaqi Zhang [zjiaqi@vt.edu](mailto:zjiaqi@vt.edu)" and push to the same branch?

Yes, that should work, but I would set the name and email using ``git config`` and then do
```
git commit --amend --reset-author
```
You can check with ``git log`` if it worked before pushing.

**Comment by zjiaqi2018** [comment]
> 
> 
> > Since it's my very last commit, do I just need to do git commit --amend --author="Jiaqi Zhang [zjiaqi@vt.edu](mailto:zjiaqi@vt.edu)" and push to the same branch?
> 
> Yes, that should work, but I would set the name and email using `git config` and then do
> 
> ```
> git commit --amend --reset-author
> ```
> 
> You can check with `git log` if it worked before pushing.

It failed again. 
I changed my user name and email using git config and then git push --force to the same branch. I can see my name with 'git log':
commit 87bccec6ff4673b872bbe3bebb668deef6e24e25 (HEAD -> step-47_typos, jiaqi/step-47_typos)
Author: Jiaqi Zhang <zjiaqi@vt.edu>
Date:   Thu Jul 30 20:02:56 2020 -0400

    fix typos in step 47

and 'git config --list' shows
user.email=zjiaqi@vt.edu
user.name=Jiaqi Zhang

**Comment by drwells** [comment]
Looks good to me. Since this is just a documentation fix lets merge without waiting on the rest of the CI.

Thanks a lot for finding this and taking the time to improve it @zjiaqi2018 !

**Pull request merged**
