### PR TITLE
remove forward declarations of MappingQ

### LINKED ISSUE #13329: Link to wrong header file in Docu of MappingQ?
The docu of MappingQ https://www.dealii.org/developer/doxygen/deal.II/classMappingQ.html links to the header file

#include <[deal.II/fe/mapping_manifold.h](https://www.dealii.org/developer/doxygen/deal.II/mapping__manifold_8h_source.html)>

but it should be "#include <deal.II/fe/mapping_q.h>" instead, shouldn't it?

### PR DESCRIPTION
**Pull request by nfehn**
closes #13329

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]
Looks good, thank you for testing.

**Review by marcfehling — APPROVED** [review]
Looks good! If it doesn't work, it helps to simply hide the forward declaration from doxygen like here #13276.

**Comment by nfehn** [comment]
@marcfehling I chose your suggestion for `MappingQCache`, where removing the forward declaration is not so easy.

**Review by kronbichler — APPROVED** [review]

**Review by marcfehling — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]

**Pull request merged**
