### PR TITLE
Derandomize CUDA devices used in tests

### PR DESCRIPTION
**Pull request by masterleinad**
As requested in #7398, this PR makes sure that always the first graphics cards are used in `CUDA` tests.

### CODE REVIEW

**Comment by Rombur** [comment]
Since this only changes cuda tests that are not check by this tester. I will merge.

**Comment by masterleinad** [comment]
Oh, I thought you were checking this before merging... Anyway, probably my bad.

**Comment by masterleinad** [comment]
See #7432.

**Comment by Rombur** [comment]
> Oh, I thought you were checking this before merging... Anyway, probably my bad.

No, the testing machine is pretty busy during the day. I cannot hog it to run the testsuite.

**Comment by masterleinad** [comment]
Yes, sorry my fault I should have tested that myself before.

**Pull request merged**
