### PR TITLE
Add more choices to QuadratureSelector

### PR DESCRIPTION
**Pull request by jodlbauer**
Extends the class QuadratureSelector by some more choices.

Some points to discuss (probably):

- So far, I added all quadratures that could be constructed using an unsigned int argument, i.e. including those with default-valued additional arguments. Not sure if those should be selectable or not.
- Removed checks for valid order, this is done anyway by the called quadrature
- Naming of flags

PS: I think I screwed up something before and accidentally closed the previous PR #9037, but couldn't reopen it again ... . So here it is again.

### CODE REVIEW

**Comment by masterleinad** [comment]
Thanks! It would be great if you could extend tests/base`/quadrature_selector.cc` for checking that the new choices work as expected.

**Comment by jodlbauer** [comment]
Added some tests, but haven't run them so far.

**Comment by drwells** [comment]
This looks good.

I can think of one quick improvement, though: could you add something like
```cpp
  Assert(typeid(QuadratureSelector<dim>(name, order).get_points()) 
         == typeid(q.get_points()),
         ExcInternalError());
```
to the test to verify that we really do create the right type?

**Comment by jodlbauer** [comment]
Had to remove the QGaussLog/R choices, as those quadratures only exist for dim = 1.

**Comment by jodlbauer** [comment]
`typeid(QuadratureSelector<dim>(name, order)) == typeid(q)`

will not work, as the left one is still of type QuadratureSelector, but q is QGauss, ... etc.

**Comment by masterleinad** [comment]
You should be able to tets via `dynamic_cast`, though.

**Comment by jodlbauer** [comment]
The problem I see is that after construction, the selector class has no info about which quadrature it corresponds to. The returned quadrature class is only used to call the base Quadrature constructor with resp. points and weights.

**Comment by drwells** [comment]
You're right: this isn't possible to implement.

**Comment by drwells** [comment]
@masterleinad are you happy? If so lets merge :)

**Comment by bangerth** [comment]
Oh, I should have waited for @masterleinad , I guess :-( 

@masterleinad -- if you have more concerns here, then let me know and either I or @jodlbauer will fix them up!

**Comment by masterleinad** [comment]
That's fine with me. I was looking at `QuadratureSelector::create_quadrature` for the `dynamic_cast` check but just realized that this is `private`. The test here should be good enough.

**Pull request merged**
