### PR TITLE
Remove DoFHandlerType from dofs/dof_accessor

### PR DESCRIPTION
**Pull request by peterrum**
After the green light in https://github.com/dealii/dealii/pull/10557#issuecomment-648550001.

part of #10333

### CODE REVIEW

**Comment by bangerth** [comment]
There are some windows-related failures that you'll have to address, though:
```
D:\a\dealii\dealii\include\deal.II\dofs\dof_accessor.templates.h(2283,1): error C2244: 'dealii::DoFCellAccessor<dimension,space_dimension,level_dof_access>::neighbor': unable to match function definition to an existing declaration [D:\a\dealii\dealii\build\source\fe\obj_fe_debug.vcxproj]
D:\a\dealii\dealii\include\deal.II\dofs\dof_accessor.templates.h(2281): message : see declaration of 'dealii::DoFCellAccessor<dimension,space_dimension,level_dof_access>::neighbor' [D:\a\dealii\dealii\build\source\fe\obj_fe_debug.vcxproj]
D:\a\dealii\dealii\include\deal.II\dofs\dof_accessor.templates.h(2283,1): message : definition [D:\a\dealii\dealii\build\source\fe\obj_fe_debug.vcxproj]
D:\a\dealii\dealii\include\deal.II\dofs\dof_accessor.templates.h(2283,1): message : 'dealii::TriaIterator<dealii::DoFCellAccessor<dimension,space_dimension,level_dof_access>> dealii::DoFCellAccessor<dimension,space_dimension,level_dof_access>::neighbor(const unsigned int) const' [D:\a\dealii\dealii\build\source\fe\obj_fe_debug.vcxproj]
D:\a\dealii\dealii\include\deal.II\dofs\dof_accessor.templates.h(2283,1): message : existing declarations [D:\a\dealii\dealii\build\source\fe\obj_fe_debug.vcxproj]
D:\a\dealii\dealii\include\deal.II\dofs\dof_accessor.templates.h(2283,1): message : 'dealii::TriaIterator<dealii::DoFCellAccessor<dealii::DoFAccessor<structdim,dim,spacedim,level_dof_access>::dimension,dealii::DoFAccessor<structdim,dim,spacedim,level_dof_access>::space_dimension,level_dof_access>> dealii::DoFCellAccessor<dimension,space_dimension,level_dof_access>::neighbor(const unsigned int) const' [D:\a\dealii\dealii\build\source\fe\obj_fe_debug.vcxproj]
D:\a\dealii\dealii\include\deal.II\dofs\dof_accessor.templates.h(2302,1): error C2244: 'dealii::DoFCellAccessor<dimension,space_dimension,level_dof_access>::child': unable to match function definition to an existing declaration [D:\a\dealii\dealii\build\source\fe\obj_fe_debug.vcxproj]
D:\a\dealii\dealii\include\deal.II\dofs\dof_accessor.templates.h(2300): message : see declaration of 'dealii::DoFCellAccessor<dimension,space_dimension,level_dof_access>::child' [D:\a\dealii\dealii\build\source\fe\obj_fe_debug.vcxproj]
D:\a\dealii\dealii\include\deal.II\dofs\dof_accessor.templates.h(2302,1): message : definition [D:\a\dealii\dealii\build\source\fe\obj_fe_debug.vcxproj]
  Generating incremental_function.inst
```
+ more.

**Comment by kronbichler** [comment]
> I'm really looking forward to doing a comparison at some point for compile time and shared lib size after all of these changes have been made!

One comparison of library size taken from #9790, comparing a build close before the 9.2 release (May 11) and current master (Jun 24):
```
-rwxr-xr-x. 1 kronbichler users 1573302472 11. Mai 07:21 libdeal_II.g.so.9.2.0-pre*
-rwxr-xr-x. 1 kronbichler users 1441960216 24. Jun 19:16 libdeal_II.g.so.9.3.0-pre*
-rwxr-xr-x. 1 kronbichler users  242043384 11. Mai 07:22 libdeal_II.so.9.2.0-pre*
-rwxr-xr-x. 1 kronbichler users  225385360 24. Jun 19:18 libdeal_II.so.9.3.0-pre*
```
We're making progress.

**Comment by bangerth** [comment]
Yes, and I look forward to even more :-)

**Comment by peterrum** [comment]
I think this time the test will pass!

**Comment by bangerth** [comment]
It does :-)

**Pull request merged**
