### PR TITLE
Use non-reference type for copied RBL element

### LINKED ISSUE #11087: Build warnings with apple-clang 12.0
```
include/deal.II/base/patterns.h:1796:26: warning: loop variable 'entry' is always a copy because the range of type 'const std::__1::vector<bool, std::__1::allocator<bool> >' does not return a reference [-Wrange-loop-analysis]
        for (const auto &entry : t)
                         ^
<PATH>/include/deal.II/base/patterns.h:2100:44: note: in instantiation of member function 'dealii::Patterns::Tools::Convert<std::__1::vector<bool, std::__1::allocator<bool> >, void>::to_string' requested here
        return Convert<std::vector<bool>>::to_string(mask, pattern);
                                           ^
<PATH>/include/deal.II/base/patterns.h:1796:14: note: use non-reference type 'std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > >'
        for (const auto &entry : t)
```
... Jeez, I think that I'm going to leave the rest for now :-D

### PR DESCRIPTION
**Pull request by jppelteret**
Fixes #11087

### CODE REVIEW

**Review by masterleinad — COMMENTED** [review]
The warning only makes sense for `T=std::vector<bool>`.
We should be able to use `std::transform` here instead and delegate these problems to the STL.

**Comment by jppelteret** [comment]
Thanks for the tip! I was going to just replace the RBL by an old-fashioned manual iteration, but your suggestion is much better.

**Review by masterleinad — APPROVED** [review]
If this helps with the warning, I am fine with it.

**Comment by jppelteret** [comment]
> If this helps with the warning, I am fine with it.

It did, thanks. Unfortunately there are a whole bunch more, but I think I'll tackle them another time.

**Review by kronbichler — APPROVED** [review]

**Pull request merged**
