### PR TITLE
CMake: Also propagate compiler and linker flags to the boost check

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Comment by masterleinad** [comment]
The only reason against this I can think of is that propagating `-Werror` might change the `boost` library used. But this should not really be a problem in the end.

**Comment by tamiko** [comment]
@masterleinad We can always filter something like `-Werror` if neededin the future. The reason for that change is that I have a couple of containers that need `CXXFLAGS` to be propagated (for example for `-stdlib=libc++`).

**Pull request merged**
