### PR TITLE
Restrict vector_tools/interpolate_with_material_id_02

### PR DESCRIPTION
**Pull request by masterleinad**
This test uses a `parallel::distributed::Triangulation` object and therefore needs `p4est` support.

### CODE REVIEW

**Comment by masterleinad** [comment]
> It looks like the tester is unhappy due to #7554.

That would be weird... I rebased.

**Comment by drwells** [comment]
The tester didn't print the full output but it did get caught up in `FEValues`, so I assume that #7554 caused the problem; by rebasing I meant that you should include #7557.

**Comment by masterleinad** [comment]
> The tester didn't print the full output but it did get caught up in `FEValues`, so I assume that #7554 caused the problem; by rebasing I meant that you should include #7557.

Sure. I am just surprised that the tester didn't complain for #7554 or #7557 but here.

**Comment by drwells** [comment]
I have no idea how #7554 passed either.

**Comment by bangerth** [comment]
The OS X tester is stuff, but the remaining tests are green -- so I'll merge.

**Pull request merged**
