### PR TITLE
Add a check on whether LLD links shared object

### PR DESCRIPTION
**Pull request by BrettDong**
I found that  [LLD doesn't link a shared object library with object files compiled with Intel C++ Compiler](https://software.intel.com/en-us/comment/1947463). For example, the following code
```c++
#include <iostream>
void foo() { std::cout << "Hello, world!" << std::endl; }
```
compiled by `icpc` will fail to link by `ld.lld` to produce a shared object library:
```
~$ icpc -fuse-ld=lld -shared -o libmylib.so lib.o
ld.lld: error: can't create dynamic relocation R_X86_64_64 against symbol: __gxx_personality_v0 in readonly segment;
recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.so
>>> referenced by lib.cpp
>>>               lib.o:(.gnu.linkonce.d.DW.ref.__gxx_personality_v0+0x0)
```
I was misled by the instruction `ld.lld` outputs, added `-Wl,-z,notext` flag and then `libdeal_II.so` linked successfully, but the generated `libdeal_II.so` was actually faulty and my application crashed in deal.II randomly. All problems disappeared after I tried to use `ld.gold` instead of `ld.lld` when building deal.II.

In this pull request I added a check on whether LLD can link the object file produced by C++ compiler to generate a shared object library. If LLD fails, then it will fallback to GOLD.

I tested this on my local machine. When using GCC, both `DEAL_II_COMPILER_LLD_LINKS_EXEC` and `DEAL_II_COMPILER_LLD_LINKS_SO` checks pass and LLD is finally used. When using Intel Compiler, `DEAL_II_COMPILER_LLD_LINKS_SO` fails and GOLD is used.

### CODE REVIEW

**Comment by BrettDong** [comment]
In CI test log I see
```
-- Performing Test DEAL_II_COMPILER_LLD_LINKS_EXEC
-- Performing Test DEAL_II_COMPILER_LLD_LINKS_EXEC - Failed
-- Performing Test DEAL_II_COMPILER_LLD_LINKS_SO
-- Performing Test DEAL_II_COMPILER_LLD_LINKS_SO - Failed
-- Performing Test DEAL_II_COMPILER_HAS_FUSE_LD_GOLD
-- Performing Test DEAL_II_COMPILER_HAS_FUSE_LD_GOLD - Success
```
Is it possible to view `CMakeFiles/CMakeError.log` to see if `lld` really fails or there is some problem in my code? I think `lld` should handle `gcc` well.

**Comment by tjhei** [comment]
> Is it possible to view `CMakeFiles/CMakeError.log`

No, I am not keeping any other build artifacts, sorry. The machine uses gcc 5 and an ubuntu image that does not have lld installed:
```
$ docker run --rm -it tjhei/candi:v9.0.1-r4
dealii@ceaeef135cba:~$ touch a.cc
dealii@ceaeef135cba:~$ g++ -fuse-ld=ldd a.cc
g++: error: unrecognized command line option ‘-fuse-ld=ldd’
dealii@ceaeef135cba:~$ g++ -fuse-ld=gold a.cc
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o:function _start: error: undefined reference to 'main'
collect2: error: ld returned 1 exit status
```

**Comment by BrettDong** [comment]
> The machine uses gcc 5 and an ubuntu image that does not have lld installed

Thanks for clarification. Then the log output makes sense.

**Comment by BrettDong** [comment]
CI test seems hanging with error message related to jenkins itself...

**Comment by masterleinad** [comment]
Can you just rebase?

**Comment by bangerth** [comment]
This passes the tester, but I don't know whether that's the right approach.

@tamiko ?

**Comment by tjhei** [comment]
> This passes the tester, but I don't know whether that's the right approach.

agreed. I don't understand why we need to do two compile checks instead of extending the test above that is already there.

**Comment by BrettDong** [comment]
> extending the test above that is already there

What do you mean by extending the test? I don’t know how to implement that so I implemented in the way that uses two cmake checks and combine them by AND.

**Comment by masterleinad** [comment]
> > extending the test above that is already there
> 
> What do you mean by extending the test? I don’t know how to implement that so I implemented in the way that uses two cmake checks and combine them by AND.

The question is if you could just have added
```
ADD_FLAGS(CMAKE_REQUIRED_FLAGS "-shared")
ADD_FLAGS(CMAKE_REQUIRED_FLAGS "-fPIC")
```
to the existing test.

**Comment by BrettDong** [comment]
I was not sure if I could just change the existing check to detect linker’s ability to produce a shared library only and no longer checks if it can produce an executable. My original thought is that doing two checks gives more confidence that the compiler front-end is really compatible with linker.

**Comment by tamiko** [comment]
@BrettDong Would you mind to test quickly whether this workaround works for you? At least on my machine it bails out with ICC as intended:
```
-- Performing Test DEAL_II_COMPILER_HAS_FUSE_LD_LLD
-- Performing Test DEAL_II_COMPILER_HAS_FUSE_LD_LLD - Failed
-- Performing Test DEAL_II_COMPILER_HAS_FUSE_LD_GOLD
-- Performing Test DEAL_II_COMPILER_HAS_FUSE_LD_GOLD - Success
```

**Comment by BrettDong** [comment]
The test `DEAL_II_COMPILER_HAS_FUSE_LD_LLD` succeeds on our server:

```
Performing C++ SOURCE FILE Test DEAL_II_COMPILER_HAS_FUSE_LD_LLD succeeded with 
the following output:
Change Dir: /home/binrui/dealii/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_2eb79/fast"
/usr/bin/make -f CMakeFiles/cmTC_2eb79.dir/build.make CMakeFiles/cmTC_2eb79.dir/build
make[1]: Entering directory '/home/binrui/dealii/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_2eb79.dir/src.cxx.o
/opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/bin/mpiicpc    -DDEAL_II_COMPILER_HAS_FUSE_LD_LLD -xSKYLAKE-AVX512 -diag-error warn -Werror -fuse-ld=lld   -o CMakeFiles/cmTC_2eb79.dir/src.cxx.o -c /home/binrui/dealii/build/CMakeFiles/CMakeTmp/src.cxx
error #13000: could not open message catalog file:  diagsc.cat
error #13000: could not open message catalog file:  diagsc.cat
error #13000: could not open message catalog file:  diagsc.cat
Linking CXX executable cmTC_2eb79
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_2eb79.dir/link.txt --verbose=1
/opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/bin/mpiicpc   -DDEAL_II_COMPILER_HAS_FUSE_LD_LLD -xSKYLAKE-AVX512 -diag-error warn -Werror -fuse-ld=lld    -rdynamic CMakeFiles/cmTC_2eb79.dir/src.cxx.o  -o cmTC_2eb79
error #13000: could not open message catalog file:  diagsc.cat
error #13000: could not open message catalog file:  diagsc.cat
make[1]: Leaving directory '/home/binrui/dealii/build/CMakeFiles/CMakeTmp'

Source file was:

    int main() { return 0; }
    
```

**Comment by tamiko** [comment]
@BrettDong I have changed back to precisely the code snippet you had. This works as intended on my machine (configures lld for clang/gcc) and fails for icc with the relocation error you reported:
```
-- Performing Test DEAL_II_COMPILER_HAS_FUSE_LD_LLD
-- Performing Test DEAL_II_COMPILER_HAS_FUSE_LD_LLD - Failed
-- Performing Test DEAL_II_COMPILER_HAS_FUSE_LD_GOLD
-- Performing Test DEAL_II_COMPILER_HAS_FUSE_LD_GOLD - Success
```

```
Run Build Command(s):/usr/sbin/gmake cmTC_24f11/fast && /usr/sbin/gmake -f CMakeFiles/cmTC_24f11.dir/build.make CMakeFiles/cmTC_24f11.dir/build
gmake[1]: Entering directory '/home/tamiko/UNI/Software/dealii/build-2/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_24f11.dir/src.cxx.o
/opt/intel/compilers_and_libraries_2019.4.243/linux/bin/intel64/icpc    -DDEAL_II_COMPILER_HAS_FUSE_LD_LLD -diag-error warn -Werror -shared -fPIC -fuse-ld=lld   -o CMakeFiles/cmTC_24f11.dir/src.cxx.o -c /home/tamiko/workspace/dealii/build-2/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_24f11
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_24f11.dir/link.txt --verbose=1
/opt/intel/compilers_and_libraries_2019.4.243/linux/bin/intel64/icpc   -DDEAL_II_COMPILER_HAS_FUSE_LD_LLD -diag-error warn -Werror -shared -fPIC -fuse-ld=lld    -rdynamic CMakeFiles/cmTC_24f11.dir/src.cxx.o  -o cmTC_24f11 
ld.lld: error: can't create dynamic relocation R_X86_64_64 against symbol: __gxx_personality_v0 in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
```

Please check again.

**Comment by BrettDong** [comment]
Now it works as intended. GCC passes both tests and ICC fails the LLD one. Thanks!

**Pull request merged**
