### PR TITLE
Use ConsensusAlgorithm_NBX in compute_point_to_point_communication_pattern

### PR DESCRIPTION
**Pull request by peterrum**
Before, I forget this again... It is mainly just some of some code up in the file...

ping @kronbichler @tjhei

### CODE REVIEW

**Comment by peterrum** [comment]
I have run 1003 mpi tests. All have passed but one:  `mpi/parallel_vector_16.mpirun=4.debug` for some reason times out...

**Comment by tjhei** [comment]
You are kidding right, #9031 ?

**Comment by peterrum** [comment]
> You are kidding right, #9031 ?

Right: I have a short memory ;)

**Comment by peterrum** [comment]
@tjhei and I am even compiling with `-D DEAL_II_WITH_64BIT_INDICES="ON"` ;)

**Pull request merged**
