### PR TITLE
Cosmetic changes.

### PR DESCRIPTION
**Pull request by bangerth**
There's a show on TV as I write on cosmetic surgery. I thought I'd do some of
my own in a couple of places I found over the past few days.

### CODE REVIEW

**Comment by QiaoLei-88** [comment]
Surprisingly I found no astyle option to deal with spaces before semi-colon.
Do you think it is safe to automize this with "sed -i 's/ *;/;/g'"?

**Comment by bangerth** [comment]
That's essentially what I did by hand. I don't think that t can be done completely automated as there are cases such as
```
  iterator i = x.begin();
  for (; condition(*i); ++i)
    ;
```

I don't think it's too common a case to really worry about it. If you find other cases, feel free to submit a pull request.

**Comment by QiaoLei-88** [comment]
Ah, the newline can be handled by 
 sed -i  -e 'N;s/ *\n *;/;/g;P;D'

But I agree with you that handling all possible odd cases are not that worth to do.

**Comment by bangerth** [comment]
@QiaoLei-88 : You misunderstood: I think that the indentation in my example was *correct*. The code is far easier to read if the semicolon is on a line by itself, rather than at the end of the previous one.

**Comment by bangerth** [comment]
This addresses #1198 .

**Pull request merged**
