### PR TITLE
Break the declaration of the static mapping into a file of its own.

### PR DESCRIPTION
**Pull request by bangerth**
First step to what we discussed today about changing the static Q1 mapping to something more generic.

/rebuild

### CODE REVIEW

**Review by tjhei — APPROVED** [review]

**Comment by tjhei** [comment]
Strictly speaking, this is not backwards compatible, right? Do we want to deprecate the mapping_q1 include file and have it include the new file for now?

**Comment by masterleinad** [comment]
> Strictly speaking, this is not backwards compatible, right? Do we want to deprecate the mapping_q1 include file and have it include the new file for now?

I agree. Also,
```
home/runner/work/dealii/dealii/include/deal.II/matrix_free/cuda_matrix_free.templates.h(659): error: identifier "StaticMappingQ1" is undefined

/home/runner/work/dealii/dealii/include/deal.II/matrix_free/cuda_matrix_free.templates.h(659): error: the global scope has no "mapping"
```

**Comment by masterleinad** [comment]
```
/jenkins/workspace/dealii_PR-11512/include/deal.II/opencascade/utilities.h:296:7: error: ‘StaticMappingQ1’ was not declared in this scope
```

**Review by peterrum — APPROVED** [review]

**Comment by bangerth** [comment]
There is a circular inclusion problem if I wanted to `#include` `mapping_linear.h` from `mapping_q1.h`. But I think I've found a better solution -- stand by.

**Pull request closed without merging**
