### PR TITLE
Add functions to perform CUDA matrix-free loop on the host

### PR DESCRIPTION
**Pull request by Rombur**
Add functions that allow to loop over quadrature points on the host in the same "order" than we loop over them on the device. This is useful when you have complicated material properties and for debugging.

Superseed #10859

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
Fine with me.

**Comment by peterrum** [comment]
I'll have a look in an hour or so. My day quite busy till now...

**Review by peterrum — APPROVED** [review]
Looks good! Thanks for taking my comments into consideration!

**Comment by tjhei** [comment]
This looks like it broke master: 
```
In file included from /jenkins/workspace/dealii_master/include/deal.II/matrix_free/cuda_matrix_free.templates.h:22:0,

                 from /jenkins/workspace/dealii_master/include/deal.II/matrix_free/cuda_tensor_product_kernels.h:24,

                 from /jenkins/workspace/dealii_master/tests/all-headers/test_header.cc:17:

/jenkins/workspace/dealii_master/include/deal.II/matrix_free/cuda_matrix_free.h:333:22: error: ‘dealii::LinearAlgebra::CUDAWrappers’ has not been declared
       LinearAlgebra::CUDAWrappers::Vector<Number> &vec) const;
```
https://jenkins.tjhei.info/blue/organizations/jenkins/dealii/detail/master/1722/pipeline

**Comment by bangerth** [comment]
Ugh -- a good illustration that we shouldn't merge without all statuses are green. How about we just revert?

**Comment by masterleinad** [comment]
See https://github.com/dealii/dealii/pull/11337.

**Comment by Rombur** [comment]
Oops sorry about that. It only breaks three header tests though you can still build and run master.

**Pull request merged**
