### PR TITLE
CMake: lowercase all function and macro names

### PR DESCRIPTION
**Pull request by tamiko**
:sunglasses:

### CODE REVIEW

**Comment by tjhei** [comment]
This is backwards compatible because function and macro names are case insensitive?

**Comment by tamiko** [comment]
@tjhei Precisely.

**Review by tjhei — APPROVED** [review]
(i didn't check the whole diff of course)

**Review by marcfehling — APPROVED** [review]

**Comment by tamiko** [comment]
With two approvals  let's get this in quickly because it (naturally) clashes with all of my other pull requests that I have lined up.

**Comment by tjhei** [comment]
Sure, once the tests finish.

**Comment by drwells** [comment]
Truly the end of an era :)

**Comment by bangerth** [comment]
Ah, well, I guess I come too late -- I found it much easier to read things when function names are uppercase and variable names are lowercase. But I guess I'll be able to make do...

**Comment by bangerth** [comment]
Out of curiosity, how did you create the patch?

**Comment by tamiko** [comment]
@bangerth Have a look at `./contrib/utilities/lowercase_cmake` (that is somewhat buried in this pull request). The script is now also part of our `indent` CI check.

Regarding the question of lowercase / uppercase: lowercasing all function/macro/comman names is something that CMake upstream and almost all projects do.

We still have the convention in our CMake scripts to use all caps variable names for something global and lowercase with leading underscore for local variables. I still think this is a useful convention. Think about everything all caps as being exported to `config.h` or `deal.IIConfig.cmake`.

(We could dispense of the leading underscore - but I don't think this is worth the effort).

I plan to convert most of our macros to functions and remove a significant amount of global variables to modernize our CMake stuff :smile:

**Comment by bangerth** [comment]
Yes, the change is fine, it's mostly for nostalgia that I was attached to it :-) I think the places where I found it matters most is commands like
```
  string(REPLACE "frob" "nicate" outvar ${invar})
```
where `REPLACE` written uppercase makes it clear that it is not a regular argument to the function `string`, but has special meaning. But for sure I'll make do with lowercase in that situation as well :-)

(Of note, even the documentation page at https://cmake.org/cmake/help/latest/command/string.html uses uppercase here, whereas it lower-cases `string` :-) )

**Comment by tamiko** [comment]
> ```
>   string(REPLACE "frob" "nicate" outvar ${invar})
> ```

Keywords such as `REPLACE` have to be all caps, this is a cmake
requirement. So this is not going away :-)

**Pull request merged**
