### PR TITLE
Fix a bug in import function of distributed::Vector.

### PR DESCRIPTION
**Pull request by Rombur**

### CODE REVIEW

**Comment by Rombur** [comment]
This PR fixes the bug but there is another problem because `partitioner` only supports contiguous indices for locally owned elements. What's the reason for that @kronbichler ?

**Comment by Rombur** [comment]
I have updated the test so that it throws the exception `The index set specified in locally_owned_indices is not contiguous`

**Comment by kronbichler** [comment]
@Rombur Supporting non-contiguous locally owned sets is not as easy. For a contiguous set, you can simply broadcast the index range of each processor to all processors so they can identify the owner of a particular global degree of freedom easily. If you cannot do this, you need to go through two levels of communication where one goes through a "dictionary" with contiguous sets that can then provide the answer - that is at least the way Epetra/Tpetra implements the respective algorithms. I have not fully understood these algorithms but all I can say is that they are not completely trivial. Unless somebody wants to implement them I see no pressing reason to do so now...

**Comment by Rombur** [comment]
@kronbichler I see. The problem is, the way I remember it, we wanted to write everything locally in a `ReadWriteVector` and then, do the communication during the call to `import`. Now, if I want to write in the `ReadWriteVector` data  that are associated to a few cells, the indices won't be contiguous. Should we rewrite the `import` function or accept this as a limitation? @bangerth do you have an opinion on this?

**Comment by bangerth** [comment]
I can't say that I understand these issues well enough to suggest how to go. The two of you are the experts on the topic -- whatever you two come up with will be the solution.

Do we currently support the case where the locally owned set is not contiguous?

**Comment by kronbichler** [comment]
>  Now, if I want to write in the ReadWriteVector data that are associated to a few cells, the indices won't be contiguous.

Do you mean the case where we have an index set that does not contain all indices, i.e., where the index set is not surjective? That's indeed something I would accept as a limitation right now. I must admit that I don't really remember what exactly fails in the general non-contiguous case but I remember that it would have taken me more than half a day, including literature study in the Epetra/Tpetra documentation.

> Do we currently support the case where the locally owned set is not contiguous?

The parallel vector does not support this case, and neither do the PETSc wrappers. The Trilinos data structures, on the other hand, do support this. When we do parallel distributed computations, we always start with a contiguous indexing which is reasonably simple to generate and do support numbering into something non-contiguous, but I do not think we could handle all possible cases either.

**Comment by kronbichler** [comment]
@Rombur Do you plan additional changes in this PR? I do not think it is feasible to look for the general solution right now, at least not from my side.

**Comment by bangerth** [comment]
On 01/28/2017 08:51 AM, Martin Kronbichler wrote:
>     Do we currently support the case where the locally owned set is not
>     contiguous?
>
> The parallel vector does not support this case, and neither do the PETSc
> wrappers. The Trilinos data structures, on the other hand, do support this.
> When we do parallel distributed computations, we always start with a
> contiguous indexing which is reasonably simple to generate and do support
> numbering into something non-contiguous, but I do not think we could handle
> all possible cases either.

Right. I was wondering whether we ever create non-contiguous orderings 
ourselves in the DoFRenumbering namespace. But the answer is of course yes: 
via DoFRenumbering::component_wise, for example -- it's just that we typically 
split the vectors so that each vector gets a contiguous piece, but it doesn't 
have to be that way.

**Comment by Rombur** [comment]
Let's just fix the current bug for now. We will think about non-contiguous indices later if we need to.

**Comment by kronbichler** [comment]
Alright, let's merge it.

**Pull request merged**
