### PR TITLE
introduce a parameter to allow FE_Nothing dominate other FEs

### PR DESCRIPTION
**Pull request by davydden**
this is a part of : https://github.com/dealii/dealii/pull/1424

**TODO list:**
- [x] address https://github.com/dealii/dealii/pull/1424#discussion_r38277354

### CODE REVIEW

**Comment by bangerth** [comment]
Let me know when you're done. Please also add an entry to changes.h then.

**Comment by davydden** [comment]
I updated other FEs. should be good...

What do you think about wrapping 
```
      if (fe_nothing->is_dominating())
        {
          return FiniteElementDomination::other_element_dominates;
        }
      else
        {
         // the FE_Nothing has no degrees of freedom and it is typically used in
         // a context where we don't require any continuity along the interface
         return FiniteElementDomination::no_requirements;
        }
```
into a `FiniteElementDomination::Domination FE_Nothing::compare_for_face_domination () const`?

**Comment by bangerth** [comment]
You mean because you want to avoid the code duplication? There should be a way to express face dominations of the kind `fe_A.compare_for_face_domination(fe_B)` in terms of `fe_B.compare_for_face_domination(fe_A)`, i.e., you'd simply forward to the corresponding function in `FE_Nothing`. But you still have to flip the result of that other function. I'm not entirely sure whether the code would be simpler or clearer, with the exception that you wouldn't have to export the `is_dominating()` function.

I think I can live with the patch as is, unless you feel strongly.

Before merging, can you run the indentation script on the patch?

**Comment by davydden** [comment]
i suppose you are right, perhaps it wouldn't be easier to read in such a case.

**Comment by davydden** [comment]
btw, i wasn't sure in which part of the changes to put it. So far it's in `GENERAL IMPROVEMENTS`.

**Comment by bangerth** [comment]
Put it into the specifics section. My mental model is to have things that affect one class or function into specifics, and overarching issues into general. You're really just changing the meaning of one class.

**Pull request merged**
