### PR TITLE
QProjector: internally use the combined orientation.

### PR DESCRIPTION
**Pull request by drwells**
Part of #14667.

This replaces a unique indexing scheme for orientations with the standard one.

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]
Nice simplification!

**Comment by drwells** [comment]
@tjhei looks like the serial tester is out of disk space - can you take a look?

**Review by bangerth — APPROVED** [review]
Good grief, in how many places did we reinvent the wheel (in different and incompatible ways)?

**Comment by drwells** [comment]
I should go back and count when this is all over, but, off the top of my head:
- we sometimes stored 2d orientations with `face_orientation` and sometimes with `face_flip` (and sometimes we just assume everything is well-oriented)
- `std::bitset` in the periodic code
- `0u` is the default in the matrix-free code
- 'orientation, flip, rotation' in `GeometryInfo`
- this weirdness in QProjector
- `orientation + 2 * flip + 4 * rotation` in fe.cc
- the new 'standard' orientation encoding in a single unsigned char

so, at least seven mutually incompatible versions?

**Comment by bangerth** [comment]
Oof...

**Pull request merged**
