### PR TITLE
Remove deprecated MatrixFree::FE[Face]::Evaluation functions taking bools

### PR DESCRIPTION
**Pull request by masterleinad**
Deprecated in https://github.com/dealii/dealii/pull/10369.

### CODE REVIEW

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
You'll have to choose a different changelog file -- this one conflicts.

**Comment by kronbichler** [comment]
Did I miss something, but what about the functions in lines 2208, 2233, 2261, 2283, 2305, 2332, 2638, 2660? I think they all belong to the same category, so we should remove them all together.

**Comment by masterleinad** [comment]
> Did I miss something, but what about the functions in lines 2208, 2233, 2261, 2283, 2305, 2332, 2638, 2660? I think they all belong to the same category, so we should remove them all together.

They got deprecated later (see bbae82777295ce977c9b1550eee4079005dc2912 and https://github.com/dealii/dealii/pull/12350).

**Comment by kronbichler** [comment]
It is strange to remove them not uniformly. Also the other functions were deprecated early enough if I read the log correctly. Anyway, I would be equally happy if you decide to do it in two separate PRs, as long as we do them all now.

**Comment by masterleinad** [comment]
> It is strange to remove them not uniformly. Also the other functions were deprecated early enough if I read the log correctly. Anyway, I would be equally happy if you decide to do it in two separate PRs, as long as we do them all now.

The deprecations here first appeared in 9.3.0-rc1 and the other ones in 9.4.0-rc1. I'm happy to make an exception here though and remove the newer ones here as well.

**Review by kronbichler — APPROVED** [review]
Thank you!

**Pull request merged**
