### PR TITLE
Fix warning in Utilities::MPI for serial release build

### PR DESCRIPTION
**Pull request by peterrum**
Fix warning reported by @rezarastak in #9820.

### CODE REVIEW

**Comment by masterleinad** [comment]
For me, letting `all_reduce` return its result (relying on NRVO) sounds like the better option to avoid the copy.

**Comment by peterrum** [comment]
@masterleinad What do you mean? Will that also work for the other functions, like:

https://github.com/dealii/dealii/blob/c87481cc7e6f18f4dd81726262b7144898343964/include/deal.II/base/mpi.templates.h#L245-L256

https://github.com/dealii/dealii/blob/c87481cc7e6f18f4dd81726262b7144898343964/include/deal.II/base/mpi.templates.h#L260-L267

These functions do not have return values.

**Comment by masterleinad** [comment]
It would work for the other functions better than for the one in question since you need to construct an `ArrayView` in the first place but it's not-owning.
I'd like to understand why we only the warning in this particular case.

**Comment by peterrum** [comment]
@masterleinad I have created a simplified program https://godbolt.org/z/9KN9DF. But unfortunately I don't get any warnings. Could you have a look at compiler flags?

**Comment by masterleinad** [comment]
Here is a reproducer: https://godbolt.org/z/xoZKBF
It also compares default initializing with copy initializing (for an expensive type that would not be usable in the MPI call, but still). I would be fine with default initializing here.
Both copy initializing and default initializing are completely optimized away for `int`, though.

**Comment by peterrum** [comment]
Thanks, @masterleinad ! I have made the modification.

**Pull request merged**
