### PR TITLE
Remove duplicate indices if ArborX is available

### PR DESCRIPTION
**Pull request by fdrmrc**
Related to #15749

This should only fix the failing tests. I haven’t tried to fix the compilation issues occuring with C++20 yet

### CODE REVIEW

**Review by peterrum — APPROVED** [review]

**Comment by tamiko** [comment]
@fdrmrc If this changes output in some tests with arborx you can simply add a test comparison variant ending in `.output.arborx`.

**Comment by fdrmrc** [comment]
@tamiko The output should not change

**Comment by tamiko** [comment]
@fdrmrc Roger!

**Comment by tamiko** [comment]
@fdrmrc Is this pull request ready? (because it is marked as a draft)

**Review by tamiko — APPROVED** [review]

**Comment by fdrmrc** [comment]
Yes it is, thanks for marking it as ready.

**Comment by tamiko** [comment]
https://cdash.dealii.org/build/499

**Pull request merged**
