### PR TITLE
Improve test lac/gmres_eigenvalues

### LINKED ISSUE #6552: Fix lac/gmres_eigenvalues
In an attempt to make ICC happy, #6536 introduced a stopping criterion very close to floating point precision. This makes this test unstable. We should really fix this with something reliable. (That, for example, also survives more aggressive optimization.)

### PR DESCRIPTION
**Pull request by kronbichler**
Fixes #6552.

This test uses much more gentle eigenvalues that are not susceptible to roundoff. Furthermore, limit the number of iterations in GMRES to 20 for the estimates to make sure roundoff has not crept in yet. After all, this test is the eigenvalue approximation of GMRES, not the accuracy of them in the presence of roundoff.

### CODE REVIEW

**Comment by tamiko** [comment]
@kronbichler Very nice!

**Comment by tamiko** [comment]
Let's wait for the tester.

**Comment by masterleinad** [comment]
Passes on my `ICC19` build.

**Pull request merged**
