### PR TITLE
Simplify MappingQ.

### PR DESCRIPTION
**Pull request by bangerth**
This patch moves several functions from the class declaration of MappingQ
into the implementation in the .cc file. These functions are actually generic
and need to move to the MappingQGeneric base class next. This patch facilitates this.

### CODE REVIEW

**Comment by tjhei** [comment]
The diffs are a mess to read so it is impossible to check it, but I'll trust that this is just moving things around.

**Comment by bangerth** [comment]
Yes, really just moving stuff around and generally cleaning things up. Each of the patches individually passed the test suite.

**Comment by bangerth** [comment]
In reference to #1098.

**Comment by bangerth** [comment]
Err, #1198.

**Comment by bangerth** [comment]
Also #1429.

**Pull request merged**
