### PR TITLE
Correct the printed message output from ExcInvalidBoundaryFunction()

### PR DESCRIPTION
**Pull request by jihuan-tian**
The output message generated by ExcInvalidBoundaryFunction() in deal.II/numerics/error_estimator.h, i.e.

> However, the finite element in use has arg2 components,

should be corrected to

> However, the finite element in use has arg3 components

### CODE REVIEW

**Comment by bangerth** [comment]
Very nice! If you want, feel free to also add a file into the directory `doc/news/changes/minor/` like the ones that are already there, explaining the change in one sentence. This way, we have a record of your name and you will be listed as an author of deal.II!

**Comment by jihuan-tian** [comment]
I've created the description file. Thanks for your reminding!

    Best regards!
Jihuan Tian

在 2020年2月10日，上午3:41，Wolfgang Bangerth <notifications@github.com> 写道：

﻿

Very nice! If you want, feel free to also add a file into the directory doc/news/changes/minor/ like the ones that are already there, explaining the change in one sentence. This way, we have a record of your name and you will be listed as an author of deal.II!

**Comment by bangerth** [comment]
Excellent. And nice to see a contribution from Shanghai -- a city I've always had a certain fondness for :-) (Are you at one of the universities there?)

**Comment by jihuan-tian** [comment]
Dear Prof. Bangerth,

Now I work in ABB China Corporate Research Center in Shanghai. I once used deal.ii for magnetic gear simulation in one of our projects.

Meanwhile, I've been keeping math and numerical simulation as my personal research topics. I'm now developing electromagnetic field solvers and also considering to integrate deal.ii with nodejs.

Shanghai is a modernized city with an agreeable climate, a perfect coalesce of both Chinese and western cultures. Have you been to Shanghai before? Here convey my warm welcome to you!

    Best regards!
Jihuan Tian

在 2020年2月11日，上午4:46，Wolfgang Bangerth <notifications@github.com> 写道：

﻿

Excellent. And nice to see a contribution from Shanghai -- a city I've always had a certain fondness for :-) (Are you at one of the universities there?)

**Comment by bangerth** [comment]
Magnetic gear simulations -- very cool!

I was in Shanghai (visiting Shanghai Jiao-Tong) for a 8 days in 2012. I really enjoyed it and have been thinking about ways to spend a semester there ever since. I think that of all of the places I've visited in China (Beijing, Tianjin, Xi'an, Shanghai) it may be my favorite one :-)

We certainly hope that this won't be your last contribution to deal.II!

**Comment by jihuan-tian** [comment]
Thanks for your encouragement! I'll keep on contribute to deal.ii.

在 2020年2月11日，下午1:03，Wolfgang Bangerth <notifications@github.com> 写道：

﻿

Magnetic gear simulations -- very cool!

I was in Shanghai (visiting Shanghai Jiao-Tong) for a 8 days in 2012. I really enjoyed it and have been thinking about ways to spend a semester there ever since. I think that of all of the places I've visited in China (Beijing, Tianjin, Xi'an, Shanghai) it may be my favorite one :-)

We certainly hope that this won't be your last contribution to deal.II!

**Pull request merged**
