### PR TITLE
Tests: Fix various PETSc solver tests

### LINKED ISSUE #2815: petsc/solver_(01|02) and petsc_complex/solver_(01|02) tests broken.
All 4 tests throw a non-convergence error.

Prior to commit 6f53784f (back in 2013) this was apparently undetected. I accidentally checked in wrong comparison files with 6f53784f.

### PR DESCRIPTION
**Pull request by tamiko**
Closes #2815

### CODE REVIEW

**Comment by davydden** [comment]
there is also `solver_real_02`.

**Comment by davydden** [comment]
otherwise LGTM, but I will let someone else to give a quick look and hit `merge` button.

**Comment by tamiko** [comment]
I think I updated ```petsc-complex/solver_real_02``` as well :-)

**Comment by davydden** [comment]
@tamiko _ups_, i did not scroll the `files` and thus did not see `solver_real_02`, my bad

**Comment by tamiko** [comment]
*ping*

**Comment by davydden** [comment]
merged since there were no further comments.

**Comment by tamiko** [comment]
@davydden Thanks a lot :-)

**Pull request merged**
