### PR TITLE
Remove double underscores from include guards.

### PR DESCRIPTION
**Pull request by drwells**
Symbols with '__' in them are reserved by the standard.

### CODE REVIEW

**Comment by bangerth** [comment]
Is that true? My understanding is that only those symbols are reserved that (i) start with a double underscore, and (ii) start with an underscore followed by a capital letter. I didn't know about double underscores in the middle.

**Comment by tamiko** [comment]
I doubt that this is true. According to the C++11 standard `17.6.4.3.2 Global Names [global.names]`:
 - Each name that contains a double underscore __ or begins with an underscore followed by an uppercase letter (2.12) is reserved to the implementation for any use.
 - Each name that begins with an underscore is reserved to the implementation for use as a name in the global namespace.

We should get rid of macros starting with an underscore (in global namespace), but that's it.

**Comment by drwells** [comment]
@tamiko now I am confused: my understanding of that bullet in the standard is that no name may contain a double underscore. Is there a reason that our include guards do not count?

**Comment by bangerth** [comment]
Interesting. I agree that the first bullet point suggests that any occurrence of a double underscore is not allowed.

**Comment by tamiko** [comment]
@drwells My reading comprehension is somewhat limited.

**Comment by tjhei** [comment]
What happened with base/data_out_base_dx.debug ?

**Comment by bangerth** [comment]
Yes, there are numerous `data_out_base_*` tests that now fail for me.

**Comment by drwells** [comment]
I am working on this now.

**Comment by drwells** [comment]
It looks like I made a classic sed error: I wrote `s/dealii__/dealii/` instead of `s/dealii__/dealii_/g` and the one place where we have two on one line, `tests/base/patches.h`, ended up broken.

This is now fixed.

**Comment by davydden** [comment]
failing test `lac/tensor_product_matrix_03.debug` is unrelated.

**Comment by tjhei** [comment]
> It looks like I made a classic sed error:

Yay! Another victory for integration tests.

**Comment by tjhei** [comment]
Oh, and :+1:, the squiggly lines in qtcreator are finally gone!

**Pull request merged**
