### PR TITLE
Add mean_value to cuda_vector.

### PR DESCRIPTION
**Pull request by Rombur**

### CODE REVIEW

**Comment by davydden** [comment]
@Rombur : not related to the PR, but do we have somewhere a list of TODO related to CUDA? A master student of ours (me and @jppelteret ) was interested in CUDA, but I have no idea what is the status. Bruno, would you be willing to create a `Project` in deal.II's account related to CUDA with `cards` on what you are doing with it or plan to do or what has to be done by others if they wish to contribute?

**Comment by Rombur** [comment]
@davydden Sure I will. Right now I am trying to port the work that @kalj has done on MatrixFree (so MatrixFree and FEEvaluation). I am hoping to have something working for simple cases sometime in January. @kalj told me that he wanted to implement wrappers around cusparse but I don't know how far he has progressed.

**Comment by davydden** [comment]
@Rombur thanks, that sounds very interesting!

**Comment by kronbichler** [comment]
This looks good. I checked against the implementation of the l1 norm and everything makes sense (even though I'm not overly familiar with the CUDA syntax). Do we have changelog entries for the cuda stuff already? If not, go ahead and merge yourself.

**Comment by kalj** [comment]
Looks good! I hope to be able to do some more implementation work soon.

**Pull request merged**
