### PR TITLE
DataOutBase: Do not modify precision of ostream

### PR DESCRIPTION
**Pull request by tamiko**
In reference to #4704

### CODE REVIEW

**Comment by tamiko** [comment]
Do not merge - testsuite run pending.

**Comment by bangerth** [comment]
Uhm, why?

**Comment by tamiko** [comment]
@bangerth Because 5 digits of precision are no fun in the testsuite.

**Comment by tamiko** [comment]
I will let bob test this PR again

**Comment by tamiko** [comment]
No failing tests :-]

**Comment by bangerth** [comment]
You're changing more than 200,000 lines of stuff. Is this really necessary?

**Comment by tamiko** [comment]
@bangerth In order to have stable output for optimized test runs, yes.

Further, all of these output files would have to be modified anyway for the removal of floating point manipulation / test mode in LogStream.

**Pull request merged**
