### PR TITLE
Move get_data(), get_face_data(), get_subface_data() definitions dire…

### LINKED ISSUE #1329: Compilation problem with MS Visual Studio
As originally reported by @l-korous in #1321: 

1 more thing - MSVC is unhappy about FE_PolyFace class template - I believe it may be because the instantiations of this template are not explicitely specified. I wonder why it is so, I can try to debug it, but this is my first guess.

```
14>C:\hpfem\dealii\include\deal.II/fe/fe_poly_face.templates.h(95): error C2244: 'dealii::FE_PolyFace::get_data' : unable to match function definition to an existing declaration
14> definition:
14> 'dealii::FiniteElement::InternalDataBase *dealii::FE_PolyFace::get_data(const dealii::UpdateFlags,const dealii::Mapping &,const dealii::Quadrature &) const'
14> existing declarations:
14> 'dealii::FiniteElement::InternalDataBase *dealii::FE_PolyFace::get_data(const dealii::UpdateFlags,const dealii::Mapping &,const dealii::Quadrature &) const'
```

-->> the definition and declaration are identical, this is what I meant by not making much sense, and it is why I deemed it may be an instantiation issue :-)

### PR DESCRIPTION
**Pull request by l-korous**
…ctly to places where declared.

Fixes #1329

### CODE REVIEW

**Comment by bangerth** [comment]
So this now compiles?

**Comment by l-korous** [comment]
Yes it does - I only tried on MSVC though.

**Comment by bangerth** [comment]
OK, it's not pretty, but if it works, I shall be ok with it. Can you add a comment of the form
```
  // NOTE: The following functions have their definitions inlined into the class declaration
  // because we otherwise run into a compiler error with MS Visual Studio
```
to make sure the code is not moved back into the .cc file the next time someone sees it?

**Comment by l-korous** [comment]
Done - could you please check?

**Comment by bangerth** [comment]
Just to leave this here for the record: What version of Visual Studio are you using?

If this is, for example, with VS 2013, we may be able to undo this wart in a couple of years.

**Comment by l-korous** [comment]
Sure - VS 2013 Professional Update 4

**Comment by bangerth** [comment]
This patch caused another ~700 failures because it copied an old version of the functions into the header files, thus discarding the work Hamed Maien had done :-(

I'm working on a patch.

**Comment by bangerth** [comment]
See #1358.

**Pull request merged**
