### PR TITLE
removed compute_2nd as hessians are analytically computed

### PR DESCRIPTION
**Pull request by maieneuro**
Addresses #1542: FiniteElement::compute_2nd, which computes the hessians by finite differencing, is no longer needed as the hessians are now computed analytically.

### CODE REVIEW

**Comment by kronbichler** [comment]
Looks great, thanks.

**Comment by bangerth** [comment]
Would it be possible, as a follow-up, to also remove `FiniteElement::InternalDataBase::differences`, or is this still used somewhere else?

**Comment by bangerth** [comment]
Other than that, any patch that removes 260 lines of code is a good patch :-)

**Comment by maieneuro** [comment]
my bad, I missed those the first time around.

**Pull request merged**
