### PR TITLE
Deal gracefully with replicating an empty array.

### LINKED ISSUE #13460: failure in tests/base/aligned_vector_replicate_04.cc
On my machine and the tester (see https://github.com/dealii/dealii/pull/13458) the test in the subject line fails with
```
n error occurred in line <1735> of file </jenkins/workspace/dealii_PR-13458/include/deal.II/base/aligned_vector.h> in function
    void dealii::AlignedVector<T>::replicate_across_communicator(const MPI_Comm&, unsigned int) [with T = int; MPI_Comm = int]
The violated condition was: 
    ierr == MPI_SUCCESS
Additional information: 
    deal.II encountered an error while calling an MPI function.
    The description of the error provided by MPI is "Invalid argument".
    The numerical value of the original error code is 873088524.
```
This is probably because I am using MPICH as my MPI implementation. It fails on the root process with alloc_size=63, align_by=64, disp_unit=0. Maybe ``disp_unit=0`` is considered invalid?

@bangerth ?

### PR DESCRIPTION
**Pull request by bangerth**
Fixes #13460. It costs an extra `MPI_bcast()` operation, but that is negligible compared to what we do in the rest of the function and in particular to the amount of data replication we hope to avoid with this function.

/rebuild

### CODE REVIEW

**Review by tjhei — APPROVED** [review]

**Comment by tjhei** [comment]
does aligned_vector_replicate_04.cc  pass?

**Comment by bangerth** [comment]
It passed all tests on my laptop, but they also did beforehand.

**Comment by marcfehling** [comment]
You need to rebase after #13465 got merged.

**Review by masterleinad — APPROVED** [review]

**Comment by bangerth** [comment]
Rebased.

**Review by tamiko — APPROVED** [review]

**Pull request merged**
