### PR TITLE
Remove duplicated tests 02

### PR DESCRIPTION
**Pull request by drwells**
This PR continues the work started in b9c64f0dac and removes tests that are identical up to things the compiler sees (e.g., tests that are the same aside from commenting or formatting). I did this by deleting comments with the preprocessor and then running the result through clang-format. The source code for how I accomplished this is in the commit message.

I found one test that needed a minor change to do what it said it did; otherwise I deleted all duplicates that I found (if we made it this far without the test we will probably be okay).

What follows is a brief description of why each test was removed:

aniso/hp_constraints_dgp_nonparametric_08.cc
Identical (up to a comment) to aniso/hp_constraints_dgp_monomial_08.cc

bits/block_sparse_matrix_iterator_03.cc
Same as bits/block_sparse_matrix_iterator_02.cc (up to a comment)

bits/block_vector_vector_01.cc
Identical (up to a comment) to vector_vector_01.cc. This test was never properly implemented.

bits/sparse_matrix_01a.cc
Identical (up to a comment) to bits/sparse_matrix_01.cc

bits/step-16b.cc
Identical (up to a comment) to bits/step-16.cc

bits/vector_25.cc
Identical (up to a comment) to bits/vector_24.cc

The tests
dofs/sparsity_pattern_x.cc
dofs/sparsity_pattern_01_x.cc
dofs/dof_constraints_06_x.cc
dofs/dof_constraints_10_x.cc

were all duplicates (up to comments) of tests without '_x's in their names. This was a result of deleting CompressedSparsityPattern et al.

matrix_free/matrix_vector_14b.cc
This test claims it uses more quadrature points than matrix_free/matrix_vector_14.cc, but does not (and changing the number of quadrature points is nontrivial for this test)

fe/fe_support_points_q_qg0.cc
Identical (up to a blank line) to fe/fe_support_points_q_dg0.cc

fe/fe_values_view_10_single_04.cc
Identical (up to some code formatting and a comment) to fe/fe_values_view_08.cc

The tests
~~full_matrix/complex_complex_full_matrix_04.cc~~
full_matrix/complex_complex_full_matrix_05.cc
full_matrix/complex_complex_full_matrix_09.cc
~~full_matrix/complex_complex_full_matrix_19.cc~~
~~full_matrix/complex_complex_full_matrix_42.cc~~

were all duplicates of the corresponding 'complex_real_full_matrix_*.cc' test. Since the full matrices were real valued I kept the other ones.

grid/have_same_coarse_mesh_04.cc
Completely identical to grid/have_same_coarse_mesh_02.cc

petsc/25.cc
Identical (up to a comment) to petsc/24.cc

trilinos/25.cc
Identical (up to a comment) to trilinos/24.cc

Update: three of the full matrix tests have been fixed to be unique (i.e., they contain matrices of complex numbers with nonzero imaginary components).

### CODE REVIEW

**Comment by bangerth** [comment]
Hm. I wonder if the comments reveal what these tests were *supposed* to do. For example, for the pair
```
aniso/hp_constraints_dgp_nonparametric_08.cc
Identical (up to a comment) to aniso/hp_constraints_dgp_monomial_08.cc
```
I suspect that the second should simply have used a different finite element, but that whoever added the test (probably me) forgot to make that change. It would be a shame to just throw away the test now that we identified what it is missing.

I could imagine similar things for these pairs, and maybe others:
```
bits/sparse_matrix_01a.cc
Identical (up to a comment) to bits/sparse_matrix_01.cc

bits/step-16b.cc
Identical (up to a comment) to bits/step-16.cc

bits/vector_25.cc
Identical (up to a comment) to bits/vector_24.cc
```
Instead of throwing out these tests, would it make sense to just open issues about each pair for which it is simple to identify what is wrong with one or the other of the two tests?

**Comment by drwells** [comment]
Good point: some of these should probably be salvaged. Most seemed to be the result of 'method A was deprecated for method B' where method B already had a test.

I will post better descriptions of the differences later today.

**Comment by drwells** [comment]
It looks like GitHub will highlight diffs for me, so here we go.

# Summary of Differences
## `aniso/hp_constraints_dgp_nonparametric_08.cc`
### diff result
```diff
[wellsd2@rtg1 tests]$ diff aniso/hp_constraints_dgp_nonparametric_08.cc aniso/hp_constraints_dgp_monomial_08.cc
18,19c18
< // check that computation of hp constraints works for DGPNonparametric elements
< // correctly on a uniformly refined mesh for functions of degree q
---
> // check that computation of hp constraints works for DGP_Monomial elements correctly
```

### Conclusion
I am a bit on the fence on this one. This element is not fully implemented: the documentation states that
```
* The purpose of this class is experimental, therefore the implementation
* will remain incomplete.
```
which implies that the output from this test might not make any sense. Otherwise it should be its own test.

## `bits/block_sparse_matrix_iterator_03.cc`
### diff result
```diff
[wellsd2@rtg1 tests]$ diff bits/block_sparse_matrix_iterator_03.cc bits/block_sparse_matrix_iterator_02.cc
18c18,19
< // this test used to fail with aborts
---
> // I believed that this test would trigger a bug. Alas, it doesn't, but it
> // doesn't hurt to test some anyway
```

### Conclusion
The tests are the same so `bits/block_sparse_matrix_iterator_03.cc` may be removed.

## `bits/block_vector_vector_01.cc`
### diff result
```diff
[wellsd2@rtg1 tests]$ diff bits/block_vector_vector_01.cc bits/vector_vector_01.cc
18,19c18
< // check existence of
< // BlockVector<double>::BlockVector(BlockVector<float>). this conversion
---
> // check existence Vector<double>::Vector(Vector<float>). this conversion
```

### Conclusion
This test should probably be fixed (i.e., check the `BlockVector` version, not the `Vector` version).

## `bits/sparse_matrix_01a.cc`
### diff result
```diff
[wellsd2@rtg1 tests]$ diff bits/sparse_matrix_01a.cc bits/sparse_matrix_01.cc
18,21c18,19
< // check setting elements in a sparse matrix using SparseMatrix::set(). make
< // sure they are correct, and make sure that for the nonexisting entries
< // SparseMatrix::el() returns zero (operator() terminates with an exception
< // since sometime in the first half of 2010).
---
> // check setting elements in a sparse matrix using
> // SparseMatrix::set()
```

### Conclusion
These two tests test the same thing in the same way so `bits/sparse_matrix_01a.cc` may be removed.

## `bits/step-16b.cc`
### diff result
```diff
[wellsd2@rtg1 tests]$ diff bits/step-16b.cc bits/step-16.cc
19,20d18
< // this version uses the new unified DoFHAndler instead
< // of the DoFHandler in the test step-16.cc
```

## Conclusion
I honestly don't understand the context of this comment (this must have been done long ago when there were more `DoFHandler` classes). I assume that the old approach has long since been deprecated so `bits/step-16b.cc` may be removed.

## `bits/vector_25.cc`
### diff result
```diff
[wellsd2@rtg1 tests]$ diff bits/vector_25.cc bits/vector_24.cc
17c17,20
< // check Vector::operator = (Scalar) with setting to zero
---
>
> // this test used to check for Vector::clear(). However, this
> // function has since been removed, so we test for v=0 instead, although that
> // may be covered by one of the other tests
42a46
>
```

### Conclusion
These two tests test the same thing in the same way so `bits/vector_25.cc` may be removed.

## All 'sparsity pattern ending with `_x.cc`' tests
These are all results of the deprecation of the various `Compressed*SparsityPattern` classes and may all be removed.

## `fe/fe_support_points_q_qg0.cc`
### diff result
```diff
[wellsd2@rtg1 tests]$ diff fe/fe_support_points_q_qg0.cc fe/fe_support_points_q_dg0.cc
21d20
<
```

### Conclusion
These tests vary by a single blank line and I am pretty sure that `qg0` was a typo and the author meant `dg0`. Hence I believe this test should be removed.

## `fe/fe_values_view_10_single_04.cc`
### diff result
```diff
[wellsd2@rtg1 tests]$ diff fe/fe_values_view_10_single_04.cc fe/fe_values_view_08.cc
19,24c19
< // get_function_hessians for a scalar component and a non-primitive element
< //
< // like _10, but use the values not the hessians. this test exists for
< // an attempt at finding out why results for fe_values_view_10 on
< // branch_distributed_grids at the time of writing differ from those
< // on mainline.
---
> // get_function_values for a scalar component and a non-primitive element
66,68c61,62
<   std::vector<Vector<double> >
<   vector_values (quadrature.size(),
<                  Vector<double>(fe.n_components()));
---
>   std::vector<Vector<double> > vector_values (quadrature.size(),
>                                               Vector<double>(fe.n_components()));
82,83c76,77
<           Assert (std::fabs(scalar_values[q] - vector_values[q](c))
<                   <= 1e-12 * std::fabs(scalar_values[q]),
---
>           Assert (std::fabs (scalar_values[q] - vector_values[q](c))
>                   <= 1e-12 * std::fabs (scalar_values[q]),
```

### Conclusion
As far as I can tell these two tests were designed to test the same thing (function values), so the duplicated test should be removed.

## The full matrix tests
These fill complex valued matrices with real numbers and print them. They are completely duplicated by the equivalent tests starting with the names `full_matrix/complex_real_full_matrix`. Hence I recommend removing these tests.

## `grid/have_same_coarse_mesh_04.cc`
### diff result
```diff
[wellsd2@rtg1 tests]$ diff grid/have_same_coarse_mesh_04.cc grid/have_same_coarse_mesh_02.cc
```
(files are equal)
### Conclusion
The tests are identical so `grid/have_same_coarse_mesh_04.cc` should be removed.

## `matrix_free/matrix_vector_14b.cc`
### diff result
```diff
[wellsd2@rtg1 tests]$ diff matrix_free/matrix_vector_14b.cc matrix_free/matrix_vector_14.cc
18,19c18,22
< // Same as matrix_vector_14, but using more quadrature points than the FE
< // degree would suggest
---
> // this test is similar to matrix_vector_07, but implements the operations for
> // FE_DGP instead of FE_DGQ (where there is no complete tensor product and
> // different routines need to be used). The data is still not very useful
> // because the matrix does not include face terms actually present in an
> // approximation of the Laplacian. It only contains cell terms.
22a26
>
```

### Conclusion
The number of quadrature points is defined in the middle of a function in the common test file `matrix_free/matrix_vector_common.h`, so we can save this test by copying and pasting that file in and changing the correct value.

## `petsc/25.cc`
### diff result
```diff
[wellsd2@rtg1 tests]$ diff petsc/25.cc petsc/24.cc
18c18,20
< // check PETScWrappers::Vector::operator = (PetscScalar) with setting to zero
---
> // this test used to check for PETScWrappers::Vector::clear(). However, this
> // function has since been removed, so we test for v=0 instead, although that
> // may be covered by one of the other tests
```

### Conclusion
These two tests test the same thing in the same way so `petsc/25.cc` may be removed.


## `trilinos/25.cc`
### diff result
```diff
[wellsd2@rtg1 tests]$ diff trilinos/25.cc trilinos/24.cc
18c18,20
< // check TrilinosWrappers::Vector::operator = (TrilinosScalar) with setting to zero
---
> // this test used to check for TrilinosWrappers::Vector::clear(). However, this
> // function has since been removed, so we test for v=0 instead, although that
> // may be covered by one of the other tests
```

## Conclusion
These two tests test the same thing in the same way so `trilinos/25.cc` may be removed.

# Summary
Lets definitely fix
* `bits/block_vector_vector_01.cc`
* `matrix_free/matrix_vector_14b.cc`

I am not in favor of fixing `aniso/hp_constraints_dgp_nonparametric_08.cc`
because the underlying finite element is not done. The rest should be removed.

**Comment by drwells** [comment]
I'll push more commits once we agree on which are worth saving.

**Comment by bangerth** [comment]
fixed by #3000
==============
aniso/hp_constraints_dgp_nonparametric_08
bits/block_vector_vector_01.cc

yes, should be deleted
======================
bits/block_sparse_matrix_iterator_03.cc
bits/sparse_matrix_01a.cc
bits/step-16b.cc
   (this refers to the fact that we used to have a separate
    class MGDoFHandler whose functionality was later merged into
    ::DoFHandler, but the old name was retained for a while
    for backward compatibility; the comment is unreadable
    because we later apparently did a blanket rename of
    MGDoFHandler to DoFHandler)
bits/vector_25.cc
All 'sparsity pattern ending with _x.cc' tests
fe/fe_support_points_q_qg0.cc
fe/fe_values_view_10_single_04.cc
grid/have_same_coarse_mesh_04.cc
petsc/25.cc
trilinos/25.cc


others
======
About the full matrix tests: can you explain which pairs of tests you compare? You make it sound like, for example, the `full_matrix/full_matrix_01.cc` and `complex_real_full_matrix_01.cc` tests are the same, but they are not -- they use a different underlying storage type.

`matrix_free_14{,b}`
====================
I lack the technical expertise. Maybe @kronbichler can comment?

**Comment by bangerth** [comment]
I should note that while the `FE_DGPNonparametric` element has long said that it's experimental, it actually does what it's supposed to do in most cases.

**Comment by drwells** [comment]
I marked this as WIP since we don't know what to do about the matrix free test yet.

I should have been clearer in the discussion of the full matrix tests. Consider `tests/full_matrix/complex_complex_full_matrix_04.cc`. This test is identical (up to a comment) to `tests/full_matrix/complex_real_full_matrix_04.cc`:
```diff
$ diff full_matrix/complex_complex_full_matrix_04.cc full_matrix/complex_real_full_matrix_04.cc
19c19
< // complex-valued matrices and vectors; this time we actually store complex values
---
> // complex-valued matrices and vectors, even though we only store real values
```

where `tests/full_matrix/complex_complex_full_matrix_04.cc` is mostly

```cpp
template <typename number>
void
check ()
{
  const std::complex<number> array[] = { 1, 2, 3, 4, 5,
                                         6, 7, 8, 9, 0,
                                         1, 2, 3, 4, 5,
                                         6, 7, 8, 9, 0,
                                         1, 2, 3, 4, 5
                                       };

  FullMatrix<std::complex<number> > m (5,5,array);

  print_matrix (m);
}
```
so (unlike what the comment claims) the test just examines a `FullMatrix<std::complex<number>>` filled with incidentally real numbers, which is exactly what `tests/full_matrix/complex_real_full_matrix_04.cc` claims to do (and does).

**Comment by bangerth** [comment]
I see. I think it would be worth fixing this as well. Does this apply to all of the `full_matrix/complex_{complex,real}_full_matrix_*` tests or only to a subset?

**Comment by drwells** [comment]
It looks like `full_matrix/complex_complex_full_matrix_12.cc` might be a duplicate (it checks a matrix of all zeros) but all of the other `complex_complex_full_matrix*` tests use `make_complex_matrix` to fill them with complex values with nonzero imaginary component.

**Comment by drwells** [comment]
It looks like `full_matrix/complex_complex_full_matrix_12.cc` might be a duplicate (it checks a matrix of all zeros) but all of the other `complex_complex_full_matrix*` tests use `make_complex_matrix` to fill them with complex values with nonzero imaginary component.

**Comment by bangerth** [comment]
And then there is the _04 test that uses real values for both cases (when they should be complex-valued for the `complex_complex_` case). I'm going to fix that one right away. Proceed with dealing with the other tests as you suggest.

**Comment by drwells** [comment]
I fixed two of the other complex tests. I think that the ones where we just copy the identity matrix can go.

**Comment by bangerth** [comment]
OK. I would suggest you do as you say, and then feel free to merge yourself. Thanks for figuring this out!

**Comment by drwells** [comment]
I edited the commit message a bit but otherwise this is the same.

To be clear, we are okay with deleting the repeated matrix free test? If so this can be merged.

**Comment by bangerth** [comment]
@kronbichler is on vacation, so I'm going to make the executive decision and say "yes". They can always be restored if necessary, but if they are truly identical, there really doesn't seem to be much of a reason.

**Comment by kronbichler** [comment]
@drwells Indeed, the `matrix_free/matrix_vector_14b` test was lacking the quadrature points. :+1: for finding a bug in the tests!

**Pull request merged**
