### PR TITLE
Fixed bug in SparseDirectUMFPACK #12916

### PR DESCRIPTION
**Pull request by kuljitvirk**
Updated author name as requested to be a full name.

### CODE REVIEW

**Review by bangerth — COMMENTED** [review]
Let's see what the tester says here :-)

/rebuild

**Comment by bangerth** [comment]
Assuming that this passes the test suite, would you mind also adding an entry in the `doc/news/changes/minor` directory that follows the same scheme as the files already there?

**Comment by bangerth** [comment]
Would you still be willing to add an entry to the changelog?

**Review by jppelteret — APPROVED** [review]
Looks good @kuljitvirk, but perhaps you could add a changelog entry as @bangerth requested.

**Comment by masterleinad** [comment]
> Looks good @kuljitvirk, but perhaps you could add a changelog entry as @bangerth requested.

I think we should just merge the pull request since it fixes a bug. A changelog entry can be added later.

**Review by masterleinad — APPROVED** [review]

**Comment by kuljitvirk** [comment]
I will add a changelog entry tomorrow. I was away. Just got back.

**Comment by bangerth** [comment]
Ping? I have a follow-up but would like to wait till this is merged.

**Comment by jppelteret** [comment]
> I think we should just merge the pull request since it fixes a bug. A changelog entry can be added later.

Let's just do as @masterleinad suggests.

**Comment by bangerth** [comment]
I've added the missing changelog entry in #13175.

**Pull request merged**
