### PR TITLE
Add a missing newline.

### PR DESCRIPTION
**Pull request by drwells**
Another very minor clang warning.

### CODE REVIEW

**Comment by jppelteret** [comment]
Gosh, this surely doesn't demand being run through the testers, does it?

**Comment by drwells** [comment]
they didn't complain before so I think not.

**Comment by jppelteret** [comment]
Let's hope that I haven't expended all of my good luck for the weekend...

**Comment by kronbichler** [comment]
I would be confident in your shoes @jppelteret - it seems that I'm the one absorbing the bad luck with premature merges this weekend... :wink:

**Pull request merged**
