### PR TITLE
Minor fixes to BoundingBox

### PR DESCRIPTION
**Pull request by simonsticko**
Fix a few comments by @bangerth related to #9831.

- Rename `create_unit_box()` to `create_unit_bounding_box()`.
- Move the function `coordinate_to_one_dim_higher` to an internal namespace.
- Minor documentation fixes.

### CODE REVIEW

**Comment by simonsticko** [comment]
> Out of curiosity, if the only place where you think where the function is used is in the `.cc` file, why not move it there?

In functionality that I'm hoping to contribute with in future, I need to call the function also outside this class.

**Comment by bangerth** [comment]
OK, sounds good! Thanks!

**Comment by kronbichler** [comment]
Now we have a failing test due to moving the function to a namespace:
```
1646/4099 Test #1648: base/coordinate_to_one_dim_higher.debug ..............................***Failed    3.77 sec
/jenkins/workspace/dealii_PR-9852/tests/base/coordinate_to_one_dim_higher.cc: In function ‘void print_what_each_coordinate_maps_to()’:
/jenkins/workspace/dealii_PR-9852/tests/base/coordinate_to_one_dim_higher.cc:36:37: error: ‘coordinate_to_one_dim_higher’ was not declared in this scope
           deallog << i << " -> " << coordinate_to_one_dim_higher<dim>(locked, i)
```
Can you please have a look?

**Comment by simonsticko** [comment]
Fixed now.

**Pull request merged**
