### PR TITLE
Fix quad numbers in MatrixFreeTools::compute_matrix()

### PR DESCRIPTION
**Pull request by nmuch**

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]

**Comment by kronbichler** [comment]
Thank you, that is a good point, we overlooked this.

**Comment by kronbichler** [comment]
Would you be willing to make a small test, e.g. using two `DoFHandler` objects (and thus a `dof_index > 0`) but only a single quadrature formula, that otherwise gets copied from some of the existing tests?

**Review by marcfehling — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]
Nice, this is a very basic test. Thank you!

**Pull request merged**
