### PR TITLE
split instantiation of VectorTools::project() for quadrature points data

### PR DESCRIPTION
**Pull request by davydden**
fixes https://github.com/dealii/dealii/issues/3388

@kronbichler @bangerth @drwells alternative solution which splits instantiations.

### CODE REVIEW

**Comment by davydden** [comment]
the failing test 
```
all-headers/lac/la_parallel_vector.h.debug ......................***Failed
```
is unrelated to this PR.

For the record
```
$ ctest -R "project_parallel_qp"
Test project /Users/davydden/libs-sources/deal.ii/builds/master_spack
    Start 264: numerics/project_parallel_qp_q_01.mpirun=3.debug
1/8 Test #264: numerics/project_parallel_qp_q_01.mpirun=3.debug .......   Passed    0.60 sec
    Start 265: numerics/project_parallel_qp_q_01.mpirun=3.release
2/8 Test #265: numerics/project_parallel_qp_q_01.mpirun=3.release .....   Passed   13.26 sec
    Start 266: numerics/project_parallel_qp_q_02.mpirun=3.debug
3/8 Test #266: numerics/project_parallel_qp_q_02.mpirun=3.debug .......   Passed   15.15 sec
    Start 267: numerics/project_parallel_qp_q_02.mpirun=3.release
4/8 Test #267: numerics/project_parallel_qp_q_02.mpirun=3.release .....   Passed   13.20 sec
    Start 268: numerics/project_parallel_qpmf_q_01.mpirun=3.debug
5/8 Test #268: numerics/project_parallel_qpmf_q_01.mpirun=3.debug .....   Passed   12.25 sec
    Start 269: numerics/project_parallel_qpmf_q_01.mpirun=3.release
6/8 Test #269: numerics/project_parallel_qpmf_q_01.mpirun=3.release ...   Passed   17.12 sec
    Start 270: numerics/project_parallel_qpmf_q_02.mpirun=3.debug
7/8 Test #270: numerics/project_parallel_qpmf_q_02.mpirun=3.debug .....   Passed   12.56 sec
    Start 271: numerics/project_parallel_qpmf_q_02.mpirun=3.release
8/8 Test #271: numerics/project_parallel_qpmf_q_02.mpirun=3.release ...   Passed   17.32 sec

100% tests passed, 0 tests failed out of 8
```

**Comment by tjhei** [comment]
Can you adjust the copyright dates please? Looks good otherwise.

**Comment by davydden** [comment]
> Can you adjust the copyright dates please? Looks good otherwise.

done.

**Comment by kronbichler** [comment]
Looks good!

**Pull request merged**
