### PR TITLE
Amend comment related to making a local copy of Trilinos MPI vector.

### PR DESCRIPTION
**Pull request by jppelteret**
Addresses (*cough*) latecomer (*cough*) suggestion in #5794.

### CODE REVIEW

**Comment by bangerth** [comment]
:-)

I think I was hoping to see some text like this in the function documentation: "In other words, calling this function is a 'collective operation' that needs to be executed by all MPI processes that jointly share @p v."

**Comment by jppelteret** [comment]
@bangerth I got confused! Since you said
> to drop the phrase ... <sentence that I hadn't written>

that you wanted me to remove the last sentence, as opposed to replacing it with what you'd stated :-) Shall I quickly add what you'd written above?

**Comment by bangerth** [comment]
Yes, if you don't mind. I think adding the term 'collective operation' is useful because it's a technical term used in all MPI literature.

OK to merge yourself if you add the sentence.

**Comment by jppelteret** [comment]
Sure, no problem!

**Comment by bangerth** [comment]
Much appreciated!

**Comment by jppelteret** [comment]
No hassles :-) Thanks for the suggestion!

**Pull request merged**
