### PR TITLE
Update PETScWrappers::NonlinearSolver

### PR DESCRIPTION
**Pull request by stefanozampini**
Improve Jacobian documentation as reported by @luca-heltai
depends on https://github.com/dealii/dealii/pull/15768 for the updates for strict PETSc error codes

### CODE REVIEW

**Review by bangerth — APPROVED** [review]

**Comment by luca-heltai** [comment]
There are some small issues here:

```
/home/runner/work/dealii/dealii/include/deal.II/lac/petsc_snes.templates.h:411:27: error: use of undeclared identifier 'PETSC_SUCCESS' [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/lac/petsc_snes.templates.h:464:27: error: use of undeclared identifier 'PETSC_SUCCESS' [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/lac/petsc_snes.templates.h:492:27: error: use of undeclared identifier 'PETSC_SUCCESS' [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/lac/petsc_snes.templates.h:522:27: error: use of undeclared identifier 'PETSC_SUCCESS' [clang-diagnostic-error]
/home/runner/work/dealii/dealii/include/deal.II/lac/petsc_snes.templates.h:367:27: error: use of undeclared identifier 'PETSC_SUCCESS' [clang-diagnostic-error]
```

and the compilation in parallel fails:

```
/__w/dealii/dealii/include/deal.II/lac/petsc_snes.templates.h:367:27: error: ‘PETSC_SUCCESS’ was not declared in this scope; did you mean ‘EXIT_SUCCESS’?
  367 |       PetscFunctionReturn(PETSC_SUCCESS);
      |                           ^~~~~~~~~~~~~
/__w/dealii/dealii/include/deal.II/lac/petsc_snes.templates.h: In lambda function:
/__w/dealii/dealii/include/deal.II/lac/petsc_snes.templates.h:411:27: error: ‘PETSC_SUCCESS’ was not declared in this scope; did you mean ‘EXIT_SUCCESS’?
  411 |       PetscFunctionReturn(PETSC_SUCCESS);
      |                           ^~~~~~~~~~~~~
/__w/dealii/dealii/include/deal.II/lac/petsc_snes.templates.h: In lambda function:
/__w/dealii/dealii/include/deal.II/lac/petsc_snes.templates.h:464:27: error: ‘PETSC_SUCCESS’ was not declared in this scope; did you mean ‘EXIT_SUCCESS’?
  464 |       PetscFunctionReturn(PETSC_SUCCESS);
      |                           ^~~~~~~~~~~~~
/__w/dealii/dealii/include/deal.II/lac/petsc_snes.templates.h: In lambda function:
/__w/dealii/dealii/include/deal.II/lac/petsc_snes.templates.h:492:27: error: ‘PETSC_SUCCESS’ was not declared in this scope; did you mean ‘EXIT_SUCCESS’?
  492 |       PetscFunctionReturn(PETSC_SUCCESS);
      |                           ^~~~~~~~~~~~~
/__w/dealii/dealii/include/deal.II/lac/petsc_snes.templates.h: In lambda function:
/__w/dealii/dealii/include/deal.II/lac/petsc_snes.templates.h:522:27: error: ‘PETSC_SUCCESS’ was not declared in this scope; did you mean ‘EXIT_SUCCESS’?
  522 |       PetscFunctionReturn(PETSC_SUCCESS);
      |                           ^~~~~~~~~~~~~
```

**Comment by stefanozampini** [comment]
Needs to be rebased on master

**Review by luca-heltai — APPROVED** [review]
Thanks for clarifying Stefano!

**Comment by stefanozampini** [comment]
Tests are clean, this can be merged

**Pull request merged**
