### PR TITLE
Typos corrected in step-3

### PR DESCRIPTION
**Pull request by mathgirl**

### CODE REVIEW

**Comment by drwells** [comment]
Yup, these look good to me :)

Welcome to the list of contributors to deal.II!

**Comment by drwells** [comment]
Since this is just improves to the documentation I went ahead and merged it.

Many people (including myself) got started with the project by making pull requests similar to this one. I hope that you are willing to continue contributing to the library!

**Comment by bangerth** [comment]
Indeed -- every new contributor to deal.II is exciting!

**Comment by tjhei** [comment]
Thanks for the fixes and welcome to the project, Emma!

> I hope that you are willing to continue contributing to the library!

Working with her, I am hopeful about that. :smile:

**Comment by mathgirl** [comment]
Yes I am excited!!!:)

**Pull request merged**
